### ISSUE TITLE
[BUG] - No options to add more breakpoints to theme!

### ISSUE THREAD

**Issue by nekmart** [nextui-org/nextui#1000]
### Describe the bug

Hello, I am trying to nextui. But After reading whole docs and apply, I find a big issue with nextui. That is, it comes with fewer `breakpoints` for responsiveness.

```
 xs: '650px',
 sm: '960px',
 md: '1280px',
 lg: '1400px',
 xl: '1920px'
```

But we are not able to add more breakpoints here, But it should be done, for responsive design. I hope in stable version you add options to nextui?

### Steps to Reproduce the Bug or Issue

nothing

### Expected behavior

As a frontend developer, I think it is very necessary things for adding custom more and more breakpoints.

### Operating System Version

macOS

### Browser

Chrome

**Comment by leogilmour** [comment]
I agree, this is causing a small nightmare for us too.
In my default theme, I added this:
```breakpoints: {
      xs: "650px",
      sm: "768px",
      md: "960px",
      lg: "1280px",
      xl: "1400px",
      "2xl": "1920px",
    },```
    

But it doesn't do anything to the media queries :(

**Comment by jrgarciadev** [comment]
Hey @Moe03  sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2) and use TailwindCSS custom breakpoints https://tailwindcss.com/docs/responsive-design#using-custom-breakpoints
