### ISSUE TITLE
[BUG] - Components/Navbar

### ISSUE THREAD

**Issue by SitoNumbis** [nextui-org/nextui#1004]
### Describe the bug

I was testing the "Hide on Scroll" section, then after scroll down the Navbar hides, that's ok, but when I scroll up the Navbar shows up cutted half vertically.  This issue is happening only in the Hide on Scroll section in the Docs page. https://nextui.org/docs/components/navbar#hide-on-scroll. 

### Your Example Website or App

https://nextui.org/docs/components/navbar#hide-on-scroll

### Steps to Reproduce the Bug or Issue

1 - Go to Navbar in the Docs of the @nextui-org page
2 - Scroll to "Hide on Scroll" section
3 - Scroll down in the preview section to hide the Navbar
4 - Scroll up in the preview section to show the scroll

### Expected behavior

After scroll up the Navbar should show normally, not cutted half vertically.

### Screenshots or Videos

![Screenshot from 2023-01-12 16-26-12](https://user-images.githubusercontent.com/40501794/212184716-7bc4683e-01c6-419e-b80f-3039a3a0e772.png)

### Operating System Version

Linux

### Browser

Chrome

**Comment by hamza4600** [comment]
@SitoNumbis  this issue is caused by transition property applies on the nav 
`transition: transform 400ms ease 0s;`
if we remove this  it work fine

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).

https://nextui.org/docs/components/navbar#hide-on-scroll
