### ISSUE TITLE
[BUG] - Combining this with styled-components breaks themes

### ISSUE THREAD

**Issue by Pixelatex** [nextui-org/nextui#1014]
### Describe the bug

Setting the compiler to "styledComponents: true" in your next.config.js will break theming completely. The tokens are no longer replaced. (next v13.x)

### Steps to Reproduce the Bug or Issue

1. Setup a basic project with atleast one theme token in there.
2. Verify it works
3. Add the styled components dependencies + set the compiler to compile for styled in the config
4. The token no longer works

### Expected behavior

I would expect some way for this library to play nice together with styled-components considering it's a widely adopted styling library and it's supported by nextjs out of the box.

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Pixelatex  sorry for the delay, please upgrade to [V2](https://nextui.org/blog/nextui-v2)
