### ISSUE TITLE
[BUG] - Table Columns Count don't match and won't allow table to render

### ISSUE THREAD

**Issue by himrocks33** [nextui-org/nextui#1017]
### Describe the bug

When I attempt to render a table I get an error saying 'Error: Cell count must match column count. Found 2 cells and 4 columns.'

But I have 2 cells in the row and 2 columns. 

### Steps to Reproduce the Bug or Issue

This is an example I grabbed off the official docs.  It will not render see screen shot below.
`        <Table
          lined
          headerLined
          shadow={false}
          selectionMode="multiple"
          aria-label="Example static collection table"
          css={{
            height: "auto",
            minWidth: "100%",
          }}
        >
          <Table.Header>
            <Table.Column>NAME</Table.Column>
            <Table.Column>ROLE</Table.Column>
          </Table.Header>
          <Table.Body>
            <Table.Row>
                <Table.Cell>NAME</Table.Cell>
                <Table.Cell>ROLE</Table.Cell>
            </Table.Row>
          </Table.Body>
        </Table>`

### Expected behavior

Expect the table to render

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/32065815/213476186-1dec181c-ed9c-445f-97f5-bcdeb85272be.png)

![image](https://user-images.githubusercontent.com/32065815/213476297-c7dbcc19-ca3f-4879-9109-ba533252bd0f.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by kevinschaich** [comment]
Same issue here

**Comment by eialanjones** [comment]
same

**Comment by eialanjones** [comment]
A workaround is using the dynamic table approatch

**Comment by himrocks33** [comment]
@eialanjones could you elaborate please. Maybe include a code snippet if you have one?
Thanks

**Comment by ryangibbsnc** [comment]
➕ to same issue

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).

https://nextui.org/docs/components/table
