### ISSUE TITLE
[Feature Request] Adobe XD / Figma components

### ISSUE THREAD

**Issue by babycommando** [nextui-org/nextui#1018]
### Is your feature request related to a problem? Please describe.

As you design serious applications with a Ui library, it is natural to make a mockup before putting it into production, to validate, etc. It would be very nice if we could get some packs ready to use on prototyping softwares.

### Describe the solution you'd like

Public shared files for figma and AdobeXd with the components.

### Describe alternatives you've considered

Translating the components by hand? hardcore.

**Comment by jguddas** [comment]
Related https://github.com/nextui-org/nextui/discussions/176.

**Comment by jrgarciadev** [comment]
https://www.figma.com/community/file/1267584376234254760/NextUI-Figma-Kit-(Community)
