### ISSUE TITLE
[BUG] - Buttons' text appears over collapsed navbar

### ISSUE THREAD

**Issue by mykebueno** [nextui-org/nextui#1020]
### Describe the bug

Collapsed navbar will display the text from the buttons which are below the div with className **.nextui-c-iTPCAT-dusCa-isOpen-true**.
This is due to **z-index** property's value which is set to **var(--nextui-zIndices-2)**. I managed to solve this by setting this property's value to "unset" when the navbar is collapsed as this could interfere with other functionalities if I was to set this value to the whole document and not only specifically when the navbar is collapsed.  

### Steps to Reproduce the Bug or Issue

1. Set up a navbar with Navbar.Toggle and Navbar.Collapse components added to the navbar.
2. Add button(s) component(s) so that they are displayed inside the 100vh of the window.
3. Collapse the navbar.
4. You should see the text from the button(s) component(s) overlapping the collapsed navbar.

### Expected behavior

The text from buttons should not appear over the collapsed navbar.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/71532159/213872090-b768471f-eecc-4c56-b41f-1387f49ed9d0.png)
![image](https://user-images.githubusercontent.com/71532159/213872097-22720dff-0c6b-4af6-8b7a-2dfcdf3b4467.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by valerius21** [comment]
Same on macOS, Brave/Firefox/iOS w/ Vite+React

**Comment by valerius21** [comment]
Another workaround is by setting the zIndex of your navbar component to `201`, since the default value for ` var(--nextui-zIndices-2)` seems to be `200`.

Ex.

`<Navbar isBordered={true} variant={'sticky'} css={{ zIndex: 201 }}>`

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay, please upgrade to [V2](https://nextui.org/blog/nextui-v2)
