### ISSUE TITLE
[BUG] - Card provides wrong type for "as" prop

### ISSUE THREAD

**Issue by hmbrg** [nextui-org/nextui#1026]
### Describe the bug

The current `as` prop of the `Card` component is `as?: keyof JSX.IntrinsicElements;` but it should be `As<any>` to allow components to be passed.

This is how most other Next UI components do it.

For example, this would allow the Card component to be used as a Next.js Link like this:
```javascript
import Link from "next/link"

<Card as={Link} />
```

### Steps to Reproduce the Bug or Issue

1. Try to pass a component to the `as` prop.
2. Get a type error.

### Expected behavior

No error.

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @hmbrg  sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2) and test this again.
