### ISSUE TITLE
[BUG] Korean(Hangul) consonants are separated when using react-hook-form

### ISSUE THREAD

**Issue by uhgenie7** [nextui-org/nextui#1028]
### Describe the bug

I'm a Korean developer, I'm using react-hook-form and I'm using it with nextui's Input.

If I use useController of react-hook-form, consonants and vowels of korean(Hangul) are separated when I input korean(Hangul) into Input.

The reason I think this is a nextui issue rather than a react-hook-form issue is that it happened after I upgraded the nextui version to beta.11.

### Steps to Reproduce the Bug or Issue

1. import package...
```
import { useForm, useController } from "react-hook-form";
import { Input } from "@nextui-org/react";
```

2. use useController

```js

  const { field: idField } = useController({
    control,
    name: "id",
    rules: {
      required: {
        value: true,
        message: "ID_REQUIRED"
      }
    }
  });

```
3. register controller for Input
```
 <Input
            {...idField}
            clearable
            label="아이디"
            placeholder="ID_REQUIRED"
            color="primary"
            fullWidth
          />
```

### Expected behavior

When I input korean, I expected normal korean to be input like when using 1.0.0-beta.10
(ex: 아이디)

but consonants and vowels are separated in 1.0.0-beta.11.
(ex: ㅇㅏㅇㅣㄷㅣ)

### Screenshots or Videos

**success**
- [beta-10 codesandbox](https://codesandbox.io/s/nextui-react-hook-form-beta-10-x2rwnr?file=/src/index.js)

![스크린샷 2023-01-27 오전 10 29 25](https://user-images.githubusercontent.com/72803184/214992101-32293468-d659-4a8a-8b32-d19adadcd8ad.png)

**issue**
- [beta-11 codesandbox](https://codesandbox.io/s/nextui-react-hook-form-beta-11-s85zdw?file=/src/index.js)

![스크린샷 2023-01-27 오전 10 29 40](https://user-images.githubusercontent.com/72803184/214992109-bad5b9a6-d4d4-49c3-8df0-e3d918a05ba0.png)

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
