### ISSUE TITLE
[Feature Request] Add className prop to enable full, easier customizablility.

### ISSUE THREAD

**Issue by Moe03** [nextui-org/nextui#1029]
### Is your feature request related to a problem? Please describe.

I don't understand why there is no className prop that is passed to the components, using css prop while also using tailwind makes my stomach hurt, I find this library very promising, simple and clean but without className prop and continuously using css to quickly customize my application is not efficient.

### Describe the solution you'd like

Adding something like this is going to be very simple, I also know that I can customize the theme from the docs but this also doesn't solve my problem where I always need to add micro adjustments.

### Describe alternatives you've considered

Adding tailwind support would be awesome, but having at least className prop is just essential for easier adjustments.

**Comment by jrgarciadev** [comment]
Hey @Moe03  sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2) we added multiple ways to customize components, including `extendVariants` functions, global theme customization, `classNames` property and more.

Please check the customization section in V2 docs

https://nextui.org/docs/customization/theme
