### ISSUE TITLE
[Feature Request] Add documentation for Next13 SSR

### ISSUE THREAD

**Issue by Mbensler** [nextui-org/nextui#1031]
### Is your feature request related to a problem? Please describe.

No SSR documentation or examples for Next13

### Describe the solution you'd like

Currently there is only documentation on how to setup SSR in Next12 but not 13.

### Describe alternatives you've considered

Currently it seems SSR only works in the pages directory

**Comment by jrgarciadev** [comment]
NextUI v2 now offers both setup instructions + templates, please check https://nextui.org/docs/frameworks/nextjs
