### ISSUE TITLE
[Feature Request] Allow focus outside button on Dropdown close

### ISSUE THREAD

**Issue by steviesocks** [nextui-org/nextui#1033]
### Is your feature request related to a problem? Please describe.

When using Tooltip on a Dropdown Button, focus always gets returned to the Button on Dropdown close and results in the Tooltip being visible. This is typically not a desired behavior.

### Describe the solution you'd like

It would be great if there were a property on Dropdown to allow focus to go wherever a user clicks outside of the Dropdown.

For example:
1. Clicking on Dropdown Button opens the Dropdown.
2. Clicking outside the Dropdown Menu closes the Dropdown and sets focus wherever the user clicked.

### Describe alternatives you've considered

I've tried a combination of events: using shouldCloseOnInteractOutside to set an HTMLElement ref, then using onFocus on the Dropdown Button component to set focus on the ref.

**Comment by jrgarciadev** [comment]
Please upgrade to v2 this is no longer happening, unless you're navigating through the keyboard

**Comment by nanwy** [comment]
How can I close the navigation using keyboard settings? In my nextui-org/react version 2.1.10, clicking outside does not close the dropdown, but pressing 'Esc' can close it. How can I achieve this?@jrgarciadev

**Comment by nanwy** [comment]
> How can I close the "navigating through the keyboard" settings? In my nextui-org/react version 2.1.10, clicking outside does not close the dropdown, but pressing 'Esc' can close it. How can I achieve this?@jrgarciadev
> 
>  9.10.mp4

that iuuse was fixed in version 2.1.12
