### ISSUE TITLE
[BUG] - Server Rendering issue

### ISSUE THREAD

**Issue by neelhabib** [nextui-org/nextui#1038]
### Describe the bug

I am rendering a ssr page list with 100 cards. so when I mouse hover to the page link or direct go to the link, on the console, its logging 100 times warning.
`**When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.**`

I am configured everything from the docs. this is my _app.js file

```
import "../styles/globals.css";
import { store } from "../Redux/store";
import { Provider } from "react-redux";
import { NextUIProvider } from "@nextui-org/react";
import NAV from "../Component/NavBar/Nav";

function MyApp({ Component, pageProps }) {
  return (
    <NextUIProvider>
      <Provider store={store}>
          <NAV />
        <Component {...pageProps} />
      </Provider>
    </NextUIProvider>
  );
}

export default MyApp;
```
and this is my _document.js file

```
import React from "react";
import Document, { Html, Head, Main, NextScript } from "next/document";
import { CssBaseline } from "@nextui-org/react";

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return {
      ...initialProps,
      styles: React.Children.toArray([initialProps.styles]),
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>{CssBaseline.flush()}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

### Your Example Website or App

https://oxy-nextui.vercel.app/random-word-generator

### Steps to Reproduce the Bug or Issue

when reloading the page, the error logging warning 100 times to the console in dev mode and prod mode

### Expected behavior

there should be no error

### Operating System Version

Linux

### Browser

Chrome

**Comment by CookieHax** [comment]
https://github.com/nextui-org/nextui/issues/779

**Comment by UGoingNoWhereBoy** [comment]
npm i @react-aria/ssr

import {SSRProvider} from '@react-aria/ssr';
<SSRProvider>
</SSRProvider>

this should fix it, it worked for me

**Comment by st4ng** [comment]
[Adding this to my package.json fixed it:](https://github.com/nextui-org/nextui/issues/779#issuecomment-1464963799)

```
"resolutions": {
    "@react-aria/ssr": "^3.4.1"
 }
```
