### ISSUE TITLE
[BUG] - Components/Tooltip

### ISSUE THREAD

**Issue by reversoid** [nextui-org/nextui#1039]
### Describe the bug

Tooltip doesn`t show up when it is in Modal component

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-euvjp6?file=/App.js:0-422

### Steps to Reproduce the Bug or Issue

1. Create tooltip component inside Modal
2. Hover on it

### Expected behavior

As a user, I expect tooltip to show up, but it doesn`t happen

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by Othman2001** [comment]
@reversoid 
So after some time of debugging the issue is simply that next UI Modal component needs to take postion:fixed property, I have added it to the css class inside the developer tools, But i have tried to add it in the next ui code but i struggled a little.

**Comment by khashayarghajar** [comment]
it's because of z-index

**Comment by bilal2912112** [comment]
@reversoid Basically it is hovering behind the box if you remove the model.Body then you will see the btton on the left corner and when you hover it actually display behind the model

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
