### ISSUE TITLE
Avatar component doesn't resize the image

### ISSUE THREAD

**Issue by yuriwithowsky** [nextui-org/nextui#104]
**Describe the bug**
I have an image that is much larger than the size of the Avatar component and it doesn't resize the image.

**Steps to reproduce**
When adding a very large image in the Avatar component

**Expected behaviour**
The image needs to be resized based on the size of the Avatar component.

**Screenshots**
Actual:
![Captura de Tela 2021-10-30 às 10 26 07](https://user-images.githubusercontent.com/6625004/139534538-50044691-363f-49c1-b497-5593f7432a5c.png)

Expected:
![Captura de Tela 2021-10-30 às 10 26 35](https://user-images.githubusercontent.com/6625004/139534542-63f1b70b-36ab-4b6d-93e1-7f7e674b3f99.png)

..and the code:
![Captura de Tela 2021-10-30 às 10 28 00](https://user-images.githubusercontent.com/6625004/139534571-ab2ce7e9-8bae-43c6-b852-6406cdae7980.png)

**Environment / Context**
- Desktop or Mobile? Desktop
- Operating System: Mac OS Big Sour
- Browser and version: Chrome 95 and Safari 14
- Device: MacBook Air

**Comment by jrgarciadev** [comment]
Thanks for reporting it @yuriwithowsky 🙌🏻
