### ISSUE TITLE
The NextUI default font-family overread my default font 

### ISSUE THREAD

**Issue by yassersaidi** [nextui-org/nextui#1048]
### Describe the bug

I'm using a custom font from google fonts, but it can't appear because the NextUI provide default font-family variable in the :root  
the name of the var is : --nextui-fonts-sans and --nextui-fonts-mono.

Please fix the problem and let the NextUI use the default fonts of the app.

### Steps to Reproduce the Bug or Issue

1. Go to DevTools
2. Then inspect the root element (<html>)
3. you will see the defined vars in the selector (:root, .nextui-t-bzCiFt) 
4. when unchecked the vars --nextui-fonts-sans or --nextui-fonts-mono. the default font work again.

### Expected behavior

I expect to use my own fonts in my app, not the ones that came with the library package 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/39775379/219813212-e94eec19-ad05-4f03-8b15-ba03b9d90534.png)

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by yassersaidi** [comment]
possible way to fix the issue in my app:
i had to go to the glabal.css because i'm working with Tailwindcss, and add this styles to override the default one:
`:root{
    --nextui-fonts-sans: Harmattan, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji" !important;
    font-family: var(--nextui-fonts-sans);
  }
`

**Comment by NekoWings** [comment]
same problem
