### ISSUE TITLE
[BUG] - input field is overflowing when set leftLabel

### ISSUE THREAD

**Issue by ParkDyel** [nextui-org/nextui#1052]
### Describe the bug

input field is overflowing when setting leftLabel. 

am I wrong?

may be input have a width 100%

### Steps to Reproduce the Bug or Issue

```
<Input
  labelLeft="left label"
  type="number"
  underlined
  required
  {...register(`${code}.min.count`, { required: true })} // never mind, just for react-hook-form
/>
```

### Expected behavior

not overflowing when I set left-label

### Screenshots or Videos

<img width="319" alt="스크린샷 2023-02-23 오후 9 19 08" src="https://user-images.githubusercontent.com/13329748/220903881-213de58f-49f2-4697-8011-ac1a9f566e67.png">

<img width="729" alt="스크린샷 2023-02-23 오후 9 20 21" src="https://user-images.githubusercontent.com/13329748/220904149-6629c2ed-1014-4322-ab83-324b06c311c8.png">

### Operating System Version

maxOS

### Browser

Safari

**Comment by janathanni** [comment]
did you solve this? or not can you show your code with css?

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2) 

https://nextui.org/docs/components/input
