### ISSUE TITLE
[Feature Request] Integration for Next.js 13 with App directory feature

### ISSUE THREAD

**Issue by AlphaByte-RedTeam** [nextui-org/nextui#1053]
### Is your feature request related to a problem? Please describe.

The latest Next.js version is in version 13. Adding support for Next.js 13 would be great because it helps a lot with SEO and performance improvement.

### Describe the solution you'd like

As a user, I expected to always use the latest version of the technology. The new tech always comes with a lot of improvements. And so do NextUI; it helps me build a UI beautifully and easily.

### Describe alternatives you've considered

There is no alternative.

**Comment by lhz516** [comment]
It already works with Nextjs 13. A few things to know:

1. The `NextUIProvider` needs to be in a separated component, and be used in the layout like `<Provider>{children}</Provider>`
2. The server component won't work for Next UI components. When you fetch data in a server component, you can pass the data into a child component which has `use client` and Next UI components.

**Comment by vacavaca** [comment]
AFAIK app dir is not fully supported by NextUI yet, for example NextUI cannot poperly flush its styles server-side as it did in Next 12 causing FOUC. Also I cannot see the reason to not render, for example, static content using NextUI server side. So the feature request still holds.

**Comment by AlphaByte-RedTeam** [comment]
> It already works with Nextjs 13. A few things to know:
> 
> 1. The `NextUIProvider` needs to be in a separated component, and be used in the layout like `<Provider>{children}</Provider>`
> 2. The server component won't work for Next UI components. When you fetch data in a server component, you can pass the data into a child component which has `use client` and Next UI components.

It's great to know NextUI already works with Next.js v13. Thank you for the information.

**Comment by eloekset** [comment]
Does anyone know of a working sample application with NextJS 13.4.2 and NextUI? It would be great if someone could share how to set this up now, since all current getting-started-documentation is outdated.

**Comment by eloekset** [comment]
> It already works with Nextjs 13. A few things to know:
> 
> 1. The `NextUIProvider` needs to be in a separated component, and be used in the layout like `<Provider>{children}</Provider>`

This is the current layout.tsx with NextJS 13.4.2. Where should I put the NextUI Provider element, and how should that separate component be written?
```
import './globals.css'
import { Inter } from 'next/font/google'
import { CssBaseline } from "@nextui-org/react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>{CssBaseline.flush()}</head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
```

**Comment by eloekset** [comment]
Looks like I'm finally getting this right now:
![image](https://github.com/nextui-org/nextui/assets/791721/bee10922-ba3f-4741-abe7-9841f98067ae)

I don't have any Provider.tsx file, but a page.tsx in addition to that layout.tsx file:
![image](https://github.com/nextui-org/nextui/assets/791721/be336103-db7e-4415-864a-ad3fea61a282)

Other pages inside the app folder, should get a folder for the name of the route, and that folder should get a file called page.tsx:
![image](https://github.com/nextui-org/nextui/assets/791721/9281ea4c-28fd-4c3a-8ca6-65a27093647c)

**Comment by jhimelymendoza** [comment]
hi @eloekset I have followed your example and i Ialways get this error in my  web console
![image](https://github.com/nextui-org/nextui/assets/54819815/33896423-73d3-43d6-be6f-9d45fa6c52cb)

Can you help me?

**Comment by eloekset** [comment]
I'm no expert. My project is here if you want to copy from it. I haven't been working on it for a few weeks now, so things may have changed again in the meantime.
https://github.com/blog-eivindgl-com/my-portfolio

**Comment by jrgarciadev** [comment]
Please use v2 https://nextui-docs-v2.vercel.app/docs/frameworks/nextjs, it is still under development but it supports Next.js 13 and app directory much better, here's the app directory template with NextUI v2

https://github.com/nextui-org/next-app-template
