### ISSUE TITLE
[BUG] - 'theme object' page URL 404: nextUI.org

### ISSUE THREAD

**Issue by b0id** [nextui-org/nextui#1055]
### Describe the bug

Unable to read 'theme object' docs.

### Your Example Website or App

Nextui.org

### Steps to Reproduce the Bug or Issue

1. Go to [https://github.com/nextui-org/nextui/blob/main/apps/docs/content/docs/theme/default-theme.mdx](url)
2. Click on 'theme object'
3. Return 404

### Expected behavior

Would expect to read about the theme object.

Let me know redirect and I will submit a PR.

### Operating System Version

Ubuntu VM

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @b0id the markdown files weren't built to be read directly on Github, please read the docs in the documentation site https://nextui.org/docs/guide/getting-started#theme-object
