### ISSUE TITLE
Proposing for a navbar, sidebar

### ISSUE THREAD

**Issue by pgn-mahbub** [nextui-org/nextui#106]
**Is your component proposal related to a problem? Please describe.**
I propose updating a navbar or a sidebar as like vuesax's sidebar. 

**Describe the solution you'd like**
A few months ago I tried for a sidebar with 100% responsiveness. Although I have done the component I'm not satisfied. That is the reason I felt it would be best for us. I'll include those links or details you need.

**Describe alternatives you've considered**
Have you considered iterating an existing component?
I've seen a component on Vuesax's docs. Which is forced me to write the issue. 
[Sidebar Component](https://vuesax.com/docs/components/Sidebar.html#default)

**Additional context**
I've included the component's link. You may check this out. 

thanks a lot to **NextUI team**

**Comment by jrgarciadev** [comment]
Hey @pgn-mahbub thanks for your proposal, the Sidebar issue it's already created here -> #90
