### ISSUE TITLE
[BUG] - Input cursor jumps to the end of string for any input

### ISSUE THREAD

**Issue by richtone** [nextui-org/nextui#1064]
### Describe the bug

After updating package from 10 to 11 all controlled <Input /> components behave in unexpected way - after any input the input cursor (caret) jumps to the end of input.

All of them are using standard value={value} onChange={e=> setValue(e.target.value)}.

Happens in Chrome, Firefox, Edge on Windows and Chrome, Firefox, Safari on MacOS

### Your Example Website or App

https://stackblitz.com/edit/nextjs-e3722z?file=pages/index.js

### Steps to Reproduce the Bug or Issue

1. Move cursor between "e" and "v" letters

![image](https://user-images.githubusercontent.com/6845025/223690920-0c5da8a3-93ca-4b43-953a-f5183dff0ce1.png)

2. Press "q"

![image](https://user-images.githubusercontent.com/6845025/223691038-4f7a17c3-6c21-4ec4-a05d-04de80b0f307.png)

Same things happens with any other input such as deleting letter (both DEL and BACKSPACE)

### Expected behavior

Normal behaviour.

### Operating System Version

Windows, MacOS

### Browser

Chrome, Firefox, Edge, Safari

**Comment by Yukiniro** [comment]
Here is a same issue. #975

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).

https://nextui.org/docs/components/input
