### ISSUE TITLE
[Feature Request] Add Storybook

### ISSUE THREAD

**Issue by khashayarghajar** [nextui-org/nextui#1066]
### Is your feature request related to a problem? Please describe.

Add Storybook for better **UI development**, **testing**, and **documentation**

### Describe the solution you'd like

none

### Describe alternatives you've considered

[Fluent UI](https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/components-image--default)
[Chakra UI](https://chakra-ui.netlify.app/?path=/story/accordion--default)
[Storefront UI](https://docs.storefrontui.io/v1/?path=/docs/utilities-transitions--slide-left)

### Screenshots or Videos

`WordPress Gutenberg`

![Screenshot 2023-03-09 120608](https://user-images.githubusercontent.com/78317297/223966999-c47597a7-1478-4c6c-999e-b13a44b83486.jpg)

`Audi UI React`

![Screenshot 2023-03-09 120608](https://user-images.githubusercontent.com/78317297/223967362-d2ba4af6-b3d0-4e22-a91c-4d952f9d9bee.jpg)

`Grafana UI`

![Screenshot 2023-03-09 121326](https://user-images.githubusercontent.com/78317297/223967763-df38c537-784a-4a15-9168-e536be7ee8ae.jpg)

**Comment by jrgarciadev** [comment]
Hey we already have storybook

V1 -> storybook.nextui.org
V2 -> storiesv2.nextui.org
