### ISSUE TITLE
[BUG] - Layout/Grid

### ISSUE THREAD

**Issue by Yuri-Lima** [nextui-org/nextui#1068]
### Describe the bug

TS-Error
The signature '(callback: ((this: MediaQueryList, ev: MediaQueryListEvent) => any) | null): void' of 'media.addListener' is deprecated.ts(6387)
lib.dom.d.ts(9525, 9): The declaration was marked as deprecated here.

### Your Example Website or App

None - Dev

### Steps to Reproduce the Bug or Issue

1. Got to https://nextui.org/docs/layout/grid
2. Scroll down to [Responsive](https://nextui.org/docs/layout/grid#responsive)
3. just copy and paste as a TS project.

### Expected behavior

No Deprecated.

### Screenshots or Videos

![Capture-1](https://user-images.githubusercontent.com/9964218/224276675-dcf83c0c-d8ae-4b25-b593-a202808ed0b7.PNG)

### Operating System Version

Linux

### Browser

Chrome

**Comment by Yuri-Lima** [comment]
A possible solution for that issue:
Replace:
`media.addListener(updateTarget);`
To
`media.addEventListener('change', updateTarget);`

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2). Use TailwindCSS Grid Layout + Responsive design https://tailwindcss.com/docs/responsive-design
