### ISSUE TITLE
Alphabetize sidebar

### ISSUE THREAD

**Issue by carlosriveroib** [nextui-org/nextui#107]
**Describe the bug**
Sidebar isn't alphabetize. This makes it difficult to find components in Sidebar, especially as it grows and there are many more of them.

**Steps to reproduce**
1. See components sidebar to check it isn't alphabetize

**Expected behaviour**
Sidebar should be alphabetize

**Comment by jrgarciadev** [comment]
Hey @carlosriveroib the sidebar it's intentionally sorted based on more attractive components, latest components, time spent on that component, etc.. this will remain until the NextUI has the beta version, then I will sort it by name and sub-categories 🙋🏻‍♂️
