### ISSUE TITLE
[BUG] - Navbar css background not working

### ISSUE THREAD

**Issue by lebe24** [nextui-org/nextui#1071]
### Describe the bug

```Js
<Navbar css={{
        marginTop:'$50',
        backgroundColor: '$black'
    }}  variant="sticky" >
        <Navbar.Brand>
          <Text b color="blue" hideIn="xs">
            ACME
          </Text>
        </Navbar.Brand>
        <Button>
            click
        </Button>
    </Navbar>
````

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-h5g98i?file

### Steps to Reproduce the Bug or Issue

-  Nextui doc
- navbar section
- style the navbar tag

### Expected behavior

Expected the background-color to change with provided color

### Screenshots or Videos

<img width="732" alt="Screenshot 2023-03-14 at 22 08 34" src="https://user-images.githubusercontent.com/31292486/225136759-ba87d2f3-8406-43bd-a9bd-72ebd9c361e9.png">

### Operating System Version

-OS[MAC]

### Browser

Chrome

**Comment by munnokd** [comment]
Cam I work on this issue?

**Comment by Dodger23** [comment]
@lebe24 
Hi there, can't really understand what is exactly the problem, the `Navbar` css is working

![image](https://user-images.githubusercontent.com/60031675/235565579-10ac7fd6-571a-4051-b73d-52799fcc634a.png)

If you mean that `Navbar Container` is not inheriting the `background-color` from the `Navbar` then you just need to pass `ContainerCss` prop to the `Navbar` with the desired css styling

![image](https://user-images.githubusercontent.com/60031675/235565983-0fa15b22-446f-4b55-8039-fa735239252e.png)

**Comment by itsjmendez** [comment]
Hi @lebe24 - adding to @Dodger23 I encountered no issues when changing the background color of the Navbar using tailwind. 👌

![image](https://github.com/nextui-org/nextui/assets/25671632/471e2b01-353c-4196-acb4-f4098dcdff06)

**Comment by lebe24** [comment]
Hi @itsjmendez can you host your code i want to checkout how nextui works with tailwind
