### ISSUE TITLE
Adding {CssBaseline.flush()} in _document.js makes styles dissapear 

### ISSUE THREAD

**Issue by vpaul18** [nextui-org/nextui#1079]
### Describe the bug

This is my `_document.js`.

```
import React from "react";
import Document, { Html, Head, Main, NextScript } from "next/document";
import { CssBaseline } from "@nextui-org/react";

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return {
      ...initialProps,
      styles: React.Children.toArray([initialProps.styles]),
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>{CssBaseline.flush()}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

It seems that it removes all the styling from all NextUI components. Removing the `{CssBaseline.flush()}` in the `<Head/>` tag solves it but im not sure what are the consequences. 

How should I go about this ?

Thanks!

### Steps to Reproduce the Bug or Issue

1 .follow the getting started docs
2. render any NextUI component

### Expected behavior

In the official 'Getting started' it is stated to add this function. Adding it removes all the CSS. I expect that not to happen.

### Operating System Version

Windows 10

### Browser

Chrome

EDIT: it seems like there are conflicts with tailwind css.

**Comment by getlaurekt** [comment]
Ye I just installed nextui I wanted to use it in t3 stack, but the styles are not working, the button that i tried to showcase in the browser is there, but without any styles expect for the ripple-like effect after clicking, so i will have to wait untill it wont be fixed cause i have the same problem ;p

**Comment by vpaul18** [comment]
@getlaurekt  Seems like there's a clash with `@tailwind base`. Just add 
`corePlugins: {
    preflight: false,
 }` 
to your tailwind config.

**Comment by elhe26** [comment]
> `corePlugins: { preflight: false, }`
> to your tailwind config.

Where exactly?

After `@tailwind base;` or inside 

```css
@layer base {
  corePlugins: { preflight: false, }
}
```

**Comment by vpaul18** [comment]
@elhe26 here , in your tailwind.config.js `module.exports = {
  content: [
  ....
  ],
  theme: {
    extend: {
      ...
    },
  },
  plugins: [],
  corePlugins: { preflight: false, }
}`
