### ISSUE TITLE
[BUG] - Dropdown Menu in Navbar changed position when scroll

### ISSUE THREAD

**Issue by nguyen227** [nextui-org/nextui#1100]
### Describe the bug

When I use Dropdown Component with User Component inside. 
Dropdown Menu is shown when clicked but its position didn't fix when scrolling

### Your Example Website or App

https://codesandbox.io/s/8isf4c?file=/App.js&from-sandpack=true

### Steps to Reproduce the Bug or Issue

Scrolling

### Expected behavior

Expected like this: 
![image](https://user-images.githubusercontent.com/60183659/233043383-1e54c758-2adc-4e88-b32b-00ad5b377596.png)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/60183659/233042472-71122bbc-7e32-4693-86ca-3e5377c2ada3.png)
![image](https://user-images.githubusercontent.com/60183659/233044912-dbb8e0e6-55a3-414b-bacf-3ee041ae474c.png)
![image](https://user-images.githubusercontent.com/60183659/233044656-465906b8-78db-431b-8ee8-b22beda4b4c2.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by mikehesse** [comment]
Hey,

Why you closed this one? I encountered the same issue with an fixed Navbar from NextUI.

Did you find a work around? If so i would be glad if you share your approach :-)

**Comment by nguyen227** [comment]
> Hey,
> 
> Why you closed this one? I encountered the same issue with an fixed Navbar from NextUI.
> 
> Did you find a work around? If so i would be glad if you share your approach :-)

You just need to pass "position: fixed" inside containerCss in Dropdown.Menu
![image](https://github.com/nextui-org/nextui/assets/60183659/9c31e15d-a334-483d-8dd6-8f29497d97c6)

**Comment by mikehesse** [comment]
> > Hey,
> > Why you closed this one? I encountered the same issue with an fixed Navbar from NextUI.
> > Did you find a work around? If so i would be glad if you share your approach :-)
> 
> You just need to pass "position: fixed" inside containerCss in Dropdown.Menu ![image](https://user-images.githubusercontent.com/60183659/250742023-9c31e15d-a334-483d-8dd6-8f29497d97c6.png)

I tried your code and it worked! I simply have to adjust the top parameter a bit.

Thank you!

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
