### ISSUE TITLE
[BUG] - Navbar blur effect frame drop in chrome

### ISSUE THREAD

**Issue by NeatKYU** [nextui-org/nextui#1102]
### Describe the bug

Navbar component blur effect is occured frame drops in Chrome browser. 
add disableBlur attribute returns to normal.

### Steps to Reproduce the Bug or Issue

1. import navbar
2. frame drop after using navbar
3. after add disableBlur and disappear frame drop

### Expected behavior

using navbar in chrome

### Screenshots or Videos

https://user-images.githubusercontent.com/22316798/233760272-cd6b75ca-d0cd-4c99-827b-b6f520d50d58.mov

### Operating System Version

macOS

### Browser

Chrome

**Comment by janathanni** [comment]
can you show your code which uses NavBar?

**Comment by NeatKYU** [comment]
```
import Image from 'next/image'
import { Navbar } from '@nextui-org/react'
import { useRouter } from 'next/router'

interface HeaderProps {
	logo: string;
	title: string;
	children: React.ReactNode;
}

export const Header = ({ logo, title, children }: HeaderProps) => {
	const router = useRouter();

	const goHome = () => {
		router.push('/')
	}

	return (
		<Navbar variant={'sticky'} disableBlur>
			<Navbar.Brand onClick={goHome} className='cursor-pointer'>
				{/* <Image src={'/img/logo_white.png'} alt='logo' width={100} height={60}/> */}
				<span>KYLOG</span>
			</Navbar.Brand>
			<Navbar.Content>
				{children}
			</Navbar.Content>
		</Navbar>
	)
}
```
