### ISSUE TITLE
[BUG] - Can't resolve '@swc/helpers/src/_class_private_field_init.mjs' in NextJS 13 appDir

### ISSUE THREAD

**Issue by Innei** [nextui-org/nextui#1104]
### Describe the bug

I use `npx create-next-app` to create new next.js app enable next 13 appDir, and go to `app/layout.tsx` wrap next-ui NextUIProvider for children. Add 'use client' at first line of layout.tsx, then start dev.

But got an error called  `Can't resolve '@swc/helpers/src/_class_private_field_init.mjs'`

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/41265413/233923118-78467bc0-c520-4fe5-b5be-068bab8a907e.png">

If I remove NextUIProvider, it works.

### Your Example Website or App

https://github.com/Innei/next-ui-swc-reproduction

### Steps to Reproduce the Bug or Issue

1. do `pnpm install`
2. start dev.

### Expected behavior

No error.

### Operating System Version

macOS

### Browser

Chrome

**Comment by Innei** [comment]
And serverside output.

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/41265413/233923340-6bbe0a9a-56e1-421a-a65f-1f12f85d4448.png">

**Comment by jrgarciadev** [comment]
Hey @Innei this is a next.js issue https://github.com/vercel/next.js/issues/38192, please downgrade your next version to 
`"next": "13.3.0"`

**Comment by rjgrandshipper** [comment]
hi @jrgarciadev  what if upgrading to next 12 is not an option?
