### ISSUE TITLE
[Feature Request] Nested collapse

### ISSUE THREAD

**Issue by gosvoh** [nextui-org/nextui#1105]
### Is your feature request related to a problem? Please describe.

Despite the fact that it is possible to create nested Collapse components (although the documentation does not mention it), the arrows do not work correctly.

![image](https://user-images.githubusercontent.com/8506620/234387101-9f8732e5-f0a5-49cf-bf3f-c485b92af5e0.png)

### Describe the solution you'd like

I expect the arrow to be displayed correctly

![image](https://user-images.githubusercontent.com/8506620/234388327-f35258e2-f87c-4e2b-bd39-31844844d2aa.png)

### Describe alternatives you've considered

I propose to bind the state of the arrow to the state of the Collapse component, for example to the data-state or aria-expanded attributes. Or use CSS rule:
```css
.nextui-collapse-view[data-state="closed"]
  > .nextui-collapse-title-container
  > .nextui-collapse-title-content-right
  > .nextui-collapse-icon {
  transform: none;
}
```

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
