### ISSUE TITLE
[BUG] - Components/Table - striped prop works only when selectionMode prop is given 

### ISSUE THREAD

**Issue by SH-Vahn** [nextui-org/nextui#1106]
### Describe the bug

Table component with `striped` prop doesn't work - until it is given `selectionMode` property.

The issue occurs CSS selector for zebra lines refer to rows with `aria-selected=false` attribute, which is not created if no `selectionMode` property was set to Table component.

### Steps to Reproduce the Bug or Issue

1. Go to CodeSandebox example from Table>Striped Variant document ( https://codesandbox.io/s/cb7u21?file=/App.js&from-sandpack=true )
2. In the CodeSandbox editor, remove Line for `selectionMode` prop and watch the difference on preview panel.

### Expected behavior

`striped` prop works without dependency to other props

### Operating System Version

macOS

### Browser

Chrome

**Comment by janathanni** [comment]
<Table
      striped
      sticked
      aria-label="Example static striped collection table"
      selectionMode="false"
      css={{
        height: "auto",
        minWidth: "100%",
      }}
    >

the zebra line works without selection Mode. But like you told, if there has no selectionMode props, it does not show zerbra lines.

**Comment by janathanni** [comment]
I think It's right not to work striped props when does not using selectionMode. 
https://nextui.org/docs/components/table#selection-mode
if you see this doc, they does not using any striped props without selectionMode. 
and you know, actually they does not write about this issue or bug in docs.

**Comment by janathanni** [comment]
and also, I don't know but it works when giving a ```selectionMode=""```
```
    <Table
      striped
      sticked
      aria-label="Example static striped collection table"
      selectionMode=""
      css={{
        height: "auto",
        minWidth: "100%",
      }}
    >
```

**Comment by johnmangan** [comment]
I also ran into this bug. There's nothing in the `striped` prop docs to suggest `selectionMode` must be enabled, nor should it in my opinion.

> I don't know why but it works when giving a selectionMode=""

Entering an empty string is enabling selection mode, so this isn't a valid workaround, as this only occurs in scenarios where we specifically do not want the Table rows to be selectable.

**Comment by sawadyecma** [comment]
It seems like this code is related to this issue.

https://github.com/nextui-org/nextui/blob/185c34142302c20d734546142dc36100fbb8c4fe/packages/react/src/table/table.styles.ts#L274-L290

But I haven't found the solution to fix this issue yet because I'm not familiar with [stitches](https://stitches.dev/).

**Comment by sawadyecma** [comment]
I tried editing the line between 276 and 280 like below, the I found it worked well.

```ts
        [`${StyledTableRow}:nth-child(even)`]: {
          [`& ${StyledTableCell}`]: {
            bg: "$accents0",
          },
        },
```
I'm not certain whether it is right or not.
But I'm not sure about the purposes of using `&` and `[aria-selected=false]` . 

So I would like to know
- Is `[aria-selected=false]` required?
- And `&` is required ? Because I found `[`& ${StyledTableRow}:nth-child(even)`]` does not work well.

**Comment by sawadyecma** [comment]
The PR I created was closed. 
So I decided to make table striped like below.

```tsx
const { theme } = useTheme();

<Table
  css={{
    ["tr:nth-child(even)"]: {
       ["td"]: {
          backgroundColor: theme?.colors.accents0.value,
       },
    },
  }}
/>
```

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).  

https://nextui.org/docs/components/table
