### ISSUE TITLE
[BUG] - next/link with next ui button does a full page refresh on click

### ISSUE THREAD

**Issue by SeccoMaracuja** [nextui-org/nextui#1109]
### Describe the bug

next/link with @nextui-org/react button as child does a full page refresh on click.

### Your Example Website or App

https://stackblitz.com/edit/nextjs-wwzypa?file=pages/index.js
(You have to press Open in New Tab on stackblitz to see the bug.)

### Steps to Reproduce the Bug or Issue

This is my Code:
```
<Link href="/equipment">
     <Button color="primary">
        <Text size={"$xs"}>
            Equipment
        </Text>
     </Button>
</Link>
```

I tried also:
```
<Link href="/equipment" passhref>
     <Button color="primary">
        <Text size={"$xs"}>
            Equipment
        </Text>
     </Button>
</Link>
```

If I swap the link with the button like the following. The page will route client side without a full refresh on click. But I have to click on the button text. If I click on the button border or padding nothing will happen.
```
<Link href="/equipment" passhref>
     <Button color="primary">
        <Text size={"$xs"}>
            Equipment
        </Text>
     </Button>
</Link>
```

I use next js 12.

My package.json contains the following:
 "react": "18.2.0",
 "react-dom": "18.2.0",
 "next": "13.2.4",
"@nextui-org/react": "^1.0.0-beta.12",

### Expected behavior

I want to use next/link with @nextui-org/react button to route client side to another page without a full page refresh.

### Operating System Version

macOS

### Browser

Chrome

**Comment by SohamSen15** [comment]
The `Link` component is styled to resemble a hyperlink and semantically renders an `<a>` tag. To achieve your desired result, you have to use a library like `react-router`.

**Comment by Dodger23** [comment]
I think this is related to the fact that `@nextui-org/react/ Button` is a functional component and in the `Next.js/ Link` docs there is a special handling for functional components, please refer to this to understand more [Next.js/Link functional component child](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-functional-component).

However, I tried to handle it the way it was described in the docs with no success, but maybe you can give it a try.

The only thing that worked and didn't refresh the page but instead did a client-side routing was redirecting using `Next.js/ Router` like so 

``` jsx
import { Button } from '@nextui-org/react';
import { useRouter } from 'next/router';
function Home() {
  const router = useRouter();
  const handleOnPress = () => {
    router.push('equipment');
  };
  return (
    <>
      Home site
      <Button onPress={handleOnPress}>Equipment</Button>
    </>
  );
}
```
Hope this was helpful

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).

```tsx
import {Button} from  "@nextui-org/react"
import NextLink from "next/link";
....
<Button as={NextLink} href="/link-to-navigate">My Button Link</Button>
...

```
