### ISSUE TITLE
Status of version 2

### ISSUE THREAD

**Issue by ahmadlashgari** [nextui-org/nextui#1119]
Why is the publication status of version 2 not clear? None of the addresses of this version work properly, even as a test, they do not work on Next 13. Is there a package that can be tested with Next 13?

**Comment by jrgarciadev** [comment]
Hey @ahmadlashgari here you can check the roadmap + see the v2 components implemented on top of tailwindcss https://github.com/orgs/nextui-org/projects/2/views/1?pane=issue&itemId=20037976

We are currently creating the v2 documentation, https://nextui-docs-v2.vercel.app/docs/guide/introduction , it is still missing some components docs, it requires time to write the docs + examples + API
