### ISSUE TITLE
NextUI support Vite build?

### ISSUE THREAD

**Issue by dartilesm** [nextui-org/nextui#112]
## Describe the bug
Hi @jrgarciadev, I'm using your lib in some projects and it works fine congrats 🎉 . However, in a project built with Vite the build show a blank page. I let you some screenshot below.

## Steps to reproduce
1. Create a simple react project with Vite running this command `npm init vite@latest <proyect-name>`
2. Install NextUI lib (in my case it was the 1.0.1-alpha.57 version) 
3. Follow this step https://nextui.org/docs/guide/getting-started#setup
4. Generate a build and serve it on a server

## Expected behaviour
The app should be works perfectly

### Installation
![image](https://user-images.githubusercontent.com/21966352/140402913-c1a1aed8-ffdf-4584-a925-a4f30b5f7c7c.png)

### Error
https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=object&args[]=
![image](https://user-images.githubusercontent.com/21966352/140401564-11d3576f-6d27-45f7-a5bb-226ecacc5f42.png)

## Environment / Context
- Device: Desktop
- Operating System: Window 11 
- Browser and version: Microsoft Edge Version 95.0.1020.40

## Additional info
Idk, if I forget something let me know.

**Comment by jrgarciadev** [comment]
Hey @dartilesm I'm glad you liked NextUI 🙌🏼, thank you for detailing this, I've followed the same steps and works fine for me, could you please share your node/npm/yarn versions?

 Here's a screenshot:

![Screenshot 2021-11-04 at 21 44 29](https://user-images.githubusercontent.com/30373425/140439722-af7bfa6a-e37c-43fd-b60e-c647700ca0c1.png)

**Comment by dartilesm** [comment]
> Hey @dartilesm I'm glad you liked NextUI 🙌🏼, thank you for detailing this, I've followed the same steps and works fine for me, could you please share your node/npm/yarn versions?
> 
> Here's a screenshot:
> 
> ![Screenshot 2021-11-04 at 21 44 29](https://user-images.githubusercontent.com/30373425/140439722-af7bfa6a-e37c-43fd-b60e-c647700ca0c1.png)

@jrgarciadev It's weird 🤔, even before reporting this issue I deployed the repository in vercel and got the same error. Also I tried to follow the same steps but with `create-react-app` and I had no problems.

`npm -v -> 6.14.13`
`yarn -v -> 1.22.10`
`node -v -> 14.17.1` 

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/21966352/140518046-063fdb1e-1077-425f-8b5c-bbba1655a62b.gif)

You can download the repo [here](https://we.tl/t-x5DqZFN878)

**Comment by jrgarciadev** [comment]
Hey @dartilesm 🙋🏻‍♂️ the example repo works fine for me too, could you update your `npm`version to the version `7.24.1`and try again?

**Comment by dartilesm** [comment]
@jrgarciadev sorry for the late reply.

I've updated my npm version to `7.24.1` and it's still happening 🤔!
![nextui-2](https://user-images.githubusercontent.com/21966352/140649523-83bfab6f-a449-4db3-948d-ffdb470741a1.gif)

I also deployed it again to vercel, and the problem still happening. 
You can visit the app [here](https://next-ui-vite.vercel.app/)

![image](https://user-images.githubusercontent.com/21966352/140649688-348d320d-34f8-4860-96ff-24e8e0ce578a.png)

**Comment by dartilesm** [comment]
In my phone it appears as blank page 😢
![Screenshot_2021-11-07-11-47-50-396_com.android.chrome.jpg](https://user-images.githubusercontent.com/21966352/140649974-085025a6-5b58-46d1-8c6d-4e8545b5ada5.jpg)

**Comment by jrgarciadev** [comment]
Hey @dartilesm could you please try this again using the latest version `v1.0.2-alpha.1`?

**Comment by dartilesm** [comment]
Hi @jrgarciadev Merry Christmas!! Yes, sure I'll try again in few days.

**Comment by jrgarciadev** [comment]
Hey @dartilesm Merry Christmas! 🎄,  don't worry 👍🏻

**Comment by dartilesm** [comment]
@jrgarciadev I tried it again and the error changed, but with different message. I show you my changes:

![image](https://user-images.githubusercontent.com/21966352/148597340-3e73ac11-cffa-4702-a0e9-fff35ec9883b.png)
![image](https://user-images.githubusercontent.com/21966352/148597353-e00e5430-3db2-4cef-b93f-a3151693310b.png)
![image](https://user-images.githubusercontent.com/21966352/148597399-89174a0d-7e2c-47c1-ac1d-ad5e1382000d.png)
![image](https://user-images.githubusercontent.com/21966352/148597654-6eb78e11-0ae3-49c9-81d0-bd57390f61e1.png)


You can see the error here
https://next-ui-vite.vercel.app/

**Comment by dartilesm** [comment]
I let you my commit https://github.com/dartilesm/next-ui-vite/commit/fb7e51aa834f3caf588194ab1b69131ac636bf6b 
You must accept my invitation to access the repository.

**Comment by SalahAdDin** [comment]
@dartilesm Does it finally works?

**Comment by jrgarciadev** [comment]
Hey @dartilesm  I just released version v1.0.1-beta.2 which includes the solution for this 🙌🏻
