### ISSUE TITLE
[BUG] - FOUC on simple components

### ISSUE THREAD

**Issue by Widespread-Wheel** [nextui-org/nextui#1120]
### Describe the bug

Loading a basic page causes FOUC. I don't think anything overly fancy was created but I'm still getting FOUC.

I've tested this with Firefox and Edge.

### Steps to Reproduce the Bug or Issue

1. Generate a new Next.js application & install NextUI
2. Empty globals.css & page.module.css
3. Update page.tsx to the following:
```
'use client'
import {Navbar, Switch} from "@nextui-org/react";
import React from "react";

export default function Home() {
    return (
        <main>
            <Navbar>
                <Navbar.Content>
                    <Navbar.Link>Navbar Item</Navbar.Link>
                    <Navbar.Link>Navbar Item</Navbar.Link>
                    <Navbar.Link>Navbar Item</Navbar.Link>
                    <Navbar.Link>Navbar Item</Navbar.Link>
                    <Navbar.Link>Navbar Item</Navbar.Link>
                    <Navbar.Link>Navbar Item</Navbar.Link>
                    <Navbar.Link>Navbar Item</Navbar.Link>
                    <Navbar.Link>Navbar Item</Navbar.Link>
                </Navbar.Content>
            </Navbar>
            <div>
                <Switch>Switch</Switch>
                <div>
                    <h1>Header</h1>
                    <p>
                        <li>Bullet</li>
                        <li>Bullet</li>
                        <li>Bullet</li>
                    </p>
                </div>
            </div>
        </main>
    )
}
```
4. `npm run dev`
5. Load page, refresh page

### Expected behavior

No FOUC occurs

### Screenshots or Videos

Unrendered Content
![image](https://user-images.githubusercontent.com/132688703/236504091-430cedad-1e22-4cf9-bd46-6c6de109a09c.png)

Rendered Content
![image](https://user-images.githubusercontent.com/132688703/236504148-23dd9712-1e16-49ef-8f63-cb3fd9933368.png)

### Operating System Version

Windows 10

### Browser

Firefox

**Comment by janathanni** [comment]
could you show your _app.js?

**Comment by Widespread-Wheel** [comment]
Attempted using Next.js 12.3.2 with similar results.

**Comment by janathanni** [comment]
can you show your _app.js?

**Comment by Widespread-Wheel** [comment]
After double checking the _app.js and _document.js, it looks like I was missing getInitialProps. Re-adding that fixed the issue.
