### ISSUE TITLE
Input double border at focus and the black border effect at hover not working in v1.0.1-alpha.57

### ISSUE THREAD

**Issue by lohnsonok** [nextui-org/nextui#113]
**Describe the bug**
The fields are covered with double border at focus and the black border effect at hover no longer works for all inputs

**Steps to reproduce**
1. Update to latest version v1.0.1-alpha.57
2. Click on an Input bordered

**Expected behaviour**
Clear working hover state and focus state like in previous version v1.0.1-alpha.56

**Screenshots**
![Capture d’écran de 2021-11-05 19-57-24 (1)](https://user-images.githubusercontent.com/60504466/140564510-226b2c64-d40b-4f57-956a-e1559e35fcef.png)

**Environment / Context**
- Desktop
- Operating System: Ubuntu
- Browser and version Chrome 93

**Comment by jrgarciadev** [comment]
Hey @lohnsonok thank you for reporting it, I'm going to check this out 👍🏻

**Comment by lohnsonok** [comment]
> Hey @lohnsonok thank you for reporting it, I'm going to check this out 👍🏻

Ok thank, will check

**Comment by jrgarciadev** [comment]
Hey @lohnsonok this will be available in the next version (Alpha 58)

**Comment by lohnsonok** [comment]
Okay. Thank you for faster fixing !

**Comment by jrgarciadev** [comment]
Hey @lohnsonok could you please try it again with the latest version v1.0.2-alpha.1?

**Comment by jrgarciadev** [comment]
Hey @lohnsonok I tried this and it's working, I'm going to close this issue 👍🏻
