### ISSUE TITLE
[BUG] - cannot input Chinese when Input in controlled mode

### ISSUE THREAD

**Issue by xyuanbuilds** [nextui-org/nextui#1138]
### Describe the bug

cannot input Chinese when `Input` in controlled mode, like Input refresh when composition event start

### Your Example Website or App

https://nextui.org/docs/components/textarea#controlled-vs-uncontrolled

### Steps to Reproduce the Bug or Issue

1. https://nextui.org/docs/components/textarea#controlled-vs-uncontrolled
2. input Chinese in controlled 

### Expected behavior

can input

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/21687167/6fb7cd93-dbca-45d2-acf4-80d693960ea5

### Operating System Version

macOS

### Browser

Chrome

**Comment by xyuanbuilds** [comment]
only occur in doc website, when in storybook, the problem does not occur

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
