### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by atabv** [nextui-org/nextui#1141]
### Describe the bug

When you setup a new project with 

1.  npx create-next-app@latest
2. npm i @nextui-org/react framer-motion
 (https://nextui-docs-v2.vercel.app/docs/frameworks/nextjs)
3. Adding the lines from the docs to tailwind.config.js produces an error because there is no such method nextui or directory named theme

![image](https://github.com/nextui-org/nextui/assets/84914886/1379f02b-6669-48b6-8b78-4f033bd05ada)

How come your official docs have such a glaring error?

### Steps to Reproduce the Bug or Issue

1.  npx create-next-app@latest
2. npm i @nextui-org/react framer-motion
 (https://nextui-docs-v2.vercel.app/docs/frameworks/nextjs)
3. Adding lines to tailwind.config.js

// tailwind.config.js
const { nextui } = require("@nextui-org/react");

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    // ...
    './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}'
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [nextui()]
}
```

I get a Failed to compile error

```./app/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@13.4.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[2]!./node_modules/.pnpm/next@13.4.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[3]!./app/globals.css
TypeError: nextui is not a function
Import trace for requested module:
./app/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@13.4.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[2]!./node_modules/.pnpm/next@13.4.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[3]!./app/globals.css
./app/globals.css
This error occurred during the build process```



```

This seems normal because if you run a tree on @nextui-org/ inside node_modules, you will find out it doesnt have a theme directory and so there is no such method as nextui().

$ tree -L 1 node_modules/@nextui-org 
node_modules/@nextui-org
└── react

1 directory, 0 files
```


### Expected behavior

To have the correct files included in the npm install.

### Screenshots or Videos

_No response_

### Operating System Version

macOS latest

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Please run 

`npm i @nextui-org/react@dev-v2 framer-motion`

Please note that v2 documentation is not ready yet
