### ISSUE TITLE
[BUG] - Styling tooltip Arrow

### ISSUE THREAD

**Issue by landmann** [nextui-org/nextui#1142]
### Describe the bug

When I change the css of the tooltip, the arrow stays the same color as the primary color.

### Steps to Reproduce the Bug or Issue

```
    <Tooltip
      content={content}
      css={{
        color: "gray",
        background: "#FFFBF1",
        border: "2px solid gray",
      }}
      placement="top"
      {...props}
    >
      {children}
    </Tooltip>
```

### Expected behavior

The css should style the arrow as well.

### Screenshots or Videos

<img width="104" alt="Screenshot 2023-06-04 at 8 29 00 PM" src="https://github.com/nextui-org/nextui/assets/12756081/95de7af6-5ebc-4474-b352-a48ad13bc505">

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @landmann  sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2). 

Override styles: https://nextui.org/docs/customization/override-styles
Tooltip Arrow Slot: https://nextui.org/docs/components/tooltip#slots
