### ISSUE TITLE
[Feature Request] Dropdown   selectionMode="single" display text and not the key

### ISSUE THREAD

**Issue by liorFaigenzon** [nextui-org/nextui#1150]
Can the selected text be the content and not the key? I mean the display will be the value and on form submit to send the id.
https://nextui.org/docs/components/dropdown
![image](https://github.com/nextui-org/nextui/assets/14123246/ddae38fc-9374-4d67-8588-b18793e9548f)

### Describe the solution you'd like

I create a drop down, but I get this:
![image](https://github.com/nextui-org/nextui/assets/14123246/20b813af-0469-4528-bf02-a952fb6f929d)

### Describe alternatives you've considered

add ability to choose the prop to display and to be selected.

**Comment by jrgarciadev** [comment]
Hey @liorFaigenzon this is the way react-aria works, so we can't change it, moreover, you can use the dynamic rendering to get the content of the item once selected. Also please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).
