### ISSUE TITLE
load document completed to view

### ISSUE THREAD

**Issue by stone89son** [nextui-org/nextui#1153]
### Describe the bug

Dependencies:
"@nextui-org/react": "^1.0.0-beta.13",
"@types/node": "20.2.5",
"@types/react": "18.2.8",
"@types/react-dom": "18.2.4",
"eslint": "8.42.0",
"eslint-config-next": "13.4.4",
"next": "13.4.4",
"react": "18.2.0",
Video:
[c24d5802-8f7c-47a9-8472-80a2786e6d03.webm](https://github.com/nextui-org/nextui/assets/6795515/39f282ca-bba8-4260-a6de-f076c4dd8d7a)

### Steps to Reproduce the Bug or Issue

1. type command: yarn dev
2. goto localhost:3000
3. plain text will show 
4. adjusted website layout.

### Expected behavior

As a user , I expected adjusted website layout completed to show. it looks ugly and uncomfortable

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
