### ISSUE TITLE
[BUG] - Card box shadow in safari

### ISSUE THREAD

**Issue by BenSievert** [nextui-org/nextui#1154]
### Describe the bug

When looking at Cards in Safari, the box shadow does not appear. For example, this can be seen on the nextui site when looking at the Card page. This issue is due to Safari needing box shadow colors specified explictly. 

### Steps to Reproduce the Bug or Issue

1. Goto https://nextui.org/docs/components/card using the Safari browser.
2. Scroll down to variants and look at "Default card. (shadow)"

### Expected behavior

To see a box shadow, but a transparent one is rendered

### Operating System Version

macOS

### Browser

Safari

**Comment by pcraig3** [comment]
Hello, I ran into this as well, but I figured it out a way to get it to work.

What worked for me was adding a CSS rule to make the `overflow: visible` for the card container element. Your CSS should look something like `div[role="region"] { overflow: visible; }`

Here's a before and after screenshot:

| before | after |
|--------|-------|
|  no background shadows      | shadows are back!      |
|    <img width="1332" alt="Screenshot 2023-07-05 at 9 29 56 PM" src="https://github.com/nextui-org/nextui/assets/2454380/7d1acda7-d7bf-4af3-abd0-836811de34d9">   |  <img width="1332" alt="Screenshot 2023-07-05 at 9 29 52 PM" src="https://github.com/nextui-org/nextui/assets/2454380/f8e714c0-47b7-441e-b0b1-0cee39a000ae"> |
