### ISSUE TITLE
[BUG] - showIn and hideIn not working at breakpoint

### ISSUE THREAD

**Issue by ToMeHarris** [nextui-org/nextui#1156]
### Describe the bug

When using two text components, one with `hideIn` and one with `showIn`, neither is rendered when the screen is at the breakpoint width (in this case, 650).
```
<Text h1 hideIn='xs'> Big header </Text>
<Text h2 showIn='xs'> Small header </Text>
```

### Steps to Reproduce the Bug or Issue

Create two text components using `hideIn` and `showIn` with the same breakpoint. Resize the screen to the exact value of the breakpoint. Neither text will render.

### Expected behavior

As a user, I expect either one or the other to render at the breakpoint. Probably the one with `showIn`.

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @ToMeHarris  sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).  Use TailwindCSS responsive classes.
