### ISSUE TITLE
[BUG] - Tooltip component in v2 is blocking mouse events

### ISSUE THREAD

**Issue by Mahmoud-Masri** [nextui-org/nextui#1157]
### Describe the bug

When surrounding an element with Tooltip component, mouse event listeners doesn't work 

### Steps to Reproduce the Bug or Issue

```JSX
  <Tooltip content="Hello world">
      <div className="h-32 w-32 bg-[red]" onMouseDown={alert} />
  </Tooltip>
```

With the Tooltip component the onMouseDown doesn't work, however if you remove the Tooltip the onMouseDown works

### Expected behavior

I expected the onMouseDown event listener to work

### Operating System Version

macOS

### Browser

Chrome

**Comment by Mahmoud-Masri** [comment]
I've just noticed that if I replaced the `onMouseDown` with `onPointerDownCapture` it works alright

**Comment by u3u** [comment]
This is still an issue that will prevent it from being used together with the Thumb component of Slider. At least an option can be provided to disable this behavior. It would also be better to provide a `positionDependencies` option to update the Tooltip position when specified data changes.

Reference:

- https://mantine.dev/core/slider/
- https://mantine.dev/core/tooltip/
