### ISSUE TITLE
[BUG] yarn.lock file not updated after version change in subdirectories' package.json files

### ISSUE THREAD

**Issue by ryo-manba** [nextui-org/nextui#1162]
### Describe the bug

In the PR [#997](https://github.com/nextui-org/nextui/pull/997), the version of `@nextui-org/react` in the package.json files in various subdirectories was updated from `1.0.0-beta.11` to `1.0.0-beta.12`. However, the yarn.lock file at the root of the project doesn't seem to have been updated to reflect this change. 

### Steps to Reproduce the Bug or Issue

1. Clone the project and checkout to the latest commit.
2. Run `yarn install` at the root of the project.
3. Check the git status. You will see that the `yarn.lock` file has uncommitted changes.

### Expected behavior

When the version of a dependency in `package.json` is updated and committed to the repository, the corresponding update to the `yarn.lock` file should also be committed. This ensures that the exact same versions of dependencies are used across all environments, and that running `yarn install` doesn't result in uncommitted changes.

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
