### ISSUE TITLE
Tooltip delay open after cursor leave

### ISSUE THREAD

**Issue by sbc640964** [nextui-org/nextui#1168]
### Describe the bug

**Version: 2**

It's quite simple just like in the issue title.
When an opening delay is set, it will open even after the mouse has already come down from the element.

### Steps to Reproduce the Bug or Issue

Add a tooltip
Set delay
Move the mouse and download immediately
Notice it opens

### Expected behavior

If the mouse is down there is no reason to open

### Operating System Version

win10

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @sbc640964 could you be more specific, please? maybe attach a video so we can get your point, thanks!
