### ISSUE TITLE
Card.Footer not respecting theme

### ISSUE THREAD

**Issue by devpikachu** [nextui-org/nextui#117]
**Describe the bug**
Using the `docs` package as a reference, I attempted to implement a theme toggle for my website, as I found no documentation for this. Everything seems to be functional as expected, except for Card.Footer which remains with a background color of `#fff`.

**Steps to reproduce**
1. Using the latest version, implement a simple theme toggle using `use-dark-mode` and `React.useState`.
2. Import the shared theme from `@nextui-org/react/cjs/theme/shared`,
3. Toggle the theme.

**Expected behaviour**
Card.Footer changes to have the same background as the rest of the card (`#111`).

**Screenshots**
![image](https://user-images.githubusercontent.com/30475873/141008021-12457359-24ef-4853-bb9b-7f0e64672f84.png)

**Environment / Context**
- Desktop or Mobile? Desktop
- Operating System: Windows 11
- Browser and version: Firefox 94.0.1
- Device: PC

**Additional info**
[_app.js Gist](https://gist.github.com/devpikachu/532256d53023a9ae4e71fed520a61a96)
[login.js Gist](https://gist.github.com/devpikachu/2de5abd501e10bb4c27445e2cc253c8b)
[theme-toggle.js Gist](https://gist.github.com/devpikachu/04224349628612e8a5d71abf5261338b)

**Comment by jrgarciadev** [comment]
Hey @devpikachu thanks for reporting it, I will check this out as soon as possible

**Comment by jrgarciadev** [comment]
Hey @devpikachu I've fixed the bug. However, this will be available in the next version (Alpha 58) I hope to release it as soon as possible, here's the PR #118

**Comment by devpikachu** [comment]
Hey @jrgarciadev ! Thank you for the prompt reply on this! No worries on the Alpha, as the app is still in development and I have a quick workaround by setting the footer's color property until then.

**Comment by jrgarciadev** [comment]
Hey  @devpikachu   could you please try it again with the latest version v1.0.2-alpha.1?

**Comment by devpikachu** [comment]
Hello @jrgarciadev ! Can confirm, this has been fixed under 1.0.2-alpha.1. Thank you!

![Peek 2021-12-30 19-51](https://user-images.githubusercontent.com/30475873/147776319-f76bd823-1e80-46b7-84d9-f039499dc436.gif)
