### ISSUE TITLE
Can't override Styles!!!

### ISSUE THREAD

**Issue by shanewmurphy** [nextui-org/nextui#1176]
Never been so UTTERLY Annoyed by Implementing something like Next UI

You tell us Customise the theme by doing the allowing in _app.js 

`import { createTheme, NextUIProvider, Text } from "@nextui-org/react"

// 2. Call `createTheme` and pass your custom values
const myDarkTheme = createTheme({
  type: "light", // it could be "light" or "dark"
  theme: {
    colors: {
      // brand colors
      background: "#1d1d1d",
      text: "#fff",
      // you can also create your own color
      myDarkColor: "#ff4ecd",
      myNavBackGround: "#E6DCD6",
      // ...  more colors
    },
    space: {},
    fonts: {},
  },
});

// 3. Pass the new theme based on dark type theme to `NextUIProvider`
<NextUIProvider theme={myDarkTheme}>
  <App />
</NextUIProvider>`

In Nav component on Navbar element I wish to change the background colour like so:
` <Navbar
          isBordered
          variant="sticky"
          css={{
            backgroundColor: "$myNavBackGround",
          }}
        >`
I WON'T CHANGE the to `myNavBackGround: "#E6DCD6",` it just stays white!!!! 

What a absolute joke it is to change basic styles on your components.

**Comment by a-Marino** [comment]
i have the same problem..... and i have a table, i disable the border, then i reload the page and the border apperars again and doesnt go

**Comment by jrgarciadev** [comment]
Please start using v2 https://nextui-docs-v2.vercel.app/ , as V1 is based on Stitches is quite hard to provide a single way to override all styles, on V2 you can override every single part of the components thanks to the slots.

https://nextui-docs-v2.vercel.app/docs/customization/override-styles
