### ISSUE TITLE
[BUG] - Layout/Spacer

### ISSUE THREAD

**Issue by peterchui** [nextui-org/nextui#1181]
### Describe the bug

import { Container, Spacer, Card } from "@nextui-org/react";

You haven't imported the Container in your sample code.

### Steps to Reproduce the Bug or Issue

import { Container, Spacer, Card } from "@nextui-org/react";

### Expected behavior

import { Container, Spacer, Card } from "@nextui-org/react";

### Operating System Version

macOS

### Browser

Firefox

**Comment by jrgarciadev** [comment]
Hey @peterchui  sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2). 

https://nextui.org/docs/components/spacer
