### ISSUE TITLE
[BUG] nextui baseline css act differently in dev mode and build, it override my styles after build

### ISSUE THREAD

**Issue by NekoWings** [nextui-org/nextui#1182]
### Describe the bug

I use tailwind + vite + react + nextui, and my page works fine in dev mode, all the style inject into html <style>.
![image](https://github.com/nextui-org/nextui/assets/24478007/80db892d-3381-4553-813f-11b3d1a2f835)

But when I build my project, all the styles except nextui extract to css file, so the css override relationship is broken.
![image](https://github.com/nextui-org/nextui/assets/24478007/575fb585-622b-492f-9e73-668ec8d3fd88)

And I have already set disableBaseline true.

### Steps to Reproduce the Bug or Issue

1. use vite + react write a dialog with Modal component
2. change dropback style by customize .nextui-backdrop (background or zindex)
3. check style in dev mode and build file
4. see different style order in DevTools

### Expected behavior

I expected it act in same way between dev & build. But it seems a problem about style building. inline css or extract a file.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).  CSSBaseline have been removed
