### ISSUE TITLE
[Feature Request] Figma file for designers

### ISSUE THREAD

**Issue by Agentisreal** [nextui-org/nextui#1183]
### Is your feature request related to a problem? Please describe.

We are working on a big big project which one is a SAAS platform and this will be our V2 and we will be so happy if we could use the Figma file to create the UI for this project because you can save me so much time with this.

### Describe the solution you'd like

Any type of a Figma version like just the buttons, tables even without components and variables. Just to let me use the exactly same looks on components. 

### Describe alternatives you've considered

As i mentioned before a small piece of the Figma file would be so nice too.

**Comment by jrgarciadev** [comment]
https://www.figma.com/community/file/1267584376234254760
