### ISSUE TITLE
[V2] Accordion looks ugly with scrollbar

### ISSUE THREAD

**Issue by sFritsch09** [nextui-org/nextui#1185]
### Describe the bug

The Accordion-Item displays the scrollbar for a split second which looks ugly to me.

It is easily fixed by removing at **line 62** **overflow-y: auto** (better: hidden):

**packages/components/accordion/src/accordion-item.tsx**

I'm open to make PR

### Your Example Website or App

https://nextui-docs-v2.vercel.app/docs/components/accordion

### Steps to Reproduce the Bug or Issue

1. Go to [Accordion](https://nextui-docs-v2.vercel.app/docs/components/accordion)
2. Click on Accordion to show the Accordion-Item or Child

### Expected behavior

No scrollbar shown!

### Operating System Version

any

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Fixed
