### ISSUE TITLE
[BUG] - Can't set font color for Textarea component

### ISSUE THREAD

**Issue by dorin-chioibas** [nextui-org/nextui#1193]
### Describe the bug

I needed to edit the color of the text in the Textarea component. Maybe I missed something, but after reading the docs, I couldn't find any way to do that other than overriding the default css style with the help of **css**  prop. However, setting the **color** field seems not to work. I tried implementing the same **css** for a button and worked successfully. Thus I wanted to ask, might this be a bug or is it expected behavior and I'm missing something? I've added a code sandbox link down below. The difference between the Button and the Textarea can be seen in pages/index.jsx.

### Your Example Website or App

https://codesandbox.io/p/sandbox/heuristic-field-cj58g3?file=%2F.codesandbox%2Ftasks.json%3A1%2C1

### Steps to Reproduce the Bug or Issue

1. Go to pages/index.jsx
2. Check the css prop and the color field for the Textarea
3. Check the css prop and the color field for the Button
4. observe the color difference of the text, even though the same field is used for both components, the color for text is not applied to Textarea but only to the Button

### Expected behavior

Using the color field of the css prop should make the text look green when typing

### Operating System Version

Ubuntu

### Browser

Edge

**Comment by jrgarciadev** [comment]
Hey @dorin-chioibas sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).  Use TailwindCSS classes to override the color.

**Comment by xepozz** [comment]
<img width="463" height="103" alt="Image" src="https://github.com/user-attachments/assets/63bb0fd2-9f99-4d95-987f-32b7ecbac230" />

<img width="517" height="144" alt="Image" src="https://github.com/user-attachments/assets/8704e760-f755-4c96-b68a-e3e7b072600d" />

<img width="310" height="100" alt="Image" src="https://github.com/user-attachments/assets/f285f4b7-0b1d-4519-9d3e-41462ef510eb" />

Doesn't work as well
