### ISSUE TITLE
[BUG] - 404 error when installing @nextui-org/react@dev-v2

### ISSUE THREAD

**Issue by jvinters** [nextui-org/nextui#1196]
### Describe the bug

Installing the package '@nextui-org/react@dev-v2' causes an error. 

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-stately%2ftable - Not found
npm ERR! 404
npm ERR! 404  '@react-stately/table@^3.10.0' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Steps to Reproduce the Bug or Issue

1. Create a clean nextjs project (`npx create-next-app@latest`)
2. Run `npm i @nextui-org/react@dev-v2`

### Expected behavior

The package should install without causing the 404.

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Please try again with the latest snapshot, but the `@react-stately/table` version is the correct one https://github.com/adobe/react-spectrum/blob/main/packages/react-stately/package.json#L43

**Comment by jvinters** [comment]
@jrgarciadev Works now, thank you!
