### ISSUE TITLE
[Feature Request] Virtualization for Table Component

### ISSUE THREAD

**Issue by timefordroids** [nextui-org/nextui#1197]
### Is your feature request related to a problem? Please describe.

The problem is related to performance issues when rendering large data sets in the Table component. BTW, the Table is pretty fast.

### Describe the solution you'd like

React Spectrum has some references to virtualization in their docs. We could potentially leverage their solutions  for implementing virtualization.

### Describe alternatives you've considered

Additionally, it would be great to allow the application of a style prop to the Table components. This would provide greater flexibility and could also facilitate the implementation of virtualization with a solution like TanStack Virtual.

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
