### ISSUE TITLE
Components/Input

### ISSUE THREAD

**Issue by HHongVu** [nextui-org/nextui#120]
**Describe the bug**
A clear and concise description.

**Steps to reproduce**

**Expected behaviour**

**Screenshots**

**Environment / Context**
- Desktop or Mobile?
- Operating System: [e.g. iOS]
- Browser and version [e.g. chrome 22]

**Additional info**

**Comment by jrgarciadev** [comment]
Hey @HHongVu ✋🏻, what's the problem here?
