### ISSUE TITLE
onChange doesn't get triggered with spacebar 

### ISSUE THREAD

**Issue by utopy** [nextui-org/nextui#121]
Input's onChange event doesn't get triggered when pressing space on text input; For this reason the value passed to the input doesn't register spaces. 

    const [productState, setProductState] = useState<ProductInterface>({
        name: "",
    })

    function handleChange(e:ChangeEvent<FormElement>){
        console.log(e)
        setProductState({
            ...productState,
            [e.target.name]: e.target.value
        })
    }

    {...}

    <Grid  style={{marginTop:10}}>
       <Input labelPlaceholder="Name" width="100%"type="text" value={productState.name} onChange={handleChange} name="name"/>
    </Grid>

Normally the state should be updated with the space too!
I'm on a mac book pro running Catalina, tested on Firefox and Safari if it can matter somehow

EDIT: forgot to copy value assignment on input

**Comment by jrgarciadev** [comment]
Hey @utopy thank you for reporting this, I will check it out 👍🏻

**Comment by carlosriveroib** [comment]
I copied your code and it's working for me. Space is firing the onChange event
![2021-11-20 15 22 19](https://user-images.githubusercontent.com/9528363/142729942-d1fd07d3-7d05-4f81-a2fc-89ffeccc3f7f.gif)

**Comment by utopy** [comment]
I tested it again at the root of my project, right before the router, an it seems to work [(this is the example code)](https://codesandbox.io/s/funny-haibt-cdvf8?file=/src/App.js:368-472).
I tested it inside my component (with the same code) and it didn't work; it's strange because every other value change is being recognized, but at this point I'm thinking there must be an error in my implementation. I'm attaching my component's code, maybe you guys can find something wrong in it! 

```
export interface WorkInterface{
    name: string,
    description:string,
    subtitle:string,
    productCover: ImageInterface


}

export interface NewWorkProps {
    name: string,
    icon?: ReactNode,
}

const baseState:WorkInterface = {
    name: "",
    description: "",
    subtitle: "",
    productCover: {} as any
}




const NewWork:FC<NewWorkProps> = (props) => {

    const navigate = useNavigate()
    const [workCover, setWorkCover] = useState<File | null>(null)

    const [state, setState] = useState<{[key:string]:any}>({
        test: ""
      })

      const handleChangea = (e) => {
        e.preventDefault();
        setState({[e.target.name]:e.target.value})
      }

    const [workState, setWorkState] = useState<WorkInterface>(baseState)
    const fileInputRef = useRef(null)
    const actions:ButtonAction[] = [
        {name: "nuovo prodotto", onClick: (e) => {navigate("/works/new")}},
        {name: "modifica", onClick: (e) => {}, type: "secondary"}
    ]

    async function fileHandler(e:ChangeEvent<HTMLInputElement>){
        console.log(e.target.files)
        const file = e.target.files[0]
        setWorkCover(file)
    }


    function handleChange(e:ChangeEvent<FormElement>){
        e.preventDefault()
        setWorkState({
            ...workState,
            [e.target.name]: e.target.value
        })
    }

    const productPreview = workCover ? URL.createObjectURL(workCover) : "https://via.placeholder.com/250C/D7D7D7"

    return (
        <Page name={props.name} icon={props.icon} actions={actions}>
            <Grid.Container gap={2}>
            {workState.name}
            <Grid xs direction="column">
                {state.test}
            <Input  labelPlaceholder="Nome Prodotto" name="test" onChange={handleChangea} value={state.test}/>

                <Grid md={3}>
                    <Card height="200px" shadow={false} hoverable clickable onClick={() => {}}>
                        <Card.Body noPadding>
                            <Card.Image objectFit="cover" 
                                src={productPreview}/>
                        </Card.Body>
                    </Card>
                    <Input hidden type="file" ref={fileInputRef} onChangeCapture={fileHandler}/>
                </Grid>
                <Grid  style={{marginTop:10}}>
                    <Input labelPlaceholder="Nome Prodotto" width="100%"type="text" value={workState.name} onChange={handleChange} name="name"/>
                </Grid>

                <Grid  style={{marginTop:10}}>
                    <Input labelPlaceholder="Sottotitolo" width="100%" value={workState.subtitle} onChange={handleChange}  name="subtitle"/>
                </Grid>

                <Grid  style={{marginTop:10}}>
                    <Input labelPlaceholder="Descrizione" width="100%" value={workState.description} onChange={handleChange}  name="description"/>
                </Grid>

            </Grid>

            </Grid.Container>
        </Page>
    )
}

export default NewWork
```

**Comment by carlosriveroib** [comment]
Can you upload this code to Github and share the link?

**Comment by Matteo-Peronnet** [comment]
I am facing the same problem. 

The space bug comes when we wrap the Input component with the Card component.

Sorry, I couldn't create the codesandbox with the Card component, it was giving me an error.

I tested locally and reproduced the problem directly.

**Comment by jrgarciadev** [comment]
Hey guys, @Matteo-Peronnet made a PR for solving this, it will be available in the Alpha 58 version

**Comment by utopy** [comment]
awesome, thank you guys for the amazing work done so far!

**Comment by jrgarciadev** [comment]
Hey @utopy  could you please try it again with the latest version v1.0.2-alpha.1?

**Comment by utopy** [comment]
I just updated the version and tested the same component of the issue and it still doesn't work. Do i have to update something inside the component?

Right now it's 3am, gonna test it on a separate project as soon as I get to work tomorrow :)

**Comment by jrgarciadev** [comment]
I just tried on CodeSandBox with the latest version and It's working [Demo](https://codesandbox.io/s/quirky-noyce-zbtux?file=/src/App.js) 🙋🏻‍♂️

**Comment by utopy** [comment]
Yes, you are right, it works! I simply had to delete parcel cache and rebuild everything! Thank you for the fix :) again awesome work, i hope to contribute someday!
