### ISSUE TITLE
Usage creates a classless div with 'data-overlay-container' attribute.

### ISSUE THREAD

**Issue by Enalmada** [nextui-org/nextui#1215]
### Discussed in https://github.com/nextui-org/nextui/discussions/804

<div type='discussions-op-text'>

<sup>Originally posted by **MARCA-Charlie** October  7, 2022</sup>
I am using in Next.JS, the div stops children growing to their parent's height and width. As the div is classless it is hard to target with styles to overcome this.

Please see screenshot for context.

![image](https://user-images.githubusercontent.com/89167030/194594372-4b369941-3461-4ae4-8ee0-39cc9c9c28d7.png)</div>

Workaround:
```
[data-overlay-container=true] {
  height: 100%;
  width: 100%;
}
```

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
