### ISSUE TITLE
[BUG] - Navbar component is not availaible after installing 

### ISSUE THREAD

**Issue by code-withAshish** [nextui-org/nextui#1220]
### Describe the bug

I am not able to import Navbar component from `@nextui-org/react` it's simply not availaible

### Steps to Reproduce the Bug or Issue

1. install the package from npm
2. try importing it

### Expected behavior

it should contain an navbar component and i should have been able to use it

### Operating System Version

Linux

### Browser

Chrome

**Comment by code-withAshish** [comment]
> if you installed @dev-v2, you can visit this link to import navbar component correctly [https://nextui-docs-v2.vercel.app/](url)

Actually I was using v1 only and was using yarn and the problem was somehow related to package managers

Also the props intellisense for components is not available even in typescript somehow?
In both v1 and v2

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).  Props intellisense should work without any issue 👍🏻
