### ISSUE TITLE
Status color for input with left or right label

### ISSUE THREAD

**Issue by tinaluethe** [nextui-org/nextui#1227]
### Describe the bug

When using the input component with `labelLeft` and setting a status other than `default`, the label background color is the same as the input background color. (See screenshots for comparison)

### Steps to Reproduce the Bug or Issue

1. Use input component with status set to `primary` and a `labelLeft`
```
<Input labelLeft="Leftlabel" status={'primary'} />
```
<img width="692" alt="Screenshot 2023-07-29 at 21 22 14" src="https://github.com/nextui-org/nextui/assets/97974146/0f2bdcb2-5432-495e-bd2f-261d02d341ab">

2. Compare it to input component with status set to `default` and a `labelLeft`
```
<Input labelLeft="Leftlabel" status={'default'} />
```
<img width="698" alt="Screenshot 2023-07-29 at 20 49 22" src="https://github.com/nextui-org/nextui/assets/97974146/64fd6a7b-f928-4410-917a-16e00bc05d55">

### Expected behavior

I expect the background color of left or right labels to be distinguishable from the input background color when a status was set. Same as it is for `default` already 

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
