### ISSUE TITLE
[BUG] - Button broke remix.run Link to 

### ISSUE THREAD

**Issue by PR0F1L3R1** [nextui-org/nextui#1228]
### Describe the bug

latest build of v2 brokes remix.run Link with button component

in version all working good without any problem 0.0.0-dev-v2-20230719131057, after this version i think button element break href link to `location.pathname`

### Your Example Website or App

i cant transfer from local to stackblitz =(

### Steps to Reproduce the Bug or Issue

set 
```tsx
<Button as={Link} to={`anything`}>anything</Button>
```

### Expected behavior

work Button component with Link =(

### Operating System Version

macOS, windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Please test this again with the latest version

**Comment by PR0F1L3R1** [comment]
not fixed, same problem
![image](https://github.com/nextui-org/nextui/assets/40261445/606aeffe-3188-4cb1-a477-9aa022e69167)

![image](https://github.com/nextui-org/nextui/assets/40261445/2b1a3fc6-a80b-4ad0-ac3b-161dfb605eef)

**Comment by jrgarciadev** [comment]
Can you upload a video/repo, I don't fully understand what the error is

**Comment by PR0F1L3R1** [comment]
I created repo with this bug. https://github.com/PR0F1L3R1/nextui-button-link

You can check source code and deployed version.

**Comment by jrgarciadev** [comment]
Did you try this way?

```tsx
<Link to='/test'>
  <Button>
        Go to page
   </Button>
 </Link>     
```

**Comment by PR0F1L3R1** [comment]
> Did you try this way?
> 
> ```tsx
> <Link to='/test'>
>   <Button>
>       Go to page
>    </Button>
>  </Link>     
> ```

yes, i have tried this way, but it's break animation, because reloading page =(

**Comment by jrgarciadev** [comment]
Hey @PR0F1L3R1 I couldn't figure out why remix changes the "href" when using polymorphic components, but here's a workaround that works similarly to the native remix link.

```tsx
const ButtonLink = ({ to, children }: {
  to: string
  children: React.ReactNode
}) => {
  const navigate = useNavigate()
  return (
    <Button as="a" href={to}>
      {children}
      <PrefetchPageLinks page={to} />
    </Button>
  )
}

export default function Index() {
	return (
		<div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
			<h1>Welcome to Remix</h1>
			<ButtonLink to='/test'>
				Go to page
			</ButtonLink>
		</div>
	);
}
```

**Comment by jrgarciadev** [comment]
Hey @PR0F1L3R1 please upgrade to the latest version, we are no longer filtering the props when the component is not a pure html element
