### ISSUE TITLE
[BUG] - nextui() plugin does not allow tailwind intellisense

### ISSUE THREAD

**Issue by dejiemiabata** [nextui-org/nextui#1235]
### Describe the bug

just noticed this with the new 2.0.0 upgrade. Once I add nextui() to the plugins array of tailwing.config.js I am unable to get tailwind intellisense when styling but the moment I remove it from the plugins array, I get the tailwind intellisense. Wondering if this is supposed to be happening ?

### Steps to Reproduce the Bug or Issue

1. Add nextui() in plugins array of tailwind.config.js
2. Try tailwind intellisense
3.  Remove nextui() in plugins array of tailwind.config.js
4. Try tailwind intellisense

### Expected behavior

Expected behavior is for tailwind intellisense to keep functioning.

### Operating System Version

macOS M2

### Browser

Safari

**Comment by jrgarciadev** [comment]
Hey @dejiemiabata vscode intellisense works fine for me, please check this again.

https://github.com/nextui-org/nextui/assets/30373425/e04c2bd9-3e8e-4a57-a8bf-a50e50d142ff

**Comment by dejiemiabata** [comment]
seems like this issue might just be with my IntelliJ IDE. I tried on VScode and you are correct that intellisense works

**Comment by jrgarciadev** [comment]
Ok so I will close this issue 👍🏻
