### ISSUE TITLE
[BUG] - Component -Navbar with Avatar

### ISSUE THREAD

**Issue by indianboat** [nextui-org/nextui#1240]
### Describe the bug

In Navbar with Avatar Component when click on Avatar, dropdown menu opens on the bottom of the page. And also it should be closed when click on avatar again but it is not. 

Same issue "with search input" in Navbar component

### Steps to Reproduce the Bug or Issue

![bug](https://github.com/nextui-org/nextui/assets/61136840/f8bde36c-803e-4404-8fbf-6eff1c6e3b1b)

### Expected behavior

As a user i was expecting float dropdown menu

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by mustafaazad03** [comment]
Hi, 
I am interested in this issue. I will try to fix this issue.

**Comment by mustafaazad03** [comment]
Hi @indianboat ,
can you help me with how to install the modules and on which port the server will start ??

**Comment by indianboat** [comment]
> Hi @indianboat , can you help me with how to install the modules and on which port the server will start ??



> Hi @indianboat , can you help me with how to install the modules and on which port the server will start ??

Just install Nextui v2 in your nextjs project and start server using "npm run dev", it will run the server on 3000 port by default.
