### ISSUE TITLE
[BUG] - Inputs don't reset values when we're using formRef.current.reset()

### ISSUE THREAD

**Issue by gustavocadev** [nextui-org/nextui#1247]
### Describe the bug

Inputs components donts reset with formRef.current?.reset()

### Your Example Website or App

https://github.com/gustavocadev/nextjs-drizzle-orm-sqlite

### Steps to Reproduce the Bug or Issue

1. Download the projects and follow the README
2. Add a note, and we'll see the form inputs are not reset

### Expected behavior

I was expecting the form.reset() resets the `<Input />` components

### Operating System Version

Windows

### Browser

Edge

**Comment by PeterKwesiAnsah** [comment]
@gustavocadev Are the inputs controlled??

**Comment by gustavocadev** [comment]
> @gustavocadev Are the inputs controlled??

What do you mean?, I don't use any state to control the inputs

**Comment by jrgarciadev** [comment]
Hey @gustavocadev even though we use the native `input` element under the hood, the implementation is not native, it uses a controlled state that can be set from outside, here's the code https://github.com/nextui-org/nextui/blob/main/packages/components/input/src/use-input.ts#L89-L93

So if you want to clear the input values `onSubmit` / `action` you will need to control those values.

Here's an example: https://codesandbox.io/p/sandbox/festive-nova-jfxwcl?file=%2FApp.jsx%3A13%2C4&utm_medium=sandpack


You could also use a library to control the form:
https://react-hook-form.com/
https://formik.org/

**Comment by gustavocadev** [comment]
Got it! Thx
