### ISSUE TITLE
DarkTheme TextArea and Button Loading

### ISSUE THREAD

**Issue by Matteo-Peronnet** [nextui-org/nextui#126]
**Describe the bug**
When we use the dark theme with a TextArea component in the page, there is a glitch effect with the button loading.

This does not happen with InputText components.

Maybe a class conflict?

I have made a codepen accessible.

**Steps to reproduce**
TextArea **BUG** : https://codesandbox.io/s/fetch-sample-forked-re48o
Text **Working** : https://codesandbox.io/s/fetch-sample-forked-tgisw

**Expected behaviour**
There should be the same behavior when there are only InputText on the page.

**Environment / Context**
Dark theme
As soon as there is a TextArea present in the page

**Comment by jrgarciadev** [comment]
Hey @Matteo-Peronnet thanks for reporting it, could you please try it again with the latest version `v1.0.2-alpha.1`?

**Comment by jrgarciadev** [comment]
Hey @Matteo-Peronnet I tried this and it doesn't keep happening -> https://codesandbox.io/s/fetch-sample-forked-904ei?file=/src/App.js,

I'm going to close this issue, thanks for reporting it 🙌🏻
