### ISSUE TITLE
[BUG] - Dropdown backdrop error in mobile mode

### ISSUE THREAD

**Issue by HighError** [nextui-org/nextui#1266]
### Describe the bug

if you put any value other than 'transparent' in the DropDown backdrop value on mobile devices, the menu does not open and an error occurs

```
app-index.js:31 Warning: A props object containing a "key" prop is being spread into JSX:
  let props = {key: someKey, ref: ..., aria-disabled: ..., role: ..., aria-label: ..., aria-labelledby: ..., aria-describedby: ..., tabIndex: ..., data-key: ..., onPointerEnter: ..., onPointerLeave: ..., data-focus: ..., data-hover: ..., data-disabled: ..., data-selected: ..., data-pressed: ..., data-focus-visible: ..., className: ..., onClick: ..., children: ...};
  <li {...props} />
React keys must be passed directly to JSX without using spread:
  let props = {ref: ..., aria-disabled: ..., role: ..., aria-label: ..., aria-labelledby: ..., aria-describedby: ..., tabIndex: ..., data-key: ..., onPointerEnter: ..., onPointerLeave: ..., data-focus: ..., data-hover: ..., data-disabled: ..., data-selected: ..., data-pressed: ..., data-focus-visible: ..., className: ..., onClick: ..., children: ...};
  <li key={someKey} {...props} />
  ```

### Steps to Reproduce the Bug or Issue

1. Create Dropdown
2. Set backdrop value - `blur` or `opaque`
3. Open mobile mode in Chrome from dev tools
4. Click on button

### Expected behavior

Should open menu with effect, or menu without effect if not supported

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/46526245/d984a4c9-c322-4dc7-a67f-8e792645cf47

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
For the opening issue when the backdrop is set, use this option or a real device. We're working on fixing the key one.


![CleanShot 2023-08-04 at 15 43 09@2x](https://github.com/nextui-org/nextui/assets/30373425/6e3b1084-8f97-4bc5-8b47-2ac3913dc70b)
