### ISSUE TITLE
Components/Avatar

### ISSUE THREAD

**Issue by PissMan420** [nextui-org/nextui#127]
**Describe the bug**
the avatar component should have a onClick callback 

**Steps to reproduce**

**Expected behaviour**
I should be able to have a onClick={() => alert(“hi”)} prop working 

**Screenshots**
![81D5889C-E327-4E44-B207-DCA8854CBFEE](https://user-images.githubusercontent.com/37189791/147197340-6d65d85a-2c5c-480f-8774-44ca2d75fe15.png)

**Environment / Context**
- Mobile? Yes 👍 
-. iOS
- Browser and version safari 
- Device: iPhone XR 

**Additional info**

**Comment by jrgarciadev** [comment]
Hey @PissMan420 thanks for reporting it, could you please try it again with the latest version v1.0.2-alpha.1?

**Comment by PissMan420** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37189791/147428351-12235f4f-449d-49e8-8bc4-3706d26e9ced.png">
hurray it work!

**Comment by jrgarciadev** [comment]
@PissMan420  Excellent!, I'm gonna close this issue 👍🏻

**Comment by PissMan420** [comment]
@jrgarciadev What are some easy things I can do to help with this project code?
