### ISSUE TITLE
[BUG] - Template Navbar prevents getting 100 on Lighthouse accessibility score

### ISSUE THREAD

**Issue by Sinan-Karakaya** [nextui-org/nextui#1288]
### Describe the bug

(Tbh not sure if this counts as a bug, so I can move it somewhere else if needed)

Running Lighthouse on a near stock navbar from the V2 template leads to a score of 98 in accessibility. The only changes made are just different links, and no more search bar.

This happens in both desktop and mobile mod, and is because the list of items doesn't contain only <li> elements.

### Your Example Website or App

https://portfolio-oop9rd9k1-sinan-karakaya.vercel.app/fr

### Steps to Reproduce the Bug or Issue

Clone the latest next-app template.
Run Lighthouse
Get 97-98 in accessibility because of the navbar items.

### Expected behavior

Get a 100 score on accessibility when using the stock config

### Screenshots or Videos

mobile version with a score of 98:
![image](https://github.com/nextui-org/nextui/assets/91690021/323f1da6-8ceb-45e1-bb60-c4bc28b2d387)

desktop version with a score of 97:
![image](https://github.com/nextui-org/nextui/assets/91690021/12667022-a09a-4175-b4ad-48230ddd6c3a)

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Sinan-Karakaya please open this as a Feature Request in the template [repo](https://github.com/nextui-org/next-app-template), remember that the template is a good point to start but you can modify/fix any part of it including the a11y issues directly in you cloned repo.
