### ISSUE TITLE
[BUG] - Modal split into client/server error

### ISSUE THREAD

**Issue by Fami6Xx** [nextui-org/nextui#1296]
### Describe the bug

It is because the modal has these two export * from "..."

### Steps to Reproduce the Bug or Issue

1. Create a new project
2. Create 2 files (ModalClient, ModalServer)
3. In ModalClient, create just a button and Modal and into modal put {props.children} so that everything else can be server
4. In ModalServer write everything else that is needed in modal (This has to be Server component)
5. In page.js just put ModalClient and into it ModalServer
6. Build

### Expected behavior

The modal component can be split into client / server components

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/87103935/4ed8396d-c8b0-4f9d-9fc1-982cd3535342)

Server component
![](https://cdn.discordapp.com/attachments/1137450040785371166/1137450818824577237/image.png)

Client component (NavbarNextButton)
![](https://cdn.discordapp.com/attachments/1137450040785371166/1137450913116725348/image.png)

Server component (NavbarNextModal)
![](https://cdn.discordapp.com/attachments/1137450040785371166/1137451222706688081/image.png)

### Operating System Version

Windows 10

### Browser

Other (add additonal context)

**Comment by jrgarciadev** [comment]
Hey @Fami6Xx please try this with the latest version, yesterday I changed all exports to named exports

**Comment by Fami6Xx** [comment]
Seems to be working now, thanks for fast fix
