### ISSUE TITLE
[BUG] - Weird keyboard behavior when combining Input with Downshift

### ISSUE THREAD

**Issue by David3141** [nextui-org/nextui#1299]
### Describe the bug

Hello! First off, lovely component library. Been using the v2 in a small app and have been loving it! 

In that app, I'm also using `downshift` for an Autocomplete component. However, I've noticed a weird behavior after I switched from the old `<Downshift>` component to the `useCombobox` hook. When navigating through the results with the keyboard, every 2nd entry is being skipped. After trying to debug the issue, I noticed that this behavior is related to NextUI's `Input` component, which is also the reason I'm creating the issue here. When switching to a standard `<input>`, the issue disappears. My first naive guess is that the Input component somehow triggers the keyboard event twice.

I tried it in 3 different browsers (Firefox, Safari, Brave) and the issue was apparent in all of them.

If you think I should create the issue at https://github.com/downshift-js instead of here, just tell me and I will do that :)

### Your Example Website or App

- https://stackblitz.com/github/David3141/nextui-downshift-example?file=src%2Fcomponents%2FDownshiftExample.tsx
- https://github.com/David3141/nextui-downshift-example

### Steps to Reproduce the Bug or Issue

Click into the input field and navigate through the items with your keyboard

### Expected behavior

I expect the keyboard navigation to not skip every other entry. 

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/13077061/98cea97a-1ed3-49df-a5ef-348a1fa73f35

### Operating System Version

macOS

### Browser

Firefox

**Comment by 0w0k** [comment]
你@

**Comment by jrgarciadev** [comment]
Hey @David3141 please use the released Select component https://nextui.org/blog/v2.1.0

**Comment by David3141** [comment]
Hey @jrgarciadev, thanks for your reply! Unfortunately I can't do that, since I used downshift to implement an Autocomplete, not a Select. However, the issue is fixed as of version 2.1.10 (maybe earlier) 🎉 You can check out the stackblitz link above if you want, updating the package is all I did and the issue was fixed.

Thanks for this awesome library, it's easily one of my favorites I ever used. Also, loving the new components of 2.1.0!
