### ISSUE TITLE
[BUG] pnpm sb dev -p 6006 -Error: Failed to load static files, no such directory

### ISSUE THREAD

**Issue by vaynevayne** [nextui-org/nextui#1304]
### Describe the bug

clone nextui

run `pnpm run dev`

<img width="1141" alt="image" src="https://github.com/nextui-org/nextui/assets/124666577/8640c275-b7db-4693-98ba-2c46e83dd99c">

### Steps to Reproduce the Bug or Issue

same as title

### Expected behavior

same as title

### Operating System Version

macos

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Try tunning only the `pnpm sb`, the `dev` one works fine to me though

**Comment by vaynevayne** [comment]
It's still not working., Are there any other commands that need to be executed before running pnpm sb?
Also, I'm running install without any parameters, could this be the cause?

<img width="1121" alt="image" src="https://github.com/nextui-org/nextui/assets/124666577/9c7ff123-24ef-47c9-b347-7681790c1a49">
