### ISSUE TITLE
[BUG] - Tailwind classes used by NextUI components are not present in the compiled css (using pnpm)

### ISSUE THREAD

**Issue by fulopkovacs** [nextui-org/nextui#1305]
### Describe the bug

The styles that the NextUI components use does not get compiled into the css file tailwind generates.

### Steps to Reproduce the Bug or Issue

1. Create a new project with `pnpm create next-app -e https://github.com/nextui-org/next-pages-template` ([as it is recommended in the docs](https://nextui.org/docs/frameworks/nextjs#create-next-app-1))
2. Start the dev server and see that the styling is broken:
<img width="1512" alt="image" src="https://github.com/nextui-org/nextui/assets/43729152/9494d453-b99e-4554-9007-e80a68e015a6">
3. If I add all the Tailwind classes to the `safelist` in my tailwind config using a regex, the styling gets fixed (see screenshots below 👇 )

### Expected behavior

All styles used by the components are present in the css file generated by Tailwind css.

### Screenshots or Videos

❌ Project without any changes:
<img width="1512" alt="image" src="https://github.com/nextui-org/nextui/assets/43729152/a4f75be5-e512-494a-9884-1bb33c6e5ae7">

✅ When I load all tailwind styles using safelist:
```ts
import {nextui} from '@nextui-org/react'

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  darkMode: 'class',
  safelist: [{pattern: /.*/}],
  plugins: [nextui()],
}

```
<img width="1511" alt="image" src="https://github.com/nextui-org/nextui/assets/43729152/2ab2d51a-4433-4999-bc7b-6d394ccffea8">

### Operating System Version

macOS 12.2.1

### Browser

Firefox

**Comment by fulopkovacs** [comment]
I couldn't reproduce the issue with `yarn`, so I checked if I set up `.npmrc` correctly, and it turns out I didn't run `pnpm i` after modifying the `.npmrc` file. 🤦 ([docs](https://nextui.org/docs/frameworks/nextjs#setup-pnpm-optional-1))

To be fair, this step is only listed in the _Manual installation_ section (as step 5), could you add it to the [_create-next-app_](https://nextui.org/docs/frameworks/nextjs#create-next-app) section too? I think that'd be helpful.

**Comment by jrgarciadev** [comment]
Hey @fulopkovacs we have the `pnpm` step all over the place including Next.js steps https://nextui.org/docs/frameworks/nextjs#setup-pnpm-optional

**Comment by stephtr** [comment]
> @jrgarciadev is this the `.npmrc` in the root of the monorepo or in an individual app that next ui is being used in? not working for me same issue.

In a monorepo, the `.npmrc` leads to the @nextui-org packages being installed in the root of the monorepo. Therefore, you have to adapt the path in tailwindind's content config to point to the monorepo's root node_modules/... folder.

**Comment by jrgarciadev** [comment]
Hey @stephtr the tailwind's contente path is already pointed to the root node_modules

**Comment by stephtr** [comment]
> Hey @stephtr the tailwind's contente path is already pointed to the root node_modules

My comment was related to @b-bot's issue. I had the same issue. In my case, I have a monorepo with the next-app sitting at `./website`. Inside the website folder, I therefore needed the following content string to fix it: `../node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}`

**Comment by dudeofawesome** [comment]
I ran in to the same issue with an NPM workspace, and found that I could use `require.resolve` in a general solution to find the correct path regardless of repo setup:

```js
...
content: [
  ...,
  `${dirname(require.resolve('@nextui-org/theme'))}/**/*.{js,ts,jsx,tsx}`,
],
...
```
