### ISSUE TITLE
[BUG] - Navbar

### ISSUE THREAD

**Issue by sunnyRavindra** [nextui-org/nextui#1317]
### Describe the bug

React and usestate imports are not specified in the code snippet, and 'use client' not specified.

### Steps to Reproduce the Bug or Issue

the Toggle functionality cant be used without the import and 'use client'.

### Expected behavior

'use client'
import React, { useState } from 'react';

### Operating System Version

all

### Browser

Chrome

**Comment by tianenpang** [comment]
Hey @sunnyRavindra, you'll need to install the ***individual*** package and import components from there. You can find the package names in the docs for each component, for example: `@nextui-org/navbar`.

For more details, please refer to: https://nextui.org/docs/frameworks/nextjs#use-nextui-components.

![nextui org_docs_frameworks_nextjs](https://github.com/nextui-org/nextui/assets/32772271/bca8fa2e-95f7-4ba2-81e6-995ff8c495c0)
