### ISSUE TITLE
[BUG] - Typo correction in documentation

### ISSUE THREAD

**Issue by Shwetzksk** [nextui-org/nextui#1318]
### Describe the bug

I recently came across a small typographical error in the documentation . I believe this correction will help improve the overall quality of the documentation.

Documentation for table, section "Loading more data" - https://nextui.org/docs/components/table#loading-more-data

Below I had attached screenshot

![Screenshot 2023-08-08 155341](https://github.com/nextui-org/nextui/assets/59056624/503a7ece-6e0f-4423-a40c-822de8e5159d)

### Your Example Website or App

https://nextui.org/docs/components/table#loading-more-data

### Steps to Reproduce the Bug or Issue

Click on this : https://nextui.org/docs/components/table#loading-more-data

### Expected behavior

The word should be "allows" instead it is "sllows"

### Operating System Version

Windows

### Browser

Chrome

**Comment by jguddas** [comment]
Great catch, feel free to create a PR for this.
