### ISSUE TITLE
[BUG] - Dropdown single item - typescript

### ISSUE THREAD

**Issue by HighError** [nextui-org/nextui#1322]
### Describe the bug

The code is taken from the example and it throws a type error

### Steps to Reproduce the Bug or Issue

1. Copy code from example

### Expected behavior

No type error

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/46526245/38383d4e-c437-4241-a851-1f5405b54857)

### Operating System Version

Windows

### Browser

Chrome

**Comment by tianenpang** [comment]
Hi @HighError, you can add a generic type to `useState` to resolve this ts error. 

For example: 
```tsx
import type { Selection } from '@nextui-org/react';

import { useState } from 'react';


const App = () => {
  const [selectedKeys, setSelectedKeys] = useState<Selection>(new Set(['text']));

  return (
    <Dropdown>
      ...
      <DropdownMenu
        ...
        selectedKeys={selectedKeys}
        onSelectionChange={(keys) => setSelectedKeys(keys)}
      >
        ...
      </DropdownMenu>
    </Dropdown>
  );
};
```
