### ISSUE TITLE
[Feature Request] Leave Accordion item content in DOM even when closed

### ISSUE THREAD

**Issue by dmythro** [nextui-org/nextui#1327]
### Is your feature request related to a problem? Please describe.

For my particular case I'd like all Accordion content to always be in DOM — for SEO, screen readers etc. Now (v2.0.8), it's added to DOM on open and removed from DOM on item close.

### Describe the solution you'd like

It can be additional boolean prop, or maybe a default behaviour.

### Describe alternatives you've considered

Maybe I missed something and it's possible now?

**Comment by dmythro** [comment]
Thanks a lot!

**Comment by jrgarciadev** [comment]
You're welcome @dmythro 🙌🏻
