### ISSUE TITLE
[BUG] - Input is always controllable

### ISSUE THREAD

**Issue by brian-teratis** [nextui-org/nextui#1332]
### Describe the bug

When using the Input component and typing something in it, you get the warning in console:
"Warning: A component is changing an uncontrolled input to be controlled. ..."

But sometimes you don't want an input to be controllable, as you maybe just use it in a form and catch the values with the submit.
The documentation should state that you **have** to use value and onValueChange to force this input to controllable or it should be fixed that you can use this input without bothering with those two properties as well as you can just use the normal html input

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-v2mcby?file=src%2FApp.tsx&terminal=dev

### Steps to Reproduce the Bug or Issue

Just click inside the input field and start typing. The warning should pop up immediately in the browser console.

### Expected behavior

No warning in the console, as I am not providing "value" to the input at any point.

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by Shaikhaltamash861** [comment]
assign me
