### ISSUE TITLE
[BUG] - Modal not inheriting typeface / font

### ISSUE THREAD

**Issue by tomgoldsmith** [nextui-org/nextui#1336]
### Describe the bug

When using the Modal component, the base font from my application is not being inherited into the Modal. This is working fine in other places (e.g. Tabs). 

If I set my font explicitly as follows, it renders with the selected font. 

``` ts
import {
  Modal,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter
} from '@nextui-org/react';
import { Nunito } from 'next/font/google';
const font = Nunito({ subsets: ['latin'] });

export default function TestComponent() {

return (
 <Modal
        isOpen={isOpen}
        onOpenChange={onOpenChange}
        scrollBehavior="inside"
        placement="top-center"
        classNames={{
          body: `${font.className}`
        }}
      >
       <ModalContent>

       </ModalContent>
  </Modal>
)
}
```

### Steps to Reproduce the Bug or Issue

1. Add modal to UI
2. observe that content is not inheriting the font.

### Expected behavior

Modal to inherit font . 

### Operating System Version

MacOS, Node

### Browser

Chrome

**Comment by jguddas** [comment]
How are you adding the font to your app?

**Comment by tomgoldsmith** [comment]
Same as above but on the main layout.tsx. 

```
import { Nunito } from 'next/font/google';
const font = Nunito({ subsets: ['latin'] });
```

```
<main className={`${font.className} mx-auto max-w-5xl`}>
     <Providers>{children}</Providers>
 </main>
```

**Comment by jguddas** [comment]
Modals are portaled 🌀, you can apply the styles to `body` or specifying the `portalContainer` which by default is `body`.

https://nextui.org/docs/components/modal#modal-props:~:text=your%20own%20animation.-,portalContainer,-HTMLElement

**Comment by tomgoldsmith** [comment]
Ah OK, that explains it then. Easy to miss that in the docs and to be honest having never used portals before even if I had seen that property it would not have made me realise.
