### ISSUE TITLE
[BUG] - Unknown element <[object Object]> in collection in Components/Table

### ISSUE THREAD

**Issue by goggle555** [nextui-org/nextui#1342]
### Describe the bug

An error occurred when embedding a separately installed `Table` component in React Server Component.

```
- error Error: Unknown element <[object Object]> in collection.
    at getFullNode.next (<anonymous>)
    at iterateCollection.next (<anonymous>)
    at Generator.next (<anonymous>)
```

The documentation says [it supports server components](https://nextui.org/blog/nextui-v2#react-server-components-support).
Please tell me how to use it correctly.

### Steps to Reproduce the Bug or Issue

1. Create NextUI project from template:
   ```bash
   npx create-next-app -e https://github.com/nextui-org/next-app-template
   ```
2. Install individual package:
   ```bash
   npm install @nextui-org/table
   ```
3. Implement `Table` to Server Component:
   ```tsx
   // app/table/page.tsx
   import {Table, TableHeader, TableColumn, TableBody, TableRow, TableCell} from "@nextui-org/table";
   
   export default function TablePage() {
     return (
       <Table aria-label="Example static collection table">
         <TableHeader>
           <TableColumn>NAME</TableColumn>
           <TableColumn>ROLE</TableColumn>
           <TableColumn>STATUS</TableColumn>
         </TableHeader>
         <TableBody>
           <TableRow key="1">
             <TableCell>Tony Reichert</TableCell>
             <TableCell>CEO</TableCell>
             <TableCell>Active</TableCell>
           </TableRow>
           <TableRow key="2">
             <TableCell>Zoey Lang</TableCell>
             <TableCell>Technical Lead</TableCell>
             <TableCell>Paused</TableCell>
           </TableRow>
           <TableRow key="3">
             <TableCell>Jane Fisher</TableCell>
             <TableCell>Senior Developer</TableCell>
             <TableCell>Active</TableCell>
           </TableRow>
           <TableRow key="4">
             <TableCell>William Howard</TableCell>
             <TableCell>Community Manager</TableCell>
             <TableCell>Vacation</TableCell>
           </TableRow>
         </TableBody>
       </Table>
     );
   }
   ```

### Expected behavior

Table component rendered without `"use client"` statement.

### Screenshots or Videos

![localhost_3000_table](https://github.com/nextui-org/nextui/assets/53290691/5ab549f5-0ce6-4c76-9118-2f1695e343e9)

### Operating System Version

macOS

### Browser

Edge

**Comment by jrgarciadev** [comment]
Hey @goggle555 we are waiting for next [react-aria](https://github.com/adobe/react-spectrum) release to get this issue fixed, the current collection approach is compiled by next.js in a different way so it removes the `use client;` directive, in the meantime please add the directive on top of your files for collection based components -> Table, Accordion, Dropdown, and Tabs.

**Comment by goggle555** [comment]
@jrgarciadev 
OK, thank you! I will try to use `"use client"` until it is resolved :)

**Comment by movingelectrons** [comment]
has this been resolved?

**Comment by wingkwong** [comment]
@movingelectrons not yet. still pending on react-aria side. please use `use client` directive for the time being.

**Comment by PatoArtek** [comment]
Hi, i´m getting this error on "@nextui-org/tabs": "^2.0.35"

**Comment by lingfliu** [comment]
Still go the error. Should manually add "use client" at where this error is raised.
