### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by ccorreia64** [nextui-org/nextui#1343]
### Describe the bug

The variants docs has a wrong property. It should be called **compoundVariants** according to the source code
![image](https://github.com/nextui-org/nextui/assets/5826696/8ef1f536-acca-4d13-8896-1ada0dd4ec50)

![image](https://github.com/nextui-org/nextui/assets/5826696/bfef2ccf-5fee-4a30-ab39-3c0ed731b095)

### Steps to Reproduce the Bug or Issue

[Custom variants](https://nextui.org/docs/customization/custom-variants)

### Expected behavior

It should be called **compoundVariants**

### Operating System Version

All

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Good catch thank you!

Fix is ont its way
https://github.com/nextui-org/nextui/commit/cef7235c4bb3c8c3938bee2496b19beb6df83d22
