### ISSUE TITLE
[BUG] - Spinner not accepting the default transparent classes from tailwind

### ISSUE THREAD

**Issue by pedrosantosobral** [nextui-org/nextui#1344]
### Describe the bug

![Screenshot 2023-08-10 at 13 53 15](https://github.com/nextui-org/nextui/assets/33328797/04ef495e-d368-4bd9-beb6-938399ae0536)

The tailwind transparent border colors are not being applied to the Spinner circle1 and circle2:
If I add the rules manually to both circles, the spinner looks alright:
![Screenshot 2023-08-10 at 14 04 57](https://github.com/nextui-org/nextui/assets/33328797/fc6bf3e2-a68f-44fd-a12a-67176989c906)
![Screenshot 2023-08-10 at 14 06 20](https://github.com/nextui-org/nextui/assets/33328797/267f620e-3163-4f5f-87e4-fa5111eefd8c)

(missing border-r-color, border-l-color, border-top-color)

![Screenshot 2023-08-10 at 13 57 47](https://github.com/nextui-org/nextui/assets/33328797/10b50408-7cbb-4f63-90b1-7dcbcc475930)
(adding the classes manually works as intended)

Another option to fix the circle is changing the theme's foreground color to the background color, but that will break all the text, as the text uses the foreground color from the theme as well.

I leave here the tailwind config file:
![Screenshot 2023-08-10 at 14 00 53](https://github.com/nextui-org/nextui/assets/33328797/f628803c-d9f3-48b4-ae81-6e539a62f903)

### Steps to Reproduce the Bug or Issue

Add a spinner to a page

### Expected behavior

Should have transparent borders like the docs

### Operating System Version

MacOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @pedrosantosobral I checked this on the docs https://nextui.org/docs/components/spinner and border transparent classes are correctly applied 🤔 

![CleanShot 2023-08-10 at 10 12 57@2x](https://github.com/nextui-org/nextui/assets/30373425/f79e5675-d31d-41f2-8f53-c634530a3aee)

**Comment by pedrosantosobral** [comment]
> Hey @pedrosantosobral I checked this on the docs https://nextui.org/docs/components/spinner and border transparent classes are correctly applied 🤔
> 
> ![CleanShot 2023-08-10 at 10 12 57@2x](https://user-images.githubusercontent.com/30373425/259752280-f79e5675-d31d-41f2-8f53-c634530a3aee.png)

You are right, they are being applied on the docs, and the classes are added correctly on the component, on my fresh installation, its just the rules seem to "do not exist?" the classes styles are not being applied.

I checked and we have a correct tailwind version installed and no custom styles from us are being applied that would override tailwind classes. Just trying to understand where the issue is coming from.

**Comment by jrgarciadev** [comment]
You could compare your project to this one https://github.com/nextui-org/next-app-template and see where's the difference, I'll close this since it couldn't be replicated
