### ISSUE TITLE
[BUG] - compoundVariants is not working when extendVariants 

### ISSUE THREAD

**Issue by maxigs7** [nextui-org/nextui#1347]
### Describe the bug

I want to add more color variants for the button and I tried to replicate the same behavior that button is using for adding the classes. So when I use the `extendVariants` function to add a new color and compoundVariants, it is not applied.

### Your Example Website or App

https://codesandbox.io/p/sandbox/issue-compoundvariants-jktcks?file=%2FApp.jsx%3A4%2C22-4%2C36

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/p/sandbox/issue-compoundvariants-jktcks?file=%2FApp.jsx%3A4%2C22-4%2C36
2. You can check the button is not red

### Expected behavior

As a user, I expected the button change their color classes when compoundVariants is being extended.

### Operating System Version

Windows

### Browser

Edge

**Comment by jrgarciadev** [comment]
Hey @maxigs7 extendVariants doesn't include the default variants/compoundVariants, only the passed ones, so you need to create the `solid` variant in your `extendVariants` function, as follows:

```js

const NextUIButton = extendVariants(Button, {
  variants: {
    variant: {
      solid: "", // <- add the solid variant
    },
    color: {
      accent: "",
    },
  },
  compoundVariants: [
    {
      variant: "solid",
      color: "accent",
      class: "bg-red-500 text-red-900",
    },
  ],
});
```

https://codesandbox.io/p/sandbox/issue-compoundvariants-forked-m9w82g?file=%2FApp.jsx%3A3%2C1-20%2C4

Inherit the default variants/compoundVariants etc is way more complicated

**Comment by maxigs7** [comment]
Thanks, @jrgarciadev!

That worked. I think would be nice to add some notes in the docs about that, it's kinda confusing.

**Comment by jrgarciadev** [comment]
I agree with you @maxigs7 Will make this clear on the docs, thank you!

**Comment by yairopro** [comment]
```typescript
import { button, extendVariants, Button as NextUIButton } from "@nextui-org/react";

const Button = extendVariants(NextUIButton, {
  variants: {
    ...button.variants, // 🟢 extend original variants
    variant: {
      ...button.variants.variant, // 🟢 extend original variants.variant
      outlined: "border-medium bg-transparent", // then add your variant
    },
  },

  compoundVariants: [ // now you're free to compose with every variants' keys
    {
      variant: "outlined",
      color: "default",
      class: "text-default border-default-50",
    },
    {
      variant: "outlined",
      color: "primary",
      class: "text-primary border-primary-50",
    },
// ...
  ],
});
```
