### ISSUE TITLE
[BUG] - Pagination component warnings in console

### ISSUE THREAD

**Issue by MrAndriy** [nextui-org/nextui#1348]
### Describe the bug

When import Pagination component using documentation in console throws errors.
Setups:
NextJS v13 using pages routing.

### Steps to Reproduce the Bug or Issue

1. Setup NextUI providers
2. Import Pagination component
3. Use them for example  <Pagination total={10} initialPage={1} /> 
4. Open console
5. Warning: [object Object]: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
6. Warning: Invalid ARIA attribute `ariaLabel`. Did you mean `aria-label`?

### Expected behavior

As a user, I expect that these are minor bugs.
I am grateful for the opportunity to use this product and believe that you have done a great job.

### Screenshots or Videos

![Screenshot 2023-08-10 at 16 38 57](https://github.com/nextui-org/nextui/assets/59733657/4d28fdf8-5465-44da-95a7-c42535e57cf0)

### Operating System Version

macOs

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey which version are you using?

I believe this issues were already fixed:
https://github.com/nextui-org/nextui/pull/1315
https://github.com/nextui-org/nextui/pull/1314
