### ISSUE TITLE
Allow disabling the input elevation animation

### ISSUE THREAD

**Issue by remorses** [nextui-org/nextui#138]
**Is your iteration request related to a problem?**
I think the bordered Input is the best looking, but i don't like the elevation animation on focus

**Describe the solution you'd like**
Allow passing a prop like `disableElevationAnimation` that disables this behaviour (only on bordered and normal variants)

**Additional context**
This library looks awesome! really great work 🔥

**Comment by remorses** [comment]
What if we add a new token in the theme called `$inputHoverElevation` and let the user customize it via the theme? I can open a PR if you like this solution 👍

**Comment by jrgarciadev** [comment]
Hey @remorses thanks for your proposals, I'm into the first one `disableElevationAnimation`, could you please implement it? 🔥

**Comment by jrgarciadev** [comment]
Hey @remorses I'm going to close this PR since as I mentioned [here](https://github.com/nextui-org/nextui/pull/147)  we will apply this from another approach, thanks 🙏🏻
