### ISSUE TITLE
[BUG] - Tabs are not working on mobile devices

### ISSUE THREAD

**Issue by ssshojaei** [nextui-org/nextui#1387]
### NextUI Version

2.0.1

### Describe the bug

On mobile, click does not move the tabs! My component and your document were tested in Firefox 116.2.0 mobile and Chrome 115.0.5790.166.

### Steps to Reproduce the Bug or Issue

1. Launch your mobile web browser.
2. Navigate to the [Tabs documentation](https://nextui.org/docs/components/tabs).
3. Try to switch tabs

### Expected behavior

As a user, I anticipated to switch tabs just clicking on the tab title.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/26822650/2b807e1e-df02-48d7-b25c-f38ae263ede1

### Operating System Version

Android

### Browser

Chrome

**Comment by jguddas** [comment]
https://github.com/nextui-org/nextui/issues/1349

**Comment by jrgarciadev** [comment]
Closing this in favor of #1349
