### ISSUE TITLE
[BUG] - "required" prop does not get passed to input element

### ISSUE THREAD

**Issue by codedotspirit** [nextui-org/nextui#1394]
### NextUI Version

2.0.16

### Describe the bug

Hi there!
I'm running into some weird behaviour with the "Input" component. When I pass `required={true}` to the component, the input element itself does not obtain the property. 

### Steps to Reproduce the Bug or Issue

1. Import the "Input" component from `@nextui-org/input`
2. Create a component in your code and specify the `required={true}` prop
3. Check your dev tools tab

### Expected behavior

Expected behaviour: The required property gets added to the `<input>` element and prevents a form from being submitted when empty/invalid.
Actual behaviour: The property does not get added and a form with this component can be submitted even when the input is emptry/invalid.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/66965600/10151aa9-5878-40e9-9958-6784d9d0f1c8)
![image](https://github.com/nextui-org/nextui/assets/66965600/9a698f71-ff72-467e-899d-5fe29c7d8e6b)

### Operating System Version

- OS: Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @codedotspirit you have to use `isRequired` prop https://nextui.org/docs/components/input#required
