### ISSUE TITLE
[BUG] - `<AccordionItem/>` does not have `isOpen` prop typing despite being mentioned in docs

### ISSUE THREAD

**Issue by RiadhAdrani** [nextui-org/nextui#1396]
### NextUI Version

2.0.19

### Describe the bug

Despite being mentioned in the [documentation](https://nextui.org/docs/components/accordion#accordion-item-props), I keep recieving `eslint` errors:

### Your Example Website or App

https://github.com/stackblitz/core/issues/2684

### Steps to Reproduce the Bug or Issue

1. Create a new component
2. Import `Accordion` and `AccordionItem` from `@nextui-org/react` 
3. Use `<AccordionItem isOpen={isOpen}/>`
4. ESLint TS error displayed

### Expected behavior

Expect `isOpen` to be of type `boolean | undefined`

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/54232641/4f1c0a9c-55f9-4555-8079-bd4cdfe9778c)

![image](https://github.com/nextui-org/nextui/assets/54232641/0316d06c-a9ff-4912-9c49-ed03ae4da088)

### Operating System Version

WSL2 (Linux on Windows 11)  

### Browser

Edge

**Comment by hydrohiester** [comment]
Can you clarify what "Indicator props" are and how to use them? The docs say there is an "isOpen" indicator prop. https://nextui.org/docs/components/accordion#accordion-item-indicator-props
