### ISSUE TITLE
[BUG] - Input type only accepts string

### ISSUE THREAD

**Issue by dml0031** [nextui-org/nextui#1400]
### NextUI Version

2.0.18

### Describe the bug

Input component only accepts a value of type string and is forcing number input values to be converted to strings.

### Steps to Reproduce the Bug or Issue

1. Attempt to set value of Input to anything other than a string

### Expected behavior

Input allows value to be numbers in addition to strings.

### Screenshots or Videos

<img width="1396" alt="Screenshot 2023-08-14 at 10 05 04 AM" src="https://github.com/nextui-org/nextui/assets/61286551/ff9e3423-50a3-4e0b-81b5-21db1964cb1a">

### Operating System Version

Any

### Browser

Chrome

**Comment by AabhasDhaubanja** [comment]
I'll take this.

**Comment by dml0031** [comment]
Got it, that was my temporary fix at all, was just a struggle for deeply nested objects but think I have a temp solution. Appreciate it.
