### ISSUE TITLE
[BUG] - Some UI elements do not render correctly when using `yarn`

### ISSUE THREAD

**Issue by mdwelsh** [nextui-org/nextui#1401]
### NextUI Version

2.0.10

### Describe the bug

When using `yarn`, some UI elements -- such as buttons -- do not render correctly. I am using the latest version of `yarn` (4.0.0-rc48).

This is easy to reproduce and confirm using the template:

```
yarn create next-app -e https://github.com/nextui-org/next-app-template
```

The following screenshot shows what the resulting page looks like:

![Screenshot 2023-08-14 at 9 46 27 AM](https://github.com/nextui-org/nextui/assets/996692/2ccd7d2f-9ced-4322-8128-a264c1109072)

As you can see, the button elements ("Documentation" and "GitHub") are not styled appropriately.

I have been able to repro this in my own Next.js project using NextUI 2.0.10, so it is not specific to this template, as far as I can tell.

When you use the template from `npm`, it renders correctly:

```
npx create-next-app -e https://github.com/nextui-org/next-app-template
```

Screenshot:

![Screenshot 2023-08-14 at 9 45 53 AM](https://github.com/nextui-org/nextui/assets/996692/17f51f17-73ee-4fa8-b7da-3234b0fd54fc)

### Steps to Reproduce the Bug or Issue

1. Run: `yarn create next-app -e https://github.com/nextui-org/next-app-template`
2. Follow the prompts to create the app.
3. `cd` into the app directory and run `yarn && yarn dev`
4. Navigate to `http://localhost:3000`

### Expected behavior

All of the UI elements are rendered according to the same steps performed using `npm`.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @mdwelsh thanks for reporting this, could you please open this issue on the template repo? https://github.com/nextui-org/next-app-template/issues

Thanks!

**Comment by mdwelsh** [comment]
Sure, but this is not a template bug per se -- it happens when I use nextui in my own project, without the template at all.
Let me know what you prefer.

**Comment by jrgarciadev** [comment]
Ok so let's leave it here since it also happens without the template.

I'll take a look as soon as I can

Thanks!

**Comment by jrgarciadev** [comment]
Hey @mdwelsh I tested this again using the latest template and it worked fine, please try again.
