### ISSUE TITLE
[BUG] - `Accordion` doesn't handle `selectedKeys` changes

### ISSUE THREAD

**Issue by wolkyura** [nextui-org/nextui#1402]
### NextUI Version

2.0.19

### Describe the bug

It's only possible to update accordion selection through the `onSelectionChange` handler. I have attached a link to a codesandbox demonstrating a simple example where accordions are used as steps with Back/Next buttons. When trying to change `selectedKeys` - nothing happens. 

```tsx
  const [selectedKeys, setSelectedKeys] = React.useState<Selection>(new Set(["1"]));

  return (
    <Accordion
      selectedKeys={selectedKeys}
      onSelectionChange={setSelectedKeys}
    >
      <AccordionItem key="1" aria-label="Accordion 1" title="Accordion 1">
        <Button onClick={() => setSelectedKeys(new Set(["2"]))}>Next</Button>
      </AccordionItem>
    </Accordion>
)
```

### Your Example Website or App

https://codesandbox.io/p/sandbox/reverent-maria-vr8229

### Steps to Reproduce the Bug or Issue

1. Click on the link to sandbox
2. See accordions
3. Click on the "Next" button

### Expected behavior

I'd expect that it's possible to update `selectedKeys` from any handler by just returning new Set of values (`new Set()`)

### Operating System Version

macOS 12.3.1

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @wolkyura thanks for reporting this, could you please open this issue on the template repo? https://github.com/nextui-org/next-app-template/issues

Thanks!

**Comment by wolkyura** [comment]
I tried to change `Set()` to `string[]`, but it didn't work either (https://codesandbox.io/p/sandbox/busy-leftpad-5xy9p6).

The example of controlled `Acoordion` uses `new Set()` (https://nextui.org/docs/components/accordion#controlled):
<img width="400" alt="Screen Shot 2023-08-16 at 8 08 43 PM" src="https://github.com/nextui-org/nextui/assets/54850073/653afa24-7275-40d6-ac9a-91480e4f21fc">

Also, I think it's a bit confusing that state and setter have different types

<img width="400" alt="Screen Shot 2023-08-16 at 8 04 43 PM" src="https://github.com/nextui-org/nextui/assets/54850073/e18d19e4-957f-413a-b157-345d77bcc63c">

**Comment by SohamSen15** [comment]
Yeah, this is a bug. What I think is happening is that the onSelectionChange doesn't pass through the state change to the actual rendered component.

**Comment by jrgarciadev** [comment]
Hey guys, we're looking into this, but yes it is a bug. Thanks, @wolkyura for reporting it
