### ISSUE TITLE
[BUG] - It's not possible to enter space when `Input` is inside `AccordionItem`

### ISSUE THREAD

**Issue by wolkyura** [nextui-org/nextui#1405]
### NextUI Version

2.0.19

### Describe the bug

1. If the accordion is open by default, it's not possible to focus `Input` on the first click.
2. It's not possible to enter space in an `Input` that is nested within the content of `AccordionItem`.

### Your Example Website or App

https://codesandbox.io/p/sandbox/proud-bird-38k5c2

### Steps to Reproduce the Bug or Issue

1. Open codesandbox link
2. Click on the input field inside the accordion
3. See that the first click doesn't focus the input
4. Click on the input field a second time
5. Try typing any characters followed by a space and see that it's not possible to enter a space

### Expected behavior

I expect regular behavior using `Input` inside `AccordionItem`

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/54850073/71af5322-5df7-4c13-ae25-28ce0d6c6516

### Operating System Version

macOS 12.3.1

### Browser

Chrome

**Comment by austinedger0811** [comment]
My team is having a similar problem. I will update you if a solution is found.

**Comment by SohamSen15** [comment]
This problem is not occurring in Safari. It is probably a browser-based bug.

**Comment by austinedger0811** [comment]
> 

I have reproduced this problem in Safari.

**Comment by unqxl** [comment]
same issue, but entering space works after you click outside the input field and start writing again

I initially thought it was a problem with my OS or browser, but rebooting the PC had no effect on the problem, however a type of "solution" was written above

**Comment by jrgarciadev** [comment]
Hey guys this is an `Accordion` we'll look into it, the `Space` bar event to open the `AccordionItem` might be causing this

**Comment by unqxl** [comment]
is there any updates about that?

**Comment by bstivenprz** [comment]
I have the same issue with this bug, using `Input` inside `Accordion` component, my team needs some feedback asap.

**Comment by samosaboy** [comment]
This happens with Textarea as well: https://github.com/nextui-org/nextui/issues/1608

**Comment by jrgarciadev** [comment]
Fixed, install the latest version `v2.1.13`

**Comment by domenico-ruggiano** [comment]
Same think is happening using `Input` or `TextArea` inside `Table` component

**Comment by JosePadilla98** [comment]
The problem with the accordion happens to me with control or any other kind of keyboard input

**Comment by umtale** [comment]
This bug is now reprodusing in 2.6.14
