### ISSUE TITLE
 [Feature Request] Make zIndex as a prop for modal and popover

### ISSUE THREAD

**Issue by jhh09** [nextui-org/nextui#1409]
### Is your feature request related to a problem? Please describe.

This is a repeat of the same request made here the developer closed without offering a solution:

https://github.com/nextui-org/nextui/issues/667

The issue is the same in v1 as in v2.  The z-index of tooltips appears to be hardcoded to 100000 which makes it impossible to do things like have modals launched from tooltips without the tooltip hovering over.  The z-index should be configurable.

### Describe the solution you'd like

I'll defer to developer on this.  Could allow a class passed in which is applied to the container div holding the tooltip content, or add a predictable css class name developers can then override in their own css.  i.e.

.nextui-tooltip-container {
   z-index: 1000 !important;
}

### Describe alternatives you've considered

Tried manually controlling opening/closing the tooltip based on the presence of a modal, but while that can work it means devs have to re-implement the logic for hovers and such already present in nextui's tooltip.

**Comment by jrgarciadev** [comment]
Hey @jhh09 fix is on its way https://github.com/nextui-org/nextui/pull/1410

After the release you'll be able to apply a custom z-index as follows:

```tsx
 <Popover
        style={{
          zIndex: 10,
        }}
      >
        <PopoverTrigger>
          <Button>Open Popover</Button>
        </PopoverTrigger>
        <PopoverContent>
          <div className="px-1 py-2">
            <div className="text-sm font-bold">Popover Content</div>
            <div className="text-xs">This is a content of the popover</div>
          </div>
        </PopoverContent>
      </Popover>
```

**Comment by jhh09** [comment]
That's a nice clean solution, thanks.  Hopefully same change is coming to other elements where z-index matters (tooltips, modals).

**Comment by jrgarciadev** [comment]
Change on its way for `Tooltip` https://github.com/nextui-org/nextui/pull/1413, for Modal you can use the `className="z-[YOUR_Z_INDEX]"` because it is not positioned relative to a `Trigger`

**Comment by glensuarez** [comment]
Me funcionó esa opción style={{
      zIndex: 10,
    }}>

**Comment by VarunSoni1001** [comment]
Try making the component's position which is making the issue to "**static**" if it is "**relative**".
This worked for me.
