### ISSUE TITLE
Typo in Getting started section

### ISSUE THREAD

**Issue by kalwabed** [nextui-org/nextui#141]
**Describe the bug**
I found a small typo in the Getting started guide.

**Steps to reproduce**
1. Go to https://nextui.org/docs/guide/getting-started
3. Scroll down to https://nextui.org/docs/guide/getting-started#communnity
4. See a typo

**Expected behavior**
It should be **Community**, not **Communnity**.

**Comment by jrgarciadev** [comment]
Hey @kalwabed thanks for reporting it
