### ISSUE TITLE
[BUG] - Popover and dropdown doesn't open on mobile with any backdrop except from transparent

### ISSUE THREAD

**Issue by devisreal** [nextui-org/nextui#1415]
### NextUI Version

2.0.22

### Describe the bug

I am trying to use the popover component to build a menu with the blur backdrop, everything is already setup and working fine on desktop. But after testing with a smaller device the popover doesn't open on mobile until you long press the trigger , it just flashes on the page and never stays open. I tried using a dropdown and discovered it had the exact same bug.

It is the same bug if you open the docs on a mobile device, with blur and opaque backdrops you have to long press for the popover to open.

### Steps to Reproduce the Bug or Issue

1. Go to the popover components page
2. Copy any of the snippets, preferably the one with blur or opaque backdrop
3. Implement it on a page
4. Test using a mobile device
5. See bug

### Expected behavior

As a user, I expect the popover to open when pressed, not long pressed

### Operating System Version

WIndows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hi @devisreal we're following this issue here https://github.com/nextui-org/nextui/issues/1349
