### ISSUE TITLE
[BUG] - Incorrect input label position with default value (react-hook-form)

### ISSUE THREAD

**Issue by Fredcyp** [nextui-org/nextui#1416]
### NextUI Version

2.0.22

### Describe the bug

Input label is in default position while there is already an value inside the input provided by react-hook-form.
When manually modifying the value it detects the change and renders the label in the correct position, but should be correct on first render.

### Steps to Reproduce the Bug or Issue

Create input with {...register('name')} values provided by react-hook-form with a default value (value added with ref).
Then render component.

### Expected behavior

Show label in correct position when value is provided by react hook-form-form without user interaction.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/44406444/9bc44191-f016-493f-a729-d53963a9987b

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Fredcyp please use the `controlled` way.

https://www.react-hook-form.com/get-started/#IntegratingwithUIlibraries

Example: https://stackblitz.com/edit/github-osw1rc-u4xqhq?file=pages%2Findex.js
