### ISSUE TITLE
[BUG] - Button as a Link (Polymorphic) throws deprecation warning

### ISSUE THREAD

**Issue by phev8** [nextui-org/nextui#1423]
### NextUI Version

v2.0.22

### Describe the bug

When using a Button as a link (as showed in the documentation), I get a deprecation warning:
```
onClick is deprecated, please use onPress
```

### Steps to Reproduce the Bug or Issue

```
export default function App() {
  return (
    <Button
      href="https://github.com/nextui-org/nextui"
      as={Link}
      color="primary"
      showAnchorIcon
      variant="solid"
    >
      Button Link
    </Button>
  );
}
```

### Expected behavior

The button should behave as a link and navigate to the next page without depreciation warning. 

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
This warning is intentional, please use `onPress` instead of `onClick`.

here's why we use `onPress`:

https://react-spectrum.adobe.com/blog/building-a-button-part-1.html

**Comment by phev8** [comment]
I saw this, but I don't use `onClick` the `Link` component of NextUI does, doesn't it? 
Or maybe just the documentation is misguiding in this place on how to implement a link that looks like a button?

**Comment by jrgarciadev** [comment]
Oh got it!, I'll reopen this then, thanks!

**Comment by phev8** [comment]
Thank you! Appreciate the great work
Also I just noted this issue, in case it would lead to issues in future, right now, it seems to work apart from the warning.
