### ISSUE TITLE
[BUG] - React Routing not working in production build

### ISSUE THREAD

**Issue by Sohangkumar** [nextui-org/nextui#1424]
### NextUI Version

2.0.5

### Describe the bug

React-Router-Dom Routing is not working in production. I tried many times to recreate the project but it's not working with Nextui. When I tried to use other UI or without UI it's perfectly working. I think there is some issue with NextUI's newer version. As older version 1.0 also worked perfectly with my project. I found this bug only in production builds not in dev mode. 

In routing, I used a Browser router, Which shows that error 404 is not found on your page in networking. But useNavigate hook API worked perfectly from react-router-dom. In detail, I don't know why the error is poping up but this is a serious issue.popping

### Steps to Reproduce the Bug or Issue

1. Make a Vite react js project
2. Install Tailwind, NextUI 2.0 & React-router-dom
3. Create a dashboard page with routing tabs and a sidebar
4. Create components tsx file and route them using createBrowserRouter or BrowserRouter from react-router-dom
5. Link them in sidebar button
6. Try to change the content of the middle section using routing e.g. user tables, Dashboard page, user settings, etc.
7. Try dev environment working perfectly with routing (More complex try nested routing)
8. Create a production build using (e.g. npm run build)
9. deploy your production build to any server or testing environment (Nginx, apache 2 --> Docker, or deploy on github pages, render, or any other platform)
10. Try to use routing there (Issue persist here)

### Expected behavior

As a user I felt that NextUI has creating some-what a bug or something in a production environment as other libraries and even without any libraries this is working perfectly. 

### Operating System Version

Deployment Docker

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Sohangkumar please create a codesanbox/stackblitz/public repo, to see the issue.
