### ISSUE TITLE
[BUG] - Using nextjs router to navigate from Dropdown action causes runtime error in Safari

### ISSUE THREAD

**Issue by phev8** [nextui-org/nextui#1428]
### NextUI Version

v2.0.22

### Describe the bug

When using a dropdown action to navigate via NextJS's router (next/navigation), I receive a runtime error when the next page loads:
```
TypeError: Argument 1 ('root') to Document.createTreeWalker must be an instance of Node
```

The issue happens in Safari (and Firefox) but not in Chrome. 

### Steps to Reproduce the Bug or Issue

A simple Dropdown menu in a navbar like this: (in a NextJS project with app router)
```
'use client';

import React from 'react';
import { Dropdown, DropdownMenu, DropdownTrigger, DropdownItem } from "@nextui-org/dropdown";
import { Button } from "@nextui-org/button";
import { Navbar, NavbarContent, NavbarItem } from '@nextui-org/react';
import { useRouter } from 'next/navigation';

interface TestDropdownProps {
}

const TestDropdown: React.FC<TestDropdownProps> = (props) => {
    const router = useRouter();

    return (
        <Navbar isBordered maxWidth="full" shouldHideOnScroll>
            <NavbarContent justify="center">
                <Dropdown>
                    <NavbarItem>
                        <DropdownTrigger>
                            <Button
                                disableRipple
                                className="p-0 bg-transparent data-[hover=true]:bg-transparent"
                                radius="sm"
                                variant="light"
                            >
                                NavMenu
                            </Button>
                        </DropdownTrigger>
                    </NavbarItem>
                    <DropdownMenu
                        aria-label="ACME features"
                        className="w-[340px]"
                        itemClasses={{
                            base: "gap-4",
                        }}
                        onAction={(item) => {
                            console.log(item);
                            router.push(
                                '/service-status'
                            )
                        }}
                    >
                        <DropdownItem
                            key="service-status"
                            description="ACME scales apps to meet user demand, automagically, based on load."
                        >
                            Autoscaling
                        </DropdownItem>
                    </DropdownMenu>
                </Dropdown>
            </NavbarContent>
        </Navbar >
    );
};

export default TestDropdown;
```

### Expected behavior

Since we cannot pass href or Link to the dropdown items, I would expect we can navigate with the router from within the onAction. It seems to work in Chrome but not in Safari (macOS)

### Operating System Version

macOS

### Browser

Safari

**Comment by jackinthebottle** [comment]
so do I.

I'm using nextjs 13.0.

Uncaught TypeError: Failed to execute 'createTreeWalker' on 'Document': parameter 1 is not of type 'Node'.
    at $9bf71ea28793e738$export$2d6ec8fc375ceafa (webpack-internal:///(app-client)/./node_modules/@react-aria/focus/dist/import.mjs:597:27)
    at $9bf71ea28793e738$var$focusFirstInScope (webpack-internal:///(app-client)/./node_modules/@react-aria/focus/dist/import.mjs:423:18)
    at eval (webpack-internal:///(app-client)/./node_modules/@react-aria/focus/dist/import.mjs:581:33)

**Comment by AlecRust** [comment]
I get the same error using the example code from https://nextui.org/docs/components/navbar#with-avatar

Same error in any browser for me.

**Comment by Seeeev** [comment]
> ### NextUI Version
> v2.0.22
> 
> ### Describe the bug
> When using a dropdown action to navigate via NextJS's router (next/navigation), I receive a runtime error when the next page loads:
> 
> ```
> TypeError: Argument 1 ('root') to Document.createTreeWalker must be an instance of Node
> ```
> 
> The issue happens in Safari (and Firefox) but not in Chrome.
> 
> ### Your Example Website or App
> _No response_
> 
> ### Steps to Reproduce the Bug or Issue
> A simple Dropdown menu in a navbar like this: (in a NextJS project with app router)
> 
> ```
> 'use client';
> 
> import React from 'react';
> import { Dropdown, DropdownMenu, DropdownTrigger, DropdownItem } from "@nextui-org/dropdown";
> import { Button } from "@nextui-org/button";
> import { Navbar, NavbarContent, NavbarItem } from '@nextui-org/react';
> import { useRouter } from 'next/navigation';
> 
> interface TestDropdownProps {
> }
> 
> const TestDropdown: React.FC<TestDropdownProps> = (props) => {
>     const router = useRouter();
> 
>     return (
>         <Navbar isBordered maxWidth="full" shouldHideOnScroll>
>             <NavbarContent justify="center">
>                 <Dropdown>
>                     <NavbarItem>
>                         <DropdownTrigger>
>                             <Button
>                                 disableRipple
>                                 className="p-0 bg-transparent data-[hover=true]:bg-transparent"
>                                 radius="sm"
>                                 variant="light"
>                             >
>                                 NavMenu
>                             </Button>
>                         </DropdownTrigger>
>                     </NavbarItem>
>                     <DropdownMenu
>                         aria-label="ACME features"
>                         className="w-[340px]"
>                         itemClasses={{
>                             base: "gap-4",
>                         }}
>                         onAction={(item) => {
>                             console.log(item);
>                             router.push(
>                                 '/service-status'
>                             )
>                         }}
>                     >
>                         <DropdownItem
>                             key="service-status"
>                             description="ACME scales apps to meet user demand, automagically, based on load."
>                         >
>                             Autoscaling
>                         </DropdownItem>
>                     </DropdownMenu>
>                 </Dropdown>
>             </NavbarContent>
>         </Navbar >
>     );
> };
> 
> export default TestDropdown;
> ```
> 
> ### Expected behavior
> Since we cannot pass href or Link to the dropdown items, I would expect we can navigate with the router from within the onAction. It seems to work in Chrome but not in Safari (macOS)
> 
> ### Screenshots or Videos
> _No response_
> 
> ### Operating System Version
> macOS
> 
> ### Browser
> Safari

set the key of the DropdownItem component to a path format '/service-status' then at the router.push() use the toString function of the item, 'router.push(item.toString)'.

**Comment by karim2012** [comment]
I have this error too, when will it be fixed?

**Comment by jrgarciadev** [comment]
Hey guys we added Client Side Routing support in v2.2.0

https://nextui.org/docs/guide/routing
https://nextui.org/blog/v2.2.0#client-side-routing

**Comment by karim2012** [comment]
@jrgarciadev I updated the version of nextui, I modified the Provider with:<NextUIProvider navigate={router.push}>

But when I try to click on the <Link /> imported from nextui I get this error:
`TypeError: Argument 1 ('root') to Document.createTreeWalker must be an instance of Node`

Actually the link works, in the sense that the page is changed correctly, but for some reason this error appears, even if it does not seem to affect the operation of my app

**Comment by markwilson** [comment]
I'm having the same issue with a Button in a dropdown. It doesn't seem to matter whether I use the Client Side Routing approach, or `const router = useRouter()` and `router.push(...)`.

My stack trace points to it coming from `@react-aria/focus` and there's [a similar issue that's just recently been closed on the spectrum repo](https://github.com/adobe/react-spectrum/issues/4514). However when I try using the nightly build of that repo, I still encounter the same issue.
