### ISSUE TITLE
Input clearable is getting emptied on submit

### ISSUE THREAD

**Issue by Oleven** [nextui-org/nextui#143]
**Describe the bug**
If you put the *clearable* attribute on an Input, pressing enter on it clears the input itself before propagating to the form submit button.
Pressing enter should result in a form submit with such input valued at what the user typed, instead the input gets cleared.
The same doesn't apply if you manually click on the submit button, and this is related to the nature of the button, which gets priority over the *submit* one. Forcing the clearable button to have a **type='button'** would resolve the issue.

**Steps to reproduce**
Create a new react project (I use Vite, but use whatever)
Install NextUI
Write the following component:
`import { Button, Input, Spacer } from "@nextui-org/react";
import React from "react";
const LoginFormTest = ({}) => {
  return (
    <form
      onSubmit={e => {
        e.preventDefault();
        e.stopPropagation();
        console.log("ok");
      }}>
      <Input clearable contentRight={<i className='fas fa-user'></i>} fullWidth size='lg' bordered placeholder='Username' type='text' />
      <Spacer y={2} />
      <Button type='submit' color='primary' style={{ width: "100%" }}>
        Send
      </Button>
      <Spacer y={2} />
    </form>
  );
};

export default LoginFormTest;`

**Expected behaviour**
The input shouldn't be cleared

**Screenshots**
In the following gif, you can clearly see the moment in which 
![NewRecording-_1_-_online-video-cutter com_](https://user-images.githubusercontent.com/50867388/150533487-b05495f9-02b1-457d-8e6e-5c1eb023bd9b.gif)

**Environment / Context**
- Desktop
- Windows 10
- Chrome latest
- PC

**Comment by jrgarciadev** [comment]
Hey @Oleven thanks for reporting it, I will check this out asap
