### ISSUE TITLE
[BUG] - Accordion hideIndicator doesn't work

### ISSUE THREAD

**Issue by juan-manuel-alberro** [nextui-org/nextui#1430]
### NextUI Version

2.0.22

### Describe the bug

The `hideIndicator` prop in the `AccordionItem` don't hide the indicator.

```jsx
  <AccordionItem
    key="dashboard"
    title="Dashboard"
    startContent={<PieChart />}
    hideIndicator
  >
    The content
  </AccordionItem>
```

![image](https://github.com/nextui-org/nextui/assets/7114488/06090320-0859-4fbe-ac05-fc18a8b32d5a)

### Steps to Reproduce the Bug or Issue

1. Create an Accordion
2. Add the `hideIndicator` prop

### Expected behavior

The arrow on the right must be hidden.

### Operating System Version

Linux

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @juan-manuel-alberro it works fine for me 🤔 

https://codesandbox.io/p/sandbox/frosty-star-7xvt62?file=/App.jsx:9,16-9,29&utm_medium=sandpack

**Comment by juan-manuel-alberro** [comment]
@jrgarciadev Oh I see, is set in the `Accordion` and not in the `AccordionItem`.
Why the `AccordionItem` accepted the `hideIndicator` prop as valid then 🤔 (plus the documentation mentioned that in the `AccordionItem` - https://nextui.org/docs/components/accordion#accordion-item-props)

**Comment by jrgarciadev** [comment]
Oh I get you, it should work with AccordionItem too, I'll take a look at it later today, use it in `Accordion` in the meantime
