### ISSUE TITLE
[BUG] - YOUR_ISSUE_TITLE_HERE_REPLACE_ME

### ISSUE THREAD

**Issue by windend** [nextui-org/nextui#1443]
### NextUI Version

2.0.24

### Describe the bug

Error: Unknown element <[object Object]> in collection.  use dropdown  component

### Steps to Reproduce the Bug or Issue

import dropdown demo

### Expected behavior

use normal

### Operating System Version

macos

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Duplicated https://github.com/nextui-org/nextui/issues/1403
