### ISSUE TITLE
[Feature Request] Please add RSS

### ISSUE THREAD

**Issue by kuchta** [nextui-org/nextui#1444]
### Is your feature request related to a problem? Please describe.

Please add RSS feed to your blog at https://nextui.org/blog

### Describe the solution you'd like

...

### Describe alternatives you've considered

...

**Comment by jrgarciadev** [comment]
NextUI blog already has a RSS feed, https://nextui.org/feed.xml

**Comment by kuchta** [comment]
Hi @jrgarciadev 

Thank you, but I would be nice if site has auto-discovery of that feed: https://dri.es/rss-auto-discovery
