### ISSUE TITLE
[BUG] - Select popover closes on label pointer up event

### ISSUE THREAD

**Issue by TechnologicNick** [nextui-org/nextui#1457]
### NextUI Version

2.1.0

### Describe the bug

Clicking the `<label>` element opens the Select popover as expected, but it immediately closes when releasing the mouse button.

### Your Example Website or App

https://codesandbox.io/p/sandbox/snowy-sun-8y839x?file=%2FApp.jsx%3A8%2C14&utm_medium=sandpack

### Steps to Reproduce the Bug or Issue

1. Go to the example.
2. Click and hold down the left mouse button on "Favorite Animal".
3. Release the mouse button and observe the Select popover closes.

### Expected behavior

As a user, I expect the Select popover to stay open, but I am seeing that it closes.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/20935774/5b10df91-6428-42a2-b58b-e8cb6189b41a

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Fixed: https://github.com/nextui-org/nextui/pull/1455

**Comment by TechnologicNick** [comment]
Nice
