### ISSUE TITLE
[Feature Request] Incompatibility with Server component in NextJS

### ISSUE THREAD

**Issue by gaurav6386** [nextui-org/nextui#1459]
### Is your feature request related to a problem? Please describe.

This feature is in regards to Abstract UI Component of NextUI for NextJS. Currently most of the NextUI component are structured as client component utilising the react hooks inside of each component. As a result we cannot specfically make use of NextJS SSR.
Let's take a specific case of rendering a NavBar:
To render a NavBar in NextJS it is recommended to breakdown the NavBar into the client and server component such that all the interactive logic is handled by client component and remaining static content, link, branding element etc as server component for SEO optimisation.
But the way the components are written in NextUI it completely eliminate the use of Server component from NextJS. So basically even if I write avatar component it can't be rendered as server component because of internal use createContext and other hooks.
Here is sample implementation that should be expected to work in NextJS while using composition
```tsx
//components/NavBar/NavClientWrapper.tsx
"use client"

import { Navbar, NavbarContent, NavbarMenuToggle } from "@nextui-org/react"
import { useState } from "react";

export default function NavClientWrapper({
    children,
  }: {
    children: React.ReactNode
  }) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <Navbar
      isBordered
      isMenuOpen={isMenuOpen}
      onMenuOpenChange={setIsMenuOpen}
    >
      <NavbarContent className="sm:hidden" justify="start">
        <NavbarMenuToggle aria-label={isMenuOpen ? "Close menu" : "Open menu"} />
      </NavbarContent>
      {children}
    </Navbar>
  )
}  

//components/NavBar/Content.tsx
import {NavbarBrand, NavbarContent, NavbarItem, Link, Button, NavbarMenu, NavbarMenuToggle, NavbarMenuItem} from "@nextui-org/react";
import NavClientWrapper from "./NavWrapper";

export default function AppNavBar() {
  
  const menuItems = [
    "Profile",
    "Dashboard",
    "Activity",
    "Analytics",
    "System",
    "Deployments",
    "My Settings",
    "Team Settings",
    "Help & Feedback",
    "Log Out",
  ];

  return (
    <NavClientWrapper>
        <NavbarContent className="sm:hidden pr-3" justify="center">
          <NavbarBrand>
            <p className="font-bold text-inherit">Ticketing.Dev</p>
          </NavbarBrand>
        </NavbarContent>

        <NavbarContent className="hidden sm:flex gap-4" justify="center">
          <NavbarBrand>
            <p className="font-bold text-inherit">Ticketing.Dev</p>
          </NavbarBrand>
          <NavbarItem>
            <Link color="foreground" href="#">
              My Tickets
            </Link>
          </NavbarItem>
          <NavbarItem isActive>
            <Link href="#" aria-current="page">
              Orders
            </Link>
          </NavbarItem>
          <NavbarItem>
            <Link color="foreground" href="#">
              Cart
            </Link>
          </NavbarItem>
        </NavbarContent>

        <NavbarContent justify="end">
          <NavbarItem className="hidden lg:flex">
            <Link href="#">Login</Link>
          </NavbarItem>
          <NavbarItem>
            <Button as={Link} color="warning" href="#" variant="flat">
              Sign Up
            </Button>
          </NavbarItem>
        </NavbarContent>

        <NavbarMenu>
          {menuItems.map((item, index) => (
            <NavbarMenuItem key={`${item}-${index}`}>
              <Link
                className="w-full"
                color={
                  index === 2 ? "warning" : index === menuItems.length - 1 ? "danger" : "foreground"
                }
                href="#"
                size="lg"
              >
                {item}
              </Link>
            </NavbarMenuItem>
          ))}
        </NavbarMenu>
    </NavClientWrapper>
  );
}

// /app/layout.tsx
import { Provider } from './provider'
import AppNavBar from '@/components/common/NavBar/Content'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider attribute="class" defaultTheme="dark">
          <AppNavBar />
          {children}
        </Provider>
      </body>
    </html>
  )
}
```

Since the component like NavbarBrand, NavbarContent, NavbarItem etc. in Content.tsx uses createContext, useMemo and other react hook it is not possible to acheive the above implementation. 

Also, it's worth noting that responsive design using CSS-in-JS libraries and SSR in Next.js don't always seamlessly complement each other.

### Describe the solution you'd like

I know the way this library is written it would be very hard to adjust to NextJS paradigm. And it would be better if lead developer were to bring in the composition pattern described in the NextJS doc into this library.
My take on this would be to be able to completely utilise the functionality of NextJS it would be optimal to breakdown the existing UI component into separate client and server components such that the component which involve user interactivity are left as it is but the components that are mostly static and are use by web crawler for SEO to be rewritten with NextJS in mind.
[Please refer](https://nextjs.org/docs/getting-started/react-essentials#thinking-in-server-components)
![image](https://github.com/nextui-org/nextui/assets/60260013/032e1029-cd01-4e81-8efa-7f8db9194c21)

### Describe alternatives you've considered

Currently I am reverting back to tailwind since it is more permissive and compatible with server component in NextJS and uses mediaqueries for responsive layout.

**Comment by Tuan2002** [comment]
Hey you, Client component with NextJS is so magic =)). It's not really CSR, it still render stactic elenment in server (you can view page source to see your content) but state logic will be processed in the client.

**Comment by jrgarciadev** [comment]
Hey @gaurav6386, all NextUI components are compatible with "SSR", I think you have a confusion with the `use client;` directive, using the `use client;` directive doesn't mean the component will no longer render in the server, it renders and then it is hydrated in the client, you can see those components as how Next.js with `pages` directory works.

I recommend you to carefully read the Next.js React Essentials documentation: https://nextjs.org/docs/getting-started/react-essentials#client-components

![CleanShot 2023-08-21 at 18 09 25](https://github.com/nextui-org/nextui/assets/30373425/fd87d9a8-4bfa-403d-9018-6ccba829dfd4)

You can also check this video: https://www.youtube.com/watch?v=6jM_0wDOw4g&t=1s

It is worth saying that NextUI also includes some components that can be fully rendered on the server (Server components), you can differentiate them with this tag:

![CleanShot 2023-08-21 at 18 14 30](https://github.com/nextui-org/nextui/assets/30373425/49366db8-960f-4564-8213-aec54f591e71)


I hope my answer clarifies your doubts on this subject.
