### ISSUE TITLE
[BUG] - Example code in async pagination display wrong content

### ISSUE THREAD

**Issue by TzeHimSung** [nextui-org/nextui#1466]
### NextUI Version

2.1.3

### Describe the bug

nextui docs provided example `Async Pagination` code at `Table` component page. However, page 2 and 3 display same content at that example (it make request at page 2 content). Page 4 and 5 display same content also (make request at page 3 content).

### Steps to Reproduce the Bug or Issue

1. Go to `https://nextui.org/docs/components/table#async-pagination`
2. Click page 2
3. Click page 3 (page content not change...why?)
4. Click page 4 (page content changed but display page 3 content)
5. Click page 5 (page content not change again)

### Expected behavior

Click every page and display source content

### Operating System Version

Windows

### Browser

Chrome

**Comment by TzeHimSung** [comment]
Add another steps to reproduce the bug:
1. Go to `https://nextui.org/docs/components/table#async-pagination`
2. Click page 3 or other one behind
3. Tables shows nothing

**Comment by ssidharth010** [comment]
![image](https://github.com/nextui-org/nextui/assets/47074625/63bb6839-0b30-4d58-a8f4-d13ba64ca70e)
The page seems to be setting correctly but the cursor value is somehow not getting updated.
