### ISSUE TITLE
[BUG] - Select

### ISSUE THREAD

**Issue by JoaquinLeonq98** [nextui-org/nextui#1470]
### NextUI Version

2.1.3

### Describe the bug

When using the component import [import {Select, SelectItem} from "@nextui-org/react";], it is detected as a syntax error and cannot be used.

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

N/A

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/88640299/8f733ede-c1a1-41ba-951b-3a5d3fc4f6cd)

### Operating System Version

Windows

### Browser

Firefox

**Comment by jrgarciadev** [comment]
Maybe this examples can help you

https://codesandbox.io/p/sandbox/c7jgc2?file=/App.jsx:1,1&utm_medium=sandpack

But that's definitely not an issue with the Select component.

Btw if you pass the items prop to the Select you don't need to use the "map" function check the dynamic example: https://nextui.org/docs/components/select#dynamic-items
