### ISSUE TITLE
[BUG] - NEXT UI is not compatible with typesscript 

### ISSUE THREAD

**Issue by AhmedShehata98** [nextui-org/nextui#1479]
### NextUI Version

2.1.5

### Describe the bug

I am using next js 13 with app directory and typescript
When imports and packages from " @nextui-org/react " it popup issue from the typescript saying :

Cannot find module '@nextui-org/react' or its corresponding type declarations.ts(2307)

### Steps to Reproduce the Bug or Issue

1.  when i create Providers.tsx file and  import { NextUIProvider } from "@nextui-org/react";
2. create fn component : function Providers({ children }: { children: React.ReactNode }) {
  return <NextUIProvider>{children}</NextUIProvider>;
}
3. Appearing issue message: Cannot find module '@nextui-org/react' or its corresponding type declarations.ts(2307)

### Expected behavior

as a user i expected import { NextUIProvider } from "@nextui-org/react"; but got issue message Cannot find module '@nextui-org/react' or its corresponding type declarations.ts(2307)

### Operating System Version

windows 11

### Browser

Edge

**Comment by jrgarciadev** [comment]
NextUI has its types declarations built-in, Try deleting your node_modules, and re-installing again, but it looks like you don't have the package correctly installed

This indicates that NextUI has its typescript declarations in the same package.
![CleanShot 2023-08-23 at 10 54 13@2x](https://github.com/nextui-org/nextui/assets/30373425/fc2c84a9-17aa-4bf5-b6ff-2d1e1ab2602b)


You can also check the Next.js + NextUI templates:
https://github.com/nextui-org/next-app-template. (App directory)
https://github.com/nextui-org/next-pages-template (Pages directory)

**Comment by AhmedShehata98** [comment]
It works, thanks 🙏

في الأربعاء، ٢٣ أغسطس ٢٠٢٣ ١٦:٥٦ Junior Garcia ***@***.***>
كتب:
