### ISSUE TITLE
[BUG] - Select component and react-hook-form: Can't set selected item

### ISSUE THREAD

**Issue by matthiasfeist-foodfacts** [nextui-org/nextui#1480]
### NextUI Version

2.1.5

### Describe the bug

When using the new Select component together with react form hook, it seems that the react form hook can't set the selected item based on it's internal state.

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-uxr8cy?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

Create a form with react-hook-form and set up a Select component like this:
```javascript
import * as React from 'react';
import './style.css';

import { Select, SelectItem } from '@nextui-org/react';
import { useForm, SubmitHandler } from 'react-hook-form';

type Inputs = {
  example: string;
};

export default function App() {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<Inputs>({
    defaultValues: {
      example: 'two',
    },
  });

  return (
    <div>
      <form>
        <Select label="Select an animal" {...register('example')}>
          <SelectItem key={'one'} value={'one'}>
            one
          </SelectItem>
          <SelectItem key={'two'} value={'two'}>
            two
          </SelectItem>
        </Select>
      </form>
    </div>
  );
}
```

### Expected behavior

in the example above, the expected behavior is that the second list item is selected in the Select component. Just like the HTML select tag behaves.

### Operating System Version

macOS ventura

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @matthiasfeist-foodfacts being this a UI library you need to apply the controlled way to connect react-hook-form to the `Select` component, Here are the docs from the `react-hook-form` team:
https://react-hook-form.com/get-started#IntegratingwithUIlibraries


Here's an example:
https://codesandbox.io/p/sandbox/compassionate-franklin-xnwxt8?file=/App.jsx:135,49&utm_medium=sandpack

**Comment by knightvibhi** [comment]
@jrgarciadev  Hey, im trying to set a default value to select component but it seems to the validation check fails event though im setting the `field.value` to the desired value
