### ISSUE TITLE
[Feature Request] UnoCSS support

### ISSUE THREAD

**Issue by Yiniau** [nextui-org/nextui#1481]
### Is your feature request related to a problem? Please describe.

I usually use unocss for development, and some existing projects also use unocss, which will lead to the inability to use nextui due to a css solution

### Describe the solution you'd like

support unocss

### Describe alternatives you've considered

maybe provide a version without tailwind

**Comment by jrgarciadev** [comment]
Hey @Yiniau I appreciate your suggestion, however removing TailwindCSS to provide support to X frameworks means re-doing all components styles again, which is definitely not a target for us. From my understanding UnoCSS supports TailwindCSS classes so you could give it a try, but I haven't tested it yet.
