### ISSUE TITLE
[BUG] - NavBar Menu broken 

### ISSUE THREAD

**Issue by a-Marino** [nextui-org/nextui#1484]
### NextUI Version

2.1.5

### Describe the bug

![image](https://github.com/nextui-org/nextui/assets/70865138/6030d2de-099d-4fab-9801-979d04fd3ef2)
Navbar Menu is broken, i've copied the code from the doc and changed only the logo and doesnt work 

### Steps to Reproduce the Bug or Issue

Open navbar with menu

### Expected behavior

open navbar menu

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/70865138/8eeaf937-f3e4-4877-95bc-4445153b228a)
![image](https://github.com/nextui-org/nextui/assets/70865138/facb1669-853d-4627-944b-48a777601fe4)

### Operating System Version

Windows

### Browser

Opera

**Comment by jrgarciadev** [comment]
Hey @a-Marino looks like your application is not applying the styles correctly. Check your TailwindCSS setup and make sure everything is correct.

You can follow the template repositories we have as guidance:

https://github.com/nextui-org/next-app-template
https://github.com/nextui-org/next-pages-template

**Comment by a-Marino** [comment]
Nop, everything its set up right, the only thing i only changed the project from npm to pnpm

**Comment by jrgarciadev** [comment]
@a-Marino  Did you try using the templates? , if the issue were a NextUI issue it shouldn't work anywhere, so I believe it is a setup/environment issue
