### ISSUE TITLE
Module '"@nextui-org/react"' has no exported member 'CssBaseline'.

### ISSUE THREAD

**Issue by KevinKeyssx** [nextui-org/nextui#1487]
When i try to import the CssBaseline i have the next issue:

Module '"@nextui-org/react"' has no exported member 'CssBaseline'.ts(2305)

'use client'

import { useServerInsertedHTML } from 'next/navigation'
import {NextUIProvider, CssBaseline} from "@nextui-org/react";
import { Header } from "./Header";

export function Providers({ 
    children 
}: { 
    children: React.ReactNode 
}) {
    useServerInsertedHTML(() => {
        return <>{CssBaseline.flush()}</>
    })
    return (
        <NextUIProvider>
            <Header />
            {children}
        </NextUIProvider>
    )
}

**Comment by jrgarciadev** [comment]
NextUI v2 doesn't have a CssBaseline, check the installation steps https://nextui.org/docs/guide/installation
