### ISSUE TITLE
TEXT COMPONENT NOT AVAILABLE

### ISSUE THREAD

**Issue by Kanyoroh** [nextui-org/nextui#1489]
### NextUI Version

BETA

### Describe the bug

export 'default' (imported as 'Text') was not found in '@nextui-org/react' (possible exports: Accordion, AccordionItem, Avatar, AvatarGroup, AvatarGroupProvider, AvatarIcon, Badge, Button, ButtonGroup, ButtonGroupProvider, Card, CardBody, CardFooter, CardHeader, CardProvider, Checkbox, CheckboxGroup, CheckboxGroupProvider, CheckboxIcon, Chip, CircularProgress, Code, Divider, Dropdown, DropdownItem, DropdownMenu, DropdownSection, DropdownTrigger, FreeSoloPopover, Image, Input, Kbd, Link, LinkIcon, Listbox, ListboxItem, ListboxSection, Menu, MenuItem, MenuSection, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader, ModalProvider, Navbar, NavbarBrand, NavbarContent, NavbarItem, NavbarMenu, NavbarMenuItem, NavbarMenuToggle, NavbarProvider, NextUIProvider, Pagination, PaginationCursor, PaginationItem, PaginationItemType, Popover, PopoverContent, PopoverProvider, PopoverTrigger, Progress, Radio, RadioGroup, RadioGroupProvider, ScrollShadow, Select, SelectItem, SelectSection, Skeleton, Snippet, Spacer, Spinner, Switch, Tab, Table, TableBody, TableCell, TableColumn, TableHeader, TableRow, Tabs, Textarea, Tooltip, User, VisuallyHidden, absoluteFullClasses, accordion, accordionItem, avatar, avatarGroup, badge, baseStyles, button, buttonGroup, card, checkbox, checkboxGroup, chip, circularProgress, cn, code, colorVariants, colors, commonColors, dataFocusVisibleClasses, divider, drip, dropdown, dropdownItem, dropdownMenu, dropdownSection, extendVariants, focusVisibleClasses, forwardRef, getKeyValue, groupDataFocusVisibleClasses, image, input, kbd, link, linkAnchorClasses, listbox, listboxItem, listboxSection, mapPropsVariants, mapPropsVariantsWithCommon, mappedSpacingScaleKeys, menu, menuItem, menuSection, modal, navbar, nextui, pagination, popover, progress, radio, radioGroup, ringClasses, scrollShadow, select, semanticColors, skeleton, snippet, spacer, spacingScaleKeys, spinner, table, tabs, toIterator, toggle, translateCenterClasses, tv, useAccordion, useAccordionItem, useAvatar, useAvatarGroup, useAvatarGroupContext, useBadge, useButton, useButtonGroup, useButtonGroupContext, useCard, useCardContext, useCheckbox, useCheckboxGroup, useCheckboxGroupContext, useChip, useCode, useDisclosure, useDivider, useDropdown, useImage, useInput, useKbd, useLink, useListbox, useMenu, useModal, useModalContext, useNavbar, useNavbarContext, usePagination, usePaginationItem, usePopover, usePopoverContext, useProgress, useRadio, useRadioGroup, useRadioGroupContext, useScrollShadow, useSelect, useSkeleton, useSnippet, useSpacer, useSpinner, useSwitch, useTable, useTabs, useTooltip, useUser, user)

### Steps to Reproduce the Bug or Issue

export 'default' (imported as 'Text') was not found in '@nextui-org/react' (possible exports: Accordion, AccordionItem, Avatar, AvatarGroup, AvatarGroupProvider, AvatarIcon, Badge, Button, ButtonGroup, ButtonGroupProvider, Card, CardBody, CardFooter, CardHeader, CardProvider, Checkbox, CheckboxGroup, CheckboxGroupProvider, CheckboxIcon, Chip, CircularProgress, Code, Divider, Dropdown, DropdownItem, DropdownMenu, DropdownSection, DropdownTrigger, FreeSoloPopover, Image, Input, Kbd, Link, LinkIcon, Listbox, ListboxItem, ListboxSection, Menu, MenuItem, MenuSection, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader, ModalProvider, Navbar, NavbarBrand, NavbarContent, NavbarItem, NavbarMenu, NavbarMenuItem, NavbarMenuToggle, NavbarProvider, NextUIProvider, Pagination, PaginationCursor, PaginationItem, PaginationItemType, Popover, PopoverContent, PopoverProvider, PopoverTrigger, Progress, Radio, RadioGroup, RadioGroupProvider, ScrollShadow, Select, SelectItem, SelectSection, Skeleton, Snippet, Spacer, Spinner, Switch, Tab, Table, TableBody, TableCell, TableColumn, TableHeader, TableRow, Tabs, Textarea, Tooltip, User, VisuallyHidden, absoluteFullClasses, accordion, accordionItem, avatar, avatarGroup, badge, baseStyles, button, buttonGroup, card, checkbox, checkboxGroup, chip, circularProgress, cn, code, colorVariants, colors, commonColors, dataFocusVisibleClasses, divider, drip, dropdown, dropdownItem, dropdownMenu, dropdownSection, extendVariants, focusVisibleClasses, forwardRef, getKeyValue, groupDataFocusVisibleClasses, image, input, kbd, link, linkAnchorClasses, listbox, listboxItem, listboxSection, mapPropsVariants, mapPropsVariantsWithCommon, mappedSpacingScaleKeys, menu, menuItem, menuSection, modal, navbar, nextui, pagination, popover, progress, radio, radioGroup, ringClasses, scrollShadow, select, semanticColors, skeleton, snippet, spacer, spacingScaleKeys, spinner, table, tabs, toIterator, toggle, translateCenterClasses, tv, useAccordion, useAccordionItem, useAvatar, useAvatarGroup, useAvatarGroupContext, useBadge, useButton, useButtonGroup, useButtonGroupContext, useCard, useCardContext, useCheckbox, useCheckboxGroup, useCheckboxGroupContext, useChip, useCode, useDisclosure, useDivider, useDropdown, useImage, useInput, useKbd, useLink, useListbox, useMenu, useModal, useModalContext, useNavbar, useNavbarContext, usePagination, usePaginationItem, usePopover, usePopoverContext, useProgress, useRadio, useRadioGroup, useRadioGroupContext, useScrollShadow, useSelect, useSkeleton, useSnippet, useSpacer, useSpinner, useSwitch, useTable, useTabs, useTooltip, useUser, user)

### Expected behavior

export 'default' (imported as 'Text') was not found in '@nextui-org/react' (possible exports: Accordion, AccordionItem, Avatar, AvatarGroup, AvatarGroupProvider, AvatarIcon, Badge, Button, ButtonGroup, ButtonGroupProvider, Card, CardBody, CardFooter, CardHeader, CardProvider, Checkbox, CheckboxGroup, CheckboxGroupProvider, CheckboxIcon, Chip, CircularProgress, Code, Divider, Dropdown, DropdownItem, DropdownMenu, DropdownSection, DropdownTrigger, FreeSoloPopover, Image, Input, Kbd, Link, LinkIcon, Listbox, ListboxItem, ListboxSection, Menu, MenuItem, MenuSection, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader, ModalProvider, Navbar, NavbarBrand, NavbarContent, NavbarItem, NavbarMenu, NavbarMenuItem, NavbarMenuToggle, NavbarProvider, NextUIProvider, Pagination, PaginationCursor, PaginationItem, PaginationItemType, Popover, PopoverContent, PopoverProvider, PopoverTrigger, Progress, Radio, RadioGroup, RadioGroupProvider, ScrollShadow, Select, SelectItem, SelectSection, Skeleton, Snippet, Spacer, Spinner, Switch, Tab, Table, TableBody, TableCell, TableColumn, TableHeader, TableRow, Tabs, Textarea, Tooltip, User, VisuallyHidden, absoluteFullClasses, accordion, accordionItem, avatar, avatarGroup, badge, baseStyles, button, buttonGroup, card, checkbox, checkboxGroup, chip, circularProgress, cn, code, colorVariants, colors, commonColors, dataFocusVisibleClasses, divider, drip, dropdown, dropdownItem, dropdownMenu, dropdownSection, extendVariants, focusVisibleClasses, forwardRef, getKeyValue, groupDataFocusVisibleClasses, image, input, kbd, link, linkAnchorClasses, listbox, listboxItem, listboxSection, mapPropsVariants, mapPropsVariantsWithCommon, mappedSpacingScaleKeys, menu, menuItem, menuSection, modal, navbar, nextui, pagination, popover, progress, radio, radioGroup, ringClasses, scrollShadow, select, semanticColors, skeleton, snippet, spacer, spacingScaleKeys, spinner, table, tabs, toIterator, toggle, translateCenterClasses, tv, useAccordion, useAccordionItem, useAvatar, useAvatarGroup, useAvatarGroupContext, useBadge, useButton, useButtonGroup, useButtonGroupContext, useCard, useCardContext, useCheckbox, useCheckboxGroup, useCheckboxGroupContext, useChip, useCode, useDisclosure, useDivider, useDropdown, useImage, useInput, useKbd, useLink, useListbox, useMenu, useModal, useModalContext, useNavbar, useNavbarContext, usePagination, usePaginationItem, usePopover, usePopoverContext, useProgress, useRadio, useRadioGroup, useRadioGroupContext, useScrollShadow, useSelect, useSkeleton, useSnippet, useSpacer, useSpinner, useSwitch, useTable, useTabs, useTooltip, useUser, user)

### Screenshots or Videos

export 'default' (imported as 'Text') was not found in '@nextui-org/react' (possible exports: Accordion, AccordionItem, Avatar, AvatarGroup, AvatarGroupProvider, AvatarIcon, Badge, Button, ButtonGroup, ButtonGroupProvider, Card, CardBody, CardFooter, CardHeader, CardProvider, Checkbox, CheckboxGroup, CheckboxGroupProvider, CheckboxIcon, Chip, CircularProgress, Code, Divider, Dropdown, DropdownItem, DropdownMenu, DropdownSection, DropdownTrigger, FreeSoloPopover, Image, Input, Kbd, Link, LinkIcon, Listbox, ListboxItem, ListboxSection, Menu, MenuItem, MenuSection, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader, ModalProvider, Navbar, NavbarBrand, NavbarContent, NavbarItem, NavbarMenu, NavbarMenuItem, NavbarMenuToggle, NavbarProvider, NextUIProvider, Pagination, PaginationCursor, PaginationItem, PaginationItemType, Popover, PopoverContent, PopoverProvider, PopoverTrigger, Progress, Radio, RadioGroup, RadioGroupProvider, ScrollShadow, Select, SelectItem, SelectSection, Skeleton, Snippet, Spacer, Spinner, Switch, Tab, Table, TableBody, TableCell, TableColumn, TableHeader, TableRow, Tabs, Textarea, Tooltip, User, VisuallyHidden, absoluteFullClasses, accordion, accordionItem, avatar, avatarGroup, badge, baseStyles, button, buttonGroup, card, checkbox, checkboxGroup, chip, circularProgress, cn, code, colorVariants, colors, commonColors, dataFocusVisibleClasses, divider, drip, dropdown, dropdownItem, dropdownMenu, dropdownSection, extendVariants, focusVisibleClasses, forwardRef, getKeyValue, groupDataFocusVisibleClasses, image, input, kbd, link, linkAnchorClasses, listbox, listboxItem, listboxSection, mapPropsVariants, mapPropsVariantsWithCommon, mappedSpacingScaleKeys, menu, menuItem, menuSection, modal, navbar, nextui, pagination, popover, progress, radio, radioGroup, ringClasses, scrollShadow, select, semanticColors, skeleton, snippet, spacer, spacingScaleKeys, spinner, table, tabs, toIterator, toggle, translateCenterClasses, tv, useAccordion, useAccordionItem, useAvatar, useAvatarGroup, useAvatarGroupContext, useBadge, useButton, useButtonGroup, useButtonGroupContext, useCard, useCardContext, useCheckbox, useCheckboxGroup, useCheckboxGroupContext, useChip, useCode, useDisclosure, useDivider, useDropdown, useImage, useInput, useKbd, useLink, useListbox, useMenu, useModal, useModalContext, useNavbar, useNavbarContext, usePagination, usePaginationItem, usePopover, usePopoverContext, useProgress, useRadio, useRadioGroup, useRadioGroupContext, useScrollShadow, useSelect, useSkeleton, useSnippet, useSpacer, useSpinner, useSwitch, useTable, useTabs, useTooltip, useUser, user)

### Operating System Version

WINDOWS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Use TailwindCSS text utilities instead, we left this clear in V2 roadmap 


https://github.com/orgs/nextui-org/projects/2/views/1

**Comment by zvictor** [comment]
> we left this clear in V2 roadmap

I thought the purpose of a migration page (https://nextui.org/docs/guide/upgrade-to-v2) was to communicate the steps needed in order to upgrade. Has it changed to a Roadmap now?
