### ISSUE TITLE
New docs UI sidebar glitches (overlays the navbar) when scrolling down

### ISSUE THREAD

**Issue by TDiblik** [nextui-org/nextui#149]
**Describe the bug**
When you're scrolling on the right side of the docs page on Microsoft Edge, you are able to overlay sidebar on top of the navbar.

**Steps to reproduce**
1. Scroll on the right side of the page
2. After you're down on the bottom of the page, keep scrolling
2b. If you're unable to reproduce this bug, sometimes you have to place you're currsor on the left side of the page (as shown in the video)

**Expected behaviour**
Sidebar should not be able to overlay the navbar

**Screenshots**

https://user-images.githubusercontent.com/71404604/150651534-4923a3a7-2ec7-4cc9-b9cc-c12fd8da1405.mp4

**Environment / Context**
Microsoft edge v. 97.0.1072.69

**Comment by jrgarciadev** [comment]
Hey @TDiblik  Thanks for reporting it 👐🏻
