### ISSUE TITLE
[BUG] - NextUIProvider breaks layout

### ISSUE THREAD

**Issue by cleytoncarvalho** [nextui-org/nextui#1494]
### NextUI Version

2.1.5

### Describe the bug

NextUIProvider should not add a new div to the final html or it should have a `display: contents;` so the element don't break the layout when it needs to have full height, like this:

<img width="749" alt="" src="https://github.com/nextui-org/nextui/assets/7952866/6757b6dd-a174-472e-ad8b-0313c8215475">

For now I am using `[&>div]:contents` in the body to solve the problem.

If the div is really necessary maybe the docs could explain that?

### Steps to Reproduce the Bug or Issue

1. Setup NextUIProvider

### Expected behavior

Should not contribute to the layout

### Operating System Version

macOS

### Browser

Safari

**Comment by cleytoncarvalho** [comment]
I just realized that display: contents; in NextUIProvider breaks some components like Popover

**Comment by jrgarciadev** [comment]
Hey @cleytoncarvalho NextUI does not add any default styles to the application, only the needed variables for theme colors/layout etc..

**Comment by cleytoncarvalho** [comment]
@jrgarciadev yeah I see. This is one of the reasons I choose the lib for my new project, really liked it. The problem I mention is related with the div that NextUIProvider creates in the DOM, in my case I need it to have full height but if I do it many components don't work properly like Popover.

**Comment by jrgarciadev** [comment]
Are you sure it comes from NextUIProvider? This is the provider code, only the overlay and i18n providers https://github.com/nextui-org/nextui/blob/main/packages/core/system/src/provider.tsx, we don't add any dom element

**Comment by cleytoncarvalho** [comment]
Thanks! I will investigate.

**Comment by cleytoncarvalho** [comment]
The div is created by the OverlayProvider. I have done some testing and want to ask you if the OverlayProvider is really necessary? Can't find many information about it in the Aria Kit docs, but found this:

"This is used to ensure that the main content of the application is hidden from screen readers if a modal or other overlay is opened." - [https://react-spectrum.adobe.com/react-aria/useDialog.html#example](url)

It adds `aria-hidden="true"` to all elements when something like a popover is open (except the popover), but I removed OverlayProvider and this behavior still continues, so I think OverlayProvider is not necessary.

**Comment by jrgarciadev** [comment]
Oh got it, the thing is that the OverlayProvides is the one that provides the context for Modal stack, so we cannot remove it, it would break the modal context.

Did you try adding `min-h-screen` to the body? We use the same provider in nextui.org and we don't have this issue


![CleanShot 2023-08-26 at 12 08 10@2x](https://github.com/nextui-org/nextui/assets/30373425/56e79f70-4a85-47f5-9e06-19d21b1d18d4)

You can also check the Next.js templates:
https://github.com/nextui-org/next-pages-template
https://github.com/nextui-org/next-app-template

**Comment by cleytoncarvalho** [comment]
Thanks for the explanation! `min-h-screen` will fix my issue.

**Comment by ahuth** [comment]
Using `min-h-screen` alone didn't work for me in the [Remix Blues stack](https://github.com/remix-run/blues-stack).

What did work was adding a css file with

```css
body > [data-overlay-container] {
  height: 100%;
}
```

so the added div is the same height as the body.

Any chance in the future that `NextUIProvider` could take a `className` prop and pass it to the `OverlayProvider` (and presumably on to the wrapping div)?

Then we could do something like:

```jsx
<body className="h-full">
  <NextUIProvider className="h-full">
    <Outlet />
```

**Comment by tianenpang** [comment]
Hey @ahuth thank you for your feedback and we have now added support for setting `className` for the `NextUIProvider`. try on the latest version 🙌🏻

**Comment by ahuth** [comment]
Thanks!

**Comment by jackwong721** [comment]
To solve this problem is just easy. My solution is just adding the `style={{ height: "100%" }}` to the` <NextUIProvider>`.

So the final will be look like:

`<NextUIProvider style={{ height: "100%" }}>
    <div className='app'>
    </div>
</NextUIProvider>`
