### ISSUE TITLE
[BUG] - Impossible to navigate the contents of the side bar in the NextUI documentation

### ISSUE THREAD

**Issue by nibble0101** [nextui-org/nextui#1497]
### NextUI Version

N/A

### Describe the bug

Currently when you navigate to https://nextui.org/docs/components/, there is a sidebar for navigating to the sections describing the components available in NextUI. However, depending on the screen height, some of  the items under the last collapsible are hidden from view. When you click the last visible item("Customize theme" in the screenshot below), you cannot scroll up or down using the arrow keys and there is no scrollbar. 

Unfortunately, clicking below doesn't expand the hidden items either. The only way I can navigate the side bar again is by reloading the page.  
![image](https://github.com/nextui-org/nextui/assets/52580190/64005048-1ef8-41f4-96a6-8fbaab29414c)

### Steps to Reproduce the Bug or Issue

1. Navigate to https://nextui.org/docs/components/
2. Click one of the items under the `Components` collapsible item on the left
3. When using a large screen, adjust the browser so  that some items under the collapsible are hidden from view
4. Try navigating up and down using the arrow keys or clicking to expand the hidden items

### Expected behavior

I expect the hidden items to be scrolled into view when the last visible item is clicked or a scrollbar be displayed to scroll to the items below.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/52580190/d9138b5a-1553-4692-9e92-99cc05abe799)

### Operating System Version

Pop_os

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @nibble0101 even though the scroll is not displayed because we hide it to a have a cleaner design, you can scroll the content:


https://github.com/nextui-org/nextui/assets/30373425/4df13467-ecae-4a44-b39a-b2b20dc42d98

**Comment by nibble0101** [comment]
> Hey @nibble0101 even though the scroll is not displayed because we hide it to a have a cleaner design, you can scroll the content:
> 
>  CleanShot.2023-08-26.at.10.33.39.mp4

I'm surprised you've chosen to sacrifice usability for 'clean design'. Did you try scrolling without using a mouse?
