### ISSUE TITLE
[BUG] - Table

### ISSUE THREAD

**Issue by arvind8652** [nextui-org/nextui#1498]
### NextUI Version

2.1.5

### Describe the bug

while clicking on ts or js tab, file extension is not changing it not changing from js to ts, only the first file extension is changing

### Steps to Reproduce the Bug or Issue

1. go on table components tab
2. click on custom cells table
3. click on code tab 
4. click on ts tab

### Expected behavior

file extension should change when we change the ts or js tab

### Screenshots or Videos

<img width="515" alt="image" src="https://github.com/nextui-org/nextui/assets/54900001/f8b546e6-f69f-416c-81d5-1e387d3b4979">

### Operating System Version

window

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @arvind8652 this is intended since we don't rewrite simple components as icons in typescript, they are shared between .js and .ts files
