### ISSUE TITLE
[BUG] - The default `transition` of tailwindcss is overridden by the `nextui` plugin and has a higher priority.

### ISSUE THREAD

**Issue by u3u** [nextui-org/nextui#1502]
### NextUI Version

2.1.5

### Describe the bug

This will prevent me from directly setting my own `transition` effect.

<img width="484" alt="image" src="https://github.com/nextui-org/nextui/assets/20062482/e9c4fdbb-b172-4c8a-887a-0d2738c56543">

<img width="337" alt="image" src="https://github.com/nextui-org/nextui/assets/20062482/d229e1ed-5ad5-442d-a468-9d7771efc684">

### Steps to Reproduce the Bug or Issue

Add the `nextui()` plugin to `tailwind.config.js`.

### Expected behavior

There should not be duplicate `transition`.

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
@u3u could you explain better, what is the issue here?, Are you trying to add a custom transition to the tailwind config and the NextUI ones override it?

**Comment by u3u** [comment]
```js
transitionDuration: {
  DEFAULT: '300ms',
}
```

Yes, it will override the default `transitionDuration` that I have set and result in the generation of additional duplicate `.transition` classes.

<img width="454" alt="image" src="https://github.com/nextui-org/nextui/assets/20062482/e5eb110b-26c1-4ee2-b9e4-199e0b14d582">
<img width="448" alt="image" src="https://github.com/nextui-org/nextui/assets/20062482/d109fd7f-8ad2-4d09-ab48-2ab91770fab3">

**Comment by jrgarciadev** [comment]
I agree, I'll redefine the transitions names to avoid the conflicts

**Comment by u3u** [comment]
```diff
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      transitionDuration: {
+        DEFAULT: '250ms',
      },
    }
  }
}
```

Thank you! However, I believe that the standard transition effects `transition-(all|colors|opacity|shadow|transform)` do not need to be renamed and redefined because it seems that only the default `duration` has been modified. It can be directly overridden in `tailwind.config.js`.

**Comment by luisanton-io** [comment]
Facing the same issue. Importing NextUI overrides transition durations set via tailwing arbitrary values like `duration-[3s]`.
Just checking if is there a fix in the works...?

**Comment by njarraud** [comment]
It seems that it is still an issue. I cannot define custom transition durations via tailwind as mentioned by [luisanton-io](https://github.com/luisanton-io). nextui always overwrites them? It makes it hard to mix with other custom components.

Any plans for a fix or a solution?

**Comment by Moriarty47** [comment]
Yes, the nextui transition effects take a higher priority.

![image](https://github.com/nextui-org/nextui/assets/21117495/db38e8d7-9f03-4fa3-8eee-173724668ad8)

And now I have to use them like this `!duration-300 transition-opacity !ease-in-out` to make it work.

![image](https://github.com/nextui-org/nextui/assets/21117495/22c2240d-1256-44e3-aa5c-e5f2b3e03450)

**Comment by u3u** [comment]
I have submitted a PR (#2677), the next version will address this issue.
