### ISSUE TITLE
[BUG] - 'use client' directive missing in components

### ISSUE THREAD

**Issue by RS1-Project** [nextui-org/nextui#1504]
### NextUI Version

2.1.2

### Describe the bug

The blog post announcing v2.0 states:
> NextUI components already include the `use client` directive so you can import them directly in your React Server Components (RSC).

But I'm afraid this seems to be wrong. If I import a component from `nextui-org/react` I receive an error stating that a component is trying to use `useEffect` or `useState` without declaring first `use client`.
Am I missing something? Should I enable RSC support somewhere?
Thanks!

### Steps to Reproduce the Bug or Issue

1. Import a component directly in a Server Component
2. Run the app an you can see the error

### Expected behavior

I would expect all the components to work automatically in Server Components.

### Operating System Version

macOS

### Browser

Safari

**Comment by tianenpang** [comment]
Hey @RS1-Project, you'll need to install the ***individual*** package and import components from there. you can find the package names in the docs for each component.

For more details, please refer to: https://nextui.org/docs/frameworks/nextjs#use-nextui-components.

![nextui org_docs_frameworks_nextjs](https://github.com/nextui-org/nextui/assets/32772271/bca8fa2e-95f7-4ba2-81e6-995ff8c495c0)

Additionally, components with the `Server component` badge are fully React Server Components.

![Screenshot 2023-08-27 060052](https://github.com/nextui-org/nextui/assets/32772271/9c18c2de-d739-4f79-9863-048441f0a2df)
