### ISSUE TITLE
[BUG] - Navbar Menu - Scroll locked when the animation is disabled

### ISSUE THREAD

**Issue by indrow** [nextui-org/nextui#1506]
### NextUI Version

2.1.7

### Describe the bug

When the navbar menu animation is disabled, we can't scroll the whole pages.

### Steps to Reproduce the Bug or Issue

1. Install NextJS v13.4.19 with app directory, typescript and tailwindcss.
2. Install NextUI and framer-motion
3. Create a navbar component, copy from components/navbar > With Menu.
4. Add `disableAnimation` to Navbar props.
5. Add some text or other elements so we can scroll.
6. Run development server.
7. Wait page to load.
8. After `NavbarMenu` component loaded, it will freeze the page scroll.

### Expected behavior

Able to scroll page.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @indrow could you send a video or reproduction? 

This does not happen to me:

https://github.com/nextui-org/nextui/assets/30373425/5e543439-355a-4aa7-b1d6-ea7cc6cf12de
