### ISSUE TITLE
[Feature Request] Tooltip activation failover on touch/mobile devices

### ISSUE THREAD

**Issue by CaseyBlackburn** [nextui-org/nextui#1510]
### Is your feature request related to a problem? Please describe.

(I've been working on moving to using NextUI coming from a background with previously using React-Bootstrap. Been loving everything so far, but I've noticed that Tooltip component seems to be missing functionality that I appreciated in React-Bootstrap.)

When using Tooltip component currently a mobile device/touch screen device is unable to activate a tooltip.

### Describe the solution you'd like

I would like to see similar functionality of how React-Bootstrap handles tooltips. On a device with a pointer, the hovering of the pointer on the activating element should activate the tooltip. (Current behavior) But have the fallback activation of touching the activating element on a touch screen will also launch the tooltip and touching outside of the tooltip will close the tooltip.

### Describe alternatives you've considered

I've considered adding hover detection for a Popover component but that feels hacky at best.

**Comment by jrgarciadev** [comment]
Hey @CaseyBlackburn this functionality is not supported by `react-aria` the library we use to provide the accessibility and behavior to components https://react-spectrum.adobe.com/react-aria/useTooltipTrigger.html.

You could use the controlled example to open/close the tooltip with you own conditions
https://nextui.org/docs/components/tooltip#controlled
