### ISSUE TITLE
[BUG] - DropdownTrigger doesn't work with custom components

### ISSUE THREAD

**Issue by elnexreal** [nextui-org/nextui#1516]
### NextUI Version

2.1.7

### Describe the bug

If you try to use a custom component in `DropdownTrigger` that returns a button it doesn't work

### Steps to Reproduce the Bug or Issue

1. Create a component that returns a button
2. Add that component to `DropdownTrigger`
3. It doesn't open

### Expected behavior

I expected the panel opening but it doesn't do anything

### Screenshots or Videos

![firefox_JNs26TVpOl](https://github.com/nextui-org/nextui/assets/40328573/2ff64561-b3c8-4159-ba86-5ddddf4fdcf2)

### Operating System Version

Windows

### Browser

Firefox

**Comment by elnexreal** [comment]
The code for the button is
```jsx
export default function CustomBtn(props: btn) {
	return (
		<button className="text-center px-4 py-2 btn-line bg-black/50 rounded-lg overflow-hidden text-2xl" onClick={props.func}>
			{props.text}
		</button>
	)
}```

The code for the dropdown is
```jsx
<Dropdown>
	<DropdownTrigger>
		<CustomBtn text="Account" />
	</DropdownTrigger>
	<DropdownMenu aria-label="Account">
		<DropdownItem>Test</DropdownItem>
		<DropdownItem>Test</DropdownItem>
		<DropdownItem>Test</DropdownItem>
		<DropdownItem>Test</DropdownItem>
	</DropdownMenu>
</Dropdown>
```

**Comment by landiehan** [comment]
@elnexreal You need to forward ref to your custom button component, and pass props from `DropdownTrigger` to your button.
See [this codebox](https://codesandbox.io/p/sandbox/youthful-brook-mdk9vm?file=%2FApp.jsx%3A4%2C19&utm_medium=sandpack) and checkout console to see props passed down.

**Comment by elnexreal** [comment]
Thx
