### ISSUE TITLE
SELECT - DEFAULT VALUE NOT WORKING

### ISSUE THREAD

**Issue by Mateusvaz89** [nextui-org/nextui#1522]
### NextUI Version

2.1.0

### Describe the bug

When the component is rendered, the default value is not displayed, only the placeholder.

import { useContext, useEffect } from 'react'
import { ServiceContext } from '../service/context'
import { PaymentContext } from '../payment/context'
import { Select, SelectItem } from '@nextui-org/react'

export function Installments() {
    const { pack } = useContext(ServiceContext)
    const { paymentMethod, installments, setInstallments } =
        useContext(PaymentContext)
    useEffect(() => {}, [paymentMethod])

    if (pack && paymentMethod == 'CREDIT_CARD')
        return (
            <Select
                defaultValue={1}
                value={installments}
                onChange={(e) => {
                    setInstallments(parseInt(e.target.value))
                }}
                label="Parcelamento"
                size="sm"
            >
                {Array.from([1, 2, 3]).map((e) => (
                    <SelectItem
                        key={e}
                        value={e}
                        textValue={`${e}x de ${(pack!.price / e).toLocaleString(
                            'pt-BR',
                            {
                                style: 'currency',
                                currency: 'BRL',
                            }
                        )}`}
                    >
                        {e}x de
                        {(pack!.price / e).toLocaleString('pt-BR', {
                            style: 'currency',
                            currency: 'BRL',
                        })}
                    </SelectItem>
                ))}
            </Select>
        )
}

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

The expected default value in rendering is 1

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Mateusvaz89 is the `installments` value dynamic? does it come from an API?, in addition, why are you passing it to the value of the Select? `value={installments}`

Please make sure to use the correct dynamic way:
https://nextui.org/docs/components/select#dynamic-items

Do not use a `map` function to dynamically render the items

**Comment by Mateusvaz89** [comment]
not in the api, and a value between 1 and 3 fixed

**Comment by jrgarciadev** [comment]
It works fine to me 
https://codesandbox.io/p/sandbox/keen-sanderson-6hzm6f?file=/App.jsx:16,43&utm_medium=sandpack

**Comment by Mateusvaz89** [comment]
defaultSelectedKeys={[`${installments}`]} 
worked thanks!!!!

**Comment by StephenB-24** [comment]
> defaultSelectedKeys={[`${installments}`]} worked thanks!!!!

THANK YOU SO MUCH. This helps me tremendously
