### ISSUE TITLE
[BUG] - Select component requires too many properties.

### ISSUE THREAD

**Issue by andres3dc** [nextui-org/nextui#1523]
### NextUI Version

2.1.7

### Describe the bug

Hello everyone, I'm using the select component with TypeScript, and when defining it, it asks for many properties that are not important in the end. I've attached an image for reference.

### Steps to Reproduce the Bug or Issue

`import {Select, SelectProps} from "@nextui-org/react";`

`<Select></Select>`

### Expected behavior

I expected the Select component to require fewer properties during its definition, as some of the requested properties appear to be unnecessary for its functionality.

### Screenshots or Videos

<img width="877" alt="image" src="https://github.com/nextui-org/nextui/assets/3432275/2fb68083-7ee9-41d3-8b6b-5a75f18d558e">

### Operating System Version

macOs 

### Browser

Chrome

**Comment by akshayantony55** [comment]
@andres3dc I see all those are optional fields. Can you double check?

**Comment by jrgarciadev** [comment]
Hey @andres3dc try restarting your Typescript server, those properties are not required, all of them are optional (except the `children`)

check this to restart your TS server: https://tinytip.co/tips/vscode-restart-ts/

**Comment by ahmedali5530** [comment]
@jrgarciadev still facing the issue in `"@nextui-org/react": "^2.1.8",`. I am using Phpstorm version 2023.2.1 and tried restarting ts service so many times.
