### ISSUE TITLE
[BUG] - Listbox

### ISSUE THREAD

**Issue by panthchristian** [nextui-org/nextui#1529]
### NextUI Version

2.1.7

### Describe the bug

The ListboxWrapper.jsx is not being identified and loaded and shows
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### Your Example Website or App

https://stackblitz.com/edit/nextui-listbox?file=src%2FApp.jsx

### Steps to Reproduce the Bug or Issue

Simply copy and paste the code in the file as named in the documentation

### Expected behavior

According to documentation the page should render the list but it is showing blank page

### Screenshots or Videos

<img width="1249" alt="image" src="https://github.com/nextui-org/nextui/assets/65898155/d94fcbd2-f4e0-4c4d-a1a5-ee3b4c5103a3">

### Operating System Version

Windows

### Browser

Edge

**Comment by tianenpang** [comment]
Hi @panthchristian you need to export the `ListboxWrapper` from `ListboxWrapper.jsx` and follow the [installation guide](https://nextui.org/docs/guide/installation) to setup the tailwindcss and the provider to get the styles right.
