### ISSUE TITLE
[BUG] - When the `title` prop of Tab is not a string, it should not be passed to HTML elements.

### ISSUE THREAD

**Issue by u3u** [nextui-org/nextui#1531]
### NextUI Version

2.1.7

### Describe the bug

It will cause the incorrect title `[object Object]` to be displayed when hovering over it.

<img width="351" alt="image" src="https://github.com/nextui-org/nextui/assets/20062482/b1cc8aca-04e9-4809-801f-335851146fd6">

### Steps to Reproduce the Bug or Issue

https://nextui.org/docs/components/tabs#with-icons

### Expected behavior

Only when `title` is a string can it be passed to HTML elements.

### Operating System Version

macOS

### Browser

Chrome

**Comment by akshayaqburst** [comment]
I will work on this
