### ISSUE TITLE
Issues using create-react-app [react-scripts v5]

### ISSUE THREAD

**Issue by TheAlphaReturns** [nextui-org/nextui#154]
**Describe the bug**
Blank page when creating a hello world

**Steps to reproduce**
1. Make a new create react app and instantly eject it
2. Install nextui
3. make a hello world
4. its a blank screen

**Expected behaviour**
a hello world

**Screenshots**
my pleasure

![nextui1](https://user-images.githubusercontent.com/61358474/150668828-52ee03da-f0e7-4438-8276-a15a3945a3f5.png)
![nextui2](https://user-images.githubusercontent.com/61358474/150668830-924a6294-df86-45b4-8890-c1d7dacc5212.png)
![nextui3](https://user-images.githubusercontent.com/61358474/150668837-509bc1ac-dccc-4a29-8759-946b5881c5d7.png)
![nextui4](https://user-images.githubusercontent.com/61358474/150668839-8c818688-47bb-4b7d-8126-8ffd3fcf9abb.png)

- Desktop or Mobile? Desktop
- Operating System: [e.g. iOS] Windows
- Browser and version [e.g. chrome 22] Firefox 96
- Device: [e.g. iPhone6] hp pavillion 15"

**Additional info**
please don't instantly close this issue. tell me how I can fix this. This is my first time using react. I literally spent a week learning that I had to eject my create-react-app to make eslint customizations without it failing to build

**Comment by anridev24** [comment]
If you check console, there are lots of error. It's not working

**Comment by mariusflorescu** [comment]
Hi @TheAlphaReturns, apparently this has nothing to do with the `eject` script.

**Comment by TheAlphaReturns** [comment]
Something about no create stitches function yes

**Comment by mariusflorescu** [comment]
@TheAlphaReturns no, there is nothing that you are doing wrong.

Until it gets fixed, I think I found a workaround.

In your `package.json`, decrease the version of `react-scripts` to version 4.

example:
```
"dependencies": {
    "@nextui-org/react": "^1.0.2-beta.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.0", <--- THIS LINE
    "web-vitals": "^2.1.0"
  },
```

**Comment by TheAlphaReturns** [comment]
Is react scripts included in ejected create-react-app?

**Comment by mariusflorescu** [comment]
Sorry, my bad, it won't work since you are trying to eject (forgot the key point of your issue).
There is an issue that needs some investigation.

**Comment by jrgarciadev** [comment]
Hey @TheAlphaReturns right @mariusflorescu commented before you can solve this decreasing the `react-scripts` to the `v4`, I will look into what changed in react-scripts `v5` and try to figure that out with the `Stitches` team

**Comment by anridev24** [comment]
@TheAlphaReturns if you are using Typescript downgrade `react-scripts` to `v4` also `typescript` to` 4.1.0` delete `tsconfig.json` then delete `yarn.lock`  or `package-lock.json` also remove `node_modules` and finally  run `yarn` or `npm install`, and it should work

**Comment by TheAlphaReturns** [comment]
For now I'll use unejected JavaScript create-react-app

**Comment by TheAlphaReturns** [comment]
ok so just tested. ejected create-react-app, using react-scripts v4 works

**Comment by AdamSlack** [comment]
I found that the suggested workaround brought some additional issues. Specifically with the hot-loading that is bundled in with react/create-react-app. A `process is not defined` error occured each time the app reloaded.

Adding `react-error-overlay` as a devDependency and specifying it as a resolution in the project's package.json helped mitigate it for me (https://stackoverflow.com/questions/70357360/process-is-not-defined-on-hot-reload/70374227)

```json
  "devDependencies": {
    "react-error-overlay": "6.0.9"
  },
  "resolutions": {
    "react-error-overlay": "6.0.9"
  },
```

**Comment by Dhananjay-JSR** [comment]
I think until a permanent solution is found there should be a mention somewhere in Readme or in Documentation that developer who wish to work with NextUI on a brand new React Project needs to downgrade react-scripts to 4.0.0 from package json file to avoid any issue

**Comment by Dhananjay-JSR** [comment]
if you got no issue @jrgarciadev  with this can I make PR about changes in docs 😄

**Comment by jrgarciadev** [comment]
Hey @Dhananjay-JSR that sounds good, could you please create an `issue` to assign it to you?

Thanks 🙌🏻

**Comment by Dhananjay-JSR** [comment]
#189 there you go @jrgarciadev 😄

**Comment by jrgarciadev** [comment]
Hey guys we have tried this again using the `"@nextui-org/react": "1.0.2-beta.4",` of `NextUI` and is no longer happening to me, could you please try using the same version?
