### ISSUE TITLE
[BUG] - Table

### ISSUE THREAD

**Issue by xicarox** [nextui-org/nextui#1566]
### NextUI Version

V2.1.0

### Describe the bug

error ./app/Agendamiento/content/table/App.jsx:20:0
Module not found: Can't resolve './VerticalDotsIcon'
  18 | } from "@nextui-org/react";
  19 | import {PlusIcon} from "./PlusIcon";
> 20 | import {VerticalDotsIcon} from "./VerticalDotsIcon";
  21 | import {SearchIcon} from "./SearchIcon";
  22 | import {ChevronDownIcon} from "./ChevronDownIcon";
  23 | import {columns, users, statusOptions} from "./data";

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./app/Agendamiento/page.tsx

### Steps to Reproduce the Bug or Issue

./VerticalDotsIcon

### Expected behavior

./VerticalDotsIcon

### Screenshots or Videos

./VerticalDotsIcon

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Fixed here: https://github.com/nextui-org/nextui/issues/1603
