### ISSUE TITLE
[BUG] - The floating labels wont change position on chrome autofill

### ISSUE THREAD

**Issue by maddevfaizal** [nextui-org/nextui#1571]
### NextUI Version

2.1.10

### Describe the bug

The floating label works if we manually type on iot , but it wont work if chrome autofills it

### Steps to Reproduce the Bug or Issue

refer the screenshot
![Screenshot from 2023-09-05 15-31-54](https://github.com/nextui-org/nextui/assets/110644871/01ce2ca8-636b-4b9c-bb44-416dca2df414)

### Expected behavior

the label should change position on auto fill

### Operating System Version

Linux

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Update to the latest version

**Comment by maddevfaizal** [comment]
@jrgarciadev  have tried v2.1.10 , same issue

**Comment by Yiniau** [comment]
same question

**Comment by ttiras** [comment]
same here on v2.1.13

**Comment by wingkwong** [comment]
Closing - no longer reproducible

**Comment by codenomnom** [comment]
Not sure if this has to be reopened, but I'm on `2.6.10` and I see this:

![image](https://github.com/user-attachments/assets/08881f79-8ede-4f75-9a06-d5b8eb927547)

Looks good if I click anywhere on the screen:

![image](https://github.com/user-attachments/assets/5ba87b8b-6f8f-4d34-81e5-ecbf848ea4d3)

It's not related to password input in any way - I observe the same issue with a regular input field (username).

@wingkwong @jrgarciadev tagging you so someone can follow up, thank you! 🙂

**Comment by wingkwong** [comment]
@codenomnom can you share the code as well as `package.json`? A minimal reproducible sandbox will be much better.

**Comment by pppdns** [comment]
This still happens with the latest version:
<img width="318" alt="Screenshot 2025-01-15 at 15 53 47" src="https://github.com/user-attachments/assets/d38b8ee4-fb9f-4f79-8351-9a36a33f702f" />


```
"@nextui-org/input": "^2.4.6"
```

**Comment by wingkwong** [comment]
@pppdns please share a reproducible environment

**Comment by radu-torro** [comment]
anyone found a fix? i still have this issue present 2.7.6

![Image](https://github.com/user-attachments/assets/1aae88bf-3119-48e3-9098-8f2b6a159c26)

**Comment by codenomnom** [comment]
I still experience this issue. @wingkwong sorry for not posting a reproduction repo, will do next week. If that has any connection - I'm currently using Chrome on Windows. Everything else seems pretty regular setup.
