### ISSUE TITLE
[BUG] - Button is exported in lower case 'button'

### ISSUE THREAD

**Issue by AbrahamDN** [nextui-org/nextui#1573]
### NextUI Version

2.1.10

### Describe the bug

The Button component is exported in lowercase on `@nextui-org/react`, can't directly use it as a component this way.

### Steps to Reproduce the Bug or Issue

Just try to import Button on your NextJS app (13.4.19)

### Expected behavior

I expected `import { Button }` but instead I get  `import { button }"`
^ Similar with ButtonGroup too.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/40493309/35ab873a-d53d-49de-a982-4b4720792fa5)
![image](https://github.com/nextui-org/nextui/assets/40493309/1f2ef934-ce91-4d34-803e-996aa48241e7)

### Operating System Version

Windows 11 Home

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @AbrahamDN the lowercase button is the styles function which you can use it in any framework, it is the [tailwind-variants](https://tailwind-variants.org) function https://github.com/nextui-org/nextui/blob/main/packages/core/theme/src/components/button.ts

You can find those declarations in the repository by clicking here:

![CleanShot 2023-09-05 at 14 09 15@2x](https://github.com/nextui-org/nextui/assets/30373425/45d7d01a-7a69-4c30-ab49-be1020c6815b)
