### ISSUE TITLE
[Feature Request] Add `allowClear` prop for Select component

### ISSUE THREAD

**Issue by caohonghai** [nextui-org/nextui#1579]
### Is your feature request related to a problem? Please describe.

In certain scenarios, the select component in a form is not required to be selected. When I select a value, I might want to delete it.

### Describe the solution you'd like

Now, I would like to add an additional property called `allowClear` to the select props, which will allow me to clear the selected data when hovering over it.

### Describe alternatives you've considered

Currently, I can only do so by triggering an event with a button. 

### Screenshots or Videos

just like [this](https://ant.design/components/select):

**default**
![image](https://github.com/nextui-org/nextui/assets/43627226/f1f2ea45-5de6-4ed8-90b5-eaef5c86b2f6)

**hover**
![image](https://github.com/nextui-org/nextui/assets/43627226/05f9f0de-f877-4a40-9b5c-4c860e2b329d)

**Comment by wingkwong** [comment]
Closing - tracked in https://github.com/nextui-org/nextui/issues/2239
