### ISSUE TITLE
camera and dark mode button

### ISSUE THREAD

**Issue by jaseem1999** [nextui-org/nextui#158]
**camara and dark mode button**

![pro](https://user-images.githubusercontent.com/65609243/151165407-c4c3c7be-2588-480d-a811-9475dbcbdaf2.png)

**Comment by Dhananjay-JSR** [comment]
Can someone explain the issue to me ??

**Comment by gr8pathik** [comment]
I think the search box is overlapping the camera and the dark mode button is the issue

**Comment by jaseem1999** [comment]
> I think the search box is overlapping the camera and the dark mode button is the issue

Yes
