### ISSUE TITLE
[Feature Request] ability  to make a  completly costum  component with variant support same as chakra ui

### ISSUE THREAD

**Issue by zakidze** [nextui-org/nextui#1580]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

check this out i want exact this functionality

https://chakra-ui.com/docs/styled-system/component-style

### Describe alternatives you've considered

-

**Comment by jrgarciadev** [comment]
https://nextui.org/docs/customization/custom-variants
