### ISSUE TITLE
[BUG] - Table

### ISSUE THREAD

**Issue by Shubhankar-1** [nextui-org/nextui#1581]
### NextUI Version

2.1.10

### Describe the bug

I Pasted code from next ui  table example and got this error .

![image](https://github.com/nextui-org/nextui/assets/66659343/45451056-293e-41bb-aaa6-d77dfaf04aec)

### Steps to Reproduce the Bug or Issue

1. Go to: https://nextui.org/docs/components/table#use-case-example
2. Try to run in your Next js project

### Expected behavior

It expected to run but It hang website and show error "Maximum call stack size exceeded"

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/66659343/a6bee71d-56de-4731-8c85-d5333373ae77)

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Shubhankar-1 fixed here:https://github.com/nextui-org/nextui/issues/1603

e.g.: https://codesandbox.io/p/sandbox/dz93xg?file=/App.tsx:1,1&utm_medium=sandpack

**Comment by Shubhankar-1** [comment]
Ohh Thanks @jrgarciadev,
However, I experimented with react-icons instead of VerticalDotsIcon at that time. Is VerticalDotsIcon have been the cause of the error?
