### ISSUE TITLE
[BUG] - Input label is covering the input value

### ISSUE THREAD

**Issue by infomiho** [nextui-org/nextui#1582]
### NextUI Version

2.1.10

### Describe the bug

Using an input like this:
```ts
<Input
  {...addForm.register("url", {
    required: "Website URL is required",
    validate: (value) => {
      try {
        new URL(value);
        return true;
      } catch (e) {
        return "Website URL is invalid";
      }
    },
  })}
  label="Website URL"
  variant="bordered"
  errorMessage={addForm.formState.errors.url?.message}
/>
```
inside of the `<Tabs />` component.

After switching between tabs, the label goes down and covers the input value (see the video below).

### Your Example Website or App

https://github.com/wasp-lang/wasp/blob/miho-postgresql-ext/waspc/examples/pg-vector-example/src/client/pages/MainPage.tsx

### Steps to Reproduce the Bug or Issue

1. Open the app
2. Write something in the input
3. Switch the tab
4. Return to initial tab

### Expected behavior

As a user I expect the label not to cover the input value

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/2223680/e0e99a26-c955-4ee1-9b38-9a2031863f7c

### Operating System Version

MacOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Please check this: https://github.com/nextui-org/nextui/issues/1416
