### ISSUE TITLE
[BUG] - Dropdown scroll

### ISSUE THREAD

**Issue by franco4457** [nextui-org/nextui#1587]
### NextUI Version

2.1

### Describe the bug

The page scroll is disabled when the dropdown is open.

> PS: maybe it's intentional

### Your Example Website or App

https://nextui.org/docs/components/dropdown

### Steps to Reproduce the Bug or Issue

1. Go to https://nextui.org/docs/components/dropdown
2. Click any button demo
3. Scroll page don't work 😞 

### Expected behavior

The dropdown scroll is overwriting the native scroll of the page

### Operating System Version

Ubuntu

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @franco4457 you can pass `shouldBlockScroll={false}`  to Dropdown to disable the scroll block

![CleanShot 2023-09-15 at 11 10 31@2x](https://github.com/nextui-org/nextui/assets/30373425/9c29708d-9e11-4a0e-9dcc-0a88e21e989e)

**Comment by franco4457** [comment]
Damn, I'm so sorry bro. When reading the doc, I just ignored that prop 😅

**Comment by R4tch3t** [comment]
how maxWidth for overflow in dropdown??
