### ISSUE TITLE
[BUG] -NextUI Table - type.getCollectionNode is not a function

### ISSUE THREAD

**Issue by TylerNRobertson** [nextui-org/nextui#1593]
### NextUI Version

2.1.10

### Describe the bug

Whenever you wrap a table element with another container, even if it's a supported HTML table element, this error is thrown. For some reason the table enforces the children to be only components it expects, wondering if its possible to switch to an element selector approach vs expecting the direct children

### Steps to Reproduce the Bug or Issue

1. Install NextUI
2. Build a table
3. Wrap your NextUI `TableRow` or the cells within a row, with a div or table HTML element and this error ill throw

### Expected behavior

Be able to wrap with any component you'd like to extend the tables functionality

### Operating System Version

Any

### Browser

Firefox

**Comment by jrgarciadev** [comment]
Hey NextUI relies on `react-aria` colections https://react-spectrum.adobe.com/react-stately/collections.html, the collections API uses specific components to manage items, sections, etc... You can use any content inside of those items tho
