### ISSUE TITLE
[Feature Request] Open dropdown on hover 

### ISSUE THREAD

**Issue by TheGhost55** [nextui-org/nextui#1598]
### Is your feature request related to a problem? Please describe.

The feature request is related to a ux problem. 

### Describe the solution you'd like

As a user, when I see a dropdown menu in the nav bar i'd expect it to open on hovering over it. 

Ideal would be: 

1. Hover over dropdown trigger 
2. Dropdown opens
3. Mouse leaves the dropdown trigger and items
4. Dropdown closes

This feature could be implemented as a new component. <HoverDropdown>

### Describe alternatives you've considered

There isn't a real alternaive.

**Comment by jrgarciadev** [comment]
https://codesandbox.io/p/sandbox/sffwws?file=%2FApp.jsx%3A1%2C1&utm_medium=sandpack

**Comment by TheGhost55** [comment]
> https://codesandbox.io/p/sandbox/sffwws?file=%2FApp.jsx%3A1%2C1&utm_medium=sandpack

In the example, it is only possible to open the dropdown with an onClick event instead of an onHover event.

**Comment by jrgarciadev** [comment]
It seems Codesanbox is not working properly, here's the code

```tsx
import React from "react";
import {Dropdown, DropdownTrigger, DropdownMenu, DropdownItem, Button} from "@nextui-org/react";

export default function App() {
 const [isOpen, setOpen] = React.useState(false)

  return (
    <Dropdown isOpen={isOpen}>
      <DropdownTrigger
        onPointerEnter={() => setIsOpen(true)}
        onPointerLeave={() => setIsOpen(false)}
      >
        <Button 
          variant="bordered" 
        >
          Open Menu
        </Button>
      </DropdownTrigger>
      <DropdownMenu aria-label="Static Actions">
        <DropdownItem key="new">New file</DropdownItem>
        <DropdownItem key="copy">Copy link</DropdownItem>
        <DropdownItem key="edit">Edit file</DropdownItem>
        <DropdownItem key="delete" className="text-danger" color="danger">
          Delete file
        </DropdownItem>
      </DropdownMenu>
    </Dropdown>
  );
}

```
