### ISSUE TITLE
[BUG] - Navbar with Dropdown

### ISSUE THREAD

**Issue by devjamescockfield** [nextui-org/nextui#1607]
### NextUI Version

2.1.10

### Describe the bug

I have copied and pasted the code for this navbar [Navbar with Dropdown](https://nextui.org/docs/components/navbar#with-dropdown-menu) and when I open the dropdown it will not close if you click away from the dropdown.

and here is my code:
```
import {
    Button,
    Dropdown,
    DropdownItem,
    DropdownMenu,
    DropdownTrigger,
    Navbar,
    NavbarBrand,
    NavbarContent,
    NavbarItem
} from "@nextui-org/react";
export default function NavbarWidget() {

return (
        <Navbar>
            <NavbarBrand>
                <p className="font-bold text-inherit">ACME</p>
            </NavbarBrand>
            <NavbarContent className="hidden sm:flex gap-4" justify="center">
                <Dropdown>
                    <NavbarItem>
                        <DropdownTrigger>
                            <Button
                                disableRipple
                                className="p-0 bg-transparent data-[hover=true]:bg-transparent"
                                endContent={icons.chevron}
                                radius="sm"
                                variant="light"
                            >
                                Features
                            </Button>
                        </DropdownTrigger>
                    </NavbarItem>
                    <DropdownMenu
                        aria-label="ACME features"
                        className="w-[340px]"
                        itemClasses={{
                            base: "gap-4",
                        }}
                    >
                        <DropdownItem
                            key="autoscaling"
                            description="ACME scales apps to meet user demand, automagically, based on load."
                        >
                            Autoscaling
                        </DropdownItem>
                        <DropdownItem
                            key="usage_metrics"
                            description="Real-time metrics to debug issues. Slow query added? We’ll show you exactly where."
                        >
                            Usage Metrics
                        </DropdownItem>
                        <DropdownItem
                            key="production_ready"
                            description="ACME runs on ACME, join us and others serving requests at web scale."
                        >
                            Production Ready
                        </DropdownItem>
                        <DropdownItem
                            key="99_uptime"
                            description="Applications stay on the grid with high availability and high uptime guarantees."
                        >
                            +99% Uptime
                        </DropdownItem>
                        <DropdownItem
                            key="supreme_support"
                            description="Overcome any challenge with a supporting team ready to respond."
                        >
                            +Supreme Support
                        </DropdownItem>
                    </DropdownMenu>
                </Dropdown>
                <NavbarItem isActive>
                    <Link href="#" aria-current="page">
                        Customers
                    </Link>
                </NavbarItem>
                <NavbarItem>
                    <Link color="foreground" href="#">
                        Integrations
                    </Link>
                </NavbarItem>
            </NavbarContent>
            <NavbarContent justify="end">
                <NavbarItem className="hidden lg:flex">
                    <Link href="#">Login</Link>
                </NavbarItem>
                <NavbarItem>
                    <Button as={Link} color="primary" href="#" variant="flat">
                        Sign Up
                    </Button>
                </NavbarItem>
            </NavbarContent>
        </Navbar>
    )
}
```

### Steps to Reproduce the Bug or Issue

1. Go to https://nextui.org/docs/components/navbar#with-dropdown-menu
2. Copy and paste the code into a file
3. Run code
4. Open dropdown
5. Click off the dropdown

### Expected behavior

When you click away from the dropdown it will close automatically.

### Screenshots or Videos

[Video](https://i.gyazo.com/4be2a9f24294d07e4c55165901e61d9d.gif)

### Operating System Version

Windows 11 

### Browser

Firefox

**Comment by Hunter-7010** [comment]
> ### NextUI Version
> 2.1.10
> 
> ### Describe the bug
> I have copied and pasted the code for this navbar [Navbar with Dropdown](https://nextui.org/docs/components/navbar#with-dropdown-menu) and when I open the dropdown it will not close if you click away from the dropdown.
> 
> and here is my code:
> 
> ```
> import {
>     Button,
>     Dropdown,
>     DropdownItem,
>     DropdownMenu,
>     DropdownTrigger,
>     Navbar,
>     NavbarBrand,
>     NavbarContent,
>     NavbarItem
> } from "@nextui-org/react";
> export default function NavbarWidget() {
> 
> return (
>         <Navbar>
>             <NavbarBrand>
>                 <p className="font-bold text-inherit">ACME</p>
>             </NavbarBrand>
>             <NavbarContent className="hidden sm:flex gap-4" justify="center">
>                 <Dropdown>
>                     <NavbarItem>
>                         <DropdownTrigger>
>                             <Button
>                                 disableRipple
>                                 className="p-0 bg-transparent data-[hover=true]:bg-transparent"
>                                 endContent={icons.chevron}
>                                 radius="sm"
>                                 variant="light"
>                             >
>                                 Features
>                             </Button>
>                         </DropdownTrigger>
>                     </NavbarItem>
>                     <DropdownMenu
>                         aria-label="ACME features"
>                         className="w-[340px]"
>                         itemClasses={{
>                             base: "gap-4",
>                         }}
>                     >
>                         <DropdownItem
>                             key="autoscaling"
>                             description="ACME scales apps to meet user demand, automagically, based on load."
>                         >
>                             Autoscaling
>                         </DropdownItem>
>                         <DropdownItem
>                             key="usage_metrics"
>                             description="Real-time metrics to debug issues. Slow query added? We’ll show you exactly where."
>                         >
>                             Usage Metrics
>                         </DropdownItem>
>                         <DropdownItem
>                             key="production_ready"
>                             description="ACME runs on ACME, join us and others serving requests at web scale."
>                         >
>                             Production Ready
>                         </DropdownItem>
>                         <DropdownItem
>                             key="99_uptime"
>                             description="Applications stay on the grid with high availability and high uptime guarantees."
>                         >
>                             +99% Uptime
>                         </DropdownItem>
>                         <DropdownItem
>                             key="supreme_support"
>                             description="Overcome any challenge with a supporting team ready to respond."
>                         >
>                             +Supreme Support
>                         </DropdownItem>
>                     </DropdownMenu>
>                 </Dropdown>
>                 <NavbarItem isActive>
>                     <Link href="#" aria-current="page">
>                         Customers
>                     </Link>
>                 </NavbarItem>
>                 <NavbarItem>
>                     <Link color="foreground" href="#">
>                         Integrations
>                     </Link>
>                 </NavbarItem>
>             </NavbarContent>
>             <NavbarContent justify="end">
>                 <NavbarItem className="hidden lg:flex">
>                     <Link href="#">Login</Link>
>                 </NavbarItem>
>                 <NavbarItem>
>                     <Button as={Link} color="primary" href="#" variant="flat">
>                         Sign Up
>                     </Button>
>                 </NavbarItem>
>             </NavbarContent>
>         </Navbar>
>     )
> }
> ```
> 
> ### Steps to Reproduce the Bug or Issue
> 1. Go to https://nextui.org/docs/components/navbar#with-dropdown-menu
> 2. Copy and paste the code into a file
> 3. Run code
> 4. Open dropdown
> 5. Click off the dropdown
> 
> ### Expected behavior
> When you click away from the dropdown it will close automatically.
> 
> ### Screenshots or Videos
> [Video](https://i.gyazo.com/4be2a9f24294d07e4c55165901e61d9d.gif)
> 
> ### Operating System Version
> Windows 11
> 
> ### Browser
> Firefox

Just put tabindex="-1" or tabIndex={-1}(in nextjs) on <html> element you will be good.

**Comment by jrgarciadev** [comment]
Try again using the latest version `v2.1.12` 

https://codesandbox.io/p/sandbox/hdgrs9?file=/App.jsx:1,1&utm_medium=sandpack

**Comment by rwchampin** [comment]
This medium article shows how to toggle the Dropdown menu on hover.  [Toggle NextUI Dropdown Menu on Hover](https://medium.com/@rwchampin/nextui-dropdown-on-hover-open-close-nextui-dropdown-component-on-hover-9733b1572480)
