### ISSUE TITLE
[BUG] - Accordion prevents <Input/> or <Textarea/> children from working correctly

### ISSUE THREAD

**Issue by samosaboy** [nextui-org/nextui#1608]
### NextUI Version

2.1.12

### Describe the bug

When using `<Accordion>` and `<AccordionItem>`, if the nested children are of `<Input />` or `<Textarea />` type, their input commands are not registered. For example, you are unable to use the "Spacebar" key and most punctuations.

### Your Example Website or App

https://codesandbox.io/s/morning-firefly-yscnvz?file=/src/App.js

### Steps to Reproduce the Bug or Issue

1. Use the base [accordion](https://nextui.org/docs/components/accordion#usage) example
2. Add a text area using the [Textarea](https://nextui.org/docs/components/textarea#usage) example
3. Observe that punctuations, spacebar and at times regularly input is not registered correctly

### Expected behavior

As a user, I expect input and textarea to function regularly and as expected when inside the accordion.

### Operating System Version

macOS

### Browser

Opera

**Comment by jrgarciadev** [comment]
Fixed, install the latest version `v2.1.13`

**Comment by alfredoPacheco** [comment]
It seems we are not able to use Arrows Keys (Up and Down) when using TextArea inside an Accordion.

I forked @samosaboy sandbox and upgraded to lastest NextUI version.
[sanbbox](https://codesandbox.io/p/sandbox/quizzical-pare-dwsw3k?file=%2Fpackage.json%3A8%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clprf7z7x00073b6hxal8yj30%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clprf7z7w00033b6h329l6fjw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clprf7z7w00043b6hx9hbbxt3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clprf7z7w00063b6hxsq72nf1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clprf7z7w00033b6h329l6fjw%2522%253A%257B%2522id%2522%253A%2522clprf7z7w00033b6h329l6fjw%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clprf9u6p006z3b6hky94n2ep%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clprf9u6p006z3b6hky94n2ep%2522%257D%252C%2522clprf7z7w00063b6hxsq72nf1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clprf7z7w00053b6h8eik1ki6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clprf7z7w00063b6hxsq72nf1%2522%252C%2522activeTabId%2522%253A%2522clprf7z7w00053b6h8eik1ki6%2522%257D%252C%2522clprf7z7w00043b6hx9hbbxt3%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clprf7z7w00043b6hx9hbbxt3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Please enter at least two lines in a Textarea to test. And the same applies for any other control inside an Accordion, in my case I was using TipTap.

**Comment by alfredoPacheco** [comment]
I am temporarily doing this as a workaround:

```
<AccordionItem
            key={item.$id}
            ...
            onKeyDown={e => e.stopPropagation()}
          >
            ...
```
