### ISSUE TITLE
[BUG] - Skeleton showing behind elements after they load in dark mode

### ISSUE THREAD

**Issue by stosh15x** [nextui-org/nextui#1609]
### NextUI Version

2.1.12

### Describe the bug

Skeletons are showing behind elements after they load.

It appears that the tailwind css could be compiling out of order?
If you manually uncheck the background-color: hsl... the skeleton disappears

Priority:
`:is(.dark .dark\:bg-content2) {
    --tw-bg-opacity: 1;
    background-color: hsl(var(--nextui-content2) / var(--nextui-content2-opacity, var(--tw-bg-opacity)));
}`

Being over written:
`.data-\[loaded\=true\]\:bg-transparent[data-loaded=true] {
    background-color: transparent;
}`

### Steps to Reproduce the Bug or Issue

`<Card>
            <CardBody>
                <span className={"truncate text-sm font-medium text-gray-500"}>Balance</span>
                <Skeleton isLoaded={user} className="rounded-lg bg-default-200">
                    <span className="text-2xl font-semibold tracking-tight text-success-600">{!user || toCurrency(user.balance)}</span>
                </Skeleton>
            </CardBody>
        </Card>`

### Expected behavior

I expect the skeleton to be invisible as if it where never there after the element loads.

### Screenshots or Videos

![Screenshot 2023-09-12 at 12 41 18 AM](https://github.com/nextui-org/nextui/assets/10407579/24945ca8-b245-4bca-ad87-fb62fac46733)

![Screenshot 2023-09-12 at 12 39 24 AM](https://github.com/nextui-org/nextui/assets/10407579/12db150c-a71c-4257-b4c6-593b38574d79)

### Operating System Version

macOS

### Browser

Chrome

**Comment by vinerz** [comment]
Confirmed to have this bug.

Also, Skeleton seems to not have the `disableAnimation` property implemented as per docs.

**Comment by Vicargo** [comment]
I have the same issue

**Comment by gadgetman6** [comment]
any fixes?

**Comment by jrgarciadev** [comment]
Issue reproduction: https://codesandbox.io/p/sandbox/quirky-lederberg-2kv8dn?file=%2FApp.jsx%3A1%2C1-20%2C1&utm_medium=sandpack

We will work on this soon
