### ISSUE TITLE
[BUG] - Property isRequired does not exist on Switch component

### ISSUE THREAD

**Issue by st1ng7ay** [nextui-org/nextui#1610]
### NextUI Version

2.1.12

### Describe the bug

Property isRequired does not exist on Switch component

### Steps to Reproduce the Bug or Issue

add isRequired property to Switch component

### Expected behavior

Switch have isRequired property

### Screenshots or Videos

<img width="861" alt="image" src="https://github.com/nextui-org/nextui/assets/79450231/3b3d79ce-007d-4484-ab49-401599804894">

### Operating System Version

MacOS Ventura

### Browser

Chrome

**Comment by Digoler** [comment]
I don't see this attribute in the source code

**Comment by jrgarciadev** [comment]
Hey @st1ng7ay the Switch component is not meant to be required by concept, however, you can apply your own validations using the `controlled` way https://nextui.org/docs/components/switch#controlled

We adhere to react-aria implementation which doesn't have "isRequired" support, therefore I'm going to close this issue

**Comment by st1ng7ay** [comment]
there are isRequired prop in switch props docs :

https://nextui.org/docs/components/switch#switch-props

**Comment by Glavin001** [comment]
A couple members on my team ran into this bug as well. **Docs are still not up-to-date.**
