### ISSUE TITLE
Add expanded prop to the Collapse component

### ISSUE THREAD

**Issue by klimsemenov86** [nextui-org/nextui#162]
**Is your iteration request related to a problem?**
I need a way to control the expanded state of the Collapse component. For example, when I click on the button I need to collapse the Collapse component if it was expanded before.

**Describe the solution you'd like**
The expanded prop as @jrgarciadev proposed.

**Additional context**
Here is the case: https://take.ms/TMG83

**Comment by DaniAcu** [comment]
@jrgarciadev Could you assign me?

**Comment by jrgarciadev** [comment]
For sure @DaniAcu 🙌🏻

**Comment by DaniAcu** [comment]
@jrgarciadev PR is ready to be reviewed and merged. 😆

**Comment by jrgarciadev** [comment]
Thank you @DaniAcu 🚀, @klimsemenov86 this change is already included in the new version `v1.0.2-beta.3`

**Comment by klimsemenov86** [comment]
@DaniAcu @jrgarciadev thank you! It works 👍
