### ISSUE TITLE
[BUG] - Select placeHolder and Value color

### ISSUE THREAD

**Issue by nico-limo** [nextui-org/nextui#1624]
### NextUI Version

2.1.10

### Describe the bug

I installed the Select package and I am having an issue changing the placeHolder color and Select value

I need to change the green selected text into red and also the placeholder

### Steps to Reproduce the Bug or Issue

Change the colors on the Component itself with classNames

### Expected behavior

The select value and placeholder are possible to modify

### Screenshots or Videos

CODE
![image](https://github.com/nextui-org/nextui/assets/74354611/51a158b0-ca89-4374-a58b-91a8e93f4776)

PREVIEW
![image](https://github.com/nextui-org/nextui/assets/74354611/2b870a7d-75c7-4d43-8929-53b73eccb932)

![image](https://github.com/nextui-org/nextui/assets/74354611/b299baa3-4bcb-45bb-8232-c4dd9403fac9)

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @nico-limo the placeholder is under the `value` slot, check this example: 
https://codesandbox.io/p/sandbox/vigorous-joji-crdnwd?file=%2FApp.jsx%3A1%2C1&utm_medium=sandpack
