### ISSUE TITLE
[BUG] - ListItem slots are not working

### ISSUE THREAD

**Issue by a7ul** [nextui-org/nextui#1625]
### NextUI Version

2.1.12

### Describe the bug

ListboxItem slots are not working
When I try to customize the styles for ListBoxItem using the slots, it doesnt seem to get affected.

```tsx
<Listbox className="gap-5" onAction={(key) => alert(key)}>
  <ListboxItem
    classNames={{
      title: "text-green-50",
    }}
    variant="faded"
    title="Hello"
    key="hello"
  />
</Listbox>

```

### Steps to Reproduce the Bug or Issue

1. copy the code above 
2. Try changing the title color etc
3. Title doesnt get styled

### Expected behavior

The slots should apply to the list box item

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @a7ul fixed it will be available in the next release.

In the meantime you can use `itemClasses` https://nextui.org/docs/components/listbox#customizing-the-listbox
