### ISSUE TITLE
[BUG] - Button Group issues

### ISSUE THREAD

**Issue by niklasp** [nextui-org/nextui#1626]
### NextUI Version

2.0.15

### Describe the bug

`variant="bordered"` does not show correct borders, the selected tab should have all borders

<img width="640" alt="Bildschirmfoto 2023-09-14 um 21 40 21" src="https://github.com/nextui-org/nextui/assets/1685139/ac02317e-41a8-4169-8f0a-76244be785b1">

Also setting `radius` on the `ButtonGroup` does not affect the buttons

### Steps to Reproduce the Bug or Issue

Create a button group with buttons, try to set `radius` or use bordered variant

### Expected behavior

see above

### Operating System Version

mac0s

### Browser

Firefox

**Comment by niklasp** [comment]
is this also fixed: `Also setting radius on the ButtonGroup does not affect the buttons`

**Comment by dar0xt** [comment]
same for me
