### ISSUE TITLE
[BUG] - Dropdown and Tooltip can't be used together

### ISSUE THREAD

**Issue by marian2js** [nextui-org/nextui#1647]
### NextUI Version

2.1.13

### Describe the bug

It's not possible to have a button with a Tooltip on mouse hover and a dropdown on click.

No matter how the components are combined, only one feature works at a time.

### Tooltip -> Dropdown -> DropdownTrigger -> Button

```
<Tooltip content="Foo">
  <Dropdown>
    <DropdownTrigger><Button>...</Button></DropdownTrigger>
  </Dropdown>
</Tooltip> 
```

Dropdown works, tooltip doesn't.

### Dropdown -> Tooltip -> DropdownTrigger -> Button

```
<Dropdown>
  <Tooltip content="Foo">
    <DropdownTrigger><Button>...</Button></DropdownTrigger>
  </Tooltip> 
</Dropdown>
```

Dropdown works, tooltip doesn't.

### Dropdown -> DropdownTrigger -> Tooltip -> Button

```
<Dropdown>
  <DropdownTrigger>
    <Tooltip content="Foo"><Button>...</Button></Tooltip>
  </DropdownTrigger> 
</Dropdown>
```

Tooltip works, dropdown doesn't.

### Expected behavior

As a user, I expect to be able to have a button with both a Tooltip on mouse hover and a Dropdown on click.

### Operating System Version

macOS

### Browser

Chrome

**Comment by a-ryang** [comment]
same

**Comment by jrgarciadev** [comment]
Hey guys.

Tooltip and Dropdown/Popover cannot share the same DOM element as the trigger element.

A workaround is to add an extra element inside the Tooltip. Keep in mind that the focus state will be handled differently.


```tsx
    <Popover placement="top" showArrow={true}>
      <Tooltip content="Help text">
        {/* extra element */}
        <div className="max-w-fit">
          <PopoverTrigger>
            <Button>Open Popover</Button>
          </PopoverTrigger>
        </div>
      </Tooltip>
      <PopoverContent>
        <div className="px-1 py-2">
          <div className="text-small font-bold">Popover Content</div>
          <div className="text-tiny">This is the popover content</div>
        </div>
      </PopoverContent>
    </Popover>
```

See this [Codesanbox](https://codesandbox.io/p/sandbox/musing-sun-d967kd?file=%2FApp.jsx%3A7%2C36&utm_medium=sandpack)

**Comment by jgentes** [comment]
@jrgarciadev's suggestion works, for clarity with Dropdown:
```html
<Dropdown>
  <Tooltip color="default" size="sm" content="Settings">
    <div>
      <DropdownTrigger>
        <Button>
          <SettingsIcon />
        </Button>
      </DropdownTrigger>
    </div>
    </Tooltip>
    <DropdownMenu variant="faded" aria-label="Dropdown menu with description">
      <DropdownItem key="new" description="Create a new file">
        New file
      </DropdownItem>
    </DropdownMenu>
</Dropdown>
```

**Comment by obouchari** [comment]
Is there a way to use Tooltip with ListboxItem? Can't use solution above because the ListBox expect ListBoxItem as children.
