### ISSUE TITLE
[BUG] - Chip: typo in module export

### ISSUE THREAD

**Issue by stx-chris** [nextui-org/nextui#1649]
### NextUI Version

2.1.13

### Describe the bug

There seems to be a confusion between `chip` and `Chip` in the module exports.

<img width="721" alt="image" src="https://github.com/nextui-org/nextui/assets/62717406/cbae80a7-27c5-49e7-aa36-42a2979a428f">

### Steps to Reproduce the Bug or Issue

Use `import { Chip } from "@nextui-org/chip` and build the app. The error will pop up right away

### Expected behavior

No error

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
NextUI exports all components in `lowecase` https://unpkg.com/browse/@nextui-org/chip@2.0.21/package.json, try deleting your node_modules and `.lock` file, and reinstall the packages, make sure to not have something like `@nextui-org/Chip` in your package.json file
