### ISSUE TITLE
[BUG] - Popover Blur and Opaque on mobile

### ISSUE THREAD

**Issue by isaacismaelx14** [nextui-org/nextui#1650]
### NextUI Version

2.1.13

### Describe the bug

When you touch the blur or opaque popover on mobile it is not working

### Your Example Website or App

https://nextui.org/docs/components/popover#backdrop

### Steps to Reproduce the Bug or Issue

1. Open DevTools and activate device emulation.
2. Choose a mobile device.
3. Click on either 'opaque' or 'blur'.

### Expected behavior

As mobile User, I should be able to see content.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/48190882/e551c11a-55db-470d-a6e2-57233403ff2d

### Operating System Version

macOs, android

### Browser

Chrome

**Comment by E0han** [comment]
Facing the same issue, hopefully rises someone's attention
