### ISSUE TITLE
[BUG] - Error when first time create nextui project

### ISSUE THREAD

**Issue by huynhthuan** [nextui-org/nextui#1652]
### NextUI Version

2.1.13

### Describe the bug

- I create project with command npx create-next-app -e https://github.com/nextui-org/next-app-template
- After create project done, i run project with npm run dev and open console tab
- I have error like image below
- How i can fix that error? Thank you very much.
![image](https://github.com/nextui-org/nextui/assets/43500546/54af8e96-e598-4189-b702-54939b527778)

### Steps to Reproduce the Bug or Issue

1. Run cmd npx create-next-app -e https://github.com/nextui-org/next-app-template
2. Run cmd cd to new project folder created
3. Run cmd npm run dev
4. Open with chorme and open dev console tab

### Expected behavior

I expected not see error.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/43500546/54af8e96-e598-4189-b702-54939b527778)

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Please report this to the template repo: https://github.com/nextui-org/next-app-template/pull/2

We just merged a PR that fixes some hydration issues, https://github.com/nextui-org/next-app-template/pull/2, you could try again and check if this one was fixd
