### ISSUE TITLE
[BUG] - Button: ripple elements not destoryed

### ISSUE THREAD

**Issue by wyx2333333** [nextui-org/nextui#1656]
### NextUI Version

2.0.0

### Describe the bug

when the button is clicked, will create child element span ```span class="nextui-ripple"``` and not destoryed

### Steps to Reproduce the Bug or Issue

1. Click Button
2. View Chrome DevTools Elements
3. Check Button child elements

### Expected behavior

destroy the ripple elements when the animation ends

### Screenshots or Videos

![516501695098540_ pic_hd](https://github.com/nextui-org/nextui/assets/29940101/5e405ca3-02af-44b6-aa52-0045019a5d93)
![516541695098591_ pic](https://github.com/nextui-org/nextui/assets/29940101/1844d36e-ecf2-448b-bd57-e6d202a34958)

### Operating System Version

macOS

### Browser

Chrome

**Comment by borcamichael** [comment]
When will this fix be released to npm?

**Comment by iveyZhou** [comment]
This bug still exists in the latest version, when will the fix version be released？

**Comment by moisesmiss** [comment]
I have the same issue :(
