### ISSUE TITLE
[Feature Request] Add extra attribute to automatically import NextLink internally in Link component

### ISSUE THREAD

**Issue by syntaxlexx** [nextui-org/nextui#1658]
### Is your feature request related to a problem? Please describe.

I am pleased by how good the NextUI is.
However, while using the `Link` component, it becomes so unnecessary to keep on importing 
```jsx
import NextLink from "next/link";
```

### Describe the solution you'd like

If only we could just pass an extra attribute like `next` | `asNext` | `nextLink` and the `Link` component would automatically wrap it as NextLink.

### Describe alternatives you've considered

Renaming all `Link` imports to `NextLink` and having to manually add `as={NextLink}` in all my files in Nextjs

**Comment by isaacismaelx14** [comment]
I think there is a small problem with this is that next ui is not only used with NextJS, so they would have to add next js as a dependency.  You can use it with [Remix](https://nextui.org/docs/frameworks/remix), [Astro](https://nextui.org/docs/frameworks/astro) & [Vite](https://nextui.org/docs/frameworks/vite)

What I recommend to you is to create a custom component using `as={NextLink}` and then you can re-use that component.

```ts
import { Link, LinkProps } from '@nextui-org/react';
import NextLink from 'next/link';

type Props = Exclude<LinkProps, 'as'>;

const SPALink: React.FC<Props> = (props) => {
  return (
    <Link {...props} as={NextLink}>
      {props.children}
    </Link>
  );
};

export default SPALink;

```
