### ISSUE TITLE
[BUG] - Table

### ISSUE THREAD

**Issue by Shubham-Radadiya** [nextui-org/nextui#1661]
### NextUI Version

13.4.19

### Describe the bug

I am trying to add the table code in my next js project but it is giving me an error, how can I solve it please help me.

![Screenshot (95)](https://github.com/nextui-org/nextui/assets/107168361/bfed8b74-995e-4f84-82cc-bb0f620ab99f)

### Steps to Reproduce the Bug or Issue

./..\..\node_modules\@react-aria\i18n\dist\real-module.mjs
ReactServerComponentsError:

You're importing a component that needs useEffect. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

   ,-[F:\ashvinbhai_project\node_modules\@react-aria\i18n\dist\real-module.mjs:1:1]
 1 | import $iFADg$react, {useContext as $iFADg$useContext, useState as $iFADg$useState, useEffect as $iFADg$useEffect, useMemo as $iFADg$useMemo, useCallback as $iFADg$useCallback} from "react";
   :                                                                                     ^^^^^^^^^
 2 | import {useIsSSR as $iFADg$useIsSSR} from "@react-aria/ssr";
 3 | import {LocalizedStringDictionary as $iFADg$LocalizedStringDictionary, LocalizedStringFormatter as $iFADg$LocalizedStringFormatter} from "@internationalized/string";
 4 | import {DateFormatter as $iFADg$DateFormatter} from "@internationalized/date";
   `----

### Expected behavior

./..\..\node_modules\@react-aria\i18n\dist\real-module.mjs
ReactServerComponentsError:

You're importing a component that needs useEffect. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

   ,-[F:\ashvinbhai_project\node_modules\@react-aria\i18n\dist\real-module.mjs:1:1]
 1 | import $iFADg$react, {useContext as $iFADg$useContext, useState as $iFADg$useState, useEffect as $iFADg$useEffect, useMemo as $iFADg$useMemo, useCallback as $iFADg$useCallback} from "react";
   :                                                                                     ^^^^^^^^^
 2 | import {useIsSSR as $iFADg$useIsSSR} from "@react-aria/ssr";
 3 | import {LocalizedStringDictionary as $iFADg$LocalizedStringDictionary, LocalizedStringFormatter as $iFADg$LocalizedStringFormatter} from "@internationalized/string";
 4 | import {DateFormatter as $iFADg$DateFormatter} from "@internationalized/date";
   `----

### Operating System Version

window

### Browser

Chrome

**Comment by MaxBalaban** [comment]
Hey,

If you are using Next.js 13 with the App router, you need to import the NextUI components from its individual packages, not from @nextui-org/react. In your case, try to change your import 'from' to @nextui-org/table instead of @nextui-org/react.

https://nextui.org/docs/frameworks/nextjs#use-nextui-components

**Comment by MaxBalaban** [comment]
If after changing the import statement you will see the new error, probably this issue will be helpful for you: https://github.com/nextui-org/nextui/issues/1574

Good luck!

**Comment by mo-mainstream** [comment]
hello, I'm still getting this error even after importing the table from `@nextui-org/table` and adding `use client` at the top of the file. 
<img width="736" alt="image" src="https://github.com/nextui-org/nextui/assets/130951625/1b33f2c0-bd54-4f2a-a7f0-79d7a106a80e">

I'm using `"@nextui-org/table": "^2.0.23"` and the latest `nextjs 13.5.3` with App Router.

**Comment by MaxBalaban** [comment]
> hello, I'm still getting this error even after importing the table from `@nextui-org/table` and adding `use client` at the top of the file.

@mo-mainstream Hey,
I would suggest you check if you nested the elements right, for example:

```JSX
<Table>
      <TableHeader>
        <TableColumn>NAME</TableColumn>
      </TableHeader>
      <TableBody>
        <TableRow key="1">
          <TableCell>Tony Reichert</TableCell>
        </TableRow>
      </TableBody>
    </Table>
```

If you add a div element as a child of the table body, it probably will not work. You can start with the table from the documentation and then edit it. If it still will not work, please share the code with us.

**Comment by mo-mainstream** [comment]
Hey @MaxBalaban , thank you for your quick reply and the hint you gave regarding the structure. I had a `<Pagination>` component after the `<TableBody>` and inside the `<Table>`. This used to work fine in v1, but since we moved to v2 and nextjs, this caused the error above.

So if you have this code, it will not work:
```
<Table>
  <TableHeader>
    <TableColumn>NAME</TableColumn>
  </TableHeader>
  <TableBody>
    <TableRow key="1">
      <TableCell>Tony Reichert</TableCell>
    </TableRow>
  </TableBody>
  <Pagination />
</Table>
```

I had to move the pagination outside the table component.

**Comment by jrgarciadev** [comment]
Hey @mo-mainstream NextUI v2 is not backwards compatible with v1, table with. pagination implementation changed, you need to use `bottomContent` prop to add the pagination, please check this example: https://nextui.org/docs/components/table#paginated-table
