### ISSUE TITLE
[Feature Request] stepper and searchable select/autocomplete

### ISSUE THREAD

**Issue by ayubaezekiel** [nextui-org/nextui#1670]
### Is your feature request related to a problem? Please describe.

A searchable or autocomplete suitable for large data and a stepper useful for multi step form

### Describe the solution you'd like

The two components are in reference to mantineUI, behavior can be similar.

### Describe alternatives you've considered

Coming from mantineUI, those are only two components lacking

**Comment by Julius-Java** [comment]
I would love to be assigned this task and implement it. Thank you very much.

**Comment by Tomycl** [comment]
here's an example:
[Stepper Component](https://mantine.dev/core/stepper/)
