### ISSUE TITLE
[BUG] - Select

### ISSUE THREAD

**Issue by DeshChow** [nextui-org/nextui#1684]
### NextUI Version

2.0.10

### Describe the bug

- Selected value is not showing when controlling it with Formik. It is taking the selected value. But not showing in the UI.

### Steps to Reproduce the Bug or Issue

1. Control the select box using formik

### Expected behavior

1. The selected value should show in the UI

### Operating System Version

macOs

### Browser

Chrome

**Comment by Sisableng** [comment]
is there any solution for this? or how to use the selectedKeys or defaultSelectedKeys for this Select component?
I tried to imitate as in the doc but not showing in the ui, same as your problem

**Comment by DeshChow** [comment]
> you just need to pass the key inside an array like this `['cat']` for example `selectedKeys={['cat']}`

Yes. It is working . Thanks.
