### ISSUE TITLE
[BUG] - Tailwind setup for Vite

### ISSUE THREAD

**Issue by Redoxahmii** [nextui-org/nextui#1687]
### NextUI Version

2.1.13

### Describe the bug

The configuration provided in the documentation of the website for tailwind.config.js is 
```
// tailwind.config.js
const {nextui} = require("@nextui-org/react");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    // ...
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [nextui()],
};
```
 this method disables all the text utility classes provided by tailwind as the preconfigured tailwind.config.js looks something like this 
```
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
``` 

Update the documentation so this issue does not occur.

### Steps to Reproduce the Bug or Issue

1. Create a Vite NextUI project with the documentation provided on their website.

### Expected behavior

Have my Text utilities working but instead it disables all of them.

### Operating System Version

Linux

### Browser

Chrome

**Comment by 5war00p** [comment]
@Redoxahmii  Can you confirm that you have added your `components`, `pages` folder/file paths to the content array in `tailwind.config.ts`?

**Comment by Yukiniro** [comment]
I have the same problem. And there is only one file entry named `src`.

**Comment by Yukiniro** [comment]
I noticed there is a path ` "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",` in `tailwind.config.ts`. But there is no `@nextui-org/theme` in the `node_modules`. So, I installed `@nextui-org/theme` which could resolve this problem.

**Comment by Redoxahmii** [comment]
> @Redoxahmii Can you confirm that you have added your `components`, `pages` folder/file paths to the `content` array in `tailwind.config.ts`?

For me i have never had to add those specifically but using the provided config by tailwindcss everything works out of the box. Currently the only way it is working is by doing this 
`/* eslint-disable no-undef */
const { nextui } = require("@nextui-org/react");
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [nextui(), require("tailwindcss-animated")],
};
`
If there is something i might be missing i would be glad to know more about.

**Comment by 5war00p** [comment]
Ofcourse you need to add three items in the `content` array.
- To support tailwind styles you need to add the file paths (wildcards) - in your case  `index.html` and every `js, ts, tsx, jsx` file inside `/src`
- To support nextui styles and themes you need add `"./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}"`

So what you had done previously is you copy pasted the one that given nextui, which doesn't contain your src path and index.html, if you closely see  three dots inside content array represents you need to add nextui-theme to the array with existing patterns
![image](https://github.com/nextui-org/nextui/assets/57614947/fa19c464-8d5c-4db7-8f4b-55464934d003)

**Comment by Redoxahmii** [comment]
Does not really clarify clearly so should look into that making it a bit more simpler for someone coming newly to your library. Simply adding a comment would make it more clear.

**Comment by 5war00p** [comment]
> Does not really clarify clearly so should look into that making it a bit more simpler for someone coming newly to your library. Simply adding a comment would make it more clear.

So what I'm explaining is you should understand configuring tailwind fully. The file paths that are added to the `content` array in `tailwind.config.js` only supports the tailwind classes, other files won't be able to apply tailwind styles. As NextUI themes depends on tailwind classes you need to add that to the `content` array which is given in NextUI docs. Adding other file paths simply denoted by `...`, so you need to add your required files over there.

Earlier you just copy pasted from NextUI docs where you lost all you files paths inside `content` array so styles were missing.
