### ISSUE TITLE
[BUG] - Textarea Input height is conflict

### ISSUE THREAD

**Issue by PlayerNguyen** [nextui-org/nextui#1690]
### NextUI Version

2.1.12

### Describe the bug

When I implemented the Textarea component with react-hook-form and react-i81next
```jsx
<Textarea
              label={t("xxx")}
              placeholder={t(
                "xxx.placeholder"
              )}
              fullWidth
              minRows={5}
              cacheMeasurements
              labelPlacement="outside"
              description={t(
                "xxx.altLabel"
              )}
              {...register("metaDescription")}
            />
```
The Textarea is broken like this
<img width="503" alt="image" src="https://github.com/nextui-org/nextui/assets/10703461/831ca595-7cab-4dd5-9bd0-7e7fafd18d09">

After trying to browse some stuffs on Edge Debug Tool, I found that when I disabled the line `.h-unit-10` style, the text area worked as expected.

<img width="441" alt="image" src="https://github.com/nextui-org/nextui/assets/10703461/b801e822-4cf3-4c15-be9a-15d7bef2f49f">

<img width="574" alt="image" src="https://github.com/nextui-org/nextui/assets/10703461/5cf42e8b-7517-40b8-a567-a4fa7ab19973">

### Steps to Reproduce the Bug or Issue

1. Setup a Vite - Tailwind - NextUI 
2. Implement the Textarea as above
3.  Met the error

### Expected behavior

As a user, I expected to see full-width Textarea but I am seeing a collapsed text-area

### Operating System Version

Latest macOS Ventura

### Browser

Edge

**Comment by lalalazero** [comment]
Hello~

I'm trying to find out what's wrong here. so I'm using your code to test, but style is fine as below.

![image](https://github.com/nextui-org/nextui/assets/20458239/1c75af1a-cc84-4fc1-ae5b-8a57b7760bfa)

the code is 
```
import { Textarea, Button } from '@nextui-org/react'
import { useForm } from 'react-hook-form'

export const Test = ({
    children,
}: {
    children: React.ReactNode;
}) => {

    const { register, handleSubmit } = useForm()
    const onSubmit = (data: any) => {
        console.log('去提交', data)
    }
    return <form onSubmit={handleSubmit(onSubmit)}>
        <Textarea
            label={"label"}
            placeholder={
                "test placeholder"
            }
            fullWidth
            minRows={5}
            cacheMeasurements
            labelPlacement="outside"
            description={
                "desription altLabel"
            }
            {...register("abc")}
        />
        <Button type='submit'>submit</Button>
    </form>

}

```

would you please provide a minimal reproducible repo for more details?

**Comment by Nichtmetall** [comment]
Hey, I had the same issue. My fix was simply adding a `div` wrapper around the `Textarea` component and overwrite the css. 

```css
#textarea-wrapper > div > div {
    height: auto !important;
}
```

**Comment by PlayerNguyen** [comment]
@Nichtmetall Thanks, smooth like a butter man

**Comment by AlpayC** [comment]
Hello, I have used the code with the CSS rule as a workaround, but it doesn't seem to be working. What am I doing wrong? Here is my code

`        <div
          className="flex justify-center items-start gap-10 h-[100vh] w-3/4"
          id="textarea-wrapper"
        >
          <Textarea
            label="Input"
            labelPlacement="outside"
            placeholder="Enter your JSON"
            className="max-w-6xl "
            onChange={(e) => setValue(e.target.value)}
            children={value}
          />

          <Textarea
            label="Output"
            labelPlacement="outside"
            placeholder="Here comes the Output"
            className="max-w-6xl"
            value={JSON.stringify(outputValue, null, 2)}
            isReadOnly={true}
          />
        </div>`

**Comment by Nichtmetall** [comment]
Did you forgot to put the closing tag for the `<div>`?

Otherwise I can Imagine that the `h-[100vh]` is overwriting your style.

**Comment by AlpayC** [comment]
yeah it was the height. Thank you. 

I hope it will be featured/fixed in the next release. 

Have a nice weekend

> Did you forgot to put the closing tag for the `<div>`?
> 
> Otherwise I can Imagine that the `h-[100vh]` is overwriting your style.

yeah it was the height. Thank you. 

I hope it will be featured/fixed in the next release. 

Have a nice weekend

**Comment by AlpayC** [comment]
Did you forgot to put the closing tag for the <div>?

Otherwise I can Imagine that the h-[100vh] is overwriting your style.

**Comment by Nichtmetall** [comment]
Hopefully! :D

**Comment by jrgarciadev** [comment]
Hey guys if you want to disable the Textarea autosize you can use the `disableAutosize` property, so it will be render as a normal Textarea without the height calculations.

**Comment by SimonDeconde** [comment]
> Hey, I had the same issue. My fix was simply adding a `div` wrapper around the `Textarea` component and overwrite the css.
> 
> ```ts
> <div id='textarea-wrapper'>
>    <Textarea {...props} />
> </div>
> ```
> 
> ```css
> #textarea-wrapper > div > div {
>     height: auto !important;
> }
> ```

This fixed my problem too. Thanks a LOT, @Nichtmetall !
