### ISSUE TITLE
[BUG] - Navbar positions

### ISSUE THREAD

**Issue by Redoxahmii** [nextui-org/nextui#1694]
### NextUI Version

2.1.13

### Describe the bug

The navbar when used with position sticky takes space inside the page lets say if I use w-screen and h-screen although it is sticky it still takes space in the page which causes the page to become scrollable.

### Steps to Reproduce the Bug or Issue

1.Use Navbar with position sticky (default behavior)
2.Make the page take 100vw and 100vh

### Expected behavior

Should not cause the page to become scrollable.

### Operating System Version

Linux

### Browser

Chrome

**Comment by ghOst-vedant** [comment]
hello are your working on this issue??

**Comment by abhinandan-verma** [comment]
@Redoxahmii  I would like to solve this issue,
can you provide the reproducing code, I know its too late but if is possible

**Comment by abhinandan-verma** [comment]
@Redoxahmii  I believe it will be if you close the issue.  If  any such issue is found, I will try to resolve it thereby.
