### ISSUE TITLE
[BUG] - Navbar sticky position doesnt work

### ISSUE THREAD

**Issue by cha2hyun** [nextui-org/nextui#1697]
### NextUI Version

2.1.13

### Describe the bug

navbar's position-sticky doesnt work. 

Noted
Tested browsers : chrome, firefox, safari
Template Used : https://github.com/nextui-org/next-pages-template

### Your Example Website or App

https://nangmanski.com/

### Steps to Reproduce the Bug or Issue

1. make navbar position sticky
2. scroll to bottom
3. sticky position doesnt work

### Expected behavior

expected to be not scrolled, but it is scrollable 

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/56015532/728f5734-8a94-4286-9bcc-c5072ffb1a80

### Operating System Version

macOs, iPhone

### Browser

Firefox

**Comment by 5war00p** [comment]
Hey @cha2hyun, this is a styling problem with the template that you used over here: 
https://github.com/nextui-org/next-pages-template/blob/main/layouts/default.tsx#L11

There is a parent div `<nav>`  which has height specified as `h-screen`, so all the children are gonna scroll after the screen's height.

There is no issue with Navbar, it acts as parent element says.

See this (without `h-screen`):

https://github.com/nextui-org/nextui/assets/57614947/2d2ac8d1-dc66-46c0-b776-c623704a2a3f

**Comment by cha2hyun** [comment]
> Hey @cha2hyun, this is a styling problem with the template that you used over here: https://github.com/nextui-org/next-pages-template/blob/main/layouts/default.tsx#L11
> 
> There is a parent div `<nav>` which has height specified as `h-screen`, so all the children are gonna scroll after the screen's height.
> 
> There is no issue with Navbar, it acts as parent element says.
> 
> See this (without `h-screen`):
> 
>  2023-09-26.23-44-18.mp4

Thanks for solution 👍
