### ISSUE TITLE
[BUG] - ListboxItem does not update when component state changes.

### ISSUE THREAD

**Issue by WorldOfMaze** [nextui-org/nextui#1700]
### NextUI Version

2.1.10

### Describe the bug

When a React component's state changes, the ```ListboxItem```s do not re-render and, as a result, the new state is not reflected in the ```Listbox```.

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-bubauw?file=app%2Ftest.tsx

### Steps to Reproduce the Bug or Issue

1. Open the ```Stackblitz```  project.
2. Clear the ```Search``` input.
3. The first list item will have a title of ```One-```.
4. Type ```abc``` in the ```Search``` input.

### Expected behavior

The title of the first list item should be updated as the the value of the search input changes.  At the end of the steps above, the title still reads ```One-``` rather than ```One-abc```.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by WorldOfMaze** [comment]
Upgrade ```nextui-org/react``` to 2.1.13.  Same results.

**Comment by clouddna-au** [comment]
Upgrade to 2.210 same thing

**Comment by rpdave** [comment]
The issue here is that the ListboxItems are memoized.
This means that only when the items are updated the ListBoxItem will reflect those changes.

So in you example you need to update the code to the following. Please see comments marked with numbers. I can see that this achieves the result that you want `One-abc.`
```
'use client';

import { Input } from '@nextui-org/input';
import { Listbox, ListboxItem } from '@nextui-org/react';

import { useState } from 'react';

const data = [
  { id: '1', name: 'One', description: 'The value one.', searchValue: '' }, // 1. Add a searchValue key to each item
  { id: '2', name: 'Two', description: 'The value two.', searchValue: '' },
  { id: '3', name: 'Three', description: 'The value three.', searchValue: '' },
];

const ListboxTest = () => {
  const [searchValue, setSearchValue] = useState('');
  const [myData, setMyData] = useState(data); // 2. Put your data in state
  return (
    <div className="m-10 flex flex-col gap-4">
      <Input
        className="mb-4"
        color="default"
        isClearable={true}
        label="Search..."
        onValueChange={(value) => {
          setSearchValue(value);
          // 3. Everytime you update the value update the total state as well.
          // You could also make a precise insertion, here I have updated all the values
          setMyData([
            ...myData.map((dataItem) => ({
              ...dataItem,
              searchValue: value,
            })),
          ]);
        }}
        placeholder="Search..."
        radius="lg"
        variant="flat"
      />
      <Listbox items={myData} color="primary">
        {(item) => (
          <ListboxItem key={item.id} description={item.description}>
            {/* 4. Use the searchValue from item */}
            {`${item.name}-${item.searchValue}`}
          </ListboxItem>
        )}
      </Listbox>
      <p className="mt-8 border border-t-slate-600 pt-4 underline">
        Current value of <e>searchValue</e>
      </p>
      <div className="mx-8 min-h-[58px] rounded-lg border border-slate-600 p-4">
        {searchValue}
      </div>
    </div>
  );
};

export default ListboxTest;
```

**Comment by WorldOfMaze** [comment]
@rpdave Thank you for your help with this.
