### ISSUE TITLE
[Model] Press `esc` when typing with input method will close modal

### ISSUE THREAD

**Issue by Innei** [nextui-org/nextui#1705]
### NextUI Version

2.1.13

### Describe the bug

When I'm typing with the input method, pressing esc closes the modal instead of just interrupting the typing

### Steps to Reproduce the Bug or Issue

1. Open model
2. Typing with  the input method
3. press Esc

### Expected behavior

Don't close modal when typing.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/41265413/227b12cd-3ec0-453e-904c-3f2e9cb9e51d

### Operating System Version

macOS

### Browser

Chrome

**Comment by Innei** [comment]
For those of us who use input methods for typing, you need to handle the (compositionstart_event)[https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event] event

**Comment by wingkwong** [comment]
you may set `isKeyboardDismissDisabled` to `true`
