### ISSUE TITLE
[BUG] - Hydration failed error with the table component

### ISSUE THREAD

**Issue by chloehjung15** [nextui-org/nextui#1709]
### NextUI Version

2.1.10

### Describe the bug

When using the table component, I get the hydration error for react
```
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <tr> in <table>.

```
I think this is because in the <TableHeader> component, it only takes in <TableColumn> components which are <th> tags so it's missing a <tr> tag in the <thead>. 

### Steps to Reproduce the Bug or Issue

1. Create a react project
2. Use the <Table> component

### Expected behavior

No hydration error

### Operating System Version

ubuntu

### Browser

Chrome

**Comment by GioooTDM** [comment]
Same problem here.

```js
const TableTest = () => {
    return (
        <div>
            Caratteristiche
            <table>
                <tr>
                    <td>
                        Foo
                    </td>
                    <td>
                        Bar
                    </td>
                </tr>
                <tr>
                    <td>
                        Foo 
                    </td>
                    <td>
                        Bar
                    </td>
                </tr>
            </table>
        </div>
    );
}
```
![image](https://github.com/nextui-org/nextui/assets/73108434/9107652f-8557-4b1c-bad7-f2bcda2eabde)

**Comment by wingkwong** [comment]
you may try wrapping by `<tbody>`
