### ISSUE TITLE
[Feature Request] Skeleton should prevent it;s hidden content from being clicked to trigger the onPress event for the hidden content example Button

### ISSUE THREAD

**Issue by prince272** [nextui-org/nextui#1714]
### Is your feature request related to a problem? Please describe.

When clicking on an enabled Skeleton animation, it still works.

### Describe the solution you'd like

Consider applying a pointer events = none when a component is clicked on an enabled Skeleton animation.

### Describe alternatives you've considered

Consider applying a pointer events = none when a component is clicked on an enabled Skeleton animation.

**Comment by wingkwong** [comment]
I couldn't reproduce the issue on the latest version. Can you share your code?
