### ISSUE TITLE
[BUG] - Page doesn't scroll when `disableAnimation={true}` on the `<Navbar/>`

### ISSUE THREAD

**Issue by JoWinner** [nextui-org/nextui#1735]
### NextUI Version

2.1.13

### Describe the bug

Every page refuses to scroll after complete loading when `disableAnimation` is set to `true` on the `<Navbar/>` component. After setting `disableAnimation` to `false` the page scrolls perfectly.

### Steps to Reproduce the Bug or Issue

1. Add  the `<Navbar/>` component to a page.
2. Pass `disableAnimation={true}` prop to `<Navbar/>` component
3. Reload the page and scroll (wait for load completion)
4. Pass `disableAnimation={false}` prop to `<Navbar/>`
5. Reload the page and scroll (wait for load completion)

### Expected behavior

Pages must scroll after load completion but when `disableAnimation` is `true` it doesn't scroll. Page can only be scrolled on the `scrollbar` or during page load.

### Operating System Version

Windows

### Browser

Chrome

**Comment by nikita-shtimenko** [comment]
Same issue.
Spent a lot of time trying to fix it, till i ended up here.

**Comment by eracoding-de** [comment]
Can confirm this bug.
