### ISSUE TITLE
Remove focus border (outline) on safari

### ISSUE THREAD

**Issue by shaynlink** [nextui-org/nextui#174]
First sorry for my English 😅

Isn't really a bug, focus border (aka outline) is a default css in all navigator, it's not working on chrome but it's on safari.

**Why remove outline ?**
What is outline ? outline is a default css style active when a div (or other component) is focused, for indicate to user that this component is used.
But when outline is active, on toggle you have an unpleasant feeling and you want to click outside the component for remove outline (please say me I'm not alone 😟).
So this feeling is not good for user experience, because for one click component like toggle you need click two time (one time for interact with component and one time outside component for remove outline).
You can keep outline for multi interact component like input, but isn't good for one click component like toggle, button or for parent/global component like card.

**Steps to reproduce**
1. Click on toggle
2. See outline

**Expected behaviour**
Outline not apparead

**Screenshots**
<img width="707" alt="image" src="https://user-images.githubusercontent.com/38408035/151521363-fdd18d2b-7a00-49ab-9245-a81d86b21ba3.png">
<img width="128" alt="image" src="https://user-images.githubusercontent.com/38408035/151521434-1d67f60d-8928-4134-b7ea-fdd285e15da9.png">

**Environment / Context**
- Desktop (I don't have iPhone, so idk for safari mobile)
- Operating System: MacOS 12.2
- Browser and version: Safari stable 15.3
- Device: MacBook Pro 2020 M1

**Comment by mariusflorescu** [comment]
@shaynlink thank you for reporting !

**Comment by Joaovsa7** [comment]
Isn't an outline good for accessibility? I think that we should consider this point before removing it. 

What do you think about it?

**Comment by Perni1984** [comment]
yes it is - better to style the outline in a proper way than to remove it.

https://www.a11yproject.com/posts/never-remove-css-outlines/

**Comment by asleepingpanda** [comment]
I have a card based design that I would prefer to not have a focus state on at all. Is there any way to remove it, currently?
