### ISSUE TITLE
Add hover effect to Button component

### ISSUE THREAD

**Issue by siddiquiaffan** [nextui-org/nextui#1748]
### Is your feature request related to a problem? Please describe.

When we hover over the button created using Button component, we see nothing. There should be a hover effect, it'll make the UX even better.

### Describe the solution you'd like

Add hover effect on Button component

### Describe alternatives you've considered

NA

### Screenshots or Videos

[Button-NextUI---Beautiful-fast-and-modern-React-UI-Library.webm](https://github.com/nextui-org/nextui/assets/61529008/859fd1ff-89e2-4518-becc-81d9c3621eb3)

**Comment by kevin-eberhardt** [comment]
Hi together,
Yes, that would be perfect!
@siddiquiaffan: Maybe interesting for you: As a workaround I created my own simple component that adds the hover effect using the tailwind classes.

```typescript
import { ButtonProps } from "@nextui-org/react";
import { Button as NextUIButton } from "@nextui-org/react";
export default function Button({
  children,
  color,
  className,
  ...rest
}: ButtonProps) {
  if (color === "primary") {
    className = `${className} hover:bg-primary-800 dark:hover:bg-primary-100`;
  }
  if (color === "default" || color === undefined) {
    className = `${className} hover:bg-gray-100 border-gray-300 border-1 dark:border-gray-700 dark:hover:bg-gray-700`;
  }

  return (
    <NextUIButton color={color} className={className} {...rest}>
      {children}
    </NextUIButton>
  );
}
``` 

👋 Kind regards

**Comment by siddiquiaffan** [comment]
Hey, it looks great!

I was just suggesting that it should be already included in it.

**Comment by jrgarciadev** [comment]
Added in v2.2.0


https://github.com/nextui-org/nextui/assets/30373425/5a5d66e5-8075-4f74-9ab1-da929f5c3a43

**Comment by siddiquiaffan** [comment]
> Added in v2.2.0
> 
>  CleanShot.2023-11-05.at.08.37.35.mp4

Looks like, just reduced opacity on hover.

BTW looks good 👍

**Comment by jrgarciadev** [comment]
Yes @siddiquiaffan, and you can control that opacity by using the new `hoverOpacity` variable.

```ts
module.exports = {
  plugins: [
    nextui({
      themes: {
        light: {
          layout: {
            hoverOpacity: 0.8, //  this value is applied as opacity-[value] when the component is hovered
          },
        },
        dark: {
          layout: {
            hoverOpacity: 0.9, //  this value is applied as opacity-[value] when the component is hovered
          },
        },
      },
    }),
  ],
};
```

**Comment by siddiquiaffan** [comment]
Thanks @jrgarciadev, looks really good. I think we should also be able to control the opacity on component level by passing `hoverOpacity` prop.

**Comment by jrgarciadev** [comment]
You're welcome 🤝  @siddiquiaffan 

You can use TailwindCSS classes to change the hover opacity at component level

```ts
<Button classNames="data-[hover=true]:opacity-50">Button</Button>
```

**Comment by siddiquiaffan** [comment]
Ofcourse we can make use of Tailwind CSS, I suggested prop thing for more
simplicity.

**Comment by jrgarciadev** [comment]
Tailwind css doesn't support dynamic classes https://tailwindcss.com/docs/content-configuration#dynamic-class-names, so having a property that accepts a number for opacity will not work
