### ISSUE TITLE
[BUG] - No se esta importando "@nextui-org/react": "latest"

### ISSUE THREAD

**Issue by mendozalz** [nextui-org/nextui#1755]
### NextUI Version

2.1.13

### Describe the bug

Al guiarme por los pasos de la instalación de las dependencias hace falta "@nextui-org/react": "latest"

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/p/sandbox/s6cnwl?file=%2Fpackage.json%3A11%2C5-11%2C34&utm_medium=sandpack

Allí es donde pude encontrar la dependencia que me hacia falta

### Expected behavior

no funciona, ni toma el tailwind

### Operating System Version

Windows

### Browser

Chrome

**Comment by szbphoto** [comment]
Hi, can you give me an english description? So i can help you

**Comment by mendozalz** [comment]
Sorry for not having written the issue in English, it happens that when you want to use nextui from the installations of individual packages you need to add to npm the installation of "@nextui-org/react": "latest" which gave me headaches head to start making use of the components.

**Comment by jrgarciadev** [comment]
Hey @mendozalz the purpose of "Individual" installation is to install only the components that you need, so you have to refactor the imports accordingly

For instance these imports:
`import {Card, CardHeader, CardBody, CardFooter, Avatar, Button} from "@nextui-org/react";`

Need to be changed to:
 `import {Card, CardHeader, CardBody, CardFooter} from "@nextui-org/card";
 import {Avatar} from "@nextui-org/avatar";
 import {Button} from "@nextui-org/button";
`

You can find the individual imports in the documentation at the top.

![CleanShot 2023-10-26 at 09 41 29](https://github.com/nextui-org/nextui/assets/30373425/d83e5d73-9261-4dc4-9123-aec2ae7f1668)
