### ISSUE TITLE
[BUG] - Image Cors issue [solved] 

### ISSUE THREAD

**Issue by IntelligentQuantum** [nextui-org/nextui#1756]
### NextUI Version

2.1.13

### Describe the bug

Well i use NextJs for my project and i have cors origin issue with images

When i import image from (import {Image} from "@nextui-org/react";) it gives me cors origin error

`“http://localhost:4000/account/uploaded-image/profile/profile.jpg” was blocked due to its Cross-Origin-Resource-Policy header (or lack thereof)`

But it works well with import Image from 'next/image';

### Steps to Reproduce the Bug or Issue

1. Import Avatar Or Image From NextUI
2. Create an api with nestjs and put this to your controller
3. `return res.sendFile(join(__dirname, '..', '..', `uploads/${ folder }/${ image }`));`

`
<Image
    src={`http://localhost:4000/account/uploaded-image/posts/${ image }`}
    alt='Image'
/>
`

Then you get cors error

### Expected behavior

Should not get cors error

### Operating System Version

Linux, windows

### Browser

Firefox

**Comment by keyskull** [comment]
the bug seems to still happening

**Comment by CX330Blake** [comment]
> the bug seems to still happening

Same here

**Comment by IntelligentQuantum** [comment]
```js
import type { NextConfig } from 'next';

const nextConfig: NextConfig =
{
    images:
    {
        remotePatterns:
        [
            {
                protocol: 'https',
                hostname: '**'
            },
            {
                protocol: 'http',
                hostname: '**'
            }
        ]
    }
};

export default nextConfig;

```

BackEnd

```js

    const corsOptions: CorsOptions =
    {
        origin: ['http://localhost:3000'],
        methods: 'GET, HEAD, PUT, PATCH, POST, DELETE',
        credentials: true,
        preflightContinue: false,
        optionsSuccessStatus: 204
    };

    app.enableCors(corsOptions);
```

I did these things and works fine
