### ISSUE TITLE
[BUG] - Select Item does not appear when used inside a Modal

### ISSUE THREAD

**Issue by ymhaah** [nextui-org/nextui#1758]
### NextUI Version

2.1.13

### Describe the bug

If you put a Select inside a Modal the select items does not appear when using the select, This problem only appears in this following casethe

### Steps to Reproduce the Bug or Issue

 put a Select inside a Modal

### Expected behavior

the select items does not appear

### Screenshots or Videos

![التقاط الويب_11-10-2023_143630_localhost](https://github.com/nextui-org/nextui/assets/77534098/23586b45-796b-455a-a88e-7a992085a332)

### Operating System Version

Windows

### Browser

Edge

**Comment by szbphoto** [comment]
Hello, can you provide a source code for it? I have tried it and its works fine

**Comment by ymhaah** [comment]
> Hello, can you provide a source code for it? I have tried it and its works fine

### Here's a general example that faces the same problem

```ts
<Modal isOpen={isOpen} onOpenChange={onOpenChange} size="xl">
                <ModalContent>
                    {(onClose) => (
                        <>
                            <ModalHeader className="flex flex-col gap-1">
                                modal
                            </ModalHeader>
                            <ModalBody>
                                <Select label="select" className="max-w-xs">
                                    <SelectItem key={1} value="1">
                                        1
                                    </SelectItem>
                                    <SelectItem key={2} value="2">
                                        2
                                    </SelectItem>
                                    <SelectItem key={3} value="3">
                                        3
                                    </SelectItem>
                                </Select>
                            </ModalBody>
                            <ModalFooter>
                                <Button
                                    color="primary"
                                    type="submit"
                                    onPress={() => {
                                        onClose();
                                    }}
                                >
                                    Add
                                </Button>
                            </ModalFooter>
                        </>
                    )}
                </ModalContent>
 </Modal>
```
### Before opening the select:

![التقاط الويب_14-10-2023_21306_localhost](https://github.com/nextui-org/nextui/assets/77534098/b36e94f0-c71c-4370-95d6-d245e5f456cf)
### after opening the select:

![التقاط الويب_14-10-2023_212933_localhost](https://github.com/nextui-org/nextui/assets/77534098/2743f5af-e3fe-42b7-979e-fb2cf4fad0db)
---

**Comment by Safee-ullah1** [comment]
I had this error on Next.js 14.3.0-canary.30 and it was due to partial prerendering enabled

**Comment by wingkwong** [comment]
Closing - please try on the latest version.

![image](https://github.com/nextui-org/nextui/assets/35857179/85d907e7-8574-4757-aebf-8345b3f5e4ef)

**Comment by jackwong721** [comment]
I have the same issue on the modal components only. At the main page, it work fines. When it comes to modal, it could not pop the select item element as described as this post. Anyone know the solution?

**Comment by j3rryl** [comment]
Did you find a work around for the above issue?

**Comment by jackwong721** [comment]
> Did you find a work around for the above issue?
Try to use NextUi official modal. The issue can be eliminated. Don’t use self created modal. Then should be work

**Comment by j3rryl** [comment]
@jackwong721 
This is what I was doing.
`
const roles = [
  {key:"admin", label:"admin"},
  {key:"user", label:"user"},
];
<Modal
        isOpen={editModal.isOpen}
        onOpenChange={editModal.onOpenChange}
        placement="top-center"
        size="lg"
      >
        <ModalContent>
          {(onClose) => (
            <>
              <form>
                <ModalHeader className="flex flex-col gap-1">
                  Confirm Action
                </ModalHeader>
                <ModalBody>
                  <Input
                    label="First Name"
                    placeholder="Enter first name"
                    type="text"
                    name="first_name"
                    isRequired
                    variant="bordered"
                  />
           
                  <Select
                    label="Role"
                    placeholder="Select role"
                    variant="bordered"
                  >
                    {roles.map((role) => (
                      <SelectItem key={role.key} textValue={role.label}>
                        {role.label}
                      </SelectItem>
                    ))}
                  </Select>
                </ModalBody>
                <ModalFooter>
                  <Button color="danger" variant="flat" onPress={onClose}>
                    Close
                  </Button>
                  <Button color="primary" type="submit">
                    Save
                  </Button>
                </ModalFooter>
              </form>
            </>
          )}
        </ModalContent>
      </Modal>
`

I believe I am using the NextUI Modal, however when I move it outside the modal, I am able to see the Select items. Could there be an issue Modal?

**Comment by x0m4ek** [comment]
> Did you find a work around for the above issue?

npm install @nextui-org/react@latest update to last version like mentioned above
