### ISSUE TITLE
[BUG] - [Docs > Select > controlling with state] state seems not changed on button click event

### ISSUE THREAD

**Issue by cha2hyun** [nextui-org/nextui#1762]
### NextUI Version

current

### Describe the bug

https://nextui.org/docs/components/select#controlling-the-open-state

it seems state does not changed on button click event

### Steps to Reproduce the Bug or Issue

1. Docs > Select
2. controlling-the-open-state
3. press open
4. press close > doesnt work

### Expected behavior

state has to be changed 

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/56015532/e7194b4f-d181-47c7-9169-3e78e730db6e

### Operating System Version

macOs, iPhone

### Browser

Chrome

**Comment by bibaswan7** [comment]
I am interested to solve this, please assign it to me
