### ISSUE TITLE
[BUG] - Components/Text

### ISSUE THREAD

**Issue by farshed** [nextui-org/nextui#1767]
### NextUI Version

2.1.13

### Describe the bug

I can't seem to import many components including `Text` and `Container`. When I try to, I get an error that such a component is not exported from "@nextui-org/react". I have also tried importing them from "@nextui-org/container" or "@nextui-org/text" but these submodules don't exist either.

### Steps to Reproduce the Bug or Issue

Try to import Text into a TypeScript React project.

`import { Text } from '@nextui-org/react';`

### Expected behavior

N/A

### Screenshots or Videos

<img width="576" alt="Screenshot 2023-10-14 at 4 17 29 PM" src="https://github.com/nextui-org/nextui/assets/23633421/4cdb73e4-f21f-4982-9cde-ecba5ab8c678">
<img width="592" alt="Screenshot 2023-10-14 at 4 17 42 PM" src="https://github.com/nextui-org/nextui/assets/23633421/3fbc64a2-fe92-4758-8fec-1f26b9ca8b37">

### Operating System Version

macOS Ventura 13.0.1

### Browser

Chrome

**Comment by JaviCeRodriguez** [comment]
Hi @farshed !

I had the same problema on migrating a next app from v1 beta to v2. Searching in previous issues, I found this issue #1489 

Maybe making a new Text component with Tailwind classes, you can resolve this. See the docs about [text classes](https://tailwindcss.com/docs/font-size)

**Comment by jrgarciadev** [comment]
Hey @farshed NextUI v2 doesn't include a Text component due to TailwindCSS provides a lot of utilities to work with Text, Grid and Container, so it doesn't make sense to create a wrapper for those utilities.
