### ISSUE TITLE
[website] Toggle of Dark mode is effortless section is very slow

### ISSUE THREAD

**Issue by Joaovsa7** [nextui-org/nextui#177]
**Describe the bug**
Hey Guys.

It's not exactly a bug, but i realized that the toggle of `Dark mode is effortless.` is very slow. And i don't know if you guys realized this behavior so i'm opening this issue.

**Steps to reproduce**
1. Go to 'https://nextui.org/'
2. Scroll down to section 'Dark mode is effortless.'
3. Click on 'toggle to see the theme changing very slow'

**Expected behaviour**
Toggle of theme would be smooth.

**Screenshots**

https://user-images.githubusercontent.com/41493938/151548972-8f8428dd-593c-4a3a-aad5-fd71026f3373.mov

**Environment / Context**
- Desktop
- MacOS Big Sur
- Chrome 97
- Macbook

**Additional info**
I would like to help u guys to solve this problem!

ps. Congratulations for the website, it's very beautiful!

**Comment by mariusflorescu** [comment]
In addition to that, whenever the theme is set to `system` and the actual system preferred theme is dark, the switch will be incorrect (default to light).
