### ISSUE TITLE
[BUG] - NEXTUI Avatar Avatar Group Issue

### ISSUE THREAD

**Issue by ersanyakit** [nextui-org/nextui#1772]
### NextUI Version

2.1.10

### Describe the bug

When I dynamically update the 'name' value of the AVATAR object within the AVATAR Group, I encounter the error seen in the screenshots below.

### Steps to Reproduce the Bug or Issue

<AvatarGroup className={" z-10 select-none	"} size="sm" isBordered={true}>
                    <Avatar color="secondary" className={getColorFromIndex(selectedChip)} name={formatNumberWithK(betItem.totalBetAmount + betItem.betAmount)} />
                </AvatarGroup>

### Expected behavior

It must update the name value of avatar

### Screenshots or Videos

<img width="1012" alt="Ekran Resmi 2023-10-16 12 31 01" src="https://github.com/nextui-org/nextui/assets/10724463/47529dce-2f82-46fd-b1ba-f4fdc453b751">
<img width="992" alt="Ekran Resmi 2023-10-16 12 31 13" src="https://github.com/nextui-org/nextui/assets/10724463/971f44aa-8de2-4355-9147-259fd7a91f41">

### Operating System Version

MacOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @ersanyakit looks like your ` name={formatNumberWithK(betItem.totalBetAmount + betItem.betAmount)}` function is not returning a string, you can do this `name={String(formatNumberWithK(betItem.totalBetAmount + betItem.betAmount))}`

Or you can try updating NextUI to the latest version 2.1.13, I think we remove the `capitalize` function call.
