### ISSUE TITLE
[BUG] - Build type error

### ISSUE THREAD

**Issue by Ianduha13** [nextui-org/nextui#1788]
### NextUI Version

2.0.13

### Describe the bug

Hello everyone, here Ian, nice to meet everyone
I'm having a issue when i run yarn build in my project and I really dont know how to fix it:

./node_modules/@nextui-org/system-rsc/dist/extend-variants.d.ts:22:14
Type error: Type 'CP[K]' is not assignable to type 'string | number | symbol'.
  Type 'CP[keyof CP]' is not assignable to type 'string | number | symbol'.
    Type 'CP[string] | CP[number] | CP[symbol]' is not assignable to type 'string | number | symbol'.
      Type 'CP[string]' is not assignable to type 'string | number | symbol'.

  ```
20 | type SuggestedVariants<CP, S> = {
  21 |   [K in keyof CP]?: ValidateSubtype<CP[K], string> extends "true"
> 22 |   ? { [K2 in CP[K]]?: GetSuggestedValues<S> }
     |              ^
  23 |   : ValidateSubtype<CP[K], boolean> extends "true"
  24 |   ? {
  25 |     true?: GetSuggestedValues<S>;
```
  
I'm using the following dependencies:
 "@nextui-org/react": "2.1.13",
    "framer-motion": "^10.16.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    
I already commented each component that uses next ui inside my app and still having the same

### Steps to Reproduce the Bug or Issue

"dependencies": {
    "@nextui-org/react": "2.1.13",
    "framer-motion": "^10.16.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "@reduxjs/toolkit": "^1.9.6",
    "@types/node": "20.5.9",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.15",
    "axios": "^1.5.1",
    "eslint": "^8.49.0",
    "eslint-config-next": "^13.4.19",
    "eslint-plugin-unused-imports": "^3.0.0",
    "formik": "^2.4.4",
    "mongoose": "^7.5.2",
    "next": "13.4.19",
    "notistack": "^3.0.1",
    "postcss": "8.4.29",
    "qs": "^6.11.2",
    "react-icons": "^4.11.0",
    "react-redux": "^8.1.3",
    "swiper": "^10.2.0",
    "tailwind-variants": "^0.1.14",
    "tailwindcss": "3.3.3",
    "typescript": "5.2.2",
    "yup": "^1.2.0",
    "zod": "^3.22.2"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^6.7.0",
    "@typescript-eslint/parser": "^6.7.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-tailwindcss": "^3.13.0",
    "prettier": "^3.0.3",
    "prettier-plugin-tailwindcss": "^0.5.4"
  }

### Expected behavior

Is supposed to build without problems, in local works correctly

### Operating System Version

macOS

### Browser

Chrome

**Comment by ryo-manba** [comment]
Apologies for the delayed response. Since this issue has been open for a while, we will be closing it. Please try with the latest version, and if the same error occurs, feel free to open a new issue. Thank you for reporting.
