### ISSUE TITLE
[BUG] - strokeWidth doesn't do anything on Circular Progress

### ISSUE THREAD

**Issue by MaKTaiL** [nextui-org/nextui#1790]
### NextUI Version

2.1.13

### Describe the bug

The strokeWidth prop of the Circular Progress component doesn't work. It should increase the width of the circle but it doesn't do anything. A temporary workaround is to set:

``` javascript
<CircularProgress
  classNames={{
    indicator: "stroke-[5px]",
    track: "stroke-[5px]",
  }}
/>
```
But the circle goes out of bounds of the SVG and I can't seem to figure out a way to add a padding to fix it.

![image](https://github.com/nextui-org/nextui/assets/5403043/b32837dd-e3d4-49ad-bd36-b016b8744cbf)

### Steps to Reproduce the Bug or Issue

``` javascript
<CircularProgress
  value={50}
  strokeWidth={10}
  showValueLabel={"Testing"}
/>
```

### Expected behavior

strokeWidth prop should change the default width of the circle

### Operating System Version

Windows

### Browser

Chrome

**Comment by KhalidHassan218** [comment]
faced the same issue , no solution yet ? !
