### ISSUE TITLE
[Feature Request] Document way of optimizing

### ISSUE THREAD

**Issue by r34son** [nextui-org/nextui#1798]
### Is your feature request related to a problem? Please describe.

Yeah, by default all of dependencies of @nextui-org/react are in bundle

### Describe the solution you'd like

  experimental: {
    optimizePackageImports: ['@nextui-org/react'],
  },

### Describe alternatives you've considered

Note about that in your documentation

**Comment by rharkor** [comment]
Were do I put this ?

**Comment by r34son** [comment]
> Were do I put this ?

In 'next.config.js'
