### ISSUE TITLE
[BUG][Reproducible from the official website https://nextui.org/] - Infinite dark/light theme toggle loop

### ISSUE THREAD

**Issue by gustaveWPM** [nextui-org/nextui#1799]
### NextUI Version

NextUI Version used on https://nextui.org/

### Describe the bug

The theme toggles from dark to light and from light to dark, infinitely, without any interaction.

### Your Example Website or App

https://nextui.org/docs/components/navbar#navbar

### Steps to Reproduce the Bug or Issue

1. Go to: https://nextui.org/docs/components/navbar#navbar
2. Click frantically on the button to change theme,
3. Stop to click.

### Expected behavior

No infinite loop.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/118654172/39201266-bf90-4fe8-889c-f2b711fc934e

### Operating System Version

Linux

### Browser

Chrome

**Comment by wingkwong** [comment]
Closing - no longer reproducible
