### ISSUE TITLE
[BUG] - Unknow weird behavior using NextUI

### ISSUE THREAD

**Issue by Oolix** [nextui-org/nextui#1801]
### NextUI Version

2.1.13

### Describe the bug

Certain items in NextUI just aren't behaving as expected on my project. One example is inputs, this is what it appears for me on Firefox (I've tried it on Chrome and it's the same) 
![image](https://github.com/nextui-org/nextui/assets/128627893/9e4763b3-5217-4d5b-a31a-4a1453258460)
Other elements have other behavior, the Skeleton doesn't have it's 'shimmer' effect it doesn't display anything, the NavbarMenuTrigger doesn't display at all either. I've tried re-importing my files into a new clean project with no avail, I've tried other computers, I don't have any overwriting css files I only use Tailwind and I cannot figure it out... In the case of that picture it seems the Input background is being set by something, if I set background of input's to 'none' it appears fine but I want to fix the rest of my broken elements. Has anyone run into this issue or have an idea?

### Steps to Reproduce the Bug or Issue

1. Use an Input inside of a Modal
2. Hovering shows input has a different background

### Expected behavior

I expected the UI to mirror the examples in the documentation.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/128627893/1c91c19a-1b4b-4a9a-8ef3-ac7be5f1abff)

### Operating System Version

Windows 11

### Browser

Firefox

**Comment by alexbmills5** [comment]
All seems to be normal with that version

**Comment by jrgarciadev** [comment]
So maybe you have conflicting css classes in your project
