### ISSUE TITLE
[Feature Request] NextUI misses layout elements

### ISSUE THREAD

**Issue by jim-king-2000** [nextui-org/nextui#1803]
### Is your feature request related to a problem? Please describe.

We are full-stack web engineers who are afraid of css. We need out-of-the-box react ui library which could be customized with js properties.

We are trying NextUI and we find it miss layout element such as Box and Grid. Besides, we need to apply sematic color (bgcolor) and sematic length to `Box`. Such as:
`<Box background='content1' width='md' height='100%' />`
In the code snippet above, `content1` and `md` is intrinsic in NextUI. It is too hard for us to implement such a `Box` with css.

### Describe the solution you'd like

Implement `Box` and `Grid`.

### Describe alternatives you've considered

Or show us how to implement it with css.

**Comment by jrgarciadev** [comment]
Hey @jim-king-2000 NextUI's goal is to allow developers to use TailwindCSS as much as possible, we don't want to create a component for TailwindCSS utilities:

- Text (needless) - @see https://tailwindcss.com/docs/font-size
- Container (needless) - @see https://tailwindcss.com/docs/container
- Grid  (needless) - @see https://tailwindcss.com/docs/display#grid
