### ISSUE TITLE
[Feature Request] Where is the slider?

### ISSUE THREAD

**Issue by tayloraucoin** [nextui-org/nextui#1804]
### Is your feature request related to a problem? Please describe.

I am about to convert my application UI to your UI library as part of a design rebrand. 

I'm making sure that everything is compatible, and one component that is not listed in your documentation can be traced in your codebase. That is the `slider` component. 

I see in a PR that it can be found at `packages/components/slider/src/slider.tsx` https://github.com/nextui-org/nextui/pull/1693/files but is not found in your document components https://nextui.org/docs/components.

Are there other components that are available but not listed?

On a related note, I also notice that there are several components missing from the Figma file. Namely the `dropdown` and `select`. 

### Describe the solution you'd like

Could I please request that all forms of documentation and design file be updated promptly? 

### Describe alternatives you've considered

This would require digging into the codebase and then the designer having to go through a much more lengthly process to deliver the designed UI assets. 

### Screenshots or Videos

<img width="231" alt="Screen Shot 2023-10-24 at 9 14 27 AM" src="https://github.com/nextui-org/nextui/assets/10913613/816239e0-ba5f-4519-943f-c15b48968da0">
<img width="239" alt="Screen Shot 2023-10-24 at 9 14 35 AM" src="https://github.com/nextui-org/nextui/assets/10913613/c8cd4816-3e1b-4f92-aa85-3b96c65b3574">
<img width="1484" alt="Screen Shot 2023-10-24 at 9 14 41 AM" src="https://github.com/nextui-org/nextui/assets/10913613/a123ccdd-abaa-4763-b1a5-01c38765f03c">

**Comment by sayem314** [comment]
+1 for range slider

**Comment by timefordroids** [comment]
As we can see, it will be available in the next release
https://github.com/nextui-org/nextui/pull/1777

**Comment by tayloraucoin** [comment]
Wonderful, thank you!

**Comment by tayloraucoin** [comment]
@jrgarciadev I see that the assets are still missing from the Figma file though. Could we please get an update so that those can be available to the design team? 

Thank you for all your contributions!
