### ISSUE TITLE
[BUG] - ReactServerComponentsError with hello world example

### ISSUE THREAD

**Issue by ad-manish** [nextui-org/nextui#1807]
### NextUI Version

2.1.13

### Describe the bug

created a new project with all defaults by this command 

npx create-next-app -e https://github.com/nextui-org/next-app-template

after that i am using basic example 

```
import React from "react";
import {Avatar} from "@nextui-org/react";

export default function Home() {
  return (
    <div className="flex gap-3 items-center">
      <Avatar src="https://i.pravatar.cc/150?u=a042581f4e29026024d" />
      <Avatar name="Junior" />
      <Avatar src="https://i.pravatar.cc/150?u=a042581f4e29026704d" />
      <Avatar name="Jane" />
      <Avatar src="https://i.pravatar.cc/150?u=a04258114e29026702d" />
      <Avatar name="Joe" />
    </div>
  );
}
```
and I am getting this below error 

```
./app/page.tsx
ReactServerComponentsError:

You're importing a component that needs useEffect. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

   ,-[/Users/manishbansal/code/Nextjs /billing-system/algo-invoice-nextui/node_modules/@react-aria/i18n/dist/real-module.mjs:1:1]
 1 | import $iFADg$react, {useContext as $iFADg$useContext, useState as $iFADg$useState, useEffect as $iFADg$useEffect, useMemo as $iFADg$useMemo, useCallback as $iFADg$useCallback} from "react";
   :                                                                                     ^^^^^^^^^
 2 | import {useIsSSR as $iFADg$useIsSSR} from "@react-aria/ssr";
 3 | import {LocalizedStringDictionary as $iFADg$LocalizedStringDictionary, LocalizedStringFormatter as $iFADg$LocalizedStringFormatter} from "@internationalized/string";
 4 | import {DateFormatter as $iFADg$DateFormatter} from "@internationalized/date";
   `----

The error was caused by importing '@nextui-org/react/dist/index.mjs' in './app/page.tsx'.

Maybe one of these should be marked as a client entry with "use client":
  ./app/page.tsx
```

### Steps to Reproduce the Bug or Issue

1. create a new app using template 
2. go to Components from the documentation page. 
3. copy the fist component code 
4. paste in the home page.tsx 
5. rename `app` to `home` in the just the method name 
6. npm run dev 

its is giving the weird error, at first its said : 
Module not found: Can't resolve '@nextui-org/react'

then i run this command to fix this issue 
npm i @nextui-org/react framer-motion

so basic compilation error gone, but i am running the app using  npm run dev, it is giving error.

### Expected behavior

it should display dummy avatar component on the home page

### Operating System Version

MacOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @ad-manish when using Next.js 13 with App Router directory you need to import the components from their packages 

For instance in this case you need to import the avatar as follows:

```ts
import {Avatar, AvatarGroup} from "@nextui-org/avatar";
```

![CleanShot 2023-10-26 at 09 29 19](https://github.com/nextui-org/nextui/assets/30373425/3d3e702b-795b-4423-b855-f6ae4da8640a)

Individual packages already includes the `use client;` directive, the main package `@nextui-org/react` doesn't include it because not all components are client components, we also have server components as the [Divider](https://nextui.org/docs/components/divider), [Spacer](https://nextui.org/docs/components/spacer), [Kbd](https://nextui.org/docs/components/kbd) etc..
