### ISSUE TITLE
[BUG] - DropDown Change BackGroundColor on hover

### ISSUE THREAD

**Issue by koala819** [nextui-org/nextui#1808]
### NextUI Version

2.1.13

### Describe the bug

I don't know if it's a bug or if it's me using NextUI wrong.
I would have liked to change the background color on hover in a dropDown, but I understood that I had to use the mandatory colors (primary/secondary/danger/...). I didn't change these colors because I used them differently.
So I searched how to create new colors, but I was unsuccessful.
But with one mistake, I succeeded.
Maybe others need this hack, which I share below.
Maybe someone can give me the correct way to achieve the same result

thematic.js
```js
import {
  FaChessBoard,
  FaRobot,
} from "react-icons/fa";

export const thematics = [
  {
    name: "themathicName01",
    description: "description01",
    path: "#",
    icon: <FaChessBoard size={20} />,
  },
  {
    name: "themathicName02",
    description: "description02",
    path: "#",
    icon: <FaRobot size={20} />,
  },
 ```

colorVariants.ts
```js
export const colorVariants: { [key: string]: string } = {
  "themathicName01": "hover:bg-[#C7B4FF]",
  "themathicName02": "hover:bg-[#D1E4E2]",
};
 ```

Navbar.tsx
```js
import { thematics } from "@/src/lib/thematics";
import { colorVariants } from "@/src/lib/colorVariants";

export function Navbar() {
return (
...
  <DropdownMenu aria-label='Item_3' items={thematics}>
                {(thematic: any) => {
                  return (
                    <DropdownItem
                      key={thematic.name}
                      color={"undefined" as any}
                      variant='shadow'
                      className={`${
                        colorVariants[thematic.name]
                      } p-4 space-x-4`}
                      description={thematic.description}
                      startContent={thematic.icon}
                      onClick={() => router.push(thematic.path || "#")}
                    >
                      {thematic.name}
                    </DropdownItem>
                  );
                }}
              </DropdownMenu>
...
)}
```

### Steps to Reproduce the Bug or Issue

write 
```js
color={"undefined" as any}
```
to remove the check error by TS and use your custom color
```
className={`${colorVariants[thematic.name]} p-4 space-x-4`}
```

### Expected behavior

For me it's an hack to use custom colors on hover with dropDpwn

### Screenshots or Videos

![2023-10-25 22_48_48-Window](https://github.com/nextui-org/nextui/assets/70317658/4d381171-6b7f-4f5e-bcd2-653b0f646c58)
![2023-10-25 22_48_32-Window](https://github.com/nextui-org/nextui/assets/70317658/673c1083-48ca-46d9-b3b4-86b3f720adbf)

### Operating System Version

Windows

### Browser

Firefox

**Comment by jrgarciadev** [comment]
Hey @koala819 there's an example in the documentation that covers this scenario: https://nextui.org/docs/components/dropdown#customizing-the-dropdown-items-style
