### ISSUE TITLE
[BUG] - Layout/Container

### ISSUE THREAD

**Issue by 200sOnly** [nextui-org/nextui#1815]
### NextUI Version

latest

### Describe the bug

The code sandbox doesn't work

### Steps to Reproduce the Bug or Issue

GoTo: https://v1.nextui.org/docs/layout/container
Click on Sandbox on any example

### Expected behavior

The code sandbox should display the expected result

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
NextUI v1 will no longer receive updates, sorry
