### ISSUE TITLE
[BUG] - Select

### ISSUE THREAD

**Issue by afgomezv** [nextui-org/nextui#1816]
### NextUI Version

2.0.10

### Describe the bug

El componente no renderiza siempre sale este error en consola: 
Error: Unknown element <[object Object]> in collection.

siempre realizo la importación del componente principal o individual
import {Select, SelectSection, SelectItem} from "@nextui-org/react";
import {Select, SelectSection, SelectItem} from "@nextui-org/select";

Cualquiera de las dos opciones anteriores muestra el mismo error.
Tambien instalado el select invidualmente, sigo con el mismo error

### Your Example Website or App

https://github.com/afgomezv/gestion-precontractual.git

### Steps to Reproduce the Bug or Issue

Unhandled Runtime Error
Error: Unknown element <[object Object]> in collection.

### Expected behavior

que el componente trabaje normalmente sin errores

### Screenshots or Videos

import { title } from "@/components/primitives";
//import { Select, SelectSection, SelectItem } from "@nextui-org/";
import { Select, SelectSection, SelectItem } from "@nextui-org/select";

export default function AboutPage() {
  return (
    <div>
      <h1 className={title()}>About</h1>
      <Select aria-label="Favorite Animal" label="Favorite Animal">
        <SelectItem key="penguin" value="penguin">
          Penguin
        </SelectItem>
        <SelectItem key="zebra" value="zebra">
          Zebra
        </SelectItem>
        <SelectItem key="shark" value="shark">
          Shark
        </SelectItem>
      </Select>
    </div>
  );
}

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by stephen-blueamaryllisconsulting** [comment]
¿Puedes mostrar el código para el componente "Select"?

**Comment by afgomezv** [comment]
Ya corregi el error
