### ISSUE TITLE
[BUG] - Unexpected Application Error! type.getCollectionNode is not a function.

### ISSUE THREAD

**Issue by joyanedel** [nextui-org/nextui#1818]
### NextUI Version

2.1.10

### Describe the bug

When using React, we separate the row components apart of the table itself in another component and then just render the aforementioned component, React just popped "Unexpected Application Error!
type.getCollectionNode is not a function"

It happens in Chrome and Safari, I haven't tested in another browser but probably happen the same

This code does not work:
```
<Table className="m-o p-0">
  <TableHeader>
    <TableColumn children="Date" />
    <TableColumn children="Assignments" />
    <TableColumn children="Total Cost" />
    <TableColumn children="Last Sent" />
    <TableColumn children="View" />
  </TableHeader>
  <TableBody>
    {
      props.runs.map(run => <RunRow key={run.id} week={props.week} run={run} />)
    }
  </TableBody>
</Table>

const RunRow = (props: RunRowProps) => {
  ...

  return (
    <TableRow>
      <TableCell children={dateText} />
      <TableCell children={assignmentText} className="text-right" />
      <TableCell children={totalCostText} className="text-right"/>
      <TableCell children={lastSentText} />
      <TableCell>
        <Link
          color="primary"
          children="View"
          href=...
        />
      </TableCell>
    </TableRow>
  )
}
```

But the following code does work instead:
```
<table className="m-o p-0">
  <tr>
    <th children="Date" />
    <th children="Assignments" />
    <th children="Total Cost" />
    <th children="Last Sent" />
    <th children="View" />
  </tr>
  <tbody>
    {
      props.runs.map(run => <RunRow key={run.id} week={props.week} run={run} />)
    }
  </tbody>
</table>

const RunRow = (props: RunRowProps) => {
  ...
  return (
    <tr>
      <td children={dateText} />
      <td children={assignmentText} className="text-right" />
      <td children={totalCostText} className="text-right"/>
      <td children={lastSentText} />
      <td>
        <Link
          color="primary"
          children="View"
          href=...
        />
      </td>
    </tr>
  )
}
```

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-bvjw8c?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Create a component that render a Table with of their subcomponents
2. Create component that render only row information using TableRow
3. Insert created component inside Table component body

### Expected behavior

As a user, I expected standard table rendering behavior but I am seeing React Exception "Unexpected Application Error! type.getCollectionNode is not a function."

### Screenshots or Videos

<img width="1120" alt="image" src="https://github.com/nextui-org/nextui/assets/61957946/46c9b113-0243-480e-bc55-763b59cc6018">

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @joyanedel this is a [react-aria](https://react-spectrum.adobe.com/react-stately/collections.html) limitation, all collection-based components need to be specific components in order to build the entire collection, in this case, you can only use the `TableRow` as `TableBody` children.

You can use dynamic tables if you don't want to repeat `TableRow` all the time
https://nextui.org/docs/components/table#dynamic
