### ISSUE TITLE
[BUG] - The scrollbar in the Modal with mobile view is not working

### ISSUE THREAD

**Issue by catmengli** [nextui-org/nextui#1820]
### NextUI Version

2.1.13

### Describe the bug

If an inside scrollbar is enabled in ModalBody, something weird occurs: the top area of ModalBody is not working while the bottom area is fine. When scrolling in the top area, the focus isn't even on the modal but on the page below, and the page below scrolls.

### Steps to Reproduce the Bug or Issue

In [Modal docs](https://nextui.org/docs/components/modal), the bug is just there. Use the Overflow scroll preview, open it in mobile view, try to scroll on top area of modalbody content. The modal content won't scroll but the doc page scrolls

### Expected behavior

Scroll normally on modal content

### Screenshots or Videos

[Screen Recording - Made with FlexClip.webm](https://github.com/nextui-org/nextui/assets/149179359/27e20deb-9a89-4f2c-b9c6-fda68091ead2)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
Closing - no longer reproducible
