### ISSUE TITLE
[Feature Request] Select Searchable

### ISSUE THREAD

**Issue by WilliamBRDrive** [nextui-org/nextui#1821]
### Is your feature request related to a problem? Please describe.

It's a problem when I have a select with several options to choose from

### Describe the solution you'd like

When, for example, using a select box that lists 100 services, and the user has to select one of them

### Describe alternatives you've considered

Having the ability in the Select menu to search for a specific item you want, instead of scrolling to find it

### Screenshots or Videos

https://mantine.dev/core/select/#searchable

**Comment by toxsick** [comment]
Duplicate of #1586

**Comment by jrgarciadev** [comment]
Use the https://nextui.org/docs/components/autocomplete component.
