### ISSUE TITLE
[Dropdowns][Dropdown Menu] Expose a function to programmatically control the opened state of a DropdownMenu

### ISSUE THREAD

**Issue by gustaveWPM** [nextui-org/nextui#1824]
### Is your feature request related to a problem? Please describe.

https://github.com/nextui-org/nextui/discussions/1811

### Describe the solution you'd like

kapa.ai on the NextUI Discord server said:

> Unfortunately, based on the information provided in the extracts, there isn't a specific method or function exposed by NextUI to programmatically control the visibility of a DropdownMenu without unmounting it.

### Describe alternatives you've considered

Force a remount with a `key` attribute hack.

**Comment by jrgarciadev** [comment]
@gustaveWPM check this comment: https://github.com/nextui-org/nextui/discussions/1811#discussioncomment-7411340
