### ISSUE TITLE
[Dropdown][Single Selection] Type the single selection

### ISSUE THREAD

**Issue by gustaveWPM** [nextui-org/nextui#1827]
### Is your feature request related to a problem? Please describe.

Hello,
In the documentation of the "Single Selection" Dropdowns: https://nextui.org/docs/components/dropdown#single-selection

The example says:

```tsx
import React from "react";
import {Dropdown, DropdownTrigger, DropdownMenu, DropdownItem, Button} from "@nextui-org/react";

export default function App() {
  const [selectedKeys, setSelectedKeys] = React.useState(new Set(["text"]));

  const selectedValue = React.useMemo(
    () => Array.from(selectedKeys).join(", ").replaceAll("_", " "),
    [selectedKeys]
  );

  return (
    <Dropdown>
      <DropdownTrigger>
        <Button 
          variant="bordered" 
          className="capitalize"
        >
          {selectedValue}
        </Button>
      </DropdownTrigger>
      <DropdownMenu 
        aria-label="Multiple selection example"
        variant="flat"
        closeOnSelect={false}
        disallowEmptySelection
        selectionMode="multiple"
        selectedKeys={selectedKeys}
        onSelectionChange={setSelectedKeys}
      >
        <DropdownItem key="text">Text</DropdownItem>
        <DropdownItem key="number">Number</DropdownItem>
        <DropdownItem key="date">Date</DropdownItem>
        <DropdownItem key="single_date">Single Date</DropdownItem>
        <DropdownItem key="iteration">Iteration</DropdownItem>
      </DropdownMenu>
    </Dropdown>
  );
}
```

But, in fact, copy/pasting this example in my IDE throws an error:

> Type 'Dispatch<SetStateAction<Set<string>>>' is not assignable to type '(keys: Selection) => any'.
  Types of parameters 'value' and 'keys' are incompatible.
    Type 'Selection' is not assignable to type 'SetStateAction<Set<string>>'.
      Type 'string' is not assignable to type 'SetStateAction<Set<string>>'.ts(2322)

In fact, I need some minor changes to not have type errors:

```tsx
  const [selectedKeys, setSelectedKeys] = React.useState<Selection>(new Set<string>(['text']));
```

But, this is still very annoying.
Why should I work with a collection of items for "selectedKeys", as it should be a single value in this context?

### Describe the solution you'd like

I'd like to have a plain "selectedKey", only representing the selected item, without to have to handle a list of 0 or 1 element.

### Describe alternatives you've considered

/

**Comment by jrgarciadev** [comment]
Hey @gustaveWPM it is quite complex to match both types "single" and "multiple", that's why we decided to only support the "multiple" props, for instance, the `selectedKeys` instead of `selectedKey`.  However, the documentation example is maybe too complex, here's a simple one to achieve the same results:

https://codesandbox.io/p/sandbox/vibrant-babycat-4w8g8p?file=%2FApp.tsx%3A1%2C1&utm_medium=sandpack

**Comment by gustaveWPM** [comment]
> Hey @gustaveWPM it is quite complex to match both types "single" and "multiple", that's why we decided to only support the "multiple" props, for instance, the `selectedKeys` instead of `selectedKey`. However, the documentation example is maybe too complex, here's a simpler way to achieve the same results:
> 
> https://codesandbox.io/p/sandbox/vibrant-babycat-4w8g8p?file=%2FApp.tsx%3A1%2C1&utm_medium=sandpack

Hello,
Thank you for your answer.

I find this alternate way to write the same component way more elegant!

I think it would be a good idea to document this.

**Comment by Kristoffer-Martinsen** [comment]
I have the same problem but the sandbox.io isn't available anymore. I don't know if you remember how you solved this problem?

**Comment by jack828** [comment]
I had the same problem, I went with this in the end:
```typescript

export const getSelectionValue = (selection: Selection) => {
  if (typeof selection === 'string') {
    return selection
  }
  if (selection instanceof Set) {
    return selection.keys().toArray()[0]
  }
}

const Component = () => {

  const [inputYear, setInputYear] = useState<Selection>(new Set([]))
  const addEntry = () => {
    if (!getSelectionValue(inputMonth) || !getSelectionValue(inputYear)) return
	... other stuff...
  	}
	return (
		<>
          <div className="flex items-center">
            <Select
              className="max-w-xs"
              label="Year"
              placeholder="-- Select Year --"
              selectedKeys={inputYear}
              onSelectionChange={setInputYear}
            >
              {years.map((year) => (
                <SelectItem key={year.key}>{year.label}</SelectItem>
              ))}
            </Select>
          </div>
            <Button
              color="primary"
              onPress={addEntry}
              className="w-full"
              isDisabled={isDisabled}
            >
              Add Entry
            </Button>
		</>
	)
}
```
