### ISSUE TITLE
[BUG] - DropdownMenu Cannot Accept React.Fragment

### ISSUE THREAD

**Issue by Innders** [nextui-org/nextui#1828]
### NextUI Version

2.1.13

### Describe the bug

Placing a `<React.Fragment>` or `<></>` inside of `<DropdownMenu>` causes error.

```javascript
<Dropdown placement="top-start">
  <DropdownTrigger>
    <Button
      variant="light"
      endContent={<Icon icon="expand_all" className={styles.icon} />}
    >
      Select Organisation
    </Button>
  </DropdownTrigger>
  <DropdownMenu
    onAction={(name) =>  router.push(`/org/${name}`)}
  >
    <React.Fragment>
      {organisations.map((org) => (
        <DropdownItem key={org.name}>
          {org.name}
        </DropdownItem>
      ))}
      <DropdownItem key="new">Create new Organisation</DropdownItem>
    </React.Fragment>
  </DropdownMenu>
</Dropdown>
```

Error: `TypeError: Cannot convert a Symbol value to a string`.

Workaround1: Remove fragment and ignore type error `Type 'Element[]' is not assignable to type 'CollectionElement<object>'`

Workaround2: Move all Dropdown Items outside of return and instead return array of Dropdown Items like `<DropdownMenu>{dropdownItems}</DropdownMenu>`

### Steps to Reproduce the Bug or Issue

```javascript
<DropdownMenu>
  <React.Fragment>
    <DropdownItem>Item 1</DropdownItem>
    <DropdownItem>Item 2</DropdownItem>
    <DropdownItem>Item 3</DropdownItem>
  </React.Fragment>
</DropdownMenu>
```

or

```javascript
<DropdownMenu>
  <>
    <DropdownItem>Item 1</DropdownItem>
    <DropdownItem>Item 2</DropdownItem>
    <DropdownItem>Item 3</DropdownItem>
  </>
</DropdownMenu>
```

### Expected behavior

Ignore the fragment and render the items as if it wasn't there.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/49156310/6194b31b-4aee-4327-9f9d-cacfce2efced)

![image](https://github.com/nextui-org/nextui/assets/49156310/499328a1-38fa-4aec-b3f7-708175609997)

### Operating System Version

MacOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Innders DropdownMenu is a collection-based component https://react-spectrum.adobe.com/react-stately/collections.html, which means that it needs to have specific components as children to work properly, you cannot use other components as children rather than DropdownItem or DropdownSection, in addition I don't see any advantage in using the fragment, just remove it 👍🏻

**Comment by Innders** [comment]
Thanks for the reply and explanation @jrgarciadev .

Still, when you remove the fragment you get a type error 🤔

```javascript
const items = [1,2,3]

return (
  <Dropdown>
      <DropdownTrigger>Trigger</DropdownTrigger>
      <DropdownMenu>
          {items.map((item) => (
              <DropdownItem key={item}>{item}</DropdownItem>
          ))}
          <DropdownItem key="extra">Extra Item</DropdownItem>
      </DropdownMenu>
  </Dropdown>
)
  ```
  
  
![image](https://github.com/nextui-org/nextui/assets/49156310/f2222f36-0bf3-4e04-a479-2518babb8aa5)

**Comment by jrgarciadev** [comment]
Hey @Innders you should use the dynamic rendering for dynamic items:

```tsx
 const items = [
    {
      key: "new",
      label: "New file",
    },
    {
      key: "copy",
      label: "Copy link",
    },
    {
      key: "edit",
      label: "Edit file",
    },
    {
      key: "delete",
      label: "Delete file",
    },
    {
      key: "extra",
      label: "Extra item",
    },
  ];

  return (
    <Dropdown>
      <DropdownTrigger>
        <Button variant="bordered">Open Menu</Button>
      </DropdownTrigger>
      <DropdownMenu items={items}>
        {(item) => <DropdownItem key={item.key}>{item.label}</DropdownItem>}
      </DropdownMenu>
    </Dropdown>
  );
  ```
  
  https://nextui.org/docs/components/dropdown#dynamic-items
