### ISSUE TITLE
yarn audit shows 30 vulnerabilities

### ISSUE THREAD

**Issue by Dhananjay-JSR** [nextui-org/nextui#183]
**Steps to reproduce**
1. Go to root directory of project in main branch
2. run **yarn audit**
3. Scroll down to end

**Screenshots**
![vulner](https://user-images.githubusercontent.com/47073516/151650608-0b15abb0-157d-4451-ae6d-e4e7d40ff304.PNG)

**Environment / Context**
- NextUI Source Package

**Additional info**
Out of 30 Vulnerability 
    _3 Moderate_ , _4 Critical_ Vulnerability are direct dependency of **@nextui-org/docs**  while few are indirect dependency

**Expected behaviour**
_**Should**_ Expect 0 Vulnerability Package

**Comment by JJTech0130** [comment]
See https://overreacted.io/npm-audit-broken-by-design/
Yarn uses the same audit system as npm.
