### ISSUE TITLE
[BUG] - Tabs not changing with radius

### ISSUE THREAD

**Issue by jeffsummer08** [nextui-org/nextui#1834]
### NextUI Version

2.1.13

### Describe the bug

I'm changing the radius of the Tabs component to "full", but the changes are not showing on the end product. Furthermore, even without specifying the radius of the component, the Tabs component is still defaulted to "rounded-none".

### Steps to Reproduce the Bug or Issue

1. Create a Tabs component and set radius to full

### Expected behavior

I expected the tabs to be extremely round, but instead they are completely square.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/86799981/95959f64-ddd0-438a-ad39-afc7f6b76003)

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @jeffsummer08 it works fine for me:
https://codesandbox.io/p/sandbox/quiet-bash-ynnz7j?file=%2FApp.jsx%3A18%2C47&utm_medium=sandpack
