### ISSUE TITLE
[BUG] - Input and Select have different label colors

### ISSUE THREAD

**Issue by Innders** [nextui-org/nextui#1837]
### NextUI Version

2.1.13

### Describe the bug

By default the components `Input` and `Select` have different text colors.

Input: `foreground-600`
Select: `foreground-500`

I noticed this when using both components next to another in a form, which would be a very common use case.

Further to that I had trouble easily changing the Select <label> color and needed to use CSS modules to do it.

### Steps to Reproduce the Bug or Issue

Use default `Input` and default `Select` components.

### Expected behavior

Use a consistent color shade across both components.

I would personally suggest `foreground-600`.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/49156310/7fab5174-8c8e-476e-9bbb-909098ab1c01)

### Operating System Version

MacOS

### Browser

Chrome

**Comment by shubhalgupta** [comment]
@Innders which files to change? Also, please assign this issue to me!

**Comment by jrgarciadev** [comment]
Hey this should be fixed in the next release v2.2.0 

https://github.com/nextui-org/nextui/pull/1797
