### ISSUE TITLE
[Feature Request] improve user experience with select component

### ISSUE THREAD

**Issue by code-dev-pro** [nextui-org/nextui#1847]
### Is your feature request related to a problem? Please describe.

Currently, when we have multiple select components, if we click on another closed select, this one does not open and the other closes. you must therefore click twice on a closed select so that it opens when one is already open.

### Describe the solution you'd like

I would like that when we have multiple select components, if we click on another closed select, this one opens and the other closes.

### Describe alternatives you've considered

It will great having same experience when having a select and input or button.

### Screenshots or Videos

![IMG_4951](https://github.com/nextui-org/nextui/assets/254780/8d3e9ca4-3058-437e-add7-5120ae5bc481)

**Comment by jrgarciadev** [comment]
Duplicated:


https://github.com/nextui-org/nextui/issues/1287

**Comment by code-dev-pro** [comment]
It's not the same component. I speak about select not Dropdown.
