### ISSUE TITLE
[BUG] - Progress components with the isStriped attribute have the color attribute disabled, and are always gray no matter what color is set.

### ISSUE THREAD

**Issue by ldystudio** [nextui-org/nextui#1879]
### NextUI Version

2.2.2

## for example：
```
import React from "react";
import { Progress } from "@nextui-org/react";

export default function App() {
  return (
    <Progress
      isStriped
      aria-label="Loading..."
      color="secondary"
      value={60}
      className="max-w-md"
    />
  );
}
```
Set the color attribute to secondary, but display in gray

### Steps to Reproduce the Bug or Issue

Set the color attribute to secondary, but display in gray

### Expected behavior

wrong color

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/109018032/851df898-3909-41cd-967a-34ac4aa6ea8f)

### Operating System Version

Windows

### Browser

Chrome

**Comment by ldystudio** [comment]
Fixed in version 2.2.9

**Comment by luganitoo** [comment]
The issue is back, apparently

**Comment by udriss** [comment]
It's even not visible at all for me!

Note visible :
`<Progress
          isStriped={true}
          value={uploadProgress} />`
          
Visible :
`<Progress
          value={uploadProgress} />`
