### ISSUE TITLE
[BUG] - Breadcrumb issues

### ISSUE THREAD

**Issue by acromondx** [nextui-org/nextui#1883]
### NextUI Version

2.2.2

### Describe the bug

Whenever I try to use the breadcrumb component in my code, I get this error below

`./node_modules/.pnpm/@nextui-org+breadcrumbs@2.0.2_@nextui-org+system@2.0.7_@nextui-org+theme@2.1.6_react-dom@18.2.0_react@18.2.0/node_modules/@nextui-org/breadcrumbs/dist/chunk-QYRQCSZA.mjs
Attempted import error: 'breadcrumbs' is not exported from '@nextui-org/theme' (imported as 'breadcrumbs').`

### Steps to Reproduce the Bug or Issue

I used Nextjs starter code (pnpm create next-app -e https://github.com/nextui-org/next-app-template) and installed the breadcrumb component (@nextui-org/breadcrumbs).  I used the same code in the [documentation](https://nextui.org/docs/components/breadcrumbs).

### Expected behavior

It is supposed to work as shown in the documentation.

### Screenshots or Videos

![Screenshot_20231105_203619](https://github.com/nextui-org/nextui/assets/50566307/584a404d-2634-4c6c-a641-10c591bfb0b0)

### Operating System Version

Linux (Kubuntu)

### Browser

Edge

**Comment by jrgarciadev** [comment]
https://codesandbox.io/p/sandbox/ancient-star-7c4yh6?file=%2FApp.jsx%3A7%2C44&utm_medium=sandpack
