### ISSUE TITLE
[BUG] -React does not recognize the `hideSelectedIcon`

### ISSUE THREAD

**Issue by dt50** [nextui-org/nextui#1888]
### NextUI Version

2.3.4

### Describe the bug

When use DropdownSection in DropdownMenu, every time console in browser send warning about  `Warning: React does not recognize the 'hideSelectedIcon' prop on a DOM element`

### Steps to Reproduce the Bug or Issue

1. Create Dropdown (with trigger and menu)
2. Create DropdownSection with DropdownSection's
3. Click in browser by this Dropdown
4. Open console in browser

### Expected behavior

As a programmer, I wouldn't to see that

### Screenshots or Videos

![CleanShot 2023-11-06 at 11 26 39@2x](https://github.com/nextui-org/nextui/assets/32037208/b36a1878-cd8b-4eae-bb39-737f8c868c3a)

### Operating System Version

mac os

### Browser

Firefox

**Comment by ahmedsmae** [comment]
Appears when using sections
ListboxSection
DropdownSection
