### ISSUE TITLE
[Create React App] Rendering White Page 

### ISSUE THREAD

**Issue by Dhananjay-JSR** [nextui-org/nextui#189]
The Issue begins with react-scripts v5 breaking NextUI Render Components 

Temporal Solution :- Downgrade react-script to v4 from the package.json

**Comment by Samsonroyal** [comment]
@Dhananjay-JSR I've experienced something similar with a Create React App; the app executes successfully however a white screen is rendered.
what solutions have you tried to implement?

**Comment by Dhananjay-JSR** [comment]
> @Dhananjay-JSR I've experienced something similar with a Create React App; the app executes successfully however a white screen is rendered. what solutions have you tried to implement?

The Only temporal solution to this is to manually change react-script version to 4.0.0 in package.json file in your root directory and then execute command **npm install**

**Comment by Samsonroyal** [comment]
Thanks let me try that. 🤝

**Comment by aryamitra06** [comment]
I tried after renaming "react-scripts": "4.0.0" in package.json and executed npm install and it worked!! Thanks @Dhananjay-JSR 😁

**Comment by notmedia** [comment]
@jrgarciadev Hi! Do you have any news?

**Comment by Keyruu** [comment]
Hello, this is a much needed fix. TailwindCSS doesn't work with react-scripts@4 and I want use NextUI with Tailwind. I currently can't.

**Comment by jrgarciadev** [comment]
Hey guys, we are doing our best to fix this as soon as possible, thanks for the patience 🙏🏻

**Comment by kaichaosun** [comment]
It's still broken at the main branch with error:
```shell
```

**Comment by nalinbhardwaj** [comment]
I'm having the same issue as @kaichaosun with version `1.0.6-beta.5`

**Comment by lightify97** [comment]
I'm using `1.0.6-beta.5` with tailwind and having the same issue. However if you exclude @tailwind/base from your build it works fine.

**Comment by MobileAppVault** [comment]
Any update on this?

**Comment by jrgarciadev** [comment]
Hey guys 🙌🏼, could you try this again using the latest version (v10) and react 17?
