### ISSUE TITLE
[BUG] - Breadcrumbs needs 'use client' directive in Next.js

### ISSUE THREAD

**Issue by aixegorri** [nextui-org/nextui#1890]
### NextUI Version

2.2.3

### Describe the bug

When using the component in a Next.js 14 project, it cannot be imported directly, the 'use client' directive must be included, otherwise the component does not render correctly.

### Steps to Reproduce the Bug or Issue

Import the Breadcrumbs and BreadcrumbItem components into a Next.js project.

### Expected behavior

Import the component directly without having to add the 'use client' directive.

### Operating System Version

macOS Ventura 13.5.2

### Browser

Chrome

**Comment by timomedia** [comment]
@aixegorri 
I think this is not a bug but the mechanism of Nextjs version 13 and above. Nextjs >= 13 clearly distinguishes between server-side processing before reaching the user or user-side processing. And ui components like this will be displayed on the user side, so using "use client" is mandatory.
