### ISSUE TITLE
[BUG] - Autocomplete 'endContent' not working!

### ISSUE THREAD

**Issue by sbc640964** [nextui-org/nextui#1893]
### NextUI Version

2.2.4

### Describe the bug

```jsx
<Autocomplete 
   ...
  variant="bordered"
  startContent={<PlusIcon className="h-5 w-5" />}
  endContent={<PlusIcon className="h-5 w-5" />}
>
...
</Autocomplete>
```
result:
![image](https://github.com/nextui-org/nextui/assets/46646044/32389237-0651-4e98-96b2-e3eddb1c3a2c)

### Steps to Reproduce the Bug or Issue

Insert a component in the endContent of Autocomplete and you will see that it does not appear...

### Expected behavior

The endContent element should appear like this as documented:
https://nextui.org/docs/components/autocomplete#start-content

Maybe there is a mistake in the documentation... because the title does refer only to the startContent and in the documentation itself there is also a reference to the endContent

### Operating System Version

win10

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @sbc640964 do you want to add a custom element at the end of the input or do you want to change the selector icon?

**Comment by sbc640964** [comment]
@jrgarciadev Thanks for the quick response.

 I want to add a custom element at the end of the input

**Comment by jrgarciadev** [comment]
Ok I'll try to fix this soon, thanks for reporting it

**Comment by jrgarciadev** [comment]
@sbc640964 

Autocomplete with `endContent`

![CleanShot 2023-11-06 at 15 43 00](https://github.com/nextui-org/nextui/assets/30373425/ec5c5071-e7a2-4d26-bd67-fe5485d90d8f)

Something to take into account is that you will not be able to use the clear button when having an end content.
