### ISSUE TITLE
[BUG] - Attempted import error: 'autocomplete'

### ISSUE THREAD

**Issue by sayem314** [nextui-org/nextui#1900]
### NextUI Version

2.2.4

### Describe the bug

![image](https://github.com/nextui-org/nextui/assets/14138401/fa9133bb-eb49-4d48-8e62-226570b48957)

### Steps to Reproduce the Bug or Issue

Nothing changed except upgrading to nextui

![image](https://github.com/nextui-org/nextui/assets/14138401/08d2c954-d7f9-40d9-ab5c-7892df0cb8d2)
 

### Expected behavior

Website should load without issues

### Screenshots or Videos

included above

### Operating System Version

Manjaro Linux

### Browser

Chrome

**Comment by sayem314** [comment]
Downgraded to `@nextui-org/react@2.2.3` and issue is gone

**Comment by jrgarciadev** [comment]
It works fine on codesandbox with the latest version `2.2.4`

https://codesandbox.io/p/sandbox/h5jpqz?file=%2FApp.jsx%3A5%2C32&utm_medium=sandpack

I suggest to delete the `node_modules` + `lock` file and reinstall the v2.2.4

**Comment by sayem314** [comment]
Well, I tried everything earlier except removing the lock file from Bun. And I don't directly use any Autocomplete components. But after removing the lock file and re-installing it now, it works! Thanks!
