### ISSUE TITLE
[BUG] - When navigating with keys on autocomplete component with sections it does not highlight the currently selected item

### ISSUE THREAD

**Issue by mythicalbro** [nextui-org/nextui#1908]
### NextUI Version

2.2.5

### Describe the bug

When navigating with keys on autocomplete component with sections it does not highlight the currently selected item.
Works fine without sections. 
The issue can be reproduced on the docs.

### Your Example Website or App

https://nextui.org/docs/components/autocomplete#with-sections

### Steps to Reproduce the Bug or Issue

Try to navigate autocomplete with sections on the docs.

### Expected behavior

I expected the currently selected item to be highlighted like on autocomplete without sections.

### Operating System Version

Windows

### Browser

Edge

**Comment by wingkwong** [comment]
No longer reproducible (tested in 2.3.5).
