### ISSUE TITLE
[BUG] - The isMultiline causes the label to be on the side - select component

### ISSUE THREAD

**Issue by sbc640964** [nextui-org/nextui#1910]
### NextUI Version

2.2.5

### Describe the bug

 The isMultiline causes the label to be on the side - select component

```jsx
<Select
  labelPlacement="outside"
>
...
</Select>
```

result:
![image](https://github.com/nextui-org/nextui/assets/46646044/d6f66356-33c8-4e6e-9863-5d254429e756)

### Steps to Reproduce the Bug or Issue

Create a selection element
Add **labelPlacement** to "outside"
Add **isMultiline**
You will see that the label is pushed to the side

### Expected behavior

As it was until the current version, the label should remain outside according to my personal setting in labelPlacement

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/46646044/4db6edb8-8c4a-442f-9e31-3f4446871f89)

![image](https://github.com/nextui-org/nextui/assets/46646044/a3bcba13-3002-4fe2-9b11-8295fb9a8bf9)

### Operating System Version

win10

### Browser

Chrome

**Comment by GnussonNet** [comment]
+1
