### ISSUE TITLE
[BUG] - TailWind CSS font-size class does not work

### ISSUE THREAD

**Issue by jim-king-2000** [nextui-org/nextui#1913]
### NextUI Version

2.2.5

### Describe the bug

`<p className='text-8xl'>` renders the font-size of 18px. It should be 96px. From the samples, I saw the class name is `text-tiny`, `text-large`. But what is the class name for larger font size?

### Steps to Reproduce the Bug or Issue

1. render `<p className='text-8xl'>` with nextui v2.
2. see the font size.

### Expected behavior

Tailwind css class name should work here. If it is prohibited, please show the new class names in the document.

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
It works fine for me:
https://codesandbox.io/p/sandbox/objective-villani-86xqnn?file=%2FApp.jsx%3A10%2C22&utm_medium=sandpack

**Comment by jim-king-2000** [comment]
It does **NOT** work with `next.js`.
<https://codesandbox.io/p/sandbox/cranky-jennings-8w9cjz?file=%2Fapp%2Fpage.jsx%3A4%2C32>

**Comment by jim-king-2000** [comment]
Found the culprit.

I copied the content of `tailwind.config.js` from <https://nextui.org/docs/guide/installation#tailwind-css-setup>
```js
// tailwind.config.js
const {nextui} = require("@nextui-org/react");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    // ...
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [nextui()],
};

However, `"./app/**/*.{js,ts,jsx,tsx,mdx}",` should be added to the `content` line.

This content fixes the issue:
```js
// tailwind.config.js
const { nextui } = require('@nextui-org/react');

/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./app/**/*.{js,ts,jsx,tsx,mdx}",
		'./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
	],
	theme: {
		extend: {},
	},
	darkMode: 'class',
	plugins: [nextui()],
};
```
```
