### ISSUE TITLE
[BUG] - Error: Unknown element <[object Object]> in collection.

### ISSUE THREAD

**Issue by d1d4r** [nextui-org/nextui#1917]
### NextUI Version

2.2.3

### Describe the bug

when i use Tabel in server component show this error, the tabel only run in client component "use client", plase fix it

```
const TestTabel = () => {
  return (
    <Tabel aria-label="Example empty table">
      <TableHeader>
        <TableColumn>NAME</TableColumn>
        <TableColumn>ROLE</TableColumn>
        <TableColumn>STATUS</TableColumn>
      </TableHeader>
      <TableBody emptyContent={"No rows to display."}>{[]}</TableBody>
    </Tabel>
  );
};

export default `TestTabel;`
```

### Steps to Reproduce the Bug or Issue

Tabel componet 

```
const TestTabel = () => {
  return (
    <Tabel aria-label="Example empty table">
      <TableHeader>
        <TableColumn>NAME</TableColumn>
        <TableColumn>ROLE</TableColumn>
        <TableColumn>STATUS</TableColumn>
      </TableHeader>
      <TableBody emptyContent={"No rows to display."}>{[]}</TableBody>
    </Tabel>
  );
};

export default TestTabel;
```

just run this code in server component

### Expected behavior

Tabel error server component

### Screenshots or Videos

![tabelErorr](https://github.com/nextui-org/nextui/assets/68716408/b0667450-c9e7-4f59-b9ae-2d8f4e25e620)

### Operating System Version

windows 

### Browser

Chrome

**Comment by jrgarciadev** [comment]
duplicated https://github.com/nextui-org/nextui/issues/1574
