### ISSUE TITLE
[BUG] - Clicking outside the popover element is not recognized in the other elements on the screen

### ISSUE THREAD

**Issue by sbc640964** [nextui-org/nextui#1920]
### NextUI Version

2.2.6 also

### Describe the bug

When a popover is open (Dropdown, Select, Autocomlete, Popover, etc.)
Clicking outside it, closes it but does not focus on the clicked element.

For example if I currently opened a select element, and clicked into another input element, the listbox was closed but the input element was not focused.

It really, really disrupts the work flow...

### Steps to Reproduce the Bug or Issue

Add a component that uses Popover such as Select or Autocomplete.
Add an Input element
Focus the user element in Popover - the selection bubble is opened
When it is still open try to focus the Input element.
The input element is not focused and the bubble is closed...

### Expected behavior

Clicking outside the popover will focus the clicked component (if it can focus)

### Operating System Version

WIN10
### Browser

Chrome

**Comment by SellersEvan** [comment]
I also had this issue. It has to do with the underlying codebase that NextUI is using to deal with overlays. I developed this specifically for the dropdown's but you could use it on other overlay type elements.

```typescript
import { Dropdown as NativeDropdown, DropdownProps } from "@nextui-org/react";
import React from "react";
import { useState } from "react";

export function Dropdown(props:DropdownProps) {
    const [visible, setVisible] = useState(false);
    return (
        <NativeDropdown
            {...props}
            isOpen={visible}
            onOpenChange={(isOpen) => setVisible(isOpen)}
            shouldCloseOnInteractOutside={() => {
                setVisible(false);
                return false;
            }}
        />
    );
}

```

**Comment by RiceWorld** [comment]
Same issue here!!
Clicking to toggle the popover does not work. (onOpenChange event does not fire)
