### ISSUE TITLE
[BUG] - Custom Modal component does not display correctly

### ISSUE THREAD

**Issue by ziracmo** [nextui-org/nextui#1930]
### NextUI Version

2.2.8

### Describe the bug

Hello 

I am willing to extend the Modal component in my app. When trying to open the custom modal, it goes under the footer of the application.

```javascript
import { Modal, extendVariants } from "@nextui-org/react";

export const CustomModal = Modal;

export const CustomExtendModal = extendVariants(Modal, {});

export const CustomModalWithFunction = (props:  ModalProps) => <Modal {...props} />;
```

Using directly the Modal component works well. 

PS: I successfully extend the `Popover` and the `Dropdown` components

### Your Example Website or App

https://github.com/ziracmo/NextUI-Modal-Issue

### Steps to Reproduce the Bug or Issue

- Create a custom component using `Modal` component 

### Expected behavior

Have the same behaviour as using directly the modal component.

### Screenshots or Videos

[screencast-localhost_3000-2023.11.08-18_17_19.webm](https://github.com/nextui-org/nextui/assets/12600085/c66aea0a-1bc1-4691-925b-f47dc14d154a)

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
It works fine for me: https://codesandbox.io/p/sandbox/naughty-jang-5m69jc?file=%2FApp.jsx%3A17%2C56&utm_medium=sandpack

**Comment by JosePadilla98** [comment]
> It works fine for me: https://codesandbox.io/p/sandbox/naughty-jang-5m69jc?file=%2FApp.jsx%3A17%2C56&utm_medium=sandpack

I can't access to the sandbox
