### ISSUE TITLE
[BUG] - `Button` `onPress` will trigger more events.

### ISSUE THREAD

**Issue by jim-king-2000** [nextui-org/nextui#1934]
### NextUI Version

2.2.8

### Describe the bug

When we click the "back" button to route back to the previous page, the same click will trigger the link (on the same position with respect to the "back" button) on the previous page (destination page).

### Steps to Reproduce the Bug or Issue

1. Open <https://[cache-hit-shanghai.github.io/jujiuipcappui/en/nextui/my/> on **mobile** chrome.
1. Click "About" and  go to "About" page, then click "back" icon on the "About" page to go back.
1. Notice it will be redirected to the login page.

**Notes:**
1. <https://github.com/Cache-Hit-Shanghai/jujiuuicomponents/blob/bfc0b1688799fdd4f11960c4df617abb48df182a/nextui/core/core-ui.js#L7> is the code for the back button.
1. If we open the link on PC browser, it works well.
1. The back button handles `onPress` event. If we change it to `onClick`, it works well.
1. I tried to make a smallest reproduce, but I failed. This bug only exists in this [project](https://github.com/Cache-Hit-Shanghai/jujiuipcappui).

### Expected behavior

Just go back to the previous page.

### Operating System Version

Android 13

### Browser

Chrome

**Comment by hamishtaplin** [comment]
This is a really annoying issue with Buttons - it's pretty common that a Button press will trigger a UI change that results in another Button appearing in the same position and then the mouseup event gets caught by the second Button and triggers the onPress again.

**Comment by jim-king-2000** [comment]
It's pretty weird. The two buttons interested are **NOT** even on the same page. Besides, if the button underneath is a common button processing `onPress` (not a `Link`), it works well. So, is it a bug of `nextui` or not?

**Comment by jim-king-2000** [comment]
It can't be reproduced on v2.2.9.

**Comment by friday-sds** [comment]
I believe This issue is from react-aria. https://github.com/adobe/react-spectrum/issues/5802 . @jim-king-2000 this issue is  still happening . I am using next ui 2.2.9

**Comment by jim-king-2000** [comment]
> I believe This issue is from react-aria. [adobe/react-spectrum#5802](https://github.com/adobe/react-spectrum/issues/5802) . @jim-king-2000 this issue is still happening . I am using next ui 2.2.9

Yeah, I think so. What should we do? Fire another issue for react-aria?
