### ISSUE TITLE
[BUG] - Button is doing full reload of the page

### ISSUE THREAD

**Issue by xencodes** [nextui-org/nextui#1937]
### NextUI Version

2.2.8

### Describe the bug

I have the following code in my project (Next 14):

```jsx
import Link from 'next/link'
import { Button } from '@nextui-org/react'
// ----
<Link href="/submit">
  <Button>Submit</Button>
</Link>
```

Whenever I click on the button, it does a full reload of the page instead of loading only the page. I am doing the same with `Card` component but there is no such issue with it.

### Steps to Reproduce the Bug or Issue

1. Import Link and Button
2. Use Link on a Button
3. Click on the Button

### Expected behavior

It should do lazy loading

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @xencodes I don't see the `Button` implementation in the code you shared

**Comment by xencodes** [comment]
> Hey @xencodes I don't see the `Button` implementation in the code you shared

Omg!! So sorry. I was just testing with p tags, and it works fine, but with button it does not. And I forgot to remove the p tag. My bad.

**Comment by jrgarciadev** [comment]
Ok got it, try this:

```tsx
import Link from 'next/link'
import { Button } from '@nextui-org/react'
// ----
 <Button as={Link} href="/submit">Submit</Button>

```

**Comment by xencodes** [comment]
thanks! it worked.

**Comment by mephju** [comment]
In my opinion the first version should work as well. If a button can't be used that way something is fishy.

**Comment by pppdns** [comment]
I ran into this issue too, I wasn't expecting `Link` and `Button` to not work together properly.
Your solution worked, @jrgarciadev, thanks!
Maybe this should be documented in the `Button` docs?

**Comment by terminaate** [comment]
Great, and they removed "as" prop, how one supposed to fix this problem in this big 2026?

**Comment by wingkwong** [comment]
@terminaate you can either put button styles on `next/link`:

```tsx
import Link from "next/link";
import { buttonVariants } from "@heroui/react";

<Link href="/submit" className={buttonVariants({ variant: "primary" })}>
  Submit
</Link>
```

or with BEM classes:

```tsx
<Link href="/submit" className="button button--primary">
  Submit
</Link>
```

ref: https://heroui.com/en/docs/react/getting-started/composition
