### ISSUE TITLE
[BUG] - v2 textarea doesn't allow spaces

### ISSUE THREAD

**Issue by ceastman-r7** [nextui-org/nextui#1939]
### NextUI Version

2.1.13

### Describe the bug

When trying to type in the Textarea box, spaces are not allowed.

### Steps to Reproduce the Bug or Issue

                    <Textarea
                      label="Justification"
                      placeholder="Explain what change meets this criteria and why it's needed"
                      className={`${question.answered_yes ? 'h-32' : 'h-0'} transition-all duration-300 overflow-hidden w-full mt-5`}
                      defaultValue={comment}
                      onBlur={
                        (event) => { handleCommentUpdate(index, event.target.value) }
                      }
                    />

### Expected behavior

As a user I expect to be able to type full sentences including spaces in the Textarea box.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/97614291/df49a2e3-e65d-4397-a3fa-db92381c3e22

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
This issue was fixed a while ago, update to the latest version.

https://codesandbox.io/p/sandbox/hjdl4j?file=%2FApp.jsx&utm_medium=sandpack
