### ISSUE TITLE
[BUG] - With extendVariants, some components don't work with slots

### ISSUE THREAD

**Issue by IraiDev** [nextui-org/nextui#1942]
### NextUI Version

2.2.0

### Describe the bug

When trying to use the extendVariants function with the Input, Table, and other components, the slots cease to function. They do not recognize the provided styles. So far, I have tested it with the Input, Select, Button, and Table components. I am using React.js.

### Steps to Reproduce the Bug or Issue

only use extendVarians function

### Expected behavior

I hope that the styles can be applied to adapt Next UI components to my application. Currently, with the extendVariants function, the styles are not being recognized, making it challenging to integrate the components seamlessly.

### Operating System Version

windows

### Browser

Chrome

**Comment by mister-mist** [comment]
Can you show how you have used the extendVariants function?

**Comment by jrgarciadev** [comment]
Hello @mister-mist, it's important to note that the `extendVariants` function isn't designed to support slot overrides or the addition of custom slots. Its primary purpose is to extend the definitions of the default variants.

However, if you're looking to override the label styles, you can achieve this by using the `classNames` prop. Here's an example to illustrate how you can do that:


```tsx
<Input
        type="email"
        label="Email"
        placeholder="Enter your email"
        classNames={{
          label: "text-danger",
        }}
      />
```
