### ISSUE TITLE
[BUG] - Non-dissmissable modal can be closed by pressing ESC key

### ISSUE THREAD

**Issue by mythicalbro** [nextui-org/nextui#1952]
### NextUI Version

2.2.5

### Describe the bug

In the docs it says that its possible to make a modal non-dismissible by setting the isDismissable prop to false, but it does not make it non-dismissible. It can still be closed by pressing ESC key.
It can be reproduced on the docs.

### Your Example Website or App

https://nextui.org/docs/components/modal#non-dissmissable

### Steps to Reproduce the Bug or Issue

1. Go to https://nextui.org/docs/components/modal#non-dissmissable
2. Press "Open Modal" button
3. Press ESC

### Expected behavior

I expected the modal to be non-dismissible, but it is still dismissible by pressing ESC key.

### Operating System Version

Windows

### Browser

Edge

**Comment by jrgarciadev** [comment]
Hey @mythicalbro in this context non-dismissable means that the Modal only can be closed by calling the `onClose` function or changing the `isOpen` to `false`, otherwise the property would be useless.

**Comment by mythicalbro** [comment]
> Hey @mythicalbro in this context non-dismissable means that the Modal only can be closed by calling the `onClose` function or changing the `isOpen` to `false`, otherwise the property would be useless.

But the modal can still be closed by pressing ESC key when `isDismissable` is set to `false`. In the docs it says that this behavior can be disabled by setting `isDismissable` to `false`.

**Comment by webdevaw** [comment]
This bug still exists. When `isDismissable` is set to `false` pressing ESC key closes modal.

**Comment by cristiansantana** [comment]
Still exists the bug... when `isDismissable = {false}` esc key still can close the non-dismissable modal (the documentation indicates that this should not happen)
