### ISSUE TITLE
[BUG] - SSR "useLayoutEffect" in Tooltip component

### ISSUE THREAD

**Issue by friedemannsommer** [nextui-org/nextui#1954]
### NextUI Version

2.2.8

### Describe the bug

There seems to be a similar problem in the latest version as in a previous issue #1386.

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
 at file:///app/node_modules/@nextui-org/tooltip/dist/chunk-MA2FG3JE.mjs:29:7
 at file:///app/node_modules/@nextui-org/snippet/dist/chunk-DMESSLTO.mjs:36:18
 at div
 at file:///app/node_modules/@nextui-org/snippet/dist/chunk-DMESSLTO.mjs:34:7
```

https://github.com/nextui-org/nextui/blob/12cebcfdac525abc4debf7cee45166c840265b11/packages/components/tooltip/src/use-tooltip.ts#L183-L187

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-7urocq?file=README.md

### Steps to Reproduce the Bug or Issue

1. open the Stackblitz example
2. run `npm run start` in the Stackblitz terminal
3. navigate to `/` (index) page
4. the terminal output should now include a `useLayoutEffect` warning

### Expected behavior

I would expect that the `Tooltip` component does not call the `useLayoutEffect` hook inside a SSR environment.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/5468809/36d6e740-c53d-479f-868e-a5f8299c494c)

### Operating System Version

Linux

### Browser

Other (add additonal context)

**Comment by adelsz** [comment]
Running into this as well

**Comment by hexaaagon** [comment]
same issues

**Comment by kelvinCJJ** [comment]
Hi, any updates on this?

**Comment by Zuwie** [comment]
Same issue with Remix here.

**Comment by aramshiva** [comment]
Still getting this issue.

**Comment by SzymonDukla** [comment]
Still getting it, so how come the issue is closed

**Comment by luixo** [comment]
The last release was on 10 November, the change will get in effect in the next release.
