### ISSUE TITLE
[BUG] - NextUIProvider creates a <div data-overlay-container="true">  that breaks "z-index" usage

### ISSUE THREAD

**Issue by bdiazc90** [nextui-org/nextui#1955]
### NextUI Version

2.2.9

### Describe the bug

I had some gradient images in my landing page (with z-index: -50) like example:

![image](https://github.com/nextui-org/nextui/assets/20211744/2c17616f-7af2-4b3c-bd86-5538f0ab9a90)

But once i installed Next UI, the gradient images get hidden, because of all my elements are now being wrapping by the NextUIProvider, that creates a `<div data-overlay-container="true">` with a lot of predefined styles, like for example, **the background color** of the document. Like this:

![Captura de pantalla 2023-11-11 a la(s) 02 12 33](https://github.com/nextui-org/nextui/assets/20211744/41b9acec-291d-48f4-a5b7-b000b1813ad2)

### Steps to Reproduce the Bug or Issue

Install NextUI and make the steps of implementation.
Then, Inspect you web in Chrome dev tools, and you will see this div just inside de body.

### Expected behavior

I expect to have the chance of decide what styles are pre-charged with de NextUIProvider,
or at least, a way to keep the background color of the document, as transparent.

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Fixed a while ago: https://github.com/nextui-org/nextui/issues/1494
