### ISSUE TITLE
[BUG] - docker build has a error that is Switch Component

### ISSUE THREAD

**Issue by jmy2022** [nextui-org/nextui#1956]
### NextUI Version

2.0.25

### Describe the bug

6 ./components/theme-switch.tsx:43:4
18.26 Type error: 'Component' cannot be used as a JSX component.
18.26   Its element type 'Element | Component<any, any, any> | null' is not a valid JSX element.
18.26     Type 'Component<any, any, any>' is not assignable to type 'Element | ElementClass | null'.
18.26       Type 'Component<any, any, any>' is not assignable to type 'ElementClass'.
18.26         The types returned by 'render()' are incompatible between these types.
18.26           Type 'React.ReactNode' is not assignable to type 'import("/app/node_modules/@types/react-dom/node_modules/@types/react/ts5.0/index").ReactNode'.
18.26             Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
18.26               Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.
18.26 
18.26   41 |    return (
18.26   42 |            <div>
18.26 > 43 |            <Component
18.26      |             ^
18.26   44 |                    {...getBaseProps({
18.26   45 |                            className: clsx(
18.26   46 |                                    "px-px transition-opacity hover:opacity-80 cursor-pointer",
18.37 error Command failed with exit code 1.

### Steps to Reproduce the Bug or Issue

# Install dependencies only when needed
FROM node:alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json ./
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:alpine AS builder
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN yarn build && yarn install --production --ignore-scripts --prefer-offline

# Production image, copy all the files and run next
FROM node:alpine AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# You only need to copy next.config.js if you are NOT using the default configuration
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/components ./components
COPY --from=builder /app/styles ./styles
COPY --from=builder /app/types ./types
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE 3000

ENV PORT 3000

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# ENV NEXT_TELEMETRY_DISABLED 1

CMD ["node_modules/.bin/next", "start"]

# COPY failed: file not found in build context or excluded by .dockerignore: stat yarn.lock: file does not exist

### Expected behavior

thanksm

### Screenshots or Videos

above

### Operating System Version

macos

### Browser

Chrome

**Comment by jrgarciadev** [comment]
This doesn't seen to be a NextUI issue.
