### ISSUE TITLE
[Feature Request] TextArea supports autocompletion

### ISSUE THREAD

**Issue by obiscr** [nextui-org/nextui#1957]
### Is your feature request related to a problem? Please describe.

I'm looking for a component similar to the [AutoComplete ](https://nextui.org/docs/components/autocomplete) component, except that AutoComplete is based on a ComboBox, whereas I want to base it on a TextArea. 

Maybe another way would be clearer, I made an editor with TextArea, and I want to support something like AutoComplete in this editor.

Is there any way to do this?

### Describe the solution you'd like

I wish there was a way to simply implement the ability to use autocomplete in TextArea, who is very, very much like code completion for editors.

### Describe alternatives you've considered

I haven't found an alternative.

**Comment by jrgarciadev** [comment]
Hey @obiscr the Autocomplete component is not meant to support Textarea + Suggestions. Maybe what you're looking for is something like this https://editorjs.io/

**Comment by obiscr** [comment]
I see, thank you!
