### ISSUE TITLE
[BUG] - ExtendVariants does not retain applied styles (always reverts to default styles) in 2.2.9

### ISSUE THREAD

**Issue by cheestudio** [nextui-org/nextui#1959]
### NextUI Version

2.2.9

### Describe the bug

I am extending the Button component with some variants and it's been working great:

```
import { extendVariants, Button } from "@nextui-org/react";

const base = "wallabie-button relative rounded-[5px] border border-solid shadow-wallabie-light py-2 px-5 text-sm border-[#E9DBCC] bg-wallabie-offwhite text-wallabie-gray hover:border-wallabie-tan/40 hover:shadow-wallabie-dark";

export const ButtonExt = extendVariants(Button, {
  variants: {
    color: {
      light: `${base}`,
      dark: `${base} border-[#E9DBCC] bg-wallabie-teal-100 text-wallabie-black`,
    },
    type: {
      icon: `${base} p-2`,
      text: `${base} p-2 bg-transparent border-none underline hover:text-wallabie-orange shadow-none`,
    },
  },
  defaultVariants: { 
    color: "light"
  }
});
```

Since updating 2.2.9, the styles apply on first render, but any subsequent renders (e.g. opening a modal) causes reverts the button styles back to the original default gray styling.

On render:
![image](https://github.com/nextui-org/nextui/assets/2074095/af888c41-d919-419f-acc5-7039b347ed64)

After opening a modal:
![image](https://github.com/nextui-org/nextui/assets/2074095/17b5eaf6-892c-4bcf-b525-738cb0782019)

### Steps to Reproduce the Bug or Issue

Install NextJS with NextUI

Extend variants of Button and apply

### Expected behavior

The button styles should be consistent, rather than reverting to the default styles

### Operating System Version

Windows

### Browser

Chrome

**Comment by cheestudio** [comment]
As an update: it seems the `defaultVariant` does not retain on render. 

`<ButtonExt onPress={(e) => console.log(e)}>Get Started</ButtonExt>`

If I force a variant, it seems to work fine:

`<ButtonExt color="light" onPress={(e) => console.log(e)}>Get Started</ButtonExt>`

**Comment by CSpencerND** [comment]
Having the same issue

**Comment by xxxijustwei** [comment]
Please rewrite compoundVariants
```
export const EButton = extendVariants(Button, {
    compoundVariants: [
        {
            className: "bg-p-base text-t-100 font-[800]",
        }
    ],
    variants: {
        color: {
            default: "bg-p-base text-t-100 font-[800]"
        }
    },
    defaultVariants: {
        color: "default",
        size: "md"
    }
});
```

**Comment by william0619** [comment]
I also encountered this problem and do not know when it will be repaired
