### ISSUE TITLE
[BUG] - height input without label

### ISSUE THREAD

**Issue by sbc640964** [nextui-org/nextui#1961]
### NextUI Version

2.2.9

### Describe the bug

When no label was assigned, The controller wrapper continued to be high without proportion.

![image](https://github.com/nextui-org/nextui/assets/46646044/e2f3bc5b-d295-4451-a97b-eb230efb6cc3)

### Steps to Reproduce the Bug or Issue

Simply, create an input without a label, whose label position is inside

### Expected behavior

The height of the input is automatically updated to the height of the text + padding

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/46646044/e2f3bc5b-d295-4451-a97b-eb230efb6cc3)

### Operating System Version

WIN10

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Use `labelPlacement="outside"`
