### ISSUE TITLE
[Feature Request] DATE PICKER, DATE_RANGE PICKER, ALSO SIDEBAR

### ISSUE THREAD

**Issue by shourovr82** [nextui-org/nextui#1964]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

it could be inspired from material ui 

### Describe alternatives you've considered

no its a feature

**Comment by jrgarciadev** [comment]
These components were already requested, check the Discussions page -> feature requests.

**Comment by shourovr82** [comment]
> These components were already requested, check the Discussions page -> feature requests.

ok. but please add these features as soon as possible.
