### ISSUE TITLE
[BUG] - `Card` border disappears when the parent div contains `overflow-auto`

### ISSUE THREAD

**Issue by jim-king-2000** [nextui-org/nextui#1965]
### NextUI Version

2.2.9

### Describe the bug

Set `overflow-auto` to the parent div, the border of the child `Card` disappears.

### Steps to Reproduce the Bug or Issue

1. Open <https://codesandbox.io/p/sandbox/test-nextui-tch2hd>
2. See The up and down border of the card (contains 'abcd') disappears.
3. Change `<div className="overflow-auto">` to `<div>`.
4. Notice the borders are back.

**Note**: It works find in dark mode. It is only reproducible in light mode.

### Expected behavior

Render the border normally.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by jrgarciadev** [comment]
The Card border is actually a `shadow` so it needs to have space to be visible, you can add some padding to the parent to make it visible.

https://codesandbox.io/p/sandbox/test-nextui-forked-cscxsp?file=%2Fapp%2Fpage.jsx%3A11%2C33

**Comment by jim-king-2000** [comment]
`Card` should behave consistently no matter what the properties are set to the parent div. The border displays normally when the parent div does not have `overflow-auto`, while it displays abnormally when `overflow-auto` is set. The inconsistency is the bug.
