### ISSUE TITLE
isLoading prop for `<Card />`, which will show skeleton loading styling in card

### ISSUE THREAD

**Issue by erenkulaksiz** [nextui-org/nextui#197]
**Is your component proposal related to a problem? Please describe.**

The problem here is, i am using cards for some dynamic generated content. Currently rendering `<Loading />` component to tell the user that cards is loading. If there was a skeleton type of cards (with isSkeleton prop), instead of showing them the loading component, i can easly show some cards with skeleton styling.

**Describe the solution you'd like**

Check out my codepen example from November 3, 2020 (has messy code but its on-point example): [` https://codepen.io/erenkulaksiz/pen/zYBapQR?editors=1010`]( https://codepen.io/erenkulaksiz/pen/zYBapQR?editors=1010)
Click the 'fetch' button. While fetching, it will show 3 cards while loading with state of skeleton loader.

Theres also some examples from Material UI & Chakra UI: 
[`https://mui.com/components/skeleton/`]( https://mui.com/components/skeleton/)
[`https://chakra-ui.com/docs/feedback/skeleton`](https://chakra-ui.com/docs/feedback/skeleton)

**Describe alternatives you've considered**

The current alternative i have currently is, while loading content inside cards i show user `<Loading />` component. I want to show some cards with skeleton type of loading instead of showing one dumb loading component.

**Additional context**

I'll try to create pull request if i have freetime soon, with isSkeleton prop on `<Card />`

The example i attached uses Axios to get data from IMDB api, while loading it shows skeleton loaders. I know this is not important feature but i think some of users might need it in the future.

**Comment by jrgarciadev** [comment]
Hey @erenkulaksiz thanks for the suggestions, however since the `Skeleton` component is not ready yet could you please move this to the Discussions section?, we hope to add the `Skeleton` component after the `v1` stable release

**Comment by erenkulaksiz** [comment]
Thanks for the response! I'll add this issue to discussions, sure.
