### ISSUE TITLE
[BUG] - Listbox does not work in server components

### ISSUE THREAD

**Issue by De3ph** [nextui-org/nextui#1972]
### NextUI Version

2.2.9

### Describe the bug

This is my Next.js 14.0.2 app/page.tsx file. After setting up providers by follwing documentation, it doesn't work as I expected. When I replace Listbox with Button, it works correctly. Did I miss something?

### Your Example Website or App

https://github.com/De3ph/next14-nextui

### Steps to Reproduce the Bug or Issue

Go and clone the repo
install dependencies with pnpm and run the application on dev server

### Expected behavior

I expect Listbox work properly in server components.

### Screenshots or Videos

![code](https://github.com/nextui-org/nextui/assets/62203579/e003a083-0d37-4516-be0e-1ea1b64fb20b)

### Operating System Version

Windows

### Browser

Edge

**Comment by jrgarciadev** [comment]
Please check this comment https://github.com/nextui-org/nextui/issues/1619#issuecomment-1721346449
