### ISSUE TITLE
[BUG] - Tolltip Inside DropdownTrigger causes `Maximum update depth exceeded` error

### ISSUE THREAD

**Issue by remorses** [nextui-org/nextui#1975]
### NextUI Version

2.2.8

### Describe the bug

Tolltip Inside DropdownTrigger causes `Maximum update depth exceeded` error

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-eu7v7n?file=app%2Fpage.tsx

### Steps to Reproduce the Bug or Issue

1. `npm run dev`
2. Notice the console logs `Maximum update depth exceeded`, this will also consume a lot of CPU

### Expected behavior

No Maximum update depth exceeded error

### Operating System Version

Any

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Please check this comment https://github.com/nextui-org/nextui/issues/1647#issuecomment-1746920362
