### ISSUE TITLE
[BUG] - Cannot find package 'lodash.mapkeys' imported from @nextui-org/theme

### ISSUE THREAD

**Issue by kelvinCJJ** [nextui-org/nextui#1980]
### NextUI Version

2.2.9

### Describe the bug

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'lodash.mapkeys' imported from /var/task/node_modules/@nextui-org/theme/dist/chunk-5QVKTCUZ.mjs    at new NodeError (node:internal/errors:405:5)    at packageResolve (node:internal/modules/esm/resolve:895:9)    at moduleResolve (node:internal/modules/esm/resolve:988:20)    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:939:12)    at defaultResolve (node:internal/modules/esm/resolve:1181:79)    at nextResolve (node:internal/modules/esm/loader:163:28)    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)    at link (node:internal/modules/esm/module_job:76:36) {  code: 'ERR_MODULE_NOT_FOUND'} | 2023-11-15T06:25:24.113Z a50ac449-2fea-4d4e-8c80-cac97ab38e49 ERROR Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'lodash.mapkeys' imported from /var/task/node_modules/@nextui-org/theme/dist/chunk-5QVKTCUZ.mjs at new NodeError (node:internal/errors:405:5) at packageResolve (node:internal/modules/esm/resolve:895:9) at moduleResolve (node:internal/modules/esm/resolve:988:20) at moduleResolveWithNodePath (node:internal/modules/esm/resolve:939:12) at defaultResolve (node:internal/modules/esm/resolve:1181:79) at nextResolve (node:internal/modules/esm/loader:163:28) at ESMLoader.resolve (node:internal/modules/esm/loader:835:30) at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18) at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40) at link (node:internal/modules/esm/module_job:76:36) { code: 'ERR_MODULE_NOT_FOUND' }

### Steps to Reproduce the Bug or Issue

1. install Next.js with SST
2. use "npx sst deploy" to deploy the stacks on AWS
3. after full deployment, the cloudwatch logs returns this missing node module

### Expected behavior

As a user, I expect that the node module would be installed, but according to the image i uploaded, lodash.mapskeys is missing 

### Screenshots or Videos

![nextui theme](https://github.com/nextui-org/nextui/assets/21039497/5c696a84-8676-4369-a7e1-82db9594f19b)

### Operating System Version

Windows

### Browser

Edge

**Comment by florent-martineau** [comment]
I do have the same issue. I tried downgrading to `@nextui-org/react` version `2.1.13` to no avail.

**Comment by getellez** [comment]
same here

**Comment by getellez** [comment]
You need to downgrade NextJS to 13.5.3. It worked for me. I had the version 13.5.4

**Comment by wingkwong** [comment]
Closing - not applicable. This will be removed in next version.
