### ISSUE TITLE
[BUG] - Skeleton component animation is buggy in safari browser.

### ISSUE THREAD

**Issue by hanzlah101** [nextui-org/nextui#1981]
### NextUI Version

2.2.9

### Describe the bug

The flowing animation of the skeleton component remains squared shaped only i.e border radius isn't working properly on the **safari browser**. On other browsers like chrome, edge it works completely fine.

### Steps to Reproduce the Bug or Issue

Go to `https://nextui.org/docs/components/skeleton` on safari browser and issue is clearly visible

### Expected behavior

Provided the border radius it the animation div should also behave the same.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/116737045/e2d21340-8189-4ae3-b896-db07f053a6eb

### Operating System Version

macOs

### Browser

Safari

**Comment by jrgarciadev** [comment]
Which version of safari do you have?

It work fine for me

https://github.com/nextui-org/nextui/assets/30373425/3539c519-6fb6-418f-ba9b-ee63a1ceb516

**Comment by wingkwong** [comment]
Closing - Not reproducible + Inactivity
