### ISSUE TITLE
Input component isClearable not working

### ISSUE THREAD

**Issue by jbmagx** [nextui-org/nextui#1984]
### NextUI Version

2.2.9

### Describe the bug

I’m using NextUI with latest version of Vite ReactJS and Tailwind CSS. I just noticed that the isClearable feature of the Input component doesn’t clear the input field. I wonder what’s causing this issue. I tried creating a new project, installed the latest version of Vite, Tailwind CSS, and NextUI. But the issue is still there. Hope you can investigate this. Thank you.

### Steps to Reproduce the Bug or Issue

1. Create a vite reactjs project with latest version.
2. Install Tailwind CSS.
3. Install NextUI.
4. Add an Input component with an isClearable props.
5. Type on the input field and click the clear button.

### Expected behavior

I expect for the input field to be cleared. But only the clear button is gone. The input field still has its value.

### Operating System Version

macOS

### Browser

Chrome

**Comment by jbmagx** [comment]
Additional info:

I have an old project that uses the NextUI v2.1.13 and framer-motion v10.16.4. The clear button there still works fine. But since I want to use the updated version of NextUI, so I upgraded to v2.2.9 and then the clear button doesn't empty the input field anymore. I'm assuming that something gone wrong with the Input component clear button in the latest version.

**Comment by alexander-densley** [comment]
+1
