### ISSUE TITLE
Append custom Classes to Components

### ISSUE THREAD

**Issue by creazy231** [nextui-org/nextui#199]
**Describe the bug**
Want to add some classes to the `<Text />` component without success. Manually added classes simply don't appear.

**Steps to reproduce**
1. Add Text Element
```js
import {Text} from '@nextui-org/react';

return(
  <Text
    size={12}
    className="example-class"
  >Example Text</Text>
);
```

**Expected behaviour**
```html
<p class="nextui-c-PJLV nextui-c-PJLV-ijwlVtB-css example-class">Example Text</p>
```

**Current behaviour**
```html
<p class="nextui-c-PJLV nextui-c-PJLV-ijwlVtB-css">Example Text</p>
```

Maybe this also appears on other elements. Didn't have time to test.

**Comment by jrgarciadev** [comment]
Thanks for reporting it @creazy231 🙌🏻 , thank you @Dhananjay-JSR for fixing it so fast 🚀
