### ISSUE TITLE
[BUG] - Input `type="email"` default browser validation not showing missing '@' symbol message

### ISSUE THREAD

**Issue by aliabb01** [nextui-org/nextui#1996]
### NextUI Version

2.2.9

### Describe the bug

I have a simple form with NextUI input element. This input has `type="email"`. 

Suppose form submission happens with a non-email string or without the '@' symbol. In that case, the default browser validation (showing a message) does not show the browser message and the input element gets focused.

### Your Example Website or App

https://aliabb.vercel.app

### Steps to Reproduce the Bug or Issue

1. Go to the contact section at the bottom of the home page.
2. Write a non-email string to email input (Ex: abc) and write any message to the textarea
3. Submit the form

### Expected behavior

As a user, I expected to see the default browser validation message about email missing the '@' symbol

### Operating System Version

Windows 11 Home

### Browser

Chrome

**Comment by Armandotrsg** [comment]
It also happens when you use `type="tel"`. I think it's because behind the scenes when the HTML type validation fails NextUI only sets the cursor focus to the input without showing the error message.

**Comment by lyalls-marc** [comment]
I had a look at this issue it looks like it is react aria that changed which break it default behaviour

**Comment by Armandotrsg** [comment]
> I had a look at this issue it looks like it is react aria that changed which break it default behaviour

So it's an issue with React-Aria?

**Comment by wingkwong** [comment]
I could reproduce the issue with the latest `@nextui-org/input` (`v2.1.17`) but not in the current `main` branch. Seems this has been resolved but the fix will be available in the next release.

<img width="538" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/5cb57418-c446-4600-9d1d-4d7c79867bfe">
