### ISSUE TITLE
[BUG] - Input autofill highlight

### ISSUE THREAD

**Issue by Innders** [nextui-org/nextui#2005]
### NextUI Version

2.2.6

### Describe the bug

When autofilling inputs on chrome there's an ugly highlighting of the text. I'm not sure if it's a bug but it doesn't look very nice and clashes with the style of the input.

### Steps to Reproduce the Bug or Issue

1. Input type text or password.
2. Use autofill on chrome to fill the input value. Also the same for password autofill.
3. New filled text has highlighted background.

### Expected behavior

Autofill text without highlight background.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/49156310/674aa297-fa8c-4833-934a-3583188de757)

### Operating System Version

MacOS

### Browser

Chrome

**Comment by getellez** [comment]
But in the nextui docs the input doesn't look like that, why?

**Comment by getellez** [comment]
@Innders  I fixed the background by removing the colors property from the `theme` in the `tailwind.config.js` file

**Comment by dejavuhuh** [comment]
> @Innders I fixed the background by removing the colors property from the `theme` in the `tailwind.config.js` file我通过从 `tailwind.config.js` 文件中删除 `theme` 的颜色属性来修复背景

@getellez How did you do that?

**Comment by abhinandan-verma** [comment]
@Innders @wingkwong   this issue  has been solved kindly close it.

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3430
