### ISSUE TITLE
[Feature Request] BreadCrumbs allow custom colors in color property

### ISSUE THREAD

**Issue by CharriereThibaud** [nextui-org/nextui#2007]
### Is your feature request related to a problem? Please describe.

Currently, we are only limited to default colors ("foreground", "primary", "secondary", "success", "warning", "danger").

### Describe the solution you'd like

As an user, it should be great to be able to use custom colors like tailwind colors or hexadecimal color code.

```jsx
<Breadcrumbs color="red">
            <BreadcrumbItem href="/">Home</BreadcrumbItem>
</Breadcrumbs>
```

```jsx
<Breadcrumbs color="#128a67f">
            <BreadcrumbItem href="/">Home</BreadcrumbItem>
</Breadcrumbs>
```

```jsx
<Breadcrumbs className="red-600">
            <BreadcrumbItem href="/">Home</BreadcrumbItem>
</Breadcrumbs>
```

### Describe alternatives you've considered

- Add a custom property like `customColor`
- Let set color with Tailwind color className

**Comment by CaseyBlackburn** [comment]
You can already customize them as you wish.
Make use of the slots for applying your preferred styles: [Slots](https://nextui.org/docs/components/breadcrumbs#slots)

See the example of a customized Breadcrumb: [Customizing the Breadcrumbs Styles](https://nextui.org/docs/components/breadcrumbs#customizing-the-breadcrumbs-styles)

**Comment by CharriereThibaud** [comment]
Indeed, we can override the styles, I hadn't noticed this while searching in the documentation.
However, it requires overriding multiple times, especially when dealing with ellipsis or objects. I believe it could be worthwhile for all components that have a `color` attribute to be able to assign a custom color, in hexadecimal or RGB for example.
I close this issue and will open a new proper issue fot all components that implement `color` attribute.
