### ISSUE TITLE
[Feature Request] Table Cell Selection

### ISSUE THREAD

**Issue by SainDev** [nextui-org/nextui#2015]
### Discussed in https://github.com/nextui-org/nextui/discussions/2014

<div type='discussions-op-text'>

<sup>Originally posted by **SainDev** November 22, 2023</sup>
### Is your feature request related to a problem? Please describe.
The library lacks a built-in cell selection feature, which is sorely lacking and I have to look for solutions in third-party libraries.
Now I'm trying to screw my own solution, but everything is complicated by the lack of onMouseDown and onMouseUp events in the TableCell component.

### Describe the solution you'd like
Cell range selection functionality that would allow cells to be selected and, for example, output to the user the sum of the selected cells. Single and Multiple.

### Describe alternatives you've considered
Very good tables with selections and filters at https://primereact.org/datatable/ , but I would like to use your library, as it is amazing in design and animations.
https://www.ag-grid.com/react-data-grid/range-selection/</div>

**Comment by jrgarciadev** [comment]
NextUI table is based on the react-aria `useTable` hook which accepts keyboard selections by using the `Ctrl`, `Cmd`, `Shift`, `Enter`, `Space` keys, but you need to change the `selectionBehavior` to `replace`. 

https://react-spectrum.adobe.com/react-aria/useTable.html#selection-behavior

**Comment by SainDev** [comment]
@jrgarciadev OK. This works when selecting rows, but what about when you need to select cells?

**Comment by AhmedBaset** [comment]
> OK. This works when selecting rows, but what about when you need to select cells?

Anything changed since then?

Hey @jrgarciadev, This issue title is "Table Cell Selection" it shouldn't be closed "as completed" with the provided the row selection approach

**Comment by SainDev** [comment]
> Anything changed since then?

Unfortunately, no. I had to implement my own solution and use the Tanstack table.
