### ISSUE TITLE
[BUG] - Input field animation behaves unexpected

### ISSUE THREAD

**Issue by VMLVaske** [nextui-org/nextui#2017]
### NextUI Version

2.2.1

### Describe the bug

I am using the input field from NextUI without any conflicting or other CSS classes in my project. I expect the field to behave as it does in the docs. 
When entering data, the label does not move up and 'out of the way' as it does in the docs. 
![Screenshot 2023-11-22 at 14 57 02](https://github.com/nextui-org/nextui/assets/32402989/9f8f583d-0ee0-4e0e-8606-6ae9546eb1d2)

When taking the focus from the component, the inputted data kinda overlaps with the label. 
![Screenshot 2023-11-22 at 14 57 41](https://github.com/nextui-org/nextui/assets/32402989/a029b029-bd70-49fd-b3a7-76291959b666)

Issue persists across several different browsers (Brave, Chrome) and computers. Seems to be a bug of the component? 
NextUI/react version is ^2.2.1, NextUI/Input version is 2.1.6

### Steps to Reproduce the Bug or Issue

1. create next project according to template
2. use input component
3. be faced with the behaviour

### Expected behavior

As a user, I expect the component to behave in the same way as the example component in the docs does. 

### Operating System Version

macOs

### Browser

Other (add additonal context)

**Comment by jrgarciadev** [comment]
Hey @VMLVaske update to the latest version v2.2.9, this issue was fixed a while ago.

**Comment by VMLVaske** [comment]
Hi @jrgarciadev! Version 2.2.9 doesn't work for me, it throws a compiler error: 
./node_modules/@nextui-org/autocomplete/dist/chunk-SGJY6NTV.mjs
Attempted import error: 'autocomplete' is not exported from '@nextui-org/theme' (imported as 'autocomplete').

Import trace for requested module:
./node_modules/@nextui-org/autocomplete/dist/chunk-SGJY6NTV.mjs
./node_modules/@nextui-org/autocomplete/dist/index.mjs
./node_modules/@nextui-org/react/dist/index.mjs

Just wanted to let you know.

**Comment by VMLVaske** [comment]
Ah, this solved it. Tried deleting + reinstalling before writing to you, but think I maybe forgot the lock file ^^° sorry for taking your time with 1-Level support bs :D thanks for the help tho, appreciate you man :)
