### ISSUE TITLE
[BUG] - Table: Rerender the entire table after modifying the data

### ISSUE THREAD

**Issue by myesn** [nextui-org/nextui#2019]
### NextUI Version

2.2.9

### Describe the bug

After setting the `classNames` property on the dynamic data `<Table>` component, the entire table will be re-rendered when the dynamic data is changed

Please view the `<table>` element in the Elements tab of DevTools in your browser.

### Your Example Website or App

[codesandbox](https://codesandbox.io/p/devbox/polished-brook-m69r66?file=%2FApp.jsx%3A86%2C14)

### Steps to Reproduce the Bug or Issue

```tsx
<Table
      classNames={{
        wrapper: ["p-0"],
      }}
    >
      ..
</Table>
```

### Expected behavior

Only the corresponding Dom elements of the modified data should be re-rendered

### Operating System Version

Windows

### Browser

Edge

**Comment by LinuxKunaL** [comment]
Look into the NextUI documentation to see if there are any specific guidelines or props related to dynamic data and rendering optimizations.

**Comment by myesn** [comment]
@LinuxKunaL Thanks for the reply, I can't find the relevant documentation, this may be a bug.

**Comment by black197** [comment]
@myesn You can use `React.useMemo` to cache `classNames` object to prevent re-rendering. See [codesandbox](https://codesandbox.io/p/devbox/blissful-hopper-4ncjsr?file=%2FApp.jsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpexw61k0009356idpqe3eo4%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpexw61k0004356ib7soyoel%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpexw61k0006356ik77gj3g1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpexw61k0008356isbla0c9d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpexw61k0004356ib7soyoel%2522%253A%257B%2522id%2522%253A%2522clpexw61k0004356ib7soyoel%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clpeyp7ad007z356inq4ku2t1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpeyp7ad007z356inq4ku2t1%2522%257D%252C%2522clpexw61k0008356isbla0c9d%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpexw61k0007356iiv09fut4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpexw61k0008356isbla0c9d%2522%252C%2522activeTabId%2522%253A%2522clpexw61k0007356iiv09fut4%2522%257D%252C%2522clpexw61k0006356ik77gj3g1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpexw61k0005356iwf8ndbjj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clpexw61k0006356ik77gj3g1%2522%252C%2522activeTabId%2522%253A%2522clpexw61k0005356iwf8ndbjj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by myesn** [comment]
@black197 It works, thanks :).

**Comment by erickkarl** [comment]
> @myesn You can use `React.useMemo` to cache `classNames` object and prevent re-rendering. See [codesandbox](https://codesandbox.io/p/devbox/blissful-hopper-4ncjsr?file=%2FApp.jsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpexw61k0009356idpqe3eo4%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpexw61k0004356ib7soyoel%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpexw61k0006356ik77gj3g1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpexw61k0008356isbla0c9d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpexw61k0004356ib7soyoel%2522%253A%257B%2522id%2522%253A%2522clpexw61k0004356ib7soyoel%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clpeyp7ad007z356inq4ku2t1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpeyp7ad007z356inq4ku2t1%2522%257D%252C%2522clpexw61k0008356isbla0c9d%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpexw61k0007356iiv09fut4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpexw61k0008356isbla0c9d%2522%252C%2522activeTabId%2522%253A%2522clpexw61k0007356iiv09fut4%2522%257D%252C%2522clpexw61k0006356ik77gj3g1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpexw61k0005356iwf8ndbjj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clpexw61k0006356ik77gj3g1%2522%252C%2522activeTabId%2522%253A%2522clpexw61k0005356iwf8ndbjj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Thank you! should this be the normal behaviour?

**Comment by black197** [comment]
@erickkarl I think this is more like a bug.
