### ISSUE TITLE
[Feature Request] Bad TBT optimization

### ISSUE THREAD

**Issue by rharkor** [nextui-org/nextui#2020]
### Is your feature request related to a problem? Please describe.

I love the library itself, but it consideraly slow down websites perfomance and lighthouse score..

Based on the initial setup the TBT indicator is already down at 78% with 600ms of blocking time.

### Describe the solution you'd like

Maybe optimizing library import and usage. I don't really know.

### Describe alternatives you've considered

IDK

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/70844594/ab8ca976-66a5-4470-9717-70670c4ee4dd)

**Comment by jrgarciadev** [comment]
We use third-party libraries in our documentation, such as analytics and ads, that impact the performance of the docs (this is a common issue on almost all large sites). To conduct a real library test without these third-party elements, you can use the NextUI + Next.js templates: [App Router](https://github.com/nextui-org/next-app-template), [Pages Router](https://github.com/nextui-org/next-pages-template).

Here are the results I obtained using the app template site:
 
![CleanShot 2023-11-23 at 09 03 12](https://github.com/nextui-org/nextui/assets/30373425/599b1312-a7cf-4142-9be1-ce2697b4f097)

**Comment by rharkor** [comment]
Okay I investigated a little bit and I found that when you do the test with the SEO checked the performance score is completely different don't know why
![image](https://github.com/nextui-org/nextui/assets/70844594/fabc7a56-ad62-4ce7-b9c0-14c2b804602a)

Commands used:
```bash
npx create-next-app -e https://github.com/nextui-org/next-app-template
npm run build && npm run start
```
