### ISSUE TITLE
[BUG] - Tooltip

### ISSUE THREAD

**Issue by Hariharan10202** [nextui-org/nextui#2023]
### NextUI Version

2.2.9

### Describe the bug

When I hover the tooltip or popover and zoom the screen. It changes the position automatically. 

### Your Example Website or App

chrome and brave both (latest version)

### Steps to Reproduce the Bug or Issue

Click the component and zoom the screen using mouse

### Expected behavior

It should not change the position for reference refer prime react popover

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/81140030/a21d3b37-c82e-4797-93d9-5417c3e8c3b7

### Operating System Version

13.3.1 (22E261)

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Hariharan10202 this is an expected behaviour, you can disable it (not recommended) by using the `shouldFlip` property.


https://github.com/nextui-org/nextui/assets/30373425/2c85b13c-e3e2-470b-9b00-531eeb1c4ea1
