### ISSUE TITLE
Getting style issue in Next UI v2.2.9 with Next JS v13.5.6 (App Router) and Tailwind CSS v3.3.5

### ISSUE THREAD

**Issue by imRHB** [nextui-org/nextui#2026]
- I am currently working on a Next JS project and I am trying to add the Next UI table component. But, the `search` and `pagination` select components are not displaying properly due to broken styles. 

- I would appreciate suggestions on how to change the background color of the table component. I am interested in using different components from Next UI, and I would like to customize the colors using the default Tailwind CSS color palette as well as a few custom colors (_**which can be found in the `tailwind.config.js` file under theme > colors**_). 

If you have any references or examples to share, it would greatly help me to better understand the process.

**Here is my table preview and `tailwind.config.js` file preview**

![next-ui-table](https://github.com/nextui-org/nextui/assets/86858060/d1c3c7ad-81ce-4996-bbf2-3c0f1cea92dd)
![tailwind-config](https://github.com/nextui-org/nextui/assets/86858060/db284ed4-323f-4080-a859-9f0c80f58482)

**Comment by jrgarciadev** [comment]
Could you try running the same example using the Next.js App template? https://github.com/nextui-org/next-app-template

Regarding the Table custom styles, we have an example in the documentation https://nextui.org/docs/components/table#custom-styles

**Comment by imRHB** [comment]
The above template does not have the style issue that I mentioned. However, I have noticed the table heading and table data aren't aligned properly.

- `Next JS (next: v14.0.2)`
- `Next UI (@nextui-org/react: v^2.2.9)`
- `Tailwind CSS (tailwindcss: v3.3.5)`

![next-ui-table-up](https://github.com/nextui-org/nextui/assets/86858060/fde0bd37-23af-46ce-af94-7ed304cc8010)

**Comment by imRHB** [comment]
@jrgarciadev I've noticed that the style of every `Input` component is being broken on the versions I mentioned earlier. Do you have any suggestions or fixes for this issue?

Additionally, I've tried using the `Link` component, but it's causing the page to reload upon navigation. Could you please let me know if I've made any mistakes while implementing it?

**Comment by Simon-He95** [comment]
I think you should provide a minimal demo that can be reproduced so that we can troubleshoot the problem. Thank you.

**Comment by isaacdarcilla** [comment]
I got similar issue posted in discussion.

https://github.com/nextui-org/nextui/discussions/2058

**Comment by imRHB** [comment]
@Simon-He95 I'll provide you the demo ASAP

**Comment by imRHB** [comment]
@isaacdarcilla, perhaps you're using Next JS `v14.0.x`, but, I was using Next JS `v13.5.6`. Meantime, I checked `v14.0.2`, it worked fine. Check this https://github.com/nextui-org/nextui/issues/2026#issuecomment-1825658715

**Comment by isaacdarcilla** [comment]
> @isaacdarcilla, perhaps you're using Next JS `v14.0.x`, but, I was using Next JS `v13.5.6`. Check this [#2026 (comment)](https://github.com/nextui-org/nextui/issues/2026#issue-2008632103)
> 
> Meantime, I checked `v14.0.2`, and it worked fine except for minor alignment issues on the table. Check this [#2026 (comment)](https://github.com/nextui-org/nextui/issues/2026#issuecomment-1825658715)

Can you post your package.json file?

**Comment by imRHB** [comment]
`package.json`

```
{
  "name": "next-app-template",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@nextui-org/button": "2.0.26",
    "@nextui-org/code": "2.0.24",
    "@nextui-org/input": "2.1.16",
    "@nextui-org/kbd": "2.0.25",
    "@nextui-org/link": "2.0.26",
    "@nextui-org/navbar": "2.0.27",
    "@nextui-org/react": "^2.2.9",
    "@nextui-org/snippet": "2.0.30",
    "@nextui-org/switch": "2.0.25",
    "@nextui-org/system": "2.0.15",
    "@nextui-org/theme": "2.1.17",
    "@react-aria/ssr": "^3.8.0",
    "@react-aria/visually-hidden": "^3.8.6",
    "@types/node": "20.5.7",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.16",
    "clsx": "^2.0.0",
    "eslint": "8.48.0",
    "eslint-config-next": "14.0.2",
    "framer-motion": "^10.16.4",
    "intl-messageformat": "^10.5.0",
    "next": "14.0.2",
    "next-themes": "^0.2.1",
    "postcss": "8.4.31",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwind-variants": "^0.1.18",
    "tailwindcss": "3.3.5",
    "typescript": "5.0.4"
  }
}

```

**Comment by hamitaksln** [comment]
I got the same issue when I used pnpm. I switched it to yarn and it solved. When I checked node_modules with pnpm it doesn't have `./node_modules/@nextui-org/theme` folder so maybe tailwind doesn't work properly.

**Comment by imRHB** [comment]
@jrgarciadev @Simon-He95 

I found the source of the style issue that occurred when using the Next UI input component. The issue was caused by enabling the `@tailwindcss/forms` package on the `tailwind.config.js`.

**Have a look at my [nextjs-nextui-example-app](https://github.com/imRHB/nextjs-nextui-example-app/) repo**.

If you'd like to reproduce the issue, enable the `@tailwindcss/forms` plugin from `tailwind.config.js`.

_Please note that, disabling the `@tailwindcss/forms` plugin causing another issue (**screenshots attached below**)._

- `@tailwindcss/forms` plugin **ENABLED**
![image](https://github.com/nextui-org/nextui/assets/86858060/66cbea63-c87d-459e-826d-0fd34e887ded)

- `@tailwindcss/forms` plugin **DISABLED**
![image](https://github.com/nextui-org/nextui/assets/86858060/725d0456-81a9-42b9-adfe-c507a5804562)

**Comment by surya-ven** [comment]
> I got the same issue when I used pnpm. I switched it to yarn and it solved. When I checked node_modules with pnpm it doesn't have `./node_modules/@nextui-org/theme` folder so maybe tailwind doesn't work properly.

I use pnpm and faced the same issue but was able to resolve it by following this installation instruction in the docs:

<img width="690" alt="Screenshot 2023-12-26 at 5 42 09 pm" src="https://github.com/nextui-org/nextui/assets/84949099/ce3e5bfd-4212-4130-a9a9-7704ec4e5def">
