### ISSUE TITLE
[BUG] - React Hook form cant set default value with Select component 

### ISSUE THREAD

**Issue by knightvibhi** [nextui-org/nextui#2035]
### NextUI Version

2.2.9

### Describe the bug

Im trying to create a select input it will be prefiiled with value and user wont be able to change it.. on ui side it seems to work fine but as soon as you hit save button it throws an error saying input is require or it should have this value. im using react hook form and <Controller/> component to integrate it with next ui but its seems that its not working

```
<Controller
          control={control}
          name="modify_req.update_user_workspace.current_role"
          render={({ field, fieldState, formState }) => {
            field.value = currentUser.access_type;

            return (
              <Select
                {...field}
                isInvalid={fieldState.invalid}
                errorMessage={
                  formState.errors.modify_req?.update_user_workspace
                    ?.current_role?.message
                }
                label="Select Role"
                selectedKeys={new Set([currentUser.access_type])}
              >
                {userRoles.map(({ value, label }) => (
                  <SelectItem key={value} value={value}>
                    {label}
                  </SelectItem>
                ))}
              </Select>
            );
          }}
        />
```

### Steps to Reproduce the Bug or Issue

Here is sandbox link check yourself [CodeSandBox](https://codesandbox.io/p/devbox/blissful-engelbart-dqthm8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpdu2ouq000820677m7yk1ff%2522%252C%2522sizes%2522%253A%255B46.62192393736018%252C53.37807606263982%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpdu2ouq0003206777nvsr7p%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpdu2ouq00052067b6vvobkc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpdu2ouq00072067feuyz635%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpdu2ouq0003206777nvsr7p%2522%253A%257B%2522id%2522%253A%2522clpdu2ouq0003206777nvsr7p%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpdu2ouq00072067feuyz635%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpdu2ouq00062067cobwh7sh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpdu2ouq00072067feuyz635%2522%252C%2522activeTabId%2522%253A%2522clpdu2ouq00062067cobwh7sh%2522%257D%252C%2522clpdu2ouq00052067b6vvobkc%2522%253A%257B%2522id%2522%253A%2522clpdu2ouq00052067b6vvobkc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpdu2ouq000420673onbdzs3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpdu2ouq000420673onbdzs3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Expected behavior

It should pass the parser validation and should not show any warning to user 

### Operating System Version

Linux

### Browser

Firefox

**Comment by Simon-He95** [comment]
I think you should use `defaultSelectedKeys` to set the default value

**Comment by knightvibhi** [comment]
@Simon-He95  The problem was because i forgot to pass the register as a prop to select 
```
<Controller
                  control={control}
                  name="modify_req.update_user_workspace.current_role"
                  render={({ field, fieldState, formState }) => {
                    return (
                      <Select
                        {...field}
                        isInvalid={fieldState.invalid}
                        errorMessage={formState.errors.modify_req?.update_user_workspace?.current_role?.message}
                        label="Select Role"
                        selectedKeys={[currentUser.access_type]}
                        defaultSelectedKeys={[currentUser.access_type]}
                        {...register("modify_req.update_user_workspace.current_role")}
                      >
                        {userRoles.map(({ value, label }) => (
                          <SelectItem key={value} value={value}>
                            {label}
                          </SelectItem>
                        ))}
                      </Select>
                    );
                  }}
                />
```

**Comment by devDoubleH** [comment]
Hello everyone! I don't know why this code is not working:  <Select
                    value={waiter.active ? "Active" : "Inactive"}
                    defaultSelectedKeys={[
                      waiter.active ? "Active" : "Inactive",
                    ]}
                    items={waiterStatus}
                  >
                    {(item) => (
                      <SelectItem
                        key={item.id}
                        value={item.name}
                        onClick={() => {
                          setWaiter((prev: Waiter | null) => {
                            if (!prev) {
                              return null;
                            }

                            return {
                              ...prev,
                              active: item.id === 1 ? true : false,
                            };
                          });
                        }}
                      >
                        {item.name}
                      </SelectItem>
                    )}
                  </Select>

**Comment by pkvaygon** [comment]
```
export default function SelectLocationComponent() {
  const [value, setValue] = React.useState<any>(new Set([states[0].name]));
  return (
    <>
      <Select
        disallowEmptySelection
        items={states}
        className="max-w-xs"
        selectedKeys={value}
        defaultSelectedKeys={[states[0].name]}
        label="Pick a State"
        selectionMode="single"
        onSelectionChange={setValue}>
        {(state) => (
          <SelectItem key={state.name} textValue={state.name}>
            {state.name}
          </SelectItem>
        )}
      </Select>
      <span className="text-white">{value}</span>
    </>
  );
}
```
```
export const states = [
  { value: "all", name: "All States" },
 and 50 states obj 
]
```

**Comment by ngodacthien** [comment]
im try defaultSelectedKeys="clnouuldy0002fnpku4ujs907"

clnouuldy0002fnpku4ujs907 is field.value.
But it dont default of select item.
how to fix default value?

**Comment by VictorAJ01** [comment]
> im try defaultSelectedKeys="clnouuldy0002fnpku4ujs907"
> 
> clnouuldy0002fnpku4ujs907 is field.value. But it dont default of select item. how to fix default value?

Having similar issue

**Comment by pkvaygon** [comment]
> im try defaultSelectedKeys="clnouuldy0002fnpku4ujs907"
> 
> clnouuldy0002fnpku4ujs907 is field.value. But it dont default of select item. how to fix default value?
<Select
defaultSelectedKeys={"clnouuldy0002fnpku4ujs907"}
>
<SelectItem key="clnouuldy0002fnpku4ujs907">
...

**Comment by lewissmatos** [comment]
does someone know how to set a default value to a Select? I haven't been able

**Comment by vaxevanis** [comment]
For what I see the 'issue" occurs only when iterating items on uncontrolled components. Adding a textValue prop seems to solve this.

`<Select
        onChange={(e) => handleChange(e.target.value)}
        defaultSelectedKeys={[key ?? 'all']} // whatever your key logic is
        label="Order By"
        disallowEmptySelection
        selectionMode="single"
      >
        {items.map((item) => (
          <SelectItem value={item.key} key={item.key} textValue={item.name}>
            Order by {item.name}
          </SelectItem>
        ))}
      </Select>`

**Comment by iPanda007** [comment]
<Select
                  defaultSelectedKeys={[]}
                  label="Status"
                  className="w-full rounded-md"
                  onChange={e => {
                    setActive(e.target.value);
                  }}
                  options={[
                    { label: 'Active', value: 'true' },
                    { label: 'Inactive', value: 'false' },
                  ]}
    />
              )}
            />

**Comment by iPanda007** [comment]
please put defaultSelectedKeys with array  
<Select
                  defaultSelectedKeys={['true']}
                  label="Status"
                  className="w-full rounded-md"
                  onChange={e => {
                    setActive(e.target.value);
                  }}
                  options={[
                    { label: 'Active', value: 'true' },
                    { label: 'Inactive', value: 'false' },
                  ]}
                />
              )}
            />

**Comment by lewissmatos** [comment]
thanks

**Comment by AzizMenssi** [comment]
This how I manged to make it work .
Example :
   ```
       <Controller
            name="floors"
            control={control}
            render={({ field }) => (
              <div className="col-span-12">
                <Select
                  {...field}
                  placeholder="Floors"
                  selectedKeys={new Set([field.value])}
                  onSelectionChange={(keys) => {
                    const selectedValue = Array.from(keys).join("");
                    field.onChange(selectedValue);
                  }}
                >
                  <SelectItem
                    key="floorA"
                    value="Floor A"
                    className="text-black"
                  >
                    Floor A
                  </SelectItem>
                  <SelectItem
                    key="floorB"
                    value="Floor B"
                    className="text-black"
                  >
                    Floor B
                  </SelectItem>
                </Select>
              </div>
            )}
          />
```
Hope this helps .

**Comment by pablojsx** [comment]
Controlled, without Controller, to set the default value:

type TrackType = "GUITAR"

```const [value, setValue] = useState<Selection>(
    new Set<TrackType>(['GUITAR'])
  );
```

Then in the <Select component:
```
selectedKeys={rangeSelectValue}
onSelectionChange={setRangeSelectValue}
```


In my case, TrackType is a Prisma enum so I have more options, this is just an example.

**Comment by desta** [comment]
hello i fix with key as value, this my code with ObjectKeys, I haven't tried using array map 

```
<Select
            labelPlacement='outside'
            className="max-w-xs font-bold"
            color='primary'
            label="Homepage"
            placeholder="Homepage"
            variant="bordered"
            id="homepage"
            name="homepage"
            isRequired
            selectedKeys={[homepage]}
            onChange={(e) => setHomepage(e.target.value)}
          >
            {Object.keys(HomepageList).map((item) => (
              <SelectItem key={HomepageList[item].title}>
                {HomepageList[item].title}
              </SelectItem>
            ))}
          </Select>
```

**Comment by smartercow** [comment]
This works with for me.

```
export type CategoryObj = {
  id: number;
  name: string;
  value: DBCategory;
};

export const categoryOptions: CategoryObj[] = [
  { id: 1, name: "Agency", value: "agency" },
  { id: 2, name: "Art", value: "art" },
  { id: 3, name: "Beauty", value: "beauty" },
];

export const categoryValues = categoryOptions.map((v) => v.value) as [DBCategory, ...DBCategory[]];

export const infoSchema = z.object({
  // phone: z.string().optional(),
  category: z.enum(categoryValues).optional(),
});

  // categoryValues 
  const opts = values.map((item) => {
    return { id: item[0], value: item[0], label: item[0] };
  });

  // const { error, invalid, } = useFormField();

  const opts = values.map((item) => {
    return { id: item[0], value: item[0], label: item[0] };
  });

      <Select
            aria-label={label}
            // label={label}
            key={field.value}
            items={opts}
            selectedKeys={[field.value, field.value]}
            errorMessage={error?.message}
            isInvalid={invalid}
            onSelectionChange={(keys) => {
              const selectedValue = Array.from(keys).join("");
              field.onChange(selectedValue);
            }}
            defaultSelectedKeys={[field.value, field.value]}
            placeholder="Search or select from the list"
            variant="bordered"
            color="primary"
            showScrollIndicators
            autoFocus={false}
            listboxProps={{
              itemClasses: {
                base: "rounded-none py-3 px-6",
                title: "text-base font-bold",
              },
            }}
            classNames={{
              trigger: "h-14 data-[focus=true]:border-default-200 data-[hover=true]:border-primary",
              selectorIcon: "hidden",
              value: "text-base text-foreground",
              listbox: "app-listbox px-0 py-2",
              popoverContent: "p-0",
            }}
            // scrollShadowProps={{ isEnabled: false }}
          >
            {(opt) => (
              <SelectItem key={opt.id} textValue={opt.label} classNames={{ title: "text-base" }}>
                {opt.label}
              </SelectItem>
            )}
          </Select>
```
