### ISSUE TITLE
Rich Text Editor Component

### ISSUE THREAD

**Issue by sereneinserenade** [nextui-org/nextui#204]
**Is your component proposal related to a problem? Please describe.**
We have a text area right now, but no rich-text editor component.

**Describe the solution you'd like**
I am not the design guy. But there is https://tiptap.dev/ (based on prosemirror) that is supported in react

**Describe alternatives you've considered**
Have you considered iterating an existing component?
no

**Additional context**
https://mantine.dev/others/rte/ mantine has a rich text editor, they used QuillJS, I personally think Tiptap is better since it's very extensible and also supports rendering React comopnent inside editor.

If we decide to work on this, please assign this issue to me, I'd love to work on this, all I need is design for this. :-)

**Comment by jrgarciadev** [comment]
Hey @sereneinserenade could you please move this issue to the Discussions section? thanks 🙌🏻

**Comment by sereneinserenade** [comment]
Yes 👍
