### ISSUE TITLE
RTL support for select and labels

### ISSUE THREAD

**Issue by E-Naeim** [nextui-org/nextui#2042]
Please add RTL support for:
1- Select (as the direction of the arrow and the text is not aligned correctly).
- wrong alignment
![image](https://github.com/nextui-org/nextui/assets/88117732/e4cc5bcd-d336-4094-9fa6-bd7bd2d1e891)

- correct alignment (after applying logical class names of tailwind)
![image](https://github.com/nextui-org/nextui/assets/88117732/85d65cc9-159e-45e4-8816-1bab039b91e9)

2- Labels.. either select, inputs, autocomplete or any component has a label, the label is not aligned correctly.

![image](https://github.com/nextui-org/nextui/assets/88117732/d98c3019-f4ad-4f97-937d-ced028d75cd6)

_Originally posted by @E-Naeim in https://github.com/nextui-org/nextui/discussions/2004_

**Comment by aashahin** [comment]
RTL is still not supported by NextUI
