### ISSUE TITLE
[BUG] - Accordion

### ISSUE THREAD

**Issue by Farzane2630** [nextui-org/nextui#2045]
### NextUI Version

2.2.9

### Describe the bug

I`m tryinna use Accordion component in my react app but got this error:

> Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@nextui-org_react.js?v=7c9a3c67' does not provide an export named  'Accordion'.

I  copied and paste the exact code in the nextUI example. However other components which I`ve imported from nextUI are working totaly fine and without any problem. So I guess that might relate to a bug in this component.

### Steps to Reproduce the Bug or Issue

1. go to NextUI components > Accordion > [Splitted variant](https://nextui.org/docs/components/accordion#splitted-variant)
2. copy and paste the code in react app.
3. and then you encounter above mentioned error.

### Expected behavior

It should be displayed in the DOM without any error.

### Operating System Version

Windows

### Browser

Chrome

**Comment by Strapontin** [comment]
It's working for me on :
@nextui-org/react: ^2.2.9

Can you check your package.json and share your version ?

You could also try to delete your `node_modules `and redo an `npm i`

**Comment by Farzane2630** [comment]
Thanks for your help. I'll try.

Anthony ***@***.***> schrieb am So., 26. Nov. 2023, 14:26:

**Comment by ryo-manba** [comment]
Since this issue has been open for a while, I will close it. If the same error occurs, please feel free to reopen the issue.
