### ISSUE TITLE
[BUG] - Accordion with selectionMode="multiple" Input ctrl-a not working

### ISSUE THREAD

**Issue by eracoding-de** [nextui-org/nextui#2055]
### NextUI Version

2.2.9

### Describe the bug

If Accordion component is set to `selectionMode={"multiple"}` and you place an Input component inside as a Accordion Item, you cannot select entire text inside selected input by pressing ctrl-a / cmd-a to select all text inside this Input component. 

If mode is not set to `multiple`, ctrl-a / cmd-a work properly.

### Steps to Reproduce the Bug or Issue

Use this minimal component to reproduce the issue. 
1. Open one of the items
2. type in some text into input component
3. try to select all text by shortcut ctrl-a / cmd-a
4. text is not selected

```
export default function Example() {
    return (
        <Accordion variant={"splitted"} selectionMode={"multiple"}>
            <AccordionItem key={"1"} title={"1"}>
                <Input/>
            </AccordionItem>
            <AccordionItem key={"2"} title={"2"}>
                <Input/>
            </AccordionItem>
        </Accordion>
    )
}
```

### Expected behavior

Text is selectable by ctrl-a / cmd-a

### Operating System Version

macOS

### Browser

Chrome

**Comment by black197** [comment]
Here's a [workaround](https://codesandbox.io/p/devbox/nextui-2055-85n37c?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpi334t9000c3j6fjd3xc0hr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpi334t900033j6f2x1qa7ov%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpi334t900093j6fqdwzj0o8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpi334t9000b3j6ffso3rvs2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpi334t900033j6f2x1qa7ov%2522%253A%257B%2522id%2522%253A%2522clpi334t900033j6f2x1qa7ov%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpi3kzrd00033j6fxu9da9s5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpi3kzrd00033j6fxu9da9s5%2522%257D%252C%2522clpi334t9000b3j6ffso3rvs2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpi334t9000a3j6ftpegq6fw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpi334t9000b3j6ffso3rvs2%2522%252C%2522activeTabId%2522%253A%2522clpi334t9000a3j6ftpegq6fw%2522%257D%252C%2522clpi334t900093j6fqdwzj0o8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpi334t900043j6f8xtmyxkc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clpi334t900053j6f4ziih8gd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clpi334t900063j6f3l8cjyz5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clpi334t900073j6fu2mp7bnx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522lint%2522%257D%252C%257B%2522id%2522%253A%2522clpi334t900083j6f437a70og%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%257D%255D%252C%2522id%2522%253A%2522clpi334t900093j6fqdwzj0o8%2522%252C%2522activeTabId%2522%253A%2522clpi334t900043j6f8xtmyxkc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).
