### ISSUE TITLE
[BUG] - select Label placement is disturbed on error message when select labelPlacement is outside

### ISSUE THREAD

**Issue by SaadFarooq-Dev** [nextui-org/nextui#2057]
### NextUI Version

2.2.9

### Describe the bug

**Tested the code-snippet provided by NextUI on macOS (mac sonoma M1 pro)**
**Tested this on codesandbox provided by nextUI code snippet**

In the select component when we choose label placement to be outside and we pass the error message prop the label position gets disturbed/ distorted.
<img width="577" alt="image" src="https://github.com/nextui-org/nextui/assets/140374565/2c2d59d7-f88a-471a-8e09-e35ad08afbf2">

### Steps to Reproduce the Bug or Issue

Import select component
Pass the labelPlacement="outside"
Pass an error message -> errorMessage={isValid || !touched ? "" : "You must select a cat"}

```js
import React from "react";
import {Select, SelectItem} from "@nextui-org/react";
import {animals} from "./data";

export default function App() {
  const [value, setValue] = React.useState(new Set([]));
  const [touched, setTouched] = React.useState(false);

  const isValid = value.has("cat");

  return (
    <Select
      label="Favorite Animal"
      variant="bordered"
      placeholder="Select an animal"
      labelPlacement="outside"
      errorMessage={isValid || !touched ? "" : "You must select a cat"}
      isInvalid={isValid || !touched ? false : true}
      selectedKeys={value}
      className="max-w-xs"
      onSelectionChange={setValue}
      onClose={() => setTouched(true)}
    >
      {animals.map((animal) => (
        <SelectItem key={animal.value} value={animal.value}>
          {animal.label}
        </SelectItem>
      ))}
    </Select>
  );
}

```

### Expected behavior

The expected behavior should be that the label placement should not be disturbed when the error message is shown in the select component

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/89783597/5fdc54db-a857-4fc3-964a-bb6881d98099

### Operating System Version

macOS

### Browser

Chrome

**Comment by SaadFarooq-Dev** [comment]
CFBR

**Comment by black197** [comment]
This happens when using `labelPlacement="outside"`,  `errorMessage` (or `description`) and `placeholder` together. Working on it.

**Comment by srivatsa17** [comment]
Even i am facing the same issue.

**Comment by 5war00p** [comment]
+1

**Comment by 5war00p** [comment]
If you guys wanted temporary solution, you can do this:

**Comment by 5war00p** [comment]
> i am also facing the same issue, is there any solution ?

Try this for now, adjust spacing like this: https://github.com/nextui-org/nextui/issues/2057#issuecomment-1912213216

**Comment by 5war00p** [comment]
You can create a code sandbox, so that I can look into it.

**Comment by wingkwong** [comment]
No longer reproducible in latest version

![image](https://github.com/user-attachments/assets/dda13868-f4ca-4532-b525-8f9c78e3312f)
