### ISSUE TITLE
[BUG] - Input BUG!

### ISSUE THREAD

**Issue by stone89son** [nextui-org/nextui#2064]
### NextUI Version

lastest

### Describe the bug

https://codesandbox.io/p/devbox/nextui-2006-forked-c6q2yy?file=%2Fapp%2Fpage.jsx%3A30%2C11

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/p/devbox/nextui-2006-forked-c6q2yy?file=%2Fapp%2Fpage.jsx%3A30%2C11

### Expected behavior

https://codesandbox.io/p/devbox/nextui-2006-forked-c6q2yy?file=%2Fapp%2Fpage.jsx%3A30%2C11

### Screenshots or Videos

https://codesandbox.io/p/devbox/nextui-2006-forked-c6q2yy?file=%2Fapp%2Fpage.jsx%3A30%2C11

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by wingkwong** [comment]
Closing - No longer applicable
