### ISSUE TITLE
[BUG] - Input loses focus on endContent change from null to non-null

### ISSUE THREAD

**Issue by luixo** [nextui-org/nextui#2069]
### NextUI Version

2.2.9

### Describe the bug

Hello,
When changing `endContent` of `Input` component from null to non-null via value change, input loses focus.

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-vvcbkq

### Steps to Reproduce the Bug or Issue

1. Add an input with `endContent` dependent on input `value`.
2. Change value in a way that `endContent` becomes non-null after being null.

### Expected behavior

Expected not to lose focus in this case.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by black197** [comment]
Working on it :)
