### ISSUE TITLE
[BUG] - Hydration failed because the initial UI does not match what was rendered on the server

### ISSUE THREAD

**Issue by Rimberse** [nextui-org/nextui#2073]
### NextUI Version

2.2.9

### Describe the bug

Hello,

Upon trying to use the card component's `isPressable` property within Next.js i get this error:
https://nextui.org/docs/components/card#primary-action

The card itself renders fine without this property. If I am understanding correctly the issue is that `<Card />` converts to `<Button />` during rendering and considering that it has nested `<div>` elements within it triggers this error. Is there a way to avoid it? What's the fix?

### Your Example Website or App

http://localhost:3000

### Steps to Reproduce the Bug or Issue

1. Set up Next.js project
2. Run it: `npm run dev`
3. Create a component
4. Use Next-UI card with `isPressable` property
5. Observe the bug

### Expected behavior

The card component should render without issues. `isPressable` property should not cause any console errors on runtime.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/56799896/5ffa5c0a-7b07-45bc-b08c-6021791a52ac)

### Operating System Version

Windows

### Browser

Chrome

**Comment by black197** [comment]
works fine in [codesandbox](https://codesandbox.io/p/devbox/nifty-almeida-lpjx4f?file=%2Fapp%2Fpage.jsx%3A6%2C17&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpm0ve60000b3j6gqixu80qc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpm0ve5z00023j6gs56vfll5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpm0ve5z00083j6gqykoiad6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpm0ve5z000a3j6g2a69zzl8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpm0ve5z00023j6gs56vfll5%2522%253A%257B%2522id%2522%253A%2522clpm0ve5z00023j6gs56vfll5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpm0y4yl00023j6ft1b4v825%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A17%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpm0y4yl00023j6ft1b4v825%2522%257D%252C%2522clpm0ve5z000a3j6g2a69zzl8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpm0ve5z00093j6gsa65l2lu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpm0ve5z000a3j6g2a69zzl8%2522%252C%2522activeTabId%2522%253A%2522clpm0ve5z00093j6gsa65l2lu%2522%257D%252C%2522clpm0ve5z00083j6gqykoiad6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpm0ve5z00033j6gzrswoips%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clpm0ve5z00043j6gf0c7f3xy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clpm0ve5z00053j6g7rre9czc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clpm0ve5z00063j6ggfi4kg3d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522lint%2522%257D%252C%257B%2522id%2522%253A%2522clpm0ve5z00073j6g2tlon7yy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%257D%255D%252C%2522id%2522%253A%2522clpm0ve5z00083j6gqykoiad6%2522%252C%2522activeTabId%2522%253A%2522clpm0ve5z00033j6gzrswoips%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by aaronhawkey** [comment]
Here is my creation of the issue [Codesandbox](https://codesandbox.io/p/devbox/nextui-2073-forked-m4hlhh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqcu9oxl0005356it9prex7f%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqcu9oxl0002356iln0acrps%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqcu9oxl0003356ia18zh5mt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqcu9oxl0004356iek2bp6ab%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B53.25631741287813%252C46.74368258712187%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqcu9oxl0002356iln0acrps%2522%253A%257B%2522id%2522%253A%2522clqcu9oxl0002356iln0acrps%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqcu9oxl0004356iek2bp6ab%2522%253A%257B%2522id%2522%253A%2522clqcu9oxl0004356iek2bp6ab%2522%252C%2522activeTabId%2522%253A%2522clqcubvwu004l356id86qtltp%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqcubvwu004l356id86qtltp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqcutfkl01go356iksmp87di%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clqcu9oxl0003356ia18zh5mt%2522%253A%257B%2522id%2522%253A%2522clqcu9oxl0003356ia18zh5mt%2522%252C%2522activeTabId%2522%253A%2522clqcubr0d003l356idcxaj1qw%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqcubr0d003l356idcxaj1qw%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by aaronhawkey** [comment]
Here is my recreation of this issue: [Codesandbox](https://codesandbox.io/p/devbox/nextui-2073-forked-wrl6hq)
When you refresh the page, hydration error occurs.

**Comment by warloff** [comment]
+1

**Comment by MJChimal** [comment]
+1

**Comment by wingkwong** [comment]
@aaronhawkey can you try the following

```ts
// app/providers.tsx
"use client";

import { useEffect, useState } from "react";
import { NextUIProvider } from "@nextui-org/react";

export function Providers({ children }) {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <NextUIProvider>{children}</NextUIProvider> : <></>;
}
```

**Comment by Alenriquez96** [comment]
I had this exact problem. My problem was that I had a` <Button/> `inside a `<Card/>` with `isPressable` property, and as you said, that was like having a button inside a button. I removed the property and its working fine.

**Comment by aaronhawkey** [comment]
This fixed my hydration issue:
https://github.com/nextui-org/nextui/issues/2073#issuecomment-1953728672

**Comment by favourwright** [comment]
> This fixed my hydration issue: [#2073 (comment)](https://github.com/nextui-org/nextui/issues/2073#issuecomment-1953728672)

it fixes it but useEffects run 4 times in dev instead of 2,
so I believe it would run 2x in prod

doesn't seen like an optimal solution

**Comment by favourwright** [comment]
> @aaronhawkey can you try the following
> 
> ```ts
> // app/providers.tsx
> "use client";
> 
> import { useEffect, useState } from "react";
> import { NextUIProvider } from "@nextui-org/react";
> 
> export function Providers({ children }) {
>   const [isClient, setIsClient] = useState(false);
>   useEffect(() => {
>     setIsClient(true);
>   }, []);
>   return isClient ? <NextUIProvider>{children}</NextUIProvider> : <></>;
> }
> ```

for me on using this method, nothing renders but a black page and errors on console.
```
// app/providers.tsx
"use client";

import { useEffect, useState } from "react";
import { NextUIProvider } from "@nextui-org/react";

export function Providers({ children }) {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <NextUIProvider>{children}</NextUIProvider> : {children};
}
```

the above works but then useEffects are called multiple times(which is expected) because components are mounted and remounted when isClient becomes true

**Comment by favourwright** [comment]
😁 just realized it didn't work for me because I had the following structure
```
<Provider>
  <body></body>
</Provider>
```

all my providers are in `<Provider>` so by doing `return isClient ? <NextUIProvider>{children}</NextUIProvider> : <></>;` inside my provider, it meant my entire document didn't have a `body` tag at some point.

rearranging stuff like this, fixed it
```
<body>
  <Provider>
  </Provider>
</body>
```

**Comment by arbile26** [comment]
> ```ts
>  <></>;
> ```

You saved me hours of searching. Thanks You!

**Comment by AriaFantom** [comment]
> > ```ts
> >  <></>;
> > ```
> 
> You saved me hours of searching. Thank You!

What do you mean how to use react fragements and where?
