### ISSUE TITLE
[BUG] - selectedKey prop throwing errors when assignment is done in autocomplete component

### ISSUE THREAD

**Issue by srivatsa17** [nextui-org/nextui#2075]
### NextUI Version

2.2.9

### Describe the bug

I am trying to use the same code as in example provided for autocomplete component in https://nextui.org/docs/components/autocomplete#fully-controlled.
```
type FieldState = {
    selectedKey: React.Key | null;
    inputValue: string;
    items: typeof users;
};

return (
  <Autocomplete
      className="max-w-xs"
      inputValue={fieldState.inputValue}
      items={fieldState.items}
      label="Favorite Animal"
      placeholder="Search an animal"
      selectedKey={fieldState.selectedKey}
      variant="bordered"
      onInputChange={onInputChange}
      onOpenChange={onOpenChange}
      onSelectionChange={onSelectionChange}
  >
      {(item) => <AutocompleteItem key={item.value}>{item.label}</AutocompleteItem>}
  </Autocomplete>
);

```
I am getting an error message on the selected prop `Type 'Key | null' is not assignable to type 'Key | null | undefined'.
  Type 'bigint' is not assignable to type 'Key | null | undefined'.ts(2322)
selection.d.ts(19, 3): The expected type comes from property 'selectedKey' which is declared here on type 'IntrinsicAttributes & Props<{ label: string; value: string; description: string; }> & { ref?: Ref<HTMLElement> | undefined; }'`

### Steps to Reproduce the Bug or Issue

1. Replicate this example https://nextui.org/docs/components/autocomplete#fully-controlled

### Expected behavior

Component should not be throwing error against selectedKey prop

### Operating System Version

macOS

### Browser

Firefox

**Comment by jrgarciadev** [comment]
Duplicated #2182
