### ISSUE TITLE
[BUG] - Radio-group

### ISSUE THREAD

**Issue by BrunoDeye** [nextui-org/nextui#2081]
### NextUI Version

2.2.9

### Describe the bug

The props type of the RadioGroup component is missing the "isRequired" prop. Using the prop works just fine but we doesnt have any intelisense for it and the typescript says that the prop doesnt exist on type 'IntrinsicAttributes & MergeWithAs<Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref">, Omit<...>, RadioGroupProps, "div">'. 

### Steps to Reproduce the Bug or Issue

Use the RadioGroup component with the isRequired prop

### Expected behavior

No Typescript errors and intelisense for it

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/141923197/8e855e55-9d6c-47e6-8bb9-79a0f364660f)
![image](https://github.com/nextui-org/nextui/assets/141923197/a368be05-8a2a-4657-a50e-f2ba9a8f199e)

as you can see the prop works just fine:
![image](https://github.com/nextui-org/nextui/assets/141923197/9ab10ab8-ab04-469a-b760-dbe57d2b3725)

### Operating System Version

windows 11

### Browser

Chrome

**Comment by ryo-manba** [comment]
It appears that this issue has been fixed in v2.4.0, so I will close this issue. If the same error occurs with the latest version, please feel free to reopen the issue.
