### ISSUE TITLE
[BUG] - Autocomplete popover not closing in modal

### ISSUE THREAD

**Issue by Nichtmetall** [nextui-org/nextui#2082]
### NextUI Version

2.2.9

### Describe the bug

When I add the new autocomplete component to a modal, the popover with the autocomplete items can no longer be closed. Neither when I press outside the autocomplete, nor when I press on the chevron icon to expand and collapse. This behavior only occurs if no key has been selected.

### Your Example Website or App

https://codesandbox.io/p/devbox/async-rain-dgrkwh?file=%2FApp.jsx&utm_medium=sandpack

### Steps to Reproduce the Bug or Issue

1. Implement autocomplete in modal
2. Open modal
3. Open autocomplete popover
4. Try to close the autocomplete

### Expected behavior

The popover is closing.

### Operating System Version

macOS

### Browser

Chrome

**Comment by MarcoRodasW** [comment]
I have the same issue

**Comment by sbc640964** [comment]
I have the same issue

**Comment by ThomasDeleflie** [comment]
Same here ;)

**Comment by black197** [comment]
seems like duplicate of #1987

**Comment by VerioN1** [comment]
also have this issue, will it be solved in 2.3.0?

**Comment by gitRacoon** [comment]
I have same but this comment helped in my case: https://github.com/nextui-org/nextui/issues/1987#issuecomment-1817335810
