### ISSUE TITLE
[BUG] - DropDownMenu not supporting items to spread across grid columns 

### ISSUE THREAD

**Issue by srivatsa17** [nextui-org/nextui#2091]
### NextUI Version

2.2.9

### Describe the bug

I want to basically create a mega menu by spreading dropdown menu items column wise upto a certain height and wrap the next set of items in the next column and so on. I tried this by doing the below code but still the items span only through a single column.
```
<DropdownMenu
    aria-label="Menu"
    className="grid grid-cols-2 w-[400px] gap-3 text-center"
    itemClasses={{
        base: "gap-4"
    }}
    as="div"
>
    <DropdownItem as="div">T-shirt1</DropdownItem>
    <DropdownItem as="div">T-shirt2</DropdownItem>
</DropdownMenu>
```

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

I want dropdown menu items to spread column wise upto a certain height and wrap the next set of items in the next column and so on..

### Screenshots or Videos

<img width="417" alt="image" src="https://github.com/nextui-org/nextui/assets/52497355/15bf6e95-1d79-4ba7-8157-48fc42ecc49d">

### Operating System Version

macOS

### Browser

Firefox

**Comment by srivatsa17** [comment]
> You can pass `className` to the menu list through slots. Try this:
> 
> ```js
> <DropdownMenu
>     aria-label="Menu"
>     classNames={{list: "grid grid-cols-2 w-[400px] gap-3 text-center"}} // slots
>     itemClasses={{
>         base: "gap-4"
>     }}
>     as="div"
> >
>     <DropdownItem as="div">T-shirt1</DropdownItem>
>     <DropdownItem as="div">T-shirt2</DropdownItem>
> </DropdownMenu>
> ```
> 
> [example](https://codesandbox.io/p/devbox/serene-jang-q6432z?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpqire4k00063j6grlv9hnvh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpqire4k00023j6gh18aj82o%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpqire4k00043j6gj9bbnhi0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpqire4k00053j6g2brye0i6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpqire4k00023j6gh18aj82o%2522%253A%257B%2522id%2522%253A%2522clpqire4k00023j6gh18aj82o%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpqire4k00053j6g2brye0i6%2522%253A%257B%2522id%2522%253A%2522clpqire4k00053j6g2brye0i6%2522%252C%2522activeTabId%2522%253A%2522clpqitu2x00gg3j6g3tkalgoo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clpqitu2x00gg3j6g3tkalgoo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clpqire4k00043j6gj9bbnhi0%2522%253A%257B%2522id%2522%253A%2522clpqire4k00043j6gj9bbnhi0%2522%252C%2522activeTabId%2522%253A%2522clpqitnya00eu3j6gh15i0cm3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpqire4k00033j6gy7irpukg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clpqirdvy0004eddg9zla0htg%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clpqitnya00eu3j6gh15i0cm3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Wow, that worked well for me. Thanks a lot for the help. Will close the issue.

**Comment by vitalijalbu** [comment]
Hi guys, I also want to build a responsive **megamenu**. Anyone can help? Thanks.
