### ISSUE TITLE
[BUG] - Ghost button stayed at hovered state after click on mobile devices

### ISSUE THREAD

**Issue by dbogdanov-a** [nextui-org/nextui#2095]
### NextUI Version

latest

### Describe the bug

The ghost button stayed hovered state after clicking on mobile devices https://nextui.org/docs/components/button
The ghost

### Steps to Reproduce the Bug or Issue

1. On mobile device click the ghost button
2. Hoved state applied
3. and you have to click outside to remove the hover

### Expected behavior

After clicking hover state removed

### Operating System Version

mobile

### Browser

Other (add additonal context)

**Comment by black197** [comment]
`colorVariants.ghost` in package @nextui-org/theme uses pseudo-class hover. trying to fix it.
