### ISSUE TITLE
[BUG] - Slider is not exported from next/theme

### ISSUE THREAD

**Issue by pawitpr** [nextui-org/nextui#2096]
### NextUI Version

2.2.9

### Describe the bug

The error ``./node_modules/.pnpm/@nextui-org+slider@2.2.5_@nextui-org+system@2.0.7_@nextui-org+theme@2.1.6_framer-motion@10.16_xdyk3dbkhqfxzwrelqpfukkduq/node_modules/@nextui-org/slider/dist/chunk-GZG547QZ.mjs
Attempted import error: 'slider' is not exported from '@nextui-org/theme' (imported as 'slider').``

The code `import {Slider} from "@nextui-org/slider";`

Thank you!

### Your Example Website or App

private

### Steps to Reproduce the Bug or Issue

not provided

### Expected behavior

next/theme have a problem with the slider

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/123424956/fb9470ad-de72-4908-b079-e27de88abc23

### Operating System Version

Window

### Browser

Chrome

**Comment by pawitpr** [comment]
i'll trying to update the @nextui/theme

**Comment by stuncs69** [comment]
I'm having the same issue.

**Comment by pawitpr** [comment]
> I'm having the same issue.

use the lower version, change the nextui/theme to 2.1.16
