### ISSUE TITLE
[DOCS] -  Wrong import of Button component in nextjs docs

### ISSUE THREAD

**Issue by harshmangalam** [nextui-org/nextui#2098]
### NextUI Version

2.2.9

### Describe the bug

Imported Button component from `@nextui-org/button` instead of `@nextui-org/react` in nextjs installation docs

### Steps to Reproduce the Bug or Issue

https://nextui.org/docs/frameworks/nextjs

### Expected behavior

```
import {Button} from '@nextui-org/react'
```

### Operating System Version

macOS

### Browser

Chrome

**Comment by alexbmills5** [comment]
![image](https://github.com/nextui-org/nextui/assets/128627893/6ec4be3c-b6bd-4a14-b2c6-a04ccb5c6605)
