### ISSUE TITLE
[BUG] - Button as Link with variant="ghost" doesn't have a border

### ISSUE THREAD

**Issue by dbogdanov-a** [nextui-org/nextui#2106]
### NextUI Version

2.2.9

### Describe the bug

I created the [Polymorphic Component](https://nextui.org/docs/components/link#polymorphic-component) with variant="ghost" and this button doesn't have a border

### Steps to Reproduce the Bug or Issue

Check it

### Expected behavior

This button have a border like a variant="ghost"has

### Screenshots or Videos

-

### Operating System Version

all

### Browser

Chrome

**Comment by black197** [comment]
![image](https://github.com/nextui-org/nextui/assets/23304975/1c971626-3cf8-4b78-a6f3-a0788fb8bd88)
looks fine with the same NextUI version. here's my code:

```javascript
<div className="w-[200px] p-4 flex flex-col gap-2">
  <Button
    href="https://github.com/nextui-org/nextui"
    as={Link}
    color="primary"
    showAnchorIcon
    variant="ghost"
  >
    Button Link
  </Button>
</div>
```

simply just the official demo with `variant="ghost"` and a wrapper
