### ISSUE TITLE
[BUG] - Documentation of Accordion slots wrong

### ISSUE THREAD

**Issue by TomFreudenberg** [nextui-org/nextui#2107]
### NextUI Version

latest

### Describe the bug

The documentation of [Custom Accordion Styles](https://nextui.org/docs/components/accordion#custom-accordion-styles) refers to the name `itemStyles` for adding styles to the slots down. But as in code expample this is called **`itemClasses`**

In addition I have not found something to use `classNames`. Maybe thats a not existing pprop there?

Neither:

```
<Accordion classNames="my-class" ...
```

nor

```
<Accordion classNames={{ title: "my-class" }} ...
```

pushes something down to items.

### Steps to Reproduce the Bug or Issue

Just follow the documentation

### Expected behavior

Valid documentation 

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
`classNames` is used in `AccordionItem` if you want to modify each accordion item styles separately. If you wish to modify all accordion items styles at once, then you should use `itemClasses` in `Accordion`.
