### ISSUE TITLE
[BUG] - Table

### ISSUE THREAD

**Issue by kenmoh** [nextui-org/nextui#2117]
### NextUI Version

2.2.9

### Describe the bug

I don't know if it's bug or I'm not doing it the right way. I keep getting this error in NextJS 14
 **Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".
  <... columns={[...]} children={function}>**

### Steps to Reproduce the Bug or Issue

Using the example on NextUI docs

### Expected behavior

To display a table of users

### Operating System Version

Linux

### Browser

Chrome

**Comment by black197** [comment]
It's a problem about Client Component and Server Component. `Table` is Client Component and if you want to pass function to it, you may have to wrap it and the function together with another Client Component. For example:

```javascript
function ServerComponent() {
  return <ClientComponent />
}
```

```javascript
'use client';

function ClientComponent() {
  const myFunc = ()=>{};
  return <Table columns={[...]} children={myFunc}>
}
```

**Comment by kenmoh** [comment]
Oh thank you very much. It worked. Thanks for the explanations
