### ISSUE TITLE
Nesting `<Button />` inside `<Tooltip />` changes button width

### ISSUE THREAD

**Issue by erenkulaksiz** [nextui-org/nextui#212]
**Is your iteration request related to a problem?**
I have a grid of buttons nested like this.
```javascript
<Grid.Container gap={1}>
    <Grid xs={3} sm={1} md={0.8} css={{ minHeight: 80, minWidth: 60, /*padding:0*/ }} alignItems="center">
        <Tooltip content="Add to favorites">
            <Button css={{ bg: "$primary", minWidth: 60, height: "80%", width: "100%" }} size="sm" onClick={() => handle.starWorkspace()}>
                {props.workspace?.data?.starred ? <StarFilledIcon style={{ fill: "#dbb700" }} /> : <StarOutlineIcon fill={"currentColor"} />}
            </Button>
        </Tooltip>
    </Grid>
    <Grid xs={3} sm={1} md={0.8} css={{ minHeight: 80, minWidth: 60, /*padding:0*/ }} alignItems="center">
        <Button css={{ bg: "$primary", minWidth: 60, height: "80%", width: "100%" }} style={{ minWidth: 60, width: "100%", height: "80%" }}>
            <VisibleIcon height={20} width={20} fill={"currentColor"} />
        </Button>
    </Grid>
    <Grid xs={3} sm={1} md={0.8} css={{ minHeight: 80, minWidth: 60, /*padding:0*/ }} alignItems="center">
        <Button css={{ bg: "$primary", minWidth: 60, height: "80%", width: "100%" }} style={{ minWidth: 60, width: "100%", height: "80%" }} onClick={() => setDeleteWorkspaceModalVisible(true)}>
            <DeleteIcon fill={"currentColor"} />
        </Button>
    </Grid>
    <Grid xs={3} sm={1} md={0.8} css={{ minHeight: 80, minWidth: 60, /*padding:0*/ }} alignItems="center">
        <Button css={{ bg: "$primary", minWidth: 60, height: "80%", width: "100%" }} style={{ minWidth: 60, width: "100%", height: "80%" }}>
            <AddIcon fill={"currentColor"} />
        </Button>
    </Grid>
</Grid.Container>
```
When i add tooltip to first button, it wont use 100% width of its parent. I've tried giving styles, even to tooltip itself, but it wont work.

**Describe the solution you'd like**
The container created by `<Tooltip />` should use 100% width, or flex: 1.

**Additional context**
![https://i.imgur.com/za3gjg5.png](https://i.imgur.com/za3gjg5.png)

**Comment by erenkulaksiz** [comment]
Also if i remove the minWidth styling from tooltip nested button, it looks like this 😄 
![[alt text](https://i.imgur.com/kAtShst.png)](https://i.imgur.com/kAtShst.png)

**Comment by andrew3009** [comment]
Hi,
Please see styling suggestion below to get the tooltip button the same size as the rest of the buttons.

When using the tooltip component, the tooltip needs its height and width set to be your desired size and then you need to set the height and width of the button to fill out the tooltip container using the css prop as by default Button is set to size medium. That is why without the width in the css it was so big.

See https://nextui.org/docs/components/button#button-props.

`<Tooltip
    content="Add to favorites"
    style={{ width: '100%', height: '80%' }}
 >
    <Button
        icon={props.workspace?.data?.starred ? <StarFilledIcon style={{ fill: "#dbb700" }} /> : <StarOutlineIcon fill={"currentColor"} />}
        css={{ bg: "$primary", minWidth: 60, height: "100%", width: "100%" }}
	onClick={() => handle.starWorkspace()}
    />
</Tooltip>`

**Comment by erenkulaksiz** [comment]
> Hi, Please see styling suggestion below to get the tooltip button the same size as the rest of the buttons.
> 
> When using the tooltip component, the tooltip needs its height and width set to be your desired size and then you need to set the height and width of the button to fill out the tooltip container using the css prop as by default Button is set to size medium. That is why without the width in the css it was so big.
> 
> See https://nextui.org/docs/components/button#button-props.
> 
> ```
> <Tooltip
>     content="Add to favorites"
>     style={{ width: '100%', height: '80%' }}
> >
>     <Button
>         icon={props.workspace?.data?.starred ? <StarFilledIcon style={{ fill: "#dbb700" }} /> : <StarOutlineIcon fill={"currentColor"} />}
>         css={{ bg: "$primary", minWidth: 60, height: "100%", width: "100%" }}
>         onClick={() => handle.starWorkspace()}
>     />
> </Tooltip>
> ```

Hey andrew 🙌
I don't think this is an button width issue. When you add tooltip to a button, if its a grid element then width becomes to button's default width even if i did typed `css={{width: "100%"}}`
I'm currently trying to fix this issue.

![[alt text](https://i.imgur.com/8gbDGI2.png)](https://i.imgur.com/8gbDGI2.png)

**Comment by andrew3009** [comment]
@erenkulaksiz It's because the Button is now wrapped in the Tooltip component. So your Button still needs the ``width: 100%`` to fill the Tooltip it's wrapped in and then Tooltip needs ``width: 100%`` to fill the Grid it's wrapped it after that it should match the other button that isn't wrapped in the Tooltip.

I agree it's could be considered an issue with the Tooltip as you think of the tooltip as the box that appears above the element you wrapped it in but on the other hand, the user has just wrapped an element in an element so it's also technically working correctly.

**Comment by jrgarciadev** [comment]
Hey @erenkulaksiz I've noticed some issues with your implementation, try to avoid using hardcoded `width/height` when you use the `Grid` component on the other hand you are using an `sm` button in the first `Grid` which render a smaller `Button`, I recommend you to avoid is using inline styles since they are not supported by the `SSR`, here's a fixed implementation https://codesandbox.io/s/nextui-tooltip-grid-button-774ev?file=/src/App.js, you could also use `Row` and `Col` here's an example -> https://nextui.org/docs/layout/container#auto-layout-columns

Hope it helps you! 🙌🏻

**Comment by erenkulaksiz** [comment]
Its all fixed now!
But i dont think having minWidth fixed on button sizes like 'md' 'xl' is really good thing. Maybe user is going to put only icon inside 'lg' sized button but you give something like 90 pixel minimum width which is unneccesary, user needs to edit css manually in this case.

My final code if anyone interested:
```javascript
<Grid xs={7} sm={4} justify="flex-end">
    <WorkspaceLoading loading={loading} />
    <Grid.Container justify='flex-end' gap={0.4} css={{ pb: 0 }}>
        <Grid>
            <Tooltip
                content={starred == true ? "Remove from favorites" : "Add to favorites"}
                css={{ pointerEvents: "none" }}
            >
                <Button css={{ bg: "$gradient", height: 60 }} onClick={onFavClick}>
                    {starred ? <StarFilledIcon style={{ fill: "#dbb700" }} /> : <StarOutlineIcon fill={"currentColor"} />}
                </Button>
            </Tooltip>
        </Grid>
        <Grid>
            <Tooltip
                content="Change visibility"
                css={{ pointerEvents: "none" }}
            >
                <Button css={{ bg: "$gradient", height: 60 }} auto onClick={onVisibleClick}>
                    {visible ? <VisibleIcon width={18} fill={"currentColor"} /> : <VisibleOffIcon width={18} fill={"currentColor"} />}
                </Button>
            </Tooltip>
        </Grid>
        <Grid>
            <Tooltip
                content="Delete"
                css={{ pointerEvents: "none" }}
            >
                <Button css={{ bg: "$gradient", height: 60 }} onClick={onDeleteClick}>
                    <DeleteIcon size={24} fill={"currentColor"} />
                </Button>
            </Tooltip>
        </Grid>
    </Grid.Container>
</Grid>
```
