### ISSUE TITLE
[BUG] - Autocomplete dose not support IME

### ISSUE THREAD

**Issue by XNCOAISN** [nextui-org/nextui#2121]
### NextUI Version

2.2.9

### Describe the bug

When I select a choice from the IME, the input is confirmed.

With this bug, Japanese, Chinese and Korean users would not be able to use Autocomplete.

I don't know the exact cause, but it may be the same cause as this problem.
https://github.com/mantinedev/mantine/issues/1565

### Your Example Website or App

https://nextui.org/docs/components/autocomplete

### Steps to Reproduce the Bug or Issue

https://github.com/nextui-org/nextui/assets/39142826/e8c37a72-45e0-4810-b851-b2c074ac6616

Select "Cat"
Remove "at"
Enter "猫"
Deleted parts will be restored when you confirm the conversion.

### Expected behavior

I don't want to change the value when converting

In the video example, when converting to "猫", you want to convert it to "C猫" instead of "Cat猫"

### Operating System Version

macOS

### Browser

Chrome

**Comment by ryo-manba** [comment]
Hi @XNCOAISN ,

Using the `allowsCustomValue` prop should resolve this issue. Please try it out!
https://nextui.org/docs/components/autocomplete#custom-value

https://github.com/nextui-org/nextui/assets/76232929/1cfa8e08-7174-4cc3-b224-dfe7ec1b8c42

**Comment by wingkwong** [comment]
Covered in canary & will be available in 2.6.0.
