### ISSUE TITLE
[BUG] - Listbox Type error when used with Typescript (works for Javascript) `Type error: Type 'Dispatch<SetStateAction<Set<string>>>' is not assignable to type '(keys: Selection) => any'`

### ISSUE THREAD

**Issue by kazuma-aniflex** [nextui-org/nextui#2123]
### NextUI Version

2.2.9

### Describe the bug

Type error: Type 'Dispatch<SetStateAction<Set<string>>>' is not assignable to type '(keys: Selection) => any'.
  Types of parameters 'value' and 'keys' are incompatible.
    Type 'Selection' is not assignable to type 'SetStateAction<Set<string>>'.
      Type 'string' is not assignable to type 'SetStateAction<Set<string>>'.

  394 |                 selectionMode="single"
  395 |                 selectedKeys={selectedQuality}
> 396 |                 onSelectionChange={setSelectedQuality}
      |                 ^
  397 |               >
  398 |
  399 |                 <ListboxItem onClick={() => (setIsSettingsOpen(false), setSettingsItems(false))} key="Auto">Auto</ListboxItem>
![Picsart_23-12-11_12-18-31-353](https://github.com/nextui-org/nextui/assets/145659895/579eb81e-54da-4366-a26f-c593fcb72561)
![Picsart_23-12-11_12-22-58-805](https://github.com/nextui-org/nextui/assets/145659895/8994d92c-a87f-41f1-b670-d1669a5c80fb)

### Steps to Reproduce the Bug or Issue

While using the codes from official documentations in typescript.
While the code still works in development but when building the application it throws type error.

### Expected behavior

The error doesnt cause any unexpected error it jst shows type error when building the application

### Operating System Version

Windows

### Browser

Chrome

**Comment by matheusboeira** [comment]
Hey, @kazuma-aniflex. Did you try to use `onSelectionChange={(keys) => onSelectedCaption(keys as Set<string>)}`?

**Comment by kazuma-aniflex** [comment]
@matheusboeira Thank you bro that solved the issue I was having.

**Comment by alehkonan** [comment]
As I see type Selection uses type Key that is defined in @react-types and can be string | number;
Even if I set type in useState like 
```
import { useState, type Key } from 'react';
const [value, setValue] = useState<Set<Key> | 'all'>();
```
It will still cause an error, because in @types/react `type Key = string | number | bigint.`
So the possible solution can be setting type of the state like: 
```
const [value, setValue] = useState<Set<string | number> | 'all'>();
```

**Comment by JobberRT** [comment]
@alehkonan Hi, may I ask if the `value/setValue` set to `Set`, how to assign the `<Select value={value}`? Cause I got the similar error: "Type Set<string | number> | "all" | undefined is not assignable to type string | number readonly string[] | undefined"
