### ISSUE TITLE
[Feature Request] Need block buttons

### ISSUE THREAD

**Issue by srivatsa17** [nextui-org/nextui#2127]
### Is your feature request related to a problem? Please describe.

The button feature currently does not stretch across a block/grid. I even tried to apply `max-w-max` or `max-w-md` class but it did not help me. The only thing that worked was setting the fixed width like `w-[200px]`

### Describe the solution you'd like

Would like to have block button such as https://react-bootstrap.github.io/docs/components/buttons#block-buttons

### Describe alternatives you've considered

Would be using the currently available button until the block button is supported.

### Screenshots or Videos

Would like this button to fill the max width available.

<img width="295" alt="image" src="https://github.com/nextui-org/nextui/assets/52497355/220e6a72-575e-43a1-a6de-2c45b0aec6f1">

**Comment by matheusboeira** [comment]
The `fullWidth` prop didn't work in this case? @srivatsa17

**Comment by matheusboeira** [comment]
@srivatsa17, the `fullWidth` prop didn't work in this case?

**Comment by srivatsa17** [comment]
@matheusboeira , the password/email field i am using have `max-w-md` class. When i added the just the `fullWidth` prop last time without any other class, it took up the entire screen. Now i have `max-w-md` class for the button along `fullWidth` prop and it worked. Thank you :)
