### ISSUE TITLE
[BUG] - DropdownItem Routing causes full refresh on NextJS

### ISSUE THREAD

**Issue by dml0031** [nextui-org/nextui#2131]
### NextUI Version

2.2.9

### Describe the bug

When using a dropdown as follows with NextJS app routing setup on the provider as documented:

```
<Dropdown>
  <DropdownTrigger>
    <Button>Open</Button>
  </DropdownTrigger>
  <DropdownMenu aria-label="Navigation">
     <DropdownItem key="home" href="/home">Home</DropdownItem>
     <DropdownItem key="about" href="/about">About</DropdownItem>
  </DropdownMenu>
</Dropdown>
```

Clicking on the `<DropdownItem key="home" href="/home">Home</DropdownItem>` results in a full page refresh instead of a `router.push` as expected from the routing docs.

Searched through current issues, Discord and Discussions and did not see any issue opened yet for DropdownItem but apologies if I may have missed it!

### Steps to Reproduce the Bug or Issue

1. Create a dropdown component with Dropdown items setup with an `href` parameter
2. Click dropdown item from dropdown menu
3. Page loads with a full refresh

### Expected behavior

Expect `DropDownItem` to navigate using nextjs router and not have a full refresh.

### Operating System Version

Browser

### Browser

Chrome

**Comment by torresgol10** [comment]
Have you checked this part of the documentation? It is necessary for the link to work correctly: https://nextui.org/docs/guide/routing

**Comment by dml0031** [comment]
Yes I have setup the app as documented. `@nextui-org/link` works as it should, I have only noticed this issue with `DropdownItem` that has the `href` attribute

**Comment by thallysondias** [comment]
I have same problem.
full refresh when dropdown item has href=""

**Comment by dml0031** [comment]
> I have same problem. full refresh when dropdown item has href=""
> 
> @dml0031 you found any solution?

I Have not, most likely just go back to the old method I was using and just putting a link inside of the `DropdownItem`

**Comment by dml0031** [comment]
> @dml0031 - if you provide `as={Link}` as an attribute to `<DropdownItem>`, it should work properly.
> 
> ```
> import Link from 'next/link';
> 
> <DropdownItem
>     key="about"
>     href="/about"
>     as={Link}
> >
> ```
> 
> h/t @BasitAli for answering this in a different thread - [#2301 (comment)](https://github.com/nextui-org/nextui/issues/2301#issuecomment-1936999050)

Will try that as well!

However while it may fix the issue, this bug still remains as the fix goes against the routing documentation so will keep it open for now!

**Comment by BasitAli** [comment]
> > @dml0031 - if you provide `as={Link}` as an attribute to `<DropdownItem>`, it should work properly.
> > 
> > ```
> > import Link from 'next/link';
> > 
> > <DropdownItem
> >     key="about"
> >     href="/about"
> >     as={Link}
> > >
> > ```
> > 
> > h/t @BasitAli for answering this in a different thread - [#2301 (comment)](https://github.com/nextui-org/nextui/issues/2301#issuecomment-1936999050)
> 
> Will try that as well!
> 
> However while it may fix the issue, this bug still remains as the fix goes against the routing documentation so will keep it open for now!

Agreed, the documentation needs fixing here.

**Comment by russx2** [comment]
Whilst this solution fixes the issue of using the router's navigation, it then changes the styling on how the dropdown item is rendered so isn't ideal. Surely the original issue should be considered a bug?

**Comment by Dragomir-Ivanov** [comment]
Second that. God bless the AI for pointing it.

**Comment by edarioq** [comment]
`as={Link}` worked - this should be default as soon as you add the `href` prop

**Comment by iqingting** [comment]
In my case, `as={Link}` worked in development but does not work in production.

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3240
