### ISSUE TITLE
[BUG] - Astro 4.0 can't even use the button from the tutorial

### ISSUE THREAD

**Issue by adriangalilea** [nextui-org/nextui#2135]
### NextUI Version

2.2.9

### Describe the bug

18:31:39 [ERROR] [object Object] is not a valid HTML tag name in <[object Object] color="primary">

### Steps to Reproduce the Bug or Issue

Astro 4.0
Install nextui and a dd a button on steps 1. and 2. here:
https://nextui.org/docs/frameworks/astro

### Expected behavior

.

### Operating System Version

macOS

### Browser

Chrome

**Comment by aidenberzins** [comment]
Made a minimum reproduction of this in CodeSandbox. 
https://codesandbox.io/p/devbox/bug-astro-2135-55fk5j

**Comment by adriangalilea** [comment]
> Made a minimum reproduction of this in CodeSandbox. https://codesandbox.io/p/devbox/bug-astro-2135-55fk5j

So it didn't trigger my `[ERROR]` but `console.log("This should do something... ");` wasn't working... right?

**Comment by aidenberzins** [comment]
@adriangalilea That's correct. For some reason it won't send the onClick function through to the final build. Using the astro toolbar also shows that the onClick property is null.
<img width="481" alt="Screenshot 2023-12-18 at 12 02 52 PM" src="https://github.com/nextui-org/nextui/assets/25511306/92d0e2bc-c1cb-4985-a589-e384722e952c">

**Comment by adriangalilea** [comment]
`Was there something missing in my reproduction that you noticed in your code to make it trigger the same error so the team has an easier time debugging?`

Not that I can think of, I tried again, still not working for me.

I made the repo that I was trying to achieve public just in case it helps you.
https://github.com/adriangalilea/adriangalilea/tree/nextui

I rather make it private again whenever you are done, so let me know :)

**Comment by Tossko** [comment]
Remember that you must integrate react with astro `npx astro add react`

**Comment by aidenberzins** [comment]
@Tossko Do you have to use `npx astro add react`. 
I did in my example. Whether you manually add the packages and modify the config or have astro do it shouldn't matter, right?

**Comment by aidenberzins** [comment]
@adriangalilea it appears you are using `preact` with `astro` instead of the required `react`. In order to use `nextui` you would need to implement `preact/compat` or use `react` instead. 

https://docs.astro.build/en/guides/integrations-guide/preact/#configuration

I don't believe NextUI exports to ESM, but that is a requirement for preact/compact so you may not be able to use this library currently. But you can see the error is gone in the [example code](https://codesandbox.io/p/devbox/bug-astro-2135-55fk5j) and although the click is not working on the button it did resolve your error to follow the astro docs for preact.

**Comment by adriangalilea** [comment]
> @adriangalilea it appears you are using `preact` with `astro` instead of the required `react`. In order to use `nextui` you would need to implement `preact/compat` or use `react` instead.

I'm pretty new with webdev, figured that running `npm i @nextui-org/react framer-motion` would cause the necessary changes, and it didn't apparently.

Will take a look again, thanks.
