### ISSUE TITLE
[BUG] - Accordion is not working properly

### ISSUE THREAD

**Issue by DarkWolff71** [nextui-org/nextui#2136]
### NextUI Version

2.2.9

### Describe the bug

Accordion is not working
next version: 14.0.4

Logs:
 ⨯ node_modules\@react-stately\collections\dist\import.mjs (205:22) @ $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode
 ⨯ Error: Unknown element <[object Object]> in collection.
    at getFullNode.next (<anonymous>)
    at iterateCollection.next (<anonymous>)
    at Generator.next (<anonymous>)
null

### Steps to Reproduce the Bug or Issue

Create a new next js app and install next ui and use the accordion 

### Expected behavior

The accordion should work as shown in the docs

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by r0ld3x** [comment]
Can you share the code? like what type of data you are providing?

**Comment by devlzcode** [comment]
> Can you share the code? like what type of data you are providing?

This bug happens when some components are rendered inside server components. I've experienced it with `User`, `Tabs`, and `Dropdown` so far.

**Comment by LucasTempass** [comment]
I'm suffering from the same issue using Next.js version 14.0.3. **It can be reproduced just copying and pasting the code example from the official docs.**

**Comment by eduardscript** [comment]
Same problem here

**Comment by danieldid** [comment]
The problem only seems to occur when using `use server` though

**Comment by ralphmanns** [comment]
That worked for me:

Changing the NextJs 14 defautl rootLayout export from 

`export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return`
  
to

`export default function RootLayout({children}: { children: React.ReactNode }) { return`

**Comment by satu-jovanhartono** [comment]
> Same here... This is basically my code being rendered inside a NextJS Page
> 
> 1. Using App Router
> 2. next v14.0.3
> 3. @nextui-org/react v2.2.9
> 
> ```
> <Accordion>
>   <AccordionItem
>     key="1"
>     aria-label="Overview"
>     subtitle="Press to expand"
>     title="Overview"
>   >
>     <p className="my-10 dark:text-zinc-400">{data.description}</p>
>   </AccordionItem>
> </Accordion>
> ```
> 
> <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/37680779/300560937-83e5a353-1c65-486a-a8c3-ea95290bf468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDc5MDcsIm5iZiI6MTcwODYwNzYwNywicGF0aCI6Ii8zNzY4MDc3OS8zMDA1NjA5MzctODNlNWEzNTMtMWM2NS00ODZhLWE4YzMtZWE5NTI5MGJmNDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEzMTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZTcyNmVlNTA2Yzc3MDFjMTkxNmIwYWJkOWY0OWNjNzQ0ZDg0ZDlkNDgxZTJjYjRkODM0YzRlZjU4ZjNmNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aWK8Bggm-ZrFUhkypLBcH3zlir6NSxujkx22kkd7WrA">

i'm having the same problem. for now the workaround is to use ``use client`` directive at the component that uses ``Accordion``

**Comment by satu-jovanhartono** [comment]
bump

**Comment by TudorEsan** [comment]
same problem here

**Comment by TudorEsan** [comment]
well for me it seems that what was wrong is that i had a reusable component using the AccordionItem after not using the reusable component the accordion works again
```ts
'use client';

import { AccordionItem } from '@nextui-org/react';
import Image from 'next/image';
import React from 'react';

import { Button } from '@/components/ui/button';

interface Props {
  image: string;
  buttonText: string;
  onClick: () => void;
  description: string;
  title: string;
  points: string | number;
  key: string;
}

export const ActiveTask = ({
  image,
  buttonText,
  onClick,
  description,
  title,
  points,
  key,
}: Props) => {
  return (
    <AccordionItem
      key={key}
      aria-label="Accordion 1"
      title={
        <div className="flex items-center justify-between gap-3">
          <div className="flex gap-3 items-center">
            <Image
              src={image}
              alt="x"
              width={32}
              height={32}
              className="w-8 h-8"
            />
            <p>{title}</p>
          </div>
          <p className="text-muted-foreground">{points} Points</p>
        </div>
      }
    >
      <div className="p-4">
        <p>{description}</p>
        <div className="flex justify-end">
          <Button variant="monochrome" className="ml-auto" onClick={onClick}>
            {buttonText}
          </Button>
        </div>
      </div>
    </AccordionItem>
  );
};
```

**Comment by parsasabetz** [comment]
Had the same problem here, but using the `"use client";` directive did solve it.
This probably means that NextUI should consider working on the errors related to when their components are mistakenly used in server components...
I was initially confused where I've messed up using server actions again...

**Comment by steebchen** [comment]
It would be great if server components could be supported. Of course 'use client' makes the error go away, but that basically prevents all of the contents not being rendered at all on the server, so crawlers will not see this content unless they use JS rendering.

**Comment by konotorii** [comment]
bump, still doesnt work unless rendered in client

**Comment by chihabhajji** [comment]
bump

**Comment by pradeepnswamy** [comment]
Having 'use client'; on top of my page resolved the issue

**Comment by wingkwong** [comment]
Either add `use client` directive on top of the page or use individual package (which we add that at build time).
