### ISSUE TITLE
[BUG] - slots.list is not a function

### ISSUE THREAD

**Issue by benmams59** [nextui-org/nextui#2140]
### NextUI Version

2.2.9

### Describe the bug

slots.list is not a function

I got the following error message after upgrading to NextUI 2.2.9 (the latest version) 

### Steps to Reproduce the Bug or Issue

I just upgrade my NextUI to 2.2.9 so... with the following command
1. npm i @nextui/react framer-motion

### Expected behavior

.

### Operating System Version

Linux

### Browser

Firefox

**Comment by wingkwong** [comment]
Not applicable.
