### ISSUE TITLE
[BUG] - unable to close popover of autocomplete 

### ISSUE THREAD

**Issue by awesmatic** [nextui-org/nextui#2143]
### NextUI Version

2.2.9

### Describe the bug

When utilizing autocomplete functionality within a modal and subsequently opening the popover, if no value is selected or if there is no click interaction inside the popover, it fails to close.

### Steps to Reproduce the Bug or Issue

1.create a modal 
2. inside it use autocomplete
3. open popoever and then close it without selete any thing

### Expected behavior

it should close when i click outside it

### Operating System Version

windows

### Browser

Chrome

**Comment by harrycarp** [comment]
I had the same issue. Answer found here: [#1987 (comment)](https://github.com/nextui-org/nextui/issues/1987#issuecomment-1817335810) 

In summary, fixed it with the addition of `allowsCustomValue={true}` In the Autocomplete element's props.
