### ISSUE TITLE
[BUG] - Autocomplete does not work when the clear button is hit.

### ISSUE THREAD

**Issue by Marcosfsalazar** [nextui-org/nextui#2146]
### NextUI Version

2.2.9

### Describe the bug

When the user clicks on the autocomplete field and then hits the clear button, the field stops working. The user must click outside the field and then click in the input again to restore functionality. If the user tries to search for something, the popover will not appear.

### Your Example Website or App

https://nextui.org/docs/components/autocomplete

### Steps to Reproduce the Bug or Issue

1.Go to an **autocomplete field** with an item already selected.
2.Click on the **input field**.
3.Click on the clear **'X' button**.
4.Without clicking outside the **input**, try to type something.
5.Notice that the **popover** does not appear.

### Expected behavior

As a user, I expect that when I clear the field and then try to search for something, the list of options should appear. However, currently, when I clear the field and attempt to type something, nothing happens.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/60948283/27648907-8cd6-44ac-9e28-7746fcf00c31

### Operating System Version

Ubuntu 22.04

### Browser

Chrome

**Comment by kn1ght** [comment]
Facing the same issue.
Easily reproducible in controlled autocomplete example: https://nextui.org/docs/components/autocomplete#controlled

Any updates on this?

**Comment by wingkwong** [comment]
No longer reproducible in prod doc & main branch (v2.3.5).

[issue2146-demo.webm](https://github.com/nextui-org/nextui/assets/35857179/322d23bc-cf48-4ee1-a271-40934d7d290f)
