### ISSUE TITLE
[BUG] - Routing in NextUIProvider in with NextJs

### ISSUE THREAD

**Issue by FranzaLeny** [nextui-org/nextui#2149]
### NextUI Version

2.2.9

### Describe the bug

When clicking the link in the dropdown, it opens two tabs with the target: _blank.

### Steps to Reproduce the Bug or Issue

Click on Dropdown Component

### Expected behavior

Open Single Tab Only

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/66564146/bd339289-196a-4c72-87ed-1885983738d6)
![image](https://github.com/nextui-org/nextui/assets/66564146/8ba19bca-8eba-4d64-a0c0-56682c982fff)

https://github.com/nextui-org/nextui/assets/66564146/c31fa713-390d-48d8-89b1-46eaf0fb6f34

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3240
