### ISSUE TITLE
Can I use nextui without installing tailwind?

### ISSUE THREAD

**Issue by ClearLuvMoki** [nextui-org/nextui#2157]
### Is your feature request related to a problem? Please describe.

Can I use nextui without installing tailwind?

### Describe the solution you'd like

If I want to use css-in-js then I not only need to introduce cssinjs but also tailwind;

### Describe alternatives you've considered

Installing nextui does not require additional installation of tailwind

**Comment by wingkwong** [comment]
As listed in the installation page, this is one of the requirements.
