### ISSUE TITLE
[BUG] - resetField in React Hook form doesn't work when using NextUI's Input

### ISSUE THREAD

**Issue by zhenailuoye1** [nextui-org/nextui#2158]
### NextUI Version

2.2.9

### Describe the bug

resetField in React Hook form doesn't work when using NextUI's Input,here is code:

```
'use client'

import { useForm } from 'react-hook-form'
import { Input } from '@nextui-org/react'

export default function Page() {
  const { register, resetField } = useForm({
    mode: 'onChange',
    defaultValues: {
      firstName: '',
    },
  })
  const handleClick = () => resetField('firstName')

  return (
    <form>
      <Input {...register('firstName', { required: true })} />

      <button type="button" onClick={handleClick}>
        Reset
      </button>
    </form>
  )
}
```

### Your Example Website or App

[codesandbox](https://codesandbox.io/p/devbox/empty-glade-gr9c47?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpdu2ouq000820677m7yk1ff%2522%252C%2522sizes%2522%253A%255B73.6564067%252C26.343593299999995%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpdu2ouq0003206777nvsr7p%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpdu2ouq00052067b6vvobkc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpdu2ouq00072067feuyz635%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B42.58191362%252C57.41808638%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpdu2ouq0003206777nvsr7p%2522%253A%257B%2522id%2522%253A%2522clpdu2ouq0003206777nvsr7p%2522%252C%2522activeTabId%2522%253A%2522clqgf0d2300fu3b6j7wdl5y1f%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqgeeysw00023b6j7mt52q6k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A16%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clqgf0d2300fu3b6j7wdl5y1f%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clpdu2ouq00072067feuyz635%2522%253A%257B%2522id%2522%253A%2522clpdu2ouq00072067feuyz635%2522%252C%2522activeTabId%2522%253A%2522clqgf03pl00e83b6jrbquh0i4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqgf03pl00e83b6jrbquh0i4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clpdu2ouq00052067b6vvobkc%2522%253A%257B%2522id%2522%253A%2522clpdu2ouq00052067b6vvobkc%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqgezy2x00bm3b6jos653jzp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqgezy2x00bm3b6jos653jzp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce the Bug or Issue

Typing someting in the input and clicking Reset button, the Input's value don't reset,but when I change the Input to html native input, it will be work.

### Expected behavior

I expected input can be reset, but noting happen.

### Operating System Version

macOS

### Browser

Chrome

**Comment by MrLexisDev** [comment]
When you use a library like nextUI / MUI ... react hook form recommand to use `<Controller />` : [https://react-hook-form.com/advanced-usage#ControlledmixedwithUncontrolledComponents](Controller)

In your component, you can use can type 
`
const {// Other vars, reset} = useForm({...})
`

And finally call `reset()` in your function.

**Comment by zhenailuoye1** [comment]
> When you use a library like nextUI / MUI ... react hook form recommand to use `<Controller />` : [https://react-hook-form.com/advanced-usage#ControlledmixedwithUncontrolledComponents](Controller)
> 
> In your component, you can use can type `const {// Other vars, reset} = useForm({...})`
> 
> And finally call `reset()` in your function. [https://react-hook-form.com/docs/useform/reset](reset)

It works, thank you
