### ISSUE TITLE
Customizing colors for components

### ISSUE THREAD

**Issue by khwab-41** [nextui-org/nextui#2162]
### Customizing themes for different sections of a component

So, I intended to use NextUI's Accordion for my recent project. I have my customized theme for the project, so I want the Accordion title to be of different colors and fonts. The same applies to the content of Accordion. Currently, there is no feature with which we can customize the theme of components. It would be a good addition if you can add something like that.

### Describe the solution you'd like

We can have attributes like, title-color, title-font, content-color, etc... to customize the styles

### Describe alternatives you've considered

We can also have some sort of selectors, like ::ng-deep for Material UI, with which users can customize UI of different components according to their choice.

**Comment by laurentlahmy** [comment]
Maybe like this? https://nextui.org/docs/customization/override-styles

**Comment by wingkwong** [comment]
Closing - see [here](https://nextui.org/docs/components/accordion#custom-accordion-styles) and the above link.
