### ISSUE TITLE
[BUG] - Modal can't open when the button is wrappered by <div> in mobile browser

### ISSUE THREAD

**Issue by jim-king-2000** [nextui-org/nextui#2179]
### NextUI Version

2.2.9

### Describe the bug

The example shows the following code:
```javascript
<>
      <Button onPress={onOpen}>Open Modal</Button>
      <Modal isOpen={isOpen} onOpenChange={onOpenChange}>
        <ModalContent>
          ...
        </ModalContent>
      </Modal>
</>
```
It works fine.

Now, let's wrap the `<Button>` by `<div>`.
```javascript
<>
      <div><Button onPress={onOpen}>Open Modal</Button></div>
      <Modal isOpen={isOpen} onOpenChange={onOpenChange}>
        <ModalContent>
          ...
        </ModalContent>
      </Modal>
</>
```

Then we open it with mobile browser. Notice that the modal never shows.

### Steps to Reproduce the Bug or Issue

1. Go to <https://codesandbox.io/p/devbox/test-nextui-forked-ccymt7?file=%2Fapp%2Fpage.jsx%3A12%2C9>
2. Open the website by mobile browser.
3. Click on "open Modal", notice that nothing happens.

Notice: It works well on PC browsers.

### Expected behavior

Show the dialog.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by jim-king-2000** [comment]
It works when we use `onClick` instead of `onPress`.
```javascript
<>
      <div><Button onClick={onOpen}>Open Modal</Button></div>
      <Modal isOpen={isOpen} onOpenChange={onOpenChange}>
        <ModalContent>
          ...
        </ModalContent>
      </Modal>
</>
```

**Comment by khaymanii** [comment]
It works for both onPress and onClick

**Comment by jim-king-2000** [comment]
Weird. It can't reproduce. Close it for now.

**Comment by jim-king-2000** [comment]
> It works for both onPress and onClick

It reproduces intermittently. Please try more times.

**Comment by jim-king-2000** [comment]
There is another repro steps:
1. Open <https://ccymt7-3000.csb.app/> in Chrome.
1. Switch to "mobile" mode. Click "Open Modal", see it works.
1. Switch to "PC" mode. Click "Open Modal", see it works.
1. Switch back to "mobile" mode, and click "Open Modal", see it does NOT work.

**Comment by andyngdz** [comment]
> It works when we use `onClick` instead of `onPress`.
> 
> ```js
> <>
>       <div><Button onClick={onOpen}>Open Modal</Button></div>
>       <Modal isOpen={isOpen} onOpenChange={onOpenChange}>
>         <ModalContent>
>           ...
>         </ModalContent>
>       </Modal>
> </>
> ```

Thanks. I got the same issue, switched to use onClick works well. Weird 🤔

**Comment by alexandre-xn** [comment]
Why was this closed ? The doc is not updated so examples still use onPress instead of onClick

**Comment by wingkwong** [comment]
@alexandre-xn onClick is deprecated. Please try using onPress. If issue still exists in latest version, please create a new issue.

**Comment by KhanerX** [comment]
I have the same issue, onClick works on mobile, onPress doesn't. very weird
