### ISSUE TITLE
Switch inside DropdownItem auto switch bug

### ISSUE THREAD

**Issue by jalvarezz13** [nextui-org/nextui#2187]
### NextUI Version

2.2.9

### Describe the bug

I'm encountering a peculiar issue with a switch inside a dropdown.

Whenever I open the dropdown, the switch seems to toggle, but this only happens when the switch is not selected (selected: false). Any ideas or suggestions on what might be causing this behaviour?

### Steps to Reproduce the Bug or Issue

create a component like:
```
<DropdownItem>
      <Switch />
</DropdownItem>
```

### Expected behavior

I expected no action when I open the DropdownItem

### Operating System Version

Windows

### Browser

Chrome

**Comment by MartinoVolcy** [comment]
any updates?
