### ISSUE TITLE
Trigger dropdown menu on mouse enter event

### ISSUE THREAD

**Issue by devvrats** [nextui-org/nextui#2190]
### Is your feature request related to a problem? Please describe.

There is no problem. I was looking for dropdown can trigger using mouse enter.

### Describe the solution you'd like

we can try using any cutome attribute or onmouseenter event to tringer to <dropdowntriger>

### Describe alternatives you've considered

NA

**Comment by khaymanii** [comment]
I've added the feature as requested see it in issue #2206

**Comment by wingkwong** [comment]
Closing as not planned - Not really a feature for NextUI side.
