### ISSUE TITLE
[BUG] - Chip component. Linter complain about variant prop

### ISSUE THREAD

**Issue by slatqh** [nextui-org/nextui#2203]
### NextUI Version

2.2.9

### Describe the bug

I have a linter error about variant prop for Chip component. Not sure if it's a bug or something local to me. 
<img width="523" alt="Screenshot 2024-01-03 at 12 21 30 PM" src="https://github.com/nextui-org/nextui/assets/32040388/63a9c1e1-340f-4900-8111-74e3b72c14e1">

Here is a typescript error 

`Type '{ children: string; style: { cursor: "pointer"; }; variant: string; key: number; startContent: Element; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & MergeWithAs<Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref">, Omit<...>, ChipProps, "div">'.
  Property 'variant' does not exist on type 'IntrinsicAttributes & MergeWithAs<Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref">, Omit<...>, ChipProps, "div">'.ts(2322)
(property) variant: string`

### Steps to Reproduce the Bug or Issue

Just install latest version with latest next.js version. 

### Expected behavior

Linter shouldn't complain 

### Operating System Version

macOS

### Browser

Chrome

**Comment by hassansuhaib** [comment]
Were you able to fix it? @slatqh

**Comment by wingkwong** [comment]
Not able to reproduce.
