### ISSUE TITLE
[BUG] - Button

### ISSUE THREAD

**Issue by enortek** [nextui-org/nextui#2211]
### NextUI Version

"^2.2.9",

### Describe the bug

There is a bug to create a custom button

Property 'onClear' is missing in type '{ ripples: RippleType[]; }' but required in type 'RippleProps'.ts(2741)
ripple.d.ts(11, 5): 'onClear' is declared here.
Translation
Property 'onClear' is missing in type '{ ripples: RippleType[]; }' but required in type 'RippleProps'.
You haven't passed all the required properties to RippleProps - { ripples: RippleType[]; } is missing the onClear property.

(alias) const Ripple: FC<RippleProps>
import Ripple

 ⨯ src/components/NewButton.tsx (19:16) @ eval
 ⨯ TypeError: (0 , _nextui_org_react__WEBPACK_IMPORTED_MODULE_3__.useButton) is not a function
    at eval (./src/components/NewButton.tsx:23:185)
    at stringify (<anonymous>)
digest: "1943911373"
  17 |     getButtonProps,
  18 |     getRippleProps,
> 19 |   } = useButton({
     |                ^
  20 |     ref,
  21 |     ...props,
  22 |   });
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 
 in addition the button is missing one important property which how to have button size based on screen size, let us say I define all the styling inline with className=` .....`
if I do className with backtick then it generate an error, it accept single or duple quote

 

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

create a component and copy the code from the 
https://nextui.org/docs/components/button#custom-styles

### Expected behavior

missing property 

### Screenshots or Videos

no

### Operating System Version

- OS: all

### Browser

Other (add additonal context)

**Comment by kght6123** [comment]
@enortek 
> Property 'onClear' is missing in type '{ ripples: RippleType[]; }' but required in type 'RippleProps'.ts(2741)
I was able to retrieve and set the onClear property as follows, which should resolve the error. It seems there's a mistake in the documentation, so I plan to request a correction via a pull request later on.
```tsx
  const {ripples, onClear} = getRippleProps();

  return (
    <button type="button" ref={domRef} {...getButtonProps()}>
      {startContent}
      {isLoading && spinnerPlacement === "start" && spinner}
      {children}
      {isLoading && spinnerPlacement === "end" && spinner}
      {endContent}
      {!disableRipple && <Ripple ripples={ripples} onClear={onClear} />}
    </button>
  );
```
We are still investigating other issues. Please wait.

**Comment by kght6123** [comment]
@enortek 
> in addition the button is missing one important property which how to have button size based on screen size, let us say I define all the styling inline with className= .....
> if I do className with backtick then it generate an error, it accept single or duple quote

To display the button responsively, you can specify the className using Tailwind CSS as shown below. The following example will make the button width w-32 for screen sizes sm and above, w-auto (100%) for md and above, and w-14 for other sizes:
```tsx
<Button type="button" className="sm:w-32 md:w-auto w-14">
  Responsive
</Button>
```
What issues are you facing? If you can provide a specific code example, I can investigate further.
