### ISSUE TITLE
[BUG] - Non-dissmissable modal can be closed by pressing ESC key

### ISSUE THREAD

**Issue by alexbalieiro** [nextui-org/nextui#2214]
### NextUI Version

2.2.9

### Describe the bug

In the docs it says that its possible to make a modal non-dismissible by setting the isDismissable prop to false, but it can still be closed by pressing ESC key. It can be reproduced on the docs.

### Your Example Website or App

https://nextui.org/docs/components/modal#non-dissmissable

### Steps to Reproduce the Bug or Issue

1. Go to https://nextui.org/docs/components/modal#non-dissmissable
2. Press "Open Modal" button
3. Press ESC
4. The modal closes

### Expected behavior

I expected the modal to be non-dismissible

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/74037904/fc84095b-fa53-4e56-8fcd-17797dd50d90

### Operating System Version

Windows 10 Home

### Browser

Chrome

**Comment by ryo-manba** [comment]
@alexbalieiro 
It seems like there was indeed an oversight in the documentation as you pointed out. In fact, to prevent the modal from closing with the Esc key, you need to set the isKeyboardDismissDisabled property to true.

I've already submitted a PR for this!

**Comment by alexbalieiro** [comment]
Thank you, I didn't know isKeyboardDismissDisabled property, I tried it in my project and it works.
