### ISSUE TITLE
CONTRIBUTING.MD is incorrect or package.json is missing a script.

### ISSUE THREAD

**Issue by andrew3009** [nextui-org/nextui#222]
**Describe the bug**
In the CONTRIBUTING.MD file step 2 says to start the webpack server.
```
## Start the webpack dev server
yarn build:watch
```
But this script is missing from the scripts object in package.json.

**Steps to reproduce**
1. Clone the nextui repo
2. Click on package.json
3. Run ``yarn build:watch``
4. See ``error Command "build:watch" not found.``

**Expected behaviour**
Root package.json should contain the script build:watch if it is needed to work on components source code.

**Screenshots**
<img width="601" alt="MissingBuildWatch" src="https://user-images.githubusercontent.com/54292974/152250897-22236141-2366-4daf-b7bb-7fc1e3f9a588.png">

**Comment by jrgarciadev** [comment]
Hey @andrew3009, thanks for reporting it, is already solved 🙌🏼
