### ISSUE TITLE
[Feature Request] Way to customize default styles

### ISSUE THREAD

**Issue by volnei** [nextui-org/nextui#2226]
### Is your feature request related to a problem? Please describe.

I want to customize default styles since links are default text-medium (althrough I prefer that it's follow the css context font-size) also buttons and dropdowns use bold text.

### Describe the solution you'd like

A customization on nextui plugin

### Describe alternatives you've considered

Customize manually by css, terrible

**Comment by wingkwong** [comment]
See https://nextui.org/docs/customization/customize-theme
