### ISSUE TITLE
[BUG] - Missing isRequired props on RadioGroup and CheckboxGroup

### ISSUE THREAD

**Issue by jdelglise** [nextui-org/nextui#2227]
### NextUI Version

2.2.9

### Describe the bug

In the documentation of the RadioGroup (https://nextui.org/docs/components/radio-group), there is a props "isRequired".

UPDATE : it is also true form the CheckboxGroup (I will not described it, but the issue is identical)

In the source code, this props is filtered out with the following line :

```
type UseRadioGroupProps = Omit<Props, "defaultChecked"> & Omit<AriaRadioGroupProps, "onChange"> & Partial<Pick<RadioProps, "color" | "size" | "isDisabled" | "disableAnimation" | "onChange">>;
```

### Steps to Reproduce the Bug or Issue

Try to add props isRequired on RadioGroup, e.g : 

```
    <RadioGroup isRequired={false}>
      <Radio value="buenos-aires">Buenos Aires</Radio>
      <Radio value="sydney">Sydney</Radio>
      <Radio value="san-francisco">San Francisco</Radio>
      <Radio value="london">London</Radio>
      <Radio value="tokyo">Tokyo</Radio>
    </RadioGroup>
```

typescript error :  Property 'isRequired' does not exist on type [...]

### Expected behavior

I expect this props to exist

### Operating System Version

Windows

### Browser

Chrome

**Comment by kuri-sun** [comment]
Hi @jdelglise, I was trying to reproduce this error but I could not. I believe that this works fine currently. Could you try to reproduce this error one more time on your side once again, please? Thanks!

**Comment by kuri-sun** [comment]
Also, this one is a duplicate for #2081

**Comment by wingkwong** [comment]
Closing - duplicate
