### ISSUE TITLE
[BUG] - Input Label Placement is Wrong

### ISSUE THREAD

**Issue by joseuribeh98** [nextui-org/nextui#2235]
### NextUI Version

2.1.13

### Describe the bug

Inputs were working perfect but when I updated NextUI they all started to put the label on top of the placeholder and the description is not showing. I'm not using react-hook-form on my app. 

This is a snapshot of my code: 
![image](https://github.com/nextui-org/nextui/assets/132782591/8ff5671d-3640-43f0-af59-7b49e8e52439)

This is snapshot of UI issue:
![Captura de pantalla 2024-01-11 223254](https://github.com/nextui-org/nextui/assets/132782591/9d165d43-0ec5-4888-8eeb-18069574ced3)

**I fixed this bug, importing Input component from '@nextui-org/input' instead '@nextui-org/react'**

I'm working on Next.js 14.0.4 now but I saw the same issue with Next.js 13. Also using pnpm.

I don't know if it's a node package manager issue. Because it was working while we have pnpm-lock and package-lock files (by mistake) on root. It started happening also deleting package-lock to use pnpm-lock instead or removing node_modules and installing or upgrading dependencies again (with pnpm or npm).

### Steps to Reproduce the Bug or Issue

1. Install '@nextui-org/react' using pnpm
2. Import Input component from '@nextui-org/react'
3. Give a placeholder prop
4. Give a label prop

### Expected behavior

I expect that importing Input from '@nextui-org/react' that component show the label and  description props correctly.

### Operating System Version

Windows

### Browser

Chrome

**Comment by rtopham** [comment]
I also ran into this bug, but under slightly different circumstances. It appears that the labelPlacement prop defaults to "inside" if no initial value or placeholder his provided. Even if labelPlacement is specifically specified as "outside" it will be placed inside unless either (1) an initial non-empty string is provided as a value, or (2) a non-empty placeholder is provided. I was able to work around this by providing a placeholder of " " with a blank space between the quotes. Not exactly a satisfying solution.

**Comment by kuri-sun** [comment]
Hi @joseuribeh98 @rtopham! I am trying to reproduce this issue, however, I could not. Is this issue currently resolved? Thank you!

**Comment by klicana** [comment]
> Hi @joseuribeh98 @rtopham! I am trying to reproduce this issue, however, I could not. Is this issue currently resolved? Thank you!

Hey there @kuri-sun as I mentioned, I've managed to fix this importing the component from @nextui-org/input. But I haven't tried again importing from @nextui-org/react

**Comment by joseuribeh98** [comment]
> Hi @joseuribeh98 @rtopham! I am trying to reproduce this issue, however, I could not. Is this issue currently resolved? Thank you!

Hey there @kuri-sun as I mentioned, I've managed to fix this importing the component from @nextui-org/input. But I haven't tried again importing from @nextui-org/react

**Comment by jvlomazzi** [comment]
Hi there!
I bumped my `@nextui-org/react` version and encountered this bug too. To fix it, I had to update the theme package (`npm i @nextui-org/theme@latest`). After that, I switched back to the default input import and the placement was correct.

**Comment by wingkwong** [comment]
Not reproducible in latest version
