### ISSUE TITLE
[BUG] - clicking on input clear button doesn't work

### ISSUE THREAD

**Issue by Md-Hasib-Askari** [nextui-org/nextui#2242]
### NextUI Version

2.2.9

### Describe the bug

On the website clear button in <Input /> worked pretty well, but in my case, the button fades away but the writing on the input box doesn't get cleared. I tried useRef as well it won't work.

### Steps to Reproduce the Bug or Issue

1. Create a new react app
2. Copy and paste the clear button code in Input section
3. Run the code
4. it doesn't work as given on the website

### Expected behavior

It should clear the text inside the input box. But it doesn't.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/31061360/48eb6a91-4463-49c5-9ae0-d749621b7c20

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by jdelglise** [comment]
Works for me with Next-Ui 2.2.9 on chrome ...
Note that if you changed the component to be controlled, you need to handle the clear on your state ...

**Comment by ostorres-pscu** [comment]
mine is not being controlled and on clear does not work

`        <Input
          className="mb-4"
          classNames={{ inputWrapper: "bg-white" }}
          label="Search Campaigns"
          isClearable
          radius="lg"
          variant="bordered"
          placeholder="Type to search..."

          onChange={(e) => {
            if (title === "In Development") {
              handleSearch(e, "dev");
            }

            if (title === "Live Campaigns") {
              handleSearch(e, "live");
            }
          }}
        />`

**Comment by EdsonT** [comment]
I had the same issue using  "@nextui-org/input": "2.1.16", I figured it out to solve it by upgrading the version to "@nextui-org/input": "2.1.17" in the package.json
Hope that helps

**Comment by pablojsx** [comment]
To be honest I don't remember this button working independently, what I do is to control the input then with the setter function set it to an empty string.

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/2796 (v2.3.6).  See https://nextui.org/docs/components/input#clear-button for an example.
