### ISSUE TITLE
[BUG] - Breadcrumbs

### ISSUE THREAD

**Issue by Md-Abdul-Kadir** [nextui-org/nextui#2245]
### NextUI Version

v2.2.0

### Describe the bug

in next project this components doesn't work

### Steps to Reproduce the Bug or Issue

1.on click

### Expected behavior

doesn't show 

### Screenshots or Videos

<img width="512" alt="Screen Shot 2024-01-14 at 1 02 03 PM" src="https://github.com/nextui-org/nextui/assets/86625889/771b8bb1-481a-4d16-858e-eefe25eb803c">

### Operating System Version

macOS

### Browser

Chrome

**Comment by JingpengZhang** [comment]
add "'use client"

**Comment by Md-Abdul-Kadir** [comment]
Thanks

**Comment by sex4096** [comment]
Should support server components

**Comment by wingkwong** [comment]
Not reproducible
