### ISSUE TITLE
[BUG] - Auto Complete popover does not close without make selection in modal

### ISSUE THREAD

**Issue by pikselinweb** [nextui-org/nextui#2247]
### NextUI Version

2.2.9

### Describe the bug

The autocomplete popover within the modal does not close without making a selection or right-clicking with the mouse.

### Steps to Reproduce the Bug or Issue

1. Create modal component with next ui.
2. Create auto complete in modal.
3. Focus to auto complete.
4. Try to close by clicking outside.

### Expected behavior

When autocomplete define in page i can close popover by clicking outside. But when i create auto complete in modal i must make selection to close.

### Operating System Version

MACOS

### Browser

Chrome

**Comment by pikselinweb** [comment]
```js
 useEffect(() => {
    if (!isOpen && !state.selectedItem && inputRef.current && allowsCustomValue) {
      inputRef.current.blur();
    }
  }, [isOpen, allowsCustomValue]);
  ```
  I edit package as like it in useAutocomplete chunk file to solve the problem temporary...

**Comment by Rick19F** [comment]
Here is the evidence, please we need a fix

https://github.com/nextui-org/nextui/assets/121076016/8b17088e-64ed-4991-86dc-be935f3385a4

**Comment by SergejSi** [comment]
same issue

**Comment by georgealexandruiancu** [comment]
same issue here, at least if we have a prop to control the behaviour if is opened or not like is on select component

**Comment by slatqh** [comment]
Popover also not close when isReadOnly props set to true. It's only closing when clicking outside. We need some props to control isOpen state.

**Comment by Tosters** [comment]
Still an issue - https://github.com/nextui-org/nextui/pull/2494#issuecomment-2041046604

**Comment by wingkwong** [comment]
@Tosters We haven't released that yet - it should be in the next release.
