### ISSUE TITLE
[BUG] - Navbar

### ISSUE THREAD

**Issue by BuckLearnsCode** [nextui-org/nextui#2248]
### NextUI Version

2.2.9

### Describe the bug

The hidden sm:flex items are not working.  As in, if you run this code, when you shrink and expand the screen width wise, nothing change (in terms of hidden and shown elements).  

### Steps to Reproduce the Bug or Issue

1. Install code as is written.
2. Change responsiveness

### Expected behavior

1. Certain elements are hidden / exposed based on screen size (like the links)

### Operating System Version

MacOS

### Browser

Chrome

**Comment by devappsms** [comment]
Facing same issue. 

Operating System Version
MacOS

Browser
Chrome

**Comment by dangersflow** [comment]
Facing same issue

**Comment by devappsms** [comment]
Any update on this

**Comment by ahsan-abrar** [comment]
+1

**Comment by wingkwong** [comment]
Please provide the code / reproducible environment for us to reproduce the issue.

**Comment by ahsan-abrar** [comment]
`       
    "use client";

      import React from "react";
      import {
        Navbar,
        NavbarBrand,
        NavbarContent,
        NavbarItem,
        Link,
        Input,
        DropdownItem,
        DropdownTrigger,
        Dropdown,
        DropdownMenu,
        Avatar,
      } from "@nextui-org/react";
      import { AcmeLogo } from "./AcmeLogo";
      import { SearchIcon } from "./SearchIcon";

      export default function Header() {
        return (
          <Navbar isBordered className="bg-primary">
            <NavbarContent justify="start">
              <NavbarBrand className="mr-4">
                <AcmeLogo />
                <p className="hidden sm:block font-bold text-inherit">ACME</p>
              </NavbarBrand>
              <NavbarContent className="hidden sm:flex gap-3">
                <NavbarItem>
                  <Link color="foreground" href="#">
                    Features
                  </Link>
                </NavbarItem>
                <NavbarItem isActive>
                  <Link href="#" aria-current="page" color="secondary">
                    Customers
                  </Link>
                </NavbarItem>
                <NavbarItem>
                  <Link color="foreground" href="#">
                    Integrations
                  </Link>
                </NavbarItem>
              </NavbarContent>
            </NavbarContent>

            <NavbarContent as="div" className="items-center" justify="end">
              <Input
                classNames={{
                  base: "max-w-full sm:max-w-[10rem] h-10",
                  mainWrapper: "h-full",
                  input: "text-small",
                  inputWrapper:
                    "h-full font-normal text-default-500 bg-default-400/20 dark:bg-default-500/20",
                }}
                placeholder="Type to search..."
                size="sm"
                startContent={<SearchIcon size={18} />}
                type="search"
              />
              <Dropdown placement="bottom-end">
                <DropdownTrigger>
                  <Avatar
                    isBordered
                    as="button"
                    className="transition-transform"
                    color="secondary"
                    name="Jason Hughes"
                    size="sm"
                    src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
                  />
                </DropdownTrigger>
                <DropdownMenu aria-label="Profile Actions" variant="flat">
                  <DropdownItem key="profile" className="h-14 gap-2">
                    <p className="font-semibold">Signed in as</p>
                    <p className="font-semibold">zoey@example.com</p>
                  </DropdownItem>
                  <DropdownItem key="settings">My Settings</DropdownItem>
                  <DropdownItem key="team_settings">Team Settings</DropdownItem>
                  <DropdownItem key="analytics">Analytics</DropdownItem>
                  <DropdownItem key="system">System</DropdownItem>
                  <DropdownItem key="configurations">Configurations</DropdownItem>
                  <DropdownItem key="help_and_feedback">Help & Feedback</DropdownItem>
                  <DropdownItem key="logout" color="danger">
                    Log Out
                  </DropdownItem>
                </DropdownMenu>
              </Dropdown>
            </NavbarContent>
          </Navbar>
        );
      }
`

**Comment by ahsan-abrar** [comment]
"use client";

import React from "react";
import {
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  Link,
  Input,
  DropdownItem,
  DropdownTrigger,
  Dropdown,
  DropdownMenu,
  Avatar,
} from "@nextui-org/react";
import { AcmeLogo } from "./AcmeLogo";
import { SearchIcon } from "./SearchIcon";

export default function Header() {
  return (
    <Navbar isBordered className="bg-primary">
      <NavbarContent justify="start">
        <NavbarBrand className="mr-4">
          <AcmeLogo />
          <p className="hidden sm:block font-bold text-inherit">ACME</p>
        </NavbarBrand>
        <NavbarContent className="hidden sm:flex gap-3">
          <NavbarItem>
            <Link color="foreground" href="#">
              Features
            </Link>
          </NavbarItem>
          <NavbarItem isActive>
            <Link href="#" aria-current="page" color="secondary">
              Customers
            </Link>
          </NavbarItem>
          <NavbarItem>
            <Link color="foreground" href="#">
              Integrations
            </Link>
          </NavbarItem>
        </NavbarContent>
      </NavbarContent>

      <NavbarContent as="div" className="items-center" justify="end">
        <Input
          classNames={{
            base: "max-w-full sm:max-w-[10rem] h-10",
            mainWrapper: "h-full",
            input: "text-small",
            inputWrapper:
              "h-full font-normal text-default-500 bg-default-400/20 dark:bg-default-500/20",
          }}
          placeholder="Type to search..."
          size="sm"
          startContent={<SearchIcon size={18} />}
          type="search"
        />
        <Dropdown placement="bottom-end">
          <DropdownTrigger>
            <Avatar
              isBordered
              as="button"
              className="transition-transform"
              color="secondary"
              name="Jason Hughes"
              size="sm"
              src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
            />
          </DropdownTrigger>
          <DropdownMenu aria-label="Profile Actions" variant="flat">
            <DropdownItem key="profile" className="h-14 gap-2">
              <p className="font-semibold">Signed in as</p>
              <p className="font-semibold">zoey@example.com</p>
            </DropdownItem>
            <DropdownItem key="settings">My Settings</DropdownItem>
            <DropdownItem key="team_settings">Team Settings</DropdownItem>
            <DropdownItem key="analytics">Analytics</DropdownItem>
            <DropdownItem key="system">System</DropdownItem>
            <DropdownItem key="configurations">Configurations</DropdownItem>
            <DropdownItem key="help_and_feedback">Help & Feedback</DropdownItem>
            <DropdownItem key="logout" color="danger">
              Log Out
            </DropdownItem>
          </DropdownMenu>
        </Dropdown>
      </NavbarContent>
    </Navbar>
  );
}

**Comment by wingkwong** [comment]
@ahsan-abrar are you using the latest version?

![image](https://github.com/nextui-org/nextui/assets/35857179/278a3f21-3ba3-4a15-a503-b21cd873d9d5)

**Comment by ahsan-abrar** [comment]
yes 

``` javascript
{
  "name": "orbitab_store",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@nextui-org/react": "^2.3.6",
    "framer-motion": "^11.2.6",
    "next": "14.2.3",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5",
    "autoprefixer": "^10.4.19"
  }
}

```

**Comment by ahsan-abrar** [comment]
@wingkwong I am using macOS 12.7.5 (21H1222), and chrome

**Comment by wingkwong** [comment]
Can you share a video record or a stackblitz project?

**Comment by ahsan-abrar** [comment]
@wingkwong 

https://github.com/nextui-org/nextui/assets/58684529/6a4f59ee-4497-4240-8b77-78cfc8fe2db2

**Comment by wingkwong** [comment]
this is what i see.

[issue-2248-demo.webm](https://github.com/nextui-org/nextui/assets/35857179/ce3beecc-3c00-4133-8656-bec205f1d9e9)

**Comment by ahsan-abrar** [comment]
@wingkwong  https://github.com/ahsan-abrar/ecommerce

**Comment by Arsenic-01** [comment]
Facing same issue please help

**Comment by SmallKi** [comment]
@wingkwong  I found the point of this problem. In official website, it uses CommonJs standard for setting tailwindcss, but nextjs framework uses UMD standard. So if a fresher just copy and paste all the content in nextui tailwindcss settings to `tailwind.config.ts` file, it will overlay the default setting. And then the tailwindcss is uneffective in their own components.  
Maybe document can update this part more clearly for fresher.

**Comment by SmallKi** [comment]
The correct version of `tailwind.config.ts`
```ts
// tailwind.config.ts
import type { Config } from "tailwindcss";
const {nextui} = require("@nextui-org/react");

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [nextui()],
};

export default config;

```

The wrong version:
```ts
import type { Config } from "tailwindcss";
const {nextui} = require("@nextui-org/react");

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};

module.exports = {
  content: [
    // ...
    // make sure it's pointing to the ROOT node_module
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [nextui()],
};

export default config;

```

**Comment by wingkwong** [comment]
I'll take a look. Thanks for the finding.

**Comment by SmallKi** [comment]
> @wingkwong https://github.com/ahsan-abrar/ecommerce
your tailwindcss config is not correct, try move your components to `/components` folder, or change your tailwind file:
```ts
....
const config: Config = {
  content: [
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",   // 👈 need header component to be placed in ./components, but header is placed in ./_src/components
    "./_src/components/**/*.{js,ts,jsx,tsx,mdx}" // 👈 add this line, header will be fixed;
  ],
....
```
