### ISSUE TITLE
[Feature Request] We really need a Alert component.

### ISSUE THREAD

**Issue by nayanrabiul** [nextui-org/nextui#2250]
### Is your feature request related to a problem? Please describe.

i want to notify the user about their action but i culdnt find any alert component for that . what i mean by alert you can see below picturecould

### Describe the solution you'd like

I was surprised to see no alert component. How did they miss that, especially considering it is a pretty good React UI library?

I would like to suggest the alert component. Similar to toast, however,
it can be used to share larger chunks of information in page, can also be used as an
alternative to toasts. It displays by default and does not leave until the user removes (if needed)
e.g info alert, warning alert, success alert, etc
like a good idea to have an alert that stays on the page reminding users what to do.

### Describe alternatives you've considered

I have considered using the modals as an alternative solution to a page alert
but it doesn't quite seem to do the trick because modals need to be triggered. If
triggered by default, users can close this without actually reading the message. It seems
like a good idea to have an alert that stays on the page reminding users what to do.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/38776310/f2ae0d14-39f8-4c52-9601-2e3baa53899b)

**Comment by DannyKuk** [comment]
Agree, some Alerts, basically toast in general would be needed badly.
Would be also amazing if it would be some kind of parameter "isAutoClose" or similar to trigger the auto close or the users need to close it.

**Comment by khylpe** [comment]
Absolutely agree with your feature request. The absence of an alert component is indeed surprising.

**Comment by jonathanrich1986** [comment]
Yes please!

**Comment by DemonKHH** [comment]
agree more,that's why i cant use nextui, please add it

**Comment by abhinav700** [comment]
@wingkwong Can you assign this issue to me? would love to work on it.

**Comment by alvinBM** [comment]
We're really excited about the possibility of having an alert component! It would be a fantastic addition, and we can't wait to see it implemented.

**Comment by abhinav700** [comment]
> We're really excited about the possibility of having an alert component!

Will begin working on it As soon as I get the assignment from @wingkwong

**Comment by wingkwong** [comment]
> > We're really excited about the possibility of having an alert component!
> 
> 
> 
> Me too!
> 
> Will begin working on it As soon as I get the assignment from @wingkwong 
> 
> 
> 
> 
> 
> 

Hey. Please ping me at Discord for the discussion. We will work on the design first and relay to u once it s done.

**Comment by abhinav700** [comment]
@wingkwong Should I Dm You or tag you in a channel?

**Comment by wingkwong** [comment]
DM me pls thanks

**Comment by vitalijalbu** [comment]
Guys, go with **shadcn** or **radix themes**.

**Comment by vitalijalbu** [comment]
🛟 discord server **shadcn**: https://discord.gg/nSBBXVgn

**Comment by abhinav700** [comment]
> DM me pls thanks

Okay
