### ISSUE TITLE
[BUG] - System input="date" placeholder overlaps next-ui label

### ISSUE THREAD

**Issue by antonfrolovsky** [nextui-org/nextui#2255]
### NextUI Version

2.2.9

### Describe the bug

I am experiencing an issue in the Next-UI library where the system placeholder for the input type 'date' is overlapping with the Next-UI label

And also, this bug occurred with the time, month, and week input types:
<img width="596" alt="Screenshot 2024-01-28 at 4 07 41 PM" src="https://github.com/nextui-org/nextui/assets/2322736/0b21dcee-ab7b-4144-ab8b-6a66bf8a4db3">

### Your Example Website or App

https://codesandbox.io/p/devbox/date-input-bug-ld9k24

### Steps to Reproduce the Bug or Issue

Just create 
```
<Input type="date" label="Date" />

### Expected behavior

System placeholder must be hidden or it must not overlap label

### Screenshots or Videos

See in [codesandobx](https://codesandbox.io/p/devbox/date-input-bug-ld9k24)

### Operating System Version

macOS

### Browser

Chrome

**Comment by getellez** [comment]
I have the same issue

**Comment by Auncon2** [comment]
I have the same issue

**Comment by wingkwong** [comment]
@Auncon2 are you using latest version? if so, please share a sandbox.
