### ISSUE TITLE
[BUG] - Accordion `itemClassNames` do not pass class strings

### ISSUE THREAD

**Issue by tayloraucoin** [nextui-org/nextui#2261]
### NextUI Version

latest

### Describe the bug

No class strings are distributed to components of accordion

### Steps to Reproduce the Bug or Issue

1. Open you basic usage example for Accordion https://codesandbox.io/p/devbox/mystifying-bohr-k978ys 
2. Add this property:
itemClassNames={{
      base: "!px-0",
      heading: "!px-0",
      trigger: "!px-0",
      titleWrapper: "!px-0",
      title: "!px-0",
      subtitle: "!px-0",
      startContent: "!px-0",
      indicator: "!px-0",
      content: "!px-0",
    }}
3. Notice there is no change in the rendering window + no classNames are found anyone using the devtools. 

### Expected behavior

Classnames are passed accordingly to the accordion

### Screenshots or Videos

<img width="944" alt="Screen Shot 2024-01-17 at 12 19 49 PM" src="https://github.com/nextui-org/nextui/assets/10913613/c9aa730a-00da-4811-8589-36a41f4554fa">
<img width="868" alt="Screen Shot 2024-01-17 at 12 22 15 PM" src="https://github.com/nextui-org/nextui/assets/10913613/d9901329-d4a3-4115-8ab6-5adf8b229628">

### Operating System Version

macOS

### Browser

Chrome

**Comment by tayloraucoin** [comment]
I've been able to see the className in some of the deeper children, but the more parent ones, namely what I perceive to be the `base` is not affected. Namely trying to disable the `px-2` by default.

**Comment by LauraCastrillonMp** [comment]
You need write 'itemClasses' instead 'itemsClassNames' and if you want, you could delete all the exclamations signs in case you don't need them

Like this:
![image](https://github.com/nextui-org/nextui/assets/129574887/21a2ee08-7e58-4936-a8f4-33c6189e3e34)

**Comment by wingkwong** [comment]
Closing - answered [here](https://github.com/nextui-org/nextui/issues/2261#issuecomment-1897198144).

**Comment by andyhftang** [comment]
I came here because I was sleepy and made the same stupid mistake.
The px-2 you want to disable is not an "itemClass", so you don't need itemClasses at all.
It is the most outer class, put it in className is fine.

<img width="549" alt="image" src="https://github.com/user-attachments/assets/04828558-5e7e-42a4-9431-e02ae5674e58">
