### ISSUE TITLE
Documentation search

### ISSUE THREAD

**Issue by tomsq** [nextui-org/nextui#227]
**Describe the bug**
When searching in the docs, the search bar works nicely, when hitting `cmd + k`, the searching doesn't yield any results.

**Steps to reproduce**
1. Go to the official documentation website
2. Press `cmd + k`
3. Try to search for some component
4. Nothing is found

**Environment / Context**
- Desktop
- Operating System: macOS
- Browser and version: Chrome Version 97.0.4692.99
- Device: Macbook Pro

**Comment by jrgarciadev** [comment]
Hey @tomsq thanks for the suggestion, we have this in the roadmap https://github.com/nextui-org/nextui/issues/116, currently, the searching modal search only the items are showing, there's a notice that says `For an advanced search please use the search input`, we hope to add the advance search also to the modal search soon

![Screenshot 2022-02-05 at 10 15 13](https://user-images.githubusercontent.com/30373425/152643695-3c6e81c5-f0c2-44f5-9763-e83f7416061f.png)
