### ISSUE TITLE
[BUG] - Start with `pnpm`

### ISSUE THREAD

**Issue by cha2hyun** [nextui-org/nextui#2277]
### NextUI Version

current

### install with pnpm 
> `pnpm create next-app -e https://github.com/nextui-org/next-app-template` 
<img width="802" alt="image" src="https://github.com/nextui-org/nextui/assets/56015532/7d89e5e3-15c7-47ab-b703-ba4f87d62975">

### result 
<img width="1074" alt="image" src="https://github.com/nextui-org/nextui/assets/56015532/05cf2b08-92b5-4ae6-8fcb-e7bf39781219">

### Steps to Reproduce the Bug or Issue

1. `pnpm create next-app -e https://github.com/nextui-org/next-app-template` 
2. `✔ What is your project named? … test`
3. `cd test`
4. `pnpm install`
5. `pnpm dev`

### Expected behavior

-

### Operating System Version

- pnpm version : 8.14.1

### Browser

Chrome

**Comment by Cowjiang** [comment]
I think the issue is due to the missing .npmrc setting and pls refer to [here](https://nextui.org/docs/guide/installation#setup-pnpm-optional)

Add the following code to your .npmrc file
`public-hoist-pattern[]=*@nextui-org/*`
then pls run `pnpm install` again :)
