### ISSUE TITLE
Components/Card

### ISSUE THREAD

**Issue by Pedro-99** [nextui-org/nextui#228]
The Card.Image component does not working until i replaced it with the Image component of NextJs

**Comment by jrgarciadev** [comment]
Hey @Pedro-99 could you please provide more context? or a CodeSanbox link to the problem you are mentioning?, in order to help you, thanks!

**Comment by Pedro-99** [comment]
these are the imported files
<img width="369" alt="c2" src="https://user-images.githubusercontent.com/57238132/152645399-085e83ba-697c-49f8-b4eb-8f28436ad481.PNG">
and this is the the first result that was not working ( <Card.Image />  from "nextui-org" ) 
<img width="465" alt="r" src="https://user-images.githubusercontent.com/57238132/152645494-ace80673-b55c-4992-af54-67eacd52db1f.PNG">
<img width="937" alt="r2" src="https://user-images.githubusercontent.com/57238132/152645653-11143846-3240-47ca-b62e-c52910562b63.PNG">
and this is the console:
<img width="725" alt="c" src="https://user-images.githubusercontent.com/57238132/152645539-a44884db-9a74-4115-8b1e-3721de32918c.PNG">
after that i replaced the <Card.image /> with <Image /> component from "next/Image" as shown below
<img width="547" alt="c1" src="https://user-images.githubusercontent.com/57238132/152645603-1c0c2f9a-d2ac-4013-9cad-91669bf5d767.PNG">
and this is the second result
<img width="940" alt="r1" src="https://user-images.githubusercontent.com/57238132/152645644-23756e49-5505-465f-a9a4-af832d184cda.PNG">
and this image below represent an array of objects (fruits) 

<img width="163" alt="c3" src="https://user-images.githubusercontent.com/57238132/152645687-2fd9f6ba-3909-45f5-9cac-09df5605857f.PNG">

**Comment by jrgarciadev** [comment]
Hey @Pedro-99 could you please use this example as a reference to find out the differences with what you are doing-> https://codesandbox.io/s/nextui-cards-91ny8 

Hope it helps you 🙌🏼

**Comment by Pedro-99** [comment]
i found the problem.
that was not working because the assets are not in the public folder so i copy them to the public folder and added  '/' before the url and that's working well, but i don't know why when i replaced (Card.Image from nextui-org) with (Image from next/Image) it was working well even the assets are outside the public folder.
note: the code you have sent working because you used an absolute URL in the src images.

**Comment by jrgarciadev** [comment]
Great 🙌🏼. , under the hood, the `Card.Image` uses an `<img>` component so you can try using a simple `<img>` component but I recommend that you always use the resources from the `public` path in an absolute way otherwise you could have troubles once you deploy your project. Due to this wasn't an issue I'm going to close it
