### ISSUE TITLE
[Feature Request] Request for Carousel Component Addition

### ISSUE THREAD

**Issue by codebyaadi** [nextui-org/nextui#2286]
### Is your feature request related to a problem? Please describe.

My feature request is related to enhancing the user interface by adding a carousel component. Currently, we lack an efficient way to display and navigate through a series of images or content seamlessly. The addition of a carousel component would address this need and improve the overall user experience by providing a visually appealing and user-friendly way to showcase content within the application.

### Describe the solution you'd like

I would like the addition of a versatile carousel component that allows users to display and navigate through a series of images or content. The ideal solution should be customizable, supporting options such as autoplay, navigation arrows, and pagination. It should also be easy to integrate into existing UI elements, allowing developers to adapt its appearance and behavior to suit the application's design. Additionally, it would be beneficial if the carousel supports responsive design for optimal performance across various screen sizes.

### Describe alternatives you've considered

I would like the addition of a versatile carousel component that allows users to display and navigate through a series of images or content. The ideal solution should be customizable, supporting options such as autoplay, navigation arrows, and pagination. I recommend considering the use of Framer Motion, a powerful animation library for React, to implement the carousel. Framer Motion can provide smooth animations, transitions, and a flexible API for creating dynamic and engaging user interfaces. It's known for its ease of use and compatibility with React applications, making it a great choice for enhancing the overall user experience. The carousel component should seamlessly integrate with Framer Motion to leverage its capabilities and ensure optimal performance.

**Comment by wingkwong** [comment]
Duplicate - keep track in https://github.com/nextui-org/nextui/issues/2177
