### ISSUE TITLE
[BUG] - Failed to fetch RSC payload, falling back to browser navigation when using Tab, DropdownItem etc

### ISSUE THREAD

**Issue by elanclarkson** [nextui-org/nextui#2289]
### NextUI Version

2.2.9

### Describe the bug

Navigation using the App Router is falling back to browser navigation when using NextUI link components like Tab, DropdownItem etc.

The error message `Failed to fetch RSC payload for http://localhost:3000/page_url_here. Falling back to browser navigation.` is displayed briefly before a full page refresh is carried out to the next page.

I have not delved into the code, but one possibility for this could be that default browser navigation is causing the RSC payload request to fail, in which case these components may just need to use `e.preventDefault()` to avoid this.

### Your Example Website or App

https://github.com/nextui-org/next-app-template

### Steps to Reproduce the Bug or Issue

1) Download and install the default next app template.
2) Add tabs.tsx component to the components folder containing the following:

```
'use client';

import { Tabs, Tab } from "@nextui-org/tabs";
import { usePathname, useRouter } from 'next/navigation';

export default () => {
    const pathname = usePathname();

    return (
        <Tabs key="dashboardNavigation" selectedKey={pathname} variant="underlined" aria-label="Dashboard navigation">
            <Tab key="/blog" title="Blog" href="/blog" />
            <Tab key="/about" title="About" href="/about" />
        </Tabs>
    );
};
```
3) Import this new component into app/layout.tsx and render it beneath the `<Navbar />`.

You will see the error appear briefly before a full page refresh when using the tabs to navigate, while this issue doesn't occur when using the links in the navbar to navigate.

### Expected behavior

I expect standard App Router navigation to occur when using the tabs.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by elanclarkson** [comment]
Any update on this issue? Anyone else able to reproduce it on the example project?

I am still experiencing it after updating to NextUI v2.3.6, and it is a big problem because I am losing state between browser page changes.

**Comment by wingkwong** [comment]
I'd mark this on hold first. I could reproduce the problem in latest version but in my local environment. The next bug fix release will be on 20th May. I'll retest it after that.

This is the canary version in case you need that.

```
"@nextui-org/system": "0.0.0-canary-20240513132504"
```

**Comment by wingkwong** [comment]
Closing - please use the latest version (v2.4.0)

**Comment by elanclarkson** [comment]
Thanks @wingkwong but this issue has not been resolved when navigating with dropdown items. I will see if I can create a repro.

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3240
