### ISSUE TITLE
Buttons with icons have uncomfortable padding

### ISSUE THREAD

**Issue by jescalan** [nextui-org/nextui#229]
**Describe the bug**
When you add an icon to a button, it does not adjust to accommodate in the button's padding, which leads to it looking like a design error.

For example:

![](https://p176.p0.n0.cdn.getcloudapp.com/items/7KuqWO7n/f8d17b66-a79f-4d60-b2e9-8e0c9fbeebe4.png?v=63b09cc7a8545267b4af803ba9000521)

**Steps to reproduce**
1. Implement the `Button` component with the `icon` property
2. Note that it does not look good

**Expected behaviour**

I manually corrected the padding in the console to represent what I think looks correct:

![](https://p176.p0.n0.cdn.getcloudapp.com/items/4guZXdDj/437a68ea-c366-4c95-8c29-5b8b56aa06a1.png?v=ec9eb6807f08541649a89c34bee642aa)

**Screenshots**
Screenshots are included above!

**Environment / Context**
- Desktop
- MacOS
- Chrome Latest
- Device: MacBook

**Comment by jrgarciadev** [comment]
Hey @jescalan thanks for reporting this, we will fix it as soon as possible 🙏🏻

**Comment by jrgarciadev** [comment]
Hey @jescalan 🙌🏼 , The new version was released, please try this in case it has not been resolved we reopen the issue, thank you very much! https://github.com/nextui-org/nextui/releases/tag/v1.0.2-beta.4

**Comment by jescalan** [comment]
@jrgarciadev You all are amazing! Will definitely try it out soon 🎉

**Comment by jescalan** [comment]
This is working great as long as the `auto` prop is on the button, but without that prop the padding still is weird. Solves the problem for me though, thank you again!
