### ISSUE TITLE
 Dropdown Unexpectedly Closes on Item Selection Despite closeOnSelect Being Set to False

### ISSUE THREAD

**Issue by XkoderFX** [nextui-org/nextui#2290]
### NextUI Version

2.2.9

### Describe the bug

I'm experiencing an unexpected behavior with the closeOnSelect property in a `DropdownItem` component. Contrary to the expected functionality, the Dropdown closes upon the item selection, even though `closeOnSelect` is explicitly set to `false`.

### Your Example Website or App

https://codesandbox.io/p/devbox/dazzling-williams-x2q5sh

### Steps to Reproduce the Bug or Issue

1. create a  `DropdownItem` component with multiple selectable items.
2. Explicitly set the `closeOnSelect` property to false for a `DropdownItem`.
3. Notice that the Dropdown menu closes upon the selection, contrary to the expected behavior.

### Expected behavior

When `closeOnSelect` is set to false, selecting the item with `closeOnSelect`  should not close the Dropdown menu.

### Operating System Version

macOS (13.6.3)

### Browser

Edge

**Comment by XkoderFX** [comment]
any updates on it?

**Comment by kuri-sun** [comment]
Hi @XkoderFX! Thanks for reporting the issue! I will take a look at this and fix it accordingly! Thank you 😄

**Comment by Oladapoolasunkanmi** [comment]
"@nextui-org/react": "^2.6.8"

i am experiencing this issue
