### ISSUE TITLE
[BUG] - Navbar Import's

### ISSUE THREAD

**Issue by AthulKkumar** [nextui-org/nextui#2291]
### NextUI Version

latest

### Describe the bug

In Navbar  component the code which provide for the Navbar some of the import of the components in it is not added the code snippet.

### Steps to Reproduce the Bug or Issue

Go to Navabar components
Copy the code snippet of the component
the paste it in your code to run it 
it will show error which some of the components is not defined (Basically an import issue)

### Expected behavior

What I was expecting is when i copy this code into my code base and run for first time it should need to work properly.

### Operating System Version

Any

### Browser

Chrome

**Comment by kuri-sun** [comment]
Hi @AthulKkumar, I was trying to reproduce the bug in the way that you explained above. however, I could not reproduce the bug for me. Could you please give me the code that throws the error or the details of how to reproduce this one?

**Comment by wingkwong** [comment]
Closing - inactivity.
