### ISSUE TITLE
DropdownMenu - onAction

### ISSUE THREAD

**Issue by MuhammadZubair210** [nextui-org/nextui#2296]
### NextUI Version

2.2.9

### Describe the bug

We are not able to select an item from the DropdownMenu using VR. And the same issue is happening with Apple Macbook M3 pro's trackpad click. The issue is persisting in the official documentation of @nextui-org/react.

Can you check whats causing this issue ? 

### Your Example Website or App

https://drive.google.com/file/d/1DvF20mD2MSPvcgtE8ncwt7lQTiiJ6T6L/view

### Steps to Reproduce the Bug or Issue

Select an item in the DropDownMenu from a VR headset, or select an item from Macbook M3 pro's trackpad click.

### Expected behavior

We should be able to select the item using VR's and trackpad clicks of Macbook pro M3.

### Operating System Version

VR, macOS

### Browser

Chrome

**Comment by mameikagou** [comment]
I solved it by updating my version form "v2.3.1" to "v2.4.0"

**Comment by mameikagou** [comment]
> I solved it by updating my version form "v2.3.1" to "v2.4.0"

<img width="494" alt="a296b055f1c97b3fc3c4dbd591d773c" src="https://github.com/user-attachments/assets/28b621b0-3861-40ea-a786-9121b8c14aa5">

**Comment by wingkwong** [comment]
Just FYI. The current latest is already v2.4.6.
