### ISSUE TITLE
[BUG] - Lack of RTL Support in Input 

### ISSUE THREAD

**Issue by mrbadri** [nextui-org/nextui#2315]
### NextUI Version

2.0.10

### Describe the bug

The repository does not work correctly when the direction is set to RTL (Right-to-Left). Elements are not displayed as expected, leading to usability issues.

### The label is not in the right place
[See Here](https://storybook.nextui.org/?path=/story/components-input--label-placement&globals=locale:ar-AE)

![image](https://github.com/nextui-org/nextui/assets/85818966/e95657a2-ace7-4c4d-8e38-e9086eb88a10)

### The Clear Button is not in the right place
[See Here](https://storybook.nextui.org/?path=/story/components-input--clearable&globals=locale:ar-AE)

![image](https://github.com/nextui-org/nextui/assets/85818966/8940b16a-ce39-4421-899d-2b32fc128e8e)

### Steps to Reproduce the Bug or Issue

1. Go to [https://storybook.nextui.org/?path=/story/components-input--label-placement&globals=locale:ar-AE]
2. Change the document direction to RTL (locale: Arabic).
3. Observe the issues mentioned above.

### Expected behavior

I expected the UI to properly support RTL direction, with elements aligning and displaying correctly from right to left.

### Operating System Version

All

### Browser

Chrome

**Comment by Aux9** [comment]
Hi, I'm new to GitHub buy yes, I have the same problem. any workaround to solve it?

**Comment by Aux9** [comment]
Hi, I'm new on GitHub and this is my first comment and yes, I have this issue too!
