### ISSUE TITLE
[BUG] - console error inside <Input> when hitting shift key

### ISSUE THREAD

**Issue by Berdugo1994** [nextui-org/nextui#2317]
### NextUI Version

2.2.9

### Describe the bug

When hitting shift key inside <Input> component I'm receiving a console error.
``` 
VM41982:14 Uncaught TypeError: inputTypes.contains is not a function
    at isTextElement (<anonymous>:14:31)
    at <anonymous>:31:26
    at <anonymous>:66:3
```

Seems that there is a usage of js builtin:  *contains* method instead of *includes*

### Steps to Reproduce the Bug or Issue

1. Add <Input> component
2. Hit shift keyboard
3. Check console

### Expected behavior

No error should be happen when hitting shift key.

### Screenshots or Videos

<img width="933" alt="image" src="https://github.com/nextui-org/nextui/assets/62346207/e95a69e7-f8b7-4d7b-a6d8-8b121e51a675">

### Operating System Version

macOS 17.3

### Browser

Chrome

**Comment by imhalid** [comment]
I think this is a problem with react because I get this error even though I use pure input and react.

**Comment by kuri-sun** [comment]
Hi @Berdugo1994, I was trying to reproduce this error, however I did not get the result that you explained above. Could you give me more details about how to reproduce this bug?

**Comment by Berdugo1994** [comment]
Based on the following dependencies:
next 14.1.0
react 18.2.0
nextui-org/react 2.2.9

When using <Input> component and hitting Shift button on keyboard it occurs.
<img width="820" alt="image" src="https://github.com/nextui-org/nextui/assets/62346207/bea7864d-3385-463f-be11-f5d01065688e">

**Comment by kuri-sun** [comment]
@Berdugo1994 Thank you for the reply. I created my NextJS project for this, however, I could not see the same error. Could you please send me a simple sandbox or provide the reproducing code?

**Comment by wingkwong** [comment]
Closing - not able to reproduce + inactivity.
