### ISSUE TITLE
[BUG] - Tabs individual import error in server components

### ISSUE THREAD

**Issue by grigorzyapkov** [nextui-org/nextui#2320]
### NextUI Version

2.2.9

### Describe the bug

Individually import Tabs component in a server side component causes an error.

import { Tab, Tabs } from '@nextui-org/tabs'

Uncaught Error: Unknown element <[object Object]> in collection.

### Steps to Reproduce the Bug or Issue

1. Create server side component
2. import { Tab, Tabs } from '@nextui-org/tabs'
3. Expect an error: Uncaught Error: Unknown element <[object Object]> in collection.

### Expected behavior

Should not throw an error.

### Operating System Version

any

### Browser

Chrome

**Comment by alexander-densley** [comment]
having the same issue

**Comment by Gascon1** [comment]
Also having the same issue

**Comment by sadeq-qafari** [comment]
I have the same problem, any update?

**Comment by sadeq-qafari** [comment]
> > I have the same problem, any update?
> 
> add "use client" at the header of the file. the problem will be resolved.

Im aware of this solution, I want tabs to work in server side component.

**Comment by AveshLutchman** [comment]
See: https://github.com/nextui-org/nextui/issues/1403

This issue has been here for a while now.

**Comment by HomerDoh** [comment]
Same problem

**Comment by steebchen** [comment]
It would be great if server components could be supported. Of course 'use client' makes the error go away, but that basically prevents all of the contents not being rendered at all on the server, so crawlers will not see this content unless they use JS rendering.

**Comment by Yusuf-96** [comment]
I got this error when using Tabs component in Next js version 14.2.13 even mark the component as client still does not work
⨯ Error: Functions are not valid as a child of Client Components. This may happen if you return children instead of <children /> from render. Or maybe you meant to call this function rather than return it.
  <... aria-label=... items={[...]} children={function children}>

**Comment by wingkwong** [comment]
closing - since 2.3.5, you can use individual package without adding `use client` directive.

**Comment by djyde** [comment]
I'm using `import { Tab, Tabs } from "@heroui/tabs"` but same issue

**Comment by djyde** [comment]
And my workaround is to create another client component and pass the tabs item as an array: 

```tsx
// @/components/tabs.tsx

'use client'

import { Tab, Tabs as NextUITabs, TabsProps } from "@heroui/tabs"

export function Tabs(props: TabsProps & {
  tabs: Array<{
    title: React.ReactNode,
    key: string,
    children: React.ReactNode,
  }>
}) {
  return <NextUITabs {...props}>
    {props.tabs.map((tab) => (
      <Tab key={tab.key} title={tab.title}>
        {tab.children}
      </Tab>
    ))}
  </NextUITabs>
}
```
