### ISSUE TITLE
[BUG] - Multiple Selection in Table

### ISSUE THREAD

**Issue by Lucasmm016** [nextui-org/nextui#2326]
### NextUI Version

2.2.9

### Describe the bug

When using multiple selection in the Table component, the console prints the following error:

```
Warning: Prop `data-key` did not match. Server: "row-header-column-1aed883sgup" Client: "row-header-column-qi6viwawvf9"
```

I'm using Next.js 13 and adopting the guidance of NextUI (upgrade to v2) using client-side components.

### Steps to Reproduce the Bug or Issue

Use multiple selection for the Table component.
Example: ```<Table selectionMode="multiple">```

### Expected behavior

no errors were expected.

### Screenshots or Videos

<img width="1680" alt="image" src="https://github.com/nextui-org/nextui/assets/65104584/aed93de0-8da5-4bac-8821-9e0d30918267">

### Operating System Version

MacOS

### Browser

Safari

**Comment by rsemihkoca** [comment]
i have solved mine with [link](https://github.com/nextui-org/nextui/issues/779#issuecomment-1742122331)

**Comment by manuelffernandez** [comment]
I solved the issue by following [this suggestion](https://nextjs.org/docs/messages/react-hydration-error#solution-1-using-useeffect-to-run-on-the-client-only) from the official Next.js documentation. The solution involves making the component that imports the Table component from NextUI a client component. Then, you use the useState hook in combination with useEffect to render the table after the pre-rendered content is sent to the browser. The solution will be

```typescript
"use client"

import { useState, useEffect } from 'react'
 
export default function YourComponent() {
  const [isClient, setIsClient] = useState(false)
 
  useEffect(() => {
    setIsClient(true)
  }, [])
 
  return (
    <div>
      {isClient ? (
        <Table selectionMode="multiple">
          {/* Table code... */}
        </Table>
      ) : null}
    </div>
  )
}
```

The "use client" declaration alone isn't enough to resolve the issue; the little hook trick is still necessary. I’m not sure why Next.js is pre-rendering a client component despite the declaration.
