### ISSUE TITLE
[BUG] - `outside-left` label does not focus input

### ISSUE THREAD

**Issue by ai212983** [nextui-org/nextui#2328]
### NextUI Version

2.2.9

### Describe the bug

When clicked on the label with `outside-left` placement, input doesn't get focus.

### Your Example Website or App

https://storybook.nextui.org/?path=/story/components-input--label-placement

### Steps to Reproduce the Bug or Issue

1. Open [official storybook page](https://storybook.nextui.org/?path=/story/components-input--label-placement) or [documentation page](https://nextui.org/docs/components/input#label-placements).
2. Click on "Email" label with `outside-left` placement.
3. Nothing happens.

Reproducible in Chrome, Safari and Firefox

### Expected behavior

I am expecting the same behaviour as clicking on `Email` label with `outside` placement with placeholder.

### Operating System Version

macOS

### Browser

Chrome

**Comment by ShrinidhiUpadhyaya** [comment]
Hi @wingkwong or @jrgarciadev , could you assign this to me, i can have a look into it. Thanks!!

**Comment by wingkwong** [comment]
@ShrinidhiUpadhyaya go ahead.
