### ISSUE TITLE
[BUG] - Accordion Controlled Example shows errors

### ISSUE THREAD

**Issue by chasemcdo** [nextui-org/nextui#2337]
### NextUI Version

2.2.9

### Describe the bug

When following the [controlled accordion example](https://nextui.org/docs/components/accordion#controlled) I am seeing the following error despite the functionality working as expected.
```
Type 'Dispatch<SetStateAction<Set<string>>>' is not assignable to type '(keys: Selection) => any'.
  Types of parameters 'value' and 'keys' are incompatible.
    Type 'Selection' is not assignable to type 'SetStateAction<Set<string>>'.
      Type 'string' is not assignable to type 'SetStateAction<Set<string>>'.ts(2322)
```

Changing the erroring line to the following resolves the issue as a workaround:
```
onSelectionChange={(keys: Selection) => setSelectedAccordionKeys(keys as Set<string>)}
```

### Steps to Reproduce the Bug or Issue

1. Follow controlled example
2. View error

### Expected behavior

Controlled example works without errors

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/74692158/6f9d69c9-b6de-453d-a0f0-ab6b6aa93187)

### Operating System Version

macOS

### Browser

Chrome

**Comment by kuri-sun** [comment]
Hi @chasemcdo, I will take a look at this one! Thanks!
