### ISSUE TITLE
[BUG] - The popover part of select and autocomplete component scrolls down along with the page when I scroll down the page.

### ISSUE THREAD

**Issue by NiroopR1999** [nextui-org/nextui#2340]
### NextUI Version

2.2.9

### Describe the bug

 The popover looks like it detached from select or autocomplete component when I scroll down the page.

### Steps to Reproduce the Bug or Issue

1. Create a Select or Autocomplete component with any random data.
2. Make a page with some content that makes it scrollable.
3. Place the Select or Autocomplete component at the top of the page.
4. Open the content/popover of the Select or Autocomplete component and try to scroll the page.
5. Now, the popover part scrolls down along with the page.

### Expected behavior

1. Popover part should stick to select component weather the page scrolls down or scrolls up. 

### Operating System Version

Windows

### Browser

Edge

**Comment by lmalvasia** [comment]
I have the same issue :(

**Comment by martinraveglia** [comment]
Same issue here, as far as I understand the problem is that the popover is set as a child of <body>, but my <body> is not scrollable, the content is. 
Therefore, the popover sticks with the absolute position relative to the <body> while the content of the body scrolls freely.

**Comment by kitano0324** [comment]
ver. 2.2.9

I also encountered the same problem.
Although it's not a complete solution, I got around this problem by not being able to scroll when the popover is open.

```
export default function Select({...props}: SelectProps){
  const [isOpen, setIsOpen] = useState(false)
  const itemsRef = useRef<HTMLDivElement>(null)

  // スクロールを無効にする関数
  const disableScroll = (e: Event) => {
    if (itemsRef.current && !itemsRef.current.contains(e.target as Node)) {
      e.preventDefault()
    }
  }

  useEffect(() => {
    const events = ["scroll", "wheel", "touchmove"]

    if (isOpen) {
      // スクロールイベントを無効にする
      events.forEach((event) => {
        window.addEventListener(event, disableScroll, { passive: false })
      })
    } else {
      // スクロールイベントを有効に戻す
      events.forEach((event) => {
        window.removeEventListener(event, disableScroll)
      })
    }

    // コンポーネントがアンマウントされた時にイベントリスナーを削除
    return () => {
      events.forEach((event) => {
        window.removeEventListener(event, disableScroll)
      })
    }
  }, [isOpen])
    return (
      <Select
        scrollRef={itemsRef}
        isOpen={isOpen}
        onOpenChange={(open) => open !== isOpen && setIsOpen(open)}
        {...props}
      >
        {props.children}
      </ Select>
    )
}
```

**Comment by odling** [comment]
I had the same issue where the Select component is placed under a Modal for which the inside content is scrollable.

This could actually be fixed using portalContainer under popoverProps (which has a default value of document.body). Just provide a ref to the scrollable container and the issue is gone.

I'm using v2.2.10 btw.

**Comment by NaClYen** [comment]
> I had the same issue where the Select component is placed under a Modal for which the inside content is scrollable.
> 
> This could actually be fixed using portalContainer under popoverProps (which has a default value of document.body). Just provide a ref to the scrollable container and the issue is gone.
> 
> I'm using v2.2.10 btw.

My colleague also encountered the same problem. My solution is the same as yours, which is quite reasonable.  
The current default behaviour for elements not directly nested with the `body` element may not be ideal.

**Comment by mr-devboy** [comment]
My workaround 🥸

1. Wrap component (`<Select />` or `<Autocomplete />`) in `<div></div>`.
2. Add `position: relative` to the wrapper.
3. Save `ref` of the wrapper.
4. Pass the `ref` to `popoverProps={portalContainer: ref.current ?? undefined}`

**Comment by wingkwong** [comment]
In latest version, the new behavior, which follows RA, is the popover will be closed when you scroll outside. See [here](https://storybook.nextui.org/?path=/story/components-select--with-scrollable-container).
