### ISSUE TITLE
[BUG] - Select: Keys "" passed to "selectedKeys" are not present in the collection.

### ISSUE THREAD

**Issue by Marcin-HammerHeads** [nextui-org/nextui#2346]
### NextUI Version

2.2.9

### Describe the bug

"Select" component throws multiple warnings in the console in the example using `onChange` prop and doesn't set the placeholder.

Warning message:
> Select: Keys "" passed to "selectedKeys" are not present in the collection.

### Steps to Reproduce the Bug or Issue

1. Open Select component code snippet (Controlled using `onChange`) in the CodeSandbox
2. Open console in CodeSandbox

### Expected behavior

Placeholder in the select component won't display, multiple warnings in the console will show up.

### Screenshots or Videos

<img width="735" alt="select-bug" src="https://github.com/nextui-org/nextui/assets/116552768/7e72778f-0835-415b-b2a9-71a2543e842e">

### Operating System Version

macOS Sonoma 14.2.1

### Browser

Chrome

**Comment by kuri-sun** [comment]
Hi @Marcin-HammerHeads, Could you provide me with the code after you modified the Controlled code, please?

**Comment by kuri-sun** [comment]
Hi @Marcin-HammerHeads, Could you provide me with the code after you modified the Controlled code, please?

**Comment by Marcin-HammerHeads** [comment]
I did not modify the code, the issue arises immediately after opening the **second** example in the 'Controlled' section ("using onChange"). 
This issue is present even in the docs page:
<img width="1719" alt="controlled-bug" src="https://github.com/nextui-org/nextui/assets/116552768/10e6871e-e0a9-4900-901a-851bc239f38a">

**Comment by kuri-sun** [comment]
@Marcin-HammerHeads Thanks for the reply. Now I saw it! Thank you for creating a PR @sudongyuer !

**Comment by cmedina-dev** [comment]
Hi all,

While sudongyuer's PR is being reviewed, the following can be used as a workaround. Add the following as an item to your `Select` component:

```TS
<SelectItem
  key=""
  classNames={{
    base: 'hidden',
  }}
>
Enter your placeholder text here
</SelectItem>
```

Since the `Select` component's selectedKeys is searching for an empty key ('') on the initial render (I suspect because of the initial state being set with `const [exampleSelect, setExampleSelect] = useState('')`

This workaround adds a hidden `SelectItem` component to your `Select` component which allows the component to continue functioning normally while not affecting the legitimate items in your `Select`.

**Comment by Corepex** [comment]
> Hi all,
> 
> While sudongyuer's PR is being reviewed, the following can be used as a workaround. Add the following as an item to your `Select` component:
> 
> ```ts
> <SelectItem
>   key=""
>   classNames={{
>     base: 'hidden',
>   }}
> >
> Enter your placeholder text here
> </SelectItem>
> ```
> 
> Since the `Select` component's selectedKeys is searching for an empty key ('') on the initial render (I suspect because of the initial state being set with `const [exampleSelect, setExampleSelect] = useState('')`
> 
> This workaround adds a hidden `SelectItem` component to your `Select` component which allows the component to continue functioning normally while not affecting the legitimate items in your `Select`.

This worked for me. 
No console output so far.

Besides that, the `defaultSelectedKeys` doesn't react to a state change (if you for example load the items from a API).

Did i miss something?

**Comment by dssenkungu** [comment]
Adding the selected option (key) within a set worked for me

<Select name="permission" selectedKeys={new Set(["permision"])} >
      <SelectItem key="Overall">Overall</SelectItem>
 </Select>

Good luck
