### ISSUE TITLE
[BUG] - Sidebar not working correctly in docs

### ISSUE THREAD

**Issue by simPod** [nextui-org/nextui#2347]
### NextUI Version

2.2.9

### Describe the bug

Clear button section is not highlighted in sidebar

### Steps to Reproduce the Bug or Issue

Go to https://nextui.org/docs/components/input and click Clear button in side nav. It won't highlight.

### Expected behavior

Highlighted the item I clicked on

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/327717/7b9bb079-09cc-42b9-871f-8adcf1efc5c4)

https://github.com/nextui-org/nextui/assets/327717/cd6b2151-0a49-4dd1-827f-e164ad39a0b4

### Operating System Version

macos

### Browser

Chrome

**Comment by simPod** [comment]
I have the same problem on https://nextui.org/docs/components/button as well. I click Disabled and Sizes is highlighted 

![image](https://github.com/nextui-org/nextui/assets/327717/bc10ed6d-4ad1-4725-84c3-7e07161f69bf)

**Comment by kuri-sun** [comment]
Hi @simPod, I am using macOS and chrome. Also, I was trying to reproduce this but this does not happen for me. Could you help me to reproduce this once again? Thank you!

**Comment by simPod** [comment]
Hm, I just tried and cannot reproduce as well. Will try on my other screens as well and will get back here.

**Comment by wingkwong** [comment]
Closing - not reproducible.
