### ISSUE TITLE
[BUG] [Chip] - isOneChar works incorrectly with avatar prop

### ISSUE THREAD

**Issue by luixo** [nextui-org/nextui#2350]
### NextUI Version

2.2.9

### Describe the bug

Hello,
There is a specific way of styling `Chip` component when data is one char while maintaining [special styles](https://github.com/nextui-org/nextui/blob/0b5cde7bc4fc71231eb117f44052db2efdbdc595/packages/core/theme/src/components/chip.ts#L436) for combination of one char and close button.
I believe the same styles should be added in case `avatar` prop is used.

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-169waa

### Steps to Reproduce the Bug or Issue

1. `<Chip avatar={...}>X</Chip>`

### Expected behavior

Chip is not malformed

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Closing - fixed in `@nextui-org/react@2.2.10`
