### ISSUE TITLE
[BUG] - Components/Card

### ISSUE THREAD

**Issue by KevinKeyssx** [nextui-org/nextui#2351]
### NextUI Version

2.2.9

### Describe the bug

While integrating @nextui-org/react into my project, I encountered a TypeScript error indicating that the module does not export a 'Col' component, contrary to what is suggested in the documentation. My attempt to import Col from @nextui-org/react as shown below resulted in a TypeScript error:

`import { Card, Col, Text } from "@nextui-org/react";`

Error Message:

`Module '"@nextui-org/react"' has no exported member 'Col'.ts(2305)
Module '"@nextui-org/react"' has no exported member 'Text'.ts(2305)
Property 'Header' does not exist on type 'InternalForwardRefRenderFunction<"div", CardProps, never>'.ts(2339)`

This issue is causing confusion as I relied on the official documentation for guidance. I understand that this project is in beta and such discrepancies might occur. Could you please clarify if the Col component is supposed to be part of the @nextui-org/react exports? If not, what is the recommended approach for implementing column layouts with NextUI?

Thank you for your assistance and the work you're doing on this project. Looking forward to your guidance.

### Steps to Reproduce the Bug or Issue

Import 
`import { Card, Col, Text } from "@nextui-org/react";`

See the errors

`Module '"@nextui-org/react"' has no exported member 'Col'.ts(2305)
Module '"@nextui-org/react"' has no exported member 'Text'.ts(2305)
Property 'Header' does not exist on type 'InternalForwardRefRenderFunction<"div", CardProps, never>'.ts(2339)`

### Expected behavior

A correct import

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/55340042/a3291280-d4d0-42ec-a420-3d627818fd51)

And in the documentation:

![image](https://github.com/nextui-org/nextui/assets/55340042/265f54bc-4816-47f5-9e8c-170e6f2b51d5)

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
@KevinKeyssx I think you are using v2 while looking at the v1 doc. In v2 doc, I don't see the usage of Col under Card.
