### ISSUE TITLE
[BUG] - Textarea Resizing Not Working

### ISSUE THREAD

**Issue by harrycarp** [nextui-org/nextui#2354]
### NextUI Version

2.2.9

### Describe the bug

When entering content into the text-area, the content overflows, and the textarea does not resize.

![image](https://github.com/nextui-org/nextui/assets/33830630/66765b80-4c70-4889-bb04-7949d00ca11e)

I booted up a StackBlitz, but the issue was not there so I assume it is my instance.
I have cleared, cleaned and reinstalled but to no avail.

Digging into the class names appended to the input-wrapper, it appears that it's getting assigned .h-unit-10, but I cannot find the source of this assignment. I can override it with the classNames prop on the <Textarea /> element.

![image](https://github.com/nextui-org/nextui/assets/33830630/de3c7fdd-774d-44ed-bb3b-d6380ea38da3)

### Steps to Reproduce the Bug or Issue

1. Create NextJS 14.1.0 Project
2. Install all required dependencies
3. Add Textarea
4. See if it resizes

### Expected behavior

To resize appropriately, without the h-unit-10 overriding the elements height

### Operating System Version

MacOS

### Browser

Chrome

**Comment by ziponia** [comment]
In my case, the same phenomenon occurs when the important option in tailwind settings is set to true.

To solve this, 
I think the class name should be made public to the outside so that the wrapper class name can be specified.

```js
import type { Config } from "tailwindcss";
import { nextui } from "@nextui-org/react";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  // important: true, <-- this
  darkMode: "class",
  plugins: [nextui()],
};
export default config;

```

**Comment by harrycarp** [comment]
Fix worked for me! Thanks!

> In my case, the same phenomenon occurs when the important option in tailwind settings is set to true.
> 
> To solve this, I think the class name should be made public to the outside so that the wrapper class name can be specified.
> 
> ```js
> import type { Config } from "tailwindcss";
> import { nextui } from "@nextui-org/react";
> 
> const config: Config = {
>   content: [
>     "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
>     "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
>     "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
>     "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
>   ],
>   theme: {
>     extend: {},
>   },
>   // important: true, <-- this
>   darkMode: "class",
>   plugins: [nextui()],
> };
> export default config;
> ```
