### ISSUE TITLE
[BUG] - Listbox typing issue when using dynamic collections

### ISSUE THREAD

**Issue by Cowjiang** [nextui-org/nextui#2365]
### NextUI Version

2.2.9

### Describe the bug

When I try to use the Listbox & ListboxSection via dynamic collections, typing issue will be reported as below screenshot but rendering without any error.

![image](https://github.com/nextui-org/nextui/assets/57822554/21cb6c17-44f2-4518-8159-6e4c0dd67d47)

`TS2322: Type (item: ListboxItemBaseProps) => Element is not assignable to type
(ItemElement<ListboxItemBaseProps> | ItemElement<ListboxItemBaseProps>[] | ItemRenderer<ListboxItemBaseProps>) & (ReactI18NextChildren | Iterable<...>)
Type (item: ListboxItemBaseProps) => Element is not assignable to type ItemRenderer<ListboxItemBaseProps> & string
Type (item: ListboxItemBaseProps) => Element is not assignable to type string`

### Steps to Reproduce the Bug or Issue

```tsx
import { Listbox, ListboxItem, ListboxItemProps, ListboxSection, ListboxSectionProps } from '@nextui-org/react'
import { useState } from 'react'

const settingList: Partial<ListboxSectionProps<ListboxItemProps>>[] = [
  {
    key: 'application',
    title: 'Application',
    items: [
      {
        key: 'appearance',
        title: 'Appearance'
      }
    ]
  }
]

function Setting() {
  const [selectedKeys, setSelectedKeys] = useState(new Set(['text']))
  return (
    <Listbox
      selectionMode="single"
      selectedKeys={selectedKeys}
      onSelectionChange={setSelectedKeys}
      items={settingList}
    >
      {
        section => (
          <ListboxSection {...section}>
            {(item) => (
              <ListboxItem {...item} />
            )}
          </ListboxSection>
        )
      }
    </Listbox>
  )
}

export default Setting
```

### Expected behavior

Nah, please take a look

### Operating System Version

Windows

### Browser

Chrome

**Comment by Cowjiang** [comment]
and no issue if I don't use ListboxSection , like the example in document - `Listbox -> ListboxItem`
the issue only produce on `Listbox -> ListboxSection -> ListboxItem`

**Comment by yahorbarkouski** [comment]
hey @Cowjiang, perhaps you have found a solution already?

**Comment by Cowjiang** [comment]
> hey @Cowjiang, perhaps you have found a solution already?

Not yet, just add @ts-ignore : (

**Comment by ahmadbafrani** [comment]
I have the same issue when using `ListboxSection` with dynamic items.


`<Listbox
        aria-label='Page selection'
      >
        <ListboxSection items={items}>
          {(item) => (
            <ListboxItem
              key={item.key}
            >
              {item.title}
            </ListboxItem>
          )}
        </ListboxSection>
      </Listbox>
`

**Comment by kzroo** [comment]
You can also just wrap it in a fragment (`<> </>` is shorthand for `<Fragment> </Fragment>`)

```typescript
<ListboxSection {...section}>
    <>
            {(item) => (
              <ListboxItem {...item} />
            )}
    </>
</ListboxSection>
``` 

that solves the issue as well...
