### ISSUE TITLE
[BUG] - Listbox: Hover not working

### ISSUE THREAD

**Issue by AstralBaby** [nextui-org/nextui#2368]
### NextUI Version

react 2.2.9

### Describe the bug

Listbox background is not changing when hovering over it.

### Steps to Reproduce the Bug or Issue

1. Follow installation instructions
2. Copy any listbox snippet from the official page

### Expected behavior

Is expected to show a background default 100 when the ListboxItem is hovered, instead it doesn't detect the data- attribute.
(Im using the recommended TW version)

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by Simon-He95** [comment]
I think you should provide the mini-reproduced demo

**Comment by I-am-abdulazeez** [comment]
Hi guys, any solution to this?

**Comment by wingkwong** [comment]
It looks fine on my side. or anyone can share a reproducible environment for demonstration? 

![image](https://github.com/user-attachments/assets/988c699c-201b-441c-afd9-1a24b86b025b)

**Comment by I-am-abdulazeez** [comment]
This works tho

<LinkboxItem 
     classNames={{
     base: `p-3 gap-8 items-center mb-4 ${isActive ? 'bg-brand_color_02 text-white' : ''}`,
     title: `text-[14px]`,
    }}
    className={clsx(
    `data-[hover=true]:bg-brand_color_02 data-[hover=true]:text-white data-[selectable=true]:focus:bg-brand_color_02 data- 
    [selectable=true]:focus:text-white ${isActive ? 'text-white font-semibold' : 'text-cool_text font-regular'} text-[14px] data- 
    [hover=true]:ease-in-out duration-300`
    )}
 />

**Comment by wingkwong** [comment]
@I-am-abdulazeez Can you share the code that reproduce the issue?

**Comment by wingkwong** [comment]
Closing - Not able to reproduce + inactivity.
