### ISSUE TITLE
Autocomplete, tabIndex is not passed on input

### ISSUE THREAD

**Issue by Fjohn666** [nextui-org/nextui#2372]
### NextUI Version

lastest

### Describe the bug

Hello everyone !
I love using this lib, thank you for the work !
I 'm facing an (probable) issue on autocomplete : 
The tabIndex props seems to not be passed on the input item : 

```
<Autocomplete
      size="sm"
      {...value}
     ... other props
      inputProps={{
        classNames: {
          inputWrapper: "border ....",
          innerWrapper: "justify-b....",
          input: "text-neutra...."
        },

        tabindex: tabIndex.  <---- here the tabIndex, tryed with tabIndex, and passing number or string
      }}
      listboxProps={{
          ....
      }}
      >
      {(item) => <AutocompleteItem aria-label='brand auto-complete item' key={item.id}>{item.name}</AutocompleteItem>}

        </Autocomplete>
```

I tried to pass the tabIndex props to autocomplete node but not working too.

The tabIndex props is not passed when i inspect the DOM. but this attribute work on Select and Inputs ... 
Am I doing something wrong ? or bug ?

Thanks in advance for your help

### Steps to Reproduce the Bug or Issue

create an autocomplete and pass tabIndex to inputProps

### Expected behavior

expected to see tabIndex in input node

### Operating System Version

macOS

### Browser

Chrome

**Comment by kuri-sun** [comment]
@Fjohn666 Thanks for reporting the issue! Yes, I also could create the same bug with your clear instructions! I'll take a look at this issue 👍
