### ISSUE TITLE
[Feature Request] Drawer Component

### ISSUE THREAD

**Issue by oversio** [nextui-org/nextui#2376]
### Is your feature request related to a problem? Please describe.

No, is just that would be great to have a Drawer component available on this awasome library ❤️

### Describe the solution you'd like

Just a Drawer component similar to this one ([https://mui.com/material-ui/react-drawer/](https://mui.com/material-ui/react-drawer/)) but with all your magic 🥰

### Describe alternatives you've considered

I'm trying to do it by my own 😔 due I don't wanna use another UI library

### Screenshots or Videos

![React_Drawer_component\\\_-\\\_Material UI](https://uploads.linear.app/4fe36c58-98e5-4a20-8a41-a3ce80ac4de8/0755a575-e93e-4048-827f-a50c093b1698/0e04518e-8a60-47ee-9ae4-a8e3d10c61bd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRmZTM2YzU4LTk4ZTUtNGEyMC04YTQxLWEzY2U4MGFjNGRlOC8wNzU1YTU3NS1lOTNlLTQwNDgtODI3Zi1hNTBjMDkzYjE2OTgvMGUwNDUxOGUtOGE2MC00N2VlLTlhZTQtYThlM2QxMGM2MWJkIiwiaWF0IjoxNzA4MzAzODgxLCJleHAiOjMzMjc4ODYzODgxfQ.C1SOsCbcYSbHcR6uu-lpR80OKmQKIauUEVASSxgjZ8w "=1497x")

**Comment by mauriciabad** [comment]
If this component is added, it would be very useful to also be dissmisable by dragging it out.

For mobile users this is more usable than having to click the small close button or drayed out area.

And also the option to add a handle to visually indicate it can be dragged.

**Comment by zhengjitf** [comment]
I need Drawer, too. Any plans or updates for it?
