### ISSUE TITLE
[BUG] - Tooltip is missing styles when installed individually

### ISSUE THREAD

**Issue by elanclarkson** [nextui-org/nextui#2378]
### NextUI Version

2.2.9

### Describe the bug

The Tooltip classes are not included in the Tailwind compilation when installed individually, despite the tailwind content config containing the `./node_modules/@nextui-org/theme/dist/components/tooltip.js` path.

This is because tooltip.js is missing from `@nextui-org/theme`.

### Steps to Reproduce the Bug or Issue

Install Tooltip component per the individual installation instructions and update the Tailwind content config to include a path to the missing `./node_modules/@nextui-org/theme/dist/components/tooltip.js` file.

### Expected behavior

I am expecting the classes used on the Tooltip to be included in the final Tailwind compilation. E.g. `px-2.5` doesn't do anything and the arrow doesn't work.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by nico-limo** [comment]
Having same issue. Any solution here?

**Comment by ProphetKhalul** [comment]
Same issue

**Comment by AndreyMarchuk** [comment]
bump, same issue

**Comment by wingkwong** [comment]
please provide a stackblitz example for demostration. I don't quite understand what the issue is here. There is no tooltip in theme because tooltip uses the popover theme.

**Comment by elanclarkson** [comment]
@wingkwong Ah that was indeed the issue. Once I included popover in my tailwind config the tooltip was styled correctly.

It might be worthwhile just pointing this out in the docs so it doesn't catch people out if they are trying to use tooltips without popovers (which I imagine a lot of people would be).

**Comment by wingkwong** [comment]
I second that. Lemme supplement in tooltip doc.
