### ISSUE TITLE
[BUG] - AutoComplete component sets the input value to the label 

### ISSUE THREAD

**Issue by ybwai** [nextui-org/nextui#2396]
### NextUI Version

2.2.9

### Describe the bug

-Next14
- App Router
- Client Form component using a server action for submit
- FormData on the server action comes with the label not the value of an AutoComplete component. I can also see in the browser that when I select an item the input in the html gets given the label as value

### Steps to Reproduce the Bug or Issue

1. Create a Client form and add to a page:

```
"use client";

export function Form() {
  return (
    <form action={create}>
      <Autocomplete name="voice" label="Select a voice">
        {[
          { value: "a", label: "Label A },
          { value: "b", label: "Label B" },
        ].map((voice) => (
          <AutocompleteItem key={voice.value} value={voice.value}>
            {voice.label}
          </AutocompleteItem>
        ))}
      </Autocomplete>
      <Submit />
    </form>
  );
}
```

2. in Chrome select an option and then inspect the element you will see the input has Label A or Label B as value

### Expected behavior

The value should be A or B (the value given to the Item component)

### Screenshots or Videos

<img width="832" alt="Screenshot 2024-02-21 at 23 40 08" src="https://github.com/nextui-org/nextui/assets/159251479/17104407-560e-4a0c-9a0e-899d9a07b954">
<img width="831" alt="Screenshot 2024-02-21 at 23 40 38" src="https://github.com/nextui-org/nextui/assets/159251479/baf81c82-e3fc-4af3-9708-327d2205b7e7">

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
@ybwai I believe this is the expected behaviour. The value you captured is the value of the input, i.e. the input value you see in UI. If you want to capture the form value (e.g. `a` or `b`), then you may need to use [controlled](https://nextui.org/docs/components/autocomplete#controlled) one.

**Comment by GVALFER** [comment]
I have the same issue... this is anoying. the value returned is the label instead the value of the input

**Comment by wingkwong** [comment]
@GVALFER we'll revisit this issue. Let's track in the issue you created.

**Comment by pablojsx** [comment]
same

**Comment by LeonardBoedi** [comment]
Yea this is kinda weird. I was expecting it to be like a Select component but with autocomplete/filtering, where the value set in the value attribute of the Select component is the one that gets returned and not the label that you see in the UI

**Comment by TomasMaksy** [comment]
Awful shit. I want to display one thing (e.g. name) but send an id, how common is that issue? Yeah I can control it, but I want to use it in a SSR component
