### ISSUE TITLE
[BUG] - Input with type file not working on first attempt

### ISSUE THREAD

**Issue by ybwai** [nextui-org/nextui#2397]
### NextUI Version

~~2.2.9~~ 2.4.1

### Describe the bug

Adding an Input component with type file requires you to select the file twice before it sets it as value.

### Steps to Reproduce the Bug or Issue

1. Latest NextJS with App Router (fresh install)
2. Add a <Input type="file" name="file" /> to any page
3. Select a file, you will see the value does not update and it sill says No file chosen
4. Select a file again, now it updates and sets the file

### Expected behavior

Should set the file on first attempt

### Screenshots or Videos

![Screen Recording 2024-02-21 at 23 46 27](https://github.com/nextui-org/nextui/assets/159251479/85fec569-4a3b-486f-ab84-e75412c17b48)

### Operating System Version

MacOS

### Browser

Chrome

**Comment by ubr0n** [comment]
Any update on this bug?

**Comment by andyryan33** [comment]
Same exact bug for me. Works fine if I just use a plain `<input>` but does not work using the Input component.

**Comment by m-naeem66622** [comment]
Already same issue opened here #2311

**Comment by mstfblci** [comment]
I'm having the same problem too

**Comment by NAMANIND** [comment]
hey did anyone find the solution?

**Comment by Matiasdevv** [comment]
i just handle it like this and it worked:

`	const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		e.preventDefault();
		handleFiles(e.target.files?.[0]); //other func that recieves(file:any)
	};`

**Comment by deKadir** [comment]
same here

**Comment by Default-01** [comment]
How about fixing this issue asap?

**Comment by wingkwong** [comment]
@Default-01 The PR is being reviewed. The fix will be available in the next bug release. Please be patient.
