### ISSUE TITLE
[BUG] - Next UI Routing

### ISSUE THREAD

**Issue by mhmdjaw** [nextui-org/nextui#2404]
### NextUI Version

2.2.9

### Describe the bug

I'm not sure how things behave in other client side routers, but when I'm using React Router and I navigate to the same page I'm currently on with a NextUI Link, it adds it to the stack instead of replacing it. So If I'm on page `/home`, and I click on NextUI Link that links to `/home`, it just pushes to history instead of replacing. If I do it for example 4 times, I need to hit back button 4 times to return to the previous page I was on before `/home`. I added a stackblitz example that reproduces the bug.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-gq4vfv?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Go to Login Page
2. Go to Home Page
3. Click Home Link 4 times
4. Click back button (use browser back button in the example)

### Expected behavior

Navigate back to Login page immediately after hitting back button. Instead I need to hit back 4 times.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
You can define `navigate` in `NextUIProvider`. ref: https://nextui.org/docs/guide/routing.

**Comment by mhmdjaw** [comment]
> You can define `navigate` in `NextUIProvider`. ref: https://nextui.org/docs/guide/routing.

That's what I did if you check the example. This is not a problem of NextUI not using react router for navigation. This is a bug that adds the same page to history when navigating with NextUI links (which under the hood are using react router for navigation) instead of replacing them.

**Comment by wingkwong** [comment]
I think that is the expected behaviour. By default you are using `push`, whenever you click the link, it pushes to the history stack. If you want it to be replaced, you need to define in `navigate`. Here's the example.

```ts
function NextUIRouter() {
  const navigate = useNavigate();
  return (
    <NextUIProvider navigate={(path: string) => navigate(path, { replace: true })}>
      <Outlet />
    </NextUIProvider>
  );
}
```

**Comment by mhmdjaw** [comment]
The problem is that this expected behavior is not the one expected in react router, which is why I marked the issue as a bug. In react router if you click a link (using the react router Link) that links to the same page you're currently on, it doesn't add it to the stack since that would be pointless and a normal user might get confused if they hit the back button and nothing happens.

Try it in my example and switch one of the NextUI Links with a react routet Link. You will notice that react router doesn't push the same route to the stack. Instead it replaces it (or maybe ignores the click I'm not too sure).

Based on that I believe NextUI should imitate this behavior to avoid inconsistencies between it and react router in the same codebase.

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3240
