### ISSUE TITLE
[BUG] - RTL Support for Modals

### ISSUE THREAD

**Issue by tareq96** [nextui-org/nextui#2414]
### NextUI Version

2.2.9

### Describe the bug

The Modal title overlaps with the close icon when using RTL

![image](https://github.com/nextui-org/nextui/assets/19652643/87b09e89-b778-4cee-a08a-7e0dec35ad33)

I believe it should look like this:
![image](https://github.com/nextui-org/nextui/assets/19652643/195e9daf-ab67-4c44-8e59-0a2525a38adb)

### Steps to Reproduce the Bug or Issue

Use RTL layout, put the direction: rtl for the HTML or the body tag. Then Open any modal

### Expected behavior

![image](https://github.com/nextui-org/nextui/assets/19652643/41200d5c-1966-4fe1-80ff-a1463fc6e450)

### Operating System Version

macOS

### Browser

Chrome

**Comment by kuri-sun** [comment]
Hi @tareq96! Could you provide me with the code and also its CSS, please? Thank you!

**Comment by tareq96** [comment]
Hi @kuri-sun 

`import { useEffect, useState } from 'react'
import { Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, Button, useDisclosure, Input } from "@nextui-org/react";
import { GoPlus } from "react-icons/go";
import toast from 'react-hot-toast';
import { ResponseModel } from '../../services/apiModels';
import { api } from '../../services/apis';
import { useForm } from 'react-hook-form';
import { EyeSlashFilledIcon } from '../../icons/EyeSlashFilledIcon';
import { EyeFilledIcon } from '../../icons/EyeFilledIcon';

interface Props {
    getAdminUsers: () => void;
}

const AddUserModal = ({ getAdminUsers }: Props) => {
    const { isOpen, onOpen, onOpenChange } = useDisclosure();
    const [isVisible, setIsVisible] = useState(false);
    const { register, handleSubmit, reset, formState: { errors } } = useForm();
    const [isLoading, setIsLoading] = useState(false);

    const handleCreateUser = async (userParams: any) => {
        const postData = {
            username: userParams.username,
            email: userParams.email,
            password: userParams.password,
        };

        setIsLoading(true);

        const response = await api.createAdminUser(postData) as ResponseModel;

        if (response?.status === 'success') {
            onOpenChange();
            getAdminUsers();
            response?.message && toast.success(response?.message);
        } else {
            toast.error(response?.error?.message)
        }

        setIsLoading(false);
    }

    const toggleVisibility = () => setIsVisible(!isVisible);

    useEffect(() => {
        if (!isOpen) {
            reset();
        }
    }, [isOpen]);

    return (
        <>
            <Button
                onPress={onOpen}
                color='primary'
                endContent={<GoPlus size={20} />}
                size="sm"
                className='w-3/6 xs:w-auto'
            >
                Add User
            </Button>
            <Modal isOpen={isOpen} onOpenChange={onOpenChange}>
                <ModalContent>
                    {(onClose) => (
                        <form className="" onSubmit={handleSubmit(handleCreateUser)}>
                            <ModalHeader>Add New User</ModalHeader>
                            <ModalBody>
                                <div>
                                    <Input
                                        type="username"
                                        label="Username"
                                        labelPlacement="outside"
                                        className='mb-0'
                                        isInvalid={!!errors.username}
                                        errorMessage={errors.username?.message as string}
                                        {...register('username', {
                                            required: 'This field is required'
                                        })}
                                    />
                                </div>

                                <div>
                                    <Input
                                        type="email"
                                        label="Email"
                                        labelPlacement="outside"
                                        className='mb-0'
                                        isInvalid={!!errors.email}
                                        errorMessage={errors.email?.message as string}
                                        {...register('email', {
                                            required: 'This field is required',
                                            pattern: {
                                                value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                                                message: "Invalid email address"
                                            }
                                        })}
                                    />
                                </div>

                                <div>
                                    <Input
                                        type={isVisible ? "text" : "password"}
                                        label="Password"
                                        labelPlacement='outside'
                                        className='mb-0'
                                        isInvalid={!!errors.password}
                                        errorMessage={errors.password?.message as string}
                                        {
                                        ...register('password', {
                                            required: 'This field is required',
                                            minLength: {
                                                value: 8,
                                                message: 'Length must be 8 or more'
                                            }
                                        })
                                        }
                                        endContent={
                                            <button className="focus:outline-none" type="button" onClick={toggleVisibility}>
                                                {isVisible ? (
                                                    <EyeSlashFilledIcon className="text-2xl text-primary pointer-events-none" />
                                                ) : (
                                                    <EyeFilledIcon className="text-2xl text-primary pointer-events-none" />
                                                )}
                                            </button>
                                        }
                                    />
                                </div>
                            </ModalBody>
                            <ModalFooter>
                                <Button variant="light" color='danger' onPress={onClose}>
                                    Close
                                </Button>
                                <Button type='submit' color="primary" isLoading={isLoading}>
                                    Add User
                                </Button>
                            </ModalFooter>
                        </form>
                    )}
                </ModalContent>
            </Modal>
        </>
    )
}

export default AddUserModal`

**Comment by tareq96** [comment]
Hi guys

I saw this PR is merged https://github.com/nextui-org/nextui/issues/2292#event-11937362174 but when I tried to do npm i after that, it didn't include the fix.
What should I do to get that?

Thanks,
Best Regards
________________________________

**Comment by kuri-sun** [comment]
Hi @tareq96, I took a look at it, however, I could not reproduce the same bug as yours. For me, it looks like this.

<img width="509" alt="Screenshot 2024-03-03 at 6 49 30 AM" src="https://github.com/nextui-org/nextui/assets/62743644/acb57efa-44b0-47f9-ab08-fdd0b8049790">

I think there is custom CSS on top of it, I believe since your button color is RED although the passing type is `primary`. So, could you take a look at the code and if there are any other CSS or not, please? Thank you 😊

**Comment by tareq96** [comment]
Hi @kuri-sun 

I'm able to reproduce it in the doc. site: https://nextui.org/docs/components/modal
Just change the direction of the HTML tag to "rtl" and you can re-create it for any modal.

![image](https://github.com/nextui-org/nextui/assets/19652643/22485453-d970-4b87-ac7e-c2ed1a304ba5)
![image](https://github.com/nextui-org/nextui/assets/19652643/9bb87d61-99c7-4512-b810-8b736139764e)

**Comment by mrbadri** [comment]
Hi @jrgarciadev , 
I resolved this issue
