### ISSUE TITLE
[BUG] - Big button does not trigger a click event（When the button is large and very edge click）

### ISSUE THREAD

**Issue by ekkotest** [nextui-org/nextui#2418]
### NextUI Version

2.0.10

### Describe the bug

Big button does not trigger a click event（When the button is large very edge click）

### Steps to Reproduce the Bug or Issue

 The button does trigger a click event（When the button Animation trigger）

### Expected behavior

 The button does trigger a click event（When the button Animation trigger）

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Please provide a video or an example to demonstrate
