### ISSUE TITLE
[BUG] - Select component won't open listbox if list is empty

### ISSUE THREAD

**Issue by MaaitaMohammad** [nextui-org/nextui#2422]
## Description
The select components uses the listBox components inside it, and the listBox component has `hideEmptyContent` attribute which controls if the listBox should be shown if the content is empty, I've tried to pass `false` to the listboxProps attribute of the select component but still clicking on the select component will do nothing.

After going through the select component source code I found [this line](https://github.com/nextui-org/nextui/blob/0cc8c79c53ae416586117540e05801631080e52e/packages/hooks/use-aria-multiselect/src/use-multiselect-state.ts#L79) which controls the clicking behavior and it looks like it forcefully won't open the listBox if the list is empty.

## Expected
Being able to control the clicking behavior of the select component when the list is empty.

## Suggested
Adding an extra attribute to the select component that gets passed to the useMultiSelect hook to control the clicking behavior.

**Comment by alphaxek** [comment]
you want to open an empty Listbox in Select?

**Comment by ethylon** [comment]
In term of UX, it is much better to have an empty dropdown that says "No result" instead of having nothing popup at all. It would also be useful to trigger asynchronous data loading when the user first opens the dropdown instead of loading all the data from the start.
