### ISSUE TITLE
[BUG] - Slider Value causes React hydration error

### ISSUE THREAD

**Issue by pkail** [nextui-org/nextui#2423]
### NextUI Version

2.2.9

### Describe the bug

Using Nextjs 14.1.0 I get a hydration error:
Error: Text content does not match server-rendered HTML.

Warning: Text content did not match. Server: "0–72" Client: "0 – 72"

Default Value is set to [0,72].

Error disappears when I add 
formatOptions={{style: "currency", currency: "USD"}}

Error does *not* disappear with
 hideValue={true}

### Steps to Reproduce the Bug or Issue

Set a range for the Slider component.  Use Nextjs

### Expected behavior

No hydration error.

### Operating System Version

Linux

### Browser

Firefox

**Comment by kuri-sun** [comment]
Hi @pkail! Thank you for the report! I was trying to create this bug locally as per your instructions, however, I could not reproduce it.
Do you have the example code to reproduce this error by any chance? Thanks! ☺️

**Comment by pkail** [comment]
Thanks for your interest.  However, I am going to close this issue.  It turned out that the bug disappeared when I upgraded to the latest version of FireFox (and it never showed up in Thorium).  I suspect, therefore, that it was a rendering issue caused by a bug in that older version (101, I believe).
