### ISSUE TITLE
[BUG] - `enterKeyHint` does not get passed through `input` element when using `Input` component

### ISSUE THREAD

**Issue by markwilson** [nextui-org/nextui#2432]
### NextUI Version

2.2.9

### Describe the bug

[`enterKeyHint`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/enterKeyHint) doesn't get passed through to the `input` HTML element which means the keyboard (tested only on iOS) doesn't show the correct button (e.g. `enterKeyHint="search"` should show a blue "Search" button in iOS, but instead shows the default grey "return" button).

### Steps to Reproduce the Bug or Issue

1. Create an `<Input />` with `enterKeyHint` prop set to one of the available values (e.g. "search", "go", etc.)
2. Render the component and check the attributes on the `input` HTML element

### Expected behavior

As I user, I expected to see the `enterKeyHint` attribute to be set on an `input` element created via an `Input` component with `enterKeyHint` prop set.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Thanks for reporting. I'm able to reproduce. Will take a look.
