### ISSUE TITLE
[BUG] - Checkbox-group

### ISSUE THREAD

**Issue by Mo-21** [nextui-org/nextui#2433]
### NextUI Version

2.0.10

### Describe the bug

The checkbox group lacks on mobile

https://github.com/nextui-org/nextui/assets/106859926/c239bcaa-ec9d-4e3e-8438-aa1d797c3729

### Steps to Reproduce the Bug or Issue

1. Go to checkbox group page on mobile
2. Toggle the horizontal group 

### Expected behavior

I didn't expect it to lag

### Operating System Version

Android

### Browser

Edge

**Comment by kuri-sun** [comment]
Hi @Mo-21, Thank you for reporting the issue! However, I could not reproduce the bug successfully. Here is the video of me trying to reproduce this bug. 

https://github.com/nextui-org/nextui/assets/62743644/0817f259-1142-46f2-a146-2ae971468ea9

Could you specify a little bit more detailed information about this such as width and height for this and the exact reproducing steps?
Thank you so much ☺️

**Comment by Mo-21** [comment]
Hi Kuri,

I tried reproducing the problem with the devtools in browser but it didn't work too. However, my screen size is 412 X 869. My edge version (on android): 122.0.2365.56
