### ISSUE TITLE
"Styled" function doesn't works with Text component

### ISSUE THREAD

**Issue by dartilesm** [nextui-org/nextui#244]
## Description
Styles is not apply to Text component when using "styled" function, however it's works with css prop.
![image](https://user-images.githubusercontent.com/21966352/152705548-14af0abc-1e67-4a7e-a1a3-1bcca20511d6.png)

## Example
Let you an [example](https://codesandbox.io/s/dazzling-williamson-uc7mg?file=/src/App.js)
I did something wrong? 🥲

**Comment by jrgarciadev** [comment]
Hi @dartilesm, thanks for reporting, I'll fix it and include it in beta 4 👍🏻

**Comment by jrgarciadev** [comment]
Hey @dartilesm I've tried to solve this but unfortunately, the `css` prop has priority over the `styled` function is the way Stitches works so like we use the `css` prop internally for these props `color` `fontSize` and `textTransform` they are not overridable, a workaround is to use the `StyledText` included in NextUI as I did here -> https://codesandbox.io/s/pedantic-ardinghelli-uru6h

Hope it helps you 🙌🏻
