### ISSUE TITLE
[BUG] - onPress Button doesn't have PressEvent type

### ISSUE THREAD

**Issue by LangRizkie** [nextui-org/nextui#2440]
### NextUI Version

2.2.9

### Describe the bug

The docs say that we need to use `onPress` instead `onClick`. I'm trying to return whole Event but returning `Parameter 'e' implicitly has an 'any' type.`. Because PressEvent does not defined.

### Steps to Reproduce the Bug or Issue

1. Create Button component
2. add onPress attribute with parameter

### Expected behavior

returning `PressEvent` types

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by wingkwong** [comment]
I'm able to get PressEvent. Mind to share a Stackblitz link for reproducing the issue?

<img width="1322" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/3f477ea4-a0ca-4f8f-8592-705ee6bf0ca2">

**Comment by LangRizkie** [comment]
> I'm able to get PressEvent. Mind to share a Stackblitz link for reproducing the issue?
> 
> <img alt="image" width="1322" src="https://private-user-images.githubusercontent.com/35857179/310007798-3f477ea4-a0ca-4f8f-8592-705ee6bf0ca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDU2OTQsIm5iZiI6MTcwOTY0NTM5NCwicGF0aCI6Ii8zNTg1NzE3OS8zMTAwMDc3OTgtM2Y0NzdlYTQtYTBjYS00ZjhmLTg1OTItNzA1ZWU2YmYwY2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEzMjk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjOGFjOWYzZThmZTE2OTIwYmRlYTAzYjRiYmIxYmZlNjU2NjZlOGNkY2QxZjU2N2I5NWEwY2EzNDkzM2E3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N-Nzf8M4wcPGU6wnKyQa2bXvz_HfWZ-D5JlAm0AEIpI">

Yup, we can get the log, but we can't importing the types

**Comment by wingkwong** [comment]
@LangRizkie You may try the following

```ts
import {PressEvent} from "@react-types/shared";

const handlePress = (e: PressEvent) => {
  console.log(e)
};
```

```ts
<Button {...args} onPress={(e) => handlePress(e)}>
...
</Button>
```

**Comment by LangRizkie** [comment]
> ```ts
> import {PressEvent} from "@react-types/shared";
> ```

So, its not the part of nextui or react itself? I should install another lib for it, thank you!

**Comment by wingkwong** [comment]
I believe so. I don't see it's exported from nextui.

**Comment by awhitford** [comment]
Note that it only needs to be a `devDependency`, like here:
https://github.com/nextui-org/nextui/blob/e67b3af223607c6e8ef2dedb1348b3424e3b75d3/package.json#L70

I must admit that I am a little confused as to why this is here:
https://github.com/nextui-org/nextui/blob/e67b3af223607c6e8ef2dedb1348b3424e3b75d3/packages/hooks/use-aria-press/src/events.ts#L5

**Comment by mattiasw** [comment]
If you prefer not to install an extra package just for this, the following seems to work:
```
type PressEvent = Parameters<NonNullable<React.ComponentProps<typeof Button>['onPress']>>[0];
```

**Comment by anuraaga** [comment]
I ran into this as well and unfortunately, possibly due to a newer version of some package the suggestion to use `@react-types/shared` does not provide a compatible type.

```
  Types of parameters 'e' and 'e' are incompatible.
    Type 'PressEvent' is missing the following properties from type 'PressEvent': x, yts(2322)
```

I went with the approach of introspecting `Parameters` above but perhaps it would be easier to use the component if it reexported the compatible `PressEvent`.
