### ISSUE TITLE
[BUG] - Bug when using Korean language in modal form 

### ISSUE THREAD

**Issue by jscode28** [nextui-org/nextui#2445]
### NextUI Version

2.0.10

### Describe the bug

When filling out a form in a modal, if you enter Korean in the input and then tap, the last letter will be entered in the next input.

### Steps to Reproduce the Bug or Issue

1. Modal Open
2. Modal Form Component
3. Input in Korean Language write
4. tab button
5. next input in before last letter <- bug

### Expected behavior

<img width="428" alt="image" src="https://github.com/nextui-org/nextui/assets/110439044/36ffff85-f198-4810-ad7d-f9427c27bf97">

### Operating System Version

macOs

### Browser

Chrome

**Comment by wingkwong** [comment]
here's some preliminary findings:
- able to reproduce in chrome, but not safari and firefox
- happens in modal form - normal inputs work fine
- happens in korean language (i use 2-set korean to reproduce)
- focus would go to checkbox
