### ISSUE TITLE
[BUG] - Input label slot has a color bug

### ISSUE THREAD

**Issue by thought7878** [nextui-org/nextui#2459]
### NextUI Version

2.2.9

### Describe the bug

 Input label slot has a color bug

### Your Example Website or App

https://codesandbox.io/p/devbox/crimson-wood-zrgpsk?file=%2FApp.jsx%3A13%2C31

### Steps to Reproduce the Bug or Issue

add custom color for label slot 
<img width="1440" alt="Screen Shot 2024-03-06 at 15 53 07" src="https://github.com/nextui-org/nextui/assets/5996844/5705e384-d37c-4ef7-aded-3b756d1bd6e3">

### Expected behavior

Input label slot can display correctly with custom color

### Screenshots or Videos

<img width="1440" alt="Screen Shot 2024-03-06 at 15 53 07" src="https://github.com/nextui-org/nextui/assets/5996844/ab877af0-4360-44e9-8a7f-39812d3c8d20">

### Operating System Version

macOS

### Browser

Chrome

**Comment by ryo-manba** [comment]
Hi @thought7878 ,
This issue arises due to higher specificity in the default styles. 
As a temporary workaround you can override this using the [Important modifier](https://tailwindcss.com/docs/configuration#important-modifier) in TailwindCSS.

```tsx
classNames={{
   label: "!text-blue-500",
}}
```
