### ISSUE TITLE
className not being passed to <Text> component

### ISSUE THREAD

**Issue by bruxo00** [nextui-org/nextui#246]
**Steps to reproduce**
Try to pass a className to a <Text> component like: `<Text h1 className='test-class'>Loading...</Text>`.

**Expected behaviour**
`test-class` should be present on the element and it is not.

**Environment / Context**
- Desktop
- Windows 10 64 Bits
- Opera 83.0.4254.27

**Additional info**
**@nextui-org/react:** 1.0.2-beta.3
**react:** 17.0.2

**Comment by jrgarciadev** [comment]
Hey @bruxo00 this issue was fixed and is pending to be released https://github.com/nextui-org/nextui/issues/199
