### ISSUE TITLE
[BUG] - Autocomplete Console error when typing

### ISSUE THREAD

**Issue by Develekko** [nextui-org/nextui#2460]
### NextUI Version

2.2.10

### Describe the bug

Whenever I type into the Autocomplete component, an error occurs:
stopPropagation is now the default behavior for events in React Spectrum. You can use continuePropagation() to revert this behavior.
![nextui](https://github.com/nextui-org/nextui/assets/52341115/17759d0a-9787-427b-8f64-f9e434956984)

### Your Example Website or App

https://nextui.org/docs/components/autocomplete#usage

### Steps to Reproduce the Bug or Issue

just open https://nextui.org/docs/components/autocomplete#usage
check console while typing into any Autocomplete Input

### Expected behavior

no error while typing 

### Screenshots or Videos

![nextui](https://github.com/nextui-org/nextui/assets/52341115/3c474d9d-9df0-47a6-b0cf-34140fb9fb24)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
Thanks for reporting. I'll take a look.

**Comment by wingkwong** [comment]
may be resolved by https://github.com/nextui-org/nextui/pull/2100

**Comment by OsirisFrik** [comment]
Next version: 14.1.0
NextUI version: 2.2.9
Browser: Microsoft Edge Version 122.0.2365.92 (Official build) (64-bit)

same issue
