### ISSUE TITLE
[Feature Request] Autcomplete and lists should show the scrollbar in the content list

### ISSUE THREAD

**Issue by victormanuelrequena** [nextui-org/nextui#2478]
### Is your feature request related to a problem? Please describe.

UX Problem, without the scrollbar is hard for the user look the info

### Describe the solution you'd like

As a user i expected can look all the info and use an scrollbar

### Describe alternatives you've considered

A prop for show or not the scrollbar

### Screenshots or Videos

<img width="503" alt="image" src="https://github.com/nextui-org/nextui/assets/83138160/82a0d7ec-8853-4dd0-bc1e-558a69f7a420">

**Comment by jrgarciadev** [comment]
@victormanuelrequena this is possible by passing `hideScrollBar={false}` to the `scrollShadowProps` property.

```tsx
<Autocomplete
      label="Favorite Animal"
      placeholder="Search an animal"
      defaultSelectedKey="cat"
      defaultItems={animals}
      className="max-w-xs"
      scrollShadowProps={{
        hideScrollBar: false
      }}
    >
      {(item) => <AutocompleteItem key={item.value}>{item.label}</AutocompleteItem>}
    </Autocomplete>
  );
  ```

**Comment by victormanuelrequena** [comment]
Thank you!
