### ISSUE TITLE
[Feature Request] Support for turbo pack

### ISSUE THREAD

**Issue by rharkor** [nextui-org/nextui#2479]
### Is your feature request related to a problem? Please describe.

When you want to use turbopack you always get the error "Error: createContext only works in Client Components."

### Describe the solution you'd like

Find a solution to use turbopack

### Describe alternatives you've considered

Not using it

**Comment by cmedina-dev** [comment]
Hi @rharkor, can you elaborate on the issue a bit more? I've been using Turbopack just fine in multiple projects without error (Next 14.1.0). Can you post what version of Next.js / Turbopack you're using?

![image](https://github.com/nextui-org/nextui/assets/117231596/69dae699-2bc7-4901-a1fa-bea894958540)

These projects utilize server actions as well, so something reproducible would help a lot.

**Comment by rharkor** [comment]
Finally I found how to reproduce,
@cmedina-dev 
The problem occurs when you use `@nextui-org/react` instead of individual packages like `@nextui-org/button`.

How to reproduce:
1. Get the boilerplate: `npx create-next-app -e https://github.com/nextui-org/next-app-template`
2. Add --turbo to the dev script in `package.json`.
So it looks like this `"dev": "next dev --turbo",`
*Please not that at this point if you run the dev script everything work*
3. Install `@nextui-org/react`
4. Replace any import of the main page with the global library
Example:
`import { Link } from "@nextui-org/link";`
to
`import { Link } from "@nextui-org/react";`

**Comment by cmedina-dev** [comment]
Ah, this isn't an issue with Turbopack. NextUI does use client-side hooks (createContext) and by default Next.js pages are server components which will cause this error. You need to add `'use client'` at the top of your page.tsx (or wherever client-side hooks are used) for pages to render properly.

There are other workarounds such as creating an import to allow the rest of `page.tsx` to remain a server component, see: https://stackoverflow.com/a/76181667

**Comment by cmedina-dev** [comment]
The maintainers could mark the specific components that utilize the client-side hooks with `'use client'` but I'm not sure if there's reasoning for leaving them as server components so I think they'd better be able to answer.

**Comment by connorblack** [comment]
I'm also experiencing some turbo-related issues, specifically with compilation of the tailwind plugin:

```
./src/styles/globals.css:850:30
Parsing css source code failed
  848 |   --background: ({ opacityVariable, opacityValue }) => {
  849 |           if (!isNaN(+opacityValue)) {
> 850 |             return `hsl(var(${nextuiColorVariable}) / ${opacityValue})`;
      |                              ^
  851 |           }
  852 |           if (opacityVariable) {
  853 |             return `hsl(var(${nextuiColorVariable}) / var(${nextuiOpacityVariable}, var(${opacityVariable})))`;

Unexpected token Delim('$') at [project]/src/styles/globals.css:849:29
```

- "tailwindcss": "^3.4.3"
- "next": "14.3.0-canary.28"
- "@nextui-org/react": "^2.3.6" 

It works with the default/babel `next dev` command.

**Comment by Elmosh** [comment]
> I'm also experiencing some turbo-related issues, specifically with compilation of the tailwind plugin:
> 
> ```
> ./src/styles/globals.css:850:30
> Parsing css source code failed
>   848 |   --background: ({ opacityVariable, opacityValue }) => {
>   849 |           if (!isNaN(+opacityValue)) {
> > 850 |             return `hsl(var(${nextuiColorVariable}) / ${opacityValue})`;
>       |                              ^
>   851 |           }
>   852 |           if (opacityVariable) {
>   853 |             return `hsl(var(${nextuiColorVariable}) / var(${nextuiOpacityVariable}, var(${opacityVariable})))`;
> 
> Unexpected token Delim('$') at [project]/src/styles/globals.css:849:29
> ```
> 
> * "tailwindcss": "^3.4.3"
> * "next": "14.3.0-canary.28"
> * "@nextui-org/react": "^2.3.6"
> 
> It works with the default/babel `next dev` command.


i'm facing the same exact error with turbo, everything works with next@14.1.4, any newer versions causes this error.

**Comment by Forsect** [comment]
Next 14.2.3 - issue still here, as others said.

**Comment by Elmosh** [comment]
It turned out this issue wasn't cased by nextui but by a custom tailwind plugin:
```js
function addVariablesForColors({ addBase, theme }) {
  let allColors = flattenColorPalette(theme("colors"));
  let newVars = Object.fromEntries(
    Object.entries(allColors).map(([key, val]) => [`--${key}`, val]),
  );

  addBase({
    ":root": newVars,
  });
}
```

Once removed then all worked out fine with turbo & latest Next & nextui

**Comment by gcb** [comment]
> NextUI does use client-side hooks (createContext) and by default Next.js pages are server components which will cause this error. 

This should be up and front on the main site, for the benefit of anyone starting a new project on nextjs 14+
