### ISSUE TITLE
[BUG] - Lack of RTL Support in breadcrumbs

### ISSUE THREAD

**Issue by mrbadri** [nextui-org/nextui#2486]
### NextUI Version

2.0.10

### Describe the bug

The repository does not work correctly when the direction is set to RTL (Right-to-Left). Elements are not displayed as expected, leading to usability issues.

### Steps to Reproduce the Bug or Issue

Go to [this page](https://storybook.nextui.org/?path=/story/components-breadcrumbs--default&globals=locale:ar-AE)
Change the document direction to RTL (locale: Arabic).
Observe the issues mentioned above.

---
### breadcrumbs in LTR direction:
![image](https://github.com/nextui-org/nextui/assets/85818966/69a0686d-14bc-4eb7-9e39-1f1be2133ee7)

### breadcrumbs in RTL direction:
![image](https://github.com/nextui-org/nextui/assets/85818966/0181e4ce-9f63-492c-a556-64b00183fc73)
### breadcrumbs in RTL direction must be: 
![image](https://github.com/nextui-org/nextui/assets/85818966/c68282ba-68f4-42db-b8d3-424806701cdf)

### [view this page](http://localhost:6006/?path=/story/components-breadcrumbs--default&globals=locale:ar-AE)

---

### Expected behavior

I expected the UI to properly support RTL direction, with elements aligning and displaying correctly from right to left.

### Operating System Version

All

### Browser

Chrome

**Comment by tareq96** [comment]
@mrbadri any update on this? when it's expected to go live?

**Comment by ShrinidhiUpadhyaya** [comment]
Hi @wingkwong, can i look into this? Also a question, how to change the direction for components in the storybook?
