### ISSUE TITLE
[BUG] - No Difference Between `Bordered` & `Ghost` Variant Button

### ISSUE THREAD

**Issue by alphaxek** [nextui-org/nextui#2490]
### NextUI Version

2.2.10

### Describe the bug

Is there a difference between `ghost` & `bordered` variant button which I am missing, if there is none I can remove it.

Code:
https://github.com/nextui-org/nextui/blob/2894aecca1a2ef0dfb3066b9b8df24ce48c99dae/packages/core/theme/src/components/button.ts#L46

https://github.com/nextui-org/nextui/blob/2894aecca1a2ef0dfb3066b9b8df24ce48c99dae/packages/core/theme/src/components/button.ts#L51

**No difference, looks same as per code as well.**
![image](https://github.com/nextui-org/nextui/assets/116849110/dc1f5628-5a79-4ce8-b61a-5efd0d1ecccf)

Visuals (Dark Mode & Light Mode):
![dark](https://github.com/nextui-org/nextui/assets/116849110/d9b18307-9fea-49fc-a3a6-11cffd6b9511)

![border](https://github.com/nextui-org/nextui/assets/116849110/0c000084-47d0-4f3f-aafa-203737b62546)

### Steps to Reproduce the Bug or Issue

Please refer below:

https://nextui-storybook-v2-g8xni4v4p-nextui-org.vercel.app/?path=/story/components-button--default&args=variant:bordered

https://nextui-storybook-v2-g8xni4v4p-nextui-org.vercel.app/?path=/story/components-button--default&args=variant:ghost

### Expected behavior

No duplicate button variants (if there are any).

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
Hover the button to see the difference.

**Comment by alphaxek** [comment]
@wingkwong got it, thanks for clarifying
