### ISSUE TITLE
[Feature Request] Link with URL object

### ISSUE THREAD

**Issue by meness** [nextui-org/nextui#2492]
### Is your feature request related to a problem? Please describe.

`<Link/>` doesn't support URL object as described [here](https://nextjs.org/docs/app/api-reference/components/link#with-url-object). Right now, `href` supports `string` only.

### Describe the solution you'd like

I want to pass a URL object as shown below: `<Link href={{pathname: 'lorem', query:{slug:'ipsum'}}}/>`

### Describe alternatives you've considered

A simple working solution is to pass a string with all required data as shown below: `<Link href="/lorem/ipsum"/>`

**Comment by m-naeem66622** [comment]
@meness Had you tried one of the following:
1. `as` prop for [Polymorphic Content](https://nextui.org/docs/components/link#polymorphic-component) and then pass it URL Object has href prop
2. Or customizing the [Routing](https://nextui.org/docs/components/link#routing) using guide of NextUI

**Comment by meness** [comment]
@m-naeem66622 NextUI Link component supports `string` only

**LinkButtonProps**

```ts
export interface LinkButtonProps<T extends ElementType = 'button'> extends AriaButtonElementTypeProps<T> {
  /** A URL to link to if elementType="a". */
  href?: string,
}
  ```
  

  **Usage**

  ```ts
<Button
  as={Link}
  href={`${ipsum/${ipsum.id}`}>
    lorem
</Button>
```
