### ISSUE TITLE
[BUG] - Striped table display issue with multiple computed values

### ISSUE THREAD

**Issue by bwrightgene** [nextui-org/nextui#2506]
### NextUI Version

2.2.8

### Describe the bug

When utilizing a striped table (isStriped) with multiple computed values, the table renders the contents of the cell beneath the stripe for the table.

Example Code:
```js
<TableCell>
  {/* broken */}
  {firstName} {lastName}

  {/* working */}
  {firstName + ' ' + lastName}
</TableCell>
```

### Steps to Reproduce the Bug or Issue

1. Create table
2. Set isStriped prop
3. Within a cell, add two separate computed values
4. Ensure you have at least two rows with this configuration
5. Observe striped rows displaying incorrectly

### Expected behavior

All rows will render it's contents above the background striping

### Screenshots or Videos

Current:
![image](https://github.com/nextui-org/nextui/assets/97042269/f02b7244-4c9f-4021-a65b-19c0153098c2)
![image](https://github.com/nextui-org/nextui/assets/97042269/088f78bc-104f-4bbf-a425-d22700df8716)

Expected:
![image](https://github.com/nextui-org/nextui/assets/97042269/a0f1e05c-dc1d-47cf-a486-9b86a8078433)

### Operating System Version

Ubuntu 23.04

### Browser

Chrome

**Comment by alphaxek** [comment]
Hi @bwrightgene, I will raise PR with fix, thanks!
