### ISSUE TITLE
[BUG] - The autocomplete component does not work within the modal component.

### ISSUE THREAD

**Issue by laborasyon** [nextui-org/nextui#2510]
### NextUI Version

2.2.10

### Describe the bug

I wanted to use the autocomplete component in the modal. I cannot turn off the dropdown unless I select a value from the list.

### Steps to Reproduce the Bug or Issue

1. Add modal component
2. Add autocomplete component inside modal component
3. Click on the autocomplete widget
4. Try turning it off without selecting a value

### Expected behavior

I need to turn off the autocomplete dropdown item without selecting a value.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
@laborasyon I've already made the fix [here](https://github.com/nextui-org/nextui/pull/2494). Please stay tuned for the next version.

**Comment by wingkwong** [comment]
Closing - will be available in the upcoming release [v2.3.10](https://github.com/nextui-org/nextui/milestone/20)
