### ISSUE TITLE
[BUG] - Ripple displays outside of the button 

### ISSUE THREAD

**Issue by notmedia** [nextui-org/nextui#2523]
### NextUI Version

2.2.10

### Describe the bug

This bug appears only locally in safari (macOS) and mobile(iOS) chrome/safari.
I reproduced in codesanbox but probably you should download and check it locally too. Because in sandbox I have normal behaviour.

### Your Example Website or App

https://codesandbox.io/p/devbox/flamboyant-http-qnhdcl

### Steps to Reproduce the Bug or Issue

_

### Expected behavior

_

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/12993018/47a813d0-a357-43e4-a0da-556e4b829a80

### Operating System Version

macOS

### Browser

Safari

**Comment by wingkwong** [comment]
I've tried your code locally in safari but didn't reproduce the issue.

**Comment by notmedia** [comment]
@wingkwong this is strange. Now I see this on codesandbox too

My Safari version is 17.3.1 (19617.2.4.11.12)

**Comment by jrgarciadev** [comment]
I couldn't replicate this:

https://github.com/nextui-org/nextui/assets/30373425/b4f5cb13-a2ee-41c0-8fa5-386c14e00000

**Comment by notmedia** [comment]
After updating on Safari 17.4.1 I can't reproduce it too. Let's close it for now.
