### ISSUE TITLE
[Feature Request] Better Documentation of AutoComplete with API data

### ISSUE THREAD

**Issue by ybwai** [nextui-org/nextui#2529]
### Is your feature request related to a problem? Please describe.

The documentation Dynamic Example does not actually show how to feed the auto complete data that is fetched async, nor how to display loading state. 

### Describe the solution you'd like

Documentation to have a clear example of how to do a fetch, present a loading state and then when ready display the fetched items for selection.

### Describe alternatives you've considered

None

**Comment by wingkwong** [comment]
@ybwai Does [[Asynchronous Loading](https://nextui.org/docs/components/autocomplete#asynchronous-loading) example](https://nextui.org/docs/components/autocomplete#asynchronous-loading) help?

**Comment by voicify-dan** [comment]
> @ybwai Does [Asynchronous Loading](https://nextui.org/docs/components/autocomplete#asynchronous-loading) example help?

Yes sorry had not seen it, only saw the dynamic section. Would be good for this example to also have an interactive demo.

**Comment by ybwai** [comment]
Also that example doesn't really show making different api requests depending on the input from the user, as the user types the list of items will fully change. Issue I am having is that I get a visible loading state and while the data set is empty and the fetch is loading I get console errors:

```
import.mjs:1290 Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at eval (import.mjs:1290:33)
    at Array.some (<anonymous>)
    at MutationObserver.eval (import.mjs:1290:15)
    ```
    
    but as soon as the data is loaded it appears correctly.
    
    would be awesome to have a good example of how you recommend using the AutoComplete to fetch data using the input from the user, show a loading state while data is fetched, then display the data. 
    
    Many thanks!

**Comment by voicify-dan** [comment]
Actually ignore me, think what i am after is the https://nextui.org/docs/components/autocomplete#asynchronous-filtering example
