### ISSUE TITLE
[BUG] - No dark mode on Input

### ISSUE THREAD

**Issue by TeoConan** [nextui-org/nextui#2530]
### NextUI Version

2.2.9

### Describe the bug

Hi everyone 👋  is there a way to have an automatic dark mode on Input component ? 
My Input is stuck on light mode, I read the NextUI documentation and I don't know how it's working on nextui.org

![image](https://github.com/nextui-org/nextui/assets/22664730/b225b39e-019c-4c8e-adaf-ef78ef63465c)

Maybe I missed something in my `tailwind.config` ?
```
const config: Config = {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    ...
    darkMode: 'media',
    plugins: [nextui(), require('@tailwindcss/typography')],
};
```

Here my code where I implement my input :
```
<Input
  type="text"
  label="Search"
/>
```

If anyone know what is happening...
Thank in advance :)

### Steps to Reproduce the Bug or Issue

1. Create an Input
2. Use dark mode via media queries

### Expected behavior

Dark mode applied on Input, like background and text
Same as nextui.org

### Operating System Version

macOS

### Browser

Chrome

**Comment by alphaxek** [comment]
Hi @TeoConan, can you share the code snippet how you are enabling the `dark mode`

**Comment by TeoConan** [comment]
Hi :)
Thanks you for your answer

I dont't really see what you mean about how I enable the dark mode, I just use Tailwind config file here :
``` javascript
const config: Config = {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    ...
    darkMode: 'media',
    plugins: [nextui(), require('@tailwindcss/typography')],
};
```

And I use dark classes in my pages like this :
``` tsx
<body className="dark:bg-black bg-white">
    <NextUIProvider>
        <ApplicationContextProvider>
            {children}
        </ApplicationContextProvider>
    </NextUIProvider>
</body>
```

I also upgrade my packages 2.2.10 and I didn't change anything...

**Comment by TeoConan** [comment]
After testing, using "class" property seems to solve a loooot of problems, I'm thinking to switch to class instead of media

``` js
    darkMode: 'class',
    plugins: [nextui(), require('@tailwindcss/typography')],
```

**Comment by alphaxek** [comment]
Hi @TeoConan,

try `<body className="dark bg-white">`.

You can follow below links to enable the dark mode, there are different ways to enable it.

https://nextui.org/docs/customization/dark-mode

**Comment by wingkwong** [comment]
@TeoConan If you use `darkMode: 'media'` , it will set the dark or light theme based on the browser's color scheme preference. Based on your reply, it seems you want to apply dark mode styles on an element regardless of the system settings. In this case, you should use `darkMode: 'class'` instead.

**Comment by TeoConan** [comment]
You're right, I changed it and now it's better 👍🏻
