### ISSUE TITLE
[Feature Request] Code Component is not responsive

### ISSUE THREAD

**Issue by Navin-Jethwani-76** [nextui-org/nextui#2535]
### Is your feature request related to a problem? Please describe.

The [Code](https://nextui.org/docs/components/code) component is always rendered in a single line which makes the width of the body increase when the text inside is of long length.

### Describe the solution you'd like

The height of the component should increase as needed and the code should be wrapped so that it looks good on mobile devices.

### Describe alternatives you've considered

I tried adding a `text-wrap` in the className but it didn't wrap. also tried adding a paragraph tag inside code and adding the class to it but that didn't work either.

### Screenshots or Videos

[SandBox](https://codesandbox.io/p/devbox/jolly-benji-mysfq6)

open the rendered web page in a new tab and set the width of the screen to 375px using dev-tools

**Comment by winchesHe** [comment]
You can try add className to  the code `overflow-hidden text-ellipsis w-full`，also Add Tooltip wrap the code get the full content

**Comment by winchesHe** [comment]
The Code component just provide inline display, if want to mutiple line text, should given a Ellipsis component

**Comment by Navin-Jethwani-76** [comment]
> The Code component just provide inline display, if want to mutiple line text, should given a Ellipsis component

I added the className as suggested but it just truncates the rest of the code. I have updated the [Sandbox](https://codesandbox.io/p/devbox/jolly-benji-mysfq6) as well. Can you check if it is what you suggested?

**Comment by winchesHe** [comment]
> > The Code component just provide inline display, if want to mutiple line text, should given a Ellipsis component
> 
> I added the className as suggested but it just truncates the rest of the code. I have updated the [Sandbox](https://codesandbox.io/p/devbox/jolly-benji-mysfq6) as well. Can you check if it is what you suggested?

yes, the performance is a way to fixed your problem, also you can use Tooltip component to show full-content

if you want to mutiple line display the text then  you sholud't use the Code component
