### ISSUE TITLE
[BUG] - Skeleton does not respect disableAnimation

### ISSUE THREAD

**Issue by WesleyKapow** [nextui-org/nextui#2537]
### NextUI Version

2.2.9

### Describe the bug

Passing `disableAnimation` to skeleton does nothing, the animation continues.

### Steps to Reproduce the Bug or Issue

1. Setup a skeleton so that it is animating.
2. Add `disableAnimation`.

### Expected behavior

Expect animation to not happen.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Thanks for reporting. I'm able to reproduce. I'll work on it.
