### ISSUE TITLE
Pagination on refresh loses styles

### ISSUE THREAD

**Issue by Siumauricio** [nextui-org/nextui#254]
**Describe the bug**
The pagination component  when refreshing the browser makes component  colors like  default browser ,and display warning in console 

**Steps to reproduce**
Easy just copy pagination and put wherever and refresh the page and u will see the component style loses colors and styles.

https://codesandbox.io/s/practical-dewdney-rrpkf?file=/pages/index.js

**Expected behaviour**
Not loses the styles when refreshing the browser

**Screenshots**
![image](https://user-images.githubusercontent.com/47042324/152940973-074f76ad-dfc6-49a2-8c0d-023ff793df47.png)
![image](https://user-images.githubusercontent.com/47042324/152941480-57ec8f5d-bbd5-450e-bd7b-dff122ea1b6f.png)

**Environment / Context**
- Desktop
- Windows
- Edge  version 98.0.1108.43

**Additional info**
I be tested in my machine and sandbox and just works after I click the button of page

**Comment by jrgarciadev** [comment]
Hey @Siumauricio I noticed you are using Next.js so in order to guarantee the same classNames both on the server and on the client you have to `flush` the NextUI styles on the `_document.jsx/tsx` as the documentation indicates -> https://nextui.org/docs/guide/nextui-plus-nextjs

i.e

```jsx
import Document, { Html, Head, Main, NextScript } from 'next/document';
import { CssBaseline } from '@nextui-org/react';

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return {
      ...initialProps,
      styles: <>{initialProps.styles}</>
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>{CssBaseline.flush()}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```

Here's your example fixed https://codesandbox.io/s/crazy-sea-1doyp?file=/pages/index.js


Hope it helps you 🙌🏻

**Comment by Siumauricio** [comment]
I tried and yeah seems to work, but for many reasons that I don't know, buttons inside a modal lose the styles, like the colors, etc.

Using this way makes the buttons inside a modal loses the styles

``` js     
 <Head>
       {CssBaseline.flush()}
</Head> 
```

But I found a way to solve it which is just using <Head /> like that

```js
<Head />
{CssBaseline.flush()}
```
