### ISSUE TITLE
[BUG] - Label Placement breaking Select UI error state

### ISSUE THREAD

**Issue by LangRizkie** [nextui-org/nextui#2543]
### NextUI Version

2.2.10

### Describe the bug

Misaligned label with input using Select Component with `labelPlacement` set to "Outside" and set `errorMessage` value

### Your Example Website or App

https://codesandbox.io/p/devbox/condescending-moon-fyy2ql

### Steps to Reproduce the Bug or Issue

1. Create Select Component
2. set `labelPlacement` to "outside"
3. set `errorMessage` value

### Expected behavior

aligned label with input

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by NickNaskida** [comment]
The same thing happens with the description on v `2.2.10`.

1. Create Select Component
2. set labelPlacement to "outside"
3. set placeholder to some value
4. set description to some value


![Screenshot 2024-04-08@2x](https://github.com/nextui-org/nextui/assets/82929931/3b32b5d9-48af-430b-80b2-b81cf5140552)
