### ISSUE TITLE
[BUG] - DropdownItem doens't recpect props form the `as` component.

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [nextui-org/nextui#2549]
### NextUI Version

2.2.10

### Describe the bug

When supplying `as` prop to `DropdownItem` , TS signals an error for the `as`'s component props. Example:
```
<DropdownItem as={Link} to="/about">About</DropdownItem>
```
Here signals an error fro the `to` prop doesn't exists.
However there is no error when I make:
```
<NavbarBrand as={Link} to="/about"><NavbarBrand>
```

I guess there is discrepancy how these components processes their props.

### Steps to Reproduce the Bug or Issue

Follow code above

### Expected behavior

TS shouldn't signal errors on `as`'s component props.

### Operating System Version

Linux

### Browser

Firefox

**Comment by winchesHe** [comment]
I think beacuse the `as` prop is default prop about nextui, you can see it in the type `HTMLNextUIProps`, But for this component, It did not implement the function of AS, just like the offcial website did not show the API
