### ISSUE TITLE
[BUG] - Some out-of-date mistakes in the official example of customise the INPUT

### ISSUE THREAD

**Issue by bennettsimon** [nextui-org/nextui#2550]
### NextUI Version

2.2.10

### Describe the bug

I found a wrong example in using pseudo class to change the style of input. In the [Custom Style](https://nextui.org/docs/components/input#custom-styles) section, the snippet of the code like this:
```
<Input
        label="Search"
        isClearable
        radius="lg"
        classNames={{
          // ...
          inputWrapper: [
            "shadow-xl",
            "bg-default-200/50",
            "dark:bg-default/60",
            "backdrop-blur-xl",
            "backdrop-saturate-200",
            "hover:bg-default-200/70",
            "dark:hover:bg-default/70",
            "group-data-[focused=true]:bg-default-200/50",
            "dark:group-data-[focused=true]:bg-default/60",
            "!cursor-text",
          ],
        }}
 />
```
However, in the latest version of nextUI using `hover:` to change the style doesn't work any more. This method maybe out-of-date.

The right way to change the behaviour of pseudo class is using code like `data-[hover=true]` which refs to [Data Attributes](https://nextui.org/docs/components/input#data-attributes).

Besides, I also confused about the distinction between the prefix `group-data-` and `data-` where I found that they actually behave the same.

The documents and examples need update.

### Your Example Website or App

https://codesandbox.io/api/v1/sandboxes/define

### Steps to Reproduce the Bug or Issue

1. Go to [Custom Style](https://nextui.org/docs/components/input#custom-styles) section
2. Open the example in [codesandbox](https://codesandbox.io/api/v1/sandboxes/define)
3. Change the `hover:`
4. You'll see nothing happen.

### Expected behavior

The documents and examples need update.

### Operating System Version

macOS

### Browser

Chrome

**Comment by sagarj0** [comment]
Yes, I also faced the same problem, 
and tried to apply same pseudo class  ( 'hover: cursor-pointer') to every slots of Input.
at the end it only worked for input tag.

But the problem with that is it doesn't show cursor for whole Input component, because input tag obviously doesn't have full size as Input component and which is completely normal.

so the soultion(in my opinion),  the 'hover:cursor-pointer' applied directly to Input component should work.


![sorce code](https://github.com/nextui-org/nextui/assets/89570837/50f455e0-9415-4611-bd43-028e66da9501)
![cursor](https://github.com/nextui-org/nextui/assets/89570837/244c46b1-786c-4856-af5b-960594a2b30b)
![pointer](https://github.com/nextui-org/nextui/assets/89570837/dbf43d6e-23bb-4f75-b547-eb42bdcf9f85)

**Comment by winchesHe** [comment]
> ### NextUI Version
> 2.2.10
> 
> ### Describe the bug
> I found a wrong example in using pseudo class to change the style of input. In the [Custom Style](https://nextui.org/docs/components/input#custom-styles) section, the snippet of the code like this:
> 
> ```
> <Input
>         label="Search"
>         isClearable
>         radius="lg"
>         classNames={{
>           // ...
>           inputWrapper: [
>             "shadow-xl",
>             "bg-default-200/50",
>             "dark:bg-default/60",
>             "backdrop-blur-xl",
>             "backdrop-saturate-200",
>             "hover:bg-default-200/70",
>             "dark:hover:bg-default/70",
>             "group-data-[focused=true]:bg-default-200/50",
>             "dark:group-data-[focused=true]:bg-default/60",
>             "!cursor-text",
>           ],
>         }}
>  />
> ```
> 
> However, in the latest version of nextUI using `hover:` to change the style doesn't work any more. This method maybe out-of-date.
> 
> The right way to change the behaviour of pseudo class is using code like `data-[hover=true]` which refs to [Data Attributes](https://nextui.org/docs/components/input#data-attributes).
> 
> Besides, I also confused about the distinction between the prefix `group-data-` and `data-` where I found that they actually behave the same.
> 
> The documents and examples need update.
> 
> ### Your Example Website or App
> https://codesandbox.io/api/v1/sandboxes/define
> 
> ### Steps to Reproduce the Bug or Issue
> 1. Go to [Custom Style](https://nextui.org/docs/components/input#custom-styles) section
> 2. Open the example in [codesandbox](https://codesandbox.io/api/v1/sandboxes/define)
> 3. Change the `hover:`
> 4. You'll see nothing happen.
> 
> ### Expected behavior
> The documents and examples need update.
> 
> ### Screenshots or Videos
> _No response_
> 
> ### Operating System Version
> macOS
> 
> ### Browser
> Chrome

@bennettsimon https://tailwindcss.com/docs/hover-focus-and-other-states# maybe this can show the difference between data and group data
