### ISSUE TITLE
[BUG] - AutoComplete error when items is an empty array

### ISSUE THREAD

**Issue by ybwai** [nextui-org/nextui#2554]
### NextUI Version

2.2.10

### Describe the bug

With an async filtering AutoComplete if the initial items array is an empty array [] or if the fetch returns an empty array [] we get a console error:

```
import.mjs:1290 Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at eval (import.mjs:1290:33)
    at Array.some (<anonymous>)
    at MutationObserver.eval (import.mjs:1290:15)
```

### Steps to Reproduce the Bug or Issue

In the example Async Filtering AutoComplete change the fetch so that if the search term is empty it returns [] and you will see the error, then see how if you type a term that returns empty you also get an error.

### Expected behavior

Instead of an error we should get a zero state or at least not an error

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
@ybwai I couldn't reproduce the issue. Can you provide the code you've changed?

**Comment by ybwai** [comment]
Sure, I've setup a new nextjs app here: https://github.com/ybwai/test/tree/main/nextjs-blog
If you launch and open on the browser and start typing you will see the errors on the console.
Hope that helps.
I am using react-query in this one, but same thing happens with asyncList

**Comment by wingkwong** [comment]
Okay. Now I can reproduce the issue. I think there is something wrong with `allowsCustomValue`. Without setting `allowsCustomValue`, it works fine.

**Comment by ybwai** [comment]
ah good spot, you are right. however I do need allowsCustomValue as I want to be able to paste a link directly or search for one via auto complete.

**Comment by wingkwong** [comment]
what about setting `allowsEmptyCollection` to `false`?

**Comment by ybwai** [comment]
> what about setting `allowsEmptyCollection` to `false`?

that gets rid of the error but the AutoComplete no behaves oddly, it doesn't open and show when items are retrieved, opens only on focus

**Comment by MinChanSike** [comment]
Same issue, I need to use `allowsCustomValue` to get AutoComplete items from user input.

**Comment by TheJazzDev** [comment]
Anyone found a work around for this issue yet? I need to use `allowCustomValue`.

**Comment by wingkwong** [comment]
@MinChanSike @TheJazzDev can you guys also share your code please? Somehow I couldn't reproduce the issue on storybook but the OP's repo. Still investigating - was doubting `buttonProps` from `useComboBox`.
