### ISSUE TITLE
[BUG] - Tabbing through form fields in Modal leads to data loss on reaching Close button

### ISSUE THREAD

**Issue by SergejSi** [nextui-org/nextui#2558]
### NextUI Version

2.2.10

### Describe the bug

When navigating through a form within a Modal using the Tab key, reaching the Close (X) button unexpectedly triggers a form reset or re-render, resulting in the loss of all entered data.

### Steps to Reproduce the Bug or Issue

1. Open the Modal containing a form with multiple input fields.
2. Enter data into each field sequentially.
3. Use the Tab key to navigate through the fields.
4. Continue tabbing until the Close (X) button is selected.
5. Observe that the form data is cleared or the modal is re-rendered, causing data loss.

Once the Close (X) button is reached by tabbing through the form, all data entered in the form is lost, suggesting a form reset or re-render occurs.

### Expected behavior

Tabbing through the form and reaching the Close (X) button should not alter the state of the form or clear any entered data.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/19937663/e448b88f-442f-47bf-b906-cb8b1dded719

### Operating System Version

macOs

### Browser

Chrome

**Comment by wingkwong** [comment]
@SergejSi I'm not able to reproduce the issue. Can you please share your code?

[eng-533.webm](https://github.com/nextui-org/nextui/assets/35857179/143c89d2-4c2f-4110-8e24-1de6af52e6a8)
