### ISSUE TITLE
Input background color not changeable with theming

### ISSUE THREAD

**Issue by hmbrg** [nextui-org/nextui#256]
**Describe the bug**
Right now, we can't use a custom color provided by a theme to change the background color of inputs. This is because the input code uses baked in values from the next-ui theme instead of relying on `$varname` to access user provided themeing tokens.

**Steps to reproduce**
1. Set custom primary color inside a custom theme: `primary: '$grass10',`
2. Background color of input doesn't change

**Expected behaviour**
The background color should change according to the provided theme token.

**Screenshots**
<img width="228" alt="Screenshot 2022-02-09 at 00 09 25" src="https://user-images.githubusercontent.com/7304269/153091034-754c71dc-2660-440c-b520-87e5695ca006.png">
As shown here, the background color is not able to change in the primary variant (also in the secondary variant).

**Environment / Context**
- all environments

**Additional info**
The following code from `packages/react/src/input/input.styles.ts` shows the underlying issue: 
```js
    primary: {
      $$inputColor: addColorAlpha(theme?.colors.primary.value, 0.2), // this prevents the use of stitches tokens
      $$inputPlaceholderColor: '$colors$primary',
      $$inputTextColor: '$colors$primary',
      $$inputLabelColor: '$$inputTextColor',
      $$inputHoverBorderColor: '$colors$primary',
      $$inputPlaceholderOpacity: 0.5
    },
```

**Comment by jrgarciadev** [comment]
Hey @hmbrg thank you for reporting this, we have fixed this here -> https://github.com/nextui-org/nextui/pull/236/files#diff-fb92e92269a2ac69303e310951f31abd85960aba5ccda2a3d31d53d0d1f1eea1

The release is pending

**Comment by jrgarciadev** [comment]
The new version was released, please try this in case it has not been resolved we reopen the issue, thank you very much! https://github.com/nextui-org/nextui/releases/tag/v1.0.2-beta.4
