### ISSUE TITLE
[Feature Request] Autocomplete should expose label slot

### ISSUE THREAD

**Issue by russx2** [nextui-org/nextui#2570]
### Is your feature request related to a problem? Please describe.

Form field components that support `label` and `labelPlacement` attributes (such as Input, Slider, Select, etc) expose a `label` slot to allow customisation of the label. The Autocomplete component does not support this slot meaning we are unable to customise the label styling. 

### Describe the solution you'd like

I'd expect the `label` slot to be exposed.

### Describe alternatives you've considered

I don't believe there's any other way of styling the label without some global-level CSS hacks.

**Comment by wingkwong** [comment]
Closing - since `label` belongs to `input`, you can actually customise the label by passing `inputProps`.

```tsx
inputProps={{
  classNames: {
    label: "foo bar baz",
  },
}}
```
