### ISSUE TITLE
[Feature Request] In table component custom checkbox component.

### ISSUE THREAD

**Issue by Rutvikraj-Paroscale** [nextui-org/nextui#2572]
### Is your feature request related to a problem? Please describe.

Current NextUI provides default checkbox component in its table component. In my project we use a custom checkbox component.

### Describe the solution you'd like

NextUI has a feature to use a custom checkbox component as a standalone component. Can it be used to integrate a custom checkbox component in table ?

### Describe alternatives you've considered

We are currently adding a new column to display our custom checkbox.

**Comment by KelvinDiasMoreira** [comment]
Yes, you can. Here is the example: https://nextui.org/docs/components/table#custom-cells.

`const renderCell = React.useCallback((user, columnKey) => { if(columnKey === "yourColunm") return ( <YourComponent/> ) }`

is that what you need ?

**Comment by Rutvikraj-Paroscale** [comment]
Hi Kelvin,

Thanks for the suggestion. That could work but then we might not be able to
use the in-built selection functionality? We might have to create a
selection functionality of our own. Please correct me if I'm wrong.

Thank you,
Rutvikrajsinh Champavat

**Comment by KelvinDiasMoreira** [comment]
Yes, I think that you will need create a custom functionality.

**Comment by Rutvikraj-Paroscale** [comment]
I wanted to use the in-built selection functionality but with a custom
checkbox component because creating our own selection functionality may not
be as performant as the in-built one.

Thank you,
Rutvikrajsinh Champavat
