### ISSUE TITLE
[BUG] - Some user links in support us section led to 404 pages.

### ISSUE THREAD

**Issue by smultar** [nextui-org/nextui#2575]
### NextUI Version

Website

### Describe the bug

Whenever you click on the links to some users presented on the **NextUI Website**, under the **Sponsor us** section. It will sometimes lead to a 404 page. Maybe some of the links have changed, since the site's creation.

![image](https://github.com/nextui-org/nextui/assets/6223536/efd91bc9-1f05-4bbf-a322-12b6ad0ec533)

### Your Example Website or App

https://nextui.org/

### Steps to Reproduce the Bug or Issue

* Visit **[NextUI](https://nextui.org/)** main page.

* Attempt to click on a user presented.

### Expected behavior

Clicking on a user should have taken us to a valid user page.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/6223536/0bf4ba42-fafb-43f4-b2d7-90e05d4a38f8

### Operating System Version

Window 11 - Pro

### Browser

Edge

**Comment by kuri-sun** [comment]
Thanks @smultar! I will take a look at this.
