### ISSUE TITLE
[BUG] - Motions on mobile screens

### ISSUE THREAD

**Issue by vitalijalbu** [nextui-org/nextui#2577]
### NextUI Version

Latest

### Describe the bug

Idk guys, but on mobile screens motions are very very low, meaning they are not as in desktop mode…
Need to improve them….
Take a look at the modal on mobile (i use safari on ios)
https://nextui.org/docs/components/modal

### Steps to Reproduce the Bug or Issue

https://nextui.org/docs/components/modal

### Expected behavior

Expected motions more “fluid”

### Operating System Version

Ios

### Browser

Safari

**Comment by abdelrahman-essawy** [comment]
I have the same problem
```json
    "@nextui-org/react": "^2.2.9",
    "@nextui-org/theme": "^2.1.17",
```
