### ISSUE TITLE
[BUG] - Next UI Input type="number" not displaying the browser default error message

### ISSUE THREAD

**Issue by ramanan1998** [nextui-org/nextui#2578]
### NextUI Version

2.2.10

### Describe the bug

Hey, This is my first time opening an issue on Github. I've been working on my personal project started a week ago and wanted to try Next UI as a component library with React hook form. So I created a form that includes two Input field with type="number", min=0, max=5.

```
<Input                                    // next ui Input component
    size="sm"
    type="number" 
    id="childCount"
    required
    variant="bordered" 
    placeholder="Maximum no. of children" 
    classNames={{
      inputWrapper: [ "data-[hover=true]:border-primary-blue", "group-data-[focus=true]:border-primary-blue" ]
    }}
    min={0}
    max={5}
    {...register("childCount", {
      validate: (value) => {
        if(value > 5){
          return "Maximum no.of children are limited to 5"
        }

        return true
      },
      valueAsNumber: true
    })} 
/>
```

```
<input                                       // native input element
    type="number" 
    id="infantCount"
    placeholder="Maximum no. of infants" 
    min={0}
    max={5}
    required
    className="border border-black h-10 w-full p-2"
    {...register("infantCount", {
      validate: (value) => {
        if(value > 5){
          return "Maximum no.of infants are limited to 5"
        }

        return true
      },
      valueAsNumber: true
    })} 
/>
```

If I try to submit the form with value of "10" or "1000" something like that, the next ui Input field doesn't show me any default browser tooltip warning "value must be less than or equal to 5". only the native input element shows me that warning.

### Steps to Reproduce the Bug or Issue

"

### Expected behavior

If the user enters a value 1000, both the input field (Next UI Input as well as native input element) supposed to show me a default tooltip "value must be less than or equal to 5".
but only the native input element throws me the warning.
The validate method in next UI Input component didn't work as well. I am stuck with here without able to submit my form.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/104082218/95ae9fa1-156b-4120-ad4f-4f85beaf16dd

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by wingkwong** [comment]
Please upgrade to the latest version. I remember it has been resolved in v2.3.x.

![image](https://github.com/nextui-org/nextui/assets/35857179/81201e0a-6c51-46c7-8a30-fa44f6a6724f)
