### ISSUE TITLE
[BUG] - Link element reloading page on Astro

### ISSUE THREAD

**Issue by irg1008** [nextui-org/nextui#2579]
### NextUI Version

2.2.10

### Describe the bug

When using Link component inside an astro island, the page is reloaded instead of doing SPA routing

### Steps to Reproduce the Bug or Issue

Import Link component or Button then use `as={Link}`
Click on Link
The page will reload

### Expected behavior

The page should not reload but instead navigate like SPA without refreshing the browser.
A normal a tag works as expected

### Operating System Version

Windows

### Browser

Chrome

**Comment by kovacsni76574** [comment]
This Bug still exists, right?
