### ISSUE TITLE
Modal blur backdrop not working in Firefox

### ISSUE THREAD

**Issue by bruxo00** [nextui-org/nextui#258]
**Steps to reproduce**
1. Open Firefox
2. Go to modaldocumentation
3. Open modal with blured background
4. [No blur](https://i.imgur.com/Rj6owek.png)

**Expected behaviour**
A modal with a blured background. Works fine in Opera at least.

**Screenshots**
[No blur](https://i.imgur.com/Rj6owek.png)

**Environment / Context**
- Desktop
- Windows 10 64 Bits
- Firefox 97.0 (64-bit)

**Additional info**
**@nextui-org/react:** 1.0.2-beta.3
**react:** 17.0.2

**Comment by jrgarciadev** [comment]
Hey @bruxo00 the `Modal` component `blur` is based on the `backdrop-filter` css property which unfortunately is not supported by Firefox until now 

Offical docs:
https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter#browser_compatibility
