### ISSUE TITLE
Next UI Autocomplete not re-rendering updated value options on defaultItems change

### ISSUE THREAD

**Issue by Aks6193** [nextui-org/nextui#2582]
### NextUI Version

2.2.10

### Describe the bug

The autocomplete component does not re-render the option value on change of the default values
`const autocomplete= useMemo(() => {
    if (data)
      return (
      <Autocomplete
          variant="bordered"
          defaultItems={data}
          className="max-w-full"
          onSelectionChange={onSelectionChange}
        >
          {(item) => (
            <AutocompleteItem key={item.id}>{item.name}</AutocompleteItem>
          )}
        </Autocomplete>
      );
  }, [data]);`

  
  data interface has the following keys `{
id: number,
name: string}`

The name attribute of the data changes after some user activity but the autocomplete does not update the text in the items, even though if you look at the developer tools the props show the latest value but the rendered items dont. 

### Steps to Reproduce the Bug or Issue

1. create a autocomplete with default items of type interface data {id: number, name: string}
2. update data after some user activity fro example each data item is listed in input boxes and onchange of the input box the name of the data item is updated. 
3. The autocomplete does not refelct these changed values, unless page is refreshed in some way but the props passed to autocomplete reflect the value

### Expected behavior

The autocomplete should reflect the change in text in the updated value

### Operating System Version

Windows

### Browser

Firefox

**Comment by wingkwong** [comment]
@Aks6193 `defaultItems` is uncontrolled. You may try to use `items`, which is controlled, instead.

**Comment by Aks6193** [comment]
> @Aks6193 `defaultItems` is uncontrolled. You may try to use `items`, which is controlled, instead.
