### ISSUE TITLE
[Feature Request] I don't want to see aria-lable warning

### ISSUE THREAD

**Issue by devmemory** [nextui-org/nextui#2586]
### Is your feature request related to a problem? Please describe.

Hello. I just started using Next ui in my company.

And it's pretty annoying to see the console, because of warning.
`console.js:43 An aria-label or aria-labelledby prop is required for accessibility.`

`console.js:43 If you do not provide a visible label, you must specify an aria-label or aria-labelledby attribute for accessibility`

I've checked if it's possible to turn on and off by searching in google. But I couldn't find it.

Since it's not basic warning from pure HTML, I want an option to make it silence.

Can you make a new feature to turn on and off this warning?

Or is there already an option to make it silence?

### Describe the solution you'd like

```
const blahConfig = {
   onwarn: (warning, handler) => {
                // so in this case "a11y-" might be replaced to "aria"
		if (warning.code.startsWith('a11y-')) {
			return;
		}
		handler(warning);
	},
}
```

This kind of option is provided in SvelteKit config option.

### Describe alternatives you've considered

Or something like
```
const option = {
   ariaWarning: false
}

<NextUIProvider className="nextui-provider" warningOption={option}>
    {...}
</NextUIProvider>
```

**Comment by abhinav700** [comment]
@wingkwong can you assign this issue to me

**Comment by ryo-manba** [comment]
As I mentioned in the PR, I’ll close this issue.
https://github.com/nextui-org/nextui/pull/3728#issuecomment-2337153798
