### ISSUE TITLE
[BUG] - Select controlled mode not support number key

### ISSUE THREAD

**Issue by Zeiion** [nextui-org/nextui#2587]
### NextUI Version

2.2.10

### Your Example Website or App

[https://stackblitz.com/\~/github.com/Zeiion/react-nextui](https://stackblitz.com/\~/github.com/Zeiion/react-nextui)

### Steps to Reproduce the Bug or Issue

1. npm install & npm run dev
2. the first select is not default selected

### Expected behavior

\`\` is expect to support React.Key (string | number), so the first select should be default selected and works well when selecting new items

### Screenshots or Videos

![CleanShot 2024-03-26 at 16 49 12](https://uploads.linear.app/4fe36c58-98e5-4a20-8a41-a3ce80ac4de8/08d534ec-6a41-4ef3-87a4-eecb4b833528/48b9a7a7-2dfb-436c-aefe-5c41575f0a8a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRmZTM2YzU4LTk4ZTUtNGEyMC04YTQxLWEzY2U4MGFjNGRlOC8wOGQ1MzRlYy02YTQxLTRlZjMtODdhNC1lZWNiNGI4MzM1MjgvNDhiOWE3YTctMmRmYi00MzZjLWFlZmUtNWM0MTU3NWYwYThhIiwiaWF0IjoxNzExNDQ5MjcyLCJleHAiOjMzMjgyMDA5MjcyfQ.MPtWiZ4fdsSsXnF1MIqZjDNvaNFFzp8y1CCaXH9cuNE)

### Operating System Version

macOS

### Browser

Chrome

### Describe the bug

the `selectedKeys` props for the \`\` is not working when keys are numeric
but when i parse them into strings, it works.

The problem seems to appear in `packages/hooks/use-aria-multiselect/src/use-multiselect-list-state.ts`

```typescript
const {
    collection,
    disabledKeys,
    selectionManager,
    selectionManager: {setSelectedKeys, selectedKeys, selectionMode},
  } = useListState(props);
```

when call `collection.getItem(1)`, it gets `undefined`

sb test to reproduce the bug can be add as

```typescript
const ControlledNumberTemplate = ({color, variant, ...args}: SelectProps<User>) => {
  const [value, setValue] = React.useState<Selection>(new Set([1]));

  const handleSelectionChange = (e: ChangeEvent<HTMLSelectElement>) => {
    setValue(new Set([Number(e.target.value)]));
  };

  return (
    <div className="flex flex-col w-full max-w-xs gap-2">
      <Select
        className="max-w-xs mt-8"
        color={color}
        items={usersData}
        label="Assigned to"
        selectedKeys={value}
        variant={variant}
        onChange={handleSelectionChange}
        {...args}
      >
        {(item) => (
          <SelectItem key={item.id} textValue={item.name}>
            <div className="flex items-center gap-2">
              <Avatar alt={item.name} className="flex-shrink-0" size="sm" src={item.avatar} />
              <div className="flex flex-col">
                <span className="text-small">{item.name}</span>
                <span className="text-tiny text-default-400">{item.email}</span>
              </div>
            </div>
          </SelectItem>
        )}
      </Select>
      <p className="text-default-500">Selected: {value}</p>
    </div>
  );
};
```

**Comment by wingkwong** [comment]
Thanks for reporting. I'm able to reproduce. Will make a PR soon.
