### ISSUE TITLE
[Feature Request] Improving installation instructions in the guide

### ISSUE THREAD

**Issue by Dilettante258** [nextui-org/nextui#2599]
### Is your feature request related to a problem? Please describe.

I believe the instructions in the guide for installing this UI library are not very detailed. I encountered a lot of issues while using a React application created with Vite. It took me a while to resolve them.

### Describe the solution you'd like

I encountered the following problems:

1. The description of [Setup pnpm (optional)](https://nextui.org/docs/guide/installation#setup-pnpm-optional-1) is not very clear. Initially, I overlooked it and spent a lot of time troubleshooting in other places. I suggest emphasizing the importance of this step for pnpm users earlier in the guide.
2. Regarding deployment on platforms like Vercel: After resolving the first issue, I noticed that when deploying my website on Vercel, the styles were still missing. Initially, I didn't understand why. Later, I realized that I also needed to set up `.npmrc` on Vercel.
3. Later, I added the `next-themes` package, but after installation, my styles disappeared again. When I checked the developer console, I found that the content of my CSS file went from over 7000 lines to 1300 lines! I'm not entirely sure why this happened, but after making some modifications to `tailwind.config.js`, it successfully reverted back to normal.

### Describe alternatives you've considered

This is my solution:

1. Skip the explanation.
2. Please refer to Vercel's official [instructions](https://vercel.com/guides/using-private-dependencies-with-vercel#other-package-registries) (other-package-registries)。
   I executed the following command on my computer:

```bash
PS C:\Users\admir> cd YOUR_LOCAL_REPOSITORIES_LOCATION
PS C:\.....> cmd //Switch from powershell to cmd
C:\.....> npx vercel env add NPM_RC production < C:\\Users\\USERNAME\\.npmrc
Vercel CLI 33.6.1
✅ Added Environment Variable NPM_RC to Project xxxxxxx [231ms]
```

1. I write the tailwind configuration file this way：

```js
import { nextui } from '@nextui-org/react';

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  darkMode: 'class',
  plugins: [nextui()],
};

export default config;
```

### Screenshots or Videos

![56966a4d4216329df6c24f4ff4b24851](https://uploads.linear.app/4fe36c58-98e5-4a20-8a41-a3ce80ac4de8/2ded68ff-7994-4f36-af57-cb7b9b8350dc/7901f1e9-8882-4c37-86b4-c319067d0eb8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRmZTM2YzU4LTk4ZTUtNGEyMC04YTQxLWEzY2U4MGFjNGRlOC8yZGVkNjhmZi03OTk0LTRmMzYtYWY1Ny1jYjdiOWI4MzUwZGMvNzkwMWYxZTktODg4Mi00YzM3LTg2YjQtYzMxOTA2N2QwZWI4IiwiaWF0IjoxNzE4Njg4NzQ0LCJleHAiOjMzMjg5MjQ4NzQ0fQ.kLuPyUHRolZN4DVPiw1QbgCMXoqTL9QSX4WCRh7Mc4A)

![544398878bc56913e8c6b42ec3513ee2](https://uploads.linear.app/4fe36c58-98e5-4a20-8a41-a3ce80ac4de8/b5e6d1a7-00eb-44c2-a861-c83dab073656/4e823890-6e8a-4386-82e9-90bfd059db97?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRmZTM2YzU4LTk4ZTUtNGEyMC04YTQxLWEzY2U4MGFjNGRlOC9iNWU2ZDFhNy0wMGViLTQ0YzItYTg2MS1jODNkYWIwNzM2NTYvNGU4MjM4OTAtNmU4YS00Mzg2LTgyZTktOTBiZmQwNTlkYjk3IiwiaWF0IjoxNzE4Njg4NzQ0LCJleHAiOjMzMjg5MjQ4NzQ0fQ.prpNl0npIEh8EHQajjBTjPw_Koe_j8VpRmEdakMmzQY)

![8efde71a2e05998466f45622225fc0b0](https://uploads.linear.app/4fe36c58-98e5-4a20-8a41-a3ce80ac4de8/a2093631-113d-45d2-a352-a27c6b4e9000/7987f733-a533-43aa-9d22-a4b99efa599a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRmZTM2YzU4LTk4ZTUtNGEyMC04YTQxLWEzY2U4MGFjNGRlOC9hMjA5MzYzMS0xMTNkLTQ1ZDItYTM1Mi1hMjdjNmI0ZTkwMDAvNzk4N2Y3MzMtYTUzMy00M2FhLTlkMjItYTRiOTllZmE1OTlhIiwiaWF0IjoxNzE4Njg4NzQ0LCJleHAiOjMzMjg5MjQ4NzQ0fQ.rgtflBfFRgkg_B9F7nEbONoHcXneodXuyB6_ZvQW0lo)

![fce40ac11050720a1b81dc7f23a00a13](https://uploads.linear.app/4fe36c58-98e5-4a20-8a41-a3ce80ac4de8/4ae5051e-9110-4a86-b7bb-eac729e690e5/30cd7cdc-f981-4086-9fe7-f6936439ad76?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRmZTM2YzU4LTk4ZTUtNGEyMC04YTQxLWEzY2U4MGFjNGRlOC80YWU1MDUxZS05MTEwLTRhODYtYjdiYi1lYWM3MjllNjkwZTUvMzBjZDdjZGMtZjk4MS00MDg2LTlmZTctZjY5MzY0MzlhZDc2IiwiaWF0IjoxNzE4Njg4NzQ0LCJleHAiOjMzMjg5MjQ4NzQ0fQ.JdrknPAJJ76CNbK9jjH2IMSD4-Rkyjw3lLVFqth2kRI)

bun create-next-app -e [https://github.com/nextui-org/next-app-template](https://github.com/nextui-org/next-app-template)

**Comment by Dilettante258** [comment]
The [use-dark-mode](https://github.com/donavon/use-dark-mode) has not been updated for four years, and it seems that it cannot be used on React 18. It is recommended to remove the [guidance](https://nextui.org/docs/customization/dark-mode#using-use-dark-mode-hook) for using it.

![image](https://github.com/nextui-org/nextui/assets/113875344/8d5ba912-8c84-42b1-a4bb-ad121ac8640a)
![image](https://github.com/nextui-org/nextui/assets/113875344/1ed324c6-204a-4bc2-9481-c59dfd5579fd)

**Comment by Mingyang-Li** [comment]
I'm also setting up a theme switcher using NextUI with vite. Like you said, `use-dark-mode` is not actively maintained, have you found a way to integrate dark-mode into your vite app?

PS: Agree with your comments about lack of details regarding pnpm - I've had issues installing NextUI using pnpm in my monorepo earlier, I resolved it by doing this:
```js
import { nextui } from '@nextui-org/react';

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    // 👇 making sure it's pointing to the ROOT node_modules 👇
    '../../node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  darkMode: 'class',
  plugins: [nextui()],
};

export default config;
```

My monorepo folder structure:
```
root
  /packages
    /frontend
      package.json
      tailwind.config.js
    /backend
    /core-db
    /core-cms
   etc etc
package.json
pnpm-lock.yaml
pnpm-workspace.yaml
tsconfig.json
turbo.json
```

**Comment by Dilettante258** [comment]
@Mingyang-Li 很抱歉。我前几天从邮件中看到了你的回复，当时我是准备过一会就回复的。但是后来忘了。我使用了 [next-themes](https://github.com/pacocoursey/next-themes) 来作为 [use-dark-mode](https://github.com/donavon/use-dark-mode) 的替代，他在react中也可以正常运作。

> I'm sorry. I saw your reply in the email a few days ago, and I was prepared to reply shortly. But later I forgot. I used "next-themes" As "use dark mode" Instead, it can also function normally in React.

**Comment by Mingyang-Li** [comment]
谢啦 @Dilettante258 - can confirm `next-themes` works fine in Vite app
