### ISSUE TITLE
[Feature Request] How to add the autocomplete="off" attribute to the Input component?

### ISSUE THREAD

**Issue by baijunjie** [nextui-org/nextui#2602]
### Is your feature request related to a problem? Please describe.

How to add the autocomplete="off" attribute to the Input component? However, I've noticed that the component seems to ignore the props.autocomplete attribute, which means all input fields get hijacked by 1Password, resulting in a very poor experience.
<img width="469" alt="image" src="https://github.com/nextui-org/nextui/assets/7956480/076f7e5f-1b85-43e8-8782-175ffb8f4879">

The solution provided by 1Password is to add the autocomplete="off" attribute to the Input. However, NEXTUI does not support this, and I'm wondering if there's any workaround. Thank you very much! 🙏🏻
https://1password.community/discussion/117501/as-a-web-developer-how-can-i-disable-1password-filling-for-a-specific-field

### Describe the solution you'd like

```jsx
<Input autocomplete="off" />
```
output
```html
<input type="text" autocomplete="off" />
```

### Describe alternatives you've considered

none

**Comment by wingkwong** [comment]
@baijunjie please try with a capital C

```
<Input autoComplete="off" />
```

<img width="760" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/35409741-96f7-45b5-bcb6-632a6f1a36ed">

**Comment by baijunjie** [comment]
> @baijunjie please try with a capital C
> 
> ```
> <Input autoComplete="off" />
> ```
> 
> <img alt="image" width="760" src="https://private-user-images.githubusercontent.com/35857179/319021859-35409741-96f7-45b5-bcb6-632a6f1a36ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTU1OTMsIm5iZiI6MTcxMjExNTI5MywicGF0aCI6Ii8zNTg1NzE3OS8zMTkwMjE4NTktMzU0MDk3NDEtOTZmNy00NWI1LWJjYjYtNjMyYTZmMWEzNmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAzMzQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MzBiOGU1YjhlMzU3ZTc1NGFiNGYzNjgyZDZkM2MwZWVkMDc1N2MwNTJmNDc2YmMwMGI2ZmM1NTliNmFiYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gazm6yXRXRsu4oZ6IF_79f7P1mMfvXObzDs-JQdRyoc">

You are right！Thanks
