### ISSUE TITLE
[BUG] - Modal search window

### ISSUE THREAD

**Issue by hoachnt** [nextui-org/nextui#2615]
### NextUI Version

2.2.10

### Describe the bug

The modal search window on the official website does not close.

### Steps to Reproduce the Bug or Issue

1. Go to the official website. 
2. Click to search button or press "ctrl + k". 
3. Close the modal.

### Expected behavior

Guys, just fix this so I can search for the components I need

### Screenshots or Videos

[Screencast from 2024-03-31 17-18-37.webm](https://github.com/nextui-org/nextui/assets/91771575/e6b52a78-902d-4ead-912e-24db10fede67)

### Operating System Version

- Fedora linux 39(workstation)

### Browser

Firefox

**Comment by wingkwong** [comment]
Thanks for reporting. will make a PR soon.
