### ISSUE TITLE
[BUG] - Modal

### ISSUE THREAD

**Issue by webkooid** [nextui-org/nextui#2617]
### NextUI Version

2.2.10

### Describe the bug

After open modal then close it, modal still exist, do not hidden, 
you can try

### Steps to Reproduce the Bug or Issue

click Open Modal
close it

still showing

### Expected behavior

after click close, should be hidden

just like NORMAL modal

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate as #2615
