### ISSUE TITLE
[BUG] - Popover Content still moving while wrapped with fixed parent

### ISSUE THREAD

**Issue by LangRizkie** [nextui-org/nextui#2623]
### NextUI Version

2.2.10

### Describe the bug

Wrapping Popover component with fixed class make the entire content not respecting the parent trigger

### Your Example Website or App

https://codesandbox.io/p/devbox/competent-shaw-g7nccq?file=%2FApp.jsx%3A11%2C28

### Steps to Reproduce the Bug or Issue

1. Import Popover component
2. Wrap Popover with fixed class

### Expected behavior

Popover Content still put along parent side

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by wingkwong** [comment]
No longer reproducible.

<img width="425" alt="image" src="https://github.com/user-attachments/assets/3f337f3c-a703-4e7d-a450-faec07022e8d">
