### ISSUE TITLE
[BUG] - React does not recognize the `isDisabled` prop on a DOM element.

### ISSUE THREAD

**Issue by mustafahalabi** [nextui-org/nextui#2626]
### NextUI Version

2.2.10

### Describe the bug

```
Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at button
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/popover/dist/chunk-2U2X4IMV.mjs:24:115)      
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/dropdown/dist/chunk-63RZRIL7.mjs:15:108)     
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/popover/dist/chunk-LOWKC34K.mjs:21:13)       
    at Dropdown (webpack-internal:///(ssr)/./node_modules/@nextui-org/dropdown/dist/chunk-XLXG7E33.mjs:17:13) 
```

### Steps to Reproduce the Bug or Issue

<Dropdown placement="bottom-end">
						<DropdownTrigger>
							<button className="mt-1 h-8 w-8 outline-none transition-transform">
								<User
									name=""
									avatarProps={{
										src: user?.image,
									}}
								/>
							</button>
						</DropdownTrigger>
						<DropdownMenu aria-label="Profile Actions" variant="flat">
							<DropdownItem key="profile" className="h-14 gap-2">
								<p className="font-semibold">Signed in as</p>
								<p className="font-semibold">{user?.email}</p>
							</DropdownItem>
							<DropdownItem key="settings" color="primary">
								My Profile
							</DropdownItem>
							<DropdownItem key="team_settings" color="primary">
								My Orders
							</DropdownItem>
							<DropdownItem key="logout" color="danger" onClick={logout}>
								Log Out
							</DropdownItem>
						</DropdownMenu>
					</Dropdown>

### Expected behavior

Not to throw the error.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/45153433/1057d25d-a571-4631-baea-273e141a3f10)

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
Handled in https://github.com/nextui-org/nextui/pull/2522. Please wait for the next release.

**Comment by ImSingee** [comment]
@wingkwong Thanks for fixing this! Is there any ETA for the release? This warning is really annoying.

**Comment by wingkwong** [comment]
> @wingkwong Thanks for fixing this! Is there any ETA for the release? This warning is really annoying.

@ImSingee I'll leave @jrgarciadev to answer this question.

**Comment by mustafahalabi** [comment]
@wingkwong @jrgarciadev any updates about the ETA for the release ?

**Comment by wingkwong** [comment]
@mustafahalabi target on [15 Apr](https://github.com/nextui-org/nextui/milestone/20)

**Comment by ducan-ne** [comment]
@mustafahalabi did you noticed this change in your side? it seem like I still getting this in v2.3.0, not sure about the others

**Comment by wingkwong** [comment]
@ducan-ne please DM me at [discord](https://discordapp.com/users/495466997304262658)

**Comment by ducan-ne** [comment]
@wingkwong can't send message to you directly, just sent a friend request
