### ISSUE TITLE
[BUG] - there is not way to change border bg custom Input

### ISSUE THREAD

**Issue by Andrestheran** [nextui-org/nextui#2635]
### NextUI Version

 2.1.17

### Describe the bug

there is not way to change the border color once you select the input it stays as gray doesnt matter the classnames props added

### Steps to Reproduce the Bug or Issue

trying to set custom styles

 classNames={{
          label: "text-black/50 dark:text-white/90",
          input: [
            "bg-transparent",
            "text-black/90 dark:text-white/90",
            "placeholder:text-default-700/50 dark:placeholder:text-white/60",
          ],
          innerWrapper: "bg-transparent",
          inputWrapper: [
            "shadow-xl",
            "bg-default-200/50",
            "dark:bg-default/60",
            "backdrop-blur-xl",
            "backdrop-saturate-200",
            "hover:bg-default-200/70",
            "dark:hover:bg-default/70",
            "group-data-[focused=true]:bg-default-200/50",
            "dark:group-data-[focused=true]:bg-default/60",
            "!cursor-text",
          ],
        }}

### Expected behavior

I would like to know the option to set that border color

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
@Andrestheran I don't see you've set the border in `inputWrapper`. Below is an example by adding `border-2 border-red-300` to `inputWrapper`.

<img width="308" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/2cf7a7df-44a2-4eb8-8f56-14783c53d3bb">

**Comment by Andrestheran** [comment]
@wingkwong I paste the example thta we could found on the documentation hover when you click on the field there is a focus gray color and there is not any way to put any other color 
<img width="375" alt="Screenshot 2024-04-02 at 10 11 42 PM" src="https://github.com/nextui-org/nextui/assets/77905995/206098bf-d56a-43bd-8b94-c0b8a15b391c">

**Comment by wingkwong** [comment]
@Andrestheran Can you share the code of your screenshot?

**Comment by Andrestheran** [comment]
sure, thank you so much for helping me out!

`<Input
                  id="firstName"
                  label="First Name"
                  value={form.values.firstName}
                  onChange={form.handleChange}
                  classNames={{
                    label: ["border-none", "bg-white"],
                    input: ["border-none", "bg-white"],
                    inputWrapper: ["border-none", "bg-white"],
                    innerWrapper: ["bordernone", "bg-white"],
                  }}
                  disabled={!isEditMode}
                />`

**Comment by Andrestheran** [comment]
I tried all the options and colors but trying and trying and always getting that gray shadow

**Comment by wingkwong** [comment]
@Andrestheran Try the following to see if this is what you want.

```
inputWrapper: ["border-none", "bg-white", "data-[hover=true]:bg-white", "group-data-[focus=true]:bg-white"],
```

<img width="334" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/f8d7c1cb-2fa2-461d-910c-de3b8f7d7f92">

**Comment by Andrestheran** [comment]
it works!!1 thk u so much!

**Comment by wingkwong** [comment]
@Andrestheran Thanks for the confirmation. I'm going to close this issue then.
