### ISSUE TITLE
[BUG] - SELECT_MULTIPLE_CLICKS_GIVES_ANUMATION_ERROR

### ISSUE THREAD

**Issue by makandriival** [nextui-org/nextui#2636]
### NextUI Version

2.2.10

### Describe the bug

Multipple clicks on the select gives this error:
`Unhandled Runtime Error
Error: Only two keyframes currently supported with spring and inertia animations. Trying to animate scale(0.8),scale(0.80774),scale(0.82541),scale(0.84721),scale(0.86972),scale(0.89102),scale(0.91018),`

### Steps to Reproduce the Bug or Issue

click fast mutiple time on select component

### Expected behavior

expected: it opens and closes
actual: it gives error

### Operating System Version

any

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate: #2519. Please try `framer-motion@11.0.22`
