### ISSUE TITLE
[Progress-indicator] Progress with Indicator

### ISSUE THREAD

**Issue by nico-limo** [nextui-org/nextui#2655]
### Is your feature request related to a problem? Please describe.

I would like have the number indicator from Progress, at top from where is the line limit

On this example I harcoded the values to show where I want the value. NuxtUi have the indicator

![image](https://github.com/nextui-org/nextui/assets/74354611/bd3c8275-8879-490b-a1db-c6bda0b06d2b)

Example code
```ts
    <Progress
        aria-label="Loading..."
        value={borrowLimitUsed}
        valueLabel={borrowLimitUsed.toFixed(2)}
        showValueLabel
        size="sm"
        classNames={{
          value: `absolute right-[720px] bottom-4`,
        }}
      />
```

### Describe the solution you'd like

Adding a div that have conditional to show it or not, with same width that the fulfilled linea 

### Describe alternatives you've considered

Not alternative found

### Screenshots or Videos

Expected Result will be something like this
![image](https://github.com/nextui-org/nextui/assets/74354611/02f38936-78eb-480f-b68e-8a739f7ec3dc)

**Comment by HydenLiu** [comment]
Maybe, You can use this
https://nextui.org/docs/components/slider#value-formatting
