### ISSUE TITLE
Collapse button server-client rendering mismatch

### ISSUE THREAD

**Issue by gillescoolen** [nextui-org/nextui#267]
**Describe the bug**
The chevron used in the collapse component causes a server-client rendering mismatch using NextJS.

**Steps to reproduce**
1. Clone [this example repository](https://github.com/gillescoolen/nextui-mismatch-example).
2. Run `npm ci`.
3. Run `npm run dev`.
4. Visit [your localhost](http://localhost:3000).

**Expected behaviour**
The example renders without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/31668393/153362459-e7be15a5-447f-46ad-b5ea-32eea0f240bc.png)

**Environment / Context**
- Desktop
- macOS Monterey 12.2
- Chrome Version 98.0.4758.80 (Official Build) (arm64)
- Macbook Pro 14 M1

**Additional info**
I've found [this](https://stackoverflow.com/questions/67176204/how-to-resolve-prop-id-did-not-match-server-react-tabs-30-client-react) stackoverflow post about mismatches, but this has not been discussed anywhere in the NextUI documentation. I expected the component to work without issues. Is importing the component dynamically as shown in the post the way to go?

**Comment by jrgarciadev** [comment]
hey @gillescoolen could you try this again? using the `v1.0.6-beta.5`

**Comment by prkirby** [comment]
I wanna say I'm getting this same issue for the Label component: 

```
Prop `id` did not match. Server: "react-aria-2" Client: "react-aria-4"
    at label
    at Styled.label
    at div
    at Styled.div
```

Should I open a new ticket @jrgarciadev

**Comment by luixo** [comment]
I'm getting this error with `1.0.0-beta.9`.
