### ISSUE TITLE
[BUG] - Autocomplete hideEmptyContent prop

### ISSUE THREAD

**Issue by brunogarcia** [nextui-org/nextui#2670]
### NextUI Version

2.2.10

### Describe the bug

If the property `hideEmptyContent` is applied on the `Autocomplete` component, the search option stop working.

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-s4ajow?file=app%2Fcomponents%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1.- On the example, search for a "Cat"
2.- Select the "Cat" option
3.- Clear the selection
4.- Try to search a "Dog" (it's not possible to search again)

### Expected behavior

As a user, I expect to be able to search different items on the `Autocomplete` component

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/366057/5bda30b2-c8b5-4d35-a9ce-d0c4854e4dba

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Closing - no longer reproducible on v2.4.2.
