### ISSUE TITLE
[Feature Request] Input OTP

### ISSUE THREAD

**Issue by SainDev** [nextui-org/nextui#2678]
### Is your feature request related to a problem? Please describe.

Input Otp is used to enter one-time passwords.

### Describe the solution you'd like

new component "Input OTP"

### Describe alternatives you've considered

https://ui.shadcn.com/docs/components/input-otp
https://primereact.org/inputotp/

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/1188424/9ba5c9bd-f7f5-499f-b93f-d633e632d82a)

**Comment by nguyenthengocit37** [comment]
+1

**Comment by ameybh** [comment]
Hi @wingkwong , I'd like to contribute this component.

**Comment by denis-gankin** [comment]
up

**Comment by macci001** [comment]
Seems like there isn't much update available for this. I need input-otp in my personal project, I have kinda base-work for this ready. May I take this up?
@wingkwong

**Comment by wingkwong** [comment]
@macci001 DM me at discord for discussion first.

**Comment by wingkwong** [comment]
reassign to @macci001.
