### ISSUE TITLE
[BUG] - With Sections You can use the AutocompleteSection component to group autocomplete items keyboard naviagation is not working

### ISSUE THREAD

**Issue by Malith-ra** [nextui-org/nextui#2680]
### NextUI Version

2.0

### Describe the bug

With Sections You can use the AutocompleteSection component to group autocomplete items keyboard naviagation is not working

### Steps to Reproduce the Bug or Issue

With Sections You can use the AutocompleteSection component to group autocomplete items keyboard naviagation is not working

### Expected behavior

With Sections You can use the AutocompleteSection component to group autocomplete items keyboard naviagation is not working

### Screenshots or Videos

With Sections You can use the AutocompleteSection component to group autocomplete items keyboard naviagation is not working

### Operating System Version

Windows

### Browser

Chrome

**Comment by HydenLiu** [comment]
Hello, Can you provide a minimal reproducible environment (e.g. Stackblitz) please?

**Comment by Malith-ra** [comment]
https://nextui.org/docs/components/autocomplete

![image](https://github.com/nextui-org/nextui/assets/53249044/ca670435-4929-4aa6-b39b-a09ea92dc66d)


in this autocompelete component not going up and down when clicking keyboard up and down keys

**Comment by wingkwong** [comment]
preliminary finding:

- onKeyDown not working once `Listbox` is wrapped by `ScrollShadow`
