### ISSUE TITLE
[BUG] - Modal - size="full" not working correctly with scrollBehavior="inside"

### ISSUE THREAD

**Issue by kodobrody** [nextui-org/nextui#2681]
### NextUI Version

2.2.10

### Describe the bug

Hey, I just discovered that I can't have fullscreen modal with scrollable body. If I try to eg.
```
<Modal
        isOpen={isOpen}
        onOpenChange={onOpenChange}
        scrollBehavior="inside"
        size="full"
      >
```
it results in modal stopping being full screen.

### Your Example Website or App

https://codesandbox.io/p/devbox/heuristic-jasper-4hd333?file=%2FApp.jsx%3A24%2C19

### Steps to Reproduce the Bug or Issue

When using modal add both props size="full" and scrollBehavior="inside"

### Expected behavior

Modal should stay fullscreen

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/117864696/4dbaf933-0752-459c-9f4a-a22bcaefc924)

### Operating System Version

Windows

### Browser

Chrome

**Comment by ShrinidhiUpadhyaya** [comment]
When `scrollBehavior="inside"` is set, 7.5rem is reduced from the total height

 ```
 inside: {
        base: "max-h-[calc(100%_-_7.5rem)]",
        body: "overflow-y-auto",
      },
```

Maybe there is some design decision taken for that calculation, but the below code can fix this bug
```
  inside: {
        base: "max-h-full",
        body: "overflow-y-auto",
      },
```

Note:- If needed i could generate a PR for this.
