### ISSUE TITLE
[BUG] - In Select Component need a   props "allowClear"  

### ISSUE THREAD

**Issue by Arjun059** [nextui-org/nextui#2687]
### NextUI Version

2.x.x

### Describe the bug

I don't want to user to clear selected item. need allowClear props.  ref https://ant.design/components/select

### Steps to Reproduce the Bug or Issue

I don't want to user to clear selected item.

### Expected behavior

I don't want to user to clear selected item. need allowClear props. ref https://ant.design/components/select 

### Screenshots or Videos

I don't want to user to clear selected item.  ref https://ant.design/components/select

### Operating System Version

Window

### Browser

Chrome

**Comment by wingkwong** [comment]
Closing - duplicate of #1579
