### ISSUE TITLE
[BUG] - Group button use case border or so

### ISSUE THREAD

**Issue by j-vitali** [nextui-org/nextui#2694]
### NextUI Version

latest

### Describe the bug

See before and after clicking it:
<img width="579" alt="Screenshot 2024-04-12 alle 12 36 59" src="https://github.com/nextui-org/nextui/assets/161858414/3e88171e-b4ab-4cea-9fc9-5fe23b1d55f9">

After
<img width="579" alt="Screenshot 2024-04-12 alle 12 36 54" src="https://github.com/nextui-org/nextui/assets/161858414/854e5beb-8b8d-46b7-b2fc-542c5bf93dc2">

### Steps to Reproduce the Bug or Issue

Click on the button icon

### Expected behavior

Mus have equal height (40px)

### Operating System Version

mac

### Browser

Chrome

**Comment by ryo-manba** [comment]
Hi @j-vitali, 
I don't think this is a bug. The scale is reduced to make it clear when the button is clicked. 
You can check this in the code here: 
https://github.com/nextui-org/nextui/blob/main/packages/core/theme/src/components/button.ts#L89
