### ISSUE TITLE
[BUG] - Select (Documentation Error)

### ISSUE THREAD

**Issue by tempestshad0w** [nextui-org/nextui#2696]
### NextUI Version

2.2.10

### Describe the bug

I saw some mistakes here. [Multiple With Chips](https://nextui.org/docs/components/select#multiple-with-chips)
In App.jsx, I got this code. {(user) => (
        <SelectItem key={user.id} textValue={user.name}>
          <div className="flex gap-2 items-center">
            <Avatar alt={user.name} className="flex-shrink-0" size="sm" src={user.avatar} />
            <div className="flex flex-col">
              <span className="text-small">{user.name}</span>
              <span className="text-tiny text-default-400">{user.email}</span>
            </div>
          </div>
        </SelectItem>
      )}
But I think, it could be more accurate by using {users.map((user) => (...))}
I want your review. Thank you.

### Steps to Reproduce the Bug or Issue

I think it's documentation error.

### Expected behavior

I think it's documentation error.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
if you are talking about the below code, then it's not a bug. That's a called [dynamic collection](https://react-spectrum.adobe.com/react-stately/collections.html#dynamic-collections).

```tsx
{(user) => (
  <SelectItem key={user.id} textValue={user.name}>
    <div className="flex gap-2 items-center">
      <Avatar alt={user.name} className="flex-shrink-0" size="sm" src={user.avatar} />
      <div className="flex flex-col">
        <span className="text-small">{user.name}</span>
        <span className="text-tiny text-default-400">{user.email}</span>
      </div>
    </div>
  </SelectItem>
)}
```

**Comment by tempestshad0w** [comment]
Thank you for your explanation regarding the code I mentioned in the
previous message. I appreciate your clarification on the dynamic collection
concept. Your input has been helpful in enhancing my understanding of this
aspect of coding. Thank you once again for taking the time to respond.
