### ISSUE TITLE
[BUG] - Table Column resize 

### ISSUE THREAD

**Issue by junaidnectarai** [nextui-org/nextui#2699]
### NextUI Version

2.2.10

### Describe the bug

We are PRO users of NextUI and are looking to incorporate table column resizing. However, we have noticed that the option for column resizing is not provided in the NextUI documentation. I attempted to utilize the logic outlined in https://tanstack.com/table/latest/docs/introduction, but unfortunately, it did not function with NextUI. Therefore, we would greatly appreciate any suggestions or guidance you can offer to help us implement table column resizing. Thank you very much in advance.

### Steps to Reproduce the Bug or Issue

Inside the TableHeader i cannot use any other component other than TableColumn

### Expected behavior

I should be able to use any custom element inside the TableHeader in order to achieve the other functionality

### Operating System Version

Windows 10 pro

### Browser

Chrome

**Comment by misbah-u** [comment]
+1 would appreciate help on this

**Comment by kuri-sun** [comment]
@junaidnectarai Thanks for sharing a great suggestion for the matter! we now released v2.3.0, and we will take a look into this one so that we can get you back to guys immediately!! Thank you 🚀

**Comment by farah-u** [comment]
@kuri-sun  thank you! please let us know asap when there's an update here. We're using NextUI's table here, and really don't want to migrate away because of this issue :( thanks so much for the amazing design components!

**Comment by awestm** [comment]
Thanks for the nice looking table! However, would be great to have this planned at some point. Column resizing is a fairly fundamental feature imo
