### ISSUE TITLE
[BUG] - Navbar

### ISSUE THREAD

**Issue by ngodacthien** [nextui-org/nextui#2723]
### NextUI Version

2.2.10

### Describe the bug

app-index.js:35 Warning: React does not recognize the `originalProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### Steps to Reproduce the Bug or Issue

See Error in console

### Expected behavior

i dont know

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Duplicate - #2593. The fix will be available in the next version (v2.3.0 - which we will release soon).
