### ISSUE TITLE
[BUG] - Navbar Sample code does not do animation

### ISSUE THREAD

**Issue by deepshaswat** [nextui-org/nextui#2728]
### NextUI Version

2.2.10

### Describe the bug

When all the sample code is added, the menu dropdown does not do animation. Its total blank

### Steps to Reproduce the Bug or Issue

Just copy the sample codes

### Expected behavior

It should work as the sample UI shown

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
@deepshaswat Which sample code you are referring to? Can you also provide a Stackblitz link for demo?

**Comment by deepshaswat** [comment]
@wingkwong https://stackblitzstartersvczyv6-z54r--3000--7dbe22a9.local-credentialless.webcontainer.io/

**Comment by wingkwong** [comment]
@deepshaswat can you double check the link

![image](https://github.com/nextui-org/nextui/assets/35857179/55386fef-5bf1-45ca-a2df-6a52dd3d86bf)

**Comment by deepshaswat** [comment]
Can you try again. https://stackblitzstartersvczyv6-z54r--3000--7dbe22a9.local-credentialless.webcontainer.io/
![Screen Shot 2024-04-16 at 09 48 48 AM](https://github.com/nextui-org/nextui/assets/1560547/e11985da-51bd-45d7-b705-1ec52ca7858f)

**Comment by deepshaswat** [comment]
This Menu bar: https://nextui.org/docs/components/navbar#with-dropdown-menu

**Comment by wingkwong** [comment]
@deepshaswat I still couldn't open the link. I think the link should be something like `https://stackblitz.com/edit/xxxxxxx`. Also from your screenshot, the styles are pretty broken. You may follow [installation](https://nextui.org/docs/guide/installation) to setup properly.

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3240
