### ISSUE TITLE
[BUG] - Navbar The Controlled Menu bar is not activated for the smaller screen

### ISSUE THREAD

**Issue by deepshaswat** [nextui-org/nextui#2729]
### NextUI Version

2.2.10

### Describe the bug

The menu bar is fixed and the control menu is never activated when all the sample codes are added

### Steps to Reproduce the Bug or Issue

Just copy the sample codes to a new NextJS project

### Expected behavior

it should work as shown in the sample

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Not able to reproduce the issue. Please share a Stackblitz link.
