### ISSUE TITLE
[BUG] - Spinner in v2.3.0 It's currently unsupported to use "export *" in a client boundary

### ISSUE THREAD

**Issue by sFritsch09** [nextui-org/nextui#2735]
### NextUI Version

2.3.0

### Describe the bug

Cannot use Spinner anymore in NextJS 14.2.1 build fails with error:

```sh
./node_modules/@nextui-org/react-utils/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.
```

Build worked in version 2.2.10

### Steps to Reproduce the Bug or Issue

Import Spinner in app router in any page.js and start build

1. `import { Spinner } from '@nextui-org/react';`
2. `yarn build`

### Expected behavior

Spinner should work with SSR

### Operating System Version

macOS

### Browser

Opera

**Comment by sFritsch09** [comment]
Oki thanks that helps, it is weird because it was working before...

**Comment by volfadar** [comment]
![Uploading image.png…]()
for those who use put NextUIProvider in the Layout as server components, try to redeclare NextUIProvider in anywhere with "use client" on top of the file.

**Comment by volfadar** [comment]
![Screenshot_87](https://github.com/nextui-org/nextui/assets/44869940/4d8b576d-6783-4484-9718-c8753260c6b3)

for those who use put NextUIProvider in the Layout as server components, try to redeclare NextUIProvider in anywhere with "use client" on top of the file.

**Comment by RobinGiel** [comment]
Just for the record, this was not the case before the recent update of the package.

**Comment by kemiljk** [comment]
I want to be clear, these changes are awesome! Super glad to see all of this. 

But...This is a pretty big breaking change for many codebases, might be worth communicating this more widely or offering a codemod to easily update to individual imports. Across a large codebase, this is a lot of work to resolve.

Took me a while to convert global imports to individual imports safely, so maybe worth some comms/messaging somewhere.

**Comment by Arek1997** [comment]
I had similar issue
./node_modules/.pnpm/@nextui-org+react-utils@2.0.11_react@18.2.0/node_modules/@nextui-org/react-utils/dist/index.mjs Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.

This line of code caused it
export * from "@nextui-org/react-rsc-utils";

I solved it by exports all function from this package manually
export { DOMEventNames, DOMPropNames, filterDOMProps, getValidChildren, pickChildren, renderFn } from "@nextui-org/react-rsc-utils";

**Comment by DannelCu** [comment]
> Hey, you can't import components directly from `@nextui-org/react` in a server component without using the `use client;` directive. You have two options:
> 
> 1. Use the component from its specific package, e.g., `import {Spinner} from '@nextui-org/spinner'`. This method is recommended because we have already added the `use client;` directive internally for components that require it, simplifying your setup.
> 2. Use the component from the main package `@nextui-org/react` and add the `use client;` directive at the top of your file.

this currenly it is not working because the directory structure have changed and it gives a module not found error in my case was the card and card header.

**Comment by wingkwong** [comment]
Please upgrade to the latest version. Now the react package will automatically include the use client; directive https://github.com/nextui-org/nextui/pull/2758

The advantage you have by using individual imports, is that not all components are client component, we have some of then that can run only on the server

e.g.

https://nextui.org/docs/components/badge
https://nextui.org/docs/components/code
https://nextui.org/docs/components/divider
https://nextui.org/docs/components/kbd

![image](https://github.com/nextui-org/nextui/assets/35857179/98d8d8d4-95b9-4158-a2bf-bbcb367466f6)

**Comment by DannelCu** [comment]
> Please upgrade to the latest version. Now the react package will automatically include the use client; directive #2758
> 
> The advantage you have by using individual imports, is that not all components are client component, we have some of then that can run only on the server
> 
> e.g.
> 
> https://nextui.org/docs/components/badge https://nextui.org/docs/components/code https://nextui.org/docs/components/divider https://nextui.org/docs/components/kbd
> 
> ![image](https://private-user-images.githubusercontent.com/35857179/323456409-98d8d8d4-95b9-4158-a2bf-bbcb367466f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTE4ODksIm5iZiI6MTcxMzQxMTU4OSwicGF0aCI6Ii8zNTg1NzE3OS8zMjM0NTY0MDktOThkOGQ4ZDQtOTViOS00MTU4LWEyYmYtYmJjYjM2NzQ2NmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAzMzk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MTYwZjFmNDVkNzllNWYzZjZjZDRjYjA0OGU0MTVjZjVhNmIyOGIwYjVjNTY1ZjU4Y2E2ZmIxYTgyNzRjYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cGT1uJgODd2ySFpwOD_rJKdeNiwgbT3DYY0-8g_3HJQ)

I had the latest version 2.3.2 and was getting an error from next-flight-loader, which stated that even on client components, it is not allowed. I have downgraded my next UI back to 2.2.10 and that solved the problem

**Comment by wingkwong** [comment]
@DannelCu please create a new issue with a minimal reproducible environment.

**Comment by emmadal** [comment]
for the next version you should import like this: 
`import {Spinner} from '@nextui-org/spinner'` if you try to import it in a server component
but in a client component, please add the `use client` directive at the top of file then you can use the old import.
e.g. import {Spinner} from '@nextui-org'

**Comment by ivstudio** [comment]
```./node_modules/@nextui-org/react/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.```

After updating from @nextui-org/react: `2.2.9` to `2.3.2`, I started receiving the above error. Unfortunately, reverting to the previous version doesn't resolve the issue. The only workaround so far is to add `'use client'` to any component using NextUI. However, this is a significant breaking change and requires substantial code updates, which is not ideal.
