### ISSUE TITLE
Default button type submit and not button

### ISSUE THREAD

**Issue by Keyruu** [nextui-org/nextui#274]
**Describe the bug**
The docs stated that the Buttons default native type should be `button`, but it's actually `submit`. The doc was updated, but the default should still be `button`.
https://nextui.org/docs/components/button#button-props

**Comment by jrgarciadev** [comment]
Thanks for reporting it @Keyruu 🙌🏻

**Comment by TokiyaHorikawa** [comment]
Is it ok if I do the fix for this issue?

**Comment by jrgarciadev** [comment]
For sure @TokiyaHorikawa
