### ISSUE TITLE
[BUG] - DropdownItem onPress not working

### ISSUE THREAD

**Issue by dml0031** [nextui-org/nextui#2743]
### NextUI Version

2.3.0

### Describe the bug

After the update, when trying to click on a `DropdownItem` using the `onPress` click handler, nothing happens. The dropdown just closes. If I disable `closeOnSelect` for both the `Dropdown` and `DropdownItem` and then try and use the `onPress` handler it works as intended.

### Steps to Reproduce the Bug or Issue

1. Add items to a `Dropdown`
2. Add `onPress` handler to `DropdownItem` inside the dropdown
3. Click on the dropdown Item
4. Dropdown will close without action inside the `onPress` does anything

### Expected behavior

Expect the `onPress` action to complete when clicking on the `DropdownItem`

### Operating System Version

Any

### Browser

Chrome

**Comment by daniel-esserweb** [comment]
I also have this issue, not only in the dropdown some others component also that have onPress action dont work

**Comment by jrgarciadev** [comment]
Hey guys, we're currently looking into this issue, please use the `onAction` in the meantime

e.g.

https://stackblitz.com/edit/vitejs-vite-sell4f?file=src%2FApp.tsx

**Comment by jrgarciadev** [comment]
@daniel-esserweb could you please tell us on which other components the `onPress` is not working?

**Comment by Reynard-G** [comment]
@jrgarciadev I've tested with `console.log` & Server Actions on `onPress` & `onClick`, both of which don't seem to work in the current version. Tested v2.2.10 and both event handlers work as expected.

**Comment by jmndao** [comment]
Same issues here, I don't why it stop functioning at some point
