### ISSUE TITLE
[BUG] - Failed to compile Next.JS

### ISSUE THREAD

**Issue by mihainiculai** [nextui-org/nextui#2748]
### NextUI Version

2.3.0

### Describe the bug

<img width="1449" alt="Screenshot 2024-04-16 at 23 57 26" src="https://github.com/nextui-org/nextui/assets/104020546/89da3bc8-9c7c-4d01-b700-fa6789584958">

### Steps to Reproduce the Bug or Issue

1. Open the app
2. ...

### Expected behavior

I must see the page. but...

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @mihainiculai please check this https://github.com/nextui-org/nextui/issues/2735#issuecomment-2059385978
