### ISSUE TITLE
[BUG] - Attempted import error after upgrade to 2.3.1

### ISSUE THREAD

**Issue by ChangwooLim** [nextui-org/nextui#2750]
### NextUI Version

2.3.1

### Describe the bug

Thank you for making beautiful library. Today, I tried to upgrade nextui to 2.3.1 by running `npx nextui-cli@latest upgrade` 
After that, when I run `npm run dev`, I got error 

```
 ✓ Ready in 2.8s
 ○ Compiling /middleware ...
 ✓ Compiled /middleware in 532ms (64 modules)
 ○ Compiling /not-found ...
 ⨯ ./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').

Import trace for requested module:
./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
./node_modules/@nextui-org/calendar/dist/index.mjs
./node_modules/@nextui-org/react/dist/index.mjs
./components/navbar.tsx
 ⨯ ./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').

Import trace for requested module:
./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
./node_modules/@nextui-org/calendar/dist/index.mjs
./node_modules/@nextui-org/react/dist/index.mjs
./components/navbar.tsx
 ⨯ ./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').

Import trace for requested module:
./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
./node_modules/@nextui-org/calendar/dist/index.mjs
./node_modules/@nextui-org/react/dist/index.mjs
./components/navbar.tsx
 ⨯ ./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').

Import trace for requested module:
./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
./node_modules/@nextui-org/calendar/dist/index.mjs
./node_modules/@nextui-org/react/dist/index.mjs
./components/navbar.tsx
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ⨯ ./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').

Import trace for requested module:
./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
./node_modules/@nextui-org/calendar/dist/index.mjs
```

./components/navbar.tsx does not include Calendar component. Not only navbar.tsx, but I didn't add anything after upgrade version.

I tried to downgrade to 2.2.10, and it worked as usual.
I'm using nextjs, and please let me know if there's more information needed

### Steps to Reproduce the Bug or Issue

1. Upgrade nextui to 2.3.1 by `npx nextui-cli@latest upgrade`
2. Run `npm run dev`

### Expected behavior

I expected my site shown normally, but got error `Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').`

### Operating System Version

Linux(Ubuntu 22.04)

### Browser

Chrome

**Comment by ChangwooLim** [comment]
import { Navbar as NextUINavbar, NavbarContent, NavbarMenu, NavbarMenuToggle, NavbarBrand, NavbarItem, NavbarMenuItem } from "@nextui-org/navbar";
import { Spacer } from "@nextui-org/react";
import { Link } from "@nextui-org/link";

For more information, above is list of nextui components called from navbar.tsx directly.

below is error shown at browser(shown around 1-2 sec and became `./node_modules/@nextui-org/calendar/dist/chunk-IYRE4RWH.mjs
Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').
`)
 1 of 1 unhandled error
Server Error
ModuleDependencyError: export 'calendar' (imported as 'calendar') was not found in '@nextui-org/theme' (possible exports: absoluteFullClasses, accordion, accordionItem, autocomplete, avatar, avatarGroup, badge, baseStyles, breadcrumbItem, breadcrumbs, button, buttonGroup, card, checkbox, checkboxGroup, chip, circularProgress, code, collapseAdjacentVariantBorders, colorVariants, colors, commonColors, dataFocusVisibleClasses, divider, drip, dropdown, dropdownItem, dropdownMenu, dropdownSection, focusVisibleClasses, groupDataFocusVisibleClasses, image, input, kbd, link, linkAnchorClasses, listbox, listboxItem, listboxSection, mappedSpacingScaleKeys, menu, menuItem, menuSection, modal, navbar, nextui, pagination, popover, progress, radio, radioGroup, ringClasses, scrollShadow, select, semanticColors, skeleton, slider, snippet, spacer, spacingScaleKeys, spinner, table, tabs, toggle, translateCenterClasses, tv, user)

**Comment by ChangwooLim** [comment]
What I did
1. Upgrade tailwind to latest version(3.4.3)
2. Upgrade @nextui-org/theme to latest version(but had latest version, 2.2.0)

```
		"@nextui-org/button": "2.0.26",
		"@nextui-org/code": "2.0.24",
		"@nextui-org/input": "2.1.16",
		"@nextui-org/kbd": "2.0.25",
		"@nextui-org/link": "2.0.26",
		"@nextui-org/navbar": "^2.0.28",
		"@nextui-org/react": "^2.2.10",
		"@nextui-org/snippet": "2.0.30",
		"@nextui-org/switch": "2.0.25",
		"@nextui-org/system": "2.0.15",
		"@nextui-org/theme": "^2.2.0",
```

above is nextui part of my package.json

**Comment by wingkwong** [comment]
Can you also try the following

- bump `@nextui-org/system` to latest, i.e. `2.1.0`
- remove node_modules and reinstall

**Comment by ChangwooLim** [comment]
Thank you for reply
- bump @nextui-org/system to latest, i.e. 2.1.0
-> It worked but having another problem
-> Now, I have to add "use client"; where it wasn't needed

```
 ⨯ ./node_modules/@nextui-org/system/node_modules/@nextui-org/react-utils/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.
Import trace for requested module:
./node_modules/@nextui-org/system/node_modules/@nextui-org/react-utils/dist/index.mjs
./node_modules/@nextui-org/system/dist/chunk-EXMY5KYR.mjs
./node_modules/@nextui-org/system/dist/index.mjs
./node_modules/@nextui-org/react/dist/index.mjs
./app/FreeApps.tsx
./app/page.tsx
```

If I add "use client"; at app/page.tsx, it works. But is it necessary to add "use client"?

For whom having same problem
- remove node_modules and reinstall
-> It didn't work for me. I tried it before submitting issue.

**Comment by ChangwooLim** [comment]
I found solution at [another issue](https://github.com/nextui-org/nextui/issues/2735#issuecomment-2059385978).

I'll fix and leave feedback

**Comment by Jayszu** [comment]
> I found solution at [another issue](https://github.com/nextui-org/nextui/issues/2735#issuecomment-2059385978).
> 
> I'll fix and leave feedback

Did this but still doesnt work

**Comment by Arek1997** [comment]
I had similar issue
`./node_modules/.pnpm/@nextui-org+react-utils@2.0.11_react@18.2.0/node_modules/@nextui-org/react-utils/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.`

This line of code caused it
`export * from "@nextui-org/react-rsc-utils";`

I solved it by exports all function from this package manually
`export {
  DOMEventNames,
  DOMPropNames,
  filterDOMProps,
  getValidChildren,
  pickChildren,
  renderFn
} from "@nextui-org/react-rsc-utils";`

**Comment by ldystudio** [comment]
It looks like it's working fine, thanks.

**Comment by wingkwong** [comment]
Closing:

- original issue was resolved by bumping `@nextui-org/system` to latest version
- for `Error: It's currently unsupported to use "export *" in a client boundary` issue, please refer to [this comment](https://github.com/nextui-org/nextui/issues/2735#issuecomment-2059385978).
