### ISSUE TITLE
[BUG] - onPress, onPressStart, onPressEnd, onPressChange, onPressUp and onClick not working in DropdownItem

### ISSUE THREAD

**Issue by rivaslive** [nextui-org/nextui#2751]
### NextUI Version

2.3.1

### Describe the bug

onClick, onPress and derivatives events not working in latest version inside of DropdownItem

### Steps to Reproduce the Bug or Issue

1. include a console.log in onPress in DropdownItem

### Expected behavior

Let the function be executed

### Operating System Version

macOS

### Browser

Chrome

**Comment by DevelopJKong** [comment]
same problem

**Comment by charklewis** [comment]
Same issue here

**Comment by j-vitali** [comment]
same issues

**Comment by jmndao** [comment]
Same problem here.

**Comment by rivaslive** [comment]
https://github.com/nextui-org/nextui/pull/2763 Fixed this.
