### ISSUE TITLE
[BUG] - Controlled Checkbox remains checked despite state being false

### ISSUE THREAD

**Issue by NickNaskida** [nextui-org/nextui#2752]
### NextUI Version

2.3.1

### Describe the bug

The checkbox selection broke after upgrading to 2.3.1. I am using the controlled checkbox and it shows me the checked icon when it's checked state is false. I was using the version 2.2.10 before and it was working. I assume smth change with the new update.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-canhwr?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Go to `App.tsx` & main rendered page
2. Click one of the checkboxes
3. Click another checkbox
4. See that the first checkbox's icon remains checked, but `isSelected` is false

### Expected behavior

As a user, I expected the checkbox to show not selected state (the one without the checkbox icon), but it shows it despite the state being false. Everything has been working on NextUI v2.2.10 but after the update to 2.3.1, it broke.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/82929931/534bf1c8-a791-4aae-86c7-b5c0b2ca72ec

### Operating System Version

macOS

### Browser

Chrome

**Comment by j-vitali** [comment]
aiia very very bad.... how we can use such library in production??
