### ISSUE TITLE
Build Error in nextjs

### ISSUE THREAD

**Issue by daphnesaj** [nextui-org/nextui#2755]
### NextUI Version

14.2.1

### Describe the bug

./node_modules/@nextui-org/react-utils/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.

### Steps to Reproduce the Bug or Issue

1. I added the button component and implemented it and it broke my code,.
2. I rerun the project and then this happened.

### Expected behavior

I cant run the project because of this

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/79005254/482e24d5-7f4c-4dd6-a4ee-03b458f5d2c2)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
See [this comment](https://github.com/nextui-org/nextui/issues/2735#issuecomment-2059385978)

**Comment by Arek1997** [comment]
I had similar issue
./node_modules/.pnpm/@nextui-org+react-utils@2.0.11_react@18.2.0/node_modules/@nextui-org/react-utils/dist/index.mjs Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.

This line of code caused it
export * from "@nextui-org/react-rsc-utils";

I solved it by exports all function from this package manually
export { DOMEventNames, DOMPropNames, filterDOMProps, getValidChildren, pickChildren, renderFn } from "@nextui-org/react-rsc-utils";
