### ISSUE TITLE
[BUG] - Error while compiling after updating to 2.3.1

### ISSUE THREAD

**Issue by jannikdresselhaus** [nextui-org/nextui#2756]
### NextUI Version

2.3.1

### Describe the bug

When importing a component in a client boundary, I receive the error:

./node_modules/@nextui-org/react-utils/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.

### Steps to Reproduce the Bug or Issue

1. Import NextUI component within client boundary
2. Try to build project using npm run build

### Expected behavior

I expected to compile without errors. The error was introduced after upgrading to the new version.

### Operating System Version

Linux

### Browser

Chrome

**Comment by wingkwong** [comment]
See [this comment](https://github.com/nextui-org/nextui/issues/2735#issuecomment-2059385978).
