### ISSUE TITLE
[BUG] - DatePicker cannot override Input Slot

### ISSUE THREAD

**Issue by xxxijustwei** [nextui-org/nextui#2770]
### NextUI Version

2.3.3

### Describe the bug

DatePicker cannot override Input Slot

### Steps to Reproduce the Bug or Issue

```ts
                <DatePicker 
                    name="issue_date"
                    label="Issue Date"
                    variant="bordered"
                    timeInputProps={{
                        classNames: {
                            label: "text-red-200"
                        }
                    }}
                />
```

### Expected behavior

ignore

### Screenshots or Videos

<img width="323" alt="image" src="https://github.com/nextui-org/nextui/assets/19197493/6d73c6f0-6c25-4652-9d18-416325de9947">

### Operating System Version

macOS

### Browser

Chrome

**Comment by razvanilin** [comment]
I just experienced this as well. I was trying to modify the `inputWrapper` slot through `timeInputProps` but no luck

**Comment by AmazingTurtle** [comment]
@ryo-manba further it would be great if there was away to properly customize the DatePicker with the `extendVariants` way. I see that slotted components in general are difficult to properly style every now and then. Same goes for the DropDown, for example, where you can not predefine itemClasses unfortunately. What's your take on that in the future?
