### ISSUE TITLE
[BUG] - Page freezing when clicking on dropdown button

### ISSUE THREAD

**Issue by utkarsh-source** [nextui-org/nextui#2771]
### NextUI Version

2.3.0

### Describe the bug
- As soon as you click on the dropdown button nothing appears and the page wont scroll any more unless you click again . Probably the dropdown is rendered but may have be overlapped with content of higher z index value.

## Issue happens at this page.
- [https://nextui.org/docs/components/dropdown](url)

### Steps to Reproduce the Bug or Issue

1. Go to the components then dropdown.
2. Click on any of the dropdown button example.
3. Observe that the page freezes and no dropdown appears.

### Expected behavior

Dropdown content should appear a when clicking the dropdown button.

### Screenshots or Videos

[scrnli_4_18_2024_12-59-27 PM.webm](https://github.com/nextui-org/nextui/assets/54720265/4f22db09-807c-4ce9-b8dc-2d3be22d43fe)

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by viettran2502** [comment]
Popover too.

**Comment by wingkwong** [comment]
duplicate - Tracked [here](https://github.com/nextui-org/nextui/issues/2768) instead.
