### ISSUE TITLE
[Feature Request] - Create a File Upload Input System

### ISSUE THREAD

**Issue by muhammadasif-wd** [nextui-org/nextui#2774]
### Is your feature request related to a problem? Please describe.

The current absence of a file upload input system within our project creates a bottleneck for users wanting to seamlessly add attachments or multimedia content. This leads to a fragmented user experience and a reliance on external hosting services, complicating the workflow.

### Describe the solution you'd like

**1. File Upload Input Component:** Introduce a dedicated component or form input designed specifically for file uploads.
**2. User Interface Enhancement:** Design a user-friendly interface with clear instructions and feedback for successful uploads, including progress indicators.
**3. Backend Implementation:** Develop backend logic to securely handle uploaded files, incorporating file type validation, size limits, and efficient storage management.
**4. Error Handling Mechanisms:** Implement robust error handling to address issues like oversized files, unsupported formats, and server-side errors, providing informative messages to users.
**5. Accessibility Considerations:** Ensure the file upload feature adheres to accessibility standards, ensuring usability for all users, including those using assistive technologies.

**Desired Outcome**
I envision a seamless file upload experience within our project's interface, enabling users to effortlessly add files directly without interruptions. This enhancement will elevate user satisfaction, streamline workflows, and promote collaboration by simplifying the sharing of essential project assets.

### Describe alternatives you've considered

**Alternative Considerations**
While considering alternatives, integrating third-party file upload libraries or APIs was explored. However, these solutions often lack the seamless integration, customization, and security assurances that a native file upload input system can provide. Thus, an in-house implementation is preferred for optimal functionality and user experience.

Please let me know if further details or clarifications are needed. Thank you for considering this feature request.

**Comment by wingkwong** [comment]
will be tracked here: #3772
