### ISSUE TITLE
[BUG] - Popover is not showing in right place

### ISSUE THREAD

**Issue by RK1PF** [nextui-org/nextui#2775]
### NextUI Version

@nextui-org/popover: 2.1.18

### Describe the bug

The Poporver is not showing in the right place, it is displayed at the bottom of the page.
![image](https://github.com/nextui-org/nextui/assets/88942109/e57f9789-4783-40e5-8a0d-8676ccaa1ffa)

It is not working even in the NextUI official docs [page](https://nextui.org/docs/components/popover):

### Steps to Reproduce the Bug or Issue

I'm using the [template ](https://nextui.org/docs/frameworks/nextjs) for NextJS and I have just added the Popover component to the '/about' page.

### Expected behavior

The Popover is supposed to show at the level of the button that is triggering it

### Operating System Version

Windows

### Browser

Firefox, Chrome, Edge

**Comment by DevelopJKong** [comment]
I've encountered the same problem with the previsous version after updating and then rolling back your library. can you stop this same happening when we rollback your library?

**Comment by wingkwong** [comment]
Fixed in [v2.3.4](https://github.com/nextui-org/nextui/releases/tag/%40nextui-org%2Freact%402.3.4)
