### ISSUE TITLE
[BUG] - Upgrading to 2.3 from 2.2 on Next 14.2.2 breaks my app

### ISSUE THREAD

**Issue by ybwai** [nextui-org/nextui#2777]
### NextUI Version

2.3.3

### Describe the bug

```
 ⨯ ./node_modules/@nextui-org/react-utils/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.
Import trace for requested module:
./node_modules/@nextui-org/react-utils/dist/index.mjs
./node_modules/@nextui-org/system/dist/chunk-EXMY5KYR.mjs
./node_modules/@nextui-org/system/dist/index.mjs
./node_modules/@nextui-org/react/dist/index.mjs
```

### Steps to Reproduce the Bug or Issue

With next 14.2.2 and @nextui-org/react 2.2.10 all is working fine, as soon as I upgrade to next ^2.3 my app breaks with the above error.

### Expected behavior

Upgrade should be backwards compatible and my app should still work. 

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Duplicate - tracked [here](https://github.com/nextui-org/nextui/issues/2749)
