### ISSUE TITLE
[BUG] - BUILD_FAILED_EXPORT_ISSUE

### ISSUE THREAD

**Issue by pithou** [nextui-org/nextui#2785]
### NextUI Version

2.3.0

### Describe the bug

impossible to build my app with the latest version export issue

./node_modules/@nextui-org/react-utils/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.
    at Object.transformSource (node_modules/next/dist/build/webpack/loaders/next-flight-loader/index.js:69:31)

### Steps to Reproduce the Bug or Issue

nextjs app install version 2.3.0

npm run build

      <Button as={Link} href="/home">
        Test
      </Button>

### Expected behavior

should be able to build next app with latest version 
npm run build should not show an error

### Operating System Version

macOs

### Browser

Chrome

**Comment by wingkwong** [comment]
Duplicate - track [here](https://github.com/nextui-org/nextui/issues/2749)
