### ISSUE TITLE
[BUG] - Input Clear Button No Longer Working

### ISSUE THREAD

**Issue by clementohNZ** [nextui-org/nextui#2791]
### NextUI Version

2.3.5

### Describe the bug

When you try to clear the input using the clear button, the value is emptied, but the input still displays the uncleared text.

You can try it directly on the docs page: https://nextui.org/docs/components/input#clear-button

### Steps to Reproduce the Bug or Issue

You can try it directly on the docs page: https://nextui.org/docs/components/input#clear-button and try to clear the input.

### Expected behavior

I still see the text I tried to clear and I cannot get rid of it.

### Operating System Version

macOS Sonoma 14.3.1 (23D60)

### Browser

Chrome

**Comment by Zz-ZzzZ** [comment]
Hello, In the documentation example, `onClear` calls `console.log` so it has no working when the Clear button is clicked. You can switch to other state-changing operations like `setState()`

```import React from "react";
import {Input} from "@nextui-org/react";

export default function App() {
  return (
    <Input
      isClearable
      type="email"
      label="Email"
      variant="bordered"
      placeholder="Enter your email"
      defaultValue="junior@nextui.org"
      onClear={() => console.log("input cleared")}
      className="max-w-xs"
    />
  );
}

**Comment by wingkwong** [comment]
@ShrinidhiUpadhyaya I'll take over this.
