### ISSUE TITLE
[Feature Request] Date Picker support for dd/mm/yyyy and yyyy/mm/dd

### ISSUE THREAD

**Issue by Armandotrsg** [nextui-org/nextui#2792]
### Is your feature request related to a problem? Please describe.

In most countries we don't use the American date format

### Describe the solution you'd like

As an international user, I would expect to able to configure the date picker to be set using the dd/mm/yyyy or the yyyy/mm/dd

### Describe alternatives you've considered

-

**Comment by MartaBento** [comment]
@Armandotrsg can you check if wrapping the component with I18nProvider and the locale set for what you need solves your issue? I'm currently using:

```
<I18nProvider locale="en-GB">
<DateInput />
</I18nProvider>
```

And this allows me to use the configuration dd/mm/yyyy.

**Comment by getellez** [comment]
> @Armandotrsg can you check if wrapping the component with I18nProvider and the locale set for what you need solves your issue? I'm currently using:
> 
> ```
> import { I18nProvider } from "@react-aria/i18n";
> import { DateInput } from "@nextui-org/react";
> 
> <I18nProvider locale="en-GB">
> <DateInput ... />
> </I18nProvider>
> ```
> 
> And this allows me to use the configuration dd/mm/yyyy.

it didn't work for me, could you show a screenshot of it working with the dd/mm/yyyy format?

**Comment by Armandotrsg** [comment]
> > @Armandotrsg can you check if wrapping the component with I18nProvider and the locale set for what you need solves your issue? I'm currently using:
> > ```
> > import { I18nProvider } from "@react-aria/i18n";
> > import { DateInput } from "@nextui-org/react";
> > 
> > <I18nProvider locale="en-GB">
> > <DateInput ... />
> > </I18nProvider>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And this allows me to use the configuration dd/mm/yyyy.
> 
> it didn't work for me, could you show a screenshot of it working with the dd/mm/yyyy format?

Thanks! It worked for me, it even allows to use it in Spanish as well:

```tsx
<I18nProvider locale="es-GB">
      <DateRangePicker
        value={date}
        onChange={setDate}
        label="Fecha de postulación"
        description="dd/mm/yyyy"
        labelPlacement="outside"
      />
</I18nProvider>
```

![CleanShot 2024-04-20 at 12 33 03@2x](https://github.com/nextui-org/nextui/assets/105229933/84b06792-14fd-4a7d-aa7c-f36facb7e45e)

**Comment by jrgarciadev** [comment]
Hey guys you can set up this globally using the `NextUIProvider` `locale` property https://nextui.org/docs/api-references/nextui-provider#locale

Supported locales:

```
const localeValues = [
  'fr-FR', 'fr-CA', 'de-DE', 'en-US', 'en-GB', 'ja-JP',
  'da-DK', 'nl-NL', 'fi-FI', 'it-IT', 'nb-NO', 'es-ES', 'sv-SE', 'pt-BR',
  'zh-CN', 'zh-TW', 'ko-KR', 'bg-BG', 'hr-HR', 'cs-CZ', 'et-EE', 'hu-HU',
  'lv-LV', 'lt-LT', 'pl-PL', 'ro-RO', 'ru-RU', 'sr-SP', 'sk-SK', 'sl-SI', 'tr-TR', 'uk-UA',
  'ar-AE', 'ar-DZ', 'AR-EG', 'ar-SA', 'el-GR', 'he-IL', 'fa-AF', 'am-ET', 'hi-IN', 'th-TH'
];



const calendars = [
  'gregory', 'japanese', 'buddhist', 'roc', 'persian', 'indian',
  'islamic-umalqura', 'islamic-civil', 'islamic-tbla', 'hebrew',
  'coptic', 'ethiopic', 'ethioaa'
]
```

So for Spanish, you could do the following:

```tsx
"use client";

import {type ReactNode} from "react";
import {NextUIProvider} from "@nextui-org/react";

export function AppProvider(props: AppProviderProps) {
  const {children, className} = props;

  return (
    <NextUIProvider locale="es-ES" className={className}>
      {children}
    </NextUIProvider>
  );
}

interface AppProviderProps {
  children: ReactNode;
  className?: string;
}
```

**Comment by tjfaith** [comment]
> > > @Armandotrsg can you check if wrapping the component with I18nProvider and the locale set for what you need solves your issue? I'm currently using:
> > > ```
> > > import { I18nProvider } from "@react-aria/i18n";
> > > import { DateInput } from "@nextui-org/react";
> > > 
> > > <I18nProvider locale="en-GB">
> > > <DateInput ... />
> > > </I18nProvider>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And this allows me to use the configuration dd/mm/yyyy.
> > 
> > 
> > it didn't work for me, could you show a screenshot of it working with the dd/mm/yyyy format?
> 
> Thanks! It worked for me, it even allows to use it in Spanish as well:
> 
> ```tsx
> <I18nProvider locale="es-GB">
>       <DateRangePicker
>         value={date}
>         onChange={setDate}
>         label="Fecha de postulación"
>         description="dd/mm/yyyy"
>         labelPlacement="outside"
>       />
> </I18nProvider>
> ```
> 
> ![CleanShot 2024-04-20 at 12 33 03@2x](https://private-user-images.githubusercontent.com/105229933/324198128-84b06792-14fd-4a7d-aa7c-f36facb7e45e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzY1MDMsIm5iZiI6MTcxNzIzNjIwMywicGF0aCI6Ii8xMDUyMjk5MzMvMzI0MTk4MTI4LTg0YjA2NzkyLTE0ZmQtNGE3ZC1hYTdjLWYzNmZhY2I3ZTQ1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMDAzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTQ3NzM4OTE5OTgwMmVlMjI5ODQzZmM0N2E2ZjJhYWNjYjBkYjBlYjkzMWViY2Y0ODVjNjNlZTE3NWMyMTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hMWSQek7UCVSyF14Hojv8pa3KQXbeXU1FmK7Goe_evA)

This dosnt work for me, i want to be able to get formatt the Input like this mm/yyyy

**Comment by tjfaith** [comment]
how do i get only month and year, i need to formatt it like this mm/yyyy

**Comment by maxtsh** [comment]
> Hey guys you can set up this globally using the `NextUIProvider` `locale` property https://nextui.org/docs/api-references/nextui-provider#locale
> 
> Supported locales:
> 
> ```js
> const localeValues = [
>   'fr-FR', 'fr-CA', 'de-DE', 'en-US', 'en-GB', 'ja-JP',
>   'da-DK', 'nl-NL', 'fi-FI', 'it-IT', 'nb-NO', 'es-ES', 'sv-SE', 'pt-BR',
>   'zh-CN', 'zh-TW', 'ko-KR', 'bg-BG', 'hr-HR', 'cs-CZ', 'et-EE', 'hu-HU',
>   'lv-LV', 'lt-LT', 'pl-PL', 'ro-RO', 'ru-RU', 'sr-SP', 'sk-SK', 'sl-SI', 'tr-TR', 'uk-UA',
>   'ar-AE', 'ar-DZ', 'AR-EG', 'ar-SA', 'el-GR', 'he-IL', 'fa-AF', 'am-ET', 'hi-IN', 'th-TH'
> ];
> 
> const calendars = [
>   'gregory', 'japanese', 'buddhist', 'roc', 'persian', 'indian',
>   'islamic-umalqura', 'islamic-civil', 'islamic-tbla', 'hebrew',
>   'coptic', 'ethiopic', 'ethioaa'
> ]
> ```
> 
> So for Spanish, you could do the following:
> 
> ```tsx
> "use client";
> 
> import {type ReactNode} from "react";
> import {NextUIProvider} from "@nextui-org/react";
> 
> export function AppProvider(props: AppProviderProps) {
>   const {children, className} = props;
> 
>   return (
>     <NextUIProvider locale="es-ES" className={className}>
>       {children}
>     </NextUIProvider>
>   );
> }
> 
> interface AppProviderProps {
>   children: ReactNode;
>   className?: string;
> }
> ```

Is there any way to change the locale using a hook?

**Comment by arit98** [comment]
![Screenshot 2024-12-15 094657](https://github.com/user-attachments/assets/547716da-2cef-4a82-a9e2-c409030597d8)

Ihave used this - 
<I18nProvider locale="en-GB">
                            <DatePicker
                                    isRequired
                                    aria-label="rfxSubmissionDate"
                                    className="w-4/5"
                                    minValue={parseDate(new Date().toISOString().split('T')[0])}
                                    value={rfxSubmissionDate && parseDate(rfxSubmissionDate.toISOString().split('T')[0])}
                                    onChange={(val) => setRfxSubmissionDate(new Date(val.toString()))}
                                />
                            </I18nProvider>
                            
                            problem remain same

**Comment by fahry-mohammed** [comment]
Changing the locale in the provider updates the language of the calendar and its format. However, I need to keep the calendar localization in Swedish while ensuring the format is always `DD/MM/YYYY`, regardless of the language. Is there an option for this in the NextUI (HeroUI) `DatePicker` and `DateRangePicker`?

**Comment by intermarkec** [comment]
Bump

**Comment by stiang** [comment]
Is there any chance of getting this reopened? Unless I’m missing something there is still no way to change just the format - you have to change the entire locale, which is just plain wrong in many (most?) cases. Changing the format to better suit the context without changing anything else about the locale seems like a perfectly valid thing to want/need to do.

I understand that this might be a pain to support, depending on how the date picker is implemented, but it seems wrong to just point to the ability to change the locale as a solution.
