### ISSUE TITLE
Input component

### ISSUE THREAD

**Issue by krystofex** [nextui-org/nextui#28]
Something like this
![image](https://user-images.githubusercontent.com/48121710/132986023-783279a7-34ec-4134-bdaa-686c517d934e.png)

**Comment by DaniAcu** [comment]
Hi @jrgarciadev! Are you already working on this? I'd like to contribute to that 😁

**Comment by jrgarciadev** [comment]
Hi @DaniAcu, yes I'm currently working on it

I appreciate your contribution intention, however, is core functionality and I'm adjusting design stuff and at the same time writing the code, at the moment are only available fixes or improvements to existing components/docs 

Would you like to help the project with another thing? join the discord community to explain the details -> [Discord Invitation](https://discord.gg/9b6yyZKmH4)


Thanks! 🤗
