### ISSUE TITLE
[BUG] - Date range picker gives aria label warning even when labelled

### ISSUE THREAD

**Issue by markwilson** [nextui-org/nextui#2804]
### NextUI Version

2.3.5

### Describe the bug

Using the date range picker (a great new addition!) causes lots of aria warnings.

<img width="557" alt="Monosnap trippix 2024-04-19 09-04-23" src="https://github.com/nextui-org/nextui/assets/81990/15d08bcd-c850-491c-9dee-d0e9bc3b96f6">

### Your Example Website or App

```
<DateRangePicker
  key={index} // I'm looping over a bunch of planned date ranges
  label="Dates"
  value={{ start: plan.dates.start, end: plan.dates.end }}
  isRequired
/>
```

### Steps to Reproduce the Bug or Issue

1. Use the `DateRangePicker` (even with a `label`)

### Expected behavior

There shouldn't be any warnings, but there are. You can see them on the [`DateRangePicker` docs page](https://nextui.org/docs/components/date-range-picker).

### Screenshots or Videos

<img width="557" alt="Monosnap trippix 2024-04-19 09-04-23" src="https://github.com/nextui-org/nextui/assets/81990/f88406af-b6c4-4b3f-bd94-c28a044fad3b">

### Operating System Version

macOS

### Browser

Chrome

**Comment by classmateoula** [comment]
console.warn = console.log;
