### ISSUE TITLE
Module '"@nextui-org/react"' has no exported member 'DatePicker' getting error when try to import

### ISSUE THREAD

**Issue by Gauravdeshmukh42** [nextui-org/nextui#2816]
### NextUI Version

2.3.5

### Describe the bug

Module '"@nextui-org/react"' has no exported member 'DatePicker' after install date picker then try to import getting that error

### Steps to Reproduce the Bug or Issue

import { DatePicker } from '@nextui-org/react';   // this line getting error Module '"@nextui-org/react"' has no exported member 'DatePicker'
  
   <DatePicker
      label={label}
      variant='bordered'
      hideTimeZone
      showMonthAndYearPickers
      defaultValue={now(getLocalTimeZone())}           // Cannot find name 'getLocalTimeZone'.
    />

### Expected behavior

resolve that correct import functionality

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/33284035/11b1fe00-f48c-49d2-8470-8d563c04c9c4)

### Operating System Version

windows 11

### Browser

Chrome

**Comment by neghilovvio** [comment]
i got the same problem but i'm not able to access the shared link
