### ISSUE TITLE
[BUG] - Marker is not show as well with custom maxValue

### ISSUE THREAD

**Issue by rahXephonz** [nextui-org/nextui#2819]
### NextUI Version

latest

### Describe the bug

i'm happy when nextui come with tailwind customization also i'm bigfan of tailwind so i have some issue when im using next ui slider with custom maxValue, marks is not showing in slider

this is code that i give to reproduce

```tsx
const LeverageSlider = () => (
  <Slider
    showTooltip
    showSteps
    size="sm"
    tooltipProps={{classNames: {content: "text-xs bg-bw-primary-blue-500"}}}
    color="foreground"
    label="BTC/USD Leverage"
    maxValue={125}
    className="pt-4"
    minValue={0}
    defaultValue={0}
    classNames={{
      step: "step-item !scale-90",
      track: "bg-[#363636] h-1",
      mark: "text-xs font-medium",
      value: "text-xs",
      filler: "bg-[#D9D9D9]",
      thumb:
        "bg-bw-primary-blue-500 after:bg-bw-primary-blue-500 h-1 z-[1] data-[focused='true']:!outline-none",
    }}
    renderLabel={(props) => (
      <p className="pb-2 text-[13px] font-medium text-bw-gray-300">{props.children}</p>
    )}
    marks={[
      {
        value: 0,
        label: "0x",
      },
      {
        value: 25,
        label: "25x",
      },
      {
        value: 50,
        label: "50x",
      },
      {
        value: 75,
        label: "75x",
      },
      {
        value: 100,
        label: "100x",
      },
      {
        value: 125,
        label: "125x",
      },
    ]}
  />
);
```

### Steps to Reproduce the Bug or Issue

```tsx
const LeverageSlider = () => (
  <Slider
    showTooltip
    showSteps
    size="sm"
    tooltipProps={{classNames: {content: "text-xs bg-bw-primary-blue-500"}}}
    color="foreground"
    label="BTC/USD Leverage"
    maxValue={125}
    className="pt-4"
    minValue={0}
    defaultValue={0}
    classNames={{
      step: "step-item !scale-90",
      track: "bg-[#363636] h-1",
      mark: "text-xs font-medium",
      value: "text-xs",
      filler: "bg-[#D9D9D9]",
      thumb:
        "bg-bw-primary-blue-500 after:bg-bw-primary-blue-500 h-1 z-[1] data-[focused='true']:!outline-none",
    }}
    renderLabel={(props) => (
      <p className="pb-2 text-[13px] font-medium text-bw-gray-300">{props.children}</p>
    )}
    marks={[
      {
        value: 0,
        label: "0x",
      },
      {
        value: 25,
        label: "25x",
      },
      {
        value: 50,
        label: "50x",
      },
      {
        value: 75,
        label: "75x",
      },
      {
        value: 100,
        label: "100x",
      },
      {
        value: 125,
        label: "125x",
      },
    ]}
  />
);
```

### Expected behavior

expected marks is working well on non decimal value like 0.25

### Screenshots or Videos

<img width="374" alt="Screenshot 2024-04-20 at 17 49 41" src="https://github.com/nextui-org/nextui/assets/77242429/22e23cbe-b414-4dc3-a7ed-a68527c6b315">

### Operating System Version

Mac

### Browser

Chrome

**Comment by wingkwong** [comment]
@rahXephonz I'm still trying to understand the issue. Is this what you want? If so, you can just add `step={0.25}`.

<img width="467" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/a8e5432d-4aba-4ed9-abc1-6f8e9a745dc0">

**Comment by rahXephonz** [comment]
No, i mean the marker points is not showing for the steps.

**Comment by wingkwong** [comment]
Are you talking about these red points for each marks?

<img width="472" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/3520ca10-da12-4797-980d-bc7f71320391">

**Comment by rahXephonz** [comment]
Yes how you do that?

**Comment by wingkwong** [comment]
@rahXephonz First you need to define `step`. In my above example, I set `step={25}`. Please note that if you set a relatively small amount (says, `step={0.25}`), then they will packed extremely closed and you barely to notice them like in my first screenshot. For the color of the points, you can change the styles by adding the classes in `classNames.step`.

**Comment by rahXephonz** [comment]
> @rahXephonz First you need to define `step`. In my above example, I set `step={25}`. Please note that if you set a relatively small amount (says, `step={0.25}`), then they will packed extremely closed and you barely to notice them like in my first screenshot. For the color of the points, you can change the styles by adding the classes in `classNames.step`.

Ahh i see

So if we give a maxValue to 120 then step must be 120 / TOTAL_MARKER = 30 in this case

Now the marker should be showing expected.
