### ISSUE TITLE
[BUG] - Date Range Picker Causes "Maximum update depth exceeded" error when hovering quickly over the dates

### ISSUE THREAD

**Issue by NaderElmahdy** [nextui-org/nextui#2820]
### NextUI Version

2.3.0

### Describe the bug

When using the Date Range Picker component, if I slowly hover over the dates, it works fine, but if I move my mouse quickly over different days, the app breaks and I get an error: "Maximum update depth exceeded".
The error occurs whether the component is controlled or not.

### Steps to Reproduce the Bug or Issue

just import { DateRangePicker } from "@nextui-org/date-picker"
click the calender icon to open the popover.
move the mouse quickly over different days.

### Expected behavior

to work just fine without breaking the app.

### Operating System Version

Windows 11

### Browser

Edge

**Comment by X-Vneer** [comment]
hope this get fixed soon

**Comment by smultar** [comment]
Looking into this issue now.

**Comment by smultar** [comment]
Confirmation on `chrome` is also experiencing this issue. I've tested on all major browsers on MacOS and Windows, leaving windows being the only OS that is receiving this bug.

**Comment by daniel-esserweb** [comment]
I also have the same issue, in my case im using RangeCalendar

**Comment by muhammadasif-wd** [comment]
I am facing the same issue, as soon as please fix this issue.

**Comment by auvansang** [comment]
Me too

**Comment by Bassonlinho** [comment]
Any updates to this?

**Comment by mihainiculai** [comment]
I have this problem just with `visibleMonths >= 2`

**Comment by jrgarciadev** [comment]
Hey guys, please install `v2.3.6`

**Comment by pablojsx** [comment]
I have the same issue with Autocomplete

**Comment by wingkwong** [comment]
@pablojsx please create a new issue and share the details.

**Comment by pablojsx** [comment]
> @pablojsx please create a new issue and share the details.

it works if I set the item key to something different than configName which is a string. If I use the same value for the children and key it throws the same error "Maximum update depth exceeded".

**Comment by takho-hotak** [comment]
> it works if I set the item key to something different than configName which is a string. If I use the same value for the children and key it throws the same error "Maximum update depth exceeded".

Same for me, the key and the AutocompleteItem content must be different to avoid the Maximum update depth exceeded error
