### ISSUE TITLE
[BUG] - Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').

### ISSUE THREAD

**Issue by neghilovvio** [nextui-org/nextui#2831]
### NextUI Version

2.2.9

### Describe the bug

"use client";
import { DatePicker } from "@nextui-org/date-picker";

export default function DashboardPage() {
  return (
      <DatePicker label={"Birth date"} className="max-w-sm" />
  );
}

I got this component, but I receive the following error:

'''
Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').
'''

 I receive the same error with calendar related lib like DateInput.

### Steps to Reproduce the Bug or Issue

My package.json  most relevant libraries
{
    "@nextui-org/button": "2.0.26",
    "@nextui-org/code": "2.0.24",
    "@nextui-org/date-input": "^2.0.3",
    "@nextui-org/date-picker": "^2.0.6",
    "@nextui-org/input": "2.1.16",
    "@nextui-org/kbd": "2.0.25",
    "@nextui-org/link": "2.0.26",
    "@nextui-org/navbar": "2.0.27",
    "@nextui-org/react": "^2.2.9",
    "@nextui-org/snippet": "2.0.30",
    "@nextui-org/switch": "2.0.25",
    "@nextui-org/system": "2.0.15",
    "@nextui-org/theme": "2.1.17",
    "next": "14.0.2",
    "next-themes": "^0.2.1",
    "react": "18.2.0",
    "tailwindcss": "3.4.3",
    "typescript": "5.0.4"
    }
    
    
and the component
    
"use client";
import { DatePicker } from "@nextui-org/date-picker";

export default function DashboardPage() {
  return (
      <DatePicker label={"Birth date"} className="max-w-sm" />
  );
}

### Expected behavior

The DatePicker component have to be rendered.

### Operating System Version

macos, Sonoma 14.3

### Browser

Chrome

**Comment by wingkwong** [comment]
calendar & date picker were introduced since `@nextui-org/react@2.3.0`. In theme package, that would be >= 2.2.0. Please note that if you use `@nextui-org/react`, you don't need to see other packages since it has already bundled them.

Hence, you just need to bump the versions to the latest.
