### ISSUE TITLE
[BUG] - Modal does not adjust position when keyboard appears on iOS

### ISSUE THREAD

**Issue by jalvarezz13** [nextui-org/nextui#2837]
### NextUI Version

2.3.5

### Describe the bug

After updating from version 2.2.X to 2.3.X, there is an issue observed on iOS devices where the modal dialog does not adjust its position when the keyboard appears on the screen. As a result, the modal remains in its original position, obscuring the view of the input fields and preventing users from seeing what they are typing. This behavior affects the usability of the application, especially in forms and dialogs requiring user input.

### Steps to Reproduce the Bug or Issue

1. Create a webpage that includes a modal dialog.
2. Within the modal, include a form with several input fields.
3. Open the webpage on an iOS device using Safari.
4. Tap on the input field within the modal to bring up the iOS keyboard.

Notice that when the keyboard appears, the modal remains in its fixed position at the bottom of the screen. The keyboard covers the modal, obscuring the input field and preventing the user from seeing what is being typed.

### Expected behavior

The modal should adjust its position when the keyboard appears, moving up to ensure that the input field is visible and the user can see what they are typing.

### Operating System Version

iOS 17.4.1

### Browser

Safari

**Comment by wingkwong** [comment]
@jalvarezz13 can you attach a screenshot and some code?

**Comment by jalvarezz13** [comment]
The code could be this modal https://nextui.org/docs/components/modal#with-form without "top-center" placement.
I attach a simple demo here:

https://github.com/nextui-org/nextui/assets/64201633/49faa35e-df48-4239-8329-9544d008db1d

**Comment by daniel-esserweb** [comment]
Im facing the same issue

**Comment by mashnoon33** [comment]
Can also reproduce

**Comment by vtsybulin** [comment]
Looks like it's somehow related to the internal implementation of the scroll-blocking behavior within Modal `shouldBlockScroll`. Unfortunately, I'm short on time to dig into it more, what I ended up doing was disabling `shouldBlockScroll` completely, and relying on custom implementation, using [body-scroll-lock](https://www.npmjs.com/package/body-scroll-lock), which is fine for my case, since it's already used in the project. Tho I had to rely on `useEffect` to make it work, which is unfortunate and I had to mimic `<ModalBody />` classnames explicitly as I needed to get a scrollable modal content ref.

```typescript
const ModalTemplate = <ContentWrapperProps extends TContentWrapperProps, ModalFooterProps extends TModalFooterProps>({ title, children, ModalContentWrapper = Fragment, modalContentWrapperProps, ModalFooter, getModalFooterProps, isLoading, ...modalProps }: IModalTemplateProps<ContentWrapperProps, ModalFooterProps>): ReactElement => {
  const scrollableTargetRef = useRef<HTMLDivElement>(null);

  useEffect(
    (): void => {
      if (modalProps.isOpen && scrollableTargetRef.current) {
        disableBodyScroll(scrollableTargetRef.current);

        return;
      }

      clearAllBodyScrollLocks();
    },
    [modalProps.isOpen],
  );

  return (
    <Modal
      size="2xl"
      backdrop="blur"
      scrollBehavior="inside"
      hideCloseButton
      shouldBlockScroll={false}
      classNames={{
        backdrop: 'top-0 left-0',
      }}
      {...modalProps}
    >
      <ModalContent>
        {(close: () => void): ReactElement => (
          <ModalContentWrapper
            {...modalContentWrapperProps as ContentWrapperProps}
            className="[display:contents]"
          >

            <ModalHeader className="flex flex-col gap-1">
              <div className="flex w-full items-center justify-between gap-2">
                {title}

                <Button
                  variant="light"
                  isIconOnly
                  onPress={close}
                >
                  <CloseIcon />
                </Button>
              </div>
            </ModalHeader>

            /** Explicit <ModalBody /> implementation. class names list was taken from nextui.Modal.ModalBody as is **/
            <div
              className="flex flex-1 flex-col gap-3 overflow-y-auto px-6 py-2"
              ref={scrollableTargetRef}
            >
              {children}
            </div>

            {ModalFooter && (
              <ModalFooterBase>
                <ModalFooter
                  {...(typeof getModalFooterProps === 'function' && getModalFooterProps({
                    close,
                    isLoading,
                  })) as ModalFooterProps}
                />
              </ModalFooterBase>
            )}
          </ModalContentWrapper>
        )}
      </ModalContent>
    </Modal>
  );
};

export default ModalTemplate;


```

**Comment by jalvarezz13** [comment]
Any update? Thanks!

**Comment by jalvarezz13** [comment]
@VithuJey The error persists in version 2.4.0

**Comment by 0xAskar** [comment]
i'm having the same problem, does anyone have an idea on how to fix it?

**Comment by theonlyway** [comment]
> i'm having the same problem, does anyone have an idea on how to fix it?

Just use the version of the modal from further up where it works. Install just the individual modal package version above and import the modal from that package instead of the central package

**Comment by kamami** [comment]
Same issue with version 2.0.36 of modal

**Comment by dharmveer97** [comment]
@kamami If you want to fix this issue, you can install the individual modal box using version 2.0.0. It is a little bit buggy too, but the keyboard issue does not occur in this version. However, in other versions, the keyboard hides the inputs in all versions.

https://www.npmjs.com/package/@nextui-org/modal

**Comment by 0xAskar** [comment]
@theonlyway thanks! I also just kept the latest version and on mobile screens i adjusted the absolute position as others suggested here.

**Comment by erodriguezvesti** [comment]
same issue here, installing @nextui-org/modal@2.0.0 works for now

**Comment by LeakedDave** [comment]
Oof. 2.0.0 fixes this, but scrolling is broken even with scrollBehavior outside if the modal is too big... ruh roh

**Comment by dharmveer97** [comment]
## `TEMP SOLUTION`


```
'use client';

import React, { useEffect, useRef } from 'react';
import {
  Button,
  useDisclosure,
  Modal,
  ModalContent,
  ModalBody,
} from '@nextui-org/react';

import CreateLotForm from '../../components/forms/CreateLotForm';

const AddLotModal = () => {
  const { isOpen, onOpen, onOpenChange, onClose } = useDisclosure();
  const modalBodyRef = useRef(null);

  const handleOpen = () => {
    onOpen();
  };

  useEffect(() => {
    if (modalBodyRef.current) {
      const inputs = modalBodyRef.current.querySelectorAll(
        'input, textarea, select',
      );
      inputs.forEach((input) => {
        input.addEventListener('focus', () => {
          setTimeout(() => {
            input.scrollIntoView({ behavior: 'smooth', block: 'center' });
          }, 300);
        });
      });
    }
  }, [isOpen]);

  return (
    <div>
      <div className="flex flex-wrap gap-3">
        <Button
          variant="flat"
          color="warning"
          onClick={handleOpen}
          className="capitalize"
        >
          Add New
        </Button>
      </div>

      <Modal
        isOpen={isOpen}
        onOpenChange={onOpenChange}
        isDismissable={false}
        scrollBehavior="outside"
        size="5xl"
      >
        <ModalContent>
          {() => (
            <>
              {/* empty div for more space or height */}
              <div className="pt-12 block sm:hidden" />
              <ModalBody ref={modalBodyRef}>
                <CreateLotForm
                  enableReinitialize
                  close={onClose}
                  onSubmit={() => {}}
                />
                {/* empty div for more space or height */}
                <div className="pb-44 block sm:hidden" />
              </ModalBody>
            </>
          )}
        </ModalContent>
      </Modal>
    </div>
  );
};

export default AddLotModal;
```

**Comment by HastaCs** [comment]
any update? :(

**Comment by ArielBenichou** [comment]
+1

**Comment by jalvarezz13** [comment]
It's been almost 4 months since the bug appeared, and no one from the NextUI organization seems to have addressed it in this thread. In my case, I have decided to migrate to Shadcn.

For those who cannot do the same, I recommend installing the NextUI modal component in isolation from the rest. Also, remember to install the following dependencies to avoid potential issues:

- @nextui-org/modal: ^2.0.29
- @nextui-org/system: ^2.1.0
- @nextui-org/theme: ^2.0.0

You can install them with:
`yarn add @nextui-org/modal@^2.0.29 @nextui-org/system@^2.1.0 @nextui-org/theme@^2.0.0`

**Comment by cristyz** [comment]
I found a solution with css, tested it and it seems to work reasonably, hope it helps too.

`BaseModal.tsx`
```
import { Modal } from "@nextui-org/modal";

type BaseModalProps = {} & React.ComponentProps<typeof Modal>;
export function BaseModal({ children, backdrop = "opaque", ...props }: BaseModalProps) {
  return (
    <Modal
      backdrop={backdrop}
      classNames={{
        wrapper: "pb-[65%] landscape:pb-[50vh] landscape:xl:pb-0",
      }}
      isDismissable={false}
      placement="top"
      scrollBehavior="outside"
      {...props}
    >
      {children}
    </Modal>
  );
}
```

`tailwind.config.ts`
Add to your theme extension

```
portrait: {
  raw: "(orientation: portrait)",
},
landscape: {
  raw: "(orientation: landscape)",
},
```

Usage example
```
<BaseModal isOpen={isOpen} onOpenChange={onOpenChange}>
  <ModalContent>
    {(onClose) => (
      <>
        <ModalHeader className="flex flex-col gap-1">Title</ModalHeader>
        <ModalBody>
          <span>Your modal body</span>
        </ModalBody>
        <ModalFooter>
          <Button color="danger" variant="light" onPress={onClose}>
            Close
          </Button>
          <Button color="primary" type="submit">
            Save
          </Button>
        </ModalFooter>
      </>
    )}
  </ModalContent>
</BaseModal>
```

**Comment by ETOPS7** [comment]
I had to use `“top-center”` placement as a temporary solution since the modal does not behave consistently on mobile screens. We are really looking forward to fixing this issue.

**Comment by jalvarezz13** [comment]
@wingkwong I see you have self-assigned this issue, are you working on a specific branch you can share? Thanks

**Comment by jalvarezz13** [comment]
@cristyz Thank you for sharing the temporal solution, it's not working for my specific use case but it's a good solution for other cases :)

**Comment by Vorashil** [comment]
I have managed to avoid this by using an external library, which is not idea, but will do for now.

https://www.npmjs.com/package/use-detect-keyboard-open

```
    const isKeyboardOpen = useDetectKeyboardOpen();

    const placement = isKeyboardOpen ? "top" : "auto"

   return (
        <MyCustomModal
                        size={size}
                        isOpen={isOpen}
                        placement={placement}
                        backdrop={backdrop}
                        onClose={onClose}
                        isDismissible={isDismissible}/>
)
```

**Comment by hoanmq** [comment]
Any update or release plz?

**Comment by Jackmekiss** [comment]
Any updates?

**Comment by wingkwong** [comment]
I've made the PR, which is currently under review.

**Comment by jalvarezz13** [comment]
Thank you so much @wingkwong... I can't wait to see it at the release!

**Comment by wingkwong** [comment]
For those who need the fix before the next bug fix release (v.2.4.7), you may use the canary version for the time being  (i.e. change the version to `0.0.0-canary-20240901014525` and reinstall).

**Comment by daniel-esserweb** [comment]
> For those who need the fix before the next bug fix release (v.2.4.7), you may use the canary version for the time being (i.e. change the version to `0.0.0-canary-20240901014525` and reinstall).

This version crash the autocomplete. Any spected date to this new full release?

**Comment by wingkwong** [comment]
@daniel-esserweb I recently also noticed that. I may rollback autocomplete change first.

**Comment by wingkwong** [comment]
@daniel-esserweb just rollbacked the change and released another canary version. The full release should be available in weekend (tentatively).

**Comment by HastaCs** [comment]
fixed or news?.. :)

**Comment by wingkwong** [comment]
@HastaCs already included in the latest version.

**Comment by adnan-smlatic** [comment]
I am not sure why this is closed, same thing happening on @heroui/react": "2.7.6"

To reproduce just put an autocomplete in a modal on mobile. Totally breaks everything when keyboard is opened

**Comment by sooperjos** [comment]
Modals are unusable in ios/safari now.

**Comment by n-lavrenko** [comment]
Reopen and fix please.
I have to reimplement own autocomplete because of this bug

**Comment by adnan-smlatic** [comment]
@jim-spr @n-lavrenko If you're having scroll issues what fixed it for me on Safari was adding

```ts
<Drawer
classNames={{
				wrapper: "!h-[100dvh]"
	}}```

This example is for the drawer, but similar principle goes for modals etc. The problem is that when the keyboard gets opened it's not recalculating the height properly.

**Comment by jalvarezz13** [comment]
The issue has appeared again on a new version...
A new issue has been created here: #3937
