### ISSUE TITLE
[BUG] - INPUT WHEN  ISVALID

### ISSUE THREAD

**Issue by Fiqry919** [nextui-org/nextui#2844]
### NextUI Version

2.3.5

### Describe the bug

im trying with submit form, when input set isvalid false then cant resubmit form

### Steps to Reproduce the Bug or Issue

see error

### Expected behavior

as a user

### Operating System Version

windows

### Browser

Chrome

**Comment by wingkwong** [comment]
@Fiqry919 I'm not sure what the issue is here. When it's invalid, you can't submit the form. Can you show some code or even a video for demonstration?

**Comment by Fiqry919** [comment]
sure, this a video
https://github.com/nextui-org/nextui/assets/116353477/ebff2d9b-b20c-4c64-b9bc-9017de52c5b5

**Comment by Fiqry919** [comment]
this when use other version
https://github.com/nextui-org/nextui/assets/116353477/627d154e-63c6-4048-b5f3-48023b48f159

**Comment by Moriarty47** [comment]
I'm run into this issue too.

**Comment by Fiqry919** [comment]
thanks

**Comment by wingkwong** [comment]
I think the reason is your validation logic resides after submit. Once the input has an invalid state, submit is blocked. In this case, you can change the state by using `validate`.

**Comment by Moriarty47** [comment]
Rewrite it in this way, it worked. Thanks for your help , @wingkwong .

```tsx
const schema = {
  username: z
    .string()
    .min(3, 'Please input email')
    .max(30, 'Please input correct email')
    .email('Please input correct email'),
  password: z.string().min(6, 'Please input password'),
};

const validator = (key: keyof typeof schema) => (value: string) => {
  const res = schema[key].safeParse(value);
  console.log(res);
  return !res.success && res.error.issues[0].message || null;
};
const onSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.stopPropagation();
    e.preventDefault();
    const formData = new FormData(e.target as HTMLFormElement);
    const value = {
      username: formData.get('username'),
      password: formData.get('password'),
    };
    console.log(value);
    return value;
  };

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <form onSubmit={onSubmit} className="grid gap-4 grid-cols-1 grid-rows-2">
        <Input
          name="username"
          autoComplete="email"
          required
          autoFocus
          label="Email"
          placeholder="Input your email"
          variant="bordered"
          defaultValue=""
          validate={validator('username')}
        />
        <Input
          name="password"
          label="Password"
          placeholder="Input your password"
          type="password"
          variant="bordered"
          defaultValue=""
          validate={validator('password')}
        />
        <div className="inline-flex items-start justify-between self-start gap-4 mb-4">
          <Button color="primary" type="submit">
            Sign in
          </Button>
        </div>
      </form>
    </main>
  );
```

**Comment by Fiqry919** [comment]
> I think the reason is your validation logic resides after submit. Once the input has an invalid state, submit is blocked. In this case, you can change the state by using `validate`.

I don't understand why, but if there is a logic problem, it shouldn't work in other versions.
im trying with props validate is still same.
does this not work just for me

**Comment by wingkwong** [comment]
> Here is [a minimal env](https://stackblitz.com/edit/stackblitz-starters-gbk6t5?file=package.json)

@Moriarty47 can you share your previous version of this stackblitz link? the one to reproduce the issue. The above one got overrode.

**Comment by Moriarty47** [comment]
Ok. I think it should look something like [this](https://stackblitz.com/edit/stackblitz-starters-gbk6t5?file=app%2F%40issue%2Fpage.tsx),

**Comment by parirox** [comment]
> I'm run into this issue too.
> 
> ![1](https://private-user-images.githubusercontent.com/21117495/325299316-2fca5f8f-41d0-461a-b27f-ff7c5a37c5a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzYyOTUsIm5iZiI6MTczNTMzNTk5NSwicGF0aCI6Ii8yMTExNzQ5NS8zMjUyOTkzMTYtMmZjYTVmOGYtNDFkMC00NjFhLWIyN2YtZmY3YzVhMzdjNWEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIxNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkM2Y5MmNjMzI4ODFjZjExMjYxMTRkNmU0NGJmYjNkNjA1Y2Y1YjM0NmJjNzkyMzQ3MzBiNTAxMDZlYzkxOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ms3gYJHUFijaCm5nkxd0eAYgcizx3-MF_lbGlGuYgS8) [ ![1](https://private-user-images.githubusercontent.com/21117495/325299316-2fca5f8f-41d0-461a-b27f-ff7c5a37c5a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzYyOTUsIm5iZiI6MTczNTMzNTk5NSwicGF0aCI6Ii8yMTExNzQ5NS8zMjUyOTkzMTYtMmZjYTVmOGYtNDFkMC00NjFhLWIyN2YtZmY3YzVhMzdjNWEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIxNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkM2Y5MmNjMzI4ODFjZjExMjYxMTRkNmU0NGJmYjNkNjA1Y2Y1YjM0NmJjNzkyMzQ3MzBiNTAxMDZlYzkxOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ms3gYJHUFijaCm5nkxd0eAYgcizx3-MF_lbGlGuYgS8) ](https://private-user-images.githubusercontent.com/21117495/325299316-2fca5f8f-41d0-461a-b27f-ff7c5a37c5a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzYyOTUsIm5iZiI6MTczNTMzNTk5NSwicGF0aCI6Ii8yMTExNzQ5NS8zMjUyOTkzMTYtMmZjYTVmOGYtNDFkMC00NjFhLWIyN2YtZmY3YzVhMzdjNWEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIxNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkM2Y5MmNjMzI4ODFjZjExMjYxMTRkNmU0NGJmYjNkNjA1Y2Y1YjM0NmJjNzkyMzQ3MzBiNTAxMDZlYzkxOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ms3gYJHUFijaCm5nkxd0eAYgcizx3-MF_lbGlGuYgS8) [ ](https://private-user-images.githubusercontent.com/21117495/325299316-2fca5f8f-41d0-461a-b27f-ff7c5a37c5a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzYyOTUsIm5iZiI6MTczNTMzNTk5NSwicGF0aCI6Ii8yMTExNzQ5NS8zMjUyOTkzMTYtMmZjYTVmOGYtNDFkMC00NjFhLWIyN2YtZmY3YzVhMzdjNWEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIxNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkM2Y5MmNjMzI4ODFjZjExMjYxMTRkNmU0NGJmYjNkNjA1Y2Y1YjM0NmJjNzkyMzQ3MzBiNTAxMDZlYzkxOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ms3gYJHUFijaCm5nkxd0eAYgcizx3-MF_lbGlGuYgS8)
> 
> ```json
> {
> "dependencies": {
>     // ....
>     "@nextui-org/react": "2.2.10",
>     "framer-motion": "11.0.24",
>     "next": "13.5.1",
>     "postcss": "8.4.30",
>     "react": "18.2.0",
>     "react-dom": "18.2.0"
>   }
> }
> ```
> 
> ![2](https://private-user-images.githubusercontent.com/21117495/325301593-73ebbec4-68b9-46b6-8fc8-cb8ac565aa16.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzYyOTUsIm5iZiI6MTczNTMzNTk5NSwicGF0aCI6Ii8yMTExNzQ5NS8zMjUzMDE1OTMtNzNlYmJlYzQtNjhiOS00NmI2LThmYzgtY2I4YWM1NjVhYTE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIxNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNTZhYjFlYTJjNDIwZjQ4ZmE0Mzk3MDQ2ZDc1OTNkNDIzNzgwMTRlMzMyMjQ2ZGNlYTM5YWM3MzM5ZmIzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9JuG-A-08A6KUEQOVx269RVEfp4V0_OjSIYEdeBfhOQ) [ ![2](https://private-user-images.githubusercontent.com/21117495/325301593-73ebbec4-68b9-46b6-8fc8-cb8ac565aa16.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzYyOTUsIm5iZiI6MTczNTMzNTk5NSwicGF0aCI6Ii8yMTExNzQ5NS8zMjUzMDE1OTMtNzNlYmJlYzQtNjhiOS00NmI2LThmYzgtY2I4YWM1NjVhYTE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIxNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNTZhYjFlYTJjNDIwZjQ4ZmE0Mzk3MDQ2ZDc1OTNkNDIzNzgwMTRlMzMyMjQ2ZGNlYTM5YWM3MzM5ZmIzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9JuG-A-08A6KUEQOVx269RVEfp4V0_OjSIYEdeBfhOQ) ](https://private-user-images.githubusercontent.com/21117495/325301593-73ebbec4-68b9-46b6-8fc8-cb8ac565aa16.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzYyOTUsIm5iZiI6MTczNTMzNTk5NSwicGF0aCI6Ii8yMTExNzQ5NS8zMjUzMDE1OTMtNzNlYmJlYzQtNjhiOS00NmI2LThmYzgtY2I4YWM1NjVhYTE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIxNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNTZhYjFlYTJjNDIwZjQ4ZmE0Mzk3MDQ2ZDc1OTNkNDIzNzgwMTRlMzMyMjQ2ZGNlYTM5YWM3MzM5ZmIzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9JuG-A-08A6KUEQOVx269RVEfp4V0_OjSIYEdeBfhOQ) [ ](https://private-user-images.githubusercontent.com/21117495/325301593-73ebbec4-68b9-46b6-8fc8-cb8ac565aa16.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzYyOTUsIm5iZiI6MTczNTMzNTk5NSwicGF0aCI6Ii8yMTExNzQ5NS8zMjUzMDE1OTMtNzNlYmJlYzQtNjhiOS00NmI2LThmYzgtY2I4YWM1NjVhYTE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIxNDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNTZhYjFlYTJjNDIwZjQ4ZmE0Mzk3MDQ2ZDc1OTNkNDIzNzgwMTRlMzMyMjQ2ZGNlYTM5YWM3MzM5ZmIzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9JuG-A-08A6KUEQOVx269RVEfp4V0_OjSIYEdeBfhOQ)
> 
> ```json
> {
> "dependencies": {
>     // ....
>     "@nextui-org/react": "2.3.5",
>     "framer-motion": "11.0.24",
>     "next": "13.5.1",
>     "postcss": "8.4.30",
>     "react": "18.2.0",
>     "react-dom": "18.2.0"
>   }
> }
> ```
> 
> Here is [a minimal env](https://stackblitz.com/edit/stackblitz-starters-gbk6t5?file=package.json)

I encountered this problem, and fixed it manually by adding another helper state:

```typescript
'use client'
import React, {useEffect} from 'react';
import {Input} from "@nextui-org/input";

type AppInputProps = {
    label: string,
    name: string,
    errors?: string[],
    defaultValue?: string | undefined
};

const AppInput: React.FC<AppInputProps> = ({label, name, errors, defaultValue}) => {
    // Workaround for form submission
    const [value, setValue] = React.useState<string | undefined>();
    const [changed, setChanged] = React.useState<boolean>(false);

    useEffect(() => {
        setValue(defaultValue);
        setChanged(false)
    }, [defaultValue])


    // Workaround for form submission
    function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
        setValue(event.target.value);
        setChanged(true)
    }

    return (
        <div className="flex flex-col gap-3">
            <Input
                isClearable
                errorMessage={() => (
                    <ul>
                        {
                            (errors && errors.length > 0) && errors.map((error, i) => (
                                <li key={i} className="animate-appearance-in text-red-700 ps-3">{error}</li>
                            ))
                        }
                    </ul>
                )}
                isInvalid={errors && errors.length > 0 && !changed}
                label={label}
                labelPlacement="inside"
                name={name}
                type="text"
                value={value}
                onChange={handleChange} // Workaround for form submission
            />
        </div>
    );
};


export default AppInput;
```
