### ISSUE TITLE
[BUG] - DatePicker Console Error

### ISSUE THREAD

**Issue by KaiqueAmaralCS** [nextui-org/nextui#2846]
### NextUI Version

2.3.5

### Describe the bug

I'm getting a warning that the props are named incorrectly. Since everything is ok, apparently it is an error in the component core

React does not recognize the `showMonthAndYearPickers` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `showmonthandyearpickers` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

React does not recognize the `isRequired` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isrequired` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### Steps to Reproduce the Bug or Issue

Justa pass one of this props isRequired, isDisabled, isReadOnly, showMonthAndYearPickers

### Expected behavior

No console warnings

### Operating System Version

Windows 11

### Browser

Edge

**Comment by jrgarciadev** [comment]
Duplicated #2823
