### ISSUE TITLE
[Feature Request] Datepicker placeholder format

### ISSUE THREAD

**Issue by howailok1120** [nextui-org/nextui#2852]
### Is your feature request related to a problem? Please describe.

The datepicker placeholder is default in mm/dd/yyyy
how to force the client side to adopt dd/mm/yyyy?

### Describe the solution you'd like

may be add an API to accept formating like this:

format="dd/MM/yyyy"?

### Describe alternatives you've considered

I am using <Input type="date"> at the moment as alternatives.

**Comment by wingkwong** [comment]
Duplicated: https://github.com/nextui-org/nextui/issues/2792
