### ISSUE TITLE
[BUG] - label overflow in select

### ISSUE THREAD

**Issue by vivek-quantech** [nextui-org/nextui#2856]
### NextUI Version

2.3.6

### Describe the bug

I have used select. The label of the select is larger then width of select. when I choose one option then the label overflow from the select UI.
![Screenshot 2024-04-24 130702](https://github.com/nextui-org/nextui/assets/156406847/21612203-366e-4aa5-b643-b3819cf26cef)

### Steps to Reproduce the Bug or Issue

1. Use @nextui-org/select.
2. Give 20% width and make sure the label is larger than the width of select.
3. Select the option which is larger than the width of switch
![Screenshot 2024-04-24 130940](https://github.com/nextui-org/nextui/assets/156406847/b27934c7-60bd-4d0c-b7fe-965c50f3430a)

### Expected behavior

As a user , the label should be inside the select, It should not overflow outside the select
![Screenshot 2024-04-24 130702](https://github.com/nextui-org/nextui/assets/156406847/450e2e5f-f43f-4613-aa88-8ac7feb67502)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
1. can you try on the latest version? we've changed quite a lot.
2. if the latest version doesn't solve the problem. Please share your code or even a stackblitz link for us to have the same setup to reproduce the issue.

**Comment by vivek-quantech** [comment]
Sure , will try and let you know.
Thank You!!

**Comment by vivek-quantech** [comment]
I've created a new Next.js app and integrated the latest version of the NextUI library.
I'm still experiencing an issue where the content of the select options overflows after selecting one.

[Stackblitz link](https://stackblitz.com/edit/stackblitz-starters-hdecxq?file=app%2Fpage.tsx)

**Comment by wingkwong** [comment]
This is what I see. I think you missed some setup as I see the styles are quite different in stackblitz link.

![image](https://github.com/nextui-org/nextui/assets/35857179/497e724e-76a0-480d-bede-2773af25f190)

**Comment by kuri-sun** [comment]
@vivek-quantech 
Please confirm that this issue was solved at the current version through this video. Thank you 🙏 
@wingkwong 
I will request that we can close this issue

https://github.com/nextui-org/nextui/assets/62743644/b353b7b3-316c-4f53-81c0-1f399e732eca
