### ISSUE TITLE
[BUG] - DropdownItem not getting focused properly and 'Enter' | 'Space' not selecting the item.

### ISSUE THREAD

**Issue by matheusboeira** [nextui-org/nextui#2863]
### NextUI Version

2.3.5

### Describe the bug

When you focus on the DropdownTrigger, the next step is to press "space" to open the Dropdown. When you press it, you should focus on the first item in the list. Well, that doesn't happen. Furthermore, when you focus on the DropdownItem (after pressing tab until it gets focused), and then press Enter or Space, it closes without selecting the item.

### Steps to Reproduce the Bug or Issue

1. Go to a page that has Dropdown and other components
2. Use Tab to localize the Dropdown and press Space
3. The Dropdown first item doesn't get focused
4. Tab until you focus Dropdown first item
5. Use keyboard arrow up|down to select an item and press space
6. Nothing gets selected

### Expected behavior

As a user, I would like that when pressing the keyboard "space" while the Dropdown is focused, it focuses on the Dropdown items. Furthermore, pressing the keyboard "Enter" or "Space" should select the item.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/76896958/a510acc4-b40b-4145-bcd8-6918220e0dc0

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Please share the code also.

**Comment by matheusboeira** [comment]
@wingkwong it's reproducible here: [code](https://stackblitz.com/edit/vitejs-vite-hlgmdv?file=src%2FApp.tsx). It doesn't work only in keyboard. Try to select an item using keyboard.

**Comment by wingkwong** [comment]
@matheusboeira you need to set `onKeyDown={() => setLanguage(lang.code)}`. OnPress only captures press event only.

**Comment by matheusboeira** [comment]
@wingkwong, hmm. But I want to change the language after I press the "space" in my keyboard, not on arrow keys. And what about the tabIndex? I want to focus Dropdown list after a "Tab" when DropdownTrigger is focused.

<img width="751" alt="image" src="https://github.com/nextui-org/nextui/assets/76896958/71128f09-b4ae-4e87-971d-ee440692cae2">

**Comment by wingkwong** [comment]
@matheusboeira oh ok. I misunderstood the problem. 

> As a user, I would like that when pressing the keyboard "space" while the Dropdown is focused, it focuses on the Dropdown items. 

This seems missing indeed.

> Furthermore, pressing the keyboard "Enter" or "Space" should select the item.

To set the language, here we still need `onKeyDown={() => setLanguage(lang.code)}`

**Comment by matheusboeira** [comment]
@wingkwong exactly the same code works as expected in version 2.2.10. Pressing "Space" opens Dropdown and focus the first item. Items can be "selected" (change the language) pressing space. 

<img width="1307" alt="image" src="https://github.com/nextui-org/nextui/assets/76896958/464f6b99-267f-449f-a32b-1e0fdffa6d4b">

**Comment by wingkwong** [comment]
@matheusboeira can you confirm the following behaviours in 2.2.10?

- use tab to localize the dropdown trigger
- press space, dropdown is open and the first item is focused
- press space again, first item is selected and language is changed (i.e. setLanguage)

**Comment by matheusboeira** [comment]
@wingkwong, yes! It should be like that!

**Comment by wingkwong** [comment]
@matheusboeira Thanks a lot. much cleaner. will take a look.
