### ISSUE TITLE
[BUG] - RangeCalendar showMonthAndYearPickers prop is not working

### ISSUE THREAD

**Issue by daniel-esserweb** [nextui-org/nextui#2874]
### NextUI Version

2.3.6

### Describe the bug

In the official documentation it mentions that there is the prop showMonthAndYearPickers, but this one is not working in the component, it seems to work in Calendar component but not in RangeCalendar

### Steps to Reproduce the Bug or Issue

1. Create a RangeCalendar component
2. Enable prop showMonthAndYearPickers
3.  Check that it does not exist inside the component

### Expected behavior

It should work as the same way it works in the Calendar component

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
as discussed with Junior, this prop shouldn't be in range-based components (i.e. range calendar, date range picker).
