### ISSUE TITLE
Modal with animated got flashing abnormally when visible

### ISSUE THREAD

**Issue by TianenPang** [nextui-org/nextui#288]
**Describe the bug**
When Modal animated is true (by default), modal will blink when it appears.

**Steps to reproduce**
CodeSandbox: [https://codesandbox.io/s/next-ui-modal-1r2w18](https://codesandbox.io/s/next-ui-modal-1r2w18?file=/pages/index.js)

It doesn't always flashing when popup, but usually appears in the first few popup animations after the page has been loaded.

If not see the flashing, please try after refreshing.

**Expected behaviour**
popup with smooth animation.

**Environment / Context**
- Desktop
- Operating System: Windows 10 Pro
- Browser and version Chrome 98.0.4758.82 (Official Build) (64-bit)
- Device: Dell Inspiron 7560

**Comment by Deihim007** [comment]
I'm experiencing the same issue.

**Comment by pourya-ataee** [comment]
I'm experiencing the same issue.
I'm showing 2 different files (audio and video) in the modal simultaneously and on file timeline change this issue occurs.
Note that I'm using VideoJS
