### ISSUE TITLE
[BUG] - Select component lags and does not work when used with long list of options.

### ISSUE THREAD

**Issue by utkarsh-source** [nextui-org/nextui#2885]
### NextUI Version

ex. 2.3.6

## My Code

<img width="512" alt="Screenshot_193" src="https://github.com/nextui-org/nextui/assets/54720265/cc3a860f-6adb-4ee0-8ab6-4595ec5762be">

Here countryOptions is a long list causing the select component to lag and does not work at all.

### Screenshots or Videos

# I also get these warning on the console whenever i interact with that component

<img width="663" alt="Screenshot_192" src="https://github.com/nextui-org/nextui/assets/54720265/f6495ecf-eae9-4d7b-8baf-91059bb1e1cb">

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
please share a stackblitz link
