### ISSUE TITLE
The copy button of the Auto-Layout Columns section live editor does not copy.

### ISSUE THREAD

**Issue by imjorgemor** [nextui-org/nextui#289]
**Describe the bug**
The copy button of the Auto-Layout Columns section live editor does not copy.

**Steps to reproduce**
1. Go to 'https://nextui.org/docs/layout/container'
2. Click on ''
3. Scroll down to 'to section Auto-Layout Columns'
4. See error: onClick copy button does not copy the text of the demo.

**Expected behaviour**
The copy button shall copy the text inside de Live demo

**Screenshots**

**Environment / Context**
- Desktop or Mobile? Desktop
- Operating System: [e.g. iOS] macOs Monterrey
- Browser and version [e.g. chrome 22] Chrome 98
- Device: [e.g. iPhone6] Macbook 

**Additional info**

**Comment by jrgarciadev** [comment]
Hey @imjorgemor thank you for reporting it 🙌🏻
