### ISSUE TITLE
[BUG] - Table isStriped not working

### ISSUE THREAD

**Issue by alirezatayebinejad** [nextui-org/nextui#2896]
### NextUI Version

2.3.5

### Describe the bug

when I add isStriped it works but when I also add removeWrapper={true} the isStriped is not working and I do not see the striped styles

### Steps to Reproduce the Bug or Issue

` <Table isStriped removeWrapper={true}>
              <TableHeader>
                <TableColumn>NAME</TableColumn>
                <TableColumn>ROLE</TableColumn>
                <TableColumn>STATUS</TableColumn>
              </TableHeader>
              <TableBody>
                <TableRow key="1">
                  <TableCell>Tony Reichert</TableCell>
                  <TableCell>CEO</TableCell>
                  <TableCell>Active</TableCell>
                </TableRow>
                <TableRow key="2">
                  <TableCell>Zoey Lang</TableCell>
                  <TableCell>Technical Lead</TableCell>
                  <TableCell>Paused</TableCell>
                </TableRow>
                <TableRow key="3">
                  <TableCell>Jane Fisher</TableCell>
                  <TableCell>Senior Developer</TableCell>
                  <TableCell>Active</TableCell>
                </TableRow>
                <TableRow key="4">
                  <TableCell>William Howard</TableCell>
                  <TableCell>Community Manager</TableCell>
                  <TableCell>Vacation</TableCell>
                </TableRow>
              </TableBody>
            </Table>`

### Expected behavior

isStriped work with removeWrapper

### Operating System Version

windows 10

### Browser

Chrome

**Comment by wingkwong** [comment]
I don't see a problem here. Maybe you got some custom styles overriding? 

without `removeWrapper`

![image](https://github.com/nextui-org/nextui/assets/35857179/66ddfb1e-4920-4e3f-b048-c519e6f437ea)

with `removeWrapper`

![image](https://github.com/nextui-org/nextui/assets/35857179/05bca20f-d2ba-4fac-a2ab-8a72313fc210)

**Comment by alirezatayebinejad** [comment]
no I do not have custom style overwriting. the problem still exists for me but I fixed that issue by using this for now:
```
classnames={{
tr: "even:bg-boxBg200",
}}
```

**Comment by wingkwong** [comment]
That's weird. I just copied the same code. Probably something else affecting it. Closing this issue since we couldn't reproduce it and you've fixed it in your own way.

**Comment by alexnguyennz** [comment]
Hi I've encountered this issue with 2.4.6 - I can reproduce it with the default [isStriped demo](https://nextui.org/docs/components/table#striped-rows) and adding `removeWrapper`:

https://codesandbox.io/p/devbox/quiet-mountain-22nvn9

**Comment by scotticus** [comment]
I'm also seeing this issue. `isStriped` doesn't work with `removeWrapper`.

**Comment by wingkwong** [comment]
@scotticus are you using latest version? If so, please provide a minimal reproducible sandbox.
