### ISSUE TITLE
NextUI is not working with React webpack app

### ISSUE THREAD

**Issue by rajuldixit** [nextui-org/nextui#2897]
### NextUI Version

 "@nextui-org/react": "^2.3.6",     "framer-motion": "^11.1.7",

### Describe the bug

Hi, I am trying to install nextui in my react webpack application, after following all the steps , its not working 
but it is working fine in my plain react app

### Steps to Reproduce the Bug or Issue

npm install
npm start

### Expected behavior

It should show success green color button but no styles are applying

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/17043105/f8250e61-c639-4963-b9e6-2b3c58e35500)
![image](https://github.com/nextui-org/nextui/assets/17043105/fd85aced-db10-4ee1-9bab-412e31d8327f)
![image](https://github.com/nextui-org/nextui/assets/17043105/a1d9dfac-40d6-4303-a2af-750d0a150f03)
![image](https://github.com/nextui-org/nextui/assets/17043105/b46607b3-fa54-4e10-a606-3decde2b4936)
![image](https://github.com/nextui-org/nextui/assets/17043105/da00fd6c-d003-4c27-b7e3-b73a11b386e2)
![image](https://github.com/nextui-org/nextui/assets/17043105/60e08cfb-cc24-4815-8b9f-895e69cc711e)
![image](https://github.com/nextui-org/nextui/assets/17043105/5a83f5ff-d8b8-4a96-a990-3f250e2219fc)
![image](https://github.com/nextui-org/nextui/assets/17043105/fef68509-897c-427e-b714-643c854b8d3e)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
please provide a stackblitz link for us to reproduce the issue.

**Comment by rajuldixit** [comment]
sure, I am sharing the git repo where I got stuck, thank you in advance, 

https://github.com/rajuldixit/PropertyRentalApp

**Comment by wingkwong** [comment]
It's more on your configuration on tailwindCSS. I didn't see it's applied to your application.

**Comment by rajuldixit** [comment]
I am not able to fix this, dont know what i did wrong. if you please help. 

Thanks in advance
