### ISSUE TITLE
[BUG] - Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').

### ISSUE THREAD

**Issue by doannamthai** [nextui-org/nextui#2899]
### NextUI Version

2.3.5+

### Describe the bug

Received error when trying to upgrade to 2.3.5 and 2.3.6:

```
./node_modules/@nextui-org/calendar/dist/chunk-KHPJCHY4.mjs
Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').
```

I have the following installed:
```
dependencies : {
"@nextui-org/framer-transitions": "^2.0.15",
"@nextui-org/react": "^2.3.6",
"@nextui-org/system": "^2.0.15",
"@nextui-org/theme": "^2.1.17",
....
}
```

### Steps to Reproduce the Bug or Issue

Run npm install for all packages @nextui-org/framer-transitions, @nextui-org/react, @nextui-org/system, @nextui-org/theme

### Expected behavior

Project should be able to run but yielded the following error:

```
Import trace for requested module:
./node_modules/@nextui-org/calendar/dist/chunk-KHPJCHY4.mjs
./node_modules/@nextui-org/calendar/dist/index.mjs
./node_modules/@nextui-org/react/dist/index.mjs
./app/chatbots/[chatBotId]/chat/page.tsx
 ⨯ ./node_modules/@nextui-org/calendar/dist/chunk-KHPJCHY4.mjs
Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').

```

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
You need to bump `@nextui-org/theme` and `@nextui-org/system` to the latest version. Besides, `framer-transitions` has been renamed to `framer-utils`.
