### ISSUE TITLE
[BUG] - DatePicker styles

### ISSUE THREAD

**Issue by theonlyway** [nextui-org/nextui#2901]
### NextUI Version

2.3.6

### Describe the bug

I'm not sure if this is intended or not but the default styles for the DatePicker have blue selections and hovers matching all of the other NextUI styling but when you set the variant to `bordered` or `underlined` it changes all the default styling to be monochrome. The behavior can be seen on the documentation pages where the default variant has normal styling and the `bordered` and `underlined` variants don't.

### Steps to Reproduce the Bug or Issue

1. Create a DatePicker using the default example
```
          <DatePicker
            label="Birth date"
            className="max-w-[284px]"
            showMonthAndYearPickers
          />
```
and the styles will match the example
2. Add `variant="bordered"` and the Calendar styles will no longer be using the same styles as the default variant

### Expected behavior

I would expect the default styles to still apply to the variants unless they are being overridden either via the slots or by tailwind config.

### Operating System Version

Windows

### Browser

Edge

**Comment by wingkwong** [comment]
supplement a bit with screenshots.

default (`flat`, `faded`): 

![image](https://github.com/nextui-org/nextui/assets/35857179/7625a875-f5bf-43b9-bb84-434bcb83fb72)

monochrome (`bordered`, `underlined`): 

![image](https://github.com/nextui-org/nextui/assets/35857179/033f523f-c92d-4c9c-962e-2349f61af50d)
