### ISSUE TITLE
[BUG] - No matching export for useProviderContext

### ISSUE THREAD

**Issue by notmedia** [nextui-org/nextui#2904]
### NextUI Version

2.3.6

### Describe the bug

On build getting an errors:

```
✘ [ERROR] No matching export in "../../node_modules/@nextui-org/system/dist/index.mjs" for import "useProviderContext"

    ../../node_modules/@nextui-org/calendar/dist/chunk-KHPJCHY4.mjs:13:9:
      13 │ import { useProviderContext } from "@nextui-org/system";
         ╵          ~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "../../node_modules/@nextui-org/system/dist/index.mjs" for import "useProviderContext"

    ../../node_modules/@nextui-org/date-input/dist/chunk-KBJP3WFQ.mjs:7:9:
      7 │ import { useProviderContext } from "@nextui-org/system";
        ╵          ~~~~~~~~~~~~~~~~~~

```

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
I couldn't reproduce the issue. Have you tried removing node_modules and reinstalling again before the build?

<img width="311" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/8cba4854-bc52-42df-91fb-05e90ce86c45">

**Comment by notmedia** [comment]
@wingkwong Hi, yes

I'm trying to find a problem, on @nextui-org/react 2.3.4 version all going fine.
On 2.3.5 I'm getting error only from date-input

**Comment by notmedia** [comment]
@wingkwong some strange things with my monorepo, it installs @nextui-org/system 2.0.15 for all packages

But I see in most components that uses `useProviderContext` `package.json` has peerDep on `"@nextui-org/system": ">=2.0.0"`.
This is probably incorrect because only in `2.1.2` `useProviderContext` appears.

For example - https://github.com/nextui-org/nextui/blob/canary/packages/components/date-input/package.json#L37

**Comment by wingkwong** [comment]
I can see `useProviderContext ` has been exported [here](https://github.com/nextui-org/nextui/blob/main/packages/core/system/src/index.ts). 

- Have you also tried the latest version? 
- Also can you share how you build? I was testing in `canary` branch locally tho.

**Comment by notmedia** [comment]
These package are `date-input` and `calendar`

**Comment by wingkwong** [comment]
so you just cd to `nextui/packages/components/calendar` and run `pnpm build` to see the error?

**Comment by notmedia** [comment]
No, I have monorepo with multiple frontend apps.
One of them had dependency of `framer-transition` that locked `system` package to 2.0.15.

That’s why all other nextui component packages used `system` 2.0.15 also.

I just removed `framer-transition` package form this app deps and run clean install on my monorepo. After that all nextui packages got `system` 1.2.1

So if `system` was locked to 1.2.1 in `date-input` and `calendar` components there would be no issues. Because it would be install correct package version for this components.

**Comment by wingkwong** [comment]
As I remember, `framer-transition` has been renamed to `framer-utils` since 2.3.0. Also `@nextui-org/system` needs to be `>=2.1.0` for the new changes (e.g. calendar, date picker) introduced in 2.3.0. Therefore, I think you just need to bump all the versions to the latest ones. It should resolve the build issue on your application.

**Comment by notmedia** [comment]
Yes, we can close this issue.

Last try - look at packages peer deps for date-input and calendar.
If it’s ok that required system can be 2.0.0 without useProviderContext do nothing. If not - bump minimum required version
