### ISSUE TITLE
[BUG] - Button animation seems to be broken on 2.3.6

### ISSUE THREAD

**Issue by lgariv** [nextui-org/nextui#2905]
### NextUI Version

2.3.6

### Describe the bug

The animation of the button on click doesn't work the same as in 2.3.5

### Steps to Reproduce the Bug or Issue

1. upgrade from 2.3.5 to 2.3.6

### Expected behavior

On 2.3.5 the animation starts from the location of the click in the button.
on 2.3.6 it starts always in the middle on the X axis but seems to be right on the Y axis.

### Screenshots or Videos

2.3.6:
https://github.com/nextui-org/nextui/assets/5081484/05a7eccc-7f7e-4c83-a25a-328736184005

2.3.5 (expected behavior):
https://github.com/nextui-org/nextui/assets/5081484/8c95577c-1587-45a4-893c-c69d58ba4c54

### Operating System Version

macOS Sonoma 14 (arm64)

### Browser

Chrome

**Comment by lgariv** [comment]
Is there any update on  this? still happens on the latest version

**Comment by abhinandan-verma** [comment]
@lgariv  update to latest version.  Issue resolved there

**Comment by wingkwong** [comment]
No longer reproducible in latest version.
