### ISSUE TITLE
[BUG] - Phenomenon where content overlaps when the select box drops down

### ISSUE THREAD

**Issue by forexms78** [nextui-org/nextui#2907]
### NextUI Version

2.1.27

### Describe the bug

<img width="410" alt="스크린샷 2024-04-29 오후 1 30 37" src="https://github.com/nextui-org/nextui/assets/49295076/edc72b29-69be-493f-811d-2084bcf4a2ab">
If you take the dropdown example and use it as is, it will overlap with the content as shown in the following image.

### Steps to Reproduce the Bug or Issue

If you make a dropdown in the select box,

### Expected behavior

What appears as a dropdown should cover the content.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Have you tried the latest version? There're quite lots of changes between 2.1.27 and 2.3.6.

**Comment by forexms78** [comment]
@wingkwong I'll try it and repeat again!

**Comment by forexms78** [comment]
@wingkwong 바로 해결이 되었습니다! 감사합니다
