### ISSUE TITLE
Token autocompletion not working on utils [CodeSandbox]

### ISSUE THREAD

**Issue by hmbrg** [nextui-org/nextui#291]
**Describe the bug**
Autocomplete does not seem to work for utils right now. Inside of `css()` the utils are not even defined as a prop, they are only there if you create a media query with `css({"bp1": {"pt": ...}})`.

**Steps to reproduce**
1. Use the `css()` or `styled()` function
2. Don't get any autocompletion for utils

I've created a CodeSandbox here: https://codesandbox.io/s/distracted-rain-s63rmp?file=/src/App.tsx

**Expected behaviour**
I would expect to get suggestions of the available tokens.

**Comment by hmbrg** [comment]
I was able to fix this by manually installing `@stitches/react`. Is this a known behavior?

**Comment by hmbrg** [comment]
Are there any updates on this? I would love to contribute a fix for this, but I've been looking into this issue and I have no idea what causes it. Do you have any clues on what might be the problem here?

The error even states that there is no utility registered. Installing vanilla stitches in the repo works just fine though.

<img width="1078" alt="Screenshot 2022-03-10 at 03 08 58" src="https://user-images.githubusercontent.com/7304269/157644340-73227200-7ffa-491d-a665-37700c8a9258.png">

**Comment by hmbrg** [comment]
Thanks for your response! Unfortunately, that doesn't fix it, and the codesandbox I provided in the issue doesn't use an affected typescript version. 

I've created a new codesandbox showing the issue next to the working "vanilla" stitches config: https://codesandbox.io/s/nextui-type-issue-5x128y?file=/pages/index.js

Looking at the type of `px` shows that all type information is missing. Also all the breakpoints etc. are missing from the `styled()` options, but it all works with the "vanilla" stitches config.
<img width="677" alt="Screenshot 2022-03-10 at 14 16 14" src="https://user-images.githubusercontent.com/7304269/157669437-04a27a63-4ffd-46bc-98de-30511b97eac7.png">

**Comment by jrgarciadev** [comment]
Hey @hmbrg the commented solution aims to "VSCode", however, I was checking the CodeSandbox and is not a "Typescript" template, I've created a new Codesanbox base on the `Typescript` template and it works well, 

![Screenshot 2022-03-10 at 10 32 07](https://user-images.githubusercontent.com/30373425/157672633-e6f43a8b-59b3-4e88-a6f3-2428063d716c.png)

https://codesandbox.io/s/stitches-token-nextui-tzufq0?file=/src/App.tsx

Also it's important to point out that is not a NextUI bug, we're waiting for the Stitches team to fix it as well

**Comment by hmbrg** [comment]
I'm sorry to be such a bother, but even the example you shared doesn't seem to be working correctly. The type of `px` is still not set correctly, and I'm not getting any autocompletion on the token values that `px` accepts. 

<img width="418" alt="Screenshot 2022-03-10 at 14 38 20" src="https://user-images.githubusercontent.com/7304269/157673193-1347eb12-48cd-4774-aaa5-c9e8e4a9f93e.png">

**Comment by hmbrg** [comment]
In fact, I'm not getting any token completion on any CSS property, not only utils.

**Comment by WonderPanda** [comment]
I'm very interested to try out Next UI as well but I've been getting really used to the level of typescript/intellisense integration provided natively by stitches. Not having access to type safety for the utils that NextUI adds to the stitches theme feels like a big loss here.

@jrgarciadev Looking at the sandbox link you've provided, there is no intellisense for any of the utils let alone enforcing the correct values are used with the util (eg px)

**Comment by jrgarciadev** [comment]
Hey @WonderPanda I'm glad you want to use NextUI, the IntelliSense problems on CodeSandbox are caused due to is not possible to set a custom `Typescript` version at least up to now https://github.com/codesandbox/codesandbox-client/issues/942, and **Stitches** has a problem with the latest Typescript version (which is used by CodeSandbox) https://github.com/modulz/stitches/issues/947#issuecomment-1061809383, we hope they fix that issue soon in order to have IntelliSense also on CodeSanbox, btw if you use VsCode you will not have this issue at all so you can try out NextUI without problem  👍🏻

**Comment by WonderPanda** [comment]
> Hey @WonderPanda I'm glad you want to use NextUI, the IntelliSense problems on CodeSandbox are caused due to is not possible to set a custom `Typescript` version at least up to now [codesandbox/codesandbox-client#942](https://github.com/codesandbox/codesandbox-client/issues/942), and **Stitches** has a problem with the latest Typescript version (which is used by CodeSandbox) [modulz/stitches#947 (comment)](https://github.com/modulz/stitches/issues/947#issuecomment-1061809383), we hope they fix that issue soon in order to have IntelliSense also on CodeSanbox, btw if you use VsCode you will not have this issue at all so you can try out NextUI without problem 👍🏻

Thanks for super quick response! I'll try things out in VsCode

**Comment by jrgarciadev** [comment]
Hey @hmbrg which Typescript version are you using? did you see this comment https://github.com/modulz/stitches/issues/947#issuecomment-1061809383 ?

**Comment by hmbrg** [comment]
Yes, I did. We are using the recommended version of "4.5.5".

**Comment by hmbrg** [comment]
Here is a basic repo just like the CodeSandbox: https://github.com/hmbrg/nextui-autocomplete-issue/blob/main/pages/index.tsx#L7 

The type of "p:" is of type `px?: {} | undefined`. 

Changing the typescript version to `4.3.4` doesn't fix it, sadly.

**Comment by hmbrg** [comment]
Yes, I made VSCode use the workspace version, not changing that makes the `length` error appear. After changing this the error goes away, but this issue persists.

**Comment by jrgarciadev** [comment]
Hey @hmbrg could you please check the version you are using is set as follows:
`typescript": "4.3.2"`

Notice that it has no the `^`  symbol, otherwise could be being installed other minor typescript version

**Comment by hmbrg** [comment]
Just tried that, sadly it doesn't fix it for me. I updated my example repo here: https://github.com/hmbrg/nextui-autocomplete-issue/blob/main/pages/index.tsx#L7

Have you tried my repo? Does this work for you? If yes, maybe it's something else with my local setup.

**Comment by jrgarciadev** [comment]
Hey @hmbrg I'm still trying to figure out why the Typescript/IntelliSense is not working on CodeSandbox, if you look at this example https://codesandbox.io/s/nextui-xxl-button-kbhbid?file=/App.js (Only JS) the autocomplete works 🤔 

Regarding VsCode autocomplete it works for me here's a video (it's laggy because I tested it on Github Codespaces):
https://user-images.githubusercontent.com/30373425/160298712-05e37f88-99c6-41c3-bf7e-aa923436ff7d.mov

**Comment by hmbrg** [comment]
Thanks for looking into this! I've noticed, that even in the video you provided, the `$black` in `bgColor: "$black"` didn't autocomplete. The type overlay in VSCode even showed the type of `bgColor` as `{} | undefined`. I really wonder what's going on, because this defintly works with just using  Stitches on its own, as you can see in this example: https://codesandbox.io/s/nextui-type-issue-5x128y?file=/pages/index.js

**Comment by hmbrg** [comment]
Bump. Are there any news on this? I'm still trying to figure this out.
