### ISSUE TITLE
[BUG] - DatePicker - 'calendar' is not exported from '@nextui-org/theme'

### ISSUE THREAD

**Issue by eretztzvi** [nextui-org/nextui#2920]
### NextUI Version

2.2.10

### Describe the bug

Can't import date picker component from '@nextui-org/react' - it just can't find it,
I installed it separately and tried to import from '@nextui-org/date-picker'. 
When trying to import DatePicker component i'm getting this error:

**Attempted import error: 'calendar' is not exported from '@nextui-org/theme' (imported as 'calendar').**

Also when trying to import any date picker component from '@nextui-org/date-picker',

Also added the following components: `nextui add date-picker` & `nextui add calendar` to  '@nextui-org/react'.

### Steps to Reproduce the Bug or Issue

search nextui documentation - nothing in there
search in stackoverflow - nothing in there

### Expected behavior

I expect to get the DatePicker component when importing it from  '@nextui-org/react'

### Screenshots or Videos

<img width="986" alt="image" src="https://github.com/nextui-org/nextui/assets/92538868/77acd5f7-c4e0-4d70-8ad0-6a67101ec4a5">

<img width="979" alt="image" src="https://github.com/nextui-org/nextui/assets/92538868/82d1b133-4c8a-4b6c-b029-ad230fa9c86d">

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
calendar was introduced in 2.3.0. please bump those dependencies to the latest.
