### ISSUE TITLE
[Feature Request] Autocomplete render trailing custom element functionality

### ISSUE THREAD

**Issue by CelloAdrian** [nextui-org/nextui#2925]
### Is your feature request related to a problem? Please describe.

When dynamically populating autocomplete from an array, we don't have an option to render a custom element to the Autocomplete component, in this case for example a "Create New" button

### Describe the solution you'd like

It would be nice to be able to render a custom element in the Autocomplete component when we specify the prop

### Describe alternatives you've considered

Material UI has this functionality :
https://mui.com/material-ui/react-autocomplete/#FreeSoloCreateOption.js

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/69909485/51b87119-107d-4089-8967-0847246db4d1)
![image](https://github.com/nextui-org/nextui/assets/69909485/7971c778-7c4e-41e0-abe3-380b84309e76)

**Comment by ryo-manba** [comment]
Thanks for the issue! As a workaround, you could potentially add a custom item like `Add "{inputValue}"` when the list of filtered items becomes empty using the `onInputChange` event. Additionally, you could remove any prefix from the message in the `onSelectionChange` event based on the key. If you try this out, please let us know how it goes!
