### ISSUE TITLE
[BUG] - Select not working correctly with numbers

### ISSUE THREAD

**Issue by jegork** [nextui-org/nextui#2926]
### NextUI Version

2.3.6

### Describe the bug

Select component seems to accept numbers, and given this type definitions

```typescript
export type Key = string | number;
```
```typescript
export type Selection = 'all' | Set<Key>;
```
```typescript
onSelectionChange?: (keys: Selection) => any,
```

it indeed seems possible. However, when you provide numbers as items of Select, in `onSelectionChange`, `keys` is always `Set<string>`

### Steps to Reproduce the Bug or Issue

``` typescript
<Select
          label="Test"
          items={[{ label: "2024", value: 2024 }]}
          onSelectionChange={(v) => {
            console.log(v);
          }}
        >
          {(item) => (
            <SelectItem key={item.value} value={item.value}>
              {item.label}
            </SelectItem>
          )}
        </Select>
```

when selecting a item, log statement prints `{'2024'}` (but should `{2024}`)

### Expected behavior

`value` in `onSelectionChange` should be `Set<number>`

### Operating System Version

macOS

### Browser

Chrome

**Comment by jegork** [comment]
Additionally, when you provide `string[]` to `selectedKeys`, e.g. [2020, 2021], then it cannot find these keys, therefore the Select dropdown does not show ticks next to selected items.

<img width="288" alt="image" src="https://github.com/nextui-org/nextui/assets/43540177/e58d8bac-9631-4969-8c75-ab3f707e331a">

**Comment by ryo-manba** [comment]
Thanks for the issue!

This issue stems from React converting the key to a string.

> Note that if you do specify a custom key on each Item using the key prop, React will convert the provided key to a string. As a result, all the collection component's key-related event handlers and props (e.g. onSelectionChange, selectedKey(s)) will expect and return strings.

See: https://react-spectrum.adobe.com/react-stately/collections.html#unique-keys

While it can be resolved by assigning an id to items as shown below, the current situation requires a key, so some adjustments need to be made. I'm currently working on this fix.

```tsx
let [years, setYears] = useState([
  {id: 1, value: 2024},
  {id: 2, value: 2025},
  {id: 3, value: 2026}
]);

<Select items={years}>
  {item => <SelectItem>{item.value}</SelectItem>}
</Select>
```

**Comment by jegork** [comment]
@ryo-manba thanks for taking a look. However after installing `0.0.0-canary-20240520130845` (which should include your PR), the result is exactly the same as I had initially
