### ISSUE TITLE
[BUG] -  The aria-describedby attribute must point to an element in the same document.

### ISSUE THREAD

**Issue by vavilondev** [nextui-org/nextui#2932]
### NextUI Version

2.2.10

### Describe the bug

<img width="1335" alt="Screenshot 2024-05-02 at 15 59 54" src="https://github.com/nextui-org/nextui/assets/84386678/8939801c-85a9-4a31-a424-1ccf0978acae">
I have a lot of errors like that.

### Steps to Reproduce the Bug or Issue

I have added a bunch of nextui components, and a lot of them add that error on [validator.w3](https://validator.w3.org/)

### Expected behavior

As a user, I expect not have that errors or to have valid element with correct id

### Operating System Version

- MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
can you tried it on the latest version? There are lots of changes between 2.2.10 and the latest.

**Comment by vavilondev** [comment]
@wingkwong the same issue

**Comment by ryo-manba** [comment]
@vavilondev 
It would be helpful if you could tell me which component caused this error.

**Comment by wingkwong** [comment]
Closing - fixed in https://github.com/nextui-org/nextui/pull/3301
