### ISSUE TITLE
[BUG] - Using `DropdownItem` as `Link` will open two windows simultaneously.

### ISSUE THREAD

**Issue by baijunjie** [nextui-org/nextui#2935]
### NextUI Version

2.3.6

### Describe the bug

```jsx
import {
  Dropdown,
  DropdownTrigger,
  DropdownMenu,
  DropdownItem,
  Button,
  Link,
} from '@nextui-org/react';

function App() {
  return (
    <>
      <Dropdown>
        <DropdownTrigger>
          <Button variant="bordered">Open Menu</Button>
        </DropdownTrigger>
        <DropdownMenu aria-label="Static Actions">
          <DropdownItem as={Link} target="_blank" href="https://google.com">
            Open Google
          </DropdownItem>
        </DropdownMenu>
      </Dropdown>
    </>
  );
}

export default App;
```
<img width="232" alt="image" src="https://github.com/nextui-org/nextui/assets/7956480/00ee55a4-7d59-4865-b67f-0d8155f15020">

Upon clicking, two windows will open simultaneously.

<img width="578" alt="image" src="https://github.com/nextui-org/nextui/assets/7956480/44174bb1-69c3-4a9c-8bd9-3dfd4e37f259">

It's important to note that, by default, the browser will block one window, so it may seem like only one window is opened. However, if the browser's blocking is disabled, two windows will open.
<img width="345" alt="image" src="https://github.com/nextui-org/nextui/assets/7956480/556fdcd8-3b40-43ce-9113-35887bf9f6b8">

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-pbo2fn?file=package.json,src%2FApp.jsx&terminal=dev

### Steps to Reproduce the Bug or Issue

none

### Expected behavior

Open only one window.

### Operating System Version

macOS

### Browser

Chrome

**Comment by ErlandssonA** [comment]
bump
