### ISSUE TITLE
[BUG] - Date-picker

### ISSUE THREAD

**Issue by TigerHu33** [nextui-org/nextui#2940]
### NextUI Version

Introducing v2.3.0 🎉

### Describe the bug

DatePicker（Date and time） component lost last column
<img width="734" alt="image" src="https://github.com/nextui-org/nextui/assets/49715395/a1bf864a-911b-4954-96fb-28f8ed1ce44b">

### Your Example Website or App

https://nextui.org/docs/components/date-picker

### Steps to Reproduce the Bug or Issue

1.click on

### Expected behavior

modify the bug

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/2917
