### ISSUE TITLE
[BUG] - Next UI V2 Routing in React + Vite project does not work.

### ISSUE THREAD

**Issue by ilap** [nextui-org/nextui#2941]
### NextUI Version

v2.3.6

### Describe the bug

Following the React example with `navigate` & `NextUIProvider` ref: https://nextui.org/docs/guide/routing, does not work.

See stackblitz example

### Your Example Website or App

 https://stackblitz.com/edit/vitejs-vite-32f1ps?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Open the app in stackblitz
2. Click the links to test
3. Only the react-route-dom's links are routing

### Expected behavior

Navigation should work with the NextUI V2 components too.

### Operating System Version

macos Sonoma 14.5

### Browser

Chrome

**Comment by desiassassin** [comment]
Facing the same issue.

I see a PR is pending. Thank you in advance for fixing this 🔥

**Comment by uiii** [comment]
I have this issue as well

**Comment by wingkwong** [comment]
The [fix](https://github.com/nextui-org/nextui/commit/73d96959945820981b8a4c0e3175c13e3d1c1499) will be available in the next release. At the same time, you can use our canary version as a workaround if necessary.

```json
"@nextui-org/system": "0.0.0-canary-20240504162810"
```

update `NextUIProvider` to use `@nextui-org/system`

```tsx
import { NextUIProvider } from "@nextui-org/system";
```
