### ISSUE TITLE
[BUG] - Textarea resize icon is not appearing in the right bottom corner of the component

### ISSUE THREAD

**Issue by Gepsonka** [nextui-org/nextui#2951]
### NextUI Version

2.2.10

### Describe the bug

I set the `disableAutosize` prop on the components but the icon in the corner does not appear, I cannot resize it.

Nextjs version: 14.2.1

Code:

```typescript
const CreateListing = () => {
  return (
    <MarketplaceLayout>
      <div className="subpage-container">
        <h1 className="page-title">Create New Real Estate Listing</h1>
        <div className="listing-form-container">
          <div className="input-container">
            <Input label={"Listing Name"} />
          </div>
          <div className="input-container">
            <Textarea
              variant="bordered"
              disableAutosize
              label={"Description"}
            />
          </div>
          <div className="input-container">
            <Input type="number" label={"Amount of Tokens"} />
          </div>
          <div className="input-container">
            <Input type="number" label={"Token Listing Price"} />
          </div>
          <div className="input-container">
            <Button color="primary">Submit Listing</Button>
          </div>
        </div>
      </div>
    </MarketplaceLayout>
  );
};
```

SCSS:

```scss
.page-title {
  @apply text-3xl font-bold;

  text-align: center;
  margin-top: 1rem;
  margin-bottom: 1rem;
}

.input-container {
  margin-top: 1.5rem;
  margin-bottom: 1.5rem;
}
```

### Steps to Reproduce the Bug or Issue

See code above

### Expected behavior

To get a resizable texarea

### Screenshots or Videos

<img width="533" alt="Screenshot 2024-05-05 at 12 03 39 AM" src="https://github.com/nextui-org/nextui/assets/45335158/ab0e6b23-9ed8-485b-bebd-2f6bc9196a40">
<img width="609" alt="Screenshot 2024-05-05 at 12 04 12 AM" src="https://github.com/nextui-org/nextui/assets/45335158/cf96b3a7-28f1-4e60-999f-b1486d6e6a95">

### Operating System Version

macOS

### Browser

Firefox

**Comment by wingkwong** [comment]
> I cannot resize it.

By setting `disableAutosize` to `true`, it means that the textarea auto vertically resize should be disabled. Hence, whenever you input multiple lines and the height is greater than that of the textarea, it won't vertically resize.

> but the icon in the corner does not appear,

That is not related to `disableAutosize`. It can be shown for both case. If you want that icon, you need to add the following styles.

```
classNames={{
  base: "max-w-xs",
  input: "resize-y min-h-[40px]",
}}
```

![image](https://github.com/nextui-org/nextui/assets/35857179/11f64221-2175-42e2-8f90-67ec979efecc)
