### ISSUE TITLE
[BUG] - Switch component inside of table is trigger when a row is selected

### ISSUE THREAD

**Issue by lanoow** [nextui-org/nextui#2959]
### NextUI Version

2.3.6

### Describe the bug

I have a products table:
![image](https://github.com/nextui-org/nextui/assets/43927089/d4b0098b-8228-43bf-bf3e-d3c1214df54f)

When the switch is set active, there's no problem when selecting the row, however when the switch is inactive whenever I select the row it toggles the switch.
[scrnli_5_7_2024_10-32-43 AM.webm](https://github.com/nextui-org/nextui/assets/43927089/6ac9f77c-0cf0-4805-aae7-ff94bcde8c44)

### Steps to Reproduce the Bug or Issue

1. Create a table component
2. Add a Switch component to the row
3. Set it active on page load using useState
4. Click on the row - nothing will happen.
5. Toggle it to inactive
6. Click on the row and it will toggle with the row selection

### Expected behavior

I expected it to not change on row selection no matter what the state of the switch is but what I'm seeing is a change.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
Reopening - the PR includes breaking changes. Now it's rescheduled to v.2.5.0.

**Comment by quinhatpy** [comment]
@wingkwong Hi, when do you release a new version to fix this issue?

**Comment by wingkwong** [comment]
Next release will include lots of changes. we plan to release some beta versions first. hopefully next month.

**Comment by AlirezaAdabi** [comment]
I found a workaround, I hope it solve your problem until the new release.

I used js solution as you can see in below snippet code : 

```jsx
const divRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (divRef.current) {
      const label = divRef.current.closest('label');
      const pattern = /(?:rtl:)?group-data-(?!.*\/switch).*/;
      if (label) {
        label.classList.remove('group');
        const child = label.getElementsByClassName('switch-child');
        child[0].classList.forEach((item) => {
          if (item.match(pattern)) {
            child[0].classList.remove(item);
          }
        });
        child[0].children[0].classList.forEach((item) => {
          if (item.match(pattern)) {
            child[0].children[0].classList.remove(item);
          }
        });
      }
    }
  }, []);
  return (
    <Switch
      isSelected={isSelected}
      ref={divRef}
      onValueChange={setIsSelected}
      classNames={{
        base: cn('group/switch'),
        wrapper: cn(
          'switch-child group-data-[focus-visible=true]/switch:z-10 group-data-[focus-visible=true]/switch:ring-2 group-data-[focus-visible=true]/switch:ring-focus group-data-[focus-visible=true]/switch:ring-offset-2 group-data-[focus-visible=true]/switch:ring-offset-background group-data-[selected=true]/switch:bg-primary group-data-[selected=true]/switch:text-primary-foreground',
        ),
        thumb: cn(
          'group-data-[selected=true]/switch:ml-6 rtl:group-data-[selected=true]/switch:ml-0 rtl:group-data-[selected=true]/switch:mr-6 transition-all group-data-[pressed=true]/switch:w-7 group-data-[selected]/switch:group-data-[pressed]/switch:ml-5',
        ),
      }}
    >
  );
};
```

---

⚠If it had issue in some cases, please share your fix if you have any.
