### ISSUE TITLE
[BUG] - International calendar unexpected behaviour when change month or year on Persion calendar 

### ISSUE THREAD

**Issue by mahmood-kn** [nextui-org/nextui#2960]
### NextUI Version

2.3.6

### Describe the bug

I'm using international with Persian calendar but when I try to change the month or year the months get converted to English calendar

### Steps to Reproduce the Bug or Issue

This is my code and you can check the problem by creating below component:
```javascript
import {
  parseDate,
} from '@internationalized/date';

import { I18nProvider } from '@react-aria/i18n';
const Form = () => {
let [date, setDate] = useState(parseDate('2021-04-07'));
return (
 <I18nProvider locale='fa-IR-u-ca-persian'>
              <DatePicker
                showMonthAndYearPickers
                variant='bordered'
                className='max-w-md'
                value={date}
                onChange={setDate}
              />
            </I18nProvider>
)
}
```

### Expected behavior

I expect that I can modify month and year in Persian calendar 

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/63015240/564d677a-3101-43f3-bea0-880ac08b4865

### Operating System Version

Windows

### Browser

Chrome

**Comment by abhinandan-verma** [comment]
@mahmood-kn   I used to the code provided by you and it working fine, no change to english month.
is the issue still there ?
