### ISSUE TITLE
[BUG] - Date Picker - component lost last column with Create React App

### ISSUE THREAD

**Issue by vietvh-3042** [nextui-org/nextui#2964]
### NextUI Version

2.3.6

### Describe the bug

The calendar in the date picker or date range picker is truncated and does not show the last day column.
This error occurs when I use DatePicker with the latest version. I use it with Create React App and when I run it I get a lot of warnings.I completely use CRA's template typescript without making any changes

### Steps to Reproduce the Bug or Issue

Use the minimal version of the Date picker or date range picker

### Expected behavior

The calendar should be fully rendered.

### Screenshots or Videos

Screenshots1: Bug UI
![image](https://github.com/nextui-org/nextui/assets/103104318/6ce94164-bdb9-4e90-8ed0-fdd539b42717)

Screenshots2: Warning terminal
![image](https://github.com/nextui-org/nextui/assets/103104318/8545deef-d097-489d-a003-31d936337587)

### Operating System Version

Windows, Linux

### Browser

Chrome

**Comment by wingkwong** [comment]
see https://github.com/nextui-org/nextui/issues/2917
