### ISSUE TITLE
[BUG] - datepicker only shows 6 days of the week

### ISSUE THREAD

**Issue by ManuelCarrascal** [nextui-org/nextui#2979]
### NextUI Version

^2.0.7

### Describe the bug

I am using the default datepicker and when trying it I found an error that it does not load seven days a week but only six and I think that is wrong since in my case I need every day.

### Steps to Reproduce the Bug or Issue

just use the default datepicker component

### Expected behavior

The default datepicker shows me all the days of the week but it is only showing six

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/54221416/29021986-386c-4c7a-b2d9-18a664b816af)

![image](https://github.com/nextui-org/nextui/assets/54221416/6748cae3-21a1-4545-866a-c202da47520a)

### Operating System Version

windows

### Browser

Chrome

**Comment by wingkwong** [comment]
wondering if it is OS or browser problem. Can you screenshot the below storybook on your side?

https://storybook.nextui.org/?path=/story/components-datepicker--with-month-and-year-pickers&globals=locale:en-US

It looks fine on my side.

![image](https://github.com/nextui-org/nextui/assets/35857179/77e41ea1-cb84-416c-9130-f6a554f6adb4)

**Comment by LucasLeone** [comment]
I tried in Safari and works, but in chrome doesn't work, why?

```
                <DatePicker
                    label='Fecha'
                    showMonthAndYearPickers
                    value={selectedDate}
                    onChange={(e) => setSelectedDate(e)}
                    className='basis-full md:basis-5/12 mb-2 md:me-2 md:mb-0'
                    size='sm'
                />
 
```

**Comment by ManuelCarrascal** [comment]
I think the problem is in browsers that use base chromium because:

I was testing in chrome and it looks like this:
![image](https://github.com/nextui-org/nextui/assets/54221416/70b649a0-0e17-42c3-af05-c0fc23d0e61a)

while in mozilla firefox it looks fine
![image](https://github.com/nextui-org/nextui/assets/54221416/eabcf167-545a-4d96-962c-6d5848817e46)

I also tried brave to clear up doubts
![image](https://github.com/nextui-org/nextui/assets/54221416/278e4905-6b3e-4c2f-82b7-4abcd020787f)

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3416
