### ISSUE TITLE
[BUG] - DatePicker shows only six days

### ISSUE THREAD

**Issue by LucasLeone** [nextui-org/nextui#2983]
### NextUI Version

2.3.6

### Describe the bug

I am using the default datepicker and when trying it I found an error that it does not load seven days a week but only six and I think that is wrong since in my case I need every day.

### Steps to Reproduce the Bug or Issue

just use the default datepicker component

### Expected behavior

The default datepicker shows me all the days of the week but it is only showing six

### Screenshots or Videos

<img width="217" alt="Screenshot 2024-05-11 at 20 10 57" src="https://github.com/nextui-org/nextui/assets/60592181/34db032f-8ad3-4945-99c4-d6df55f839d0">
`<DatePicker
    label='Fecha'
    showMonthAndYearPickers
    value={selectedDate}
    onChange={(e) => setSelectedDate(e)}
    className='basis-full md:basis-5/12 mb-2 md:me-2 md:mb-0'
    size='sm'
/>`

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/2979
