### ISSUE TITLE
Col component TS error with align prop

### ISSUE THREAD

**Issue by samfromaway** [nextui-org/nextui#299]
**Describe the bug**
When using the Col component, I get a typescript error when using the align prop even though it works.

**Steps to reproduce**
1. Add a new project
2. Import Col
3. Add align prop e.g. `<Col align="center" />`

**Expected behaviour**
Have no TS error

**Screenshots**

**Environment / Context**
1.0.2-beta.4

**Comment by Dhananjay-JSR** [comment]
strange since there is no such prop named `align` for column component , I don't think it should work

**Comment by jrgarciadev** [comment]
Hey @samfromaway just as @Dhananjay-JSR there’s not a prop called ‘align’ for ‘Col’ component, here’s the API https://nextui.org/docs/layout/container#col-props

**Comment by samfromaway** [comment]
Ok interesting that it still centers the elements in Col.
