### ISSUE TITLE
[BUG] - NextUI Link not working in vercel prod environment

### ISSUE THREAD

**Issue by a0v0** [nextui-org/nextui#2991]
### NextUI Version

2.3.6

### Describe the bug

When using `Link` component from either `"@nextui-org/react"` or `"@nextui-org/link"`, I am not able to route to different pages. This unusual behaviour is coming only at the main deployment of vercel. 

Though in preview environment and also in local dev I am to navigate without any error. 

In prod site, console is giving this error.

### Your Example Website or App

https://github.com/a0v0/avtoolz

### Steps to Reproduce the Bug or Issue

Checkout https://avtoolz.com/ and try to navigate you should see the unexpected behaviour. 

### Expected behavior

navigation should work even in prod env.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/62926341/90f5033e-1db4-414a-bd56-918f73ebfe76)

### Operating System Version

ZorinOS

### Browser

Other (add additonal context)

**Comment by wingkwong** [comment]
See https://github.com/nextui-org/nextui/issues/2934#issuecomment-2096289017
