### ISSUE TITLE
Junior reply to my emails, be a man!

### ISSUE THREAD

**Issue by vitalijalbu** [nextui-org/nextui#2996]
### NextUI Version

2

### Describe the bug

Don’t be a pussy and reply to my emails @jrgarciadev or give me my money back.

How dare you? How you can be a CEO of something if you even don’t reply to your paying customers?

### Steps to Reproduce the Bug or Issue

Go to gmail and open emails

### Expected behavior

Money refund

### Operating System Version

Nextui

### Browser

Chrome

**Comment by wingkwong** [comment]
You are banned because you were re-selling NextUI Pro (not just us actually) on Reddit which is forbidden by the license. Even though you've deleted all the messages on Reddit and personal info for us to track you down, it was too late.

P.S. I'm that fake buyer.

**Comment by vitalijalbu** [comment]
> You are banned because you were re-selling NextUI Pro (not just us actually) on Reddit which is forbidden by the license. Even though you've deleted all the messages on Reddit and personal info for us to track you down, it was too late.
> 
> P.S. I'm that fake buyer.

i sold you something?? no! then give me back money or account... so simple

**Comment by vitalijalbu** [comment]
> You are banned because you were re-selling NextUI Pro (not just us actually) on Reddit which is forbidden by the license. Even though you've deleted all the messages on Reddit and personal info for us to track you down, it was too late.
> 
> P.S. I'm that fake buyer.

Read pls carefully here... @wingkwong 
Also you are **NOT located in United States** and your license doesn't make any sense, you are from Argentina.

<img width="1080" alt="Screenshot 2024-05-14 alle 09 15 54" src="https://github.com/nextui-org/nextui/assets/40239902/edd4b7db-0f4c-4c27-8d1e-142ef449b371">

I deleted all posts, of course! I spent 250$ for some components that **have still bugs an no one solves them**! How you will answer that??

So I'd say for latest time, **money back or it will end in another way** 🙂

Have a nice day all of you.

PS. @jrgarciadev your turn to reply.... at least here
