### ISSUE TITLE
DatePicker not applying inputWrapper

### ISSUE THREAD

**Issue by shahin7333** [nextui-org/nextui#2998]
I want to apply a new border with color, but I can't. what is the issue?

**Comment by wingkwong** [comment]
seems `inputWrapper` from date input is not accessible from date picker.

**Comment by ryo-manba** [comment]
Thanks for the issue! You can apply styles to the input using [slots](https://nextui.org/docs/components/date-picker#slots) as shown below.

```tsx
  <DatePicker classNames={{base: "border-3 border-white"}} />
```
![datepicker-with-classnames](https://github.com/nextui-org/nextui/assets/76232929/647d4778-215e-4ade-94d2-90ba9de4aa55)

**Comment by ryo-manba** [comment]
Ah, after looking into it a bit more, it seems this method could cause various issues. I will work on allowing `classNames` to be passed to the input instead.
https://github.com/nextui-org/nextui/issues/2895
