### ISSUE TITLE
[BUG] - Table row hover state bug when using tooltip

### ISSUE THREAD

**Issue by Moriarty47** [nextui-org/nextui#3002]
### NextUI Version

2.3.5

### Describe the bug

I am using Table that has content wrapped in tooltips with `selectionMode="multiple"` option,  here is [a minimal example](https://stackblitz.com/edit/stackblitz-starters-rzryca?file=app%2Fpage.tsx).

### Steps to Reproduce the Bug or Issue

When hover throught tooltips from bottom to top,  rows hover state stoped, as you can see below.

![1](https://github.com/nextui-org/nextui/assets/21117495/6ab2226c-e30c-40bd-af7c-e606fb3b220e)

### Expected behavior

As a user, I expected the rows hover state act normally.

### Operating System Version

WIndows

### Browser

Chrome

**Comment by KumJungMin** [comment]
This issue occurs when the mouse passes over the tooltip of row. 
Currently, the tableRow uses the hover functionality of the react-aria library. 

In table selection mode, I think it should be determined whether to cancel the hover when the mouse hovers over the tooltip. If the hover should be maintained when the mouse is over the tooltip, I think modifications might be needed within the react-aria library itself. :smiling_face_with_tear: 

https://github.com/nextui-org/nextui/blob/41d2eeb20bde3182306f134ba619942e182d0998/packages/components/table/src/table-row.tsx#L10

**Comment by matteogilioli** [comment]
To improve things a little temporarily you could use a closeDelay={0} and an offset for the Tooltip
