### ISSUE TITLE
[BUG] - Date Picker value prop throws type error

### ISSUE THREAD

**Issue by utkarsh-source** [nextui-org/nextui#3005]
### NextUI Version

ex. 2.3.0

## Bug
Got type error while using the DatePicker component ( controlled version  snippet) given on the NEXT UI website.

## My Code
import { useState } from 'react';

import { parseDate } from '@internationalized/date';
import { DatePicker as NUIDatePicker } from '@nextui-org/react';

export function DatePicker() {
  const [value, setValue] = useState(parseDate('2024-04-04'));

  return (
    <NUIDatePicker
      labelPlacement="outside"
      size="md"
      value={value}
      onChange={setValue}
      variant="bordered"
      showMonthAndYearPickers
    />
  );
}

## ScreenShots
But i get this type error if I follow the snippet given for a controlled DatePicker on the Next UI site.
<img width="904" alt="Screenshot_203" src="https://github.com/nextui-org/nextui/assets/54720265/f1ca467b-3bd3-4ab3-aff4-3ccb91724126">

Console error.
<img width="889" alt="Screenshot_204" src="https://github.com/nextui-org/nextui/assets/54720265/abda29cf-b725-4507-bf5a-8c9a0984d2aa">

Can somebody check this out?

### Steps to Reproduce the Bug or Issue

Copy the snippet for controlled date picker component.
Observe the type error.

### Expected behavior

Should not throw ant type error.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
You haven't casted the type `DateValue`. It is shown in the example in the doc.

```tsx
const [value, setValue] = React.useState<DateValue>(parseDate("2024-04-04"));
```

<img width="337" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/9b27e243-38e5-4e36-aa12-af0c527d495c">
