### ISSUE TITLE
Cannot set borderRadius:0 to Card.Image 

### ISSUE THREAD

**Issue by Spice-Z** [nextui-org/nextui#301]
**Describe the bug**
I cannot set `borderRadius: 0` to Card.Image with css props.

When component is like this,
```jsx
 <Card.Body css={{ p: 0, borderRadius: 0 }}>
   <Card.Image
     objectFit='cover'
     src={v.src}
     width='100%'
     height={200}
     alt='alt'
     css={{ borderRadius: 0 }}
   />
 </Card.Body>
```

Real DOM will be like this.

```html
<div class="nextui-c-gJBdwd nextui-c-gJBdwd-idUCfml-css">
  <div
    class="nextui-c-bVLlAJ nextui-c-bVLlAJ-bDGmTT-ready-true nextui-c-bVLlAJ-idqeSIq-css nextui-image-container nextui-image--ready"
    data-state="ready"
  >
    <img
      class="nextui-c-kbhVdb nextui-c-kbhVdb-ibOpXIv-css nextui-image"
      width="100%"
      height="200"
      src="/images/image.jpg"
      data-state="ready"
      alt="alt"
    />
  </div>
</div>
```

It seems there is another  div between Card.Body and Card.Image.
That `div`  has  `border-top-left-radius: 14px; border-top-right-radius: 14px;`, and I cannot override it.

**Steps to reproduce**
1. Set `css={{ borderRadius: 0 }}` on Card.Image
2. Happen

**Expected behaviour**
Can set `border-radius:0` style.

**Screenshots**

**Environment / Context**
- Desktop or Mobile: Both

**Additional info**

**Comment by thedevtek** [comment]
Is this solved ?
or reopened for any bug ? Please Describe
