### ISSUE TITLE
[BUG] - VSCode's Intellisense doesn't work for all props

### ISSUE THREAD

**Issue by vietan0** [nextui-org/nextui#3025]
### NextUI Version

2.3.6

### VSCode Version

1.89.1

### Describe the bug

IntelliSense displays some props and not others.

There's no `color` prop here:
| `<Button />`| `<Input />` |
| -------- | ------- |
| ![image](https://github.com/nextui-org/nextui/assets/97825820/6828c16a-ca24-4ec7-9201-090bdd95b82d) | ![image](https://github.com/nextui-org/nextui/assets/97825820/d621be0a-86ea-4184-8b2b-42a49347ae99) |

In `<Button />`, props like `color`, `onPress`, `variant`, `radius` don't show up, while props like `isLoading`, `spinner`, `disableRipple` do.

In other components e.g. `<Card />`, no props show up.
![image](https://github.com/nextui-org/nextui/assets/97825820/0446a162-c056-4a41-b2f9-b8b02e8fc338)

AFAIK, it's not a pnpm issue. I have a npm project without this issue, reinstalled everything using pnpm, and everything works fine.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-vz9tyq?file=src%2FReproIssue.tsx

### Steps to Reproduce the Bug or Issue

1. Go to Stackblitz repo
2. Go to any component's opening tag and open Intellisense by `Ctrl` + `Space`

### Expected behavior

Full list of props to show up.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/97825820/c8dab570-4350-432c-9e93-59a0c5808a59

### Operating System Version

Windows

**Comment by wingkwong** [comment]
<img width="936" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/32e0fe83-39cf-4426-b4bf-cbc9b3e01f24">

**Comment by vietan0** [comment]
@wingkwong I have another bug-free nextui project, so I tracked down its type definitions and found out the types I'm missing come from `@nextui-org/theme`, which reference `tailwind_variants`.

![image](https://github.com/nextui-org/nextui/assets/97825820/208c794e-bce5-40b1-8230-6453d913b90c)

But `tailwind-variants` was not installed in `@nextui-org/theme`:
| Expected | Actual |
| --------- | ------- |
| ![image](https://github.com/nextui-org/nextui/assets/97825820/f8ac27e0-5d14-4c4a-9445-1f11f40916cf) | ![image](https://github.com/nextui-org/nextui/assets/97825820/47d106a1-de76-4e1d-8642-37e15368e5ab)

I tried installing `tailwind-variants` in the root of my project and that didn't work. What should I do to fix this?

**Comment by wingkwong** [comment]
can you share your package.json and the way you install?

**Comment by vietan0** [comment]
https://github.com/vietan0/todo-fe/blob/main/package.json

What do you mean by 'the way I install'? I use [global installation](https://nextui.org/docs/guide/installation#global-installation)  if that's what you're asking.

**Comment by wingkwong** [comment]
like are you using pnpm or npm or other package managers
