### ISSUE TITLE
[BUG] - Input with "datetime-local" type has wrong margin when setting min/max date

### ISSUE THREAD

**Issue by JobberRT** [nextui-org/nextui#3026]
### NextUI Version

2.3.6

### Describe the bug

The `Input` component will have a wrong padding/margin when using `datetime-local` with `min`/`max` and some of the field are disabled.

# Bug screenshot
<img width="623" alt="image" src="https://github.com/nextui-org/nextui/assets/17498767/952fb8a7-582b-4a37-a1de-c11147a89924">

# Normal screenshot
<img width="625" alt="image" src="https://github.com/nextui-org/nextui/assets/17498767/5697ccb0-8fe5-4991-8cad-c308811ba21a">

### Steps to Reproduce the Bug or Issue

Create a `Input` component and set its `max` to now(so that some fields can be disabled, like `year`). 

### Expected behavior

The margin/padding is correct

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Can you share the code you used for the screenshot?

**Comment by JobberRT** [comment]
@wingkwong 
```tsx
const [tt, setTT] = useState("2024-05-20T12:00:00");

<div className={"flex flex-row flex-wrap items-center justify-between gap-3 sm:gap-5 md:gap-10 lg:gap-16"}>
    <div className={"flex flex-grow"}>
        <div className={"flex items-center justify-center gap-0.5"}>
            <Input type={"datetime-local"} value={tt} onValueChange={setTT} 
                   max={new Date(Date.now()).toISOString().slice(0, -5)} 
                   min={new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().slice(0, -5)} />
        </div>
    </div>
</div>
```

**Comment by wingkwong** [comment]
@JobberRT I still don't know how to reproduce the issue based on this code. Can you elaborate more?

![image](https://github.com/nextui-org/nextui/assets/35857179/7486f36a-f6f5-4164-9ae1-c729daa1048c)

**Comment by JobberRT** [comment]
@wingkwong  Maybe because you are using PM/AM while I'm using 24H ? In my environment, the exact same code can reproduce the bug though.

I also tried remove the "second" part of the time string, the bug is still there

**Comment by wingkwong** [comment]
Can you share a stackblitz project so that we could be on the same ground?

**Comment by JobberRT** [comment]
Sure, Here's the link: https://stackblitz.com/edit/vitejs-vite-x36zme?file=src%2FApp.tsx

**Comment by JobberRT** [comment]
Seems not... I got not PM/AM choice, it's 24H. May this be the issue?
<img width="461" alt="image" src="https://github.com/nextui-org/nextui/assets/17498767/8e1ef114-fcab-4e2f-b31f-da1c9c1b3f1a">
![image](https://github.com/nextui-org/nextui/assets/17498767/39aefc5d-8e4c-4817-807c-c0d24427997b)
