### ISSUE TITLE
React is not defined in production

### ISSUE THREAD

**Issue by flcarre** [nextui-org/nextui#303]
Describe the bug
Got a strange error on build version "React is not defined". I'm using Nextui on an open source projet, here is my template: https://github.com/flcarre/jhipster-lite-react-login-template

I tried to deploy on Vercel and got the same issue

![image](https://user-images.githubusercontent.com/43339017/155551281-1c0aa056-da1b-43e3-bfc8-b027175a7b90.png)

Steps to reproduce
npm run build && npm run preview

Expected behaviour
Build and deploy app

Environment / Context

Desktop or Mobile: Desktop
Operating System: Zorin
Browser and version chrome 22
Device: Dell laptop

Additional info
I'm using Vite, i guess it can cause the problem

**Comment by chrisly-bear** [comment]
I'm having the same issue (also using Vite). What seems to help is removing the `NextUIProvider` in the root of my application (basically skipping the [setup step](https://nextui.org/docs/guide/getting-started#setup) from the tutorial).

**Comment by flcarre** [comment]
Ok thank's, strange issue ^^

**Comment by jrgarciadev** [comment]
Hey guys, could you please compare your project structure/code to this example? -> https://github.com/nextui-org/nextui/tree/main/examples/vite-react-typescript

**Comment by flcarre** [comment]
Look similar, without the provider it work well

**Comment by jrgarciadev** [comment]
Hey @flcarre it seems to be a Vite `@vitejs/plugin-react` issue https://github.com/vitejs/vite/issues/5608, some users managed to solved them
