### ISSUE TITLE
[BUG] - Input component issue when using server actions

### ISSUE THREAD

**Issue by Hossein-i** [nextui-org/nextui#3030]
### NextUI Version

2.1.21

### Describe the bug

When the validation is done from the server side and if there is an error, it will be displayed in the input component.
After displaying the error, the input component will not allow resubmission because props isInvalid is true.

```tsx
const [state, formAction] = useFormState(checkIfExistsAction, initialState);

...

<Input
  label="Email"
  name="email"
  isInvalid={!!state?.message?.email?.join()}
  errorMessage={state?.message?.email?.join()}
/>

...
```

### Steps to Reproduce the Bug or Issue

1. [Server-side validation and error handling](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-validation-and-error-handling)
2. [Input With Error Message](https://nextui.org/docs/components/input#with-error-message)

### Expected behavior

As a user, I expected an error message to be displayed every time I submit the form if the fields are not approved, while submitting the form is only allowed once and an error is displayed and it is not possible to submit again.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/2844

**Comment by wingkwong** [comment]
Behind the scene it's because the state isn't updated due to the native browser validation behaviour if you use an uncontrolled input. or you may share the minimal reproducible environment so that we could have one more case to test on.

**Comment by Hossein-i** [comment]
[Here is a minimal env](https://codesandbox.io/p/devbox/elegant-sutherland-hcsmlq?file=%2Factions%2Fauth.ts%3A4%2C1)

**Comment by Hossein-i** [comment]
@wingkwong 

Thank you very much bro

My problem is solved

```bash
nextui remove input

npm uninstall -g nextui-cli

npx shadcn-ui@latest init

npx shadcn-ui@latest add input
```
