### ISSUE TITLE
[BUG] - DatePicker not applying inputWrapper className

### ISSUE THREAD

**Issue by pedro-bigz** [nextui-org/nextui#3033]
### NextUI Version

2.3.6

### Describe the bug

The DatePicker component is not applying inputWrapper className. When I'm passing `classNames={{ inputWrapper: 'border-small' }}`, the class border-small is not being added to input wrapper after rendered.

`<I18nProvider locale="pt-BR">
      <NextDatePicker
        classNames={{
          calendarContent: "capitalize",
          inputWrapper: classnames(
            "border-small px-[16px]",
            classNames?.inputWrapper
          ),
          ...classNames,
        }}
        isInvalid={Boolean(errorMessage)}
        errorMessage={errorMessage}
        showMonthAndYearPickers
        fullWidth
        {...props}
      />
    </I18nProvider>`

### Steps to Reproduce the Bug or Issue

1. Try to pass classNames.inputWrapper to the component

### Expected behavior

If I pass inputWrapper className as border-small, I wanna see `border-width: 1px` css attribute applied to my component

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
Duplicate - https://github.com/nextui-org/nextui/issues/2998
