### ISSUE TITLE
AutocompleteItem's onPress event is not working

### ISSUE THREAD

**Issue by Vardaan-Grover** [nextui-org/nextui#3039]
### NextUI Version

2.2.10

### Describe the bug

I recently migrated my project from Vite to NextJS. The migration did not succeed at the first go, and therefore I had to start a new NextJS project from scratch and manually copy paste files into appropriate folders by myself. While doing this I believe I've run into an issue with the AutocompleteItem's onPress event function. Even though the UI remains the same as it was, pressing a specific AutocompleteItem doesn't call its associated onPress function. I've tried copy pasting the previous code (which is working correctly) into my new NextJS project but that doesn't seem to be able to fix the issue.

### Steps to Reproduce the Bug or Issue

I am not sure how to tell you guys how you can reproduce my specific code. I'm sorry but I'm a bit of a noob.

### Expected behavior

![image](https://github.com/nextui-org/nextui/assets/67010021/a322429f-1c96-42fd-bb9f-9848755553ca)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
@Vardaan-Grover I couldn't reproduce the issue on the latest version. Please upgrade it. Feel free to reopen if you still got an issue.
