### ISSUE TITLE
[BUG] - DropdownTrigger not working with Badge + Button

### ISSUE THREAD

**Issue by dubdia** [nextui-org/nextui#3051]
### NextUI Version

2.3.6

### Describe the bug

First: I realy love to use NextUI! Thanks for that!

I think i found a bug in the dropdown.
```
<Dropdown backdrop="blur">
      <DropdownTrigger>
        <Badge content={list.length} color="default" showOutline={false}>
             <Button>
                <FaStar></FaStar>
             </Button>
        </Badge>
      </DropdownTrigger>
      <DropdownMenu>
          ...
      </DropdownMenu>
    </Dropdown>
```

The Button is not working in the DropdownTrigger when the Badge is in-between.

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

The Dropdown should open but its not working when Button is in Badge

### Operating System Version

Windows

### Browser

Chrome

**Comment by KumJungMin** [comment]
I think, the dropdown trigger is sets only inactive elment(such button, a)

https://github.com/nextui-org/nextui/blob/5194a02d8293b21014280cd98b0d4478dd45c7b0/packages/components/dropdown/src/dropdown-trigger.tsx#L11

_`dropdown-trigger.tsx`_
<img width="812" alt="스크린샷 2024-05-27 오전 8 53 15" src="https://github.com/nextui-org/nextui/assets/37934668/d7fdcc58-b1f9-4cb3-bc67-a905da683130">

**Comment by alphaxek** [comment]
@dubdia, it takes `badge` as its trigger

![droptrigtest](https://github.com/nextui-org/nextui/assets/116849110/9e25ec7b-6ecc-4149-bd39-1e0108e71212)
