### ISSUE TITLE
[BUG] - Select does not close when it's container is clicked again from open state

### ISSUE THREAD

**Issue by niraj-khatiwada** [nextui-org/nextui#3056]
### NextUI Version

2.1.0

### Describe the bug

The Select component never closes when it's container is clicked again after opening it. It is just stucked. It only closes when I click anywhere outside of  the container or any of the select items.

### Your Example Website or App

https://github.com/niraj-khatiwada/NextUI-Select

### Steps to Reproduce the Bug or Issue

Run the dev server and go to home page. I've setup the Select component only right there to reproduce.
![image](https://github.com/nextui-org/nextui/assets/51436631/cd1c7f89-15b2-4cb3-bc25-9b69dc614b46)

### Expected behavior

The Select should close when the container is clicked like normal select works. The Select demo shown in website works but for some reason, it doesn't work after installing and using it in the project.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/51436631/b0b2d17a-820f-4626-879e-79f4595edb4b

I'n constantly clicking in the container in the recording by the way.

### Operating System Version

Tested on Linux. Not sure on Windows and MacOS
EDIT: Same issue on Windows and MacOS as well.

### Browser

Chrome

**Comment by ryo-manba** [comment]
Thank you for reporting the issue! It seems the version you are using is outdated.
Please try updating to the latest version, 2.3.6.

If the issue persists, please paste the source code of the section where the Select component is being used.

**Comment by niraj-khatiwada** [comment]
> Thank you for reporting the issue! It seems the version you are using is outdated. Please try updating to the latest version, 2.3.6.
> 
> If the issue persists, please paste the source code of the section where the Select component is being used.

Just upgraded to 2.3.6 and still does not work. The Select is used in a `app/page.tsx`
![image](https://github.com/nextui-org/nextui/assets/51436631/7079792c-681a-4bc4-bfdc-2e5c526231a2)

**Comment by wingkwong** [comment]
@niraj-khatiwada can you try on this version?

```
"@nextui-org/select": "0.0.0-canary-20240524213453"
```

**Comment by niraj-khatiwada** [comment]
> @niraj-khatiwada can you try on this version?
> 
> ```
> "@nextui-org/select": "0.0.0-canary-20240524213453"
> ```

Yes, it works on this one.

**Comment by wingkwong** [comment]
If so, then it means this issue has been resolved. The fix will be available in the next version (v2.4.0) which we will release soon.

**Comment by niraj-khatiwada** [comment]
> If so, then it means this issue has been resolved. The fix will be available in the next version (v2.4.0) which we will release soon.

Is it safe to install canary release? I want to send quick fix to my project.

**Comment by wingkwong** [comment]
@niraj-khatiwada canary version is the code you can see in the `canary` branch. The next release is based on that. you may see it as a temp fix tho.
