### ISSUE TITLE
[BUG] - Autocomplete Unhandled Runtime error

### ISSUE THREAD

**Issue by stefnto** [nextui-org/nextui#3057]
### NextUI Version

2.3.6

### Describe the bug

Running the Autocomplete example with the static item list https://codesandbox.io/p/devbox/funny-archimedes-ht3dtn?file=%2Fdata.js&utm_medium=sandpack in my project with next js 14.2.3 and the latest next ui version results in the error
Error: Functions are not valid as a child of Client Components. This may happen if you return children instead of <children /> from render. Or maybe you meant to call this function rather than return it.
  <... label=... placeholder=... className=... defaultItems=... children={function children}>

### Steps to Reproduce the Bug or Issue

Copying the code from the documentation results in the error stated above

### Expected behavior

I would expect it to show the autocomplete field as it is shown in the documentation

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
I couldn't see the error in sandbox. Can you double check?

**Comment by stefnto** [comment]
Error doesn't appear on sandbox.
The autocomplete uses the select component and I saw that for it to work the component that is used in should be declared as "use client". So I made my own component, declared it as client component and included the autocomplete in it and now the error is gone
