### ISSUE TITLE
[BUG] - Select

### ISSUE THREAD

**Issue by zMohammadz84** [nextui-org/nextui#3062]
### NextUI Version

2.3.6

### Describe the bug

When nothing is selected. The placeholder is not displayed . When using onChange .

### Steps to Reproduce the Bug or Issue

When nothing is selected. The placeholder is not displayed . When using onChange .

### Expected behavior

When the state associated with the select component is empty, the placeholder will be displayed, and when the user clicks on one of the select options and chooses, the placeholder will be hidden and what the user entered will be displayed.

### Operating System Version

Windows 11 Home  V-23H2

### Browser

Chrome

**Comment by wingkwong** [comment]
I couldn't reproduce the issue. Can you share some code / video for demonstrating the issue?

<img width="331" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/f899b950-25d5-4769-945e-c6478d0857fa">

**Comment by zMohammadz84** [comment]
![Screenshot 2024-05-23 151412](https://github.com/nextui-org/nextui/assets/91136164/4863f399-3e60-4d2e-a156-f1e7f7910f7e)
![image](https://github.com/nextui-org/nextui/assets/91136164/a3cc7849-626e-4fe8-90b7-a17ba1d3f11a)

**Comment by wingkwong** [comment]
I think it was due to `selectedKeys`. `filterBy` is probably empty which is not the correct key and results in rendering an empty value.

**Comment by zMohammadz84** [comment]
> I think it was due to `selectedKeys`. `filterBy` is probably empty which is not the correct key and results in rendering an empty value.


Yes, it is true that filterBy may be empty because the initial value is from searchParams. But the placeholder should be displayed when the state is empty. In the document itself, the placeholder is empty and is not displayed . Is there a solution ?

**Comment by ryo-manba** [comment]
For the controlled component, it seems that `state.selectedItems` becomes `[]` due to the following condition, which causes the `placeholder` not to be returned. 

https://github.com/nextui-org/nextui/blob/fa26ce02fd84b25fc29925c93462d15de542b847/packages/components/select/src/select.tsx#L78

I'll fix this. Thank you for reporting the issue!

**Comment by zMohammadz84** [comment]
You're welcome 
Thank You 🙏
