### ISSUE TITLE
[BUG] - Calendar

### ISSUE THREAD

**Issue by Sammy-coding** [nextui-org/nextui#3063]
### NextUI Version

2.0.6 next-ui-org/date-picker

### Describe the bug

When the locale is ar-SA, the calendar system that shows up is hijri which is **islamic-umalqura** but it switches on selecting month and year (in the showMonthAndYearPickers) to gregorian calendar system.

### Your Example Website or App

https://github.com/Sammy-coding/calendar

### Steps to Reproduce the Bug or Issue

click on the showMonthAndYearPickers
Observe the year and month before selection
then
Select month
Select Year
The month and year changes

### Expected behavior

As a user, i am expecting that the calendar system stays hijri which is **islamic-umalqura** but it changes back to gregorian.
<img width="295" alt="Screenshot 2024-05-23 at 12 43 16" src="https://github.com/nextui-org/nextui/assets/78555689/b8cdde95-3211-44a2-9d66-ad24f0e5d8ee">
<img width="295" alt="Screenshot 2024-05-23 at 12 43 16" src="https://github.com/nextui-org/nextui/assets/78555689/040af402-09fc-4cb3-a06c-0717eee6856b">

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Please follow the guide to setup `NextUIProvider` 

https://nextui.org/docs/guide/installation#provider-setup-1

**Comment by Sammy-coding** [comment]
Even after using the nextuiprovider, the issue still persist. The calendar still switches after selecting the year. It switches from the hijri calendar system to gregorian. It doesn't stay at hijri month and year.

**Comment by Sammy-coding** [comment]
Hi @wingkwong Is there a fix for this issue

**Comment by wingkwong** [comment]
@Sammy-coding I'm working on it.
