### ISSUE TITLE
A problem of Table component

### ISSUE THREAD

**Issue by shishikami** [nextui-org/nextui#3069]
Is there any approaches to stick a table column to the right side? Since the table component I wrote contains too many columns, I need to drag the scroll bar to reach the rightmost column each time. Though I could hide serveral columns to avoid the overflow of the content, but sticking a column seems to be a better solution( I guess?
Would anyone provide some ideas pls.

**Comment by shishikami** [comment]
> [ENG-884 A problem of Table component](https://linear.app/nextui-inc/issue/ENG-884/a-problem-of-table-component)

Hmm, it says I dont have access to the workplace..

**Comment by wingkwong** [comment]
@shishikami that link is for the team member. you can ignore that.

**Comment by alphaxek** [comment]
@shishikami you want a sticky table header?

**Comment by shishikami** [comment]
@alphaxek hmm, a sticky table column, including the table header.

**Comment by alphaxek** [comment]
Hi @shishikami,

you can try this for sticky header

```
 <Table
      isHeaderSticky
</Table>
```
and you can use `Pagination` to handle bulk data.

Explore this link:
https://nextui.org/docs/components/table#async-pagination

**Comment by GoulartNogueira** [comment]
Can we mark it as solved?

**Comment by shishikami** [comment]
![view](https://github.com/user-attachments/assets/29f38b2e-35ba-48a7-beca-5165d332e61e)
I apologize for taking up so much of your time. I actually wanted a sticky column as the picture shows. However, we solved this problem by displaying columns selectively. I'll mark this as solved. Thanks.

**Comment by gamersover** [comment]
@shishikami Would you like to share you solution here? Thanks.

**Comment by shishikami** [comment]
> @shishikami Would you like to share you solution here? Thanks.

最简陋的方案就是不要设置这么多的列，或者在初始渲染的时候少设置几个列，其余的列设置为可选项，由用户选择是否展示，最大程度的保证用户交互的时候不用来回拖动；

另外一种就是借鉴一下Element Plus里面Table固定列的操作，目前UI组件层面是没提供针对列的配置的，针对指定的列手动设置position: sticky和left: ..px或者right: ..px，这种代码侵入性稍微高一些，需要针对Table cell、Table header额外配置些样式来保证固定定位的元素呈现的界面是正确的的

比如这种的：
```ts
import {Table, TableHeader, TableColumn, TableBody, TableRow, TableCell, getKeyValue} from "@nextui-org/react";

const rows = [
  {
    key: "1",
    name: "Tony Reichert",
    role: "CEO",
    status: "Active",
    value: "Extra Content"
  },
  {
    key: "2",
    name: "原神",
    role: "开放世界冒险游戏",
    status: "启动",
    value: "Genshin"
  },
];

const columns = [
  {
    key: "key",
    label: "INDEX",
  },
  {
    key: "name",
    label: "NAME",
  },
  {
    key: "status",
    label: "STATUS",
  },
  {
    key: "role",
    label: "ROLE",
  },
  {
    key: "value",
    label: "EXTRA CONTENT"
  }
];

export default function App() {
  return (
    <Table aria-label="Example table with dynamic content">
      <TableHeader columns={columns}>
        {(column) => <TableColumn key={column.key} className={column.key === 'value' ? 'sticky right-0' : ''}>{column.label}</TableColumn>}
      </TableHeader>
      <TableBody items={rows}>
        {(item) => (
          <TableRow key={item.key}>
            {(columnKey) => <TableCell className={columnKey === 'value' ? 'sticky right-0 bg-[#18181B]' : ''}>{getKeyValue(item, columnKey)}</TableCell>}
          </TableRow>
        )}
      </TableBody>
    </Table>
  );
}
```
界面呈现大概是这样：
<img width="392" alt="截屏2024-10-25 14 10 16" src="https://github.com/user-attachments/assets/9f252ee6-6823-4f53-9223-eb5284067e9d">
写的比较简陋，领会精神（bushi
