### ISSUE TITLE
[BUG] - Image behave conflict with tailwind when using object-cover

### ISSUE THREAD

**Issue by undefine-man** [nextui-org/nextui#3074]
### NextUI Version

2.0.27

### Describe the bug

Image in NextUI can't use tailwind object-cover. 
I have to use 'removeWrapper' flag to make it behave properly.

### Steps to Reproduce the Bug or Issue

better see screenshots and videos

### Expected behavior

i expected it to support object-cover .

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/24623544/86387f39-3810-48c3-be2a-89d4a36d7ba7)
https://github.com/nextui-org/nextui/assets/24623544/e3ac04b7-c919-4707-a03b-b0843db652af

have to use removeWrapper flag to make it work properly.
![image](https://github.com/nextui-org/nextui/assets/24623544/509562f7-385a-4d43-b547-8ad416e8a0dd)

https://github.com/nextui-org/nextui/assets/24623544/d0446c1b-f3dc-4f1a-93fc-5cc4107c179e

### Operating System Version

Windows

### Browser

Edge

**Comment by wingkwong** [comment]
you can add the class to the wrapper using `classNames` props.

```
classNames={{wrapper: "object-cover"}}
```

**Comment by wingkwong** [comment]
do you mean you want to add `object-cover` to `<img />`?

**Comment by undefine-man** [comment]
> do you mean you want to add `object-cover` to `<img />`?

yes, i think it shoud be a basic property
