### ISSUE TITLE
[Feature Request] How to close modal programatically?

### ISSUE THREAD

**Issue by juliushuck** [nextui-org/nextui#3075]
### Is your feature request related to a problem? Please describe.

I want to close the modal after a network request. So the user clicks the submit button of the modal. I call a react-query mutation and onSuccess i want to close the modal, but the useDisclosure hook does not give me the function to close it.

I only get the 

```js
<ModalContent>
    {(onClose) => (
```
       
which only works inside the modal content.

### Describe the solution you'd like

The useDisclosure hook should return a close method with which i can programatically close the modal whenever i need.

### Describe alternatives you've considered

I could create a hidden button in the modal content and click it programatically to fire the onClose of modal content.

**Comment by vietan0** [comment]
I think `useDisclosure` actually does have a function, take a look at `@nextui-org\use-disclosure\dist\index.d.ts`:
```diff
declare function useDisclosure(props?: UseDisclosureProps): {
    isOpen: boolean;
    onOpen: () => void;
+   onClose: () => void;
    onOpenChange: () => void;
    isControlled: boolean;
    getButtonProps: (props?: any) => any;
    getDisclosureProps: (props?: any) => any;
};
```

**Comment by n-d-r-d-g** [comment]
I can confirm what @vietan0  mentioned. I'm currently using useDisclosure as follows:
```tsx
const { isOpen, onOpen, onClose} = useDisclosure()

return (
  <>
    <button onClick={onOpen}>Open modal</button>
    <Modal isOpen={isOpen} onClose={onClose}>...</Modal>
  </>
)
```

You can call `onOpen()` to programmatically open the modal.

**Comment by wingkwong** [comment]
Closing - answered above.
