### ISSUE TITLE
[BUG] - DateRangePicker is not possible to customize

### ISSUE THREAD

**Issue by Y-k-Y** [nextui-org/nextui#3091]
### NextUI Version

2.3.6

### Describe the bug

`DateRangePicker` has calendar slot and i need to change calendar css to customize as needed(Not only container of calendar but also child components of calendar such as color of selected day...) but it seems only container of calendar can be customized.
I've also tried using `classNames` of `calendarProps` but it didn't work as well.
```
<DateRangePicker
  popoverProps={{
    placement: 'top',
  }}
  calendarProps={{
    classNames: {
      base: 'bg-[#5F66A0]',
      cell: 'text-white',
    },
  }}
  classNames={{
    label: ['text-white font-bold'],
    inputWrapper: [
      'rounded-md',
      'border focus-within:border-active focus-within:hover:border-default-400',
      '!transition-colors',
    ],
    innerWrapper: ['text-white'],
    segment: ['!text-white'],
    calendar: 'bg-[#5F66A0]',
    calendarContent: 'text-white',
    popoverContent: 'text-white',
  }}
/>
```

### Steps to Reproduce the Bug or Issue

1. Install latest nextui
2. Try to customize calendar of `DateRangePicker`

### Expected behavior

Calendar components and its child components should be customizable.

### Operating System Version

Linux

### Browser

Chrome

**Comment by daniel-aziz** [comment]
Same Issue here
