### ISSUE TITLE
[BUG] - Maximum update depth exceeded on Autocomplete component

### ISSUE THREAD

**Issue by stefnto** [nextui-org/nextui#3094]
### NextUI Version

2.3.6

### Describe the bug

I have an Autocomplete Component 
```
     const [companyCountry, setCompanyCountry] = useState("");  
       <Autocomplete
          label={translations.country}
          labelPlacement="outside-left"
          placeholder={translations.country_placeholder}
          isRequired
          defaultItems={countries}
          selectedKey={companyCountry}
          // inputValue={companyCountry}
          onSelectionChange={setCompanyCountry}
          // onInputChange={setCompanyCountry}
          inputProps={{
            classNames: inputClasses
          }}
        >
          {(item) => <AutocompleteItem key={item.value}>{item.value}</AutocompleteItem>}
        </Autocomplete>
```
where countries is a list of objects with the key "value".
When an item is selected, if the dropdown menu is triggered from the arrow and all the items are displayed, if I select on a new item I get the error:
"Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops."
 with Call Stack :
"onSelectionChange
node_modules\@react-stately\combobox\dist\useComboBoxState.mjs (31:1)
onChangeCaller
node_modules\@react-stately\utils\dist\useControlledState.mjs (29:1)
Object.eval [as setSelectedKey]
node_modules\@react-stately\utils\dist\useControlledState.mjs (54:1)
setSelectedKey
node_modules\@nextui-org\autocomplete\dist\chunk-SYFYBWAI.mjs (173:13)"
If I remove the {item.value} child in the AutocompleteItem, the error goes away, but the country items are not displayed neither on the input nor the dropdown list.

### Steps to Reproduce the Bug or Issue

Click on the arrow of autocomplete item to toggle the dropdown list when an item is already selected and select a new item

### Expected behavior

I expected for just the new item value to be displayed

### Operating System Version

Windows

### Browser

Chrome

**Comment by 50Fifty** [comment]
Can confirm that this is still an issue in NextUI 2.4.1

**Comment by TheUntraceable** [comment]
I too am having this issue.

**Comment by wingkwong** [comment]
@TheUntraceable I don't see autocomplete component in your sandbox. Did you forget to save?
