### ISSUE TITLE
[BUG] - Custom state pseudo classes are changing

### ISSUE THREAD

**Issue by vavilondev** [nextui-org/nextui#3097]
### NextUI Version

2.3.6

### Describe the bug

```
Custom state pseudo classes are changing from ":--webkit-search-cancel-button" to ":state(webkit-search-cancel-button)" soon. See more here: https://github.com/w3c/csswg-drafts/issues/4805
```
I see that it is something related to nextui styling. How can I fix it?

### Steps to Reproduce the Bug or Issue

I have ran page analysis via https://pagespeed.web.dev/

### Expected behavior

As a user, I expect not to have that warning

### Screenshots or Videos

<img width="629" alt="Screenshot 2024-05-27 at 16 43 37" src="https://github.com/nextui-org/nextui/assets/84386678/3162f21b-a111-4814-ab5a-3ca69cdceedb">

### Operating System Version

- MacOS

### Browser

Chrome

**Comment by ryo-manba** [comment]
On which page did you run the analysis? It would also be helpful if you could provide a minimal reproduction of the issue, such as a StackBlitz link.

**Comment by wingkwong** [comment]
Closing - inactivity
