### ISSUE TITLE
[BUG] - React does not recognize the `disableAnimation` prop on a DOM element.

### ISSUE THREAD

**Issue by wingkwong** [nextui-org/nextui#3109]
### NextUI Version

2.4.0

### Describe the bug

React does not recognize the `disableAnimation` prop on a DOM element.

### Steps to Reproduce the Bug or Issue

create an avatar with image

### Expected behavior

no such error

### Operating System Version

macOS

### Browser

Chrome

**Comment by hsk-christian** [comment]
<img width="1977" alt="image" src="https://github.com/nextui-org/nextui/assets/17197000/08565c77-080a-4dac-b0b9-a85610e5def5">

**Comment by pot-code** [comment]
same here

**Comment by melodyxpot** [comment]
I got same issue.

![image](https://github.com/nextui-org/nextui/assets/53822027/e6056c26-3f7b-4e9b-a513-c600fe335a52)

**Comment by wingkwong** [comment]
@melodyxpot The fix will be available in the next bug fix release. You can use canary version as a temp fix if necessary.

**Comment by melodyxpot** [comment]
> @melodyxpot The fix will be available in the next bug fix release. You can use canary version as a temp fix if necessary.

Thanks

**Comment by rileybusche** [comment]
Seeing this also. Since this is just a "warning" Does this mean the component is still safe to use In a live sight? Functions as intended locally.

**Comment by melodyxpot** [comment]
> Seeing this also. Since this is just a "warning" Does this mean the component is still safe to use In a live sight? Functions as intended locally.

Seems so
