### ISSUE TITLE
[BUG] - Input clear not working with `isClearable` using formik and yup

### ISSUE THREAD

**Issue by srivatsa17** [nextui-org/nextui#3113]
### NextUI Version

2.4.0

### Describe the bug

I upgraded to the latest version of NextUI where I am using `Formik` and `yup` for input validation and I am using `Input` components `isClearable` to clear the input typed, but the button does nothing. I even tried adding `onClear` prop and setting the field value to `""` but that also did not help much. I am actually seeing this issue right from the release of NextUI 2.0

Is there anything i am missing out here ?

Here is my code.
```
<Formik
  validationSchema={schema}
  initialValues={initialFormData}
  onSubmit={(formData, { setSubmitting, resetForm }) => {
    # Perform other login
  }}
>
  {({
    handleBlur,
    handleSubmit,
    handleChange,
    setFieldValue,
    touched,
    errors,
    values,
    isValid,
    isSubmitting,
    dirty,
  }) => (
    <Form onSubmit={handleSubmit}>
      <Field
        as={Input}
        type="email"
        label="Email"
        name="email"
        onBlur={handleBlur}
        onChange={handleChange}
        isInvalid={touched.email && errors.email}
        isValid={touched.email && !errors.email}
        variant="flat"
        labelPlacement="outside"
        className="max-w-md"
        size="lg"
        autoComplete="off"
        errorMessage={touched.email && errors.email}
        color={
          touched.email ? (errors.email ? "danger" : "success") : "default"
        }
        startContent={<EmailIcon height={24} width={24} size={24} />}
        isClearable
        onClear={() => setFieldValue(values.email, "")}
        isReadOnly={isSubmitting}
        isRequired
      />
    </Form>
  )}
</Formik>;

```

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

On clicking the clear button, input field should be cleared.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/52497355/63f2d213-85ab-4766-9809-0429f14be638

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
please provide a minimal reproducible stackblitz example.

**Comment by wingkwong** [comment]
@srivatsa17 Formik holds the state internally so you need to update the value using `onClear`, otherwise the same value will be passing to NextUI component. I've seen you used `onClear` but you've passed the wrong field name. (p.s. `values.email` is the value of the current input).

Therefore, you just need to change like this

```diff
- onClear={() => setFieldValue(values.email, "")}
+ onClear={() => setFieldValue("email", "")}
```

**Comment by srivatsa17** [comment]
Got it, worked now. Thanks @wingkwong !
