### ISSUE TITLE
[BUG] - Error when running pnpm build

### ISSUE THREAD

**Issue by DiegoBM** [nextui-org/nextui#3120]
### NextUI Version

canary and 2.4.0

### Describe the bug

When trying to build a clean clone of the project from the current 'canary' branch, it fails on the spinner package with error:
```
The inferred type of 'useSpinner' cannot be named without a reference to '../../core/system-rsc/node_modules/tailwind-variants/dist'. This is likely not portable. A type annotation is necessary
```

Can also be reproduced with last release nextui--nextui-org-react-2.4.0

node version: `22.0.0`
pnpm version: `8.15.8`

### Steps to Reproduce the Bug or Issue

1. Clone the repository from the current canary
2. Install dependencies `pnpm i --hoist`
3. `pnpm build`

### Expected behavior

It should build without errors

### Operating System Version

macOs

### Browser

Chrome

**Comment by wingkwong** [comment]
I'm not able to reproduce (node: v20.12.2, pnpm: v8.15.4)

<img width="483" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/797cfb56-fd2b-41d9-abd8-c98b1166e436">

**Comment by DiegoBM** [comment]
I'm not doing anything particular as far as I'm aware, following exactly the instructions from the report:

<img width="1426" alt="Screenshot 2024-05-29 at 22 02 41" src="https://github.com/nextui-org/nextui/assets/1613216/12651454-3066-4f20-b5fe-84672150ea0f">

**Comment by DiegoBM** [comment]
It seems like the problem came from running pnpm through npx (`npx pnpm ...`), in particular when installing the modules. Installing pnpm globally and then running using that pnpm would solve the error. I do not know why though (comments are welcome), but at least it's solved.
