### ISSUE TITLE
[BUG] - enter or space not selecting item in dropdown

### ISSUE THREAD

**Issue by wingkwong** [nextui-org/nextui#3121]
### NextUI Version

2.4.0

### Describe the bug

when you focus on the DropdownItem (after pressing tab until it gets focused), and then press Enter or Space, it closes without selecting the item. it was working on v2.2.10.

### Steps to Reproduce the Bug or Issue

1. Go to a page that has Dropdown and other components
2. open dropdown, and focus on the first item
3. press space or enter
4. Nothing gets selected

```tsx
<Dropdown>
  <DropdownTrigger>
    <Button>Trigger</Button>
  </DropdownTrigger>
  <DropdownMenu aria-label="Actions" color={color} variant={variant}>
    <DropdownItem key="new" onPress={() => console.log("NOT WORKING WITH ENTER / SPACE")}>
      New file
    </DropdownItem>
    <DropdownItem key="copy">Copy link</DropdownItem>
    <DropdownItem key="edit">Edit file</DropdownItem>
    <DropdownItem key="delete" className="text-danger" color="danger">
      Delete file
    </DropdownItem>
  </DropdownMenu>
</Dropdown>
```

### Expected behavior

Pressing the keyboard "Enter" or "Space" should select the item.

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
@wingkwong also, pressing `escape` doesn't focus the trigger back

**Comment by wingkwong** [comment]
> pressing escape doesn't focus the trigger back

focus issue has been fixed in https://github.com/nextui-org/nextui/pull/3187
