### ISSUE TITLE
[BUG] - YOUR_ISSUE_TITLE_HERE_REPLACE_ME

### ISSUE THREAD

**Issue by ravindrakanapuram** [nextui-org/nextui#3127]
### NextUI Version

2.0.34

### Describe the bug

I encountered an error while trying to render a simple table using the @nextui-org/react Table component. The error message indicates that there is an unknown element <[object Object]> in the collection. This issue causes the component to fail rendering, and it throws the following error:
I am using npm

```
Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $788781baa30117fa$export$596e1b2e2cf93690 (import.mjs:722:18)
    at eval (import.mjs:769:165)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12600:19)
    ...
```
Steps to Reproduce:

Install the latest version of @nextui-org/react:
bash
Copy code
npm install @nextui-org/react
Create a simple React component using the Table component:
javascript
Copy code
import React from "react";
import { Table, TableHeader, TableColumn, TableBody, TableRow, TableCell } from "@nextui-org/react";

export default function SimpleTable() {
  return (
    <Table aria-label="Example static collection table">
      <TableHeader>
        <TableColumn>NAME</TableColumn>
        <TableColumn>ROLE</TableColumn>
        <TableColumn>STATUS</TableColumn>
      </TableHeader>
      <TableBody>
        <TableRow key="1">
          <TableCell>Tony Reichert</TableCell>
          <TableCell>CEO</TableCell>
          <TableCell>Active</TableCell>
        </TableRow>
        <TableRow key="2">
          <TableCell>Zoey Lang</TableCell>
          <TableCell>Technical Lead</TableCell>
          <TableCell>Paused</TableCell>
        </TableRow>
        <TableRow key="3">
          <TableCell>Jane Fisher</TableCell>
          <TableCell>Senior Developer</TableCell>
          <TableCell>Active</TableCell>
        </TableRow>
        <TableRow key="4">
          <TableCell>William Howard</TableCell>
          <TableCell>Community Manager</TableCell>
          <TableCell>Vacation</TableCell>
        </TableRow>
      </TableBody>
    </Table>
  );
}
Expected Behavior:
The table should render correctly with the provided data, displaying the names, roles, and statuses in a tabular format.

Environment:

@nextui-org/react: latest version (please specify the exact version if known)
React: 18.3.1
Next.js: 14.2.3
Node.js: v21.7.1

Possible Solutions or Workarounds:

Using a native HTML table works without issues, suggesting the problem is specific to the @nextui-org/react Table component.

### Steps to Reproduce the Bug or Issue

![image](https://github.com/nextui-org/nextui/assets/79123724/6be73b78-2f02-4b4e-84d5-c7ca6dd6a177)

### Expected behavior

![image](https://github.com/nextui-org/nextui/assets/79123724/aed8d294-f1ff-4609-b255-a685fd04b093)

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/79123724/d1edd478-cfc0-4621-8082-89c05edcce01)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
you need to add `use client;` directive at the top of your file. In latest version, we've included that by default.
