### ISSUE TITLE
[BUG] - DatePicker wrong width

### ISSUE THREAD

**Issue by matheusboeira** [nextui-org/nextui#3128]
### NextUI Version

2.4.0

### Describe the bug

When opening the date picker calendar, if using internationalization, the calendar width gets "flattened". However, this only happens when the "showMonthAndYearPickers" property is set.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-hlgmdv?file=src%2Fcomponents%2FProblemDatePicker.tsx,src%2Fcomponents%2FPages.tsx

### Steps to Reproduce the Bug or Issue

1. Set `locale="pt"` prop to NextUIProvider
2. Click the button to open the calendar in the date picker.

### Expected behavior

As a user, I expect the calendar not to be flattened like the English version.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/76896958/3456db90-ef37-4556-b55f-08f387ddf094

### Operating System Version

macOS

### Browser

Chrome

**Comment by matteogilioli** [comment]
Same problem with it localization

**Comment by ryo-manba** [comment]
How is the browser zoom set? There is a reported bug where the display breaks when it is not at 100%. In the environment you provided, the issue did not occur at 100% zoom.
See: https://github.com/nextui-org/nextui/issues/2978

**Comment by matheusboeira** [comment]
@ryo-manba, this happens regardless of zoom. 

https://github.com/nextui-org/nextui/assets/76896958/3526e34e-fad0-441b-9529-73a9d4b32d25

**Comment by aayush-goyal** [comment]
@matheusboeira the link you provided seems to work fine for me. Is there anything I am missing?
