### ISSUE TITLE
[BUG] - Navbar shouldHideOnScroll causes Navbar to vanish or get stuck

### ISSUE THREAD

**Issue by andyryan33** [nextui-org/nextui#3139]
### NextUI Version

2.4.0

### Describe the bug

After updating to 2.4.0, I am seeing the Navbar component with shouldHideOnScroll set to true resulting in the Navbar disappearing after a few scrolls going up & down. Or, if it doesn't disappear, it reverts to sticky behavior. This happens even on the NextUI component documentation page under the 'Hide on scroll' section. A page refresh brings it back.

### Steps to Reproduce the Bug or Issue

1- Go to https://nextui.org/docs/components/navbar#hide-on-scroll
2- Start scrolling up and down a few times
3- Navbar disappears or goes to sticky
4- Tested on Chrome, Edge, and both mobile/desktop. 

### Expected behavior

As a user, the Navbar should hide on scroll, but reappear right when I scroll back up, and should always be at the very top if I have not scrolled or if I returned the scroll all the way to the top. 

### Screenshots or Videos

![hideonscroll_issue](https://github.com/nextui-org/nextui/assets/57786066/a4270972-3683-445b-b014-bbe6c8c3a3d3)

https://github.com/nextui-org/nextui/assets/57786066/18b98aad-2921-473a-a817-9d7281a3b318

### Operating System Version

Windows 11, Android 14

### Browser

Chrome

**Comment by wingkwong** [comment]
preliminary findings:
- works fine in Mac with different browsers
- seems Windows problem

**Comment by And3rsonTorres** [comment]
- doesn't work on my mac (Monterey 12.7.5) or my iPhone safari.
- working fine in mac and Pixel 7a Chrome.

https://github.com/nextui-org/nextui/assets/106359275/da3c0ed9-8f98-406b-ac15-f90da6c2327c

**Comment by PaisWillie** [comment]
+1

**Comment by Aaron-Darklake** [comment]
+1

**Comment by brotodex** [comment]
+1

**Comment by haobarry** [comment]
same problem

**Comment by kevinmatr** [comment]
+1

**Comment by stixandstacks** [comment]
I'm encountering this issue in a Next14 app.  Works normally on my Windows PC in various browsers, but fails consistently on my iPhone on Chrome and Safari.  Safari on Macbook breaks also.

**Comment by ajayda24** [comment]
same problem

**Comment by janosgy** [comment]
I tried different versions, and they all have this issue
2.4.1
2.3.6
2.3.0

**Comment by DanielNoonan** [comment]
Next 14, @latest NextUI, Chrome on Mac - same problem. Can also confirm that the problem exists in the NextUI docs example. Scrolling around in the NextUI docs example for about 30 - 60 seconds and the navbar either disappears or becomes permanently sticky. A page refresh resets it.

**Comment by pratyush3124** [comment]
I have fixed this issue on #https://github.com/nextui-org/nextui/pull/3315 please review.

**Comment by yelwin-d3** [comment]
+1 ,doesn't work on my mac on Chrome

**Comment by wingkwong** [comment]
@yelwin-d3 This issue is still open and there's a PR under review. The fix should be available in the next bug fix release. I closed your issue because you just reported the same thing as this one. That's why I marked yours as duplicated. We just need one issue to keep track of the progress.

**Comment by TucciAlessandro** [comment]
Hi there guys, when will we have this fixed through next-cli? Thank you

**Comment by wingkwong** [comment]
Closing - fixed in above PR. The fix will be available in next bug fix release v.2.4.3.

@TucciAlessandro once we release, you will have the fix through `nextui-cli`.
