### ISSUE TITLE
[BUG] - Skeleton component causing child components to become unresponsive

### ISSUE THREAD

**Issue by bebbs-daronmont** [nextui-org/nextui#3141]
### NextUI Version

2.4.0

### Describe the bug

When using the skeleton component in the latest version, some, if not all, of the child components become unresponsive when `isLoaded = true` i.e. when the child components are visible and should be responsive. Could be related to Next.js.

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-9upckb?file=app%2Fpage.tsx

### Steps to Reproduce the Bug or Issue

1. Open the stackblitz link and wait for the page to compile and load
2. Try to click the button

### Expected behavior

The button should be clickable.

### Operating System Version

Windows 11, developing in WSL Ubuntu 22.04 LTS

### Browser

Edge

**Comment by wingkwong** [comment]
This issue has been fixed in latest version (v2.4.1).
