### ISSUE TITLE
[BUG] - Popover display wrong position (Doc)

### ISSUE THREAD

**Issue by pjatupon** [nextui-org/nextui#3143]
### NextUI Version

2.4.0

### Describe the bug

Popover display wrong position

https://github.com/nextui-org/nextui/assets/71364214/542fe3e4-9b10-4dc9-bc2c-7cab57bc7180

### Steps to Reproduce the Bug or Issue

Popover display wrong position

### Expected behavior

windows 11 
google chrome 125.0.6422.141

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/71364214/f174c636-40bb-4d00-8602-3ea0ba9c8b58

### Operating System Version

windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/2778
