### ISSUE TITLE
[BUG] - Date Picker value prop throws type error

### ISSUE THREAD

**Issue by kennyqiyenkan** [nextui-org/nextui#3148]
### NextUI Version

2.4.0

### Describe the bug

Currently using:
`"next": "^14.2.3"`
`"@internationalized/date": "^3.5.4"`

Also referred to a [previous Bug report](https://github.com/nextui-org/nextui/issues/3005) but I am already type casting the `useState`.

Code:
```tsx
import { DateValue, parseDate } from '@internationalized/date'
import { DatePicker } from '@nextui-org/date-picker'

const VendorBasicDetailsForm = (/*...*/) => {
  /*...*/
  const [foundedDate, setFoundedDate] = useState<DateValue>(
    parseDate(vendor.founded || '2024-01-01')
  )
  return (
    /*...*/
    <DatePicker
      value={foundedDate}
      onChange={setFoundedDate}
    />
    /*...*/
  )
}
```

Other things of note:
1. Running the application loads the component fine when running `yarn dev`
2. Running `yarn build` fails due to the error

### Steps to Reproduce the Bug or Issue

1. Install `NextUI` v2.4.0
2. Install `@internationalized/date` v3.5.4
3. Follow the instructions for controlled DatePicker

### Expected behavior

Not expecting type errors

### Screenshots or Videos

![Screenshot 2024-05-31 at 11 28 12 AM (2)](https://github.com/nextui-org/nextui/assets/6787784/7445578b-e6a8-454f-b63a-8ef009fe1b22)

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
looks like this `vendor.founded` could be `null` or `undefined`

**Comment by wingkwong** [comment]
sounds weird. can you setup a stackblitz project? I couldn't reproduce the issue on my side.

**Comment by kennyqiyenkan** [comment]
Okay, after some digging into `@internationalized/date` and the specific error I am encountering, it turns out that because I am using the latest version of the package (`3.5.4`), it conflicts with [NextUI's version of the package](https://github.com/nextui-org/nextui/blob/f3fdb7b6666e509f2c66504184a7fdfe6a011865/packages/core/system/package.json#L60). After downgrading the `@internationalized/date` package, the error goes away. Here is the [link to the discussion](https://github.com/adobe/react-spectrum/discussions/4987#discussioncomment-6899888). 

Maybe updating [the docs](https://nextui.org/docs/components/date-picker#time-zones) would suffice?

**Comment by wingkwong** [comment]
Thanks. I'll have a look tomorrow. 

p.s. next14 uses swc and it fails in stackblitz. we use codesandbox for next14 apps.
