### ISSUE TITLE
[BUG] - `Pagination` has disabled animation by default 

### ISSUE THREAD

**Issue by wolkyura** [nextui-org/nextui#3150]
### NextUI Version

2.4.0

### Describe the bug

After the last update, I noticed that `Pagination` has disabled animation by default. To enable it I can set `disableAnimation={false}` but I believe this change was introduced by mistake since the documentation says it is `false` by default - https://nextui.org/docs/components/pagination#api 

### Steps to Reproduce the Bug or Issue

1. Go to https://nextui.org/docs/comComponents/pagination#usage.
2. Change the cursor
3. See that the cursor changes without animation

### Expected behavior

I'd expect `disableAnimation`  to be `false` by default

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/54850073/0a868986-f1a5-4508-a3cc-caa5687f2128

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3144. Will be available in 2.4.2.
