### ISSUE TITLE
[BUG] Pagination left arrow shows page 1 on the first load

### ISSUE THREAD

**Issue by jimmyzzxhlh** [nextui-org/nextui#3151]
### NextUI Version

2.4.1

### Describe the bug

Pagination component is showing the left arrow button as page number 1.
This only happens for the first time when the page is loaded. If I click a different page, the left arrow will be displayed correctly. 

![image](https://github.com/nextui-org/nextui/assets/11505867/91f5c777-6797-42ce-9a48-5ecabbda96fe)

### Steps to Reproduce the Bug or Issue

I'm not able to reproduce this in Stackblitz using static data. What I'm doing is:
- Load data from a Graphql endpoint. 
- Calculate the number of pages needed based on the number of items loaded, and a `rowsPerPage` parameter:

```
  const [rowsPerPage, setRowsPerPage] = useState<number>(10);
  const [page, setPage] = useState<number>(1);

  const pages = useMemo(
    () => Math.ceil(items.length / rowsPerPage),
    [items.length, rowsPerPage]
  );
```

- Pass the page number to the Pagination component.

```
      <div className="py-2 px-2 flex items-center justify-center">
        <Pagination
          isCompact
          showControls
          showShadow
          color="primary"
          page={page}
          total={pages}
          onChange={(page) => setPage(page)}
        />
      </div>
```

### Expected behavior

Left arrow should be correctly displayed. 

### Operating System Version

macOS

### Browser

Chrome

**Comment by bietiaop** [comment]
I'm having the same problem.

**Comment by alphaxek** [comment]
Hi @jimmyzzxhlh ,

See if having `initialPage` helps
![image](https://github.com/nextui-org/nextui/assets/116849110/b74f26bd-18f6-42d0-85c6-88691c1a6053)

**Comment by bietiaop** [comment]
> Hi @jimmyzzxhlh ,
> 
> See if having `initialPage` helps ![image](https://private-user-images.githubusercontent.com/116849110/337884000-b74f26bd-18f6-42d0-85c6-88691c1a6053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTkwOTQsIm5iZiI6MTcxNzg1ODc5NCwicGF0aCI6Ii8xMTY4NDkxMTAvMzM3ODg0MDAwLWI3NGYyNmJkLTE4ZjYtNDJkMC04NWM2LTg4NjkxYzFhNjA1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNDU5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjc1YWMwOGQ1OWEyOWUwNzNhNTA3NTc3ZDk1YzgzYjdjZDRiMjIyNzA1ZDQ1Zjc1ZTlkM2Y5YjcwMTE4YzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IcPd8pV2o706WHxQ_uoVe3b2Ygc2EoPchyWQZ34SIes)

I've tried. It didn't work.

```tsx
  // other codes
  const [page, setPage] = React.useState(1);
  const pages = React.useMemo(() => {
    const pages = Math.ceil(sortedItems.length / rowsPerPage) || 1;
    return pages;
  }, [sortedItems.length, rowsPerPage]);
  const bottomContent = React.useMemo(() => {
    return (
      <div className="flex justify-end">
        <Pagination
          showControls
          showShadow
          color="primary"
          initialPage={1}
          page={page}
          total={pages}
          onChange={setPage}
        />
      </div>
    );
  }, [page, pages]);
  // other codes
```

**Comment by bietiaop** [comment]
> Hi @jimmyzzxhlh ,
> 
> See if having `initialPage` helps ![image](https://private-user-images.githubusercontent.com/116849110/337884000-b74f26bd-18f6-42d0-85c6-88691c1a6053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjA3MjMsIm5iZiI6MTcxNzg2MDQyMywicGF0aCI6Ii8xMTY4NDkxMTAvMzM3ODg0MDAwLWI3NGYyNmJkLTE4ZjYtNDJkMC04NWM2LTg4NjkxYzFhNjA1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNTI3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjQxOGE4NzIzYWFiMTQ2ZWQ5M2YxYTJkMjc1MmE2NjI2Njk5YWE1MDk1NDE0ZDZiN2FmZWZmYzNiM2VmMGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cqv-fbAgtQWWXujjSLyr_YamnMGMbcuwqLgGloAAR88)

My page implementation looks like this:
First there is a list storing the ids:

```tsx
const [list, setList] = React.useState<number[]>([]);
```

Then the custom component is rendered through the list (similar to the code below, possibly with some extra code for processing):

```tsx
// ... other code
const renderItem = (id: number) => {
  return <CustomComponent id={id} />
}

// ... other code
return (
  <div className="...">
    list.map(id=>{
      <div className="...">{renderItem(id)}</div>
    })
   </div>
)
```

In `CustomComponent` there are some `Tabs`:

```tsx
const CustomComponent: React.FC<{id: number}> = React.memo(({id}) => {
  const [active, setActive] = React.useState('edit');
  const tabs = [
    { key: 'edit', title: 'Edit', component: <EditPage id={id} /> },
    { key: 'team', title: 'Team', component: <TeamPage id={id} /> },
  ];
  if(someConditions) {
    tabs.push({ key: 'review', title: 'Review', component: <ReviewPage id={id} /> })
  }
  return (
    <div className="...">
      <div className="...">
        <Tabs
          aria-label="Options"
          selectedKey={active}
          onSelectionChange={(key) => {
            setActive(key as string);
          }}
        >
          {tabs?.map((tab) => <Tab key={tab.key} title={tab.title} />)}
        </Tabs>
      </div>
      <div className="...">
        {tabs?.map((tab) => (
          <div key={tab.key} className={active === tab.key ? '' : 'hidden'}>
            {tab.component}
          </div>
        ))}
      </div>
    </div>
  );
})
```

In `EditPage`, `TeamPage`, etc., the data is fetched and presented in a table, which refers to the `Use Case Example` on the NextUI docs. The content includes the pagination component code mentioned in the last comment, the active cursor “1” jumps to the “previous page” position.

**Comment by alphaxek** [comment]
@jimmyzzxhlh I tried reproducing the issue but I couldn't reproduce, do you have any sandbox link with minimal code to play around with and see what the issue is

**Comment by jorgerojas26** [comment]
Exact same issue here

**Comment by alphaxek** [comment]
Hi @jorgerojas26 can you please share the minimal code to reproduce the issue

**Comment by bietiaop** [comment]
> Hi @jorgerojas26 can you please share the minimal code to reproduce the issue嗨，您能否分享最小代码以重现该问题

[https://codesandbox.io/p/devbox/vsw923?migrateFrom=q2h7q8](https://codesandbox.io/p/devbox/vsw923?migrateFrom=q2h7q8)

**Comment by bietiaop** [comment]
> Hi @jorgerojas26 can you please share the minimal code to reproduce the issue

Sandbox link:
[https://codesandbox.io/p/devbox/vsw923?migrateFrom=q2h7q8](https://codesandbox.io/p/devbox/vsw923?migrateFrom=q2h7q8)

**Comment by jimmyzzxhlh** [comment]
@bietiaop Thank you, this is exactly what I'm seeing.

**Comment by arindam1997007** [comment]
hi @wingkwong . Can I work on this bug?

**Comment by wingkwong** [comment]
@arindam1997007 go ahead.

**Comment by arindam1997007** [comment]
Hi @jimmyzzxhlh 

Could you please confirm if you are hiding the pagination component using `display:none` until the data is loaded from the GraphQL endpoint?

Hi @bietiaop 

For the timebeing, can you verify once, if instead of hiding the inactive tab using `display:none`, you don't re-render it. 
Perhaps something like this?

```javascript
const activeTab = tabs?.find((tab) => tab.key === active);

return <div>
...
 {activeTab && <div key={activeTab.key}>{activeTab.component}</div>}
</div>
```

**Comment by bietiaop** [comment]
> Hi @jimmyzzxhlh
> 
> Could you please confirm if you are hiding the pagination component using `display:none` until the data is loaded from the GraphQL endpoint?
> 
> Hi @bietiaop
> 
> For the timebeing, can you verify once, if instead of hiding the inactive tab using `display:none`, you don't re-render it. Perhaps something like this?
> 
> ```js
> const activeTab = tabs?.find((tab) => tab.key === active);
> 
> return <div>
> ...
>  {activeTab && <div key={activeTab.key}>{activeTab.component}</div>}
> </div>
> ```

That's what I was trying to use `display:none` to avoid re-rendering. Re-rendering of these components can lead to pointless duplicate requests.

**Comment by d3rd4nnyLABS** [comment]
@wingkwong @arindam1997007 Are you still working on  the open pull request? The pull request seems to only fail the "Authorization required to deploy" check. The Bug is currently blocking us a bit. If this can be resolved, it would be awesome!

**Comment by wingkwong** [comment]
@d3rd4nnyLABS I'll take a look tonight

**Comment by arindam1997007** [comment]
> @wingkwong @arindam1997007 Are you still working on  the open pull request? The pull request seems to only fail the "Authorization required to deploy" check. The Bug is currently blocking us a bit. If this can be resolved, it would be awesome! 

Hey. It's under review as of now. I will fix any reviews if it comes and then @wingkwong will help with the merging.

**Comment by HickAndrade** [comment]
Hello everyone,

I initially encountered the same problem. After updating the UI library, the component started to render like this:

![image](https://github.com/user-attachments/assets/83f5a7db-966a-42e6-b609-fd79e96f7542)

My temporary solution was to trigger a page switch, because it always returned to normal when I selected another page and then went back to the first one. (I like this library, even though it isn't receiving the attention it deserves).

Here is a simple example using useEffect:

```
const rowsPerPage: number = 5;

  const pages = Math.ceil(listar.length / rowsPerPage);

  const items = useMemo(() => {
    const start = (page - 1) * rowsPerPage;
    const end = start + rowsPerPage;
    return listar.slice(start, end);
  }, [page, listar]);
  
   useEffect(() => {
    if (pages > 1) {
      setPage(2);
      setTimeout(() => setPage(1), 0);
    }
  }, [pages]);

```
I hope this helps.

**Comment by stefnto** [comment]
Having the same issue, but passing false to the the showControls prop solves the issue, so probably the problem lies there.

**Comment by bietiaop** [comment]
@wingkwong Is this issue not fixed yet?

**Comment by wingkwong** [comment]
@bietiaop no. the pr requires changes.

**Comment by bietiaop** [comment]
> @bietiaop no. the pr requires changes.

ok

**Comment by Marcin-Palubinski** [comment]
```jsx
    <Pagination
      loop
      showControls
      total={total}

      page={page > total ? total : page}

      onChange={setPage}
    />
```

My `total` is also based on items.length.
Adding condition and fallback to `page` parameter fixed all isues with first render.

**Comment by AntoineArt** [comment]
> ```js
>     <Pagination
>       loop
>       showControls
>       total={total}
> 
>       page={page > total ? total : page}
> 
>       onChange={setPage}
>     />
> ```
> 
> My `total` is also based on items.length. Adding condition and fallback to `page` parameter fixed all isues with first render.

Thx for the workaround, it works for me
