### ISSUE TITLE
[BUG] Issue in renderSelectedItem when selectedItem is a String in Select

### ISSUE THREAD

**Issue by BIhab** [nextui-org/nextui#3152]
**NextUI Version**

2.4.0

**Describe the bug**

https://github.com/nextui-org/nextui/blob/be29da10978a9569f2845fc04e46d47540a58f0b/packages/components/select/src/select.tsx#L94

As a side effect of this line in the code, when you have a String that has  2 letters or more, the render Selected Item will show two items or more depending on the length of the string separated by a comma, example:

key = "19" , the output of the line highlighted will be "1,9".

**Steps to Reproduce the Bug or Issue**

    Create a Select Component with selectionMode = "single" and add an onChange function.
    
**Expected behavior**

Show the textValue of the selectedItem without spliting the key.

**Screenshots or Videos**

![Capture d’écran du 2024-06-01 00-53-26](https://github.com/nextui-org/nextui/assets/33871976/1e7e69bb-60f3-4f60-9165-a73be9037d60)

![Capture d’écran du 2024-06-01 00-55-59](https://github.com/nextui-org/nextui/assets/33871976/f5f945c6-c0a0-4066-b0c7-adaa4decf901)

**Operating System Version**

Ubuntu 22.04 LTS

**Browser**

Firefox, Chrome, Brave

**Comment by wingkwong** [comment]
@BIhab I couldn't reproduce the issue based on your description. Can you share your code?

**Comment by BIhab** [comment]
> @BIhab I couldn't reproduce the issue based on your description. Can you share your code?

@wingkwong Thanks for your response, here you'll find a reproducible environment, you can check the products key on the data file, and check "Coffee" in the select.

https://codesandbox.io/p/devbox/ljm9hm?migrateFrom=9hqpmq&embed=1&file=%2FApp.jsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx1ejk4p00062869yu0k9gq3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx1ejk4p000228697tgzitdb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx1ejk4p000428699lpt00wo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx1ejk4p00052869bknrys9j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx1ejk4p000228697tgzitdb%2522%253A%257B%2522id%2522%253A%2522clx1ejk4p000228697tgzitdb%2522%252C%2522activeTabId%2522%253A%2522clx1fv9ot02aq2869naiym713%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx1ejk4p00012869mocqimg6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522endLineNumber%2522%253A14%252C%2522startColumn%2522%253A7%252C%2522endColumn%2522%253A100000006%257D%255D%252C%2522id%2522%253A%2522clx1f9i4800td2869u5wx8x8e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.jsx%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522endLineNumber%2522%253A16%252C%2522startColumn%2522%253A10%252C%2522endColumn%2522%253A100000009%257D%255D%252C%2522id%2522%253A%2522clx1fv9ot02aq2869naiym713%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clx1ejk4p00052869bknrys9j%2522%253A%257B%2522id%2522%253A%2522clx1ejk4p00052869bknrys9j%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5176%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clx1gmynh00oc2869pmut70gy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx1gmynh00oc2869pmut70gy%2522%257D%252C%2522clx1ejk4p000428699lpt00wo%2522%253A%257B%2522id%2522%253A%2522clx1ejk4p000428699lpt00wo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx1ejk4p00032869zo1ktsgz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clx1ejl81000adaf8h3jwadko%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clx1ejt3q005u28690fhtbu7p%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx1ejt3q005u28690fhtbu7p%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by wingkwong** [comment]
Thank you. I can see the issue now. Will take a look.

**Comment by wingkwong** [comment]
@BIhab after digging the code, I think the issue is not from our side and it is caused by the incorrect usage. Here's the correction.

```diff
- const [selectedKey, setSelectedKey] = useState("1");
+ const [selectedKey, setSelectedKey] = React.useState(new Set(["1"]));
```

```diff
- setSelectedKey(value);
+ setSelectedKey(new Set(event.target.value.split(",")));
```

You may also look at the examples in the [doc](https://nextui.org/docs/components/select).

**Comment by BIhab** [comment]
@wingkwong Sorry to bother you, but I think there is a misunderstanding, the objectif is not to show a multi select, it's just a single select, but when you shoud "Coffee" which key is 12, the Select show "Bread,Water", which have key: "1" and "2".
```js
export const products = [
  { key: 1, label: "Bread" },
  { key: 2, label: "Water" },
  { key: 12, label: "Coffee" },
];
```
It should show "Coffee" on the select Placeholder not "Bread,Water".
What it really does is that he took the Key : 12, map it which result for an item to be a single char ( [1,2]), join them by a comma which result for : 1,2 and show the respective label foreach key which result for: Bread,Water

**Comment by wingkwong** [comment]
Have you tried the above modification? I could see it's `Coffee` instead of `Bread,Water` with my change.
