### ISSUE TITLE
[BUG] - Input Component has a focus bug - bad UX

### ISSUE THREAD

**Issue by Multinite** [nextui-org/nextui#3154]
### NextUI Version

^2.4.1

### Describe the bug

When focused into an <Input /> component, the border color changes to primary - as expected.
The moment you click on the Input's border, or label (label placement is `inside`), the focus blur, and re-enter, causing the border & lebel color to flicker back from primary to default, and back to primary.
I'm unsure if this applys to other variants of the input component, but I do know it occurs on the `bordered` one.
If it's possible to somehow make the other elements within the input become `pointer-events-none` to stop the focus blur?

### Steps to Reproduce the Bug or Issue

* Create a new <Input /> component
* Make the input use `bordered` variant
* click within the input to focus it.
* click either the border around the input, or the label itself and it will blur, then refocus, causing the UI to flicker in colors.

### Expected behavior

Upon clicking the border or label, no color changes in the UI should happen, no flickering.
It should remain focused within the input.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/145994855/f29eaa95-9e9d-4ac2-8dd8-cd8ed19168cb

### Operating System Version

macOS

### Browser

Chrome

**Comment by sjoerdvanBommel** [comment]
Regarding the label: this is the current behaviour of the underlying react aria library: https://react-spectrum.adobe.com/react-aria/useTextField.html

**Comment by ryo-manba** [comment]
Thanks for the issue! It is not clear that clicking the label will focus the input. So, it seems normal for the input to be refocused each time the label is clicked. As for the border, I think it would be better to fix the issue.
