### ISSUE TITLE
[BUG] - Autocomplete `onSelectionChange` has the wrong arg type

### ISSUE THREAD

**Issue by simPod** [nextui-org/nextui#3163]
### NextUI Version

v2.1.1

### Describe the bug

Autocomplete onSelectionChange has the wrong arg type. It can also be null when Autocomplete is cleared.

### Steps to Reproduce the Bug or Issue

1. click on "clear" button in Autocomplete component.

### Expected behavior

It should be

`onSelectionChange?: (key: Key|null) => void`

### Operating System Version

macos

### Browser

Chrome

**Comment by wingkwong** [comment]
`onSelectionChange` is from `react-aria` side.

**Comment by simPod** [comment]
How is react-aria related to nextui? I mean how do you guarantee it does
not break nextui? The type was correct in previous nextui version.
