### ISSUE TITLE
[BUG] - Copy paste error in sample Tooltip usage

### ISSUE THREAD

**Issue by grubyak** [nextui-org/nextui#3166]
### NextUI Version

2.41

### Describe the bug

copy paste error in sample code:

<img width="742" alt="screen-shot 2024-06-02 at 12 37 03" src="https://github.com/nextui-org/nextui/assets/1628646/8693cbf1-5f16-43ef-b693-b4dbfc673342">

### Steps to Reproduce the Bug or Issue

1. go to https://nextui.org/docs/components/tooltip#placements
2. click 'code'
3. click 'show more'

### Expected behavior

```
key={key}
placement={placement}
content={content}
```

### Operating System Version

all

### Browser

Chrome

**Comment by wingkwong** [comment]
I don't see there is any issue. we do use `placement` for `key` and `content` for the demonstration.
