### ISSUE TITLE
[BUG] - the prop isKeyboardDismissDisabled it doesn't work in popover

### ISSUE THREAD

**Issue by miguel-esserweb** [nextui-org/nextui#3171]
### NextUI Version

2.4.1

### Describe the bug

Adding the prop isKeyboardDismissDisabled={true} on the <Popover> component does not close the popover with ESC key.

### Steps to Reproduce the Bug or Issue

```import React from "react";
import {Popover, PopoverTrigger, PopoverContent, Button} from "@nextui-org/react";

export default function App() {
  return (
    <Popover placement="right" isKeyboardDismissDisabled={true}>
      <PopoverTrigger>
        <Button>Open Popover</Button>
      </PopoverTrigger>
      <PopoverContent>
        <div className="px-1 py-2">
          <div className="text-small font-bold">Popover Content</div>
          <div className="text-tiny">This is the popover content</div>
        </div>
      </PopoverContent>
    </Popover>
  );
}
```

### Expected behavior

It should be closed with the ESC key as well as the Modal component.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
preliminary findings:
- focus is on button while it should be in content
- if the focus is on content, then `isKeyboardDismissDisabled` works as expected
