### ISSUE TITLE
It is not possible to change the calendar display on a mobile

### ISSUE THREAD

**Issue by zhukovskayams** [nextui-org/nextui#3173]
### NextUI Version

2.4.0

### Describe the bug

It is not possible to change the calendar display on a mobile phone. it should be possible to display one by one as a column

<img width="539" alt="Снимок экрана 2024-06-04 в 13 49 57" src="https://github.com/nextui-org/nextui/assets/72203488/8c1220bb-c4ed-4f12-b170-794e3c12d7b6">
<img width="491" alt="image" src="https://github.com/nextui-org/nextui/assets/72203488/614b8ce2-fa21-4695-a31d-325c52b16598">

### Steps to Reproduce the Bug or Issue

1) add DateRangePicker with 2 visibleMonths to the page
2) switch to mobile mode
3) open calndar

### Expected behavior

calendars displayed one by one as column, no scrollbars
<img width="572" alt="Снимок экрана 2024-06-04 в 13 55 17" src="https://github.com/nextui-org/nextui/assets/72203488/92321862-ee3b-469f-88e4-fd0f51d27321">

### Operating System Version

macOs

### Browser

Chrome

**Comment by pratyush3124** [comment]
The way it is currently is all the 3 headers are in a div and all the 3 calenders are in another div. (visibleMonths={3}).

I can put individual header-calender pair in a div and then make the parent responsive? using breakpoints?

![image](https://github.com/nextui-org/nextui/assets/44525862/5c21f859-29f7-4ccd-8d10-c1f17dadcc72)
