### ISSUE TITLE
[BUG] - Wrong hover on table with Tooltip

### ISSUE THREAD

**Issue by matteogilioli** [nextui-org/nextui#3176]
### NextUI Version

2.4.1

### Describe the bug

When I hover over a button with tooltip on a table the rows selected by the hover are wrong, the previous rows remain in addition to the one previously selected

### Your Example Website or App

https://codesandbox.io/p/sandbox/wizardly-violet-2lgr8q

### Steps to Reproduce the Bug or Issue

1. Create a table with buttons and tooltips
2. Add a selectionMode to the table
3. Hover the mouse over the buttons with tooltips

### Expected behavior

I expect that the row selected by the hover is just the one with the mouse over it

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/55749040/41178fab-6e28-4328-90e8-e50d27cbdaf0

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/3002
