### ISSUE TITLE
[BUG] - Autocomplete

### ISSUE THREAD

**Issue by zulkiflikursani** [nextui-org/nextui#3179]
### NextUI Version

2.4.0

### Describe the bug

Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

ON $458b0a5536c1a7cf$export$40bfa8c7b0832715/setValue<

![image](https://github.com/nextui-org/nextui/assets/69183966/9cfbd92c-27ef-45b3-81e7-07cc8edfd838)

<Autocomplete
        defaultItems={data}
        label={props.label}
        placeholder="Select a user"
        labelPlacement="inside"
        name={props.name}
        defaultInputValue={props.value}
      >
        {(item) => (
          <AutocompleteItem
            key={item.kode_akun_header}
            textValue={item.kode_akun_header}
          >
            <div className="flex space-x-1">
              <span>{item.kode_akun_header}</span> <span>:</span>
              <span>{item.nama_akun_header}</span>
            </div>
          </AutocompleteItem>
        )}
      </Autocomplete>

### Your Example Website or App

https://github.com/zulkiflikursani/findHydroPro

### Steps to Reproduce the Bug or Issue

1 got to akun menu
2 edit some akun 
3 change kode header without clear value it will get this error

"Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
"

### Expected behavior

Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/69183966/f7ef1a36-4e81-407e-8dcb-22ca11854353)

### Operating System Version

macOs

### Browser

Firefox

**Comment by wingkwong** [comment]
this has been fixed already and the fix will be available in the next release (v2.4.2). At the same time, you may use the canary patch.

```
"@nextui-org/autocomplete": "0.0.0-canary-20240604122531"
```
