### ISSUE TITLE
[BUG] - Select Component Doesn't Change Color with Dark Theme

### ISSUE THREAD

**Issue by a-Marino** [nextui-org/nextui#3180]
### NextUI Version

2.0.10

### Describe the bug

I've encountered an issue with the Select component when using the dark theme. The dropdown box for items doesn't change its color according to the dark theme settings, resulting in poor visibility and user experience.

All the other Inputs are right, it only happens with Select.

### Your Example Website or App

https://github.com/a-Marino/gymSys

### Steps to Reproduce the Bug or Issue

1.Set up a Next UI project.
2.Apply the dark theme.
3.Add a Select component with a few options.
4.Open the dropdown to view the options.

### Expected behavior

The dropdown box for the Select component should adapt to the dark theme, changing its background and text color to fit the dark theme settings.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/70865138/119b39b9-06f3-429f-8320-f00f6955f1e8)
![image](https://github.com/nextui-org/nextui/assets/70865138/b042b7e7-184a-41a1-9c9a-189bf49e419b)
![image](https://github.com/nextui-org/nextui/assets/70865138/55de87b5-0ae1-4f62-a054-6a6c823f2e4d)
![image](https://github.com/nextui-org/nextui/assets/70865138/bda2a2db-5ca5-49b6-9cd1-a07866aa89c0)

### Operating System Version

Windows

### Browser

Other (add additonal context)

**Comment by wingkwong** [comment]
please provide a minimal reproducible example instead. Your provided repo needs extra setup.

**Comment by ShahirZain** [comment]
provided repo is not working, please provided the working code

**Comment by alphaxek** [comment]
Hi @a-Marino,

Try below
![image](https://github.com/nextui-org/nextui/assets/116849110/1e7b370d-1447-4dce-88fd-7d3cc10f6aa2)

**Comment by a-Marino** [comment]
Thanks @alphaxek.
I fixed it adding a default theme in the configs.

**Comment by alphaxek** [comment]
great

**Comment by Vallerian** [comment]
It is not possible to apply the `dark` class to the `Select` component by assigning the `dark` class to the `className`. You need to give the `dark` class to the `popoverContent`.

```tsx
classNames={{
  popoverContent: "dark",
}}
```
