### ISSUE TITLE
[BUG] - React does not recognize the disableAnimation | isIndeterminate | isSelected prop on a DOM element.

### ISSUE THREAD

**Issue by armandtht** [nextui-org/nextui#3184]
### NextUI Version

2.4.1

### Describe the bug

React does not recognize the `disableAnimation` | `isIndeterminate` | `isSelected` prop on a DOM element.

### Steps to Reproduce the Bug or Issue

create a checkbox with a custom icon. 

### Expected behavior

no such error

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/136462994/bde1e8b9-81e8-4bba-b1d3-f8b8c47e389d)
![image](https://github.com/nextui-org/nextui/assets/136462994/951dbc6c-01fb-4c2f-90e1-3f50a131e49f)
![image](https://github.com/nextui-org/nextui/assets/136462994/04dee508-c10e-4c31-8fba-d463a35e4fe2)

### Operating System Version

MacOS & Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
please share some code

**Comment by armandtht** [comment]
Here it is 

the checkbox: 
![Screenshot 2024-06-05 120422](https://github.com/nextui-org/nextui/assets/136462994/bdeb085e-826d-4f1f-8066-ab84b18b612a)

and its custom icon (followed same logic as custom check icon in documentation)  
![Screenshot 2024-06-05 120300](https://github.com/nextui-org/nextui/assets/136462994/dcdac31f-983f-431a-a86f-6df449cdcbc0)

**Comment by wingkwong** [comment]
1. please paste the code here instead of sharing screenshots so that i could copy and paste to my local to test. 
2. If I just look at the screenshot, those props, namely `disableAnimation`, `isIndeterminate`, `isSelected`, should not be passed to `motion.svg`, which causes the warning you see. You can use `filterDOMProps` from `@nextui-org/react-utils` to filter out all the non-DOM props.

**Comment by armandtht** [comment]
Here is a simplified exemple of the error

`import React from "react"
import { Checkbox } from "@nextui-org/checkbox"

import { HeartIcon } from "./HeartIcon"

export default function CheckboxTest() {
  return (
    <div className="flex gap-4">
      <Checkbox defaultSelected icon={<HeartIcon />}>
        Option
      </Checkbox>
    </div>
  )
}
`

And 

`import React, { SVGProps } from "react"

interface HeartIconProps extends SVGProps<SVGSVGElement> {
  filled?: boolean
  size?: number
  height?: number
  width?: number
  label?: string
}

export const HeartIcon: React.FC<HeartIconProps> = ({
  filled,
  size,
  height,
  width,
  label,
  ...props
}) => {
  return (
    <svg
      width={size || width || 24}
      height={size || height || 24}
      viewBox="0 0 24 24"
      fill="fill"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M12.62 20.81c-.34.12-.9.12-1.24 0C8.48 19.82 2 15.69 2 8.69 2 5.6 4.49 3.1 7.56 3.1c1.82 0 3.43.88 4.44 2.24a5.53 5.53 0 0 1 4.44-2.24C19.51 3.1 22 5.6 22 8.69c0 7-6.48 11.13-9.38 12.12Z"
        fill="currentColor"
      />
    </svg>
  )
}
`

As you can see, it's the same logic as the documentation, and the errors still trigger

**Comment by wingkwong** [comment]
After digging the code, i think those 3 props are required to pass to icon since they can be used in custom icon and we cant detect whether they will be used or not. Therefore, if you don't need those props, you don't need to pass to your svg. I'll update the docs a bit.
