### ISSUE TITLE
[BUG] - Autocomplete Filtering isn't working

### ISSUE THREAD

**Issue by TheUntraceable** [nextui-org/nextui#3192]
### NextUI Version

"@nextui-org/autocomplete": "0.0.0-canary-20240604122531"

### Describe the bug

When you start typing into an Autocomplete, the options aren't filtered. 

### Your Example Website or App

[![Edit TheUntraceable/next-app-template/main](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/TheUntraceable/next-app-template/main?embed=1&file=%2Fapp%2Fpage.tsx&import=true)

### Steps to Reproduce the Bug or Issue

1. Click on the autocomplete
2. Start typing

### Expected behavior

I expect the autocomplete items to be filtered out, as visible in the demo on the nextui.org website.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
1. Your codesandbox doesn't have autocomplete
2. I couldn't reproduce on canary branch
![image](https://github.com/nextui-org/nextui/assets/35857179/b3cb1dc5-2400-4298-a856-f52f2b57df1f)

**Comment by TheUntraceable** [comment]
![image](https://github.com/nextui-org/nextui/assets/73362400/8eb1eb9c-f112-4d69-94aa-a59acf4016ba)
Hmm, not sure what I'm doing wrong. I can see the code in the Codesandbox. Here is the [code](https://gist.github.com/TheUntraceable/f6d9c85770fe3b03151767e3de538522). 

https://github.com/nextui-org/nextui/assets/73362400/9087a38f-0248-4b74-8ecd-8fdc833b2b8f

**Comment by alphaxek** [comment]
Hi @TheUntraceable,

Try replacing `items={items}` with `defaultItems={items}`

Test:
![autocomtest](https://github.com/nextui-org/nextui/assets/116849110/63f94508-672c-44f5-97b1-5d451a224bfd)

**Comment by TheUntraceable** [comment]
That *does* seem to work, but is that the intended usage of the `defaultItems` props?

**Comment by wingkwong** [comment]
>  By default, Autocomplete uses a "contains" function from [useFilter](https://react-spectrum.adobe.com/react-aria/useFilter.html) to filter the list of options. This can be overridden using the defaultFilter prop, or by using the items prop to control the filtered list. When items is provided rather than defaultItems, Autocomplete does no filtering of its own.

See https://nextui.org/docs/components/autocomplete#custom-filtering

**Comment by TheUntraceable** [comment]
Thank you!
