### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by alarv** [nextui-org/nextui#3197]
### NextUI Version

2.4.1

### Describe the bug

When I create a tabs component with href after following the guide on how to set up routing (with NextUIProvider inside the body wrapping the {children}) I get an error as in the title:
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
Call Stack
startsWith
../src/shared/lib/router/utils/add-path-prefix.ts
path
../src/client/add-base-path.ts
href
../src/client/components/app-router.tsx
navigate
../src/client/components/app-router.tsx
```

It seems to happen on nested child elements, cause when I tried it on stackblitz on the app/page.tsx component it seemed to work. 

cc @wingkwong created a new issue as requested here: https://github.com/nextui-org/nextui/issues/2934

### Your Example Website or App

https://codesandbox.io/p/devbox/zen-moore-knpyrs

### Steps to Reproduce the Bug or Issue

1. Go to https://knpyrs-3000.csb.app/dashboard/tabs
2. Click on any tab
3. An error is thrown by nextjs

### Expected behavior

As a user I expected the tab to redirect to another tab, but instead an error was thrown. 

### Operating System Version

Linux

### Browser

Chrome

**Comment by wingkwong** [comment]
i copied the same dependencies on my next app but somehow it works fine. Need to dig.

**Comment by alarv** [comment]
> i copied the same dependencies on my next app but somehow it works fine. Need to dig.

If it helps on the codesandbox, when I switched to npm it stopped working (I also use npm on my project), with pnpm it looked fine

**Comment by wingkwong** [comment]
@alarv I also found that this weird behaviour. The `path` in `navigate` is `undefined` when I use npm.

**Comment by trival** [comment]
I am seeing the exact same think. Using npm, @nextui-org/react@2.4.1, next@14.2.4. 

With empty `Tab` and `href` attribute, the `navigate` function is called with `undefined` as path parameter. Using the `Link` component instead in the same location works fine.

**Comment by trescomasdev** [comment]
I had the same issue, but updating @nextui-org/system, @nextui-org/react and @nextui-org/link to the latest version and import the NextUIProvider from the @nextui-org/system package resolved the issue.
Just to make sure I deleted the node_modules folder after the updates and installed everything again and now the Link are working.

**Comment by NikhilDogra11** [comment]
> I had the same issue, but updating @nextui-org/system, @nextui-org/react and @nextui-org/link to the latest version and import the NextUIProvider from the @nextui-org/system package resolved the issue. Just to make sure I deleted the node_modules folder after the updates and installed everything again and now the Link are working.

@trescomasdev there is no issue with link components, the major problem is with tab components. Tab component still giving error in newer version.

**Comment by dwissaaj** [comment]
Hei Any solve for this issue? I also get this problem
