### ISSUE TITLE
[BUG] - Modal is not focus trapping when navigating using a keyboard

### ISSUE THREAD

**Issue by kennyqiyenkan** [nextui-org/nextui#3204]
### NextUI Version

v2.4.1

### Describe the bug

Opening a modal does not trap the focus within its contents when navigating using a keyboard (when it should according to the [docs](https://nextui.org/docs/components/modal#accessibility)).

Context: Came across the issue on my application and it was reproducible on NextUI documentation site.

### Steps to Reproduce the Bug or Issue

1. Navigate to the [Usage](https://nextui.org/docs/components/modal#usage) section of the Modal documentation
2. Open the example model using the keyboard
3. Tab through the options in modal
4. Able to focus on elements outside the modal

### Expected behavior

When tabbing through the modal, it should loop back to the first interactable element in the modal.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/6787784/65714d29-159f-4ed5-bfc4-95fa98203205

### Operating System Version

macOS

### Browser

Chrome

**Comment by chirokas** [comment]
@wingkwong :
This seems to be caused by the `disableFocusManagement` prop ([PR#2854](https://github.com/nextui-org/nextui/pull/2854/files#diff-d532d0381dac2d0d780d36eb7aac0a1d7a0765fbf74aecf94e7b9c52d04ec1ebR21)). Maybe add `disableFocusManagement` prop to the `Modal` component?

**Comment by wingkwong** [comment]
Lemme handle that.
