### ISSUE TITLE
[BUG] - ListboxItem href attribute is not working as expected.

### ISSUE THREAD

**Issue by chen-yan** [nextui-org/nextui#3206]
### NextUI Version

^2.3.2

### Describe the bug

` <Listbox aria-label='nav' selectionMode='single' variant="bordered">
                <ListboxSection key='test'>
                    <ListboxItem href='/account' key='account'>
                        Account
                    </ListboxItem>
                    <ListboxItem to='/register' isReadOnly key='register'>
                        Register
                    </ListboxItem>
                </ListboxSection>
            </Listbox>`

1. href takes page to root path "/" if without isReadyOnly
2. with isReadyOnly, page redirected by reloading the whole page.

I think this issue also affect Tab's href attribute, looks like the default onClick method conflict with the link behavior.

### Steps to Reproduce the Bug or Issue

1. remix integrated with latest nextui version
2. use Listbox render a list of links 

### Expected behavior

1. page jump to to the address of the href attribute.
2. without reload whole page

### Operating System Version

MacOS Windows

### Browser

Chrome

**Comment by chen-yan** [comment]
Here's my tmp solution:

`import {Link, LinkProps} from "@remix-run/react";
import React from "react";

interface RemixLinkProps extends Omit<LinkProps, 'to'> {
    href: string;
}


const RemixLink = React.forwardRef<HTMLAnchorElement, RemixLinkProps>(({href, ...props}, ref) => {
    delete props['onClick']
    return <Link to={href} ref={ref} {...props} />;
});

RemixLink.displayName = 'RemixLink'

export default RemixLink;`

<ListboxItem href='/account' key='account' as={RemixLink}> Account </ListboxItem>

**Comment by wingkwong** [comment]
Have you tried `v2.4.1`?

**Comment by chen-yan** [comment]
> Have you tried `v2.4.1`?

Yes, when I upgrade from 2.3.1 to 2.4.1 got this issue, and I also tried all the versions above 2.3.1, all the same.

It may be caused by some dependencies, but not sure.

**Comment by chen-yan** [comment]
This bug can also be found in Dropdown component.

**Comment by wingkwong** [comment]
@chen-yan are you using npm? if so, can you try to use pnpm to see if the issue is still reproducibe?

**Comment by chen-yan** [comment]
> @chen-yan are you using npm? if so, can you try to use pnpm to see if the issue is still reproducibe?

It works great after switch to pnpm. thank you. 
BTW, why pnpm resolve it ?

**Comment by wingkwong** [comment]
we're still investigating it. Probably some internal change from react-aria side. please use pnpm first as a temp fix for the time being.
