### ISSUE TITLE
[BUG] - If a Table is inserted into the Modal pop-up window, it cannot be scrolled left or right, and the overflow x-scroll property is invalid.

### ISSUE THREAD

**Issue by uyevan** [nextui-org/nextui#3207]
### NextUI Version

2.3.6

### Describe the bug

If a Table is inserted into the Modal pop-up window, it cannot be scrolled left or right, and the overflow x-scroll property is invalid.
the code:
`
<Modal backdrop={"blur"}
                   isOpen={isOpenShare}
                   onOpenChange={onOpenChangeShare}
                   placement={"auto"}
                   size={"5xl"}
            >
                <ModalContent>
                    {onClose => (
                        <>
                            {/*头部*/}
                            <ModalHeader className={"flex flex-col gap-1 font-extrabold dark:text-white"}>我分享的笔记
                                🍧</ModalHeader>
                            {/*内容*/}
                            <ModalBody className={'mb-4'}>
                                <Router>
                                    <Table
                            title={"我的分享"}
                            aria-label="我分享的所有笔记."
                            shadow={"sm"}/*阴影*/
                            hideHeader={false}/*隐藏头部*/
                            isStriped={false}/*条纹化*/
                            isHeaderSticky={true}/*头部阴影*/
                            fullWidth={true}
                            className={`w-64 overflow-x-auto`}
                        >
                        ........
                        </Table>
                                </Router>
                            </ModalBody>
                        </>
                    )}
                </ModalContent>
            </Modal>
`

### Steps to Reproduce the Bug or Issue

<Modal>
  ....
    <Table>  --->Unable to slide horizontally
    ....
    

### Expected behavior

Unable to slide Table horizontally。

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/92195051/572c6948-2b1e-4261-a44b-25ffb493aaf8

Unable to slide horizontally.

### Operating System Version

Windows

### Browser

Edge

**Comment by alphaxek** [comment]
Hi @uyevan , I tried reproducing the issue, working on my end, can you update to the latest version and try

Test:
![modalTable](https://github.com/nextui-org/nextui/assets/116849110/2db2ce12-72cc-463e-a7e7-071c80f59f24)

**Comment by uyevan** [comment]
Can I take a look at your implementation code? Thank.

**Comment by uyevan** [comment]
> 嗨，我尝试重现该问题，在我这边工作，您能否更新到最新版本并尝试
> 
> 测试： ![modalTable](https://private-user-images.githubusercontent.com/116849110/337772823-2db2ce12-72cc-463e-a7e7-071c80f59f24.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjY0MjcsIm5iZiI6MTcxNzgyNjEyNywicGF0aCI6Ii8xMTY4NDkxMTAvMzM3NzcyODIzLTJkYjJjZTEyLTcyY2MtNDYzZS1hN2U3LTA3MWM4MGY1OWYyNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNTU1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzQ3Nzk5ZGI2YzY5NWFhMzQ0OTc1NTk1ZTZmMjZlZWI5YWQ0NzIxNzlmMDg4MDE1MDk5ZWQ3MTVhYTIwMzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VxqGAb9guz9V0Q9MmlToluOZd6MXpYkGoyfEYEWBym8) [ ![modalTable](https://private-user-images.githubusercontent.com/116849110/337772823-2db2ce12-72cc-463e-a7e7-071c80f59f24.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjY0MjcsIm5iZiI6MTcxNzgyNjEyNywicGF0aCI6Ii8xMTY4NDkxMTAvMzM3NzcyODIzLTJkYjJjZTEyLTcyY2MtNDYzZS1hN2U3LTA3MWM4MGY1OWYyNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNTU1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzQ3Nzk5ZGI2YzY5NWFhMzQ0OTc1NTk1ZTZmMjZlZWI5YWQ0NzIxNzlmMDg4MDE1MDk5ZWQ3MTVhYTIwMzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VxqGAb9guz9V0Q9MmlToluOZd6MXpYkGoyfEYEWBym8) ](https://private-user-images.githubusercontent.com/116849110/337772823-2db2ce12-72cc-463e-a7e7-071c80f59f24.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjY0MjcsIm5iZiI6MTcxNzgyNjEyNywicGF0aCI6Ii8xMTY4NDkxMTAvMzM3NzcyODIzLTJkYjJjZTEyLTcyY2MtNDYzZS1hN2U3LTA3MWM4MGY1OWYyNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNTU1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzQ3Nzk5ZGI2YzY5NWFhMzQ0OTc1NTk1ZTZmMjZlZWI5YWQ0NzIxNzlmMDg4MDE1MDk5ZWQ3MTVhYTIwMzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VxqGAb9guz9V0Q9MmlToluOZd6MXpYkGoyfEYEWBym8) [ ](https://private-user-images.githubusercontent.com/116849110/337772823-2db2ce12-72cc-463e-a7e7-071c80f59f24.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjY0MjcsIm5iZiI6MTcxNzgyNjEyNywicGF0aCI6Ii8xMTY4NDkxMTAvMzM3NzcyODIzLTJkYjJjZTEyLTcyY2MtNDYzZS1hN2U3LTA3MWM4MGY1OWYyNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNTU1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzQ3Nzk5ZGI2YzY5NWFhMzQ0OTc1NTk1ZTZmMjZlZWI5YWQ0NzIxNzlmMDg4MDE1MDk5ZWQ3MTVhYTIwMzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VxqGAb9guz9V0Q9MmlToluOZd6MXpYkGoyfEYEWBym8)

Can I take a look at your implementation code?Thank.

**Comment by uyevan** [comment]
> Hi @uyevan , I tried reproducing the issue, working on my end, can you update to the latest version and try
> 
> Test: ![modalTable](https://private-user-images.githubusercontent.com/116849110/337772823-2db2ce12-72cc-463e-a7e7-071c80f59f24.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjY4NTQsIm5iZiI6MTcxNzgyNjU1NCwicGF0aCI6Ii8xMTY4NDkxMTAvMzM3NzcyODIzLTJkYjJjZTEyLTcyY2MtNDYzZS1hN2U3LTA3MWM4MGY1OWYyNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmVmZjkxZGJmYzM2ZGIxNGVjNGQ4ZWZiYTU3ODBlYjMzOWU4NGYxMDg5MzI1Y2ZhZDgyYzk1ZDNhMTdhMGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ib1b-VZEqyg0K_fbvRRqY1JYae0jHgCnW3T4sLyzSn0) [ ![modalTable](https://private-user-images.githubusercontent.com/116849110/337772823-2db2ce12-72cc-463e-a7e7-071c80f59f24.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjY4NTQsIm5iZiI6MTcxNzgyNjU1NCwicGF0aCI6Ii8xMTY4NDkxMTAvMzM3NzcyODIzLTJkYjJjZTEyLTcyY2MtNDYzZS1hN2U3LTA3MWM4MGY1OWYyNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmVmZjkxZGJmYzM2ZGIxNGVjNGQ4ZWZiYTU3ODBlYjMzOWU4NGYxMDg5MzI1Y2ZhZDgyYzk1ZDNhMTdhMGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ib1b-VZEqyg0K_fbvRRqY1JYae0jHgCnW3T4sLyzSn0) ](https://private-user-images.githubusercontent.com/116849110/337772823-2db2ce12-72cc-463e-a7e7-071c80f59f24.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjY4NTQsIm5iZiI6MTcxNzgyNjU1NCwicGF0aCI6Ii8xMTY4NDkxMTAvMzM3NzcyODIzLTJkYjJjZTEyLTcyY2MtNDYzZS1hN2U3LTA3MWM4MGY1OWYyNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmVmZjkxZGJmYzM2ZGIxNGVjNGQ4ZWZiYTU3ODBlYjMzOWU4NGYxMDg5MzI1Y2ZhZDgyYzk1ZDNhMTdhMGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ib1b-VZEqyg0K_fbvRRqY1JYae0jHgCnW3T4sLyzSn0) [ ](https://private-user-images.githubusercontent.com/116849110/337772823-2db2ce12-72cc-463e-a7e7-071c80f59f24.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjY4NTQsIm5iZiI6MTcxNzgyNjU1NCwicGF0aCI6Ii8xMTY4NDkxMTAvMzM3NzcyODIzLTJkYjJjZTEyLTcyY2MtNDYzZS1hN2U3LTA3MWM4MGY1OWYyNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmVmZjkxZGJmYzM2ZGIxNGVjNGQ4ZWZiYTU3ODBlYjMzOWU4NGYxMDg5MzI1Y2ZhZDgyYzk1ZDNhMTdhMGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ib1b-VZEqyg0K_fbvRRqY1JYae0jHgCnW3T4sLyzSn0)

Can I take a look at your implementation code?Thank.

**Comment by alphaxek** [comment]
Hi @uyevan,

I just merged `Modal` and `Table` component examples from nextui.org/docs and tested in codesandbox.io

```import React from "react";
import {Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, Button, useDisclosure, Table, TableHeader, TableColumn, TableBody, TableRow, TableCell} from "@nextui-org/react";

export default function App() {
  const {isOpen, onOpen, onClose} = useDisclosure();
  const [backdrop, setBackdrop] = React.useState('opaque')

  const backdrops = ["opaque", "blur", "transparent"];

  const handleOpen = (backdrop) => {
    setBackdrop(backdrop)
    onOpen();
  }

  return (
    <>
      <div className="flex flex-wrap gap-3">
        {backdrops.map((b) => (
          <Button  
            key={b}
            variant="flat" 
            color="warning" 
            onPress={() => handleOpen(b)}
            className="capitalize"
          >
           {b}
          </Button>
        ))}  
      </div>
      <Modal backdrop={backdrop} isOpen={isOpen} onClose={onClose}>
        <ModalContent>
          {(onClose) => (
            <>
              <ModalHeader className="flex flex-col gap-1">Modal Title</ModalHeader>
              <ModalBody>
              <Table aria-label="Example static collection table">
                <TableHeader>
                  <TableColumn>NAME</TableColumn>
                  <TableColumn>ROLE</TableColumn>
                  <TableColumn>STATUS</TableColumn>
                </TableHeader>
                <TableBody>
                  <TableRow key="1">
                    <TableCell>Tony Reichert</TableCell>
                    <TableCell>CEO</TableCell>
                    <TableCell>Active</TableCell>
                  </TableRow>
                  <TableRow key="2">
                    <TableCell>Zoey Lang</TableCell>
                    <TableCell>Technical Lead</TableCell>
                    <TableCell>Paused</TableCell>
                  </TableRow>
                  <TableRow key="3">
                    <TableCell>Jane Fisher</TableCell>
                    <TableCell>Senior Developer</TableCell>
                    <TableCell>Active</TableCell>
                  </TableRow>
                  <TableRow key="4">
                    <TableCell>William Howard</TableCell>
                    <TableCell>Community Manager</TableCell>
                    <TableCell>Vacation-Looooooooooooooooonnnngggggggggggggggggggggggg</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
              </ModalBody>
              <ModalFooter>
                <Button color="danger" variant="light" onPress={onClose}>
                  Close
                </Button>
                <Button color="primary" onPress={onClose}>
                  Action
                </Button>
              </ModalFooter>
            </>
          )}
        </ModalContent>
      </Modal>
    </>
  );
}
```

**Comment by uyevan** [comment]
> Hi @uyevan,
> 
> I just merged `Modal` and `Table` component examples from nextui.org/docs and tested in codesandbox.io
> 
> ```
> import {Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, Button, useDisclosure, Table, TableHeader, TableColumn, TableBody, TableRow, TableCell} from "@nextui-org/react";
> 
> export default function App() {
>   const {isOpen, onOpen, onClose} = useDisclosure();
>   const [backdrop, setBackdrop] = React.useState('opaque')
> 
>   const backdrops = ["opaque", "blur", "transparent"];
> 
>   const handleOpen = (backdrop) => {
>     setBackdrop(backdrop)
>     onOpen();
>   }
> 
>   return (
>     <>
>       <div className="flex flex-wrap gap-3">
>         {backdrops.map((b) => (
>           <Button  
>             key={b}
>             variant="flat" 
>             color="warning" 
>             onPress={() => handleOpen(b)}
>             className="capitalize"
>           >
>            {b}
>           </Button>
>         ))}  
>       </div>
>       <Modal backdrop={backdrop} isOpen={isOpen} onClose={onClose}>
>         <ModalContent>
>           {(onClose) => (
>             <>
>               <ModalHeader className="flex flex-col gap-1">Modal Title</ModalHeader>
>               <ModalBody>
>               <Table aria-label="Example static collection table">
>                 <TableHeader>
>                   <TableColumn>NAME</TableColumn>
>                   <TableColumn>ROLE</TableColumn>
>                   <TableColumn>STATUS</TableColumn>
>                 </TableHeader>
>                 <TableBody>
>                   <TableRow key="1">
>                     <TableCell>Tony Reichert</TableCell>
>                     <TableCell>CEO</TableCell>
>                     <TableCell>Active</TableCell>
>                   </TableRow>
>                   <TableRow key="2">
>                     <TableCell>Zoey Lang</TableCell>
>                     <TableCell>Technical Lead</TableCell>
>                     <TableCell>Paused</TableCell>
>                   </TableRow>
>                   <TableRow key="3">
>                     <TableCell>Jane Fisher</TableCell>
>                     <TableCell>Senior Developer</TableCell>
>                     <TableCell>Active</TableCell>
>                   </TableRow>
>                   <TableRow key="4">
>                     <TableCell>William Howard</TableCell>
>                     <TableCell>Community Manager</TableCell>
>                     <TableCell>Vacation-Looooooooooooooooonnnngggggggggggggggggggggggg</TableCell>
>                   </TableRow>
>                 </TableBody>
>               </Table>
>               </ModalBody>
>               <ModalFooter>
>                 <Button color="danger" variant="light" onPress={onClose}>
>                   Close
>                 </Button>
>                 <Button color="primary" onPress={onClose}>
>                   Action
>                 </Button>
>               </ModalFooter>
>             </>
>           )}
>         </ModalContent>
>       </Modal>
>     </>
>   );
> }
> ```

Thank you bro.

**Comment by uyevan** [comment]
> Hi @uyevan,
> 
> I just merged `Modal` and `Table` component examples from nextui.org/docs and tested in codesandbox.io
> 


I know the source of the problem, but when I don't know how to solve it, as I have tried various methods, I will describe to you the situations where it can slide left and right normally and the situations where it cannot slide left and right normally:
![Snipaste_2024-06-08_21-08-21](https://github.com/nextui-org/nextui/assets/92195051/ca6c342d-1779-49c7-b2bd-a5a7700956dc)
![Snipaste_2024-06-08_21-07-40](https://github.com/nextui-org/nextui/assets/92195051/b04ed556-ade9-4f8e-a54e-367a9beb3448)


This is an normal situation:
![Snipaste_2024-06-08_21-06-27](https://github.com/nextui-org/nextui/assets/92195051/c6e8e079-6140-4c95-94f8-65918a45bf5d)

This is an abnormal situation:
![Snipaste_2024-06-08_21-07-24](https://github.com/nextui-org/nextui/assets/92195051/42777a37-b93d-46e6-844b-77f60c95afd7)


If I use variables on the parameters, I won't be able to slide left and right normally, but I can simply define it as true to slide normally... I am very confused...

**Comment by alphaxek** [comment]
@uyevan Where have you declared this?

![image](https://github.com/nextui-org/nextui/assets/116849110/430a5db6-94bf-4273-a07c-01b855b825b1)

**Comment by uyevan** [comment]
> @uyevan Where have you declared this?
> 
> ![image](https://private-user-images.githubusercontent.com/116849110/337877193-430a5db6-94bf-4273-a07c-01b855b825b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTk2MDQsIm5iZiI6MTcxNzg1OTMwNCwicGF0aCI6Ii8xMTY4NDkxMTAvMzM3ODc3MTkzLTQzMGE1ZGI2LTk0YmYtNDI3My1hMDdjLTAxYjg1NWI4MjViMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNTA4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWUwNjk5MTc4MTA4ZmQ1ZmQ2ZDRiZDk0YTE3OTYwOTQxZWFhNWIzZjYzOWMyNTg3NThjMzgzYjdiYzI5ZDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KV6OYpb_aZntEEKCAUlMJcz0Z0-mgOmiartgrpG7D3w)

![Snipaste_2024-06-08_23-10-16](https://github.com/nextui-org/nextui/assets/92195051/f79fa037-a440-4e4f-b66d-46ed26333f8c)

**Comment by uyevan** [comment]
> @uyevan Where have you declared this?
> 
> ![image](https://private-user-images.githubusercontent.com/116849110/337877193-430a5db6-94bf-4273-a07c-01b855b825b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjA5MjEsIm5iZiI6MTcxNzg2MDYyMSwicGF0aCI6Ii8xMTY4NDkxMTAvMzM3ODc3MTkzLTQzMGE1ZGI2LTk0YmYtNDI3My1hMDdjLTAxYjg1NWI4MjViMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNTMwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODdjMjMzMDE0NTBmMzI2NzA3YmU5ZDA2MTM2ZGE2YTcyYjgxMDQ2ZWNjMmRjYjc5YmNmOGVhOWMyMDliZGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Khw_o9SIfMIO2lLcFWvMvyYSmDWD2YryBcpuU5S83Co)

![Snipaste_2024-06-08_23-33-58](https://github.com/nextui-org/nextui/assets/92195051/6f7bb27a-74e6-4065-8b4e-08cb0e5a1876)
![Snipaste_2024-06-08_23-33-27](https://github.com/nextui-org/nextui/assets/92195051/717b70a6-2b21-4280-af4e-d8207409dd81)
![Snipaste_2024-06-08_23-32-22](https://github.com/nextui-org/nextui/assets/92195051/e14d95ab-ae36-41bc-9651-479cb4b6f0fd)
![Snipaste_2024-06-08_23-31-59](https://github.com/nextui-org/nextui/assets/92195051/997912de-0e10-49f3-bdbd-684148a3fddf)

That's roughly what it means. I'm not sure if you understand it ...

**Comment by uyevan** [comment]
> @uyevan Where have you declared this?
> 
> ![image](https://private-user-images.githubusercontent.com/116849110/337877193-430a5db6-94bf-4273-a07c-01b855b825b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjE5MTksIm5iZiI6MTcxNzg2MTYxOSwicGF0aCI6Ii8xMTY4NDkxMTAvMzM3ODc3MTkzLTQzMGE1ZGI2LTk0YmYtNDI3My1hMDdjLTAxYjg1NWI4MjViMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNTQ2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmZiMWY5MjdmYzhkNjY2OGQyYjY2MTBkNjVmNmI2OTY2ZmQyMmU2OThjMzEwYTc0NjVmY2E2NGU1Njc4OGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q0VeccAIK4B6OWG5CKa1ANjvXJQWQZx2v_Ricieyedc)

I have determined what the reason is! It's because this status setting was executed twice. You see, the console printed twice at the same time, but I'm still not sure why it needs to be executed twice.
![Snipaste_2024-06-08_23-45-14](https://github.com/nextui-org/nextui/assets/92195051/38b21e6b-e876-41cd-9e13-0941f976fad1)
![Snipaste_2024-06-08_23-44-26](https://github.com/nextui-org/nextui/assets/92195051/f470549e-d186-4d50-9207-e4373c8c520a)

If I write it like this, it would be normal for him, which also indicates that it was indeed executed twice.
![Snipaste_2024-06-08_23-49-19](https://github.com/nextui-org/nextui/assets/92195051/8ea6d3bf-561d-4f21-8983-cbc03f1b12b9)

**Comment by alphaxek** [comment]
May be try declaring in `ShareComponents.tsx`, just playaround you will get it.

**Comment by alphaxek** [comment]
@uyevan does it work if you pass `true` value here? instead of passing state variables

![image](https://github.com/nextui-org/nextui/assets/116849110/9b847a71-99cf-4346-af6b-745f815765f0)

**Comment by uyevan** [comment]
> @uyevan does it work if you pass `true` value here? instead of passing state variables
> 
> ![image](https://private-user-images.githubusercontent.com/116849110/337928391-9b847a71-99cf-4346-af6b-745f815765f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDE4NjgsIm5iZiI6MTcxNzk0MTU2OCwicGF0aCI6Ii8xMTY4NDkxMTAvMzM3OTI4MzkxLTliODQ3YTcxLTk5Y2YtNDM0Ni1hZjZiLTc0NWY4MTU3NjVmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxMzU5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmIzNjZhZDFmZDlmMGEzNTE5ZDNjMTBlYjUzMzk0ODg5NTI1NTE5Mjk5NjQwZjM5ZWFkYmEzMzBlMThhNjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d6fJRhrX88VcEbtGSVQra5mNaYf2wbdq_d0CIxtEOtc)

Hello brother, I have found the root cause of the problem and solved it, and submitted a new issue. You can take a look and test it.
new issues: [https://github.com/nextui-org/nextui/issues/3223](https://github.com/nextui-org/nextui/issues/3223)

**Comment by alphaxek** [comment]
great
