### ISSUE TITLE
[BUG] - Tabs component not working

### ISSUE THREAD

**Issue by iamMikeLe** [nextui-org/nextui#3209]
### NextUI Version

2.4.1

### Describe the bug

Tabs component seems to not work correctly. At least on my machine. Can anyone try and see if the issue is not just on my machine so that we can politely blame nextUI :D.

node `v18.20.0`
npm `10.5.0`
yarn `1.22.22`

### Steps to replicate the issue:
- follow documentation to install - Automatic Installation option
1. `npm install -g nextui-cli`
2. `nextui init my-nextui-app` - select `App`, default name, select `yarn`
3. `yarn add @nextui-org/react` - to get all the components
4. replace the content of your `app/page.tsx` with (example of basic Tabs component from documentation): 

```
import {Card, CardBody, Tab, Tabs} from "@nextui-org/react";

export default function Home() {
  return (
    <section className="flex flex-col items-center justify-center gap-4 py-8 md:py-10">
      <div className="flex w-full flex-col">
      <Tabs aria-label="Options">
        <Tab key="photos" title="Photos">
          <Card>
            <CardBody>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </CardBody>
          </Card>  
        </Tab>
        <Tab key="music" title="Music">
          <Card>
            <CardBody>
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </CardBody>
          </Card>  
        </Tab>
        <Tab key="videos" title="Videos">
          <Card>
            <CardBody>
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </CardBody>
          </Card>  
        </Tab>
      </Tabs>
    </div>  
    </section>
  );
}
```
5. `yarn run dev` from root dir

And the app crashes with:

```
yarn run dev
yarn run v1.22.22
$ next dev
  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1450ms
 ○ Compiling / ...
 ✓ Compiled / in 5.4s (5649 modules)
 ⨯ Error: Unknown element <[object Object]> in collection.
    at getFullNode.next (<anonymous>)
    at iterateCollection.next (<anonymous>)
    at Generator.next (<anonymous>)
digest: "2069349907"
 GET / 500 in 5705ms
```

- I tried to adjust imports `@nextui-org/tabs` instead of react. (did the same for `Card` and `CardBody`) but did not work. Importing and using all other components work, only the Tabs does not work and gives me this error.

Can someone try it and see if it works on their machine?

### Expected behavior

It should render Tabs component correctly without crashing

### Operating System Version

macOS Sonoma 14.4.1

### Browser

Chrome

**Comment by wingkwong** [comment]
@iamMikeLe have you tried adding `use client' directive at the top of your file?

**Comment by iamMikeLe** [comment]
I have not, it works with that. Thanks!

**Comment by iamMikeLe** [comment]
fixed by adding 'use client'

**Comment by MiloWang2048** [comment]
> @iamMikeLe have you tried adding `use client` directive at the top of your file?

But why it doesn't work in rsc?

**Comment by FlashAmarillo** [comment]
Why is not working with server side components?  🤔
