### ISSUE TITLE
[BUG] - The style of a button will be broken when one uses `color=gradient`, `bordered` and `icon` simultaneously.

### ISSUE THREAD

**Issue by CNLHC** [nextui-org/nextui#321]
### Describe the bug

The style of a button will be broken when one uses `color=gradient`, `bordered` and `icon` simultaneously.

``` jsx
    <Button
            onClick={onCreate}
            bordered
            auto
            // color={"gradient"}
            icon={<FontAwesomeIcon icon={faPlusCircle} />}>
            NewTask
          </Button>
```
will generate 
<img width="130" alt="image" src="https://user-images.githubusercontent.com/21005146/156483102-0cbb22e3-bdeb-4f43-aa85-803ec3634868.png">

but

```jsx

          <Button
            onClick={onCreate}
            bordered
            auto
            color={"gradient"}
            icon={<FontAwesomeIcon icon={faPlusCircle} />}>
            NewTask
          </Button>
```
will generate 

<img width="116" alt="image" src="https://user-images.githubusercontent.com/21005146/156483172-d6802fb2-0887-4475-8cfe-baf924674505.png">

if one removes the `bordered`, the result seems to be fine.
```jsx

          <Button
            onClick={onCreate}
            // bordered
            auto
            color={"gradient"}
            icon={<FontAwesomeIcon icon={faPlusCircle} />}>
            NewTask
          </Button>
```
<img width="119" alt="image" src="https://user-images.githubusercontent.com/21005146/156483268-f3bcdd98-e897-414e-9965-c4741f8627cd.png">

### Steps to Reproduce the Bug or Issue

1. Create a `Button` instance.
2. Add  `color=gradient`, `bordered`,`icon={<SomeIcon/>}` props
3. Check the broken style.

### Expected behavior

I think the icon should be positioned correctly when one uses `color=gradient`, `bordered`, and `icon` simultaneously.

### Operating System Version

macOS Moneterey 12.2.1 (21D62)

### Browser

Edge

**Comment by sereneinserenade** [comment]
seems related to #320
