### ISSUE TITLE
[BUG] - DEFAULT requied and email validation is not working on latest version

### ISSUE THREAD

**Issue by tjfaith** [nextui-org/nextui#3210]
### NextUI Version

2.4.1

### Describe the bug

When i use isRequired={true} in version 2.3.6 i get this validation by default but on version 2.4.1 it dosnt get validated 
![error2](https://github.com/nextui-org/nextui/assets/55920490/f1c68f29-e941-4c49-8ee9-df76b5b1f371)
![error1](https://github.com/nextui-org/nextui/assets/55920490/f7b6dfc0-ed83-4499-9ad3-b8b979361d9d)

### Steps to Reproduce the Bug or Issue

The walk around is to use is to handle  it like this according to the `docs`

import React from "react";
import {Input} from "@nextui-org/react";

export default function App() {
  const [value, setValue] = React.useState("junior2nextui.org");

  const validateEmail = (value) => value.match(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+.[A-Z]{2,4}$/i);

  const isInvalid = React.useMemo(() => {
    if (value === "") return false;

    return validateEmail(value) ? false : true;
  }, [value]);

  return (
    <Input
      value={value}
      type="email"
      label="Email"
      variant="bordered"
      isInvalid={isInvalid}
      color={isInvalid ? "danger" : "success"}
      errorMessage="Please enter a valid email"
      onValueChange={setValue}
      className="max-w-xs"
    />
  );
}
``

### Expected behavior

![Uploading error2.PNG…]()

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
See https://nextui.org/blog/v2.4.0#validation-behavior
