### ISSUE TITLE
[BUG] - Not working use pnpm monorepo.

### ISSUE THREAD

**Issue by tanghaojie** [nextui-org/nextui#3215]
### NextUI Version

2.4.1

### Describe the bug

Follow [doc](https://nextui.org/docs/frameworks/vite) config vite project.
when i use sisngle repo, all works great, but when i change to pnpm monorepo , it seems styles are missing.

### Your Example Website or App
[Github repo](https://github.com/tanghaojie/nextui-monorepo-bug)
[stackblitz](https://stackblitz.com/~/github.com/tanghaojie/nextui-monorepo-bug)
[Vercel](https://nextui-monorepo-bug-app1.vercel.app/)

_No response_

### Steps to Reproduce the Bug or Issue

1. Just config vite project, and install nextui@2.4.1.
2. Config pnpm monorepo.

### Expected behavior

.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by uyevan** [comment]
change the node version to 18.17.0.

**Comment by wingkwong** [comment]
@tanghaojie You path is not correct in `tailwind.config.js`:

```diff
- './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
+ '../../node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
```

**Comment by soyricardodev** [comment]
> @tanghaojie You path is not correct in `tailwind.config.js`:
> 
> ```diff
> - './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
> + '../../node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
> ```

this fix the issue, but just work when the .npmrc is setup correctly as mentioned in the docs, but should be mentioned too that in a monorepo the path in tailwind.config.js is different.

Should i make an issue an a pr?

**Comment by wingkwong** [comment]
@soyricardodev sure. you may add a note in each Tailwind CSS Setup.
