### ISSUE TITLE
[BUG] - does the next-ui doc have something error of the classNames type descripition?

### ISSUE THREAD

**Issue by sedgwickz** [nextui-org/nextui#3216]
### NextUI Version

2.4

### Describe the bug

Just put an example like this doc page https://nextui.org/docs/components/popover#popover-props

All the doc of classNames desscripition is like 

`Record<"base"｜ "trigger"｜ "backdrop"｜ "content", string>`

Well, it means each key should be defined when using it. I also make a test by the typescript playground. Here is the link [Typescript Playground](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgILIN4Chm+QEzjDgC5kAlCBAeynwB4ByOOR5AH2UYCNvGAaZAGcwUUAHMAfFgC+WLABsIYZKTTIAvJhx5CxMtjxHkvMgCIzO3HJlA.)

Obviously, it doesn't need to do that. 

### Steps to Reproduce the Bug or Issue

Just check all the component doc at https://nextui.org/docs/components

### Expected behavior

Maybe it should be described as `Partial<Record<"base"｜ "trigger"｜ "backdrop"｜ "content", string>>` or others. I'm not sure. So hope you guys review it.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by aayush-goyal** [comment]
@wingkwong Can I pick this up? Also, is this issue only pertaining to `className` for all the components?

**Comment by wingkwong** [comment]
@aayush-goyal thanks. go ahead please.
