### ISSUE TITLE
[BUG] - Autocomplete's keyboard shortcuts behave weirdly

### ISSUE THREAD

**Issue by takuyahara** [nextui-org/nextui#3225]
### NextUI Version

0.0.0-canary-20240607005641

### Describe the bug

Autocomplete's keyboard shortcuts behave weirdly as follows. They don't happen in examples on  [document](https://nextui.org/docs/components/autocomplete).
1. When hitting tab key next autocomplete's textbox is not focused and popover opens but none of keyboard shortcut (ex. arrow up/down, enter, esc, etc...) works.
2. When autocomplete is the last focusable component, hitting tab key results popover keeps opened.

But when textbox is clicked, hitting tab key focuses to next autocomplete's textbox. This is an expected behavior.

### Your Example Website or App

https://stackblitz.com/~/github.com/takuyahara/nextui-autocomplete-issue

### Steps to Reproduce the Bug or Issue

1. Go to the above-mentioned stackblitz page.
2. Open page in new tab to see an isolated version.
3. Hit tab key and arrow up/down keys.

### Expected behavior

1. Hitting tab key focuses to next autocomplete's textbox with popover automatically opened and keyboard shortcut (ex. arrow up/down, enter, esc, etc...) works.
2. When autocomplete is the last focusable component, hitting tab key closes popover.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/46240835/7434f41d-b1fe-4934-9a39-d9f2dbf4d18d

### Operating System Version

macOS

### Browser

Brave v1.66.118 (Chromium v125.0.6422.147)

**Comment by takuyahara** [comment]
Another issues found.

### Describe the bug

1. Clicking autocomplete doesn't focus on textbox on first click so input is not accepted. It has to be clicked twice.
2. When typing in textbox and delete key is hit, focus is automatically blurred.
3. When popover is opened and outside of the browser is clicked, popover closes. And when inside of the page is clicked popover reopens without keyboard support.

### Expected behavior

1. Clicking autocomplete focuses on textbox on first click.
2. Hitting delete key in textbox doesn't blur.
3. When inside of the page is clicked again, textbox is focused and popover reopens without keyboard support.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/46240835/7db1b539-ccf8-4f2b-84eb-f9d01c495b03

**Comment by wingkwong** [comment]
This is what I see. Just use tab and arrow down key.

[issue3225.webm](https://github.com/nextui-org/nextui/assets/35857179/c0edea6b-5f50-4602-8888-6deadf85fd54)

**Comment by takuyahara** [comment]
It's weird, I see the issue on both Windows and macOS with Chrome, Brave and Safari. I wonder if you are looking the stackblitz link because in your video I see some padding on top of the page but it doesn't exist actually.

**Comment by wingkwong** [comment]
@takuyahara i was testing on my local tho.

**Comment by takuyahara** [comment]
@wingkwong Could you please check on stackblitz? This is where I see the issue (and on my local as well of course).

https://stackblitz.com/~/github.com/takuyahara/nextui-autocomplete-issue

**Comment by takuyahara** [comment]
@wingkwong I hope you have time to see. Let me know if something is lacking.

**Comment by wingkwong** [comment]
@takuyahara I could see the error on my next app also but not in storybook n doc. Need to dig a bit.

**Comment by takuyahara** [comment]
@wingkwong Just a quick note: downgrading `@nextui-org/react` to 2.2.10 fixed the issue. Still not sure why it doesn't reproduce in storybook but I see this part causes a problem. If you comment L112 out it solves issue.

https://github.com/nextui-org/nextui/blob/47c2472fb22bfe1c0c357b5ba12e5606eba0d65b/packages/components/popover/src/free-solo-popover.tsx#L109-L114

**Comment by takuyahara** [comment]
Maybe the difference that the issue happens in app but doesn't in storybook is by a difference of bundler. NextUI components are bundled by tsup but storybook bundles with Vite if I understand properly.

**Comment by takuyahara** [comment]
@wingkwong I believe that I'm reaching to the solution. `dialogRef` ([L109](https://github.com/nextui-org/nextui/blob/47c2472fb22bfe1c0c357b5ba12e5606eba0d65b/packages/components/popover/src/free-solo-popover.tsx#L109)) is applied to FreeSoloPopoverWrapper ([L65-L83](https://github.com/nextui-org/nextui/blob/47c2472fb22bfe1c0c357b5ba12e5606eba0d65b/packages/components/popover/src/free-solo-popover.tsx#L65-L83)) but it doesn't refer to `div[role="dialog"]` but to its parent.

![image](https://github.com/nextui-org/nextui/assets/46240835/730de6b8-db5f-4edb-9c28-66f5ecb08551)

So a part of FreeSoloPopover's return ([L151-L153](https://github.com/nextui-org/nextui/blob/47c2472fb22bfe1c0c357b5ba12e5606eba0d65b/packages/components/popover/src/free-solo-popover.tsx#L151-L153)) must be

```tsx
            <div {...getContentProps()} ref={dialogRef}>
              {typeof children === "function" ? children(titleProps) : children}
            </div>
```

and no ref in FreeSoloPopoverWrapper ([L65-L83](https://github.com/nextui-org/nextui/blob/47c2472fb22bfe1c0c357b5ba12e5606eba0d65b/packages/components/popover/src/free-solo-popover.tsx#L65-L83)) like

```tsx
    return disableAnimation ? (
      <div {...otherProps}>
        {children}
      </div>
    ) : (
      <LazyMotion features={domAnimation}>
        <m.div
          animate="enter"
          exit="exit"
          initial="initial"
          style={style}
          variants={TRANSITION_VARIANTS.scaleSpringOpacity}
          {...mergeProps(otherProps, motionProps)}
        >
          {children}
        </m.div>
      </LazyMotion>
    );
```

Hope this helps. 🤞

**Comment by wingkwong** [comment]
There's lots of diff between `2.2.10` and `2.4.2`. We had some major dependencies upgrades in-between. To share more context here, in dialog's focus management, focus is moved into the dialog on mount and restored to the trigger on unmount. In autocomplete, the focus behaviour is a little bit different. We set the focus whenever the popover is open in `use-autocomplete.ts`.

**Comment by takuyahara** [comment]
Quick note: I found the issue is caused by React's strict mode. Removing `<React.StrictMode>` from root component fixes the issue and this is why it doesn't reproduce in Storybook because strict mode is disabled. When enabled the issue reproduces in Storybook as well.

https://github.com/nextui-org/nextui/blob/6951b1fba03652f95babe3a490caa2a061b8cb12/packages/storybook/.storybook/main.js#L16-L19

```diff
-   options: {}
+   options: {
+     strictMode: true,
+   }
```

But since, as far as I know, the use of strict mode is not restricted every component should work on both strict and non-strict mode. It seems like there's something to be destructed on unmount and digging into `use-autocomplete.ts` (thank you for your suggestion @wingkwong).
