### ISSUE TITLE
[BUG] - NextUIProvider navigate not being called

### ISSUE THREAD

**Issue by londonbarrett** [nextui-org/nextui#3232]
### NextUI Version

2.4.1

### Describe the bug

NextUIProvider navigate function is not calling the navigate function. Every time you click a link, it's reloading the whole page

### Steps to Reproduce the Bug or Issue

1. Install last version of @nextui-org/react
2. Setup NextUIProvider with navigate property

### Expected behavior

As a user when I hit a link, it should load the content without reloading the whole page

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
1. have you tried remove node_modules and lock file before installing?
2. are you clicking the link component? or something like dropdown menu item link?

**Comment by londonbarrett** [comment]
1. I didn't, unfortunately I had rolled back to v2.3.6 and it's working again.
2. I'm using ListBox, Tabs and Link component.

**Comment by AhmedLukman** [comment]
I face similar issue with Next JS 14.2.3 when I use the button with 'as={Link}' prop. Page fully reloads on navigation.

**Comment by londonbarrett** [comment]
Also in v2.3.6 Tabs are not working with router, so I guess neither in v2.4.1

**Comment by jviall** [comment]
I am able to reproduce this issue still with v2.4.8 using Remix (React-Router) v2.13.1 (both latest).

Using tabs as links, client side routing is not used.
https://codesandbox.io/p/github/jviall/remix-start/nextui-tabs-client-routing
