### ISSUE TITLE
[BUG] - Some components are missing Slots section in their documentation.

### ISSUE THREAD

**Issue by aayush-goyal** [nextui-org/nextui#3233]
### NextUI Version

2.4.1

### Describe the bug

A few components are missing Slot section on their documentation.

Here is the comprehensive list of such components:
1. [Badge](https://nextui.org/docs/components/badge)
2. [Card](https://nextui.org/docs/components/card)
3. [Switch](https://nextui.org/docs/components/switch)

### Steps to Reproduce the Bug or Issue

1. Go to https://nextui.org/docs/components/
2. Click on any of these components: a) Badge b) Card c) Switch
3. Check right navigation bar for the content.
4. Now click on Popover component.
5. You will find Slots section for this component.

### Expected behavior

As a user, I expected that if a component is making use of Slots and classNames, there should be proper documentation on that.

### Screenshots or Videos

![Screenshot 2024-06-11 at 1 13 11 PM](https://github.com/nextui-org/nextui/assets/12670414/64d2bf5f-d1e5-4d4c-beb5-4779d945cc1a)
![Screenshot 2024-06-11 at 1 14 24 PM](https://github.com/nextui-org/nextui/assets/12670414/71446ed9-ec37-40c7-9a27-c29af7d70fc5)

### Operating System Version

macOS

### Browser

Chrome

**Comment by aayush-goyal** [comment]
I can pick this up @wingkwong

**Comment by wingkwong** [comment]
@aayush-goyal thanks. go ahead.
