### ISSUE TITLE
[BUG] - Card component "flashes" when switching between light and dark color modes

### ISSUE THREAD

**Issue by bhscer** [nextui-org/nextui#3234]
### NextUI Version

2.4.1

### Describe the bug

Let's take the official documentation as an example: "https://nextui.org/docs/components/card", when we switch between dark and light color modes of the page, we can see that:
1. When switching from light mode to dark mode, the background has changed to black, and the card will blink white.
2. When switching from dark mode to light mode, the background has changed to white and the card will flash black.

### Your Example Website or App

https://nextui.org/docs/components/card

### Steps to Reproduce the Bug or Issue

1. click the (light/dark) swtich button on nvabar
2. find the card "flash"

### Expected behavior

the card's background shouldn't flash.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
That's not the bug but the built-in animation. You can simply disable it by setting `disableAnimation` to `true`.

**Comment by bhscer** [comment]
> That's not the bug but the built-in animation. You can simply disable it by setting `disableAnimation` to `true`.

Thank for your quick reply. 
The "flash" did really disappeared after i set `disableAnimation` to `true`.
