### ISSUE TITLE
[BUG] - Popover's arrow should combine with the border line of the box

### ISSUE THREAD

**Issue by chen-yan** [nextui-org/nextui#3235]
### NextUI Version

v2.4

### Describe the bug

![image](https://github.com/nextui-org/nextui/assets/2889354/448c147d-53fa-4274-88ec-ce27274b1caa)

### Steps to Reproduce the Bug or Issue

1. render popover component
2.set showArrow value as true
3. click button.

### Expected behavior

![image](https://github.com/nextui-org/nextui/assets/2889354/699649f6-9048-4750-a1fd-17ecb37543e7)

### Operating System Version

MacOS Windows

### Browser

Chrome

**Comment by abhinandan-verma** [comment]
@wingkwong I want to work on the issue #3235 ,  I want to know How can I update the code of Popover component to display the arrow. (This will be my first contribution to this repo)

`const App = `import {Popover, PopoverTrigger, PopoverContent, Button} from "@nextui-org/react";

export default function App() {
  return (
    <Popover placement="bottom" showArrow={true}>
      <PopoverTrigger>
        <Button>Open Popover</Button>
      </PopoverTrigger>
      <PopoverContent>
        <div className="px-1 py-2">
          <div className="text-small font-bold">Popover Content</div>
          <div className="text-tiny">This is the popover content</div>
        </div>
      </PopoverContent>
    </Popover>
  );
}`;

const react = {
  "/App.jsx": App,
};

export default {
  ...react,
};
`

**Comment by arindam1997007** [comment]
Hi @wingkwong 
I have raised a PR for this fix. Please review it when you have the time :)

**Comment by wingkwong** [comment]
Closing - after an internal discussion, we'll keep the original design as it is.
