### ISSUE TITLE
[BUG] - Table Row Key forces string typing.

### ISSUE THREAD

**Issue by buchananwill** [nextui-org/nextui#3238]
### NextUI Version

2.4

### Describe the bug

The documentation about keys for the Table Rows is unclear and the typing implies that they are React.Key, which permits both numbers and strings. However, as far as I can tell from using the component, number ids/keys are converted to strings, and equality comparisons will subsequently fail. This was my workaround, to avoid the risk of breaking other parts of my projects API:

```
  const selectedSet = useMemo(() => {
    return forceString
      ? new Set<string>(selectedList.map((ident) => String(ident)))
      : new Set(selectedList);
  }, [selectedList, forceString]);

  const handleChange = useCallback(
    (selected: 'all' | Set<Key>) => {
      console.log(selected);
      const nextSelection =
        selected === 'all'
          ? [...idList]
          : ([...new Set(selected).values()] as U[]);
      dispatchSelected(nextSelection.sort());
    },
    [dispatchSelected, idList]
  );
  return { currentState, selectedSet, handleChange };
}

```

and then in the table:

```
  return (
    <Table
      aria-label="Example table with custom cells, pagination and sorting"
      isHeaderSticky
      bottomContent={bottomContent}
      bottomContentPlacement="outside"
      classNames={{
        wrapper: 'max-h-[382px]'
      }}
      selectedKeys={selectedSet} // this fails is the selectedSet is a set of numbers.
      selectionMode="multiple"
      sortDescriptor={sortDescriptor}
      topContent={topContent}
      topContentPlacement="outside"
      onSelectionChange={handleChange}
      onSortChange={setSortDescriptor}
    >
      <TableHeader columns={headerColumns}>
        {(column) => (
          <TableColumn
            key={column.uid}
            align={'start'}
            allowsSorting={column.sortable}
          >
            {column.name}
          </TableColumn>
        )}
      </TableHeader>
      <TableBody emptyContent={'No users found'} items={sortedItems}>
        {(item) => (
          <TableRow key={item.id}> // the id passed here is a number value, but apparently converted to a string by the TableRow 
            {(columnKey) => (
              <TableCell>{renderCell(item, columnKey)}</TableCell>
            )}
          </TableRow>
        )}
      </TableBody>
    </Table>
  );
```

### Steps to Reproduce the Bug or Issue

I used the example Table from the NextUI docs:

https://nextui.org/docs/components/table#use-case-example

And ran into this bug when using entities that have numerical IDs.

### Expected behavior

I would expected the Table API to respect the data type of the provided keys, or for the documentation to otherwise be clear that it does not.

### Operating System Version

- Windows 10 Home V.22H2

### Browser

Chrome

**Comment by ryo-manba** [comment]
Thanks for the issue!
This is because [React converts keys to strings](https://softwareengineering.stackexchange.com/questions/381268/why-are-react-keys-limited-to-strings/432948#432948). It might be a good idea to add this as a note in the documentation.

**Comment by buchananwill** [comment]
Thanks! The Typescript typing of React.Key is explicitly 'string | number',
without stating that the latter is coerced into the former,  so clearer
documentation would help.  Thanks!
