### ISSUE TITLE
In modal box Input Fields Obscured or hidden below by Keyboard on Mobile Devices

### ISSUE THREAD

**Issue by dharmveer97** [nextui-org/nextui#3241]
### NextUI Version

"@nextui-org/react": "^2.4.1",

### Describe the bug

On mobile devices, I've created forms within a modal box. However, when the keyboard opens up, the input fields are below by the keyboard, making it difficult for users to fill out the form.

### Environment
- Device: [e.g., iPhone X, Samsung Galaxy S10]
- Browser: [e.g., Safari, Chrome]

### Steps to Reproduce
1. Open the modal form on a mobile device.
2. Atleast add 6 fields in the form and i'm using Formik lib BTW.
3. Focus on an input field using mobile device to bring up the keyboard.
4. Observe that the input fields are covered by the keyboard.

### Expected behavior

When the keyboard opens, the modal form should adjust its position so that the input fields remain visible and accessible.

### Operating System Version

- Device: [e.g., iPhone X, Samsung Galaxy S10] - Browser: [e.g., Safari, Chrome] Macos for dev

### Browser

Safari

**Comment by dharmveer97** [comment]
https://github.com/dharmveer97/nextui-modal-bug-test

**Comment by dharmveer97** [comment]
> [ENG-1003 In modal box Input Fields Obscured by Keyboard on Mobile Devices](https://linear.app/nextui-inc/issue/ENG-1003/in-modal-box-input-fields-obscured-by-keyboard-on-mobile-devices)

????

**Comment by dharmveer97** [comment]
https://github.com/nextui-org/nextui/assets/51308779/84f82427-088e-439e-bce4-63cc312fe898

**Comment by alphaxek** [comment]
Hi @dharmveer97, I went through you Vercel app, seems to be working fine in signup/login pages.

**Comment by dharmveer97** [comment]
Hi @alphaxek the login and sign-up pages are separate pages, not modal boxes. The issue occurs when I put a form in a modal box. On mobile devices, the keyboard opens up and the fields get hidden under the keyboard.

Here is the demo repo https://github.com/dharmveer97/nextui-modal-bug-test @alphaxek

**Comment by dharmveer97** [comment]
## `TEMP SOLUTION`

'use client';

import React, { useEffect, useRef } from 'react';
import {
  Button,
  useDisclosure,
  Modal,
  ModalContent,
  ModalBody,
} from '@nextui-org/react';

import CreateLotForm from '../../components/forms/CreateLotForm';

const AddLotModal = () => {
  const { isOpen, onOpen, onOpenChange, onClose } = useDisclosure();
  const modalBodyRef = useRef(null);

  const handleOpen = () => {
    onOpen();
  };

  useEffect(() => {
    if (modalBodyRef.current) {
      const inputs = modalBodyRef.current.querySelectorAll(
        'input, textarea, select',
      );
      inputs.forEach((input) => {
        input.addEventListener('focus', () => {
          setTimeout(() => {
            input.scrollIntoView({ behavior: 'smooth', block: 'center' });
          }, 300);
        });
      });
    }
  }, [isOpen]);

  return (
    <div>
      <div className="flex flex-wrap gap-3">
        <Button
          variant="flat"
          color="warning"
          onClick={handleOpen}
          className="capitalize"
        >
          Add New
        </Button>
      </div>

      <Modal
        isOpen={isOpen}
        onOpenChange={onOpenChange}
        isDismissable={false}
        scrollBehavior="outside"
        size="5xl"
      >
        <ModalContent>
          {() => (
            <>
              {/* empty div for more space or height */}
              <div className="pt-12 block sm:hidden" />
              <ModalBody ref={modalBodyRef}>
                <CreateLotForm
                  enableReinitialize
                  close={onClose}
                  onSubmit={() => {}}
                />
                {/* empty div for more space or height */}
                <div className="pb-44 block sm:hidden" />
              </ModalBody>
            </>
          )}
        </ModalContent>
      </Modal>
    </div>
  );
};

export default AddLotModal;

**Comment by alphaxek** [comment]
@dharmveer97 have you added empty `div` for space?

**Comment by dharmveer97** [comment]
> useEffect(() => {
>     if (modalBodyRef.current) {
>       const inputs = modalBodyRef.current.querySelectorAll(
>         'input, textarea, select',
>       );
>       inputs.forEach((input) => {
>         input.addEventListener('focus', () => {
>           setTimeout(() => {
>             input.scrollIntoView({ behavior: 'smooth', block: 'center' });
>           }, 300);
>         });
>       });
>     }
>   }, [isOpen]);

I added some space at the top and bottom of the modal body to improve scrolling visibility on mobile. However, for a better solution, you could add space when the keyboard opens just useref to do this and check when keyboard open and add space when keyboard open up. This might be a good method to address the issue. I also added a use effect for scrolling, which checks if there are any `select` `inputs` or `textAreas` in the form and scrolls to that view. The useEffect is the main component of this solution. Lastly its temp solution.

**Comment by alphaxek** [comment]
@dharmveer97  Sure
