### ISSUE TITLE
[BUG] - Dropdown Menu scroll is actually the page scroll when it has too many items

### ISSUE THREAD

**Issue by vmorales-2920** [nextui-org/nextui#3244]
### NextUI Version

2.4.1

### Describe the bug

We have a dropdown that has around 80 items, but when we click the dropdown the items go all around the page.

Is there a way to make the dropdown menu  smaller? I already try it with css but I was unsuccessful.

### Steps to Reproduce the Bug or Issue

This is the code for the dropdown

use client';
import {
    Button,
    DropdownItem,
    DropdownTrigger,
    Dropdown,
    DropdownMenu,
} from '@nextui-org/react';
import "../../app/globals.css";

interface IDataItem {
    id: number;
    name: string;
}

interface IProps {
    type: string,
    data: IDataItem[]
}

export default function DropdownMenuC({ type, data }: IProps) {
    return (
        <div className="dropdown">
            <Dropdown size='sm'>
                <DropdownTrigger>
                    <Button className='Btn' variant="bordered" >
                        {type}
                    </Button>
                </DropdownTrigger>
                <DropdownMenu aria-label="items" items={data}>
                    {(item) => (
                        <DropdownItem key={item.id}>
                            {item.name}
                        </DropdownItem>
                    )}
                </DropdownMenu>
            </Dropdown>
        </div>
    );
}

### Expected behavior

to show an small the dropdown menu and that the dropdown menu scroll is not the page itself scroll.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/104101683/8ab8aa9f-f16b-4c5b-ba0c-389b3067aa43)

### Operating System Version

Linux

### Browser

Chrome

**Comment by ShrinidhiUpadhyaya** [comment]
Can i work on this issue?

### Question
What is the max height should i set to the Menu?

**Comment by vmorales-2920** [comment]
the dropdown has a max-height: 50vh, but it does not matter the height I assigned to the dropdown, it will still go all way down the page.

**Comment by ovidiu-h** [comment]
@vmorales-2920 as a quick fix you can use:

`<DropdownMenu className="max-h-[50vh] overflow-y-auto">...</DropdownMenu>`

**Comment by vmorales-2920** [comment]
Hi, is all good now. Thanks for your feedback. Have a great day!

**Comment by MarcusDelvecchio** [comment]
Having the same issue where trying to scroll the dropdown content scroll scrolls the page content. How did you resolve?

**Comment by vmorales-2920** [comment]
Hi, instead of using the dropdown component I use the select component and it worked!

**Comment by pawanrana1992** [comment]
It is still present and not yet resolved, even giving the overflow and max height the scroll of the dropdown body not based on its internal content.
multiple items are not able to scroll as the scroll is not calculating the internal content height.

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/005e9f17-d238-4343-9947-d5a3e5218503">

**Comment by pawanrana1992** [comment]
The <li className="Kyrgyzstan"> element is showing as first item in view, but there are lots of LI on top of it which is hiding behind.
![image](https://github.com/user-attachments/assets/a858a861-7cb5-49fa-a48b-fc45a372a90e)

Requesting you team please help fix this common issue first, as it is primary use component.

**Comment by pawanrana1992** [comment]
For quick solution it the class should be manually used inside ul element

<Dropdown
        classNames={{
          base: 'before:bg-gray-100 shadow-none', // change arrow background
          content:
            'rounded-md rounded-top-0 shadow-none bg-gray-100 min-w-[200px] absolute right-[-50px] top-[-16px] [&>div>ul]:overflow-x-hidden [&>div>ul]:overflow-y-auto [&>div>ul]:max-h-[250px]',
        }}
      >
        <DropdownTrigger>
          <Button
            variant="light"
            className="capitalize"
            radius="full"
            size="sm"
            title="Change Language"
            autoFocus={false}
            startContent={
              <Image
                alt="Country"
                height={18}
                width={'auto'}
                src={selectedObject?.flag}
                className={iconClasses}
              />
            }
            endContent={
              <span className="material-icons-round text-lg">
                arrow_drop_down
              </span>
            }
          >
            {selectedObject?.name?.toUpperCase()}
          </Button>
        </DropdownTrigger>
        <DropdownMenu
          aria-label="currency-and-country"
          variant="flat"
          disallowEmptySelection
          selectionMode="single"
          selectedKeys={selectedKeys as any}
          onSelectionChange={setNewCurrency}
        >
          {countries?.map((item, index) => {
            return (
              <DropdownItem
                className={`text-sm ${index == 0 ? 'mr-20' : ''}`}
                title={item.name}
                description={
                  <span
                    data-ab="abcd"
                    className="text-ellipsis block overflow-hidden whitespace-nowrap max-w-[150px]"
                  >
                    Currency: ${item?.iso2?.toUpperCase() ?? ''}
                  </span>
                }
                startContent={
                  <Image
                    alt="Country"
                    height={24}
                    // width={24}
                    src={item.flag}
                    className={iconClasses}
                  />
                }
                key={item?.iso2?.toUpperCase()}
              />
            );
          })}
        </DropdownMenu>

**Comment by vmorales-2920** [comment]
Hi, what I did was replacing the dropdown component with the select component and it worked for me
