### ISSUE TITLE
[BUG] - Table useInfiniteScroll hook fetches twice

### ISSUE THREAD

**Issue by ynchen2829** [nextui-org/nextui#3251]
### NextUI Version

2.4.1

### Describe the bug

Following the example code for Infinite pagination in [nextUI Table Infinite Scroll](https://nextui.org/docs/components/table#infinite-pagination), the expected behavior is that when the page initially loads, fetch is performed once to load the initial page, however, `loadMore` from `useAsyncList` hook is called immediately after the initial load, causing the app to load not only one, but two pages. 

This may not seem like a big deal, but in my customized software, when I call `list.reload`, this behavior rises concurrency issue and messes up the `cursor.next`, causing my Table to load the wrong page of data. 

### Your Example Website or App

[codeSandboxLink](https://codesandbox.io/p/devbox/nextui-useinfinitescroll-z9v49z?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxe16pwc00063b6j92thpnt8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxe16pwc00023b6j6yr58o82%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxe16pwc00043b6jlt9ino9f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxe16pwc00053b6jfua6gus5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxe16pwc00023b6j6yr58o82%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxe16pwc00013b6j04nnxdqb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clxe16pwc00023b6j6yr58o82%2522%252C%2522activeTabId%2522%253A%2522clxe16pwc00013b6j04nnxdqb%2522%257D%252C%2522clxe16pwc00053b6jfua6gus5%2522%253A%257B%2522id%2522%253A%2522clxe16pwc00053b6jfua6gus5%2522%252C%2522activeTabId%2522%253A%2522clxe1zl6b00o13b6jot21rsjo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clxe1zl6b00o13b6jot21rsjo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clxe16pwc00043b6jlt9ino9f%2522%253A%257B%2522id%2522%253A%2522clxe16pwc00043b6jlt9ino9f%2522%252C%2522activeTabId%2522%253A%2522clxe17yhh003t3b6jpxo0is5c%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxe17yhh003t3b6jpxo0is5c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxe17yjv002cdjgegvxweu4p%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxe1zfcs00lr3b6j1ldezlgi%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce the Bug or Issue

1. Go to sandbox
2. Run dev server
3. Inspect to see `console.log` statements, and two consecutive pages are fetched without being scrolled to the bottom.

Alternative:
1. Go to  [nextUI Table Infinite Scroll](https://nextui.org/docs/components/table#infinite-pagination)
2. Click preview
3. Notice that the initial load has 20 items instead of 10 (expected behavior), where each `loadMore` loads 10 more items 

### Expected behavior

Expected: Initial load calling `load` once
Seeing: Initial load triggers `load` once and triggers `loadMore` without scrolling to bottom.

### Operating System Version

macOS

### Browser

Chrome

**Comment by abhisektomar1** [comment]
I am Working on it!
