### ISSUE TITLE
[BUG] - New blank project using init fails to compile

### ISSUE THREAD

**Issue by Sam-Spencer** [nextui-org/nextui#3252]
### NextUI Version

2.4.1

### Describe the bug

Following the installation instructions _exactly_ as they are given in the [NextUI documentation](https://nextui.org/docs/guide/installation#automatic-installation) results in a compilation error:

> Uncaught ModuleParseError: Module parse failed: Unexpected character '@' (1:0)
> @tailwind base;

This is a completely vanilla installation in an empty directory. I feel that I must be doing something wrong here... Any help would be appreciated!

***

*Extra side note*: As someone who is new to web development and completely unfamiliar with this project, it is unclear what this Bug Report form means by "NextUI Version"... It appears NextUI is just a series of sub-packages and each of them is versioned differently, so there is no one single "version" of NextUI. What does it mean? What am I missing here? 😖 

### Your Example Website or App

https://github.com/Sam-Spencer/nextui-nonworking-demo

### Steps to Reproduce the Bug or Issue

 1. Create a new empty directory on your system
 2. Go [here, to the NextUI documentation](https://nextui.org/docs/guide/installation#automatic-installation) and follow the _Automatic Installation_ instructions exactly as they appear, accepting all default values.
 3. Run `npm run dev`
 4. Compilation fails

### Expected behavior

As a user, I expected a vanilla install that exactly follows the documented setup instructions to work and compile. However, I am unable to compile the base project.

### Screenshots or Videos

![Screenshot 2024-06-14 at 3 36 38 PM](https://github.com/nextui-org/nextui/assets/2374407/c312acde-a0b3-4ff0-b59f-63d08f2d359b)

### Operating System Version

macOS Sonoma 14.5

### Browser

Chrome

**Comment by wingkwong** [comment]
@Sam-Spencer I just cloned your repo and run `npm i` and `npm run dev`. I don't see any error.

<img width="764" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/25648c45-f136-4ce0-9335-819bc2064c05">

Just FYI. I'm using node v20.12.2 and npm v10.8.1.

**Comment by Sam-Spencer** [comment]
@wingkwong I get a warning when running `npm run dev`:

>  ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against.

But, my `NODE_ENV` is definitely a standard value. If I run `printenv NODE_ENV` I get `production` echoed back (there aren't any overrides / modifications to it in my ZSH or Bash profiles either). Any suggestions on what's going on here? Guessing its something with my system / environment and no necessarily a NextUI bug at this point, but I'd appreciate any guidance on this before closing this...

**Comment by wingkwong** [comment]
Even setting NODE_ENV to production shouldn't cause the problem. What versions are you using for Node and npm?

> Extra side note: As someone who is new to web development and completely unfamiliar with this project, it is unclear what this Bug Report form means by "NextUI Version"... It appears NextUI is just a series of sub-packages and each of them is versioned differently, so there is no one single "version" of NextUI.

I will update the issue template later.
