### ISSUE TITLE
locale not wirking [BUG] - Date-picker

### ISSUE THREAD

**Issue by esmailshahbazi** [nextui-org/nextui#3254]
### NextUI Version

2.4.1

### Describe the bug

im using "fa-IR-u-ca-persian" for locale but month name and year don't change to persian calendar

### Steps to Reproduce the Bug or Issue

Provide a clear and concise description of what you expected to happen.

### Expected behavior

im using "fa-IR-u-ca-persian" for locale but month name and year don't change to persian calendar

### Operating System Version

windows

### Browser

Chrome

**Comment by wingkwong** [comment]
Can you share your code?
