### ISSUE TITLE
[BUG] - React does not recognize the `disableAnimation` prop on a DOM element. 

### ISSUE THREAD

**Issue by uigywnkiub** [nextui-org/nextui#3257]
### NextUI Version

2.4.2

### Describe the bug

_In browser console_

Warning: React does not recognize the `disableAnimation` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `disableanimation` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### Steps to Reproduce the Bug or Issue

Bug reproduce of all your site pages.

### Expected behavior

As a user, I expected disableanimation prop in lowercase (maybe), but I am seeing a warning error log in console browser that cannot recognize attribute.

### Screenshots or Videos

<img width="511" alt="image" src="https://github.com/nextui-org/nextui/assets/29861553/877b0d44-2fdd-43ad-924e-71b8dcf18282">

### Operating System Version

- OS: macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
> Bug reproduce of all your site pages.

Can you share which site pages you were visiting? I didn't see this error.

**Comment by uigywnkiub** [comment]
> > Bug reproduce of all your site pages.
> 
> Can you share which site pages you were visiting? I didn't see this error.

localhost

**Comment by wingkwong** [comment]
please provide a minimal reproducible example

**Comment by uigywnkiub** [comment]
> please provide a minimal reproducible example


https://github.com/nextui-org/nextui/assets/29861553/cd59218a-0a9b-4674-86ce-3887dda5022d

**Comment by paperdiamond** [comment]
I also started experiencing this after updating to 2.4.2

**Comment by LeakedDave** [comment]
This is happening on all Avatars on 2.4.2

**Comment by wingkwong** [comment]
@LeakedDave please use the canary version `0.0.0-canary-20240616172522` as a temp fix at the moment.

**Comment by uigywnkiub** [comment]
> @LeakedDave please use the canary version `0.0.0-canary-20240616172522` as a temp fix at the moment.

When new version released?

**Comment by wingkwong** [comment]
@uigywnkiub Currently I don't have the exact date. We need to discuss internally first.

**Comment by iFurySt** [comment]
same question. looking forward to the new version being released. ❤️

**Comment by farrawy** [comment]
I have the same issue here. This is how I handled it since it's a warning only.

Create a file in the same directory of your layout.tsx/.jsx/.js file. For me I am using typescript. 

error-boundary.tsx

`"use client";
import React, { ReactNode } from "react";

interface ErrorBoundaryProps {
  children: ReactNode;
  fallback?: ReactNode;
}

interface ErrorBoundaryState {
  hasError: boolean;
  error: Error | null;
  errorInfo: React.ErrorInfo | null;
}

class ErrorBoundary extends React.Component<
  ErrorBoundaryProps,
  ErrorBoundaryState
> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, error: null, errorInfo: null };
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error, errorInfo: null };
  }

  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    // Log the error to an error reporting service
    console.error("ErrorBoundary caught an error", error, errorInfo);
    this.setState({ errorInfo });

    // Suppress specific warning
    if (error.message.includes("disableAnimation")) {
      console.warn("Suppressed warning about disableAnimation");
    }
  }

  render() {
    if (this.state.hasError) {
      return (
        <div>
          <h2>Something went wrong.</h2>
          <details style={{ whiteSpace: "pre-wrap" }}>
            {this.state.error && this.state.error.toString()}
            <br />
            {this.state.errorInfo?.componentStack}
          </details>
        </div>
      );
    }

    return this.props.children;
  }
}

export default ErrorBoundary;
`


layout.tsx

`import "@/styles/globals.css";
import { Metadata, Viewport } from "next";
import clsx from "clsx";

import { Providers } from "./providers";

import ErrorBoundary from "./error-boundary";
import { siteConfig } from "@/config/site";
import { fontSans } from "@/config/fonts";
import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s - ${siteConfig.name}`,
  },
  description: siteConfig.description,
  icons: {
    icon: "/favicon.ico",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body
        className={clsx(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
          <ErrorBoundary>
            <div className="relative flex flex-col h-screen">
              <Navbar user={{ name: "John Doe", avatar: "/logo.png" }} />
              <main className="container mx-auto max-w-7xl pt-16 px-6 flex-grow">
                {children}
              </main>
            </div>
          </ErrorBoundary>
        </Providers>
      </body>
    </html>
  );
}
`

I hope this helps!

**Comment by farrawy** [comment]
I have the same issue here. This is how I handled it since it's a warning only.

Create a file in the same directory of your layout.tsx/.jsx/.js file. For me I am using typescript. 

error-boundary.tsx

```
"use client";
import React, { ReactNode } from "react";

interface ErrorBoundaryProps {
  children: ReactNode;
  fallback?: ReactNode;
}

interface ErrorBoundaryState {
  hasError: boolean;
  error: Error | null;
  errorInfo: React.ErrorInfo | null;
}

class ErrorBoundary extends React.Component<
  ErrorBoundaryProps,
  ErrorBoundaryState
> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, error: null, errorInfo: null };
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error, errorInfo: null };
  }

  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    // Log the error to an error reporting service
    console.error("ErrorBoundary caught an error", error, errorInfo);
    this.setState({ errorInfo });

    // Suppress specific warning
    if (error.message.includes("disableAnimation")) {
      console.warn("Suppressed warning about disableAnimation");
    }
  }

  render() {
    if (this.state.hasError) {
      return (
        <div>
          <h2>Something went wrong.</h2>
          <details style={{ whiteSpace: "pre-wrap" }}>
            {this.state.error && this.state.error.toString()}
            <br />
            {this.state.errorInfo?.componentStack}
          </details>
        </div>
      );
    }

    return this.props.children;
  }
}

export default ErrorBoundary;
```


layout.tsx

```
import "@/styles/globals.css";
import { Metadata, Viewport } from "next";
import clsx from "clsx";

import { Providers } from "./providers";

import ErrorBoundary from "./error-boundary";
import { siteConfig } from "@/config/site";
import { fontSans } from "@/config/fonts";
import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s - ${siteConfig.name}`,
  },
  description: siteConfig.description,
  icons: {
    icon: "/favicon.ico",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body
        className={clsx(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
          <ErrorBoundary>
            <div className="relative flex flex-col h-screen">
              <Navbar user={{ name: "John Doe", avatar: "/logo.png" }} />
              <main className="container mx-auto max-w-7xl pt-16 px-6 flex-grow">
                {children}
              </main>
            </div>
          </ErrorBoundary>
        </Providers>
      </body>
    </html>
  );
}
```

I hope this helps!

**Comment by anh-ngn** [comment]
i have the same problem with 2.4.2, hope it will be fixed soon

**Comment by dumbrosio** [comment]
> please use the canary version `0.0.0-canary-20240616172522` as a temp fix at the moment.

This does not work with individual adding components

**Comment by uigywnkiub** [comment]
> > please use the canary version `0.0.0-canary-20240616172522` as a temp fix at the moment.
> 
> This does not work with individual adding components

how to install this? and when comes the new release?

**Comment by dumbrosio** [comment]
> > please use the canary version `0.0.0-canary-20240616172522` as a temp fix at the moment.
> 
> This does not work with individual adding components

My bad, the issue was on User component.

`"@nextui-org/user": "0.0.0-canary-20240616172522"` works.

**Comment by manglx** [comment]
Hello guys, I was having this same error, but I changed the import from the specific component to the global components:

This produces the error for me:
import { User } from "@nextui-org/user";

So I changed the import and the error is gone, and still works fine :)
import { User } from "@nextui-org/react";

Hope this works for you in case you don't like seing errors like me lol

**Comment by dumbrosio** [comment]
> I was having this same error, but I changed the import from the specific component to the global components:
> 
> This produces the error for me: import { User } from "@nextui-org/user";
> 
> So I changed the import and the error is gone, and still works fine :) import { User } from "@nextui-org/react";

I actually think the type of import depends on the type of installation. If I understand what you are saying, I suggest you refresh your node_modules cache.

**Comment by King-Mufasa** [comment]
updating nextui and next.js will be solution of this problem? 
I am using these versions
 "@nextui-org/react": "^2.4.2",
 "next": "14.2.4",

**Comment by wingkwong** [comment]
@King-Mufasa latest version is 2.4.6. please upgrade to include the fix

**Comment by King-Mufasa** [comment]
Thank you for your help. it works

**Comment by uigywnkiub** [comment]
> @King-Mufasa latest version is 2.4.6. please upgrade to include the fix

The version still have the error in some cases.

**Comment by wingkwong** [comment]
@uigywnkiub please share some steps for us to reproduce

**Comment by eaglit** [comment]
> @uigywnkiub please share some steps for us to reproduce

using NextUI/AvatarGroup with 'next/image' will cause this error _React does not recognize the `disableAnimation` prop on a DOM element._

for example: 

`<AvatarGroup isBordered size='sm'>
                        {images?.map((image, index) => (
                            <Avatar key={index} src={image} radius='sm' ImgComponent={Image} imgProps={{ width: 150, height: 150, blurDataURL }} />
                        ))}
                    </AvatarGroup>`

i haven't tested it yet but i guess same issue happens when using NextUI/User component with Next/Image

**Comment by wingkwong** [comment]
@eaglit please share a sandbox

**Comment by Amanow01** [comment]
app-index.js:33 Warning: React does not recognize the `Image` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `image` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at a
    at LinkComponent (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/link.js:121:19)
    at div
    at nav
    at Navbar (Server)
    at div
    at body
    at html
    at RootLayout (Server)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at DevRootNotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/dev-root-not-found-boundary.js:33:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/app/ReactDevOverlay.js:87:9)
    at HotReload (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:321:11)
    at Router (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:207:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:113:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:160:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:585:13)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:112:27)
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:117:11)

﻿

**Comment by wingkwong** [comment]
@Amanow01 please share the reproducible code.

**Comment by uigywnkiub** [comment]
> @Amanow01 please share the reproducible code.

https://github.com/uigywnkiub/explend-app/blob/f1e8b1cbaf0bf0e98934dccb4a04cf7b6b2f84c8/app/ui/sidebar/user-profile-info.tsx

If I use Image, it get error disableAnimation props... so I used to regular img to avoid it.

**Comment by WesleyKapow** [comment]
Still getting this with heroui `2.7.5` when using nextjs/Image component.

**Comment by wingkwong** [comment]
@WesleyKapow please create a new issue with a sandbox.

**Comment by uigywnkiub** [comment]
> Still getting this with heroui `2.7.5` when using nextjs/Image component.

Yes +
