### ISSUE TITLE
[BUG] - Input type "file" Not working in the first attempt.

### ISSUE THREAD

**Issue by aryankholqi** [nextui-org/nextui#3262]
### NextUI Version

2.4.1

### Describe the bug

I have form which has an Input type file to receive an image, but the problem is when I select a file for the first time, it doesn't do anything at background,
I found how to handle this bug, should set value={null} but it makes the project has a warning that an input value should not be null,

![code](https://github.com/nextui-org/nextui/assets/95369096/e7745ccd-efe0-4936-bb4e-e572ddf01f00)

### Steps to Reproduce the Bug or Issue

1- Implement a default Input type file with Next-Ui,
2- choose a file
3- you should see that your file is not given to the input

### Expected behavior

it should take the file for the first time you append

### Operating System Version

macOs

### Browser

Chrome

**Comment by wingkwong** [comment]
Duplicate - https://github.com/nextui-org/nextui/issues/2397
