### ISSUE TITLE
[BUG] - Chip component don't have correct types

### ISSUE THREAD

**Issue by vcctm** [nextui-org/nextui#3264]
### NextUI Version

2.0.29

### Describe the bug

At version: 2.0.29 of the chip component the types don't represent what is in the website.

<img width="1421" alt="image" src="https://github.com/nextui-org/nextui/assets/75961352/9b33b088-32f1-431d-be4c-344f7ff21af4">

### Steps to Reproduce the Bug or Issue

1. download  "@nextui-org/chip": "^2.0.29",
2. notice the issue when using variant prop

### Expected behavior

Don't have the issue.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Not able to reproduce (I was testing in @nextui-org/chip@2.0.30). Also you may try restart your vscode.

<img width="876" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/78b31856-d3fb-4ba6-8f62-4be96d49aef7">
