### ISSUE TITLE
Fix: Documentation is not up to date.

### ISSUE THREAD

**Issue by missnida** [nextui-org/nextui#3279]
### NextUI Version

2.4.2

### Describe the bug

Fix: Documentation is not up to date.

### Steps to Reproduce the Bug or Issue

Fix: Documentation is not up to date.

### Expected behavior

Fix: Documentation is not up to date.

### Operating System Version

all

### Browser

Chrome

**Comment by wingkwong** [comment]
Can you elaborate more? I got a draft PR updating docs [here](https://github.com/nextui-org/nextui/pull/3274).
