### ISSUE TITLE
[BUG] - disableAnimation prop Avatar

### ISSUE THREAD

**Issue by jimmailcamp** [nextui-org/nextui#3284]
### NextUI Version

2.4.2

### Describe the bug

Warning: React does not recognize the `disableAnimation` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `disableanimation` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Getting this error in my console constantly, updated to latest, still having this error. 

### Steps to Reproduce the Bug or Issue

Call Avatar component from within A card or any other nextui component

### Expected behavior

Not having this error

### Operating System Version

Mac os

### Browser

Chrome

**Comment by wingkwong** [comment]
Closing - See https://github.com/nextui-org/nextui/issues/3257#issuecomment-2172005924

**Comment by jimmailcamp** [comment]
Thanks!
Browsed the discord and could not find any answrs.
