### ISSUE TITLE
NextUI default styles are overwriting my tailwindcss

### ISSUE THREAD

**Issue by arneesh** [nextui-org/nextui#3287]
### NextUI Version

2

### Describe the bug

I want to use NextUI components in my app, but at certain places I want to use normal tailwindcss. Many of the tailwind css classes are not working at all. I came across an old issue that mentioned something similar -> https://github.com/nextui-org/nextui/discussions/397 , but this only works in `NextUI v1`. In `NextUI v2`, `NextUIProvider` doesn't even have `disableBaseline` prop? How to handle this? Running on a hard deadline, would appreciate the help.

### Steps to Reproduce the Bug or Issue

Create a NextUI Vite app using the cli as mentioned in the offical NextUI docs.

### Expected behavior

Many tailwind class are not working as NextUI is overwriting my tailwind css.

### Operating System Version

macOS Sonama 14.1

### Browser

Chrome

**Comment by TIMMLOPK** [comment]
Could you share more like your tailwindcss config and code?

**Comment by ryo-manba** [comment]
@arneesh 
Could you provide a minimal reproducible example with a link to Stackblitz?

**Comment by abhinandan-verma** [comment]
@arneesh  I tried Tailwind using custom Tailwind CSS and thing are working fine.
I would like to help you if you provide sandbox/stackblitz showing the error

Maybe you just need to update to the latest version to solve your issue.

**Comment by wingkwong** [comment]
Closing - inactivity.
