### ISSUE TITLE
[BUG] -  React does not recognize the `disableAnimation` prop on a DOM element

### ISSUE THREAD

**Issue by J4v4Scr1pt** [nextui-org/nextui#3289]
### NextUI Version

2.4.2

### Describe the bug

I just updated from 2.4.1 to 2.4.2 and got this error as soon as I started the project:
`Warning: React does not recognize the 'disableAnimation' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase 'disableanimation' instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

I then rolled back to previous version and cleaned the node_modules and the error was gone.
Did a clean of node_modules again and updated to 2.4.2 and the error was back.

The only change in 2.4.2 I see that could affect this is this change:
![image](https://github.com/nextui-org/nextui/assets/5929055/a6f365d5-61d6-49b6-9beb-ef7b22d3141c)
Because the error points to the my userMenu that has the avatar:
```
		<Dropdown placement="bottom-end">
				<DropdownTrigger>
					<div className="flex h-full w-[96px] cursor-pointer items-center justify-center">
						<Avatar
							as="button"
							fallback={
								<span className="text-purple font-normal-bold">
									{userDetails.Initials}
								</span>
							}
							className={cn('bg-transparent transition-transform', {
								'bg-alternativeLightPurple': !userDetails.UserImageId,
							})}
							imgProps={{ loading: 'lazy' }}
							showFallback
							src={avatarImage}
						/>
					</div>
				</DropdownTrigger>
				<DropdownMenu aria-label="Profile Actions" variant="flat">
					{getMenuItems(permissions, demoModeEnabled).map((item, index) => (
						<DropdownItem key={item.id} onPress={handlePress(item)} title={t(item.title)} />
					))}
				</DropdownMenu>
			</Dropdown>
```

But it also weird that a remove prop change would add this error.  So I digged deeper and found if I remove the `src={avatarImage}` the error also dissapers. I have tried different sources but all give the error. Which just to me adds to the confusion.
Maybe @wingkwong has an idea?

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

Setup a project using latest NextUI 2.4.2 and have a Avatar with the src prop.

### Expected behavior

no error on Avatar with a src prop

### Operating System Version

Window 10

### Browser

Chrome

**Comment by wingkwong** [comment]
This is an known bug which has been fixed already. See https://github.com/nextui-org/nextui/issues/3257#issuecomment-2172005924

**Comment by J4v4Scr1pt** [comment]
Ahh sry I searched for open Bugs!

**Comment by J4v4Scr1pt** [comment]
You can close this then if you want to. Thanks for the super quick response!
