### ISSUE TITLE
[BUG] - Divider not work in vertial orientation when parent height is dynamic

### ISSUE THREAD

**Issue by nealsun** [nextui-org/nextui#3296]
### NextUI Version

2.4.2

### Describe the bug

maybe 'h-full' class only works  when the parent has a defined height.

### Steps to Reproduce the Bug or Issue

not define height in parent

### Expected behavior

divider need stretch to fill the parent height when parent's height not defined

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Can you share some code?

**Comment by nealsun** [comment]
```
<div className="max-w-md">
    <div className="space-y-1">
      <h4 className="text-medium font-medium">NextUI Components</h4>
      <p className="text-small text-default-400">Beautiful, fast and modern React UI library.</p>
    </div>
    <Divider className="my-4" />
    <div id="no-height" className="flex items-center space-x-4 text-small">
      <div>Blog</div>
      <Divider orientation="vertical" />
      <div>Docs</div>
      <Divider orientation="vertical" />
      <div>Source</div>
    </div>
  </div>
  ```
 this code from Divider's doc, I remove `h-5` in the div with id `no-height`

**Comment by ShahirZain** [comment]
Hi @nealsun  this is not the bug, please try this snippet as I have tried working fine for me

```
  <div className="h-12 flex items-center text-small">
        <div>Blog</div>
        <Divider
          className="my-4 bg-[#A9ACA9] w-1 rounded-full mx-4 h-5/6"
          orientation="vertical"
        />
        <div>Docs</div>
        <Divider
          className="my-4 bg-[#A9ACA9] w-1 rounded-full mx-4 h-5/6"
          orientation="vertical"
        />
        <div>Source</div>
      </div>

```

here is the result

<img width="512" alt="Screenshot 2024-06-22 at 10 41 08 AM" src="https://github.com/nextui-org/nextui/assets/30791669/188a540c-4d74-4409-9823-65b7c1546fe0">

**Comment by nealsun** [comment]
@ShahirZain , the snippet you provided set the height `h-12` in parent div explicitly. If children's height depend on the content which I generate dynamic that I can't set the height accurately. So remove the `h-12`, it‘s not work;

**Comment by aditya-shrimali** [comment]
Hi @nealsun, try this code, am sure it will help.

> <div className="max-w-md">
    <div className="space-y-1">
      <h4 className="text-medium font-medium">NextUI Components</h4>
      <p className="text-small text-default-400">Beautiful, fast and modern React UI library.</p>
    </div>
    <Divider className="my-4" />
    <div id="no-height" className="flex items-center space-x-4 text-small">
      <div>Blog</div>
      <Divider orientation="vertical" flexItem />
      <div>Docs</div>
      <Divider orientation="vertical" flexItem/>
      <div>Source</div>
    </div>
  </div>

**Comment by nealsun** [comment]
@aditya-shrimali, no, divider still got 0 height.

**Comment by aditya-shrimali** [comment]
@nealsun this was nothing, you just forgot to add bg color on dark background. Try this code

> <div className="space-y-1">
  <h4 className="text-medium font-medium">NextUI Components</h4>
  <p className="text-small text-default-400">Beautiful, fast and modern React UI library.</p>
</div>
<Divider className="my-4" />
<div id="no-height" className="flex items-center space-x-4 text-small">
  <div>Blog</div>
  <Divider orientation="vertical" className="bg-white" flexItem />
  <div>Docs</div>
  <Divider orientation="vertical" className="bg-white" flexItem/>
  <div>Source</div>
</div>

**Comment by nealsun** [comment]
> @nealsun It was nothing, you just forgot to add bg colour on dark background. Use this line for the divider: ` <Divider orientation="vertical" className="bg-white" flexItem />`.

It's not a colour issue, I checked the element in chrome. and where is the `flexItem' prop defined?

**Comment by aditya-shrimali** [comment]
<img width="866" alt="Screenshot 2024-06-28 at 12 03 48 PM" src="https://github.com/nextui-org/nextui/assets/99111197/4e12bf57-b630-4b16-a41f-b44529172237">
Go through the official documentation, and try the background color thing

> > @nealsun It was nothing, you just forgot to add bg colour on dark background. Use this line for the divider: ` <Divider orientation="vertical" className="bg-white" flexItem />`.
> 
> It's not a colour issue, I checked the element in chrome. and where is the `flexItem' prop defined?

**Comment by nealsun** [comment]
@aditya-shrimali can you share the link? Thanks a lot.

**Comment by aditya-shrimali** [comment]
@nealsun https://mui.com/material-ui/react-divider/

**Comment by nealsun** [comment]
@aditya-shrimali Sorry, I'm talking about nextui, not mui.

**Comment by wingkwong** [comment]
@nealsun Thanks for providing the code. A vertical divider has `h-full` class which means it sets the height to 100% of its parent, as long as the parent has a defined height.

**Comment by AlieKargbo** [comment]
<Divider
          className="my-2 bg-[#A9ACA9] w-1 rounded-full mx-4 h-dvh"
          orientation="vertical"
        />

**Comment by mkarajohn** [comment]
@nealsun just add `className="h-auto"` to the `Divider` component
