### ISSUE TITLE
[BUG] - Prop `autoCapitalize` did not match. Server: "none" Client: "off"

### ISSUE THREAD

**Issue by EnricoElias** [nextui-org/nextui#3297]
### NextUI Version

"@nextui-org/date-picker": "^2.1.2", "@nextui-org/react": "^2.4.2",

### Describe the bug

I am using the DateRangePicker component in my nextjs project like this:

```
<DateRangePicker
                label="label"
                value={dateRange}
                onChange={handleChange}
                className="max-w-xs"
                visibleMonths={2}
/>
```

In my browser console, there is this error:

```
 Prop `autoCapitalize` did not match. Server: "none" Client: "off"
div
DateInputSegment@webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/date-input/dist/chunk-4HVI6SVI.mjs:18:64
div
DateRangePickerField@webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/date-picker/dist/chunk-73TKHF55.mjs:28:90
div
div
div
_c<@webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/date-input/dist/chunk-YVBCSFY6.mjs:17:288
DateRangePicker@webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/date-picker/dist/chunk-GTKUT4FT.mjs:33:457
```

### Steps to Reproduce the Bug or Issue

1. Create nextjs App 
2. Import DateRangePicker
3. Use the component
4. Look in your browser console

### Expected behavior

No error

### Operating System Version

Windows 10

### Browser

Firefox

**Comment by wingkwong** [comment]
I couldn't reproduce the issue. please share a minimal reproducible project for investigation.

**Comment by ryo-manba** [comment]
It might be an issue with react-aria.
https://github.com/adobe/react-spectrum/issues/5599
