### ISSUE TITLE
[BUG] - NavBar is not working

### ISSUE THREAD

**Issue by sauravhathi** [nextui-org/nextui#3312]
### NextUI Version

2.4.2

### Describe the bug

Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, props, _owner, _store}). If you meant to render a collection of children, use an array instead.

### Your Example Website or App
```

const jost = Jost({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={jost.className}>
      <head>
      </head>
        <body>
          <NextUiProvider>
              <Header />
          </NextUiProvider>
          <Toaster position="top-center" expand={true} />
        </body>
    </html>
  );
}
```

```
'use client';
import React from "react";
import {Navbar, NavbarBrand, NavbarContent, NavbarItem, Link, Button} from "@nextui-org/react";
// import {AcmeLogo} from "./AcmeLogo.jsx";

export default function Header() {
  return (
    <Navbar position="static">
      <NavbarContent className="hidden sm:flex gap-4" justify="center">
        <NavbarItem>
          <Link color="foreground" href="#">
            Features
          </Link>
        </NavbarItem>
        <NavbarItem isActive>
          <Link href="#" aria-current="page">
            Customers
          </Link>
        </NavbarItem>
        <NavbarItem>
          <Link color="foreground" href="#">
            Integrations
          </Link>
        </NavbarItem>
      </NavbarContent>
      <NavbarContent justify="end">
        <NavbarItem className="hidden lg:flex">
          <Link href="#">Login</Link>
        </NavbarItem>
        <NavbarItem>
          <Button as={Link} color="primary" href="#" variant="flat">
            Sign Up
          </Button>
        </NavbarItem>
      </NavbarContent>
    </Navbar>
  );
}
```

### Steps to Reproduce the Bug or Issue

I have tried 2.4.1 and 2.4.2 but the same problem.
Also tried nexui `Navbar` example.

same code i have used in another project its working fine.

### Expected behavior

Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, props, _owner, _store}). If you meant to render a collection of children, use an array instead.

![image](https://github.com/nextui-org/nextui/assets/61316762/d8e23e03-3439-47e7-83c7-2306c00702d4)

### Operating System Version

windows

### Browser

Chrome

**Comment by wingkwong** [comment]
We don't support next.js 15.0.0-rc.0 since it is using React 19 which most of our dependencies are not supporting yet. Please use v14 instead.

**Comment by Mnigos** [comment]
same issue here, still no support for react 19?

**Comment by sauravhathi** [comment]
> same issue here, still no support for react 19?

Downgrade the React version, it should work.

**Comment by wingkwong** [comment]
Nope. Current version doesn't support.
