### ISSUE TITLE
[BUG] - Navbar shouldHideOnScroll causes Navbar to vanish or get stuck

### ISSUE THREAD

**Issue by yelwin-d3** [nextui-org/nextui#3319]
### NextUI Version

in all version

### Describe the bug

In all versions, I am seeing the Navbar component with shouldHideOnScroll set to true, resulting in the Navbar disappearing after a few scrolls up and down. Alternatively, if it doesn't disappear, it reverts to sticky behavior. This issue occurs even on the NextUI component documentation page under the 'Hide on scroll' section. A page refresh restores it.

### Steps to Reproduce the Bug or Issue

1- Go to https://nextui.org/docs/components/navbar#hide-on-scroll
2- Start scrolling up and down a few times
3- Navbar disappears or goes to sticky
4- Tested on Chrome, Edge, and both mobile/desktop.

### Expected behavior

As a user, the Navbar should hide when I scroll down, but reappear as soon as I scroll back up. It should always be positioned at the very top if I haven't scrolled or if I've scrolled all the way back to the top.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/134361354/f82caa8b-be0e-404e-b3ad-b73029cae383

### Operating System Version

macOS, Window

### Browser

Chrome

**Comment by wingkwong** [comment]
Duplicate - https://github.com/nextui-org/nextui/issues/3139
