### ISSUE TITLE
[BUG] - isRequired not working on Input & Textarea

### ISSUE THREAD

**Issue by ErlandssonA** [nextui-org/nextui#3326]
### NextUI Version

2.4.2

### Describe the bug

When submitting a form that contains an Input and Textarea that has the `isRequired` attribute. It will submit the form even if the inputs are empty.

Here is some very simple code that submits the form even if the fields are empty in version `2.4.2` but in version `2.3.6` it does not submit and shows the error messages like it should do.

```JavaScript
async function handleSubmit(event) {
  event.preventDefault();

  console.log("Submit");
}
```
```JavaScript
<form onSubmit={handleSubmit}>
  <Input type="text" label="Username" name="username" size="sm" isRequired />

  <Textarea label="Message" name="message" isRequired />

  <button type="submit">Submit</button>
</form>;
```

### Steps to Reproduce the Bug or Issue

1. Create a form with a Input that has `isRequired`
2. Submit the form without typing anything in the Input

### Expected behavior

It should say that the Input can not be empty. But instead it submits the form without any data.

### Operating System Version

Windows, Linux

### Browser

Firefox

**Comment by wingkwong** [comment]
We've changed the validation behaviour from `native` to `aria` in v2.4.0. If you haven't set `validationBehavior` either in your provider or in your input component, then what you see is expected. 

Therefore, you may check out [here](https://nextui.org/blog/v2.4.0#validationbehavior) if you want to set the native `validationBehavior` globally. If you wish to use `aria` validation, you need to use `isInvalid` prop, see [here](https://nextui.org/blog/v2.4.0#validation-behavior) for more.
