### ISSUE TITLE
[BUG] - Input.Password has no onChange Event

### ISSUE THREAD

**Issue by wookaoer** [nextui-org/nextui#333]
### Describe the bug

![image](https://user-images.githubusercontent.com/37268350/157577806-3af43bdc-e5bc-4530-934c-3c2d92a6a61a.png)

when i enter the password value，the `onChange` event Will not be called

### Steps to Reproduce the Bug or Issue

1. enter the password value
2. the `onChange` event Will not be called

### Expected behavior

``

### Operating System Version

windows11

### Browser

Chrome

**Comment by KrychuTM** [comment]
In your screenshot it says "onChang" missing the "e".

**Comment by wookaoer** [comment]
> In your screenshot it says "onChang" missing the "e".

![image](https://user-images.githubusercontent.com/37268350/157634903-e8ef1d55-8a72-4ebb-be07-bdf9e614c089.png)

In fact，there has no `onChange` props in `Input.Password` and the `handlePasswordChange` function  to be not called

**Comment by jrgarciadev** [comment]
Hey @wookaoer, as @KrychuTM said, In your screenshot, it says "onChang" missing the "e", try out as follow:

```
<Input.Password onChange={handlePasswordChange} value={password} />
```

**Comment by wookaoer** [comment]
got it , sry
