### ISSUE TITLE
Popover getting removed on component re render.

### ISSUE THREAD

**Issue by Dinesh-Kuniyal** [nextui-org/nextui#3333]
### NextUI Version

^2.4.1

### Describe the bug

    const handleSubtaskCreate = (sys_board_id: number, sys_task_id: number) => {
        try {

            const updatedTasksData = TasksData.map((board: BoardDataType) => {
                if (board.id === sys_board_id) {
                    return {
                        ...board,
                        tasks: board.tasks.map((task: TasksType) => {
                            if (task.id === sys_task_id) {
                                const newSubTask: SubTasksType = {
                                    id: task.sub_tasks.length + 1,
                                    name: "",
                                    completed: 0,
                                    created: ""
                                };
                                return {
                                    ...task,
                                    sub_tasks: [...task.sub_tasks, newSubTask]
                                };
                            }
                            return task;
                        })
                    };
                }
                return board;
            });
            setTasksData(updatedTasksData);

        } catch (error) {
            console.log(error);
        }
    }
    {data.tasks && data.tasks.map((data: TasksType, index: number) => {
            return (
                <div key={data.id + index} className='p-2 md:p-4 bg-white rounded mt-2'>
                    <div className=''>
                        {data.sub_tasks.length != 0 ?
                            <Checkbox defaultSelected={data.completed == 1 ? true : false} />
                            : ""
                        }
                        <Popover
                            placement='right'>
                            <PopoverTrigger>
                                <span className='text-sm'>{data.name}</span>
                            </PopoverTrigger>
                            <PopoverContent>
                                <div className="p-4 min-w-[300px] max-w-sm w-full">
                                    <div className='flex items-center justify-between gap-2'>
                                        <div className='flex items-center'>
                                            <Checkbox size='sm' />
                                            |
                                            <IoCalendarOutline size={20} className='ml-2' />
                                        </div>
                                        <div>
                                            <Tooltip size='sm' placement='bottom' className='rounded-md' content="Priority">
                                                <Button className='bg-transparent' isIconOnly>
                                                    <IoFlagSharp />
                                                </Button>
                                            </Tooltip>
                                        </div>
                                    </div>
                                    <hr className='mt-1 mb-2' />
                                    <Textarea
                                        className='my-2 hover:bg-transparent'
                                        classNames={{
                                            input: [
                                                'block text-sm font-semibold',
                                                "bg-transparent",
                                                "hover:bg-transparent",
                                            ],
                                            inputWrapper: [
                                                "shadow-xs",
                                                "bg-transparent",
                                                "hover:bg-transparent",
                                                "dark:hover:bg-transparent",
                                                "group-data-[focus=true]:bg-transparent",
                                                "!cursor-text",
                                                "border-none",
                                                "p-0"

                                            ],
                                            innerWrapper: [
                                                "bg-transparent",
                                                "hover:bg-transparent"
                                            ]
                                        }}
                                        defaultValue={data.name}
                                        size='sm'
                                        variant='bordered'
                                        minRows={1}
                                    />
                                    <Textarea
                                        placeholder="Description"
                                        className="max-w-xs toe-scrollbar"
                                        maxRows={10}
                                    />

                                    <hr className='my-2' />

                                    <div className='flex items-center justify-between'>
                                        <span className='text-sm font-semibold'>
                                            Sub Tasks
                                        </span>
                                        <Button
                                            onPress={() => handleSubtaskCreate(sys_board_id, data.id)}
                                            size='sm' isIconOnly={true}>
                                            <GoPlus size={18} />
                                        </Button>
                                    </div>

                                    {data.sub_tasks && data.sub_tasks.map((sub_task: SubTasksType, index: number) => {
                                        return (
                                            <div key={sub_task.id + index} className='flex items-center justify-between mt-2'>
                                                <div className='flex gap-1 flex-1'>
                                                    <Checkbox size='lg' />
                                                    <Textarea
                                                        size='sm'
                                                        className='text-xs flex-1'
                                                        variant='underlined'
                                                        defaultValue={sub_task.name}
                                                        classNames={{
                                                            innerWrapper: [
                                                                'p-0'
                                                            ],
                                                            base: ['p-0'],
                                                            input: ["text-sm"]
                                                        }}
                                                        minRows={1}
                                                        maxRows={5}
                                                        endContent={
                                                            <Button size='sm' className='bg-transparent' isIconOnly={true}>
                                                                <MdOutlineDeleteOutline color='#333' size={24} />
                                                            </Button>
                                                        }
                                                    />
                                                </div>

                                            </div>
                                        )
                                    })}

                                </div>
                            </PopoverContent>
                        </Popover>
                    </div>
                </div>
            )
        })}

### Steps to Reproduce the Bug or Issue

1. Map over the object of arrays.
2. Create a popover for each traversed object.
3. Perform a function which causes state change.

### Expected behavior

As a user, I am using Popover component by nextui. When my calling handleSubtaskCreate() function the popver is getting removed.
How can I make it stable so that it shouldn't change on component re-render.

### Operating System Version

OS :- Windows

### Browser

Chrome

https://github.com/nextui-org/nextui/assets/76137603/148e8f31-c979-435b-8b91-59f1a81975e3

**Comment by wingkwong** [comment]
I think there's nothing related to NextUI popover. Your component is re-rendered because you trigger `setTasksData` in `handleSubtaskCreate` and you render it based on `data`.
