### ISSUE TITLE
[BUG] - International Calendars not working in documentation

### ISSUE THREAD

**Issue by wingkwong** [nextui-org/nextui#3339]
### NextUI Version

2.4.2

### Describe the bug

Documentation (incorrect behaviour): https://nextui.org/docs/components/calendar#international-calendars

<img width="334" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/e52fb9ff-da31-4147-8319-5f686d585f22">

Storybook (correct behaviour): https://storybook.nextui.org/?path=/story/components-calendar--international-calendars&globals=locale:da-DK

<img width="322" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/097d7b74-bf12-4a9d-808a-aba17ad1c7df">

### Steps to Reproduce the Bug or Issue

Compare the difference between documentation and storybook for International Calendars

### Expected behavior

The locale should be applied

### Operating System Version

macOS

### Browser

Chrome

**Comment by sac1hin** [comment]
Can you explain more about the issue?

**Comment by wingkwong** [comment]
@sac1hin Sure. If you look at international calendars in [documentation](https://nextui.org/docs/components/calendar#international-calendars). You can see the locale is set to `zh-CN-u-ca-chinese`. However, in the preview, it still shows in English while it should show in Chinese. In the [storybook](https://storybook.nextui.org/?path=/story/components-calendar--international-calendars&globals=locale:da-DK), you can see it renders correctly.  

```tsx
<I18nProvider locale="zh-CN-u-ca-chinese">
  <Calendar aria-label="Date (International Calendar)" />
</I18nProvider>
```

**Comment by Mihir867** [comment]
Hi, Can you assign this to me ?

**Comment by wingkwong** [comment]
@Mihir867 There's a PR already. Please check out other issues.

**Comment by Mihir867** [comment]
> @Mihir867 There's a PR already. Please check out other issues.

Ohh sure!!
Could you guide me with something I can work on, I'm actually quite new to this
