### ISSUE TITLE
[BUG] - showArrow from the Popover component does not work

### ISSUE THREAD

**Issue by YannickNCode** [nextui-org/nextui#3342]
### NextUI Version

2.4.2

### Describe the bug

I'm actually using the Popover component from NextUI. I want to show the arrow like
`<Popover key="blur" showArrow offset={10} placement="bottom" backdrop="blur" classNames={popoverClassNames}>`

But the arrow is not displayed, same for the blur effect. None of the 3 options work.
![Capture](https://github.com/nextui-org/nextui/assets/83426550/bac7d688-1e95-4455-9fc7-8485b9b87bae)

### Steps to Reproduce the Bug or Issue

1. use a Navbar component from NextUI
2. Inside this Navbar, under NavbarContent use Popover component from NextUI
3. Try to add some props like showArrow and backdrop="blur"
4. When you open the Popover you shouldnt see the Arrow or the blur effect

### Expected behavior

As a user i expect to see the arrow or a blur effect like in the exemple provided by NextUI.

### Operating System Version

Windows

### Browser

Firefox

**Comment by wingkwong** [comment]
@YannickNCode I couldn't reproduce the issue. Please share a minimal reproducible project for us to investigate.

![image](https://github.com/nextui-org/nextui/assets/35857179/49b28736-e5bc-45a3-9390-71cfb3771fa4)

**Comment by YannickNCode** [comment]
@wingkwong I found the solution. I didn't know I had to add a few extra lines in the tailwind.config.ts file.
Missing lines
`const { nextui } = require('@nextui-org/react');
'./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
plugins: [nextui()],`

Problem solved. Sorry. Have a nice day.
