### ISSUE TITLE
[BUG] - Error al obtener valor de id  usando Autocomplete con Datos dinamicos desde API de Django

### ISSUE THREAD

**Issue by devconstrib** [nextui-org/nextui#3343]
### NextUI Version

2.2.2

### Describe the bug

Estoy intentando usar el control AutoComplete en un formulario para la captura de datos pero tengo un problema con respecto al valor que se captura a la hora de seleccionar puesto que no se captura el id sino que se captura el texto que tiene el autocomplete osea el label. Dejare el codigo de como lo estoy haciendo para saber si es un problema de la forma en la que lo estoy implementando.

```
<div>
    <Controller
        control={control}
        defaultValue={''}
        name="country"
        rules={{
            required: {
                value: true,
                message: "Debes definir la moneda del pais",
            },
        }}
        render={({ field: { onChange, value, ref } }) => (
            <Autocomplete {...register("id_country")} label="Selecina un pais:" className="max-w-xs">
                {countrys.map((country) => (
                    <AutocompleteItem key={country.id} value={country.id}  >
                        {country.name}
                    </AutocompleteItem>
                ))}
            </Autocomplete>
        )}
    />
</div>
```

Deberia asiganar al id_country el valor del key es decir country.id pero me devuelve el valor de country.name

### Steps to Reproduce the Bug or Issue

1- Implementar Autocompleta con carga dinamica de datos desde un api
2-Seleccionar un valor de los mostrados por el autocomplete
3-A la hora de ver los resultados del post del formulario no se muestra el country.id sino que country.name

### Expected behavior

Deberia mostrar country.id como valor en el post

### Screenshots or Videos

![an1](https://github.com/nextui-org/nextui/assets/170656416/944d897a-ccb0-4542-91c3-239da9223842)
![an2](https://github.com/nextui-org/nextui/assets/170656416/908a5c65-3000-4828-ac1e-564febea6d3b)

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by ryo-manba** [comment]
We will not address this.
For more details, please refer to [the comments](https://github.com/nextui-org/nextui/pull/3375#issuecomment-2491442193).
