### ISSUE TITLE
[Feature] - Allow option to render the a selected radio button with a checkmark inside

### ISSUE THREAD

**Issue by cliffordfajardo** [nextui-org/nextui#335]
### Is your feature request related to a problem? Please describe.

Request is not related to a bug

### Describe the solution you'd like

**I would like the option to pass a prop to `<Radio>` component that would allow its selected state to show a checkbox .**
In the image below, I am showing the existing behavior and visualization of what a selected `<Radio>` and `<Checkbox>` input look like.

 I am using a `<Radio> group only because I only to allow the user to select 1 option, but other than that Ideally I would like to have the option to have the `<Radio>` selected state to display a checkbox.

![CleanShot 2022-03-12 at 23 22 08](https://user-images.githubusercontent.com/6743796/158049690-b1b35ed5-a3d5-43b1-9079-dc2d5ba71c03.png)

**Comment by cliffordfajardo** [comment]
What do you think @jrgarciadev ?

**Comment by jrgarciadev** [comment]
Hey @cliffordfajardo I appreciate your suggestion but it breaks the `Radio` guidelines, on the other hand, it looks like you can replace the `Radio` component with `Checkbox` allowing users to select multiples **Categories** and **Tags** at the same time
