### ISSUE TITLE
[BUG] - Table Component - topContent Not Rendering Correctly on "Select All"

### ISSUE THREAD

**Issue by RaiN3772** [nextui-org/nextui#3351]
### NextUI Version

2.4.2

### Describe the bug

When `selectionMode` is set to `multiple`, the selection checkbox appears for selecting rows. However, rendering a component in the `topContent` (e.g., a "Delete Button") based on selected keys works correctly when individual rows are selected but fails to render when all rows are selected using the "Select All" checkbox in the table header.

### Your Example Website or App

https://pastebin.com/raw/hSUqsUf7

### Steps to Reproduce the Bug or Issue

1. Set up the `Table` component with `selectionMode` set to `multiple`.
2. Add a `topContent` component, such as a "Delete Button", that should render when rows are selected.
3. Select individual rows and observe that the `topContent` renders correctly.
4. Use the "Select All" checkbox in the table header to select all rows.

### Expected behavior

The `topContent` (e.g., "Delete Button") should render when all rows are selected using the "Select All" checkbox in the table header, just as it does when individual rows are selected.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/56936836/0f2e9845-b9ae-47e3-bc9e-43173f3e67ff)
![image](https://github.com/nextui-org/nextui/assets/56936836/b1c8c09a-331f-4caa-bd3e-eaacd0ea4d6c)

### Operating System Version

- OS [Windows]

### Browser

Opera

**Comment by wingkwong** [comment]
@RaiN3772 After checking the code, I can confirm that this is not a bug. `selectedKeys` has a `Selection` type, which is either `all` or `Set<React.Key>`. When you select one item, the key will be added to the Set. When you click "select all" checkbox, `selectedKeys` will be set to `all` instead of adding all items to the Set.

Therefore, you can just simply modify your code as below.

```tsx
topContent={
  (selectedKeys === "all" || selectedKeys.size > 0) && (
    <Button className="flex-shrink-0" color="danger">
      Delete
    </Button>
  )
}
```

**Comment by RaiN3772** [comment]
> ```tsx
> (selectedKeys === "all" || selectedKeys.size > 0)
> ```

That worked, thanks alot
