### ISSUE TITLE
Prevent Collapse to open/close using space/enter key ?

### ISSUE THREAD

**Issue by fcannizzaro** [nextui-org/nextui#336]
Hi I'm using a Collapse.Group with many Collapse components that contain a form inside, but every space/enter key is catched from the Collapse component and not from the input fields. There is no way right now to disable this behaviour ?

**Comment by Dhananjay-JSR** [comment]
I guess there exist a Prop named "preventDefault" to disabled default Behavior with ENTER and SPACE Integration have you checked the Documentation page about it ?

**Comment by fcannizzaro** [comment]
yep I tested both true / false but nothing changes

**Comment by jrgarciadev** [comment]
Hey @fcannizzaro thanks for reporting it, we will do our best to include the fix in the next release 🙌🏼
