### ISSUE TITLE
[BUG] - avatar icon not shown in User component

### ISSUE THREAD

**Issue by wingkwong** [nextui-org/nextui#3369]
### NextUI Version

2.4.2

### Describe the bug

In User component, we can pass `icon` to `avatarProps`. However, there is `name` defined in `User`, this will pass to `Avatar` causing to show the initial instead of icon.

_**Need to double check why we pass `name` to `Avatar` instead of not taking from `avatarProps`.**_

### Steps to Reproduce the Bug or Issue

```tsx
<User
    avatarProps={{
        radius: "full",
        size: "sm",
        icon: <AvatarIcon />,
        classNames: {
            base: "bg-gradient-to-br from-[#FFB457] to-[#FF705B]",
            icon: "text-black/80",
        }
    }}
    name="test"
/>
```

![image](https://github.com/nextui-org/nextui/assets/35857179/38caab76-9618-41af-89e5-6c3c137dbae3)

### Expected behavior

If `name` doesn't pass to `avatarProps`, initial shouldn't be shown.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Here's a workaround:

```
avatarProps: {
  radius: "full",
  size: "sm",
  icon: <AvatarIcon />,
  classNames: {
    base: "bg-gradient-to-br from-[#FFB457] to-[#FF705B]",
    icon: "text-black/80",
  },
  name: undefined,
}
```

**Comment by oebh2408** [comment]
> Here's a workaround:
> 
> ```
> avatarProps: {
>   radius: "full",
>   size: "sm",
>   icon: <AvatarIcon />,
>   classNames: {
>     base: "bg-gradient-to-br from-[#FFB457] to-[#FF705B]",
>     icon: "text-black/80",
>   },
>   name: undefined,
> }
> ```

Thank you for the workaround!
