### ISSUE TITLE
Autocomplete does not blur when selecting item

### ISSUE THREAD

**Issue by kamami** [nextui-org/nextui#3379]
### NextUI Version

2.4.2

### Describe the bug

Input of Autocomplete component does not blur when selecting an item from the popover. Using a ref in inputProps to blur manually throws an error when hovering over the popover.

### Steps to Reproduce the Bug or Issue

Just test the example in the docs. There it is also not blurring the input. 

### Expected behavior

I would expect that the input of Autocomplete gets blurred when selecting an item from the popover.

### Operating System Version

macOs

### Browser

Chrome

**Comment by wingkwong** [comment]
That's by design.

**Comment by kamami** [comment]
But how can this be then achieved? I can not pass a ref to the input.

**Comment by wingkwong** [comment]
you may pass the ref to autocomplete component instead of passing to inputProps.  The ref will be forwarded to input.

```tsx
<Autocomplete ref={ref}> 
...
</Autocomplete>
```

**Comment by kamami** [comment]
I tired it an this makes things even worse. With this the input does not blur neither and the popover does not even disappear. 

https://github.com/nextui-org/nextui/assets/43880037/08636f88-b844-4859-a62d-64c18ea82c7a

This is the code: 
```
export default function Search({ nodes, setNodes }) {
  const inputRef = useRef(null);

  return (
    <Autocomplete
      ref={inputRef}
      label="Suche"
      placeholder="Suche eine Person"
      onSelectionChange={(key) => {
        if (inputRef.current) {
          inputRef.current.blur();
        }
      }}
    >
      {nodes.map((person) => (
        <AutocompleteItem key={person.id} value={person.id}>
          {person.data.label}
        </AutocompleteItem>
      ))}
    </Autocomplete>
  );
}
```
