### ISSUE TITLE
[BUG] - Chip component (tag-group-radio-item.tsx) Build fail

### ISSUE THREAD

**Issue by 3n1tan** [nextui-org/nextui#3389]
### NextUI Version

2.4.2 NextUI Pro

### Describe the bug

Project is giving error during build time for deployment due to error ReactNode error coming from Chip component in the Product View Info component(NextUI Pro). See attached screenshot for more details

### Steps to Reproduce the Bug or Issue

i
![netlify](https://github.com/nextui-org/nextui/assets/118386299/62610e30-9047-4e18-9f9c-76203776acd0)

### Expected behavior

No errors should be found when building for deployment

### Screenshots or Videos

![netlify](https://github.com/nextui-org/nextui/assets/118386299/9b0686e9-280b-4ed8-be55-d62b78453a64)

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
please provide a minimal reproducible environment.

**Comment by 3n1tan** [comment]
> @3n1tan Can you DM me in discord? My ID is `wingkwong`.

Thanks so much for the help. Now resolved.

**Comment by wingkwong** [comment]
Will close this issue once we patch the nextui pro.
