### ISSUE TITLE
[BUG] - extendVariants TS Error

### ISSUE THREAD

**Issue by stylehuan** [nextui-org/nextui#3396]
### NextUI Version

2.4.2

### Describe the bug

![image](https://github.com/nextui-org/nextui/assets/6212099/ae9e6b3e-2a33-4b50-a635-85059aecc282)

### Steps to Reproduce the Bug or Issue

<img width="515" alt="image" src="https://github.com/nextui-org/nextui/assets/6212099/db3dafa0-641e-488c-a6f4-a068b11b31cb">

What should I do？

### Expected behavior

normal

### Operating System Version

macOS

### Browser

Chrome

**Comment by winchesHe** [comment]
@stylehuan You should add the following code like example https://nextui.org/docs/customization/custom-variants

```ts
variants: {
    color: {
      olive: "text-[#000] bg-[#84cc16]", // Need
    },
    isDisabled: { // Need
      true: "bg-[#eaeaea] text-[#000] opacity-50 cursor-not-allowed",
    },
    size: {
      xl: "px-8 min-w-28 h-14 text-large gap-4 rounded-medium", // Need
    },
  },
```

Otherwise you can't set the value like `color: "olive", isDisabled, size: "xl"`
