### ISSUE TITLE
[BUG] - Turborepo ui package has broken behavior with compoundVariants

### ISSUE THREAD

**Issue by ellisio** [nextui-org/nextui#3399]
### NextUI Version

2.4.2

### Describe the bug

Using a Turborepo, with PNPM, the `packages/ui` does not respect `compoundVariants` correctly.

### Your Example Website or App

https://github.com/ellisio/nextui-compound-variants-bug

### Steps to Reproduce the Bug or Issue

1. Clone repo
2. Install deps: `pnpm install`
3. Run: `pnpm dev`
4. Open: `http://localhost:3000`
5. Observe the default text color for Danger and Success is black, not white.

### Expected behavior

I expect to see `text-white` when passing `color="danger|success"`. However, `text-<color>-foreground` is still used. What is also interesting, is if I change `defaultVariants.color` to `danger`, or `warning`, then the compound variant _is respected_.

- `compoundVariant` config: https://github.com/ellisio/nextui-compound-variants-bug/blob/main/packages/ui/src/button.tsx#L32-L36

### Operating System Version

macOS

### Browser

Chrome

**Comment by ellisio** [comment]
Also worth noting, I've tried pulling `extendVariants` from both `@nextui-org/react` _and `@nextui-org/system-rsc@canary` as I see there have been changes to this method in both. This issue persists regardless if on stable, or canary.

**Comment by ellisio** [comment]
I managed to get this working by changing `packages/ui/src/button.tsx` to be the following:

```typescript
import { Button as NextUIButton } from "@nextui-org/react";

import { extendVariants } from "./utils";

export const Button = extendVariants(NextUIButton, {
  variants: {
    color: {
      default: "",
      primary: "",
      secondary: "",
      danger: "",
      warning: "",
      success: "",
    },
    variant: {
      solid: "",
    },
  },
  defaultVariants: {
    color: "primary",
    variant: "solid",
  },
  compoundVariants: [
    // solid / color
    {
      variant: "solid",
      color: "default",
      className: "text-black",
    },
    {
      variant: "solid",
      color: "primary",
      className: "text-white",
    },
    {
      variant: "solid",
      color: "secondary",
      className: "text-white",
    },
    {
      variant: "solid",
      color: "danger",
      className: "text-white",
    },
    {
      variant: "solid",
      color: "warning",
      className: "text-black",
    },
    {
      variant: "solid",
      color: "success",
      className: "text-white",
    },
  ],
});
```

Looks like the `customTv` omits `color` and `variant`, which is why none of the `compoundVariants` worked. I would expect `extendVariants` to squash the default theme config, and apply what I set.

This might not actually be a bug, just a misunderstanding of `extendVariants`.

**Comment by tb-b** [comment]
I was wondering the same - would it be possible to set compoundVariants without the need to explicitly set variants as empty values?

```
	variants: {
		color: {
			primary: "",
		},
	}
```
