### ISSUE TITLE
[BUG] - First time choose file with Input file type

### ISSUE THREAD

**Issue by gdschanu-manhdung** [nextui-org/nextui#3401]
### NextUI Version

2.4.1

### Describe the bug

When i choose file from Input type file first time after reloading, I got FileList.length = 0. Everything will be okay from the second choice

### Steps to Reproduce the Bug or Issue

1. Use Input file type
2. Choose file
3. Write a handleChange value to log the filelist
4. Got FileList.length = 0

### Expected behavior

I expected input can be updated at the first time

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/2397
