### ISSUE TITLE
[BUG] - Autocomplete ref does not blur the input

### ISSUE THREAD

**Issue by kamami** [nextui-org/nextui#3404]
### NextUI Version

2.4.2

### Describe the bug

I want the input of the AutoComplete to get blurred when the user selects an item. But this does not happen.

```
export default function Search({ nodes }) {
  const inputRef = useRef(null);

  return (
    <Autocomplete
      ref={inputRef}
      label="Suche"
      placeholder="Suche eine Person"
      onSelectionChange={(key) => {
        if (inputRef.current) {
          inputRef.current.blur();
        }
      }}
    >
      {nodes.map((person) => (
        <AutocompleteItem key={person.id} value={person.id}>
          {person.data.label}
        </AutocompleteItem>
      ))}
    </Autocomplete>
  );
}
```

### Steps to Reproduce the Bug or Issue

[CodeSandbox
](https://codesandbox.io/p/devbox/upbeat-montalcini-scnl3x?file=%2FApp.jsx%3A8%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly5tewls00083b5xv5s9enam%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly5tewlr00033b5xz0ru762j%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly5tewlr00053b5xput4au5x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly5tewlr00073b5xpun1x7p3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly5tewlr00033b5xz0ru762j%2522%253A%257B%2522id%2522%253A%2522cly5tewlr00033b5xz0ru762j%2522%252C%2522activeTabId%2522%253A%2522cly5tewlr00023b5xfl9esjqf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly5tewlr00023b5xfl9esjqf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A1%257D%255D%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522cly5tj38m007k3b5xdk5qo7ag%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cly5tewlr00073b5xpun1x7p3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly5tewlr00063b5xieirdtv3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cly5tewlr00073b5xpun1x7p3%2522%252C%2522activeTabId%2522%253A%2522cly5tewlr00063b5xieirdtv3%2522%257D%252C%2522cly5tewlr00053b5xput4au5x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly5tewlr00043b5xnhm75lgl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cly5tewlr00053b5xput4au5x%2522%252C%2522activeTabId%2522%253A%2522cly5tewlr00043b5xnhm75lgl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
### Expected behavior

I would expect the input of AutoComplete to get blurred.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/43880037/5a48569e-e5cd-4d72-891b-3ea6beac0651

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
When the popover is closed, the focus will be back to the input. This is an internal behaviour. Triggering blur like that would have unexpected behaviour.

**Comment by kamami** [comment]
Do you have any tip or workaround how I can lose the focus of the input when the user selects an item from the popover? It's especially irritating on mobile when the keyboard doesn't disappear.

**Comment by abhinandan-verma** [comment]
@kamami  the thing u mentioned is not a bug, but rather a feature request.
but 2 points will hinder its implementation
1. when the popover is open the input is in focus, how can it be blurred at the same time?
2. with the latest version the popover closes on scrolling on movement, so the blur effect will not be able to come into play

so if you need it, you should try some CSS changes.

**Comment by wingkwong** [comment]
@abhinandan-verma this can't be done by CSS changes

1. he means losing focus after selecting an item, which means the popover is already closed
2. not really related in this case

**Comment by abhinandan-verma** [comment]
@wingkwong  thanks for you clarification
