### ISSUE TITLE
[BUG/Feature Request] DateRangePicker not allowed to pass showMonthAndYearPickers to calendarProps

### ISSUE THREAD

**Issue by Artem2001S** [nextui-org/nextui#3410]
### Is your feature request related to a problem? Please describe.

We can pass showMonthAndYearPickers into DatePicker component. It's user-friendly feature, needed for DateRangePicker component too. 
As described in docs, we can pass showMonthAndYearPickers into DateRangePicker component as calendarProps, but it's not working. 

BUG in docs: 
<img width="801" alt="image" src="https://github.com/nextui-org/nextui/assets/39270533/0d44bac0-4f52-4034-8e3e-03856ef39f7c">
Description for calendarProps same as selectorButtonProps - here https://nextui.org/docs/components/range-calendar

### Describe the solution you'd like

Add props showMonthAndYearPickers to RangeCalendar & DateRangePicker

### Describe alternatives you've considered

None

**Comment by wingkwong** [comment]
duplicate - #3090. Just FYI. There's already a PR under review.
