### ISSUE TITLE
[BUG] - Dropdown menu background color

### ISSUE THREAD

**Issue by rafpaz** [nextui-org/nextui#3411]
### NextUI Version

@nextui-org/dropdown@2.1.26

### Describe the bug

The dropdown menu background color cannot be modified, since the `bg-content1` class  is set on the content slot, but there is no way to access it or modify it.

### Steps to Reproduce the Bug or Issue

1. Add the dropdown component
2. Try to change the background color of the menu component that opens on click

### Expected behavior

As a user, I expect to be able to change the background color of the dropdown menu, but there is no way to do that

### Screenshots or Videos

<img width="730" alt="image" src="https://github.com/nextui-org/nextui/assets/2803345/758a345b-3b91-4b5f-94a6-2b035c65d3d8">

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Just checked. You can simply pass the class to `Dropdown`. 

```tsx
  <Dropdown
    className="bg-red-300" // override bg-content1
  >
    <DropdownTrigger>
      <Button>Trigger</Button>
    </DropdownTrigger>
    <DropdownMenu aria-label="Actions" color={color} variant={variant}>
      <DropdownItem key="new">New file</DropdownItem>
      <DropdownItem key="copy">Copy link</DropdownItem>
      <DropdownItem key="edit">Edit file</DropdownItem>
      <DropdownItem key="delete" className="text-danger" color="danger">
        Delete file
      </DropdownItem>
    </DropdownMenu>
  </Dropdown>
```
