### ISSUE TITLE
[BUG] - Input with File only works after uploading image twice

### ISSUE THREAD

**Issue by Default-01** [nextui-org/nextui#3421]
### NextUI Version

2.4.2

### Describe the bug

Input with File only works after uploading image twice.

```jsx
<Input
	type="file"
	label="Icon"
	accept="image/*"
	isClearable
	onChange={(e) => {
		const file = e.target.files?.item(0);
		if (!file) return;
		setValue("icon", file.name);
	}}
	classNames={{ base: "bg-zinc-100 rounded-lg pl-3" }}
	labelPlacement="outside-left"
/>
```

only after selecting the file for the second time it loads

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

To get the image on the first selection

### Operating System Version

WIN11

### Browser

Chrome

**Comment by wingkwong** [comment]
Duplicate - https://github.com/nextui-org/nextui/issues/2397
