### ISSUE TITLE
[Feature Request] Documentation - Expanded code tab without clicking "Show more"

### ISSUE THREAD

**Issue by kodobrody** [nextui-org/nextui#3423]
### Is your feature request related to a problem? Please describe.

No, more of related to time saving

### Describe the solution you'd like

Show the code snippet in expanded version when clicked "Code" tab in Components' documentation.
Since the user clicking the code tab wants to see the code example and not just a few lines, it would make one click less each time he/she wants to check it.

### Describe alternatives you've considered

Leave it as is

**Comment by wingkwong** [comment]
Duplicate - https://github.com/nextui-org/nextui/issues/3242
