### ISSUE TITLE
[BUG] - onClick handler is not triggered when activating <Button> with keyboard.

### ISSUE THREAD

**Issue by wasimakram-mulla** [nextui-org/nextui#3425]
### NextUI Version

2.4.2

### Describe the bug

As a generic button, the button clicks should be triggered on Spacebars and Enters when onFocus. 

"@nextui-org/react": "^2.4.2",

### Steps to Reproduce the Bug or Issue

Go to [any page](https://nextui.org/docs/components/modal) with <Button> component.
Set focus on <Button> (for example, by tabbing).
Press Spacebar or Enter key.
onClick handler is not triggered, however button shows ":active" state.
Expected behavior
onClick handler is triggered as it normally happens for <button> element in React.

### Expected behavior

onClick handler is triggered as it normally happens for <button> element in React.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wasimakram-mulla** [comment]
Similar discussion was abruptly closed before without any solution [https://github.com/nextui-org/nextui/issues/426](https://github.com/nextui-org/nextui/issues/426)
But the issue still persists and is a **BLOCKER** for me now

**Comment by wasimakram-mulla** [comment]
> [ENG-1118 [BUG] - onClick handler is not triggered when activating <Button> with keyboard.](https://linear.app/nextui-inc/issue/ENG-1118/[bug]-onclick-handler-is-not-triggered-when-activating-button-with)

No Access

**Comment by wingkwong** [comment]
1. The linear link is for internal use. You can ignore it.
2. `onClick` is deprecated. Please use `onPress` instead.

**Comment by ynchen2829** [comment]
> 1. The linear link is for internal use. You can ignore it.
> 2. `onClick` is deprecated. Please use `onPress` instead.

@wingkwong For future iterations, Is it possible to show a `deprecated` message when hovering over `onClick`?

**Comment by wingkwong** [comment]
I remember i've seen in code. need to double check tho. they will be removed eventually.
