### ISSUE TITLE
[BUG] - Compatibility Issue with NextThemesProvider and React 18

### ISSUE THREAD

**Issue by RaiN3772** [nextui-org/nextui#3435]
### NextUI Version

2.4.2

### Describe the bug

When attempting to use the `NextThemesProvider` from the `next-themes` package in a project created with Create React App using React 18, a TypeScript error occurs. The issue seems to be related to the compatibility of `NextThemesProvider` with React Types 18 `"@types/react": "18.3.3"`,. The error does not occur when using React 17 `"@types/react": "17.0.52",`.

**Error Message:**
```
TS2786: 'NextThemesProvider' cannot be used as a JSX component.
  Its return type 'string | number | boolean | Element | Iterable<ReactNode>' is not a valid JSX element.
    Type 'string' is not assignable to type 'ReactElement<any, any>'.
    44 |         />
    45 |         <NextUIProvider>
  > 46 |           <NextThemesProvider defaultTheme="system" attribute="class">
       |            ^^^^^^^^^^^^^^^^^^
    47 |             {children}
    48 |           </NextThemesProvider>
    49 |         </NextUIProvider>
```

**Workaround:**
- Downgrading React to version 17 resolves the issue.

**Potential Cause:**
- The `NextThemesProvider` might have type definitions or internal implementations that are incompatible with React 18's type definitions and component handling.

### Steps to Reproduce the Bug or Issue

1. Create a new React application using Create React App.
   ```bash
   npx create-react-app my-app
   cd my-app
   ```
2. Install the necessary dependencies.
   ```bash
   npm install @nextui-org/react next-themes
   ```
3. Create a provider component in `src/app/providers.tsx` as follows:
   ```typescript
   // app/providers.tsx
   "use client";

   import {NextUIProvider} from '@nextui-org/react'
   import {ThemeProvider as NextThemesProvider} from "next-themes";

   export function Providers({children}: { children: React.ReactNode }) {
     return (
       <NextUIProvider>
         <NextThemesProvider attribute="class" defaultTheme="dark">
           {children}
         </NextThemesProvider>
       </NextUIProvider>
     )
   }
   ```
4. Set up the providers in your application (e.g., in `src/index.tsx` or `src/index.js`).
   ```typescript
   import React from 'react';
   import ReactDOM from 'react-dom/client';
   import './index.css';
   import App from './App';
   import reportWebVitals from './reportWebVitals';
   import { Providers } from './app/providers';

   const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);
   root.render(
     <React.StrictMode>
       <Providers>
         <App />
       </Providers>
     </React.StrictMode>
   );

   reportWebVitals();
   ```
5. Run the application.
   ```bash
   npm start
   ```

### Expected behavior

The application should compile successfully, and the dark/light theme functionality should work correctly with React 18.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/56936836/243c96a3-babb-4a05-b209-0a99853e6f54)

### Operating System Version

Windows

### Browser

Chrome

**Comment by abhinandan-verma** [comment]
@RaiN3772  currently you can use the workaround to solve the issue

```bash
nextui init vite-app
```
and then choosing  `vite app` to create your app. [https://nextui.org/docs/api-references/cli-api](url)

**Comment by RaiN3772** [comment]
> @RaiN3772 currently you can use the workaround to solve the issue
> 
> ```shell
> nextui init vite-app
> ```
> 
> and then choosing `vite app` to create your app. [https://nextui.org/docs/api-references/cli-api](url)
> 
> then you can use the react v18 in your project

Thank you for the suggested workaround. I appreciate your help.

I have a couple of questions before proceeding:

Is this workaround straightforward to implement for a project that's already five months into development?
Will I need to refactor any existing code or make significant changes to integrate this workaround?
Are there any potential issues or limitations I should be aware of when using this method?

**Comment by abhinandan-verma** [comment]
@RaiN3772  I will recommend to create a test app before making any big changes. 
See if your project can  be aligned with the default template.
As per me, the app is very similar to a normal vite app, so you may not need need to make heavy changes(but it solely depends on your project).

**Comment by wingkwong** [comment]
@RaiN3772 By following your steps, I couldn't reproduce the issue. Besides, I've noticed that your provider is under services directory which it doesn't align with your steps. Can you please provide a minimal reproducible environment?

<img width="1387" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/43f37798-fc03-4699-97a2-e7ec0a2b3b08">

Here's my depenedencies

```json
  "dependencies": {
    "@nextui-org/react": "^2.4.2",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "next-themes": "^0.3.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
```

**Comment by RaiN3772** [comment]
> ```ts
> "use client";
> 
> import {NextUIProvider} from '@nextui-org/react'
> import {ThemeProvider as NextThemesProvider} from "next-themes";
> 
> export function Providers({children}: { children: React.ReactNode }) {
>   return (
>     <NextUIProvider>
>       <NextThemesProvider attribute="class" defaultTheme="dark">
>         {children}
>       </NextThemesProvider>
>     </NextUIProvider>
>   )
> }
> ```

You are correct, i just installed a new react app only with nextui and it worked correctly with react types 18
```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@nextui-org/react": "^2.4.2",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "framer-motion": "^11.3.0",
    "next-themes": "^0.3.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "tailwindcss": "^3.4.4",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0"
  }
}
```
im not sure what is wrong with my environment, but i'll investigate more. thanks for pointing it out
