### ISSUE TITLE
[BUG] - Cannot use arrow keys to move cursor in Input or Textarea within an Accordion

### ISSUE THREAD

**Issue by johnmangan** [nextui-org/nextui#3438]
### NextUI Version

2.4.2

### Describe the bug

When working with an `Input` or a `Textarea` component, we can normally move the cursor via the arrow keys on a keyboard. However, this functionality breaks if the `Input` or `Textarea` is within the content of an `Accordion` / `AccordionItem`.

Example where arrow keys fail to move the cursor position:
```
<Accordion>
  <AccordionItem>
    <Textarea />
  <AccordionItem />
<Accordion />
```

### Steps to Reproduce the Bug or Issue

1. Include an `Input` or `Textarea` component within the content of an `AccordionItem` within an `Accordion`.
2. Type any value into the `Input` / `Textarea`.
3. Attempt to move the cursor using the arrow keys.

### Expected behavior

As a user, I expect to be able to change the cursor position via arrow keys within `Input` and `Textarea` components regardless of their parent components.

### Operating System Version

macOs

### Browser

Chrome

**Comment by wingkwong** [comment]
Duplicate - https://github.com/nextui-org/nextui/issues/3364. The fix will be available in the next release.
