### ISSUE TITLE
[BUG] - Autocomplete clear button doesn't work (controlled)

### ISSUE THREAD

**Issue by sabvente** [nextui-org/nextui#3460]
### NextUI Version

2.4.2

### Describe the bug

When using the component as controller, the clear button doesn't work.

Sample code from https://nextui.org/docs/components/autocomplete#fully-controlled

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-kpdcza?file=src%2FApp.jsx

### Steps to Reproduce the Bug or Issue

1. Open stackblitz
2. Click on the Autocomplete component
3. Select something
4. Click the clear button

### Expected behavior

- The selection should be cleared.
- The sample should work in the docs.

### Operating System Version

Windows

### Browser

Chrome

**Comment by drewdearing** [comment]
ran into the same problem #3454. Mitigate the issue until fix is done by downgrading the autocomplate component.

**Comment by sabvente** [comment]
@drewdearing Thanks, then I'm closing this duplicate issue.

**Comment by wingkwong** [comment]
Thanks. Let's track on 3454. I'm currently working on the fix.
