### ISSUE TITLE
Confusing positioning of Popovers

### ISSUE THREAD

**Issue by preitinger** [nextui-org/nextui#3461]
### NextUI Version

2.4.2

### Describe the bug

The positioning of Popovers in the demo (placement set to "right") is wrong or at least very very confusing. Depending on the scrolling state the relative position of popovers is sometimes next to the button which triggers the popover, sometimes outside of the visible area, sometimes very low in the visible area... Extremely confusing. If a popover is related to the button that controls it, it should be next to it. Otherwise it should always be in the center of a container. Whatever it is, it should be reproducable. At least in my opinion. But I am completely newbie in NextUI...

### Steps to Reproduce the Bug or Issue

Click on a button that makes a popover visible.

### Expected behavior

The popover should always be visible without scrolling and always in the same position.

### Operating System Version

Ubuntu

### Browser

Chrome

**Comment by wingkwong** [comment]
Similar to https://github.com/nextui-org/nextui/issues/2778. Can you also share your code so that we could have more insights?

**Comment by abhinandan-verma** [comment]
@wingkwong  I am working on it. And will make PR soon.

**Comment by abhinandan-verma** [comment]
@preitinger  kindly close this issue 
solved by #3487

**Comment by wingkwong** [comment]
Closing - fixed in #3487

**Comment by preitinger** [comment]
I'm sorry, missed your requests :-( Thank you for fixing it!
