### ISSUE TITLE
[QUESTION] - Overriding default Input & Button style

### ISSUE THREAD

**Issue by cliffordfajardo** [nextui-org/nextui#347]
### Describe the bug

Passing a `style` object to `<Input>` to remove the rounded border does not work.
As a user sometimes, would like a rectangular input box

```
<Input
  value="test"
  placeholder="Search..."
  type="search"
  clearable
  size="lg"
  width="100%"
  style={{
    borderRadius: "initial !important", //❌
  }}
/>;
```
Allow user to to remove border-radius from inputs and buttons i

### Steps to Reproduce the Bug or Issue

1. Pass `border-radius: initial !important` to the input component & see that it does not remove the border radius

![CleanShot 2022-03-20 at 07 27 53](https://user-images.githubusercontent.com/6743796/159167288-d5b7dd93-c329-4e0c-bb9a-0b698e559d50.png)

![CleanShot 2022-03-20 at 07 28 55](https://user-images.githubusercontent.com/6743796/159167350-eef2710d-009c-434c-8875-ed17feea986c.png)

### Expected behavior

Passing `border-radius: initial !important` shouls remove the rounded border

### Operating System Version

MacOS

### Browser

Chrome

**Comment by cliffordfajardo** [comment]
I think we we might need to think about an overrides API.
I've seen this used in other libraries like:
-  materialUI: https://mui.com/customization/how-to-customize/
- Uber Base Web: https://baseweb.design/guides/understanding-overrides#understanding-overrides

**Comment by Dhananjay-JSR** [comment]
Hello @cliffordfajardo , NextUI Does Provide different ways to Override Default Styles of Component and ways to create your own component , More Details about which can be found on Official Documentation [Page](https://nextui.org/docs/theme/override-styles)

And coming back to your point to Remove Rounded Corners from Input and Button , the code should be 

`<Button css={{borderRadius: "0"}}>Default</Button>`

  `<Input css={{ $$inputBorderRadius: "0" }} bordered/>`

**Comment by cliffordfajardo** [comment]
@Dhananjay-JSR - ahh thank you!
When might might it be advisable to use`style={{...}}` vs `css={{}}` and vice-versa?
It seems like `css` prop integrates a lot more nicely with the NextUI internals as opposed to `style`
