### ISSUE TITLE
[BUG] -  Card's shadow cut off when nested inside ListBoxItem

### ISSUE THREAD

**Issue by kui04** [nextui-org/nextui#3480]
### NextUI Version

2.4.2

### Describe the bug

The shadow of a Card component nested inside a ListBoxItem is cut off. The `overflow: hidden` property in the `truncate` class appears to be causing this issue.

![QQ_1721108740651](https://github.com/user-attachments/assets/3e11858e-7e7d-4002-ad67-1c9c280d9b2e)
*Notice the corner of the Card*

### Steps to Reproduce the Bug or Issue

1. Create a new project
2. Add listbox and card
3. App.tsx
```tsx
import { Card, CardBody, CardHeader } from "@nextui-org/card";
import { Listbox, ListboxItem } from "@nextui-org/listbox";

function App() {
  return (
    <Listbox aria-label="test">
      <ListboxItem key="test" textValue="test">
        <Card shadow="lg">
          <CardHeader>header</CardHeader>
          <CardBody>body</CardBody>
        </Card>
      </ListboxItem>
    </Listbox>
  );
}

export default App;
```

### Expected behavior

The shadow of the Card should be fully visible and not cut off when nested inside a ListBoxItem. 

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/8abb6b1c-7d56-4686-a7b3-84b365535498)
*shadow is cut off*

![image](https://github.com/user-attachments/assets/35c2e648-9375-4640-8a47-6f1de175f85e)
*after change `overflow:hidden` to `overflow:visible`*

### Operating System Version

Windows

### Browser

Chrome

**Comment by abhinandan-verma** [comment]
@kui04  in which component did you change the `overflow` . can you provide stackblitz or codesandbox for better explanation

**Comment by kui04** [comment]
> @kui04 in which component did you change the `overflow` . can you provide stackblitz or codesandbox for better explanation

I create a codesandbox [here](https://codesandbox.io/p/devbox/nextui-card-shadow-issue-w5sy9f)  with some explanations
It's a `span` inside the `li`.
