### ISSUE TITLE
[BUG] - Table Sort Headers flicker when switching between light and dark theme

### ISSUE THREAD

**Issue by Monkhai** [nextui-org/nextui#3488]
### NextUI Version

2.3.6

### Describe the bug

When switching between light and dark theme, the headers flicker as seen in the video add.

https://github.com/user-attachments/assets/1ddafe95-22df-4a35-ab2a-101f3d14ea25

### Steps to Reproduce the Bug or Issue

1. Use NextUi Table.
2. Choose a column to be sortable.
3. Switch themes using a theme switcher that works on the whole UI.

### Expected behavior

I expect the theme to smoothly change as all the other themes change.

### Screenshots or Videos

https://github.com/user-attachments/assets/cd0b88fb-d638-4300-b5fa-853077e20e3c

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
I couldn't reproduce the issue. Please provide a sandbox.
