### ISSUE TITLE
[BUG] -  Cumulative layout shift  (CLS) is very noticeable and effecting google lighthouse scores

### ISSUE THREAD

**Issue by cliffordfajardo** [nextui-org/nextui#349]
### Describe the bug

It seems like it takes some time for the NextUI to hydrate and style the page causing a very noticeable cumulative layout shift (CLS)

### Steps to Reproduce the Bug or Issue
1. Load app and on first render the cummulative layout shift is shown (see video below)

### Example Website
This website is loading on vercel
- https://www.microdiscount.website/

### Expected behavior
As a user I should not notice a huge cumulative layout shift

## What I think is happening
- its taking NextUI a long time to parse the JS & by the time the JS is executed, its been 500ms of time which has passed; 500ms is the limit google gives you before layouts are considered harmful. If you have layout shifts before 500ms they are not used against you it seems
- https://github.com/WICG/layout-instability#Recent-Input-Exclusion

### Operating  & Browser System Version
- MacOS, Chrome Latest
- Using Remix as the SSR JS framework

### Screenshots or Videos
https://user-images.githubusercontent.com/6743796/159179931-8d61e410-445d-4d25-92b4-1698ac1b14a0.mp4

![CleanShot 2022-03-20 at 12 46 02](https://user-images.githubusercontent.com/6743796/159180016-3f216e44-c784-4538-a3c4-4c15ac252ebd.png)

**Comment by cliffordfajardo** [comment]
Ok - i was able to find the solution thanks to @jrgarciadev.
I wasn't generating the stylesheets on the server & doing them all clientside
That instantly fixed the CLS problem

https://user-images.githubusercontent.com/6743796/159186509-71138593-151f-4628-ae3c-a8a1fa618793.mp4


### Follow Ups
I was only able to solve this problem because I was using a SRR based solution with React and the server side method to generate the stylesheets on the server: https://nextui.org/docs/guide/nextui-plus-nextjs#next.js

If I was limited to a client side app, this wouldn't have solved my issue unfortunately.

I think we should consider leaving this issue open as this is not solved on the client side.
I don't know the internals of NextUI well, but I imagine there might be some optimizations, or restructuring of the code to reduce the layoutshift?

**Comment by jrgarciadev** [comment]
Hey @cliffordfajardo you are welcome, excellent that you find out the solution, could you share with us the code you applied in your Remix project? (if possible), in order to help other users. 

Regarding your question about solving this issue on the client-side, it's not possible due to if you are using SSR you have to `flush` / `load` the styles on the server otherwise you will have CLS, on the other hand, if you are using plain `React` you will not have this problem because there's not a preloading process on the server

**Comment by cliffordfajardo** [comment]
I added `{CssBaseline.flush()}`  to the head as in the docs for NextJS
- https://nextui.org/docs/guide/nextui-plus-nextjs#next.js

Example:

![CleanShot 2022-03-20 at 17 09 44@2x](https://user-images.githubusercontent.com/6743796/159191952-3d256931-09b4-4e39-ba81-47c7f807452a.png)

**Comment by V01D-NULL** [comment]
What's the V2 equivalent of this? @cliffordfajardo 
Preferably keeping SSR
