### ISSUE TITLE
[BUG] - DateInput extendVariants not working

### ISSUE THREAD

**Issue by rettimo** [nextui-org/nextui#3502]
### NextUI Version

2.4.3

### Describe the bug

An error occurs when using `DateInput` with `extendVariants`. 

```typescript
import {
  extendVariants,
  DateInput as NextUiDateInput,
  DateInputProps as NextUiDateInputProps,
} from '@nextui-org/react';

import { ForwardRefRenderFunction, ReactElement } from 'react';

export interface DateInputProps extends NextUiDateInputProps {}

export const DateInput: ForwardRefRenderFunction<ReactElement, DateInputProps> = extendVariants(NextUiDateInput, {});
```

![image](https://github.com/user-attachments/assets/1c85c375-534f-4578-a6c2-d355aaff3603)

### Steps to Reproduce the Bug or Issue

1. Use `DateInput` with `extendVariants`
2. Get an error

### Expected behavior

Ability to use `extendVariants` as in all other components

### Operating System Version

macOS Sonoma 14.5

### Browser

Chrome

**Comment by hugo-lovighi** [comment]
I have the same issue extending Spinner

**Comment by wingkwong** [comment]
@hugo-lovighi can you also share your code?

**Comment by hugo-lovighi** [comment]
Of cource ! 
I add a new size to nextui spinner according to [https://nextui.org/docs/customization/custom-variants](https://nextui.org/docs/customization/custom-variants) documentation.

_Spinner.tsx_ component:
```
import { Spinner as NextUiSpinner } from '@nextui-org/spinner'
import { SpinnerProps } from '@nextui-org/spinner/dist/spinner'
import { extendVariants } from '@nextui-org/system'

export const ExtendedSpinner = extendVariants(NextUiSpinner, {
    variants: {
        size: {
            xs: {
                wrapper: 'h-4 w-4',
                circle1: 'border-2',
                circle2: 'border-2',
                label: 'text-xs'
            },
        },
    },
})

type ExtendedSpinnerProps = Omit<SpinnerProps, 'size'> & {
    size?: 'xs' | 'sm' | 'md' | 'lg'
}

export const Spinner = (props: ExtendedSpinnerProps) => <ExtendedSpinner {...props} />
```

_package.json_ after this @nextui update:

```
        "@nextui-org/pagination": "^2.0.33",
        "@nextui-org/progress": "^2.0.31",
        "@nextui-org/radio": "^2.1.2",
        "@nextui-org/skeleton": "^2.0.29",
        "@nextui-org/spinner": "^2.0.30",
        "@nextui-org/switch": "^2.0.31",
        "@nextui-org/system": "^2.2.2",
        "@nextui-org/tabs": "^2.0.32",
        "@nextui-org/theme": "^2.2.6",
```
 to
```
        "@nextui-org/pagination": "^2.0.34",
        "@nextui-org/progress": "^2.0.32",
        "@nextui-org/radio": "^2.1.3",
        "@nextui-org/skeleton": "^2.0.30",
        "@nextui-org/spinner": "^2.0.31",
        "@nextui-org/switch": "^2.0.32",
        "@nextui-org/system": "^2.2.3",
        "@nextui-org/tabs": "^2.0.33",
        "@nextui-org/theme": "^2.2.7",
```

I got this error when I try to render the Spinner with the variant size (other sizes working fine)

![Screenshot from 2024-07-18 14-10-43](https://github.com/user-attachments/assets/c2adbecf-a62f-4aac-9778-be3f416f41d1)

I try to fix this issue but without success.

**Comment by hugo-lovighi** [comment]
Thanks a lot ! Ok we downgraded temporarily the dependencies. We are waiting patiently :)

**Comment by sethchurch** [comment]
I've been running into this issue as well. It seems adding a key of defaultVariants with a empty object value seems to work as a workaround for now.
