### ISSUE TITLE
[BUG] - DateRangePicker not showing multiple months correctly after 2.4.3 update

### ISSUE THREAD

**Issue by razvanilin** [nextui-org/nextui#3504]
### NextUI Version

2.4.3

### Describe the bug

The DateRangePicker calendar view is broken when `visibleMonths` is set to any value higher than 1. The Calendar header shows correctly, but only the first month table is shown. 

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-jtg1mt?file=src%2FApp.jsx

### Steps to Reproduce the Bug or Issue

Add `visibleMonths` attribute to the picker and the Calendar view will be broken. Can check the docs site to see the issue too: https://nextui.org/docs/components/date-range-picker#visible-months

### Expected behavior

All the months should be visible in the calendar view

### Screenshots or Videos

![CleanShot 2024-07-18 at 19 58 02@2x](https://github.com/user-attachments/assets/5ab99c5d-a248-4fdb-b95c-03f31cb1a67a)

### Operating System Version

macOS, Ubuntu 22.04

### Browser

Chrome

**Comment by abhinandan-verma** [comment]
@wingkwong  uploading PR within a few minutes issue solved
