### ISSUE TITLE
[Feature Request] Support Carousel Component

### ISSUE THREAD

**Issue by hkkxx** [nextui-org/nextui#3506]
### Is your feature request related to a problem? Please describe.

I like the style of NEXTUI and the extended Attributes and api for components, but I haven't found  `<Carousel />` components , hope to add it in the future.
3Q 

like this：
![image](https://github.com/user-attachments/assets/28c0e2e0-c970-4f1f-8bb0-50aacbc9e50f)

### Describe the solution you'd like

Support dynamic incoming img (or div ?) list, support automatic carousel,  set the direction of rotation, rotation length, and more I did not immediately think of.

### Describe alternatives you've considered

The example in the picture is what I saw in "daisyui" , but I prefer the style and usage of the Nexus UI. Hopefully the component UI will have more interaction with the data.。
3Q 

### Screenshots or Videos

![屏幕截图 2024-07-19 012946](https://github.com/user-attachments/assets/0a1a95c2-35b1-43fe-83cc-7765447e2fdd)

**Comment by wingkwong** [comment]
Duplicate - keep track in https://github.com/nextui-org/nextui/issues/2177
