### ISSUE TITLE
[BUG] - show warn after install nextui-org/react 

### ISSUE THREAD

**Issue by pjatupon** [nextui-org/nextui#3511]
### NextUI Version

2.4.5

### Describe the bug

![image](https://github.com/user-attachments/assets/416e2c0a-4903-4be8-8b85-1bb351b4c3e1)

### Steps to Reproduce the Bug or Issue

after install `npm i @nextui-org/react framer-motion`

### Expected behavior

after install `npm i @nextui-org/react framer-motion`

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/593e5d83-44db-4ba5-9268-67fa29653958)

### Operating System Version

windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
Thanks for reporting. We've noticed this issue as well. The team is working on it.

**Comment by wingkwong** [comment]
Fixed in v2.4.6.
