### ISSUE TITLE
The postion of select is always sticky when scroll the container box or body 

### ISSUE THREAD

**Issue by AungKyawKhiang007** [nextui-org/nextui#3514]
### NextUI Version

2.2.2

### Describe the bug

https://github.com/user-attachments/assets/9affae39-9e75-4cc8-8a05-3d92dd3e1730

### Steps to Reproduce the Bug or Issue

![Screenshot 2024-07-19 221752](https://github.com/user-attachments/assets/23ebd4a7-a989-4ead-ad61-c58d70c81f49)

### Expected behavior

![Screenshot 2024-07-19 221734](https://github.com/user-attachments/assets/2814822a-ddd9-4cbf-a521-3eb6b775d81b)

### Screenshots or Videos

Uploading 20240719_221631.MP4…

### Operating System Version

windows linux, mac

### Browser

Chrome

**Comment by wingkwong** [comment]
Please use the latest version. The select should be closed when scrolling.

**Comment by yairopro** [comment]
@wingkwong 
The issue still exists with the last version
https://codesandbox.io/p/devbox/nextui-select-sticky-issue-3514-p439fj

**Comment by wingkwong** [comment]
@yairopro I cloned your sandbox to my local to run and didn't see the issue. The select should be closed when scrolling outside.

[3514-demo.webm](https://github.com/user-attachments/assets/6f0d0ccf-1aef-4957-b5cc-4e4fcc03f98e)
