### ISSUE TITLE
[BUG] - Input

### ISSUE THREAD

**Issue by CreativeArtDesign** [nextui-org/nextui#3517]
### NextUI Version

latest doc

### Describe the bug

import {Input} from "@nextui-org/react";

wrong input in code.. it should be input not react??

### Steps to Reproduce the Bug or Issue

Only code error in code examples

### Expected behavior

Only code error in code examples

### Operating System Version

any

### Browser

Chrome

**Comment by wingkwong** [comment]
If you are installing the package [individually](https://nextui.org/docs/guide/installation#individual-installation), then you use `@nextui-org/input`. 
If you are installing the package [globally](https://nextui.org/docs/guide/installation#global-installation), then you use `@nextui-org/react`.
