### ISSUE TITLE
[BUG] - DOCS Code editor 

### ISSUE THREAD

**Issue by TIMMLOPK** [nextui-org/nextui#352]
### Describe the bug

Code editor 's text don't change under the dark mode 

### Steps to Reproduce the Bug or Issue

Switch to dark mode 

### Expected behavior

The text color may change 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/72869479/159204597-efef01b7-f79d-4ff8-9e6b-8914ece8b988.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @TIMMLOPK thanks for fast reporting 🙌🏻

**Comment by jrgarciadev** [comment]
Hey @TIMMLOPK I've made a rollback due to I haven't found the solution yet, hope to release the new version asap it's full of new features https://github.com/nextui-org/nextui/pull/354

**Comment by TIMMLOPK** [comment]
@jrgarciadev I am looking forward for the new version🥳

**Comment by jrgarciadev** [comment]
Hey @TIMMLOPK this have been fixed 👍🏻
