### ISSUE TITLE
Autocomplete component doesn't show items (list options) properly in diveces like mobile or tablet

### ISSUE THREAD

**Issue by mdsanchezcieza** [nextui-org/nextui#3524]
This component works good in devices like desktop. But in devices like mobile and tablet the items aren't showing properly. I attached some videos to explain better.

https://github.com/user-attachments/assets/1bf22f6f-8a35-404d-a0ee-2f28a5f64c56

https://github.com/user-attachments/assets/4474624b-4e6d-4d13-a4a1-ca9b9c0b601a

I hope someone can help me. Thanks in advance.

**Comment by abhinandan-verma** [comment]
@mdsanchezcieza  can you provide codesandbox or stackblitz reproducing the bug.
the component is working fine for all type of screens, both in storybook and docs.

**Comment by mdsanchezcieza** [comment]
> @mdsanchezcieza can you provide codesandbox or stackblitz reproducing the bug. the component is working fine for all type of screens, both in storybook and docs.

Hello Abhinandan. 
This is my repository:
https://github.com/mdsanchezcieza/ibs-practicas/tree/main/NEXT/ecomerce-components

The autocomplete component shows the items but the color of the text of each item it's the same that background color of the component and for this reason they can't see. This happen in devices like mobile or tablet.

And this the url of my project deployed en vercel platform for more detail of the issue:
https://components-one-gilt.vercel.app/

Thanks and advance

**Comment by wingkwong** [comment]
This is how it looks from my side

![image](https://github.com/user-attachments/assets/aaa9c197-3de9-4eea-9f4d-075803a4030b)

**Comment by mdsanchezcieza** [comment]
Ah! I checked again and it works now. I don't know exactly what happened. The last action I took was to update NextUI to the latest version. Sorry for the inconvenience, but I really appreciate the quick support.
I will definitely use these components in my projects.

Thank you very much

**Comment by mdsanchezcieza** [comment]
Thansk a lot!!!
