### ISSUE TITLE
Checkbox click behavior change after double clicked disable checkbox items

### ISSUE THREAD

**Issue by MinChanSike** [nextui-org/nextui#3528]
### NextUI Version

~~2.4.2~~ 2.4.6

### Describe the bug

Need double click to check/uncheck normal checkbox after clicking isDisabled checkbox item.

https://github.com/user-attachments/assets/d6b4c87a-de0a-46d6-81b1-19f5b2ab51c6

Please take a look sample here.
https://codesandbox.io/p/devbox/ancient-hooks-7h9mnn

### Steps to Reproduce the Bug or Issue

To simulate, only click checkbox check/uncheck container, does not click the label.

### Expected behavior

Click behavior should not change to check/uncheck checkbox.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
Able to reproduce even in 2.4.6.

**Comment by sohan01fw** [comment]
@MinChanSike  i tried this in firefox it works fine but not in chrome browser.

**Comment by abhinandan-verma** [comment]
@wingkwong  bug reproducible with `RadioGroup` and. `Switch`  too

**Comment by abhinandan-verma** [comment]
> @MinChanSike i tried this in firefox it works fine but not in chrome browser.

Only chrome is showing this behaviour, not in safari too

**Comment by abhinandan-verma** [comment]
@zymalvin  issue solved :), you'll get it as soon it's merged
