### ISSUE TITLE
[Feature Request] Image/file picker component

### ISSUE THREAD

**Issue by MiloWang2048** [nextui-org/nextui#3529]
### Is your feature request related to a problem? Please describe.

No, but input type=file is the last part of a daily working form component that nextui missing. We really need it.

### Describe the solution you'd like

Make a file picker, adapted to current form styles, and incoming `<form>` component.

### Describe alternatives you've considered

None, I just wrote it myself, but it looks wired. What we really need is actually your design!

**Comment by wingkwong** [comment]
We do support `type=file` in input - https://storybook.nextui.org/?path=/story/components-input--input-types&globals=locale:bg-BG. Is it what you want?

**Comment by abhinandan-verma** [comment]
@MiloWang2048  I believe that 
```zsh
<Input type="file" />
```

should fulfill your need. If not kindly specify the you expectation for the component.
So that we can help you.
