### ISSUE TITLE
Date Picker - selectorIcon Prop not displaying Icon

### ISSUE THREAD

**Issue by hectarescraps** [nextui-org/nextui#3532]
### NextUI Version

@nextui-org/date-picker@2.1.2

### Describe the bug

I've designated Heroicons' _Calendar Days_ icon as my Date Picker Selector Icon, but when loading the component, no icon appears. See code below. 

`<DatePicker
              className="text-orange-500 font-light text-sm "
              label=""
              defaultValue={now(getLocalTimeZone())}
              granularity="day"
              isRequired
              hideTimeZone
              selectorIcon={<CalendarDaysIcon />}
              popoverProps={{
                placement: "bottom",
                shouldFlip: false,
                backdrop: "opaque",
              }}
            />`

### Steps to Reproduce the Bug or Issue

Implement <DatePicker /> component with custom selectorIcon prop.

### Expected behavior

Expected to see Heroicons CalendarDays icon as my custom selectorIcon. Instead, saw no icon at all.

### Screenshots or Videos

<img width="1019" alt="Screenshot 2024-07-22 at 9 37 48 PM" src="https://github.com/user-attachments/assets/6c1f29d8-b932-46e1-88a2-4ee87abc1b73">

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
can you share your `CalendarDaysIcon` as well

**Comment by abhinandan-verma** [comment]
@hectarescraps  on the  [heroicons website](https://heroicons.com/outline) copying `jsx` or `svg` both copies `svg` code (I don't know if it is a bug on their part)
I used this code and it works completely fine 

```zsh
  <DatePicker  selectorIcon={<Image src="/calendar.svg" alt="calendar" width={20} height={20} />}  />
```
<img width="197" alt="Calendar Image" src="https://github.com/user-attachments/assets/ac63d36e-225f-41cb-af88-aa199143ea4d">

**Comment by hectarescraps** [comment]
Thank you so much @abhinandan-verma - got it working on my end as well now. Closing.
