### ISSUE TITLE
[Feature Request] Ability to increase Slider hit area for pointers.

### ISSUE THREAD

**Issue by ameytessact** [nextui-org/nextui#3543]
### Is your feature request related to a problem? Please describe.

In the first slider from the given image, a user has a pretty small hitarea (the grey track) on which the value changes. 

### Describe the solution you'd like

It would be good if developer could change the hitarea size from a prop or if it always had a larger hitarea in height.

### Describe alternatives you've considered

Radix UI Slider works has a larger hitarea than the shown track area: https://www.radix-ui.com/primitives/docs/components/slider

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/e8830bf9-c9a3-4849-b419-53e2e3391179)

**Comment by abhinandan-verma** [comment]
@ameytessact  The library already have size prop for different  [sizes](https://nextui.org/docs/components/slider#sizes) of slider, and it should cover most of your needs

**Comment by ameytessact** [comment]
Oh, my bad!
Thanks.

**Comment by abhinandan-verma** [comment]
@ameytessact  No issue.  Kindly close the issue as completed
Happy to help you :)
