### ISSUE TITLE
[BUG] - Styles are all messed up when attempting to use nextUI with Bun & a monorepo (repro included)

### ISSUE THREAD

**Issue by harrisrobin** [nextui-org/nextui#3556]
### NextUI Version

2.4.6

### Describe the bug

As you can see here: https://cm-mono-web.vercel.app/quote/0, the nextUI styles are completely broken. 

I'm not sure why because I followed all the instructions on installing nextUI into my project, including properly pointing my ROOT node_modules in my tailwind.config file.

Here's a repo that reproduces the issue:
https://github.com/anomalylabsinc/cm-mono

### Your Example Website or App

https://cm-mono-web.vercel.app/quote/0

### Steps to Reproduce the Bug or Issue

1. Go to website here: https://cm-mono-web.vercel.app/quote/0
2. See completely broken styles
3. See repo that implements nextUI according to docs here: https://github.com/anomalylabsinc/cm-mono

### Expected behavior

I expect nextUI to look as advertised in my website when i install it on a fresh project.

### Screenshots or Videos

![CleanShot 2024-07-25 at 14 34 18@2x](https://github.com/user-attachments/assets/2647a4a5-5d0d-40f1-bd02-f3d8ae601894)

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
please contact me at discord. my id is same as my github one.
