### ISSUE TITLE
Issue - Calendar component app crash on vercel

### ISSUE THREAD

**Issue by KundwaBruno** [nextui-org/nextui#3560]
### NextUI Version

2.4.6

### Describe the bug

I recently upgraded to nextui version 2.4.6 in order for me to use the perfect DatePicker and Calendar components. Howver once i run the app locally, it runs fine without any BUGS, but on vercel the app crashes and in the logs it displays the error below.

Tried using vercel's node version and the build was still running fine without errors.

```
Error: Cannot find package '/var/task/node_modules/@react-aria/calendar/node_modules/@react-stately/utils/package.json' imported from /var/task/node_modules/@react-aria/calendar/node_modules/@react-aria/utils/dist/import.mjs
Did you mean to import "@react-stately/utils/dist/main.js"?
    at legacyMainResolve (node:internal/modules/esm/resolve:219:26)
    at packageResolve (node:internal/modules/esm/resolve:845:14)
    at moduleResolve (node:internal/modules/esm/resolve:931:18)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:1173:14)
    at defaultResolve (node:internal/modules/esm/resolve:1216:79)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/'
}
```

Local node version: 22.2.0
Vercel node version: 20.x

### Steps to Reproduce the Bug or Issue

The Issue comes on vercel only

### Expected behavior

Should run without the app crashing

### Operating System Version

MacOs

### Browser

Chrome

**Comment by abhinandan-verma** [comment]
Seems like this [issue](https://github.com/vercel/next.js/discussions/49834) on NextJs

kindly follow these steps -

1. Try to resolve all warnings
2. Run `npm run lint` on the local environment, and check for errors
3. Set env variable `CI = false` and run `npm ci --include=dev`,    CI = true considers warnings as errors

See if the error stills persists.
Kindly follow the above steps and confirm again

**Comment by KundwaBruno** [comment]
@abhinandan-verma Thanks for the quick response,  

1. I have cleared all errors and warnings, currently`npm run lint` shows no errors or warnings
2. Which environment should i run `npm ci --include=dev` because locally the app runs fine until i push it to vercel.

**Comment by abhinandan-verma** [comment]
@KundwaBruno  you should run it remotely, observe the changes (if any).
Confirm if you still have the issue.

**Comment by KundwaBruno** [comment]
Okay, kindly guide me where to add this @abhinandan-verma

**Comment by abhinandan-verma** [comment]
@KundwaBruno  for your help, I deployed a test app with `Calendar` component on `Vercel`, and  deployment was successful. Maybe you are having some configuration or dependency conflict issue. 
here is app and repo link
[repo](https://github.com/abhinandan-verma/test-ui)
[app](https://test-ui-woad.vercel.app/)

I will recommend, compare the configurations with your own app with mine one , update your  dependencies. Hopefully you should get your issue resolved.

**Comment by abhinandan-verma** [comment]
@KundwaBruno  are you still facing the same issue?
did you compare the configuration and dependencies?

Kindly confirm

**Comment by KundwaBruno** [comment]
Now i just got another one after i updated my dependency version to the ones in your repo.

```
⨯ Error: Cannot find package '/var/task/node_modules/@nextui-org/slider/node_modules/@react-aria/ssr/package.json' imported from /var/task/node_modules/@nextui-org/slider/node_modules/@react-aria/i18n/dist/useDefaultLocale.mjs
Did you mean to import "@react-aria/ssr/dist/main.js"?
    at legacyMainResolve (node:internal/modules/esm/resolve:219:26)
    at packageResolve (node:internal/modules/esm/resolve:845:14)
    at moduleResolve (node:internal/modules/esm/resolve:931:18)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:1173:14)
    at defaultResolve (node:internal/modules/esm/resolve:1216:79)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/'
}
```

I'm use the pages router tho

@abhinandan-verma

**Comment by KundwaBruno** [comment]
@abhinandan-verma You still there?

**Comment by wingkwong** [comment]
@KundwaBruno please share a minimal reproducible environment.

**Comment by KundwaBruno** [comment]
@wingkwong I reverted back to version 2.4.10 os nextui/react and it worked, not sure if it's issue within next-ui itself

**Comment by wingkwong** [comment]
Closing - not able to reproduce.

**Comment by hmbrg** [comment]
I'm having the exact same issue, also just on Vercel and while using Pages router.

**Comment by notrealradical** [comment]
Having the same issue with Vercel and Remix

**Comment by syskin** [comment]
I faced the same issue with the following stack : 
- Nextjs 14.2.14
- @nextui-org/react 2.4.8

Local and remote build works correctly, no any warn or errors.
I'm using the page router.

I don't use the Calendar component in my project.

It causes my app crashes on Vercel :

```
⨯ Error: Cannot find package '/var/task/node_modules/@nextui-org/calendar/node_modules/@react-aria/i18n/node_modules/@react-stately/utils/index.js' imported from /var/task/node_modules/@nextui-org/calendar/node_modules/@react-aria/i18n/node_modules/@react-aria/utils/dist/import.mjs Did you mean to import "@react-stately/utils/dist/main.js"? at legacyMainResolve (node:internal/modules/esm/resolve:219:26) at packageResolve (node:internal/modules/esm/resolve:845:14) at moduleResolve (node:internal/modules/esm/resolve:931:18) at moduleResolveWithNodePath (node:internal/modules/esm/resolve:1173:14) at defaultResolve (node:internal/modules/esm/resolve:1216:79) at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12) at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25) at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38) at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40) at link (node:internal/modules/esm/module_job:95:36) { code: 'ERR_MODULE_NOT_FOUND', page: '/features' }
Oct 06 09:42:47.73
GET
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
```

I have the same behaviour for `date-picker` component :

`⨯ Error: Cannot find package '/var/task/node_modules/@nextui-org/date-picker/node_modules/@react-aria/i18n/node_modules/@react-stately/utils/index.js' imported from /var/task/node_modules/@nextui-org/date-picker/node_modules/@react-aria/i18n/node_modules/@react-aria/utils/dist/import.mjs`

I downgraded @nextui-org/react to 2.3.6, and everything works as expected.

**Comment by luixo** [comment]
This happened to me on Vercel, not being able to import `/node_modules/@nextui-org/card/node_modules/@react-aria/interactions/node_modules/@react-aria/utils/index.js` in my case.
I just made an upgrade from `2.2.9` to `2.4.8`.

**Comment by KundwaBruno** [comment]
Seems like we need to dynamically import the specific NextUI component responsible for the issue ( whether calendar input or date picker input and set ssr: false ). This ensures the component is only rendered on the client side, avoiding potential server-side rendering conflicts that may cause the crash. However I think this should be a temporary work around

**Comment by luixo** [comment]
As I decided to upgrade anyway, everything broke again with this error.
I found and fixed 2 errors in Vercel logs:
- Too many imports of the `CalendarDate.mjs`
I found the similar [issue](https://github.com/adobe/react-spectrum/issues/6394) (though no the same error) in `@react-aria` repo and made a simple fix (see [patch](https://gist.github.com/luixo/d1954b001280b81b1250ea55b0e149ee)) as well as opened a [PR](https://github.com/adobe/react-spectrum/pull/8001) to fix it for good.
- Package import problem
I'm not sure what exactly caused import to break, but I suggested it could be ESM imports in deeply nested modules (I've got `/var/task/node_modules/@heroui/card/node_modules/@react-aria/interactions/node_modules/@react-aria/utils/index.js` which seem to be quite deep) or mismatching module import.
I found that `@react-aria/utils` had multiple versions in my `yarn.lock`, specifically both `3.28.0` and `3.28.1`.
I pinned `3.28.1` via `resolutions` in `package.json` which fixed the problem.

**Comment by Abhishek1350** [comment]
Same error with React Router on vercel:

Build is successfull but getting runtime error, not even using this calendar component

`file:///var/task/node_modules/@heroui/react/dist/utils/calendar.js:1
import { startOfYear as $14e0f24ef4ac5c92$export$f91e89d3d0406102 } from '../node_modules/.pnpm/@internationalized_date@3.11.0/node_modules/@internationalized/date/dist/queries.js';
         ^^^^^^^^^^^
SyntaxError: The requested module '../node_modules/.pnpm/@internationalized_date@3.11.0/node_modules/@internationalized/date/dist/queries.js' does not provide an export named 'startOfYear'
    at #asyncInstantiate (node:internal/modules/esm/module_job:302:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async ModuleJob.run (node:internal/modules/esm/module_job:405:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:660:26)
    at async d (/opt/rust/nodejs.js:17:25130)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.`


`react-router.config.ts
import type { Config } from "@react-router/dev/config";
import { vercelPreset } from '@vercel/react-router/vite';
export default {
  // Config options...
  // Server-side render by default, to enable SPA mode set this to `false`
  ssr: true,
   presets: [vercelPreset()],
} satisfies Config;
`


`
 "dependencies": {
    "@heroui/react": "^3.0.0-beta.7",
    "@heroui/styles": "^3.0.0-beta.7",
    "@prisma/adapter-pg": "^7.4.2",
    "@prisma/client": "^7.4.2",
    "@react-router/fs-routes": "7.12.0",
    "@react-router/node": "7.12.0",
    "@react-router/serve": "7.12.0",
    "@vercel/react-router": "^1.2.5",
    "class-variance-authority": "^0.7.1",
    "i": "^0.3.7",
    "isbot": "^5.1.31",
    "lucide-react": "^0.575.0",
    "react": "^19.2.4",
    "react-dom": "^19.2.4",
    "react-router": "7.12.0"
  },
`
