### ISSUE TITLE
[BUG] - Variable updates in Modal don't work

### ISSUE THREAD

**Issue by bao-io** [nextui-org/nextui#3564]
### NextUI Version

2.4.2

### Describe the bug

just simple code in the below，you can run anywhere，when i click the button, the button text content is updated in a work, but not update in the Modal body, I'm not sure if this is a bug.
```js
"use client";

import { Button, Modal, ModalBody, ModalContent } from "@nextui-org/react";
import { useState } from "react";

export default function Page() {
  const [show, setShow] = useState(false);
  const [nums, setNums] = useState(0);

  return (
    <>
      <Button onClick={() => setShow(true)}>{nums}</Button>
      <Modal isOpen={show} onOpenChange={setShow}>
        <ModalContent>
          <ModalBody onClick={() => setNums((s) => ++s)}>{nums}</ModalBody>
        </ModalContent>
      </Modal>
    </>
  );
}
```

### Steps to Reproduce the Bug or Issue

just simple code in the below，you can run anywhere
```js
"use client";

import { Button, Modal, ModalBody, ModalContent } from "@nextui-org/react";
import { useState } from "react";

export default function Page() {
  const [show, setShow] = useState(false);
  const [nums, setNums] = useState(0);

  return (
    <>
      <Button onClick={() => setShow(true)}>{nums}</Button>
      <Modal isOpen={show} onOpenChange={setShow}>
        <ModalContent>
          <ModalBody onClick={() => setNums((s) => ++s)}>{nums}</ModalBody>
        </ModalContent>
      </Modal>
    </>
  );
}
```

### Expected behavior

Expect nums variables to be re rendered in the modeal and update their views

### Operating System Version

macos

### Browser

Chrome

**Comment by abhinandan-verma** [comment]
@bao-io  I tried the same code and everything seems perfectly fine.
Maybe you just need to update the version to the latest, and you problem is solved.


https://github.com/user-attachments/assets/3a821fe6-5e4c-40a9-b9cf-39161e255a83

**Comment by abhinandan-verma** [comment]
@bao-io  I have also used  NextJs, more specifically I made a test app to solve your issue from,   [NextUI CLI](https://nextui.org/docs/api-references/cli-api) tool, following the simple guidelines. You can try with `NexttUIProvider` way too, both behave similarly

**Comment by abhinandan-verma** [comment]
Kindly provide sandbox or stackbllitz  for efficient debugging

**Comment by abhinandan-verma** [comment]
@bao-io  you may rebuild your app  cleaning the npm cache and node_modules.
Most probably everything should work fine. 
if not kindly confirm
else close the issue as completed  

you may refer to this one #3565

**Comment by alejandro-almeida-improving** [comment]
does anyone know why this happens? I have the same issue
