### ISSUE TITLE
[BUG] - Input in Modal does not update contents

### ISSUE THREAD

**Issue by jim-king-2000** [nextui-org/nextui#3565]
### NextUI Version

2.4.6

### Describe the bug

Input control in a Modal component does not update the content.

### Steps to Reproduce the Bug or Issue

```jsx
'use client';

import { Modal, ModalContent, ModalHeader, ModalBody, Button, useDisclosure, Input } from '@nextui-org/react';
import { useState } from 'react';

export default function Page() {
	const { isOpen, onOpen, onOpenChange } = useDisclosure();
	const [text, setText] = useState('');
	return (
		<div>
			<Button onPress={onOpen} color='primary'>
				Open Modal
			</Button>
			<Modal isOpen={isOpen} onOpenChange={onOpenChange} placement='top-center'>
				<ModalContent>
					{(onClose) => (
						<>
							<ModalHeader className='flex flex-col gap-1'>Log in</ModalHeader>
							<ModalBody>
								<Input value={text} onValueChange={setText} />
							</ModalBody>
						</>
					)}
				</ModalContent>
			</Modal>
		</div>
	);
}
```
1. Click "Open Modal" button.
2. Type in the Input.

Note that the input control does not update.

### Expected behavior

Input control should work. The characters typed in should be updated.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by abhinandan-verma** [comment]
@jim-king-2000  I tried with your code and things are working completely fine.
see here
There may be some other issues like configuration or dependency.
Kindly check and confirm again.  I used the [NextUI App Template](https://github.com/nextui-org/next-app-template) for test purpose

https://github.com/user-attachments/assets/c5038b7a-b5e3-4725-883c-0a68a82799cd

**Comment by aokihu** [comment]
I have the same problem too, there aren't work on windows 11 and macOS. the problem was triggered after updated new version.

**Comment by abhinandan-verma** [comment]
@aokihu  @jim-king-2000  can you provide codesandbox  or stackblitz showing the issue.
So that I can help you better,  bcz I am not able to reproduce the bug

**Comment by qmonmert** [comment]
@abhinandan-verma https://github.com/qmonmert/reactapp you can reproduce the bug here 🙂

**Comment by shabanbx** [comment]
Not Just Input Control the useState used inside modal is not working at all, all my previously working forms inside the modals are broken now

**Comment by abhinandan-verma** [comment]
@shabanbx  can  you share some relevant code of form, package.json and NextUI configuration,

More preferably a sandbox showing the error 
I will be able to debug it efficiently

**Comment by shabanbx** [comment]
@abhinandan-verma this happened after upgrading from 2.3.6 to 2.4.6  but you uploaded the video above with the same version and its working for you. so what i did was

rm -rf node_modules
rm -rf package-lock.json

then 

npm cache clean --force

after that installed again with 2.4.6 (npm i) and the issue is gone and the useState is working again inside the modal

**Comment by abhinandan-verma** [comment]
@shabanbx  its good if the issue is resolved 

@jim-king-2000  @qmonmert   you may follow the similar steps 
And see if your issue is resolved 
(do only if doesn't harms your app in any other way)

Kindly confirm if the issue is resolved

**Comment by qmonmert** [comment]
@abhinandan-verma I confirm, issue is resolved, thanks

**Comment by abhinandan-verma** [comment]
@jim-king-2000 you can also rebuild your app  cleaning the npm cache.
confirm if error still exists
else kindly close the issue as completed 

Thank you

**Comment by jim-king-2000** [comment]
Confirmed and closed.
