### ISSUE TITLE
[Feature Request] Add selectionMode="multiple" to Autocomplete component

### ISSUE THREAD

**Issue by SIC4DA** [nextui-org/nextui#3567]
### Is your feature request related to a problem? Please describe.

in the doc i'v seen selectionMode prop used in the Autocomplete component but when i tried to use it doesn't exist i found out that its not included in the [Autocomplete Props] section its only in the [Asynchronous Loading] Autocomplete  docs

### Describe the solution you'd like

i'd like to be able to select multiple option in the Autocomplete  component as in the select 

### Describe alternatives you've considered

adding the selectionMode to the Autocomplete component

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/9ad18bf5-3bad-4dcd-ba3b-910a588b9443)

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/2109
