### ISSUE TITLE
[BUG] - SyntaxError: Named export 'useImperativeHandle' not found.

### ISSUE THREAD

**Issue by ronniechoyy** [nextui-org/nextui#3570]
### NextUI Version

2.4.6

### Describe the bug

I'm using nextjs with page router.
Run normally on lcoal dev, once deploy to vercel, when direct to some pages the routing will fail, even the page is not contain any nextui element.

module versions:
 "@nextui-org/react": "^2.4.6",
 "react": "^18.2.0",
 "next": "^14.0.0",

```
file:///var/task/node_modules/@nextui-org/react-utils/dist/chunk-RQNQ5XFG.mjs:5
  useImperativeHandle,
  ^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'useImperativeHandle' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
```

### Steps to Reproduce the Bug or Issue

Failed only on vercel

### Expected behavior

Sucessfully route to the page

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by wingkwong** [comment]
please share a minimal reproducible environment.

**Comment by ronniechoyy** [comment]
Sorry, I tried to create a repo toreproducible environment but found out the issue is not reproduce on it.
And I end up to remove the NextUIProvider.
