### ISSUE TITLE
incorrect semantic color in select component

### ISSUE THREAD

**Issue by iPanda007** [nextui-org/nextui#3579]
### NextUI Version

2.4.6

### Describe the bug

My primary sematic color is green When I was using the select listItem is always base on primary sematic color is blue ,Its only happen in select component , I would like to suggest you should add slot in listItem for overide thanks  

![Screenshot 2024-07-30 171129](https://github.com/user-attachments/assets/3100bece-fd87-4370-9865-f7ff1f3942d5)

### Steps to Reproduce the Bug or Issue

![Screenshot 2024-07-30 171129](https://github.com/user-attachments/assets/2475550b-db70-4486-826f-57ba3a614966)

### Expected behavior

My primary sematic color is green When I was using the select listItem is always base on primary sematic color is blue ,Its only happen in select component , I would like to suggest you should add slot in listItem for overide thanks  

### Operating System Version

window

### Browser

Chrome

**Comment by iPanda007** [comment]
https://github.com/user-attachments/assets/8419c6e7-5049-47ef-9d5e-78421b1221c7

**Comment by abhinandan-verma** [comment]
@iPanda007  kindly share the sandbox or stackblitz, reproducing the error you are facing.

**Comment by iPanda007** [comment]
@abhinandan-verma , Thanks I already configure customize theme with semantic color in tailwind.config.ts , It has not been worked listItem from select component ,Its has been happened replace default base next ui color ,Its only in select component

**Comment by abhinandan-verma** [comment]
@iPanda007  sorry, but I am not able to understand what you actually meant?

Can you a little clearer grammar ?

**Comment by iPanda007** [comment]
@iPanda007 Ahh! Sorry for my grammar , I am not able to share to sandbox or stackblitz  , I mean customize theme semantic color not working the select component , I provide with mp4 and screenshot thanks

**Comment by iPanda007** [comment]
I believe that Next Ui  will be the best bcz I love it

**Comment by wingkwong** [comment]
@iPanda007 please share your tailwind.config.ts

**Comment by wingkwong** [comment]
Closing - inactivity
