### ISSUE TITLE
[BUG] - NEXTUI Does not work on Vercel Production Deployment in Nextjs14

### ISSUE THREAD

**Issue by tavik000** [nextui-org/nextui#3585]
### NextUI Version

2.4.6

### Describe the bug

![image](https://github.com/user-attachments/assets/0c7f102e-8ca9-4186-b7d1-d6f483b2bd3e)

I am using Dropdown and Modal in my blog project and I am using Next 14.2.5 with NextUI 2.4.6

it work fine in localhost, but does not work in vercel production deployment (DropdownItem size weird, and the modal popup does not show)

this is localhost
![image](https://github.com/user-attachments/assets/5903fccc-5a6d-4d06-9107-9b2efa51549c)
![image](https://github.com/user-attachments/assets/c7b49782-7981-4687-96e7-5aef1e8d7def)

and there is vercel production deployment
![image](https://github.com/user-attachments/assets/500ea5f2-0fc3-4e2a-914b-efd7ac231bd5)
![image](https://github.com/user-attachments/assets/87adba6a-9af2-46e4-ab0f-0ac1475be13a)

 

### Your Example Website or App

https://react-key-blog-remake.vercel.app/en

### Steps to Reproduce the Bug or Issue

click user button at top right corner, you will see the dropdown sign in button look not correct,
click sign in button, you will see nothing popup

### Expected behavior

sign in button look same with localhost
sign in popup modal popup correctly like localhost

### Operating System Version

Window

### Browser

Chrome

**Comment by theonlyway** [comment]
It very much does work if you set it up correctly. Your site however, has none of the NextUI tailwind classes present in any of your CSS files so check your config

**Comment by tavik000** [comment]
I was followed the manual installation because my project exist before using NextUI.

this is my tailwind.config.ts

```ts
import type { Config } from 'tailwindcss';
const {nextui} = require("@nextui-org/react");

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontSize: {
        '13px': '13px',
        '14px': '14px',
        '28px': '28px',
      },
      gridTemplateColumns: {
        '13': 'repeat(13, minmax(0, 1fr))',
      },
      colors: {
        blue: {
          400: '#2589FE',
          500: '#0070F3',
          600: '#2F6FEB',
        },
      },
      height: {
        '400px': '400px',
      },
      width: {
        '1200px': '1200px',
      },
      minWidth: {
        '32px': '32px',
        '40px': '40px',
        '54px': '54px',
      },
      minHeight: {
        '32px': '32px',
        '40px': '40px',
      },
      boxShadow: {
        '0550': '0 5px 5px 0 rgba(0, 0, 0, 0.3)',
        '02': '0 2px rgba(0, 0, 0, 0.2)',
      },
      maxWidth: {
        '400px': '25rem',
        '1140px': '1140px',
      },
      padding: {
        '3px': '3px',
        '5px': '5px',
        '11px': '11px',
        '1em': '1em',
      },
      margin: {
        '5px': '5px',
      },
    },
    keyframes: {
      shimmer: {
        '100%': {
          transform: 'translateX(100%)',
        },
      },
    },
  },
  darkMode: "class",
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography'), [nextui()]],
};
export default config;

```

@theonlyway

**Comment by tavik000** [comment]
my folder structure

https://github.com/tavik000/ReactKeyBlogRemake

**Comment by tavik000** [comment]
![image](https://github.com/user-attachments/assets/3e6b77b9-9622-466d-915f-7223eb287c10)
I do have the env var

**Comment by tavik000** [comment]
after added correct env var, it fixed. 

I refer this to solve 
https://github.com/nextui-org/nextui/issues/2599
