### ISSUE TITLE
[BUG] - Switch not toggling when text is highlighted

### ISSUE THREAD

**Issue by DawidAbram** [nextui-org/nextui#3586]
### NextUI Version

2.4.6

### Describe the bug

The switch is not toggleable when some text on the page is highlighted/selected. Can be viewed even on the documentation page for the [switch](https://nextui.org/docs/components/switch) component.

### Your Example Website or App

https://nextui.org/docs/components/switch

### Steps to Reproduce the Bug or Issue

1. Select some text on the page with the switch
2. Try to toggle the switch

![Screenshot 2024-07-31 at 18 35 00](https://github.com/user-attachments/assets/b61d090b-fba3-4f0c-b949-14fe0a61cea7)

It will only work if you double click, and not always.

### Expected behavior

As a user, I would expect the focus to change to the switch and it to toggle without a problem.

### Operating System Version

macOS

### Browser

Chrome

**Comment by DawidAbram** [comment]
For anyone that has this issue, a temporary solution I applied is to create a wrapper component which has an onClick that will remove the text selection:

`onClick={(e) => {
        window.getSelection()?.removeAllRanges();
        props.onClick?.(e);
      }}`

**Comment by awesome-pro** [comment]
@DawidAbram  this issue will be closed by #3552

Kindly close the issue
