### ISSUE TITLE
[BUG] - Table - isStriped doesn't display with removeWrapper

### ISSUE THREAD

**Issue by alexnguyennz** [nextui-org/nextui#3587]
### NextUI Version

2.4.6

### Describe the bug

isStriped doesn't display with removeWrapper. If you remove `removeWrapper`, the stripes appear as expected.

### Your Example Website or App

https://codesandbox.io/p/devbox/quiet-mountain-22nvn9

### Steps to Reproduce the Bug or Issue

View table

### Expected behavior

Stripes appear

### Operating System Version

Windows

### Browser

Chrome

**Comment by Asweh-Debrej** [comment]
I noticed that the `data-odd` attribute gets missing when I applied `removeWrapper`
![image](https://github.com/user-attachments/assets/ff40f8a8-8210-4821-83d4-801a8068bc9b)
![image](https://github.com/user-attachments/assets/30745fd1-9ef7-4cd8-9d1b-f25afbfd4990)

**Comment by alexnguyennz** [comment]
This seems to be fixed now - tried the same code in a new scaffolded NextUI project and config in nextui's storybook and it's all working there.
