### ISSUE TITLE
[Feature Request] Remix example & update NextUI docs for how to setup with Remix

### ISSUE THREAD

**Issue by cliffordfajardo** [nextui-org/nextui#359]
### Is your feature request related to a problem? Please describe.

As a user who is using [Remix](https://remix.run/) for their React app, it would be nice to see an example of NextUI used with Remix

**TODO:**
- I will create a Pull request here for docs
    - related to this issue that was resolved: https://github.com/nextui-org/nextui/issues/349#event-6271818665
- I will create an example inside Remix's `examples` folder: https://github.com/remix-run/remix/tree/main/examples

I recently created a NextUI app with Remix so I'm familiar with the experience
- https://github.com/cliffordfajardo/micro-discounts

https://user-images.githubusercontent.com/6743796/159693791-4b01d759-527b-438b-bd24-9e01dd1917fa.mp4

**Comment by jrgarciadev** [comment]
Looking forward to it 🙌🏻
