### ISSUE TITLE
[BUG] - Table Pagination, First page not selected 

### ISSUE THREAD

**Issue by 7laria** [nextui-org/nextui#3590]
### NextUI Version

^2.4.6

### Describe the bug

When I load a list of items and the page value is set to 1, the page item style is not shown untill I don't change page and go back to the previous one.

<img width="508" alt="Screenshot 2024-08-01 alle 13 40 55" src="https://github.com/user-attachments/assets/3b04ec8f-a326-4f6a-a79d-fdbfd004cb39">

`
 const [page, setPage] = useState(1);
 <Pagination
          isCompact
          showControls
          showShadow
          color="secondary"
          page={page}
          total={pages}
          onChange={(page) => setPage(page)}
        />
`

### Steps to Reproduce the Bug or Issue

Just copy and paste the  [pagination component](https://nextui.org/docs/components/table#paginated-table)

### Expected behavior

<img width="486" alt="Screenshot 2024-08-01 alle 13 44 33" src="https://github.com/user-attachments/assets/362225a5-97dc-46c5-b6e8-cd579becaa5f">

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Is your pagination component rendered using `display:hidden` for the first time, and then switching to `display:block`? If not, please share a minimal reproducible environment for us to investigate.

**Comment by jesserizzo** [comment]
I'm just running into this same problem. For me, it appears to be that the `total` prop is set to 0 at first render. In my case this is because I'm using `tableInstance.getPageCount()` from React table to get my total number of pages, but here's a minimal reproduction.

```import { Pagination } from "@nextui-org/react";
import { useEffect, useState } from "react";

export const Pagination = () => {
  const [totalPages, setTotalPages] = useState<number>(0);

  useEffect(() => setTotalPages(10), [setTotalPages]);

  return <Pagination total={totalPages} page={2} />;
};
```

It works as long as the `total` prop is set to equal or higher than the `page` prop on first render. For example, if I set `totalPages` to 3 in the state initialization, this would work fine.

**Comment by wingkwong** [comment]
@jesserizzo please provide a sandbox instead.

**Comment by jesserizzo** [comment]
https://codesandbox.io/p/devbox/snowy-voice-3pzk2s

**Comment by wingkwong** [comment]
@awesome-pro please take a look

**Comment by awesome-pro** [comment]
I am working on it

**Comment by awesome-pro** [comment]
@jesserizzo  I have debugged your issue, and found it to be a logical one.
Actually you have given the initial value to `totalPages` as `0`.  For any page number(>0), `totalPages` will be lesser than the page number,  
which should not be the case,
`typescript` is interpreted language, not compiled, code runs line by line.  So after assigning `totalPages={0}` and  `activePage=2`, the `usePagination` fun is called, before setting`totalPages`  to 10,.
`activePage` can be calculated as 2 (for eg), but how would pagination be possible with `totalPages<0` and  `activePage>0`
hence are issue arises (if you notice, clicking on another key, swipes the blue color from left that is 0);

```zsh
export const Test = () => {
  const [totalPages, setTotalPages] = useState(0);  // THIS is the where the main issue starts

  useEffect(() => setTotalPages(10), [setTotalPages]);

  return (
    <div className="gap-2 flex flex-col">
      <Pagination page={2} total={totalPages} />
    </div>
  );
};

```

see here

<img width="1018" alt="Screenshot 2024-08-03 at 5 45 06 PM" src="https://github.com/user-attachments/assets/07bf4fff-749a-4ea4-848a-4bd7ef3c866f">
<img width="1105" alt="Screenshot 2024-08-03 at 5 47 01 PM" src="https://github.com/user-attachments/assets/59080b11-e7c4-46bf-8160-53f1e22f2f71">


you can use same code without any error if you take initial value of `totalPage` to be more than `page` in any case. Like this

```zsh
const Test = () => {
  const [totalPages, setTotalPages] = useState(10);

  useEffect(() => setTotalPages(10), [setTotalPages]);

  return (
    <div className="gap-2 flex flex-col">
      <Pagination page={2} total={totalPages} />
    </div>
  );
};
```


https://github.com/user-attachments/assets/2644e585-fd04-4df6-b462-cd3abfde8444

I am working to ensure the proper working of pagination in such cases too.
above one is a workaround for now :)

**Comment by MarcusDelvecchio** [comment]
Adding conditional check for a total number of pages before rendering the `<Pagination/>` component resolved this for me. See Below.

`{ pages &&
        <Pagination
        isCompact
        showControls
        showShadow
        color="secondary"
        page={page}
        total={pages}
        onChange={(page) => setPage(page)}
    />
                        }`

**Comment by 7laria** [comment]
@wingkwong here a sandbox to reproduce the error: https://codesandbox.io/p/devbox/pagination-issue-wx96n3

**Comment by 7laria** [comment]
> Is your pagination component rendered using `display:hidden` for the first time, and then switching to `display:block`? If not, please share a minimal reproducible environment for us to investigate.

No, I've shared a sandbox in the previous comment :)

**Comment by 7laria** [comment]
I've solved this error using a useEffect approach instead of using directly the prop value.
`useEffect(()=>{
      setPages(Math.ceil(props.rows.length / rowsPerPage))
    },[props.rows])`

**Comment by melodyxpot** [comment]
> @jesserizzo I have debugged your issue, and found it to be a logical one. Actually you have given the initial value to `totalPages` as `0`. For any page number(>0), `totalPages` will be lesser than the page number, which should not be the case, So after assigning `totalPages={0}` and `activePage=2`, the `usePagination` fun is called, before setting`totalPages` to 10. `activePage` can be calculated as 2 (for eg), but how would pagination be possible with `totalPages<0` and `activePage>0` hence are issue arises (if you notice, clicking on another key, swipes the blue color from left that is 0);
> 
> ```shell
> export const Test = () => {
>   const [totalPages, setTotalPages] = useState(0); // THIS is the where the main issue starts
>  
>   useEffect(() => setTotalPages(10), [setTotalPages]);
>  
>   return (
>     //code//
>   );
> };
>  
> ```
> 
> see here
> 
> <img alt="Screenshot 2024-08-03 at 5 45 06 PM" width="1018" src="https://private-user-images.githubusercontent.com/147910430/354817577-4a9fa276-cd36-4237-a656-95e95f5fb26d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODUwODgsIm5iZiI6MTczMDE4NDc4OCwicGF0aCI6Ii8xNDc5MTA0MzAvMzU0ODE3NTc3LTRhOWZhMjc2LWNkMzYtNDIzNy1hNjU2LTk1ZTk1ZjVmYjI2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwNjUzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjU4ODkwNzgyODg5NmJiMDhiYzY4YThjODJhMjMxZDRlZDUxODY2NGVlNTIyYTIxZTZmZDdhYTg1OGQwYmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FuERWxQw_Ru5iXKVJmXnhzwAdvFLkaklbXC7ymzASxI"> <img alt="Screenshot 2024-08-03 at 5 47 01 PM" width="1105" src="https://private-user-images.githubusercontent.com/147910430/354817586-d2dbee03-c216-49e4-b10a-640bc453c86a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODUwODgsIm5iZiI6MTczMDE4NDc4OCwicGF0aCI6Ii8xNDc5MTA0MzAvMzU0ODE3NTg2LWQyZGJlZTAzLWMyMTYtNDllNC1iMTBhLTY0MGJjNDUzYzg2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwNjUzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjRhY2IwYzc1NDBjMDY0Mjc5YzUzYWZhMmMzNjI3OTY3YTRjZjExYTQ0MjBmNDk2NjM2MTA3YzY3OTAzMjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8aSc8MrdvuaVGXj0fFvPKthB_2mJOWLuv7fQPqg0laQ">
> you can use same code without any error if you take initial value of `totalPage` to be more than `page` in any case. Like this
> 
> ```shell
> const Test = () => {
>   const [totalPages, setTotalPages] = useState(10);
> 
>   useEffect(() => setTotalPages(10), [setTotalPages]);
> 
>   return (
>     <div className="gap-2 flex flex-col">
>       <Pagination page={2} total={totalPages} />
>     </div>
>   );
> };
> ```
> 
>  pagination-after-setting-totalPage-10.mov 
> I am working to ensure the proper working of pagination in such cases too. above one is a workaround for now :)

Yeah this answer was helpful. I had the same issue so I set total pages as 1 at first and then it worked.
Thank you.

**Comment by Eriktse** [comment]
I just facing the same issue, my solution is ensuring page <= total, like this:
```typescript
{page <= total && <Pagination ... />}
```

**Comment by nghiepdev** [comment]
I had a similar problem—the issue was with the `total` prop. When I fetched data from the API, the initial `total` value wasn’t accurate, so the `Pagination` component didn’t update when `total` changed. What worked for me was adding `key={total}` to the `Pagination` component, which forces it to remount whenever `total` changes.

```tsx
<Pagination key={totalPages} total={totalPages} />
```
