### ISSUE TITLE
[BUG] - DropdownItem cannot be wrapped in Tooltip

### ISSUE THREAD

**Issue by tovaschreier** [nextui-org/nextui#3591]
### NextUI Version

```
"@nextui-org/dropdown": "^2.1.29", 
"@nextui-org/tooltip": "^2.0.39",
```

### Describe the bug

The allowed children for `Dropdown` is quite restrictive - only `DropdownItem`s can be rendered within it, and even wrapping a `DropdownItem` in a `div` fails catastrophically with `Unknown element <div> in collection.` This means we can't display a tooltip when hovering on a dropdown item - it completely breaks the dropdown's ability to render.

It would be incredibly useful to be able to pass any children to `Dropdown` as long as they ultimately render a `DropdownItem` (even if we need to take some extra steps, like creating a separate component for a dropdown item wrapped in a tooltip, and manually forwarding the ref to the dropdown item). 

### Steps to Reproduce the Bug or Issue

Try wrapping a DropdownItem in a Tooltip:

```
<Dropdown>
  <DropdownTrigger>
    <Button>Open Menu</Button>
  </DropdownTrigger>

  <DropdownMenu>
    <Tooltip content="tooltip">
      <DropdownItem title="Option 1" />
    </Tooltip>
    <DropdownItem title="Option 2" />
  </DropdownMenu>
</Dropdown>
```

Current behavior: when you click on the dropdown trigger, the entire dropdown fails to display - instead it throws an error like `Unknown element <[object Object]> in collection.`

### Expected behavior

The dropdown item should display as expected, and hovering on it should display the tooltip

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Dropdown is a collection-based component. Adding other elements would make the parsing fail in RA side. You may need to put `Tooltip` inside `DropdownItem` instead.

**Comment by tovaschreier** [comment]
Thanks for the quick response @wingkwong! Totally understand that this is an RA restriction - but it seems like it should be possible to use `forwardRef` to tell the Dropdown that the DropdownItem is ultimately the collection element to target...

Re: your suggested workaround, I tried putting `Tooltip` inside `DropdownItem`, but didn't see that working at all - the tooltip didn't show up on hover. If there is a way to display a tooltip on a dropdown item, I'd love to see an example on the docs explaining how!

**Comment by wingkwong** [comment]
Probably you need to set the width and height 100% to parent (dropdown item).

**Comment by Lornz-** [comment]
I confirm there's still an issue when utilizing a `Tooltip` within a `DropdownItem`. Setting the width and height to 100% does not resolve the problem. When explicitly setting `isOpen` to `true`, the tooltip does appear. The apparent issue lies within the hover event.
