### ISSUE TITLE
[BUG] - Popover closes on scroll

### ISSUE THREAD

**Issue by monster99d2** [nextui-org/nextui#3594]
### NextUI Version

2.4

### Describe the bug

I have a popover filled with a lot of content usually requiring me to scroll down to see the rest. I've found a stable version to be 2.3, but on anything 2.4 and higher the moment I begin scrolling the popover immediately closes. 

### Steps to Reproduce the Bug or Issue

1. Make a popover
2. Click it so it opens
3. Scroll

### Expected behavior

I expected it to stay open as I'm scrolling until I either click out of the popover or click the button to trigger it again.

### Operating System Version

macOS

### Browser

Chrome

**Comment by awesome-pro** [comment]
@monster99d2  this is not  bug, but rather a newly added  feature  by #3414

**Comment by monster99d2** [comment]
How do I stop this from happening?

**Comment by wingkwong** [comment]
If you scroll inside the popover, it won't close. It only closes when you scroll outside.

**Comment by AnYiEE** [comment]
> If you scroll inside the popover, it won't close. It only closes when you scroll outside.

@wingkwong It seems not to be the case. I use [NextUI 2.4.6](https://github.com/AnYiEE/touhou-mystia-izakaya-assistant/blob/v0.6.5/package.json#L76), on my website, it always gets closed when scrolling.

Reproduction steps:
1. Visit [my website](https://izakaya.cc/customer-rare).
2. Click on any avatar on the left side.
3. Click on the gear icon at the newly appeared card on the right side.
4. Move the mouse over the popover card and scroll.

The actual effect is that the popover is still closed.

The [source code link](https://github.com/AnYiEE/touhou-mystia-izakaya-assistant/blob/v0.6.5/app/(pages)/customer-rare/settingsButton.tsx#L51) of that component. It is worth noting that the popover itself does not have any additional states for controlling open and close, only specifying the props `showArrow offset={10} placement="bottom-end"`.

**Comment by wingkwong** [comment]
@AnYiEE The popover card is not scrollable so it is actually scrolling outside. Therefore it will close. Abhinandan has made a PR to introduce a new prop to disable the scroll. I think that would cover your case.

**Comment by AnYiEE** [comment]
> @AnYiEE The popover card is not scrollable so it is actually scrolling outside. Therefore it will close. Abhinandan has made a PR to introduce a new prop to disable the scroll. I think that would cover your case.

@wingkwong Your mean that this behavior is only related to whether the content in the card can scroll, not the position of the mouse? But when there is a lot of content in the card, like in my example, clicking on the first accordion in the popover card, which has a lot of content that exceeds the screen. I think it is not very easy to determine the maximum height of the popover itself in this case. It would be more intuitive to scroll by moving the mouse over or touch, instead of directly prohibiting closing the popover while scrolling.

**Comment by oatkiller** [comment]
I'm still fighting with this as well. I have a popover that is guaranteed to cause a scroll on the parent (but the tooltip's anchor is 'sticky' and is fine.)
