### ISSUE TITLE
[BUG] - Date Input margins VS Input margins

### ISSUE THREAD

**Issue by tomerbar2903** [nextui-org/nextui#3596]
### NextUI Version

@nextui-org/date-input@2.1.3

### Describe the bug

When the labelPlacement is set to `outside`, Input and DateInput behave differently, which makes it very hard to align a section with both Inputs and DateInputs. When inspected, I managed to see that the label of the Input component in positioned in an `absolute` manner (on top of its margin, whereas the label component of the DateInput is positioned regularly (in the components content).

### Steps to Reproduce the Bug or Issue

1. Create a section / div
2. Make that div `flex` `flex-col` `space-y-10`
3. Add 2 Input components
4. Add 1 DateInput component underneath them
5. See? the spacing is different

### Expected behavior

Labels that are positioned `outside` should be a part of the component's content, not margin

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/ee3bd27a-f5d1-4c9a-981b-0be7ce87e7ba)

### Operating System Version

All

### Browser

Chrome

**Comment by wingkwong** [comment]
please share a minimal reproducible environment

**Comment by wingkwong** [comment]
Closing - inactivity
