### ISSUE TITLE
[BUG] - incorrect year in date picker in fa-IR

### ISSUE THREAD

**Issue by wingkwong** [nextui-org/nextui#3602]
### NextUI Version

2.4.6

### Describe the bug

reported from

- https://github.com/nextui-org/nextui/issues/2842#issuecomment-2266755078
- https://github.com/nextui-org/nextui/issues/2842#issuecomment-2266755078

### Steps to Reproduce the Bug or Issue

1. change to locale ` fa-IR`
2. the year range is not correct

### Expected behavior

The year should be correct with the locale ` fa-IR`

### Operating System Version

macOS

### Browser

Chrome

**Comment by MhEsn** [comment]
Hi again 
After updating to newer version after @wingkwong merge request. I still have year problem in date picker.
May we can solve it together?
@wingkwong

**Comment by wingkwong** [comment]
@MhEsn We haven't released yet. It's likely done tmr.

**Comment by MhEsn** [comment]
@wingkwong Thanks then.

**Comment by MhEsn** [comment]
Hi again,
I'm still waiting for the release. When do you think it will releases?
thanks
@wingkwong

**Comment by wingkwong** [comment]
it's out already. please upgrade to 2.4.8.

**Comment by mortezafallahi** [comment]
This problem still exists, and there is also a problem with the slider and pagination in the fa-IR locale.
