### ISSUE TITLE
docs: add more package runners

### ISSUE THREAD

**Issue by Jay-Karia** [nextui-org/nextui#3605]
### Is your feature request related to a problem? Please describe.

Here https://nextui.org/docs/guide/cli#without-installation, there is a CLI script to install the package without global installation which uses `npx`.
What about the users using `pnpm`, `yarn`, or `bun`?

### Describe the solution you'd like

I would like to add different tabs for package runners like in this [page](https://nextui.org/docs/guide/cli#global-installation).

yarn - `yarn dlx`
pnpm - `pnpm dlx`
bun - `bun x`

### Describe alternatives you've considered

Add new tabs.

### Screenshots or Videos

<img width="626" alt="Untitled" src="https://github.com/user-attachments/assets/2ae7a7eb-186c-4f95-8f18-98320a654db1">

**Comment by Jay-Karia** [comment]
Should we close this ?

**Comment by wingkwong** [comment]
@Jay-Karia This will be closed when the PR is closed, which will happen in the coming days.

**Comment by Jay-Karia** [comment]
Thought that the PR was merged
