### ISSUE TITLE
[BUG] - loading svg error

### ISSUE THREAD

**Issue by hhniao** [nextui-org/nextui#3613]
### NextUI Version

2.4.6

### Describe the bug

./node_modules/slick-carousel/slick/slick-theme.css:17:159
Module not found: Can't resolve './fonts/slick.svg#slick'
  15 |     src: url('./fonts/slick.eot');
  16 |     src: url('./fonts/slick.eot?#iefix') format('embedded-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('truetype'), url('./fonts/slick.svg#slick') format('svg');
> 17 | }
     |  ^

### Your Example Website or App

https://codesandbox.io/p/devbox/new-night-8nwzdf

### Steps to Reproduce the Bug or Issue

the docs label

### Expected behavior

let it work

### Operating System Version

windows

### Browser

Chrome

**Comment by wingkwong** [comment]
the error is thrown from slick-carousel. don't think it's related to NextUI.

**Comment by hhniao** [comment]
@wingkwong 
hi, 
do you have take a look codesanbox?  it is look like thrown from slick-carousel.
i have create a project with nextjs project, it is work.

this demo it is work, only nextjs, no next-ui
[codesanbox](https://codesandbox.io/p/devbox/lingering-glitter-zflv69)

**Comment by wingkwong** [comment]
I removed nextui from your first sandbox and still able to reproduce the issue. probably it is caused by other dependencies.

**Comment by hhniao** [comment]
the first demo is create from [next-app-template](https://github.com/nextui-org/next-app-template)
can you tell me how to fix it? i have try it, not work

**Comment by hhniao** [comment]
@wingkwong 
hi, 
i found it.
```
	"scripts": {
		-- "dev": "next dev --turbo",
                ++ "dev": "next dev",
	},
```
turbopack not support *.svg#fragment
