### ISSUE TITLE
 Make Table  use-case example  overflow scrollable

### ISSUE THREAD

**Issue by massdx** [nextui-org/nextui#3618]
### Is your feature request related to a problem? Please describe.

When you select all the columns for the view.
It appears but the table is not scrollable  the overflow is hidden which blocks other information 

### Describe the solution you'd like

Add an overflow auto or scrollable to the components table to nativly manage it without the user managing it himself

### Describe alternatives you've considered

table should be scrollable 

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/d96e7e04-61bc-4ef3-904d-79596a4f09f7)

**Comment by wingkwong** [comment]
1. do you mean when the column popover is open, the table cannot be scrolled? 
2. please provide a minimal reproducible environment

**Comment by massdx** [comment]
1. when we  display all columns  in the popover
2.  the table  cannot be scrolled  to view all columns

**Comment by wingkwong** [comment]
So when you choose more columns to display, the width of the table is increasing and you mean horizontal scrolling is not available in your case right? Still, please provide a minimal reproducible environment.

**Comment by massdx** [comment]
EXACTLY

**Comment by wingkwong** [comment]
assuming you're talking about this [use case example](https://nextui.org/docs/components/table#use-case-example), I'm able to scroll after adding all columns.

![image](https://github.com/user-attachments/assets/50ce8286-dca9-429d-b1aa-aef714f73755)

**Comment by wingkwong** [comment]
closing - not reproducible + inactivity
