### ISSUE TITLE
[BUG] - missing variable in Table examples in docs

### ISSUE THREAD

**Issue by NikhilDangiAcademy** [nextui-org/nextui#3625]
### NextUI Version

2.4.6

### Describe the bug

ReferenceError: Can't find variable: useMemo
ReferenceError: Can't find variable: args

### Steps to Reproduce the Bug or Issue

In terminal we got the error

### Expected behavior

I expected proper table

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Please share your code. Probably you missed the import.

**Comment by NikhilDangiAcademy** [comment]
import React from "react";
import {Table, TableHeader, TableColumn, TableBody, TableRow, TableCell, getKeyValue, Spinner} from "@nextui-org/react";
import {useAsyncList} from "@react-stately/data";

export default function App() {
  const [isLoading, setIsLoading] = React.useState(true);

  let list = useAsyncList({
    async load({signal}) {
      let res = await fetch('https://swapi.py4e.com/api/people/?search', {
        signal,
      });
      let json = await res.json();
      setIsLoading(false);

      return {
        items: json.results,
      };
    },
    async sort({items, sortDescriptor}) {
      return {
        items: items.sort((a, b) => {
          let first = a[sortDescriptor.column];
          let second = b[sortDescriptor.column];
          let cmp = (parseInt(first) || first) < (parseInt(second) || second) ? -1 : 1;

          if (sortDescriptor.direction === "descending") {
            cmp *= -1;
          }

          return cmp;
        }),
      };
    },
  });

  return (
    <Table
      aria-label="Example table with client side sorting"
      sortDescriptor={list.sortDescriptor}
      onSortChange={list.sort}
      classNames={{
        table: "min-h-[400px]",
      }}
    >
      <TableHeader>
        <TableColumn key="name" allowsSorting>
          Name
        </TableColumn>
        <TableColumn key="height" allowsSorting>
          Height
        </TableColumn>
        <TableColumn key="mass" allowsSorting>
          Mass
        </TableColumn>
        <TableColumn key="birth_year" allowsSorting>
          Birth year
        </TableColumn>
      </TableHeader>
      <TableBody 
        items={list.items} 
        isLoading={isLoading}
        loadingContent={<Spinner label="Loading..." />}
      >
        {(item) => (
          <TableRow key={item.name}>
            {(columnKey) => <TableCell>{getKeyValue(item, columnKey)}</TableCell>}
          </TableRow>
        )}
      </TableBody>
    </Table>
  );
}

**Comment by NikhilDangiAcademy** [comment]
https://codesandbox.io/p/devbox/immutable-moon-rrfcm6?file=%2FApp.jsx%3A5%2C18&utm_medium=sandpack

> Please share your code. Probably you missed the import.

**Comment by wingkwong** [comment]
I checked your code. It's not related to NextUI at all.

> ReferenceError: Can't find variable: useMemo

You can either import from `react` like `import {useMemo} from "react";` or use `React.useMemo`

> ReferenceError: Can't find variable: args

I can't see you've defined `args`.

**Comment by NikhilDangiAcademy** [comment]
> I checked your code. It's not related to NextUI at all.
> 
> > ReferenceError: Can't find variable: useMemo
> 
> You can either import from `react` like `import {useMemo} from "react";` or use `React.useMemo`
> 
> > ReferenceError: Can't find variable: args
> 
> I can't see you've defined `args`.



> I checked your code. It's not related to NextUI at all.
> 
> > ReferenceError: Can't find variable: useMemo
> 
> You can either import from `react` like `import {useMemo} from "react";` or use `React.useMemo`
> 
> > ReferenceError: Can't find variable: args
> 
> I can't see you've defined `args`.



> I checked your code. It's not related to NextUI at all.
> 
> > ReferenceError: Can't find variable: useMemo
> 
> You can either import from `react` like `import {useMemo} from "react";` or use `React.useMemo`
> 
> > ReferenceError: Can't find variable: args
> 
> I can't see you've defined `args`.

I know the solution but I am asking you to update your code. https://nextui.org/docs/components/table

**Comment by wingkwong** [comment]
Okay. You could've mentioned [here](https://nextui.org/docs/components/table#async-pagination) at the first place. Will update it soon.
