### ISSUE TITLE
[BUG] - warning thrown in onSelectionChange in dropdown example code

### ISSUE THREAD

**Issue by KeysNClicks** [nextui-org/nextui#3626]
### NextUI Version

14.2.4

### Describe the bug

<img width="452" alt="image" src="https://github.com/user-attachments/assets/cf281580-fe8c-4e5c-aa20-0340222ba2cf">

### Steps to Reproduce the Bug or Issue

There is an error in the dropdown properties. Attached image for better understanding
Type 'Dispatch<SetStateAction<Set<string>>>' is not assignable to type '(keys: SharedSelection) => void'.
  Types of parameters 'value' and 'keys' are incompatible.
    Type 'SharedSelection' is not assignable to type 'SetStateAction<Set<string>>'.
      Type '"all" & { anchorKey?: string | undefined; currentKey?: string | undefined; }' is not assignable to type 'SetStateAction<Set<string>>'.
        Type 'String & { anchorKey?: string | undefined; currentKey?: string | undefined; }' is missing the following properties from type 'Set<string>': add, clear, delete ... 

But it's functioning correctly despite a warning appearing in the code.

### Expected behavior

There shouldn't be any errors in the dropdown properties.

### Operating System Version

Windows

### Browser

Chrome

**Comment by awesome-pro** [comment]
@KeysNClicks  kindly share, relevant code or sandbox reproducing the error

**Comment by KeysNClicks** [comment]
I copied the code from their Guides Documentation, and while all other components are functioning correctly, I'm encountering a warning with a red line on the **onSelectionChange** property in the Dropdown component. However, this warning does not impact the application's functionality.

<img width="535" alt="image" src="https://github.com/user-attachments/assets/2eb32fc2-76d5-4e44-a39b-f108d6349ddc">

**Comment by kaishuige** [comment]
@KeysNClicks 
import { Selection } from "@nextui-org/react";
const [selectedKeys, setSelectedKeys] = React.useState<Selection>(new Set('text'));
 
 You can try this. The type shouldn't report an error.

**Comment by wingkwong** [comment]
You can simply add the Selection type. I'll add TS examples in docs.

```tsx
import type { Selection } from "@nextui-org/react";

const [selectedKeys, setSelectedKeys] = React.useState<Selection>(new Set(["text"]));
```
