### ISSUE TITLE
[BUG] - It should display colors in VSCode just like Tailwind CSS variables do

### ISSUE THREAD

**Issue by raky291** [nextui-org/nextui#3627]
### NextUI Version

2.4.6

### Describe the bug

Color previews do not appear. It should display colors in VSCode just like Tailwind CSS variables do.

<img width="1612" alt="Screenshot 2024-08-09 at 8 39 10 a m" src="https://github.com/user-attachments/assets/2ac7f94e-bfa6-4eb9-b278-f81f9dfd8633">

### Steps to Reproduce the Bug or Issue

- Copy and paste the code below into a VSCode editor with the Tailwind CSS IntelliSense extension enabled.

https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss

```
export default function Files() {
  return (
    <>
      <div className="bg-content2 p-8 rounded-lg border-dashed border-2 border-foreground-500 hover:border-primary transition duration-300 ease-in-out"></div>
      <div className="bg-gray-100 p-8 rounded-lg border-dashed border-2 border-gray-300 hover:border-blue-500 transition duration-300 ease-in-out"></div>
    </>
  );
}

```

### Expected behavior

A preview of one color should appear.

Or if you prefer multiple colors, if there are multiple themes enabled.

### Operating System Version

OS: Darwin arm64 23.6.0

### Browser

Chrome

**Comment by ameybh** [comment]
This thread explains why is it is not feasible to generate colors from CSS Variables because their values might be different based on themes, media queries and other conditions.
A possible solution that might work for you could be this:
https://github.com/tailwindlabs/tailwindcss-intellisense/issues/809#issuecomment-2221559773
> I have a little solution that works for me in **VSCode** that might work for some of you. You'll need to put a color reference as a comment after the variable:
> 
> ```css
> 'light-neutrals': {
>   DEFAULT: 'rgb(var(--light-neutrals-default) / <alpha-value>) /* #ffffff */',
>   100: 'rgb(var(--light-neutrals-100) / <alpha-value>) /* #ffffff */',
>   200: 'rgb(var(--light-neutrals-200) / <alpha-value>) /* #f5f6f7 */',
>   300: 'rgb(var(--light-neutrals-300) / <alpha-value>) /* #f2f4f5 */',
>   400: 'rgb(var(--light-neutrals-400) / <alpha-value>) /* #ecedee */',
>   500: 'rgb(var(--light-neutrals-500) / <alpha-value>) /* #e1e2e3 */',
>   600: 'rgb(var(--light-neutrals-600) / <alpha-value>) /* #cacbcc */',
> },
> ```
> 
> That way **VSCode** recognizes it: <img alt="image" width="725" src="https://private-user-images.githubusercontent.com/18222884/347608544-fd599a17-8458-4b11-94bc-9ca4d3578e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODYxMTYsIm5iZiI6MTcyMzc4NTgxNiwicGF0aCI6Ii8xODIyMjg4NC8zNDc2MDg1NDQtZmQ1OTlhMTctODQ1OC00YjExLTk0YmMtOWNhNGQzNTc4ZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA1MjMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZDYzZGM5NjY5NGQ1NWU0ZWI1NmI1ZjhmM2QxODY5Mjc1YzJiZTBiMGU0MmFjNmQxMDZmNzNmYzgxZGJhNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DCuxkLdHtIc1C7-DUn2cRGpyNiWLa9X23ZzBIETQ-5I">
> 
> Note: since you're using variables that means that the color will change, you should only put a reference color in the comment. For instance I have two color variants one for each light/dark theme and put all the light colors as reference because those are my default colors.
> 
> Best of luck!

**Comment by luisrudge** [comment]
It's very frustrating to not be able to see the colors like other TW colors
<img width="539" alt="image" src="https://github.com/user-attachments/assets/a0c8ad3d-f32b-4970-9627-dd483507ad1f">
