### ISSUE TITLE
[BUG] - Grid: Property 'ref' does not exist 

### ISSUE THREAD

**Issue by snowplowtach** [nextui-org/nextui#363]
### Describe the bug

It's not possible to pass a ref to a `Grid` component

### Steps to Reproduce the Bug or Issue

Try to pass a ref to a `Grid` component:

```tsx
export function Item({ src }: { src: string }) {
  const ref = useRef()
  return (
    <Grid ref={ref}>
      <Avatar src={src} />
    </Grid>
  )
}
```

### Expected behavior

Should be able to pass a ref to `Grid`

### Screenshots or Videos

<img width="791" alt="ref-issue" src="https://user-images.githubusercontent.com/93679694/160079930-47097bc8-1f06-4f37-be88-b78d02b9e61d.png">

### Operating System Version

- OS: macOS 12.2.1

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @snowplowtach are you using the latest NextUI version? `v1.0.4-beta.5`?

Here's a fully functional example https://codesandbox.io/s/nextui-grid-ref-zr7i5v?file=/App.js

**Comment by snowplowtach** [comment]
@jrgarciadev I updated to `1.0.4.beta.5` it solved the problem. Sorry I didn't think to update before 🙈
