### ISSUE TITLE
[BUG] - Unintended Movement and Dark Blue Color Issue with NextUI Elements on Mobile Browsers

### ISSUE THREAD

**Issue by Kunwar-Pratap** [nextui-org/nextui#3632]
### NextUI Version

"@nextui-org/avatar": "^2.0.32", 		"@nextui-org/button": "2.0.37", 		"@nextui-org/card": "^2.0.33", 		"@nextui-org/checkbox": "^2.1.4", 		"@nextui-org/chip": "^2.0.32", 		"@nextui-org/code": "2.0.32", 		"@nextui-org/divider": "^2.0.31", 		"@nextui-org/dropdown": "^2.1.29", 		"@nextui-org/image": "^2.0.31", 		"@nextui-org/input": "2.2.4", 		"@nextui-org/kbd": "2.0.33", 		"@nextui-org/link": "2.0.34", 		"@nextui-org/listbox": "2.1.25", 		"@nextui-org/modal": "^2.0.39", 		"@nextui-org/navbar": "2.0.36", 		"@nextui-org/pagination": "^2.0.35", 		"@nextui-org/progress": "^2.0.33", 		"@nextui-org/snippet": "2.0.41", 		"@nextui-org/spinner": "^2.0.33", 		"@nextui-org/switch": "2.0.33", 		"@nextui-org/system": "2.2.5", 		"@nextui-org/tabs": "^2.0.35", 		"@nextui-org/theme": "2.2.9", 		"@nextui-org/tooltip": "^2.0.39"

### Describe the bug

When accessing my portfolio website, [kunwarpratap.dev](https://kunwarpratap.dev/), on mobile browsers, I observed that all NextUI elements exhibit unintended movement, shifting up and down. Additionally, a dark blue color appears near the top border of these elements. This behavior is especially noticeable when using the website in dark mode. The issue is consistent across all mobile browsers, and I have confirmed that the same issue occurs on the official NextUI website, suggesting it may be an issue with the NextUI components themselves.

### Your Example Website or App

https://kunwarpratap.dev/

### Steps to Reproduce the Bug or Issue

1. Open my website https://kunwarpratap.dev/ on any mobile browser.
2. Enable dark mode.
3. Observe the movement of the NextUI elements as they shift up and down.
4. Notice the dark blue color appearing near the top border of these elements.
5. To confirm, visit the official NextUI website on the same mobile browsers and observe similar behavior.

### Expected behavior

As a user, I expected the NextUI elements to remain static and consistent in their position without any unintended movement or color changes, especially in dark mode. Instead, I am seeing unexpected shifting of elements and an unwanted dark blue color near the top border.

### Screenshots or Videos

https://github.com/user-attachments/assets/9d344462-b7aa-4bdb-9898-5f1b158ce600

### Operating System Version

Android

### Browser

Chrome

**Comment by wingkwong** [comment]
1. please provide a minimal reproducible environment.  
2. I couldn't see the issue compared with your video
3. Can you screenshot one of the examples of "a dark blue color appears near the top border of these elements"
