### ISSUE TITLE
[BUG] - Datepicker don't apply DateInput classNames

### ISSUE THREAD

**Issue by eliasdanielr** [nextui-org/nextui#3633]
### NextUI Version

2.1.6

### Describe the bug

To optimize the final bundle of my application, I add dependencies only to the components I use. Each time I create a color variant for my application, but when I use the `DatePicker` components, I don't apply the `inputWrapper` classes

```tsx
// components/date-picker/index.tsx

"use client";

import { DatePicker as NextDatePicker } from "@nextui-org/date-picker";
import { extendVariants } from "@nextui-org/system";

export const DatePicker = extendVariants(NextDatePicker, {
	variants: {
		color: {
			stone: {
				inputWrapper: [
					"bg-red-500", // <- i tried others classes
				],
                selectorButton: [
                    "bg-red-500", // <- this works
                ]
			},
        }
	},
	defaultVariants: {
        color: "stone",
		radius: "sm",
		labelPlacement: "outside",
	},
});

export * from "@nextui-org/date-picker";
```

## Usage in my application:

```tsx
// path/register-from.tsx
import { Input, DatePicker } from "#/components"; 
//                                       ↑
//                       Yes, i add index.ts in this folder

<DatePicker
	// @ts-ignore
	maxValue={today(getLocalTimeZone())}
	showMonthAndYearPickers
	label="Birth date"
	color="default"
	isRequired
/>
```

### Steps to Reproduce the Bug or Issue

1. [Follow the docs](https://nextui.org/docs/guide/installation#individual-installation) after install `DatePicker` component.

2. Create a `extendVariants` of the `DatePicker` component

3. Add custom classNames (try all and some of them work, it seems that only the `DateInput` component works)

3. Use your custom component.

### Expected behavior

I expected the color of the `inputWrapper` and `selectorButton` to apply, but only the color of the selector applies

### Operating System Version

Linux

### Browser

Chrome

**Comment by wingkwong** [comment]
please provide a sandbox environment

**Comment by wingkwong** [comment]
Closing - inactivity
