### ISSUE TITLE
[BUG] - DatePicker Locale Not Applying en-US Format

### ISSUE THREAD

**Issue by drokbers** [nextui-org/nextui#3636]
### NextUI Version

2.4.6

### Describe the bug

Here's a draft for the GitHub issue you can create:

Issue Title: DatePicker Locale Not Applying en-US Format in NextUI 2.4.6
Description:

I'm using NextUI version 2.4.6, and I'm trying to set the date format in the DatePicker component to follow the MM/DD/YYYY format by setting the locale to en-US. According to the documentation, the locale should be set using the locale prop in the NextUIProvider. However, when I apply this, the date format in the DatePicker does not change to the expected en-US format.

Here is the code I'm using:

```
"use client";

import { NextUIProvider } from "@nextui-org/react";

export function Providers({ children }: { children: React.ReactNode }) {
  return <NextUIProvider locale="en-US">{children}</NextUIProvider>;
}
```

Despite setting the locale to "en-US", the DatePicker still displays dates in the default format instead of MM/DD/YYYY.

### Steps to Reproduce the Bug or Issue

Wrap the application with NextUIProvider and set the locale to "en-US".
Use the DatePicker component and observe the date format.

### Expected behavior

The DatePicker should display dates in the MM/DD/YYYY format when the locale is set to "en-US".

### Operating System Version

macOS 

### Browser

Chrome

**Comment by awesome-pro** [comment]
@drokbers  by default the date-picker already shows date in `MM/DD/YYYY` format.
I used the date-picker with `en-US`, and it is showing the correct format. 
Kindly see if you are still missing any configuration 
still the problem provide a sandbox

**Comment by wingkwong** [comment]
closing - let's track here: https://github.com/nextui-org/nextui/issues/3604
