### ISSUE TITLE
Unreadable show/hide icon - Input.Password component

### ISSUE THREAD

**Issue by mukeshgurpude** [nextui-org/nextui#364]
`Show/hide` password icon isn't visible in the [docs](https://nextui.org/docs/components/input#password)
<img width="728" alt="image" src="https://user-images.githubusercontent.com/55982424/160138957-429b206a-4b11-446f-a052-bc8b70970980.png">

Browser: **Brave Version 1.36.119 Chromium: 99.0.4844.83**
Platform: Windows

**Comment by Dhananjay-JSR** [comment]
Thankyou for Pointing Out Issue 👍🏻
