### ISSUE TITLE
[BUG] - Lack of RTL Support in Date Range Picker

### ISSUE THREAD

**Issue by tareq96** [nextui-org/nextui#3642]
### NextUI Version

2.4.0

### Describe the bug

The Date Picker selected overlay does not look correctly when the direction is set to RTL (Right-to-Left).

![image](https://github.com/user-attachments/assets/5d1e2693-73e1-459d-b974-4cc53b924b75)

### Your Example Website or App

https://nextui.org/docs/components/date-range-picker

### Steps to Reproduce the Bug or Issue

1. Go to https://nextui.org/docs/components/date-range-picker
2. Inspect element
3. Change the HTML tag dir attribute to "rtl"
4. Check the date picker selection background.

### Expected behavior

![image](https://github.com/user-attachments/assets/a8a50b27-a78f-4116-8cb6-da418fab8ada)

### Operating System Version

macOS

### Browser

Chrome

**Comment by elbokh** [comment]
Hi, I'm still experiencing the bug on version 2.4.6

The arrows are working fine but the background is not!

<img width="418" alt="Screenshot 2024-09-14 at 11 59 59 AM" src="https://github.com/user-attachments/assets/40c28fce-63f3-4a26-bf15-ad8b035a43ce">

**Comment by wingkwong** [comment]
@elbokh the fix should be in 2.4.7. 

<img width="322" alt="image" src="https://github.com/user-attachments/assets/ca59ac5e-dcdd-46f1-abca-24b58da31c0f">

**Comment by elbokh** [comment]
> @elbokh the fix should be in 2.4.7.
> 
> <img alt="image" width="322" src="https://private-user-images.githubusercontent.com/35857179/367510724-ca59ac5e-dcdd-46f1-abca-24b58da31c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTE5MTUsIm5iZiI6MTcyNjUxMTYxNSwicGF0aCI6Ii8zNTg1NzE3OS8zNjc1MTA3MjQtY2E1OWFjNWUtZGNkZC00NmYxLWFiY2EtMjRiNThkYTMxYzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE4MzMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNzgwZDFkYjExZTE3YWU4ZTI5Mjk4ZGViYWI2OTVhZWUwZDgyZTQ1Yzk3N2JhNjYxNzRmZDRkZTZmMDUyMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2gLpN-pesB-YJpai09r_H_VMkbiRX3XZ45pIX2QNZw4">

Hey @wingkwong, I'm on version 2.4.8 now, the issue is still persistent 😕

<img width="420" alt="Screenshot 2024-09-16 at 7 33 20 PM" src="https://github.com/user-attachments/assets/7b2d92e5-c068-4687-a5de-431efb92f3d5">

**Comment by wingkwong** [comment]
@elbokh can you share a sandbox and the locale?

**Comment by asgari-hamid** [comment]
Hi @wingkwong.
This is not fixed for locale "ar" until version v2.6.8.
Also the label direction is incorrect.
![Screenshot 2024-12-22 222524](https://github.com/user-attachments/assets/4c1f7e7e-089e-45de-bc65-95aed9f1d98e)

**Comment by wingkwong** [comment]
@asgari-hamid pls create a new issue with a sandbox
