### ISSUE TITLE
[BUG] - `React.Key` is not the same as `Key` from `@react-types/shared`

### ISSUE THREAD

**Issue by jsun969** [nextui-org/nextui#3644]
### NextUI Version

2.4.2

### Describe the bug

I'm using `Autocomplete` component. I defined a state to control the field
```tsx
const [key, setKey] = useState<React.Key | null>(null);
//                             ^ It's `string | number | bigint`
// ...
<Autocomplete
	label="Search a course"
	isDisabled={coursesQuery.isPending}
	defaultItems={coursesQuery.data?.data.courses ?? []}
	selectedKey={key}
//  ^ want `string | number` for key
	onSelectionChange={setKey}
>
```

### Steps to Reproduce the Bug or Issue

Define a controlled `Autocomplete` component

### Expected behavior

`selectedKey` should be `React.Key`

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/2182
