### ISSUE TITLE
[BUG] - Incompatibility with Next.js 15

### ISSUE THREAD

**Issue by doutoutdou** [nextui-org/nextui#3645]
### NextUI Version

2.4.6

### Describe the bug

Hello. 

I started a Next.js project (version 15) few weeks ago and I chose NextUI (version 2.4.6) as component library.

I added some NextUI components like Button or Table and it went well.

Unfortunately, since I've tried to use the Navbar component, I've run into a few problems. I am not sure if it's an issue for NextUi team or Next.JS team :/ 

But it looks like you can't use NextUI with Next.js version 15 (tried RC and last canary version (v111)) (stack trace attached)

It works well with Next.js 14.2.4

### Steps to Reproduce the Bug or Issue

1. Start a project with `nextui init -t app` (as described here https://nextui.org/docs/frameworks/nextjs)
2. Install dependencies & run the server
3. Open your browser and everything running smoothly
4. Update Next.js version to 15 (		"next": "15.0.0-rc.0" or canary version)
5. Update React to RC19 (needed by Next.js version 15)
6. Update dependencies & run the server
7. No render in the browser (see the error in the screenshot)
8. Rollback Next.js version to 14 (React can remain in RC19 without issue)
9. Update dependencies & run the server
10. Open your browser and everything running smoothly

### Expected behavior

As a User, I expected to be able to use NextUI with Next.JS version 15

### Screenshots or Videos

![Screenshot 2024-08-12 at 2 18 38 PM](https://github.com/user-attachments/assets/ed4e5215-e705-47ab-a34b-5fd2f10bfa9b)
![Screenshot 2024-08-12 at 2 23 44 PM](https://github.com/user-attachments/assets/6fbca3ff-8188-470e-85d0-3c3da9fc4840)
![Screenshot 2024-08-12 at 2 24 26 PM](https://github.com/user-attachments/assets/65b88cfa-cdf3-4e1d-b595-0542cf9cb627)

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
let's track here - https://github.com/nextui-org/nextui/issues/3021

**Comment by Jihefel** [comment]
With the Slider component, the error message is different for me.

"next": "15.0.0-canary.120",
"react": "19.0.0-rc-49496d49-20240814",
"react-dom": "19.0.0-rc-49496d49-20240814",

![image](https://github.com/user-attachments/assets/40b584ab-83c2-4a46-ae61-87163e3cb096)
