### ISSUE TITLE
[BUG] - <Input /> clearButton is in the wrong position in Safari

### ISSUE THREAD

**Issue by Pszz** [nextui-org/nextui#3651]
### NextUI Version

2.4.6

### Describe the bug

- <Input /> clearButton is in the wrong position in Safari
- In the TG embedded browser, it is the same as Safari.

![image](https://github.com/user-attachments/assets/7036a191-edbf-46cb-8865-9a3821f4ab37)

### Steps to Reproduce the Bug or Issue

- Check out this link
https://nextui.org/docs/components/input#clear-button

### Expected behavior

- Require consistent style

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
not reproducible

**Comment by Pszz** [comment]
> Reference in new issue

After checking, the problem still exists, so I submitted the browser version and system version information.

**Comment by Pszz** [comment]
> Reference i

After checking, the problem still exists, so I submitted the browser version and system version information.
