### ISSUE TITLE
[Feature Request] ListboxItem to support Link state from react-router-dom

### ISSUE THREAD

**Issue by maniteja-emmadi** [nextui-org/nextui#3653]
### Is your feature request related to a problem? Please describe.

I was working on the Select component in which the SelectItem i.e., `ListboxItem` has a href prop to navigate to a certain screen.

If I have a list of items, let's say a list of Students in an Online Library Project, And I click on `View Student Details` option which takes me to the `Student Details` Screen, but I want to send the selected student id in the location state from react-router-dom.

Currently, ListboxItem does not support location state, please add this to your future release.

### Describe the solution you'd like

The ListboxItem should accept the location state prop as the Link element from react-router-dom does. 

### Describe alternatives you've considered

As a child, we can render the Link element from `react-router-dom` in SelectItem, but that will affect the reusability of my `CustomSelect` component. And it also defeats the purpose of the `href` prop of ListboxItem.

**Comment by ameybh** [comment]
You can pass `routerOptions` along with href as described here:
https://react-spectrum.adobe.com/react-aria/routing.html#router-options

Please let me know if that solved your problem.
