### ISSUE TITLE
[BUG] - Modal does not adjust position when keyboard appears on iOS

### ISSUE THREAD

**Issue by jalvarezz13** [nextui-org/nextui#3654]
### NextUI Version

2.4.6

### Describe the bug

After updating from version 2.2.X to 2.4.X, there is an issue observed on iOS devices where the modal dialog does not adjust its position when the keyboard appears on the screen. As a result, the modal remains in its original position, obscuring the view of the input fields and preventing users from seeing what they are typing. This behavior affects the usability of the application, especially in forms and dialogs requiring user input.

### Steps to Reproduce the Bug or Issue

1. Create a webpage that includes a modal dialog.
2. Within the modal, include a form with several input fields.
3. Open the webpage on an iOS device using Safari.
4. Tap on the input field within the modal to bring up the iOS keyboard.

Notice that when the keyboard appears, the modal remains in its fixed position at the bottom of the screen. The keyboard covers the modal, obscuring the input field and preventing the user from seeing what is being typed.

### Expected behavior

The modal should adjust its position when the keyboard appears, moving up to ensure that the input field is visible and the user can see what they are typing.

### Screenshots or Videos

https://github.com/user-attachments/assets/43c2c9b1-2182-445e-bb81-ab67d65132b2

### Operating System Version

iOS

### Browser

Safari

**Comment by ETOPS7** [comment]
Got the same issue all mobile devices

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/3654
