### ISSUE TITLE
[BUG] - Font color in Bordered select is always gray

### ISSUE THREAD

**Issue by Rain-YuXia** [nextui-org/nextui#3659]
### NextUI Version

2.4.6

### Describe the bug

Just came to NextUI for a few days. I have a bordered select. I found out the font color is always gray no matter what `color props`
<img width="423" alt="Screenshot 2024-08-16 at 2 40 47 PM" src="https://github.com/user-attachments/assets/ec9b3f91-269b-46f5-b424-79cf085c1c2a">

As you can see, it's still gray even I set the `color="primary"`. It makes the font color inconsistent since the font color in `Input` is black while the font color in `Select` is gray

### Steps to Reproduce the Bug or Issue

```tsx
<Select
  name="role_id"
  label="Job Role"
  labelPlacement="outside"
  startContent={
      <UserCircleIcon className="w-4 h-4 text-default-400 pointer-events-none" />
  }
  variant="bordered"
  color='primary'
  placeholder="Select your role"
  onChange={(e) => setData('role_id', e.target.value)}
>
  {roles.map(role => (
      <SelectItem key={role}>
          {role}
      </SelectItem>
  ))}
</Select>
```

### Expected behavior

The color should be consistent or is there any way to change the color in Select?

### Operating System Version

Mac

### Browser

Chrome

**Comment by macci001** [comment]
Hi,
The `color=primary` will apply only to the label not the `selected value` and `selectable values list` in popover.

You can add the class: `
classNames: {
      "listboxWrapper": "text-primary",
      "value": "text-primary"
}
`

Adding the above class might help you get: 
![Screenshot 2024-08-16 at 10 39 28 AM](https://github.com/user-attachments/assets/41c8ccbb-d140-4e44-9597-88e8ad991225)

**Comment by macci001** [comment]
@wingkwong Will it be helpful to add an variant for this?

**Comment by Rain-YuXia** [comment]
> Hi, The `color=primary` will apply only to the label not the `selected value` and `selectable values list` in popover.
> 
> You can add the class: `classNames: { "popoverContent": "text-primary", "value": "text-primary" }` Here, the styling in `value` applies to the selected value and styling in `popoverContent` is applied to selectable values.
> 
> * Adding the above class might help you get:
>   ![Screenshot 2024-08-16 at 10 39 28 AM](https://private-user-images.githubusercontent.com/72215007/358473892-41c8ccbb-d140-4e44-9597-88e8ad991225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODYwNDYsIm5iZiI6MTcyMzc4NTc0NiwicGF0aCI6Ii83MjIxNTAwNy8zNTg0NzM4OTItNDFjOGNjYmItZDE0MC00ZTQ0LTk1OTctODhlOGFkOTkxMjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA1MjIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNWE5OTVhN2VlMTU0MzUyMGRiN2U2MDA0MGNlNGU4NjgwNjI2YzQyZjJkMmRhMmQ1YThmYmM3MTVlZTM4NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._TUOiYleuE26VlbyjBooz0pr6i1AzY53HUQ1ITnyGaQ)
> * If you like to have custom color for the selected value, you can add the ` classNames: { "popoverContent": "text-primary", "value": "text-[#99C7FB]" }` class
>   ![Screenshot 2024-08-16 at 10 47 39 AM](https://private-user-images.githubusercontent.com/72215007/358475984-a8d75cb3-3ffe-455b-aabd-c7743834030e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODYwNDYsIm5iZiI6MTcyMzc4NTc0NiwicGF0aCI6Ii83MjIxNTAwNy8zNTg0NzU5ODQtYThkNzVjYjMtM2ZmZS00NTViLWFhYmQtYzc3NDM4MzQwMzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA1MjIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMjU2N2YyMTYwYjQ3ZDc2YTM3NzQzYzk3ZjkwNjdkNDIwNjU5NTU4MDg2Mzk5NzJkODU1YzI3ZDRkODAyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OnXO1kWzW05PgRdGUXshgfJKjdFgJX_rGDnzCXvWouE)

Hi

Thank you for your solution.

It changed the color of selected value as expected. But the cons is that the color of placeholder gets changed as well.

Because the placeholder is not a real placeholder prop in an input, but a `span`.  So I have to do like this: `classNames= {{ "value": data ? "text-black" : "text-gray-500" }}` as my temporary solution.

But personally, I can't get the point of design in this way. If the `Select` has no border, the selected value color is the same as other components. Why the selected value will be changed when `Select` is bordered, making the color inconsistent with other components?

**Comment by macci001** [comment]
@Rain-YuXia 
You can add this `{"value: "group-data-[has-value=true]:text-default-foreground"}` to avoid using the conditional. This will show text as gray when placeholder is shown and black when some value is selected.
* when placeholder
![Screenshot 2024-08-16 at 1 58 24 PM](https://github.com/user-attachments/assets/33f6f409-1ff2-4633-ae2d-77bf1dc301a5)
* when value is selected
![Screenshot 2024-08-16 at 1 58 53 PM](https://github.com/user-attachments/assets/236f8757-2db5-41f9-a31b-874a88330562)

**Comment by Rain-YuXia** [comment]
@macci001 
working perfectly. Thanks

Is it an undocumented hidden feature? I can't find it anywhere in the documentation.

**Comment by macci001** [comment]
> @macci001 working perfectly. Thanks
> 
> Is it an undocumented hidden feature? I can't find it anywhere in the documentation.

This is just a hack until this big is fixed.
