### ISSUE TITLE
[BUG] - Skeleton is overflowing with isLoaded=true

### ISSUE THREAD

**Issue by almarzn** [nextui-org/nextui#3670]
### NextUI Version

2.4.6

### Describe the bug

Using <Skeleton> with `isLoaded={true}` overflows the `::before` element on the left of the element.
 - Element on the left are thus getting covered by an invisible element and thus not interactive.
 - The animation flashes on the left of the element in cases where the element is not removed and readded (see video)

### Your Example Website or App

https://codesandbox.io/p/devbox/cranky-euclid-hjympl?workspaceId=6a536476-25bc-4d3c-9a8a-569f4ba3a731

### Steps to Reproduce the Bug or Issue

1. Click Hide Skeleton

### Expected behavior

Button A should be clickable 

### Screenshots or Videos

Button A is not clickable

Also a video of the overlay flashing (after reloading)

https://github.com/user-attachments/assets/f5274588-6d55-43ec-8472-c21af6999ec7

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
handled in #3217

**Comment by ahmaddonishyar** [comment]
I like to work on this please assign me.

**Comment by wingkwong** [comment]
@ahmaddonishyar there is a PR alreayd
