### ISSUE TITLE
[BUG] - The button's event did not bubble up

### ISSUE THREAD

**Issue by Dog-Egg** [nextui-org/nextui#3672]
### NextUI Version

2.4.6

### Describe the bug

Why didn't the mousedown event bubble up when clicking a button?

### Steps to Reproduce the Bug or Issue

Look at the screenshot.

### Expected behavior

Expect the mousedown event to bubble up.

### Screenshots or Videos

![Xnip2024-08-21_18-04-20](https://github.com/user-attachments/assets/abaf9c3e-7a5b-4da4-8e84-a26d8b5227e4)

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
seems the logic from RA's onPress preventing it

**Comment by wingkwong** [comment]
closing - see https://github.com/nextui-org/nextui/issues/4059
