### ISSUE TITLE
[BUG] - If configure plugins: [nextui()] in tailwind.config.ts, i will not be able to smart hint tailwindcss.

### ISSUE THREAD

**Issue by lessthanno** [nextui-org/nextui#3673]
### NextUI Version

2.4.6

### Describe the bug

tailwind css hint is invalid

### Your Example Website or App

https://airdrop2049.com/

### Steps to Reproduce the Bug or Issue

1. import nextjs UI to tailwind.config.js
2. plugins: [nextui()]
3. tailwind css hint is invalid
4. annotate nextui(), tailwind css hint works fine

### Expected behavior

It prompts properly.

### Screenshots or Videos

<img width="825" alt="image" src="https://github.com/user-attachments/assets/34823825-2cd6-4ab2-a9dd-715286726ec3">

<img width="730" alt="image" src="https://github.com/user-attachments/assets/8aec3115-9960-4c07-8b13-a34e89ae5520">

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/c50cb4e9-ec0f-493d-aba2-a0325ab8eec3">

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
can you use the same example for before and after hiding nextui()?

**Comment by lessthanno** [comment]
> can you use the same example for before and after hiding nextui()?

The picture above is a comparison.

**Comment by wingkwong** [comment]
i mean on the same example.

**Comment by lessthanno** [comment]
> 1. tailwind

It's a problem that this can prompt!!!!
it has nothing to do with the code before or after.????
The problem is that nextui  turns off the tailwindcss smart hints.

**Comment by wingkwong** [comment]
I think it's more like IDE problem. I can see the hint before and after commenting out nextui plugin. Here's the example of typing `text-`

<img width="377" alt="image" src="https://github.com/user-attachments/assets/0c272c98-e226-447f-b3e1-938bd36a770a">
