### ISSUE TITLE
[Feature Request] Make it possible to disable the popoverTrigger using isDisabled

### ISSUE THREAD

**Issue by emilPandektes** [nextui-org/nextui#3674]
### Is your feature request related to a problem? Please describe.

Im creating a icon and title that displays information about whether a conversation is shared or not. If the person clicking that icon and title is the author it should open the popover, if not, it should be disabled.

This isn't possible with the current version of the popover trigger.

### Describe the solution you'd like

As a developer i expect there to be a prop that I can use to disable the poptrigger.

### Describe alternatives you've considered

Alternatively if have to implement logic that uses isOpen prop and does a check every time. It would produce more code overhead.

**Comment by wingkwong** [comment]
If you are using a Button component for "icon and title", then you can simply set `isDisabled` in Button.

```tsx
<Popover>
  <PopoverTrigger>
    <Button isDisabled startContent={<Icon />}>
      Open Popover
    </Button>
  </PopoverTrigger>
  {content}
</Popover>
```

or you may share your code for the discussion

**Comment by wingkwong** [comment]
closing - inactivity
