### ISSUE TITLE
[Select Label] - Unexpected behavior when selecting selector tag

### ISSUE THREAD

**Issue by JonathanAGonzalez** [nextui-org/nextui#3683]
### NextUI Version

2.2.5

### Describe the bug

When an option is selected from the dropdown, attempting to select a different option by clicking the label causes an unexpected behavior in the list of options.

[label.webm](https://github.com/user-attachments/assets/1906e6e4-65ae-4abe-922a-a0dcecad80b9)

### Steps to Reproduce the Bug or Issue

1. Select an option from the list
2. click on the label (Not on the selected option), otherwise on the label
3. see unexpected behavior

### Expected behavior

It is expected that when I click on the label the options to select will appear again

### Screenshots or Videos

[label.webm](https://github.com/user-attachments/assets/8e140ad7-d21d-4af9-bed3-5e6628a2bf7e)

### Operating System Version

windows

### Browser

Chrome

**Comment by AnYiEE** [comment]
There is already one PR (#3568).
