### ISSUE TITLE
[Feature Request] Loading component on v2

### ISSUE THREAD

**Issue by fukemy** [nextui-org/nextui#3684]
### Is your feature request related to a problem? Please describe.

Ask about Loading component from v1

### Describe the solution you'd like

Hello, I am starting to modify my project from v1 to v2, now I got this error: `'Loading' is not exported from '@nextui-org/react'`

 I tried to find the loading component on tailwind but can not find it, can you help?

### Describe alternatives you've considered

I want to use component like Loading from v1

**Comment by wingkwong** [comment]
For v2, please use [Spinner](https://nextui.org/docs/components/spinner)
