### ISSUE TITLE
CSS Error in Modals

### ISSUE THREAD

**Issue by Feli02** [nextui-org/nextui#369]
### Describe the bug

When I want to use CSS in Modals, vsc shows an error message. Is strange because when I see it in the browser the CSS works, despite the error vsc shows me. 
Note: I append to pictures, the first one is the error I get from vsc and the other one is the browser, where you can see the padding is being applied.

### Steps to Reproduce the Bug or Issue

1. Create a Modal
2. Add CSS to that modal
3. You will see the error

### Expected behavior

What I expected is to not appear an error at all. It's the only component and the first time it happen.

### Screenshots or Videos

<img width="960" alt="2022-03-26" src="https://user-images.githubusercontent.com/65402578/160254583-636c14b7-2c59-414d-b067-d63cdf6f701b.png">
<img width="960" alt="2022-03-26 (1)" src="https://user-images.githubusercontent.com/65402578/160254587-12e7ab30-4768-4954-ae07-866e06b69913.png">

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Feli02 thanks for reporting it, we will fix it as soon as we can 👍🏻
