### ISSUE TITLE
[BUG] - Components' props don't exist

### ISSUE THREAD

**Issue by tomerbar2903** [nextui-org/nextui#3692]
### NextUI Version

2.4.6

### Describe the bug

When using some components from `nextui` I encountered props issues multiple times. For example, when using the `Progress` like this:
```typescript
<Progress
value={60}
size='md'
aria-label='prediction progress'
className='h-fit'
classNames={{
  indicator: 'bg-blue-400',
}}
/>
```
I get a type error:
```
Type '{ value: number; size: string; "aria-label": string; className: string; classNames: { indicator: string; }; }' is not assignable to type 'IntrinsicAttributes & MergeWithAs<Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref">, Omit<...>, ProgressProps, "div">'.
  Property 'value' does not exist on type 'IntrinsicAttributes & MergeWithAs<Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref">, Omit<...>, ProgressProps, "div">'
```

Or when using the `Popover` like this:
```typescript
<>
  <Popover isOpen={showPopover}>
    <PopoverTrigger>
      <div
        className='h-3 w-3 rounded-full bg-green transition-all ease-in-out hover:bg-green-600'
        onMouseEnter={() => setShowPopover(true)}
        onMouseLeave={() => setShowPopover(false)}></div>
    </PopoverTrigger>
    <PopoverContent>{price}</PopoverContent>
  </Popover>
</>
```
I get the error:
```
Type '{ children: Element[]; isOpen: boolean; }' is not assignable to type 'IntrinsicAttributes & MergeWithAs<Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref">, Omit<...>, PopoverProps, "div">'.
  Property 'isOpen' does not exist on type 'IntrinsicAttributes & MergeWithAs<Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref">, Omit<...>, PopoverProps, "div">'
```

However when running `npm run dev` the components do compile successfully. 

This also occures with `classNames`, `size`, `shadow`, `label` (and many more...)  props.

I haven't seen anybody report this yet, so I 'm hoping to find the solution for this ASAP. 

This makes to a serious issue when building the application.

### Steps to Reproduce the Bug or Issue

1. Use the `Card` component
2. Specify your card's shadow by using the `shadow` prop

### Expected behavior

I should be able to use the props mentioned in the documentation, without having typing issues that fail the building the process.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/4353be0b-601f-463c-9acf-140400376b3f)
![image](https://github.com/user-attachments/assets/45f792d2-36b3-47ce-86af-3e0852563c48)
![image](https://github.com/user-attachments/assets/f9702ac5-0b41-4454-92a4-e5e5be7290a9)

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by tomerbar2903** [comment]
> [ENG-1300 [BUG] - Components' props don't exist](https://linear.app/nextui-inc/issue/ENG-1300/[bug]-components-props-dont-exist)

I don't have permissions to see this :(

**Comment by tomerbar2903** [comment]
I forgot to mention that I tried to use the project's typescript version, but it didn't work for me.

**Comment by tomerbar2903** [comment]
> > I don't have permissions to see this :(
> 
> this is for team members to mange internally. you can simply ignore this link
> 
> > I forgot to mention that I tried to use the project's typescript version, but it didn't work for me.
> 
> I don't see any issue on my side.
> 
> 1. which IDE are you using? does it still happen when you restart IDE?
> 2. have you tried removing node_modules and reinstall?
> 3. are you able to build your application despite the errors shown in IDE?
> 
> <img alt="image" width="684" src="https://private-user-images.githubusercontent.com/35857179/362530819-7ee912c7-42eb-4dcd-bd2c-aa01809de75e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NTY1ODMsIm5iZiI6MTcyNDk1NjI4MywicGF0aCI6Ii8zNTg1NzE3OS8zNjI1MzA4MTktN2VlOTEyYzctNDJlYi00ZGNkLWJkMmMtYWEwMTgwOWRlNzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE4MzEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZGRhMDM3MTgxMDM2YWNhNGU5N2ZlOWNjMTY4OTM5Y2RkOWQ2MmQyODU4NGIzMWUwY2M4NzJlMGYyYWE2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z7shYAwXG2hroLXYYPPhiDVf18JMZxxLP059Oz4aFEg">

I use VSCODE. When opening in PyCharm I don't seem to have the issue, but I don't want to switch to it.
I have tried deleting node_modules and reinstalling, delting and reinstalling typescript, and even reinstalling VSCODE all together (deleted all of my extensions). Nothing seemed to work. What typescript version are you using?

**Comment by tomerbar2903** [comment]
Can you maybe include your package.json?

**Comment by xmsz-stu** [comment]
So we need to lock typescript version on 5.4.5, right?
