### ISSUE TITLE
[BUG] - DateRangePicker error message not using NextUIProvider Locale

### ISSUE THREAD

**Issue by SimonGodefroid** [nextui-org/nextui#3693]
### NextUI Version

2.4.2

### Describe the bug

Set the locale in the `NextUIProvider`
```tsx
  <NextUIProvider locale='en-GB'>{children}</NextUIProvider>
```

### Steps to Reproduce the Bug or Issue

Set the locale in the `NextUIProvider`
```tsx
  <NextUIProvider locale='en-GB'>{children}</NextUIProvider>
```

Consume the `DateRangePicker` component

```tsx
...
// from the docs
const min = today(getLocalTimeZone());
...
<DateRangePicker
  label="Start date - End date"
  minValue={min}
/>
```

### Expected behavior

The error message should respect the provided's locale format.
ATM I receive `Value must be 8/29/2024 or later.` I expect instead `Value must be 29/08/2024 or later.`

### Screenshots or Videos

<img width="754" alt="image" src="https://github.com/user-attachments/assets/ea7fa2fb-4479-470f-93d5-47413b38484c">

### Operating System Version

macOs

### Browser

Chrome

**Comment by macci001** [comment]
Seems like validation messages which includes the date needs to be modified by the next-ui.
The validation messages obtained by the `react-aria` are created from the browser, hence the custom locale would not work in here. The message will contain the locale of the browser.

I am not sure if there is any workaround for this to get the validation message according to the custom locale.
 
I am putting in a PR to fix this.

**Comment by ryo-manba** [comment]
Thanks for the issue. If you'd like to set the validation message using a locale other than the browser's, please handle it using the `errorMessage` prop. You can refer to the following for more details: https://github.com/nextui-org/nextui/pull/3694#issuecomment-2387218249.
