### ISSUE TITLE
[BUG] -I keep getting <[object object ]> error even if using demo code

### ISSUE THREAD

**Issue by amyming112** [nextui-org/nextui#3696]
### NextUI Version

14.2.7

### Describe the bug

All the tabs, dropdown etc, I get the an object is within an object error. I tried to use just the demo code and still got the error. Using VSCode with Chrome. 

essentially everything such as <Tabs><Tab></Tab></Tabs> or <Dropdown><Button></Button></Dropdown> will throw the error. 

if I just use <Button/> it will be fine. 
<img width="937" alt="Screenshot 2024-08-31 at 20 07 44" src="https://github.com/user-attachments/assets/4c356120-4be8-4a1a-b4c8-1b1bc13d8e97">

### Steps to Reproduce the Bug or Issue

any code in tabs, dropdowns, popovers through the error. 

### Expected behavior

I expected the code to render as the demo but got the error by copying the demo code.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Please share the demo code you use. a sandbox to demonstrate is better.

**Comment by amyming112** [comment]
just the code from the web, like the first tab code from here: https://nextui.org/docs/components/tabs

**Comment by wingkwong** [comment]
I couldn't reproduce by using the example code. Please share a sandbox. In general, this error shows when you use collection-based components in a wrong way.

**Comment by amyming112** [comment]
Thanks. I'll park this for now.
