### ISSUE TITLE
[Feature Request] Can't override inline style for slots

### ISSUE THREAD

**Issue by meirboccara** [nextui-org/nextui#3711]
### Is your feature request related to a problem? Please describe.

Hey NextUI team, 

when we use a component like Input, we have a props style but we can't really modify the inline style of the input because there is many wrapper. 
I think this is a bug. 

What i will ask after will be maybe a feature. Like we have classNames that give us the possibility to modify className of each slot. We should have also a styles that will give us the possibility to modify each style of each slot. 

I will understand if you move it to bug instead of feature. 

Thanks for your response :) 

### Describe the solution you'd like

As user, i would expect to have a props styles that give me each slot to override style. 

### Describe alternatives you've considered

No alternatives 💯 . Maybe another names for the props 🥇

**Comment by wingkwong** [comment]
Can you share some examples what inline styles you wanna override?

**Comment by meirboccara** [comment]
When working on a large, legacy project, introducing new elements step by step can be challenging. In this case, there is a global CSS rule targeting the input tag. While I acknowledge that this isn't ideal, it's been in place for years and modifying it directly could have unforeseen consequences across the entire application.

As we aim to modernize the application part by part, this global CSS rule conflicts with the new UI component styles. To mitigate this, I would like to create a new Input component with inline styles to override the existing global CSS for each specific instance.

Additionally, I believe using dynamic CSS with the style property is a good approach because class names are not computed at runtime, offering more flexibility and reducing the risk of style conflicts.

**Comment by wingkwong** [comment]
Unfortunately, this is anti-pattern. We actually provide different slots in `classNames` for users to override the styles and we don't recommend to override the styles with an inline way.

Here's an example: https://nextui.org/docs/components/input#custom-styles

**Comment by meirboccara** [comment]
Hi @wingkwong,

I'd like to discuss the concept of dynamically changing styles in Tailwind CSS.

Traditionally, styled components allowed for dynamic style changes, but Tailwind CSS doesn't necessarily follow that approach. Currently, inline styles are the recommended way to achieve dynamic styling.

For my issue, i found a solution so it's not anymore the case. 

So it's more if you want to do dynamic style that change with render, how can i do it ? 
What i suggest will be : 
`styles={{
input: "border: red 2px solid",
inputWrapper: "background-color:red"
}}`

**Comment by wingkwong** [comment]
So you are using styled components? You may check this out to see if it helps: https://nextui.org/docs/customization/override-styles#css-in-js.

Free feel to DM me (same ID) at discord for discussion.
