### ISSUE TITLE
[Feature Request] Add toast or alert component

### ISSUE THREAD

**Issue by yahiaBSK** [nextui-org/nextui#3714]
### Is your feature request related to a problem? Please describe.

**When i want to make my web app shows up a small alert at the top oe the left of the screen container the information that the user was up to , like: uploading done, loading, warning, error, other small tips ...

so i can't find any solution using your library but to get some extra whole library just for getting a toast or alert component. all this just because your library doesn't contain a tiny and easy component to develop, called toast or alert. !**

### Describe the solution you'd like

**(I could have used the popover component you provided but that bothers me because I can't control its position over the page ).**

### Describe alternatives you've considered

**Probably it's the most easiest component to develop, just simple toast or alert (loading status, done uploading, warning, waiting, ext...). and it's importing too in any web app I suppose.**

### Screenshots or Videos

![130804494-a9d2d69c-f170-4576-b2e1-0bb7f13dd92d](https://github.com/user-attachments/assets/32b65585-e5b0-4b17-8548-6c07feb915f5)

**Comment by Kyle-Gagnon-99** [comment]
Easy to develop? Accessibility is very difficult and a toast is in the same boat of being difficult. It's not that easy to develop a fully accessible beautiful looking toast component. It is also in the backlog which can be found [here](https://nextuioss.featurebase.app/p/toast-2).

**Comment by jprosevear** [comment]
https://github.com/nextui-org/nextui/issues/2560#issuecomment-2309555174

**Comment by wingkwong** [comment]
toast: tracked in https://github.com/nextui-org/nextui/issues/2053
alert: tracked in https://github.com/nextui-org/nextui/issues/2250
