### ISSUE TITLE
[BUG] - Modal component doesn't work as expected

### ISSUE THREAD

**Issue by JuanGelabert** [nextui-org/nextui#3719]
### NextUI Version

2.4.6

### Describe the bug

Hello there! Im new using NextUI so I will try to be clear.
My idea is to open a form contained in a modal window once i click any CTA button on the website.
Im not advanced in the project but it is very simple.

3 Components:
 -Hero
 -ModalCTA
 -ContactForm
 
 Problem:
  At this basic Hero section I call the ModalCTA component since it renders the button to open the Modal window. When I click the button, the Modal doesn't show as expected. It appears at the bottom of the website, and seems to have non styles on it.
  ModalCTA component is just a copy of the basic provided at the NextUI Docs with the blur backdrop. I only added a "text" prop to change the button text whenever i want to reuse it (that works well)
  ContactForm is called inside ModalBody but is not coded yet, only renders a title to see something.
  
  So I dont know whats happening here. Sorry to bother you with such a noob problem, hope you can help me.
  PD: running on Chrome and Firefox Dev
  Since i havent made the repo yet, will attach some screens.
  
  
  

### Steps to Reproduce the Bug or Issue

1- Click the CTA button
2- Scroll down to see the "modal" after all the content of the website

### Expected behavior

As a User i expect to see a modal window with a contact form inside it once I click CTA button

### Screenshots or Videos

![imagen](https://github.com/user-attachments/assets/6b0f14af-a684-404e-ae72-4e820419637f)

![imagen](https://github.com/user-attachments/assets/a99dc357-c3d8-4b0f-9c8e-17d0cbee1898)

at this last screen you can realise what im talking about
![imagen](https://github.com/user-attachments/assets/11475330-c57a-42e3-a1f9-bc38fade4cdc)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
Please share a minimal reproducible environment instead of screenshots.

**Comment by CRIS-117** [comment]
I have the same problem with that component, exactly the same thing happens to me, the modal, instead of appearing above the components, appears at the bottom. Also another problem is, if I click on the button to open the modal, it doesn't work, I have to click on another part of the screen for it to appear.

**Comment by wingkwong** [comment]
@CRIS-117 please share the version and a reproducible environment.

**Comment by CRIS-117** [comment]
@wingkwong go to the following link https://ecommerce.iwsservices.com/product-detail/1 is my project, below the page there is a button that says "Agregar reseña", click on it and then click outside the button and the modal It will appear but below everything, sometimes if the footer appears at the top, if you change the screen size it will appear.

**Comment by CRIS-117** [comment]
![image](https://github.com/user-attachments/assets/559d4a1b-9598-4110-ae5f-e2712d2bb929)

**Comment by wingkwong** [comment]
@CRIS-117 we can't investigate anything just based on the screenshot. We need a minimal reproducible environment.

**Comment by CRIS-117** [comment]
@wingkwong Sorry, I shared this link: [](https://ecommerce.iwsservices.com/product-detail/1)

There you can see what happens in the button that I mentioned. It is the project where I captured it.

**Comment by wingkwong** [comment]
I know you've shared the link and I can see the behaviour. We need to source code to check. The minimal reproducible environment is like codesandbox so that I can check your implementation and debug based on that.

**Comment by CRIS-117** [comment]
@wingkwong  Thanks, I found the problem in my project when I tried to replicate the environment. The problem has to do with a CSS file, which modifies the overall project with the "*" selector, I changed this selector for another and this problem was solved.

**Comment by juliushuck** [comment]
For me the problem was that when a Modal does not have ModalContent as a child it was just getting displayed at the bottom of the page without any styling. After adding ModalContent into the creation of the modal, it worked perfectly.
