### ISSUE TITLE
Docs: add more package managers

### ISSUE THREAD

**Issue by Jay-Karia** [nextui-org/nextui#3722]
### Is your feature request related to a problem? Please describe.

In the installation [page](https://nextui.org/docs/guide/installation) there are commands in `npm`.
Whereas in some pages, (such as https://nextui.org/docs/guide/cli) there are commands found in multiple package managers.

### Describe the solution you'd like

Add more package managers tabs as in https://nextui.org/docs/guide/cli

### Describe alternatives you've considered

N/A

**Comment by macci001** [comment]
May I work on this?
