### ISSUE TITLE
[BUG] - fullWidth prop of Select component does nothing

### ISSUE THREAD

**Issue by paveldpetrov** [nextui-org/nextui#3745]
### NextUI Version

2.4.6

### Describe the bug

In the [docs ](https://nextui.org/docs/components/select#:~:text=%2D-,fullWidth,-boolean) of the Select component it is said the following:
`fullWidth Whether the select should take up the width of its parent.` and it defaults to true.
However, when I pass `fullWidth={false}`, nothing changes.

### Your Example Website or App

https://codesandbox.io/p/devbox/little-river-rnm39w

### Steps to Reproduce the Bug or Issue

1. Add a simple Select inside some wrapper with fixed width.
2. Set `fullWidth` prop to `false`
3. Observe that the Select still takes the full width of its parent.

### Expected behavior

I would expect setting `fullWidth` to `false` to remove the `w-full` className from the `base` slot.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
some preliminary findings:
- by default, there is `w-full` on `base`, `mainWrapper` etc
- setting `fullWidth` to `false` does not override the default variant (`true`)
- may double check with other components as well

**Comment by macci001** [comment]
Can I work on this? @wingkwong

**Comment by wingkwong** [comment]
@macci001 Go ahead.
