### ISSUE TITLE
[BUG] - Table Avatar Image Opacity set to 0 by default

### ISSUE THREAD

**Issue by Maryam-Ejaz** [nextui-org/nextui#3747]
### NextUI Version

@nextui-org/table": "^2.0.39"

### Describe the bug

The Avatar image is not visible in the NEXTUI table. It becomes visible when I remove "opacity-0" class from developer tools.

This is how the Table appears by default:
![default](https://github.com/user-attachments/assets/ffa99d42-1088-40f7-8963-549f44949f8f)

When you remove the opacity-0 class, it shows avatar images:
![Screenshot 2024-09-13 175807](https://github.com/user-attachments/assets/013748b0-eeb4-4e16-8f61-c31043195975)

### Steps to Reproduce the Bug or Issue

To reproduce it, just copy the code for table with avatars from official [Next UI site](https://nextui.org/docs/components/table).

### Expected behavior

I expect the images in avatar to be visible.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
I couldn't reproduce the issue. That class will be overrode by `data-[loaded=true]:opacity-100`. Please share a minimal reproducible environment so that we can take a look on the same page.

**Comment by wingkwong** [comment]
Closing - inactivity
