### ISSUE TITLE
[BUG] - `Autocomplete` and `Select` are not functioning properly.

### ISSUE THREAD

**Issue by AnYiEE** [nextui-org/nextui#3753]
### NextUI Version

2.4.7

### Describe the bug

After I upgraded to 2.4.7, these two components cannot work properly as before. The left side window in the video is 2.4.7, and the right one is 2.4.6.

https://github.com/user-attachments/assets/0ffb1c6d-e345-4e8c-b8da-84a966a2acfa

In addition, the hover background color of the `Select` component has been modified.

![2.4.7](https://github.com/user-attachments/assets/35f69306-0573-4f36-9f2c-34be315333a4)
![2.4.6](https://github.com/user-attachments/assets/7a2637fd-2829-4bf6-9014-538ae28cc840)

The text color of the button also becomes difficult to distinguish.

![2.4.7 vs 2.4.6](https://github.com/user-attachments/assets/a98b467e-fcc0-447e-bdc8-4d45f6ee5873)

### Steps to Reproduce the Bug or Issue

As shown in the window on the left side of the video.

### Expected behavior

As shown in the window on the right side of the video.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
- for autocomplete not closing, i need more info. Can you ping me in discord?
- for style-related issues, if you have custom styles like `group-data-[xxx=xxx]:xxxxx`, now you need to change to `group-data-[xxx=xxx]/select:xxxxx`.

**Comment by AnYiEE** [comment]
> * for autocomplete not closing, i need more info. Can you ping me in discord?
> * for style-related issues, if you have custom styles like `group-data-[xxx=xxx]:xxxxx`, now you need to change to `group-data-[xxx=xxx]/select:xxxxx`.

* Ok.
* I did not specify any styles as you said, you can see the source code [here](https://github.com/AnYiEE/touhou-mystia-izakaya-assistant/blob/v0.9.23/app/components/sideFilterIconButton.tsx#L93).

**Comment by wingkwong** [comment]
Resolved in v2.4.8.
