### ISSUE TITLE
[BUG] - Blocked aria-hidden on a <button> element because the element that just received focus must not be hidden from assistive technology users

### ISSUE THREAD

**Issue by J4v4Scr1pt** [nextui-org/nextui#3781]
### NextUI Version

2.4.8

### Describe the bug

Anyone else get this error when opening and closing the select?
![image](https://github.com/user-attachments/assets/16ee8c6e-b4e7-426e-8aab-b9ca48c6d631)

I Cleaned a whole page in our application and just passed this code from the docs to only have the select. The error pressits.

		<Select label="Select an animal" className="max-w-xs">
				{[
					{ key: 'cat', label: 'Cat' },
					{ key: 'dog', label: 'Dog' },
					{ key: 'elephant', label: 'Elephant' },
					{ key: 'lion', label: 'Lion' },
					{ key: 'tiger', label: 'Tiger' },
					{ key: 'giraffe', label: 'Giraffe' },
					{ key: 'dolphin', label: 'Dolphin' },
					{ key: 'penguin', label: 'Penguin' },
					{ key: 'zebra', label: 'Zebra' },
					{ key: 'shark', label: 'Shark' },
					{ key: 'whale', label: 'Whale' },
					{ key: 'otter', label: 'Otter' },
					{ key: 'crocodile', label: 'Crocodile' },
				].map((animal) => (
					<SelectItem key={animal.key}>{animal.label}</SelectItem>
				))}
			</Select>

### Steps to Reproduce the Bug or Issue

Use the Select component and open/close it a couple of times.

### Expected behavior

Not to throw the error.

### Operating System Version

Window 10

### Browser

Chrome

**Comment by wingkwong** [comment]
I couldn't reproduce the issue.

1. please try on v2.4.8.
2. if it's still reproducible on your side, please share a minimal reproducible environment.

**Comment by J4v4Scr1pt** [comment]
> I couldn't reproduce the issue.
> 
> 1. please try on v2.4.8.
> 2. if it's still reproducible on your side, please share a minimal reproducible environment.

Hey!

Thx 4 quick reply! I just realized I wrote wrong version, we do have 2.4.8 sry!

But I was creating an StackBlitz to reproduce the error and could not.. either. I just tested our application in the Prod enviorment and the error do not appear there.

Locally it happens once and I need to refresh the page to get it again otherwise it wont show. And it's not only the select, I also get for the DatePicker..

A strange bug for sure, I don't know how to procede with this?

**Comment by J4v4Scr1pt** [comment]
I still have this issue, but not all of my colleagues do. I will mark this as closed, because it seems to be locally on my computer for some strange reason.

**Comment by tielushko** [comment]
@J4v4Scr1pt were you able to resolve the issue somehow? Currently seeing this issue when using React components within astro framework.

**Comment by J4v4Scr1pt** [comment]
> @J4v4Scr1pt were you able to resolve the issue somehow? Currently seeing this issue when using React components within astro framework.

Hi, no unfortunately not. We still have this at my company application. Only first render, only dev..
I also have a private application running NextJs 14 with latest NextUI, same error.

I have tried to understand where and why this happen. But I got nothing, so I just ignore it for now because I have no time digging any deeper. Annoying yes, but it's only dev.. at least for me 😅.

**Comment by CanRau** [comment]
Got the same error trying `DateRangePicker` tho the same happened when I tried to use the same from `react-aria-components` directly, so far didn't find a workaround

**Comment by J4v4Scr1pt** [comment]
> Got the same error trying `DateRangePicker` tho the same happened when I tried to use the same from `react-aria-components` directly, so far didn't find a workaround

Ok interseting you got it with react-aria directly 🤔. I have now seen this in Production also a couple of times.
Very hard to understand why it happens.

**Comment by CanRau** [comment]
Interestingly this seems to happen only when I use the `DateRangePicker` within a (RadixUI) `Dialog` 🤔 

Switching to NextUI [Modal](https://nextui.org/docs/components/modal) fixed it for me 🥳
