### ISSUE TITLE
[BUG] - Autocomplete does not work when the clear button is hit (regression)

### ISSUE THREAD

**Issue by TheCodeDestroyer** [nextui-org/nextui#3783]
### NextUI Version

2.4.8

### Describe the bug

When pressing clear, the autocomplete does not work anymore as in dropdown does not open while the change events work properly.
The bug can be observed on the documentation page as well.

Seems like this used to be the bug in the past and was fixed but the bug has returned:
#2146 

### Your Example Website or App

 https://nextui.org/docs/components/autocomplete#colors

### Steps to Reproduce the Bug or Issue

1. Press clear button when available
2. Try to type and the dropdown does not open (it does open again if you focus out and re-focus the input, but as soon as you clear the autocomplete it stops working again)

### Expected behavior

As I user I expect the clear button not to effect the functionality of the autocomplete.

### Screenshots or Videos

https://github.com/user-attachments/assets/e1faf407-fab4-4fc3-8e42-170a99d9f523

### Operating System Version

macOS

### Browser

Chrome

**Comment by nnimoyoefoki** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by abhinav700** [comment]
I can confirm that this issue exists not only for macOS but also for ubuntu
I have begun working on it.

**Comment by abhinav700** [comment]
@wingkwong I have referred to the PR on issue #2146 to fix this.

**Comment by chenyingkeai** [comment]
In my project, I can't even click the clear button😂
