### ISSUE TITLE
[BUG] - Listbox Item href causes full reload (regression)

### ISSUE THREAD

**Issue by TheCodeDestroyer** [nextui-org/nextui#3784]
### NextUI Version

2.4.8

### Describe the bug

When navigating via Listbox it causes full page reload.
This seemed to be an issue in v2.4.0, but supposedly was fixed in `"@nextui-org/link": "0.0.0-canary-20240529193819"`.
Initial issue: #3105

### Your Example Website or App

https://codesandbox.io/p/devbox/nextjs-ui-46j3v2

### Steps to Reproduce the Bug or Issue

You can clearly see that the links on the left (using listbox) reload the whole page, while the links on left (using Link) only do it clientside

### Expected behavior

As a user I want the ListboxItem links to properly use client side navigation if `NextUIProvider` is properly defined 

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
suggest to revisit after RA version bump. I think there's something changed internally on their side.

**Comment by TheCodeDestroyer** [comment]
> suggest to revisit after RA version bump. I think there's something changed internally on their side.

@wingkwong pardon my ignorance, but which lib is RA?

**Comment by wingkwong** [comment]
React Aria. NextUI is built on top of it.

**Comment by hardchor** [comment]
Updating `@react-aria/utils` to `3.25.2` fixed it for me.

My `package.json`:

```
{
...
  "resolutions": {
    "@react-aria/utils": "^3.25.2"
  },
}
```

**Comment by ayanamists** [comment]
> Updating `@react-aria/utils` to `3.25.2` fixed it for me.
> 
> My `package.json`:
> 
> ```
> {
> ...
>   "resolutions": {
>     "@react-aria/utils": "^3.25.2"
>   },
> }
> ```
> 
> **NB**: This might be a yarn-specific feature, check how to override transitive dependencies in your favourite package manager (e.g. `overrides` in npm)

Seems not work for me

**Comment by abonoit** [comment]
> Seems not work for me

Same thing here, an href on a ListboxItem keeps reloading the page.
I'm on the latest react-aria version

**Comment by caish-cloud-admin** [comment]
> "resolutions": {
>     "@react-aria/utils": "^3.25.2"
>   },

This worked for me. I used 3.26.0 since that is the newest version.
