### ISSUE TITLE
[BUG] - SWITCH Component Width Excessely 

### ISSUE THREAD

**Issue by therealsras** [nextui-org/nextui#3791]
### NextUI Version

2.4.8

### Describe the bug

![image](https://github.com/user-attachments/assets/6195386e-a953-460f-bce7-d5998e420673)

`<Switch
        onClick={() =>
          theme === "light" ? setTheme("dark") : setTheme("light")
        }
        defaultSelected
        size="lg"
        color="primary"
        startContent={<SunIcon />}
        endContent={<MoonIcon />}
         className="border-1"
      ></Switch>`

### Steps to Reproduce the Bug or Issue

Code above

### Expected behavior

Should be no more width

### Operating System Version

macOS, Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
probably the margin should be shown when there is a label.

**Comment by therealsras** [comment]
> probably the margin should be shown when there is a label.

yes, possibly.

**Comment by qwertyroop** [comment]
Status : I will raise a PR asap, currently working on it

**Comment by wingkwong** [comment]
@qwertyroop any updates?

**Comment by ShrinidhiUpadhyaya** [comment]
I can pick this up, if no one is looking into it.

**Comment by wingkwong** [comment]
didn't see he made a commit nor update here. Reassigned to @ShrinidhiUpadhyaya.
