### ISSUE TITLE
[BUG] - When the Button color is set to danger, the color is not displaying correctly.

### ISSUE THREAD

**Issue by baijunjie** [nextui-org/nextui#3792]
### NextUI Version

2.4.8

### Describe the bug

component: "Button"
variant: "ghost"
color: "danger"
the color is not displaying correctly.

### Steps to Reproduce the Bug or Issue

Left button is "danger"
<img width="111" alt="image" src="https://github.com/user-attachments/assets/7190f921-bd5e-4aef-b8ae-e52f9f4a67be">

Left button hover
<img width="109" alt="image" src="https://github.com/user-attachments/assets/0d4b9cec-4192-4d66-8dfd-9b7dbec11fca">
<img width="380" alt="image" src="https://github.com/user-attachments/assets/78f18dbc-58d8-4b66-a41e-1e88a4ea254f">

Right button hover
<img width="110" alt="image" src="https://github.com/user-attachments/assets/a21280d3-6d9b-4af9-82bc-3c09e22a320f">
<img width="556" alt="image" src="https://github.com/user-attachments/assets/95d9552e-7a6f-4998-b997-1a127b687a9d">

### Expected behavior

The behavior of "danger" and "primary" should be consistent.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3764. you may use canary version at this moment or add `data-[hover=true]:!text-danger-foreground`.
