### ISSUE TITLE
[BUG] - Datepicker showing wrong date and week days.

### ISSUE THREAD

**Issue by SD-Siraj** [nextui-org/nextui#3794]
### NextUI Version

^14.2.3

### Describe the bug

I am having an issue the current date and the format of time is showing wrong. Particularly on IOS, and sometime occurs on chrome as well. Look at the week days. 

### Steps to Reproduce the Bug or Issue

Click on datepicker icon. It shows the current date one day before.

### Expected behavior

This should work as it looks on its official website.

### Screenshots or Videos

![Screenshot from 2024-09-23 13-01-13](https://github.com/user-attachments/assets/7fdd801b-ca05-4106-950b-51d30453f601)

### Operating System Version

MacOS, Windows

### Browser

Safari

**Comment by wingkwong** [comment]
1. please update the version. we don't have `^14.2.3`
2. is your current date 24th Sep by the time you created this issue? what timezone are you in and what is your browser timezone?
3. please share a sandbox environment so that we can take a look. Thanks.

**Comment by SD-Siraj** [comment]
The current date was Sep 23 2024 when I created this issue. However, the week day was showing wrong. The week day must be Monday instead of Sunday.

**Comment by wingkwong** [comment]
![image](https://github.com/user-attachments/assets/99f44173-17aa-4963-b144-dcb21d1ab5d6)

seems it is related to the timezone. please share those info.

**Comment by SD-Siraj** [comment]
Arabian Standard Time
Time zone in Saudi Arabia (GMT+3)
Tuesday, 24 September 2024, 9:29 am

**Comment by SD-Siraj** [comment]
I have also verified it in next ui official website it shows correct datetime. But I am getting wrong week day for current date at my end.

**Comment by wingkwong** [comment]
please share a sandbox environment.
