### ISSUE TITLE
[BUG] - Button

### ISSUE THREAD

**Issue by shubhammr21** [nextui-org/nextui#3799]
### NextUI Version

2.4.8

### Describe the bug

In button's `ghost` variant, with color `danger`, I am expecting the dark text in light mode but it stays white, in dark mode, text is white. it is working fine with other color values but not with danger.

### Steps to Reproduce the Bug or Issue

1. Set theme by following nextui docs in next js project
2. added this button
```
<Button
  color="danger"
  variant="ghost"
  startContent={<IconBrandGoogle />}
>
  Sign in
</Button>
 ```
3. set theme to light mode

### Expected behavior

As a user, I expected black text in light mode behavior but i am seeing white text in button
 

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/d8135d57-02db-4a36-a74e-fd3a742487ca)
![image](https://github.com/user-attachments/assets/03ec124a-0d63-4e07-ac81-6702ea080a2a)

### Operating System Version

- MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3764. you may use canary version at this moment or add `data-[hover=true]:!text-danger-foreground`.
