### ISSUE TITLE
[Feature Request] Particular component theming 

### ISSUE THREAD

**Issue by cdfornari** [nextui-org/nextui#380]
### Is your feature request related to a problem? Please describe.

I think it is necessary to be able to set default props, media queries and override styles for each component inside createTheme function, so you can customize each Next UI component according to the current theme

### Describe the solution you'd like

Adding a components arg to the createTheme func or a new prop to the 2nd arg object, that receives another object with the components you want to customize and the styles

### Describe alternatives you've considered

Similar to Material UI

**Comment by jrgarciadev** [comment]
Hey @cdfornari I appreciate your suggestion, however, we want to make the `createTheme` function as simple as possible and with only one task, which is to modify the theme `tokens` (e.g. colours, spacings, fontSizes, ...etc), if you want to create custom components based on the NextUI components, here's the docs 

https://nextui.org/docs/theme/override-styles
https://stitches.dev/docs/overriding-styles
