### ISSUE TITLE
[BUG] - Table elements require a children element

### ISSUE THREAD

**Issue by vladserikov** [nextui-org/nextui#3800]
### NextUI Version

2.4.8

### Describe the bug

When adding a TableHeader element for typescript, a mandatory children element is required as a props. 
Shouldn't children be optional?

### Steps to Reproduce the Bug or Issue

1. Add Table element.
2. Add TableHeader element or other table's element.

### Expected behavior

I expect that the typescript will stop requiring children to be passed as props

### Screenshots or Videos

![table1](https://github.com/user-attachments/assets/8ac43513-06b7-47ae-90d1-d695f0a9d69a)
![table2](https://github.com/user-attachments/assets/953425ee-3472-4786-a1f7-476d4356adb7)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
> Shouldn't children be optional?

No. It's mandatory from accessibility perspective. You may refer to WCAG for more info.
