### ISSUE TITLE
[BUG] - Right padding on Switch component

### ISSUE THREAD

**Issue by Gaic4o** [nextui-org/nextui#3806]
### NextUI Version

2.4.8

### Describe the bug

Padding is applied to the right side of the Switch component. What I'm curious about is whether this right padding should be applied when the text on the right side of the Switch component is activated. Currently, the padding on the right side of the Switch component is unconditionally applied, so when you use the Switch component, there is always a margin on the right side, which is frustrating.

### Steps to Reproduce the Bug or Issue

In the Switch component's official documentation, right padding is unconditionally applied.

![image](https://github.com/user-attachments/assets/44dd16a7-bd75-4c55-bac1-4c72abcd4377)

### Expected behavior

There is no string text in the Switch component, but padding is always applied to the right, so when using this Switch component, it is cumbersome to work with the UI due to the right padding.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Ideally it should be applied when there is a label. Closing this as duplicate because it has been reported here: https://github.com/nextui-org/nextui/issues/3806
