### ISSUE TITLE
[BUG] - Custom Styled Components do not have subcomponents

### ISSUE THREAD

**Issue by cdfornari** [nextui-org/nextui#381]
### Describe the bug

I made a custom styled Card component using the styled function

<img width="884" alt="Screen Shot 2022-03-31 at 3 30 54 PM" src="https://user-images.githubusercontent.com/64043046/161143181-bf4557fa-e72c-4fb8-a25e-da7a3836eb40.png">

Then when trying to use subcomponents of Card component as Card.Header, I realize that it does not have the subcomponents

<img width="789" alt="Screen Shot 2022-03-31 at 3 32 40 PM" src="https://user-images.githubusercontent.com/64043046/161143221-935e5595-3b90-482c-bef7-ef67c36dd46e.png">

So I have to import Card from NextUI just to use the subcomponents
<img width="781" alt="Screen Shot 2022-03-31 at 3 38 50 PM" src="https://user-images.githubusercontent.com/64043046/161143257-30bd9adb-65ca-4054-8fe0-a5ab25d7ef76.png">

This is the error log: 
Property 'Footer' does not exist on type 'StyledComponent<CardComponent<HTMLDivElement, CardProps>, {}, { xs: string; sm: string; md: string; lg: string; xl: string; xsMax: string; smMax: string; mdMax: string; ... 6 more ...; light: string; }, CSS<...>>'.

### Steps to Reproduce the Bug or Issue

1)  Make a custom styled Card component using the styled function of a component that has subcomponents - ex: Card - Card.Header
2) Try to use its subcomponents

### Expected behavior

Custom styled components are supposed to receive the parent's subcomponents so we can use them

### Operating System Version

macOS

### Browser

Safari

**Comment by jrgarciadev** [comment]
Hey @cdfornari the screenshots are not visible, could you please upload them again?

**Comment by cdfornari** [comment]
Sorry I just uploaded them again

**Comment by jrgarciadev** [comment]
Thanks!, here's an example with a workaround -> https://codesandbox.io/s/custom-styled-card-c8uoeq?file=/App.js

It looks like Stitches is not preserving the object attributes 🤔 , 

I'll look into it, thanks for reporting it 🙌🏻
