### ISSUE TITLE
[BUG] - Date Range Picker not selecting date inside Shadcn Sheet

### ISSUE THREAD

**Issue by Saltys-Git** [nextui-org/nextui#3814]
### NextUI Version

2.4.8

### Describe the bug

Hi,
I'm using Date Range Picker in a Shadcn Sheet to select dates but could not select any date in the popover calendar. When I try to select the date the popover calendar closes. I tried using 
`useEffect(() => { if(!isOpen) { return () => { document.body.style.pointerEvents = "" }; } }, [isOpen,]);`
for the Date Range Picker and it solves the issue a bit but it closes after pressing on one date, and then the start and end date get the single value which was selected. Some Shadcn git issue says to add modal={true} prop to the popover but in Date Range Picker there is no way to access calendar popover props.

### Steps to Reproduce the Bug or Issue

To re-create the scenario try using Date Range Picker inside a Shadcn Sheet.

### Expected behavior

As expected it should be selecting the date but the cursor seems to be not detecting the popover.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
please provide a reproducible environment.

**Comment by wingkwong** [comment]
Closing - inactivity
