### ISSUE TITLE
[BUG] - Setting the value of the controlled Select component does not work

### ISSUE THREAD

**Issue by rokukoo** [nextui-org/nextui#3818]
### NextUI Version

2.4.8

### Describe the bug

Originally, I was using `react-hook-form` to manage the Select component, but I found that if I directly used `from.setValue()` to set the value of the Select, the Select component would not show the item selected.

Through `react devtools`, I found that the `value prop` of the Select component was indeed modified, but it did not show that the item was selected, and when submitting the form, it still prompted that the `Select` was empty. In addition, I found that `state.selectedKeys` in `HiddenSelect` was also empty.

### Steps to Reproduce the Bug or Issue

Here is a simple example that can reproduce the bug

1. Define a state to control the value of Select
``` typescript
const [value, setValue] = useState("");
```
2. Use the Select component as follows
``` tsx
 <Button onPress={() => setValue(1)}>1</Button>
 <Select
  label="Region"
  value={value}
  items={[
    { id: 1, name: "a" },
    { id: 2, name: "b" },
    { id: 3, name: "c" },
  ]}
>
  {(item: { id: number; name: string }) => (
    <SelectItem key={item.id}>{item.name}</SelectItem>
  )}
</Select>
```
3. Click the button, theoretically the value of Select will be modified, and the selection box will show that it is selected.

### Expected behavior

Theoretically the value of Select will be modified, and the selection box will show that it is selected.

### Screenshots or Videos

After clicking the button, the value of Select does change, but the Select component does not show that it is selected.
![647025c46af7cc7b895a6903dc99197e](https://github.com/user-attachments/assets/bae843f2-f5b4-4d14-b306-b6e455c59c90)
![8fe48f7ee157dd89a615ea8fc19803e3](https://github.com/user-attachments/assets/54857313-5da9-4ba6-8dff-d8bdb54dd8d5)
![fab8b3e4141a2830f2fb408686f28f01](https://github.com/user-attachments/assets/40785734-a933-4bb8-97f1-f100c42707fe)
![23552de5f0884b496af85a9a709511f8](https://github.com/user-attachments/assets/45ce707f-31a0-41dc-bd12-b874b1f97caa)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
please share the full code including your react-hook-form. a minimal reproducible environment would be better.

**Comment by AnYiEE** [comment]
I think you should use `selectedKeys` instead of `value`.

**Comment by wingkwong** [comment]
`value` is uncontrolled. If you are using controlled one, please use `selectedKeys`.  
ref: https://nextui.org/docs/components/select#controlled
