### ISSUE TITLE
[BUG] - Input Component showing aria-borders and cant remove

### ISSUE THREAD

**Issue by moizkamran** [nextui-org/nextui#3820]
### NextUI Version

2.4.8

### Describe the bug

<img width="628" alt="image" src="https://github.com/user-attachments/assets/0ee28521-5276-4f43-ade2-1fe414519383">

For every <Input /> component, there is this aria border that doesnt go away. Even in light or dark mode.

### Your Example Website or App

checflow.vercel.app/register

### Steps to Reproduce the Bug or Issue

1. Use an input component

### Expected behavior

I expected it to NOT have those borders

### Operating System Version

macOS

### Browser

Chrome

**Comment by moizkamran** [comment]
Also, I've tried different computers, browsers and checked overlapping css files. Nothing seems to fix the issue. You can also see the aria label when you inspect it.

<img width="452" alt="image" src="https://github.com/user-attachments/assets/da281383-d32d-4846-af80-7b0b0f4465b8">

**Comment by AnYiEE** [comment]
There is a part of content in your stylesheet, where the 'border-*' property generates a border, but this CSS is not present in the official example of NextUI. You can check where it comes from.

```
[type=text],[type=email],[type=url],[type=password],[type=number],[type=date],[type=datetime-local],[type=month],[type=search],[type=tel],[type=time],[type=week],[multiple],textarea,select {
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none;
	background-color: #fff;
	border-color: #6b7280;
	border-width: 1px;
	border-radius: 0;
	padding: .5rem .75rem;
	font-size: 1rem;
	line-height: 1.5rem;
	--tw-shadow: 0 0 #0000
}
```

**Comment by wingkwong** [comment]
@moizkamran please provide a minimal reproducible environment.

**Comment by moizkamran** [comment]
Thank you all, it seemed one of my libs were messing with the stylesheets.
