### ISSUE TITLE
[BUG] - Tabs component is too much buggy

### ISSUE THREAD

**Issue by aliamiri1380** [nextui-org/nextui#3825]
### NextUI Version

2.4.6

### Describe the bug

this simple code for changing view based on tab index always return 0 index.
the view changes but it looks like that setSelected only could be changed inside Tabs component, after setting new value from SwipeableViews it suddenly set it to 0 again ...

```
"use client"

import { Tabs, Tab } from "@nextui-org/react";
import { useEffect, useState } from "react";
import SwipeableViews from "react-swipeable-views";

export default ({items, ...props}) => {
    const [selected, setSelected] = useState(0);

    useEffect(() => {
        console.log(selected);
    }, [selected])

    return (
        <div dir="ltr">
            <Tabs {...props} onSelectionChange={setSelected} selectedKey={selected}>
                <Tab key={0} title={'helllllo'}></Tab>
                <Tab key={1} title={'helllllo'}></Tab>
                <Tab key={2} title={'helllllo'}></Tab>
            </Tabs>
            <SwipeableViews enableMouseEvents index={selected} onChangeIndex={(i) => setSelected(i)} >
                <div className="bg-slate-100">123</div>
                <div className="bg-slate-200">456</div>
                <div className="bg-slate-300">789</div>
            </SwipeableViews>
        </div>
    );
}
```

nextui: 2.4.6
reac-swipeable-views: 0.14.0
nextjs: 14.2.7
react: ^18

### Steps to Reproduce the Bug or Issue

run code anywhere in a nextjs env 

### Expected behavior

its expected to view change when pressing tabs and also tabs change when swiping or changing views 

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
This is not the usage by design. Internally there is a state management (handled by `react-stately`). The state can only be mutated by its APIs. Therefore,  updating `selected` externally won't work in this way.

**Comment by aliamiri1380** [comment]
so is there any option to enable us to have these kinda functionality with nextui components ?

**Comment by wingkwong** [comment]
Unfortunately not. Tabs is a collection-based component. Supposedly, you can't just use one of the elements (e.g. navigation) alone.
