### ISSUE TITLE
[BUG] - 404 for v1 docs

### ISSUE THREAD

**Issue by freelook** [nextui-org/nextui#3835]
### NextUI Version

v1

### Describe the bug

404 error for https://v1.nextui.org/

### Your Example Website or App

https://v1.nextui.org/

### Steps to Reproduce the Bug or Issue

Go to https://v1.nextui.org/

### Expected behavior

Docs for v1

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
It's back on now. Thanks for reporting.
