### ISSUE TITLE
[BUG] - Docs not opening

### ISSUE THREAD

**Issue by nsikakowo** [nextui-org/nextui#3840]
### NextUI Version

lastest

### Describe the bug

The website is not opening, I get site cannot be reached, and its been like this since last week

browser:Chrome
OS: Mac

### Steps to Reproduce the Bug or Issue

- just open a browser and navigate to  https://nextui.org/

### Expected behavior

Website should open properly so user can use the docs

### Operating System Version

MAC

### Browser

Chrome

**Comment by wingkwong** [comment]
able to access.

![image](https://github.com/user-attachments/assets/7e61819c-d851-4874-b12b-f6403f7c91be)
