### ISSUE TITLE
[BUG] - Label placement - "outside" conflicts with Multiline property in Select element

### ISSUE THREAD

**Issue by Doomce** [nextui-org/nextui#3841]
### NextUI Version

2.4.8

### Describe the bug

Label position in `Select` element depends on properties: `labelPlacement="outside"` and `isMultiline={true}`.
With `isMultiline={true}`, the label is displayed inside select border.

Code:
```
<Select
    labelPlacement={"outside"}
    label="User Properties"
    placeholder="Select properties"
    className="w-full"
    variant="bordered"
    selectedKeys={selection}
    items={properties}
    isMultiline={true}
>
    {properties.map((prop) => (
        <SelectItem key={prop} value={prop}>
            {prop}
        </SelectItem>
    ))}
</Select>
```
Visualization:
![{A192378E-3109-424F-946D-5DAFA995D999}](https://github.com/user-attachments/assets/67e96a5c-2de6-4e34-bbb9-c5308e2fbf41)

Other way - without multiline
Code:
```
<Select
    labelPlacement={"outside"}
    label="User Properties"
    placeholder="Select properties"
    className="w-full"
    variant="bordered"
    selectedKeys={selection}
    items={properties}
    isMultiline={false}
>
    {properties.map((prop) => (
        <SelectItem key={prop} value={prop}>
            {prop}
        </SelectItem>
    ))}
</Select>
```

![{4CD0C7F0-1E86-450D-8DB0-471937B00975}](https://github.com/user-attachments/assets/e8b747fc-c4ac-4a56-a7a3-c52f38a023b6)

Also, This issue can be found in NextUI documentation:
![{93606098-AA3E-4F3D-8BA7-0DBFCA4ABA19}](https://github.com/user-attachments/assets/760f16d6-5df5-4786-91ca-84216a103243)

### Steps to Reproduce the Bug or Issue

1. Import Select, SelectItem components.
2. Create `Select` element
3. Set `labelPlacement="outside"` property to the item.
4. Set `isMultiline={true}` property to the item.

### Expected behavior

Label placement should not depend by `isMultiline` value (the label should be outside)

### Operating System Version

Windows

### Browser

Chrome

**Comment by macci001** [comment]
Looking on this issue.
