### ISSUE TITLE
[BUG] - Running NextUI in a monorepo Yarn Berry environment results in an error.

### ISSUE THREAD

**Issue by Gaic4o** [nextui-org/nextui#3851]
### NextUI Version

2.4.8

### Describe the bug

I installed nextui in the `yarn berry` monorepo environment using `turbo`. But when I run it, an error occurs.

### Steps to Reproduce the Bug or Issue

1. install the turbo repo environment.  `yarn dlx create-turbo@latest`
2. migrate the monorepo environment from yarn classic to yarn berry.
3. yarn dlx create-next-app@latest apps/my-app
4. install a new `nextui` project in `my-app` apps. `npm install @nextui-org/react framer-motion`
5. `Tailwind CSS Setup` and `Provider Setup` together.
6. run the project with next dev.
```
./app/globals.css.webpack[javascript/auto]!=!../../.yarn/__virtual__/next-virtual-71db4a0ca8/4/.yarn/berry/cache/next-npm-14.2.14-ec3d370484-10c0.zip/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[2]!../../.yarn/__virtual__/next-virtual-71db4a0ca8/4/.yarn/berry/cache/next-npm-14.2.14-ec3d370484-10c0.zip/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[3]!./app/globals.css
ReferenceError: nextui is not defined
Import trace for requested module:
./app/globals.css.webpack[javascript/auto]!=!../../.yarn/__virtual__/next-virtual-71db4a0ca8/4/.yarn/berry/cache/next-npm-14.2.14-ec3d370484-10c0.zip/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[2]!../../.yarn/__virtual__/next-virtual-71db4a0ca8/4/.yarn/berry/cache/next-npm-14.2.14-ec3d370484-10c0.zip/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[14].oneOf[12].use[3]!./app/globals.css
./app/globals.css
....
ReferenceError: nextui is not defined
```

### Expected behavior

It doesn’t seem like the error is occurring due to the Turbo monorepo environment. I think the issue might be with yarn berry not being able to fetch "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}", or perhaps the error is happening because yarn berry doesn’t use node_modules.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
please share a sandbox

**Comment by wingkwong** [comment]
Closing - inactivity
