### ISSUE TITLE
[Feature Request] Autocomplete for large list items

### ISSUE THREAD

**Issue by MinChanSike** [nextui-org/nextui#3852]
### Is your feature request related to a problem? Please describe.

How to prevent performance issue on binding large list item in Autocomplete?
According by example, it may cause redering performance issue when opening the Autocomplete item and scroll the items.
https://codesandbox.io/p/devbox/new-fog-9p8xrg?workspaceId=16cf6a15-f7fd-4124-bb70-c306aa11fd6e

### Describe the solution you'd like

As a user, I expected to find and select the option even it is long list or small list.
Just type in the Autocomplete textbox and select the item that I would like to choose.

### Describe alternatives you've considered

expected to integrate with `react-virtuoso` or `react-virtualized` or `react-window` for large list item.

**Comment by wingkwong** [comment]
let's track here: #3047
