### ISSUE TITLE
[BUG] - Date-picker isRequired property is not working

### ISSUE THREAD

**Issue by artemavrin** [nextui-org/nextui#3859]
### NextUI Version

2.4.8

### Describe the bug

I’ve set the field as required, but when submitting the form, the required validation is not triggered

### Your Example Website or App

https://codesandbox.io/p/devbox/datepicker-nextui-rqn8m4

### Steps to Reproduce the Bug or Issue

1. Leave the Date-picker field empty
2. Submit the form without selecting a date

### Expected behavior

The form should not submit if the Date-picker field is left empty

### Operating System Version

macOS

### Browser

Chrome

**Comment by shraddha761** [comment]
Can I work in this issue?

**Comment by wingkwong** [comment]
Yes. @macci001 is correct. Just to supplement a bit. If you wish to make it globally, you can define it in NextUIProvider. See `validationBehavior ` in https://nextui.org/docs/api-references/nextui-provider#props.

**Comment by artemavrin** [comment]
thanks a lot, but what about Select component? there is no validationBehavior prop, and it looks different on validation

**Comment by macci001** [comment]
yeah, the select for now is using the validationBehavior as `native` which needs to be [enhanced yet](https://github.com/nextui-org/nextui/blob/canary/packages/components/select/src/use-select.ts#L642). There is discrepancy which needs to be fixed.
