### ISSUE TITLE
Can't override Image containerCss width & height.

### ISSUE THREAD

**Issue by i-tengfei** [nextui-org/nextui#386]
Now there is no way to override Image containerCss width & height.
Is this by design on purpose?

https://github.com/nextui-org/nextui/blob/934577bba4730f1db5175205dd2f4cc622fcb786/packages/react/src/image/image.tsx#L130-L134

**Comment by jrgarciadev** [comment]
Hey @i-tengfei yes it's designed on purpose to ensure the image aspect ratio if you really need to change the container `width` | `height` you can use the container class `nextui-image-container`
