### ISSUE TITLE
[BUG] - LOCALLY_IMPORTED_IMAGES_NOT_VIISBLE

### ISSUE THREAD

**Issue by devendra-hackingly** [nextui-org/nextui#3862]
### NextUI Version

2.4.8

### Describe the bug

In my Device i have locally stored images and i already correctly imported image in component when putting that image string in src  in the curly brackets the image is not visible

### Your Example Website or App

http://github.com

### Steps to Reproduce the Bug or Issue

import { Image } from '@nextui-org/react';
 <Image
          width={360}
          height={230}
          src={showcasetwo}
          alt="Event Registration"
          isZoomed
          // className=' object-cover transform transition-transform duration-300 ease-in hover:scale-110'
        />

### Expected behavior

in result the image locally stored is not visible why

### Operating System Version

windows

### Browser

Chrome

**Comment by macci001** [comment]
Hey @devendra-hackingly, could you please provide the code sandbox, because it seems to work fine for me.
Simple code-demo I used to verify:
```
import { Image } from "@nextui-org/react";

const Page = () => {
    return (<>
        <Image
            src="./test-image.png"
        />
    </>)
}
export default Page;
```

**Comment by devendra-hackingly** [comment]
import { Image } from ***@***.***/react'
import showcasetwo from '@/assets/images/showcasetwo.jpg'
import React from 'react'

const OrganizingEventsCTA = () => {
  return (
    <div>
        <Image
        width={360}
        height={230}
        alt='showcase image error'
        src={showcasetwo}
        />
    </div>
  )
}

export default OrganizingEventsCTA

**Comment by devendra-hackingly** [comment]
> Hey @devendra-hackingly, could you please provide the code sandbox, because it seems to work fine for me. Simple code-demo I used to verify:
> 
> ```
> import { Image } from "@nextui-org/react";
> 
> const Page = () => {
>     return (<>
>         <Image
>             src="./test-image.png"
>         />
>     </>)
> }
> export default Page;
> ```
> 
> maybe you can re-check the src address to image again?

``

**Comment by devendra-hackingly** [comment]
import { Image } from '@nextui-org/react'
import showcasetwo from '@/assets/images/showcasetwo.jpg'
import React from 'react'

const OrganizingEventsCTA = () => {
  return (
    <div>
        <Image 
        width={360}
        height={230}
        alt='showcase image error'
        src={showcasetwo}
        />
    </div>
  )
}

export default OrganizingEventsCTA

**Comment by devendra-hackingly** [comment]
how can i import or use locally stored images could you just tell me in the
case of nextui-org/react the locally stored images are  not working


import { Image } from ***@***.***/react'
import showcasetwo from '@/assets/images/showcasetwo.jpg'
import React from 'react'

const OrganizingEventsCTA = () => {
  return (
    <div>
        <Image
        width={360}
        height={230}
        alt='showcase image error'
        src={showcasetwo}
        />
    </div>
  )
}

export default OrganizingEventsCTA

**Comment by macci001** [comment]
The reason I think you are facing this issue is that `src` attribute should have image location and not the image itself. Can you try this out once?

**Comment by devendra-hackingly** [comment]
Yes, I have already tried that with location directly but the image still
not visible
in the src attribute we need to put a link why can't we put a string in
curly brackets image itself..?
