### ISSUE TITLE
[BUG] - Input component ref is pointing to nowhere

### ISSUE THREAD

**Issue by londonbarrett** [nextui-org/nextui#3864]
### NextUI Version

2.4.8

### Describe the bug

Ref properties are always null

### Steps to Reproduce the Bug or Issue

1. Add an Input component
2. add the ref to the Input component
3. try to set focus on the input
4. if you log ref.current, it is always null

### Expected behavior

ref should point to the inner input element

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Please share the minimal reproducible environment.

**Comment by londonbarrett** [comment]
sorry, I was using react-hook-form and for some reason it was not working, then I made a basic component and it's working fine. Thanks for your attention.
