### ISSUE TITLE
[BUG] - Tabs

### ISSUE THREAD

**Issue by Masculinn** [nextui-org/nextui#3866]
### NextUI Version

^2.4.8

### Describe the bug

Component
-------------------------------------------------------------------------------------------
```
import { AlbumEditorProps, AlbumSettingProps } from "@/components/interfaces";
import { Tabs, Tab } from "@nextui-org/react";
import { FaVideo } from "react-icons/fa6";
import { MdInsertPhoto } from "react-icons/md";
import { IoIosMusicalNotes } from "react-icons/io";
import { useState } from "react";

export const AlbumEditor: React.FC<AlbumEditorProps> = (props) => {
  const { albumCards, onSubmit } = props;
  const [selected, setSelected] = useState("photo");

  return (
    <div className="flex w-full flex-col h-auto">
      <Tabs
        aria-label="Options"
        color="primary"
        size="lg"
        variant="bordered"
        className="dark w-full h-auto"
        onSelectionChange={setSelected}
      >
        <Tab
          key="photo"
          className="dark"
          title={
            <div className="flex items-center space-x-2">
              <MdInsertPhoto className="w-6 h-6" />
              <span>Photos</span>
            </div>
          }
        ></Tab>
        <Tab
          key="audio"
          title={
            <div className="flex items-center space-x-2">
              <IoIosMusicalNotes className="w-6 h-6" />
              <span>Music</span>
            </div>
          }
        ></Tab>
        <Tab
          key="video"
          title={
            <div className="flex items-center space-x-2">
              <FaVideo className="w-6 h-6" />
              <span>Videos</span>
            </div>
          }
        ></Tab>
      </Tabs>
    </div>
  );
};
```
---------------------------------------------------------------------

**Issue description**

`Type 'Dispatch<SetStateAction<string>>' is not assignable to type '(key: Key) => void'.
  Types of parameters 'value' and 'key' are incompatible.
    Type 'Key' is not assignable to type 'SetStateAction<string>'.
      Type 'number' is not assignable to type 'SetStateAction<string>'.ts(2322)
selection.d.ts(23, 3): The expected type comes from property 'onSelectionChange' which is declared here on type 'IntrinsicAttributes & Props<object> & { ref?: Ref<HTMLElement> | undefined; }'`

### Steps to Reproduce the Bug or Issue

Read description 

### Expected behavior

Expected state changes however it is not working properly

### Operating System Version

Windows

### Browser

Chrome

**Comment by AnYiEE** [comment]
Import Key type `import {type Key} from 'react';`
Then use `const [selected, setSelected] = useState<Key>("photo");`
