### ISSUE TITLE
[BUG] - page number in Pagination

### ISSUE THREAD

**Issue by rhnnss** [nextui-org/nextui#3870]
### NextUI Version

2.4.8 

### Describe the bug

<img width="606" alt="image" src="https://github.com/user-attachments/assets/e1e8c566-e09d-4a37-93ca-14ec9c129fc5">
<img width="684" alt="image" src="https://github.com/user-attachments/assets/a6e61d93-ba35-4f09-911a-673364df99a1">
<img width="619" alt="image" src="https://github.com/user-attachments/assets/0c942d02-4e81-4f0d-abb4-d7b947475a57">

### Steps to Reproduce the Bug or Issue

Reproduction Steps:

1. Navigate to the page with the NextUI pagination component.
3. Observe the initial pagination setup. The pagination component displays page numbers properly (e.g., 1, 2, 3, 4).
5. Click on the next page button (> or a numbered button for a subsequent page).
7. Observe the page numbers after navigating to the next page.
9. 
10. Actual behavior: The pagination displays duplicate numbers (e.g., two "2"s, two "3"s, etc.), or improper pagination behavior with missing or incorrectly ordered numbers.
11. Attempt to navigate to another page to confirm the pagination remains inconsistent.

### Expected behavior

Expected behavior: The pagination component should update to reflect the correct page numbers, and only one instance of each page number should be displayed.

### Screenshots or Videos

https://jam.dev/c/e83971d9-3f1f-46b5-af87-ec9ea9b8f027

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
please provide a minimal reproducible environment.

**Comment by wingkwong** [comment]
Closing - inactivity
