### ISSUE TITLE
[BUG] - Selection in Autocomplete Component Triggers Click in Adjacent Components on Mobile Devices

### ISSUE THREAD

**Issue by parteekmalik** [nextui-org/nextui#3871]
### NextUI Version

2.4.8

### Describe the bug

On mobile devices, tapping to select an item from the Autocomplete component unintentionally triggers the selection or action of adjacent components. This behavior leads to unexpected interactions and user experience issues.

### Steps to Reproduce the Bug or Issue

Use a mobile device or a mobile emulator.
Render multiple Autocomplete components on the same page (e.g., two or more).
Tap on an item in the first Autocomplete component.
Observe that the second Autocomplete component or adjacent button also registers a click or selection.

### Expected behavior

When selecting an item from the Autocomplete component, only the selected item should be updated. Adjacent components, such as buttons or other Autocomplete instances, should not be affected or triggered.

### Screenshots or Videos

[Screencast from 11-10-24 04:02:10 PM IST.webm](https://github.com/user-attachments/assets/6675ed3b-f4ca-4e8f-aaec-aa542cd2f828)

### Operating System Version

Linux

### Browser

Chrome

**Comment by parteekmalik** [comment]
"use client";
import { Autocomplete, AutocompleteItem, Button } from "@nextui-org/react";
const animals = [
  { label: "Cat", value: "cat", description: "The second most popular pet in the world" },
  { label: "Dog", value: "dog", description: "The most popular pet in the world" },
  { label: "Elephant", value: "elephant", description: "The largest land animal" },
  { label: "Lion", value: "lion", description: "The king of the jungle" },
  { label: "Tiger", value: "tiger", description: "The largest cat species" },
  { label: "Giraffe", value: "giraffe", description: "The tallest land animal" },
  {
    label: "Dolphin",
    value: "dolphin",
    description: "A widely distributed and diverse group of aquatic mammals",
  },
  { label: "Penguin", value: "penguin", description: "A group of aquatic flightless birds" },
  { label: "Zebra", value: "zebra", description: "A several species of African equids" },
  {
    label: "Shark",
    value: "shark",
    description: "A group of elasmobranch fish characterized by a cartilaginous skeleton",
  },
  {
    label: "Whale",
    value: "whale",
    description: "Diverse group of fully aquatic placental marine mammals",
  },
  { label: "Otter", value: "otter", description: "A carnivorous mammal in the subfamily Lutrinae" },
  { label: "Crocodile", value: "crocodile", description: "A large semiaquatic reptile" },
];
function Page() {
  const handleSubmit = () => {
    alert("butoon clicked");
  };
  return (
    <div className="flex w-full flex-col flex-wrap gap-4">
      <Autocomplete
        color={"primary"}
        defaultItems={animals}
        label="Favorite Animal"
        placeholder="Search an animal"
        defaultSelectedKey={"cat"}
        className="max-w-xs"
      >
        {(item) => <AutocompleteItem key={item.value}>{item.label}</AutocompleteItem>}
      </Autocomplete>
      <Autocomplete
        color={"primary"}
        defaultItems={animals}
        label="Favorite Animal"
        placeholder="Search an animal"
        defaultSelectedKey={"cat"}
        className="max-w-xs"
      >
        {(item) => <AutocompleteItem key={item.value}>{item.label}</AutocompleteItem>}
      </Autocomplete>
      <Button onPress={() => handleSubmit()}>submit</Button>
    </div>
  );
}

export default Page;

**Comment by parteekmalik** [comment]
"use client";
import { Autocomplete, AutocompleteItem, Button } from "@nextui-org/react";
const animals = [
  { label: "Cat", value: "cat", description: "The second most popular pet in the world" },
  { label: "Dog", value: "dog", description: "The most popular pet in the world" },
  { label: "Elephant", value: "elephant", description: "The largest land animal" },
  { label: "Lion", value: "lion", description: "The king of the jungle" },
  { label: "Tiger", value: "tiger", description: "The largest cat species" },
  { label: "Giraffe", value: "giraffe", description: "The tallest land animal" },
  {
    label: "Dolphin",
    value: "dolphin",
    description: "A widely distributed and diverse group of aquatic mammals",
  },
  { label: "Penguin", value: "penguin", description: "A group of aquatic flightless birds" },
  { label: "Zebra", value: "zebra", description: "A several species of African equids" },
  {
    label: "Shark",
    value: "shark",
    description: "A group of elasmobranch fish characterized by a cartilaginous skeleton",
  },
  {
    label: "Whale",
    value: "whale",
    description: "Diverse group of fully aquatic placental marine mammals",
  },
  { label: "Otter", value: "otter", description: "A carnivorous mammal in the subfamily Lutrinae" },
  { label: "Crocodile", value: "crocodile", description: "A large semiaquatic reptile" },
];
function Page() {
  const handleSubmit = () => {
    alert("butoon clicked");
  };
  return (
    <div className="flex w-full flex-col flex-wrap gap-4">
      <Autocomplete
        color={"primary"}
        defaultItems={animals}
        label="Favorite Animal"
        placeholder="Search an animal"
        defaultSelectedKey={"cat"}
        className="max-w-xs"
      >
        {(item) => <AutocompleteItem key={item.value}>{item.label}</AutocompleteItem>}
      </Autocomplete>
      <Autocomplete
        color={"primary"}
        defaultItems={animals}
        label="Favorite Animal"
        placeholder="Search an animal"
        defaultSelectedKey={"cat"}
        className="max-w-xs"
      >
        {(item) => <AutocompleteItem key={item.value}>{item.label}</AutocompleteItem>}
      </Autocomplete>
      <Button onPress={() => handleSubmit()}>submit</Button>
    </div>
  );
}

export default Page;

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/3449

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/3449
