### ISSUE TITLE
[BUG] - datepicker calendarProps classnames don't apply

### ISSUE THREAD

**Issue by hruiz13** [nextui-org/nextui#3872]
### NextUI Version

2.4.8

### Describe the bug

When I want to apply a className to the calendar within the datePicker, the original design is damaged, and the classNames that are added do not work.
```

import { Card, CardBody, DatePicker } from "@nextui-org/react";

export default function Home() {
  return (
    <Card className="mx-auto mt-4 max-w-md">
      <CardBody className="text-center">
        <h1 className="text-5xl">Date picker test</h1>
        <p className="text-xl">
          <DatePicker
            hideTimeZone
            showMonthAndYearPickers
            calendarProps={{
              content: "bg-primary",
              tw: "bg-primary text-white",
              navButtonProps: {
                //className: "text-red-500", // <- if uncommment this, all styles fails
              },
              color: "secondary",
              classNames: {
                headerWrapper: ["bg-transparent"],
                gridWrapper: ["bg-primary"],
                pickerWrapper: ["bg-primary"],
                nextButton: "text-red-500", // <- This do not work
              },
              buttonPickerProps: {
                color: "secondary",
                style: {},
                variant: "solid",
                //className: "text-white", // <- if uncommment this, all styles fails
              },
            }}
          />
        </p>
      </CardBody>
    </Card>
  );
}

```

![image](https://github.com/user-attachments/assets/d82cd123-4eed-4331-b975-1a5f556a9224)
![image](https://github.com/user-attachments/assets/27021a32-b597-493a-acbe-dd2e1077bc73)

### Your Example Website or App

https://codesandbox.io/p/devbox/elated-khayyam-9nkpz3?workspaceId=809e93b8-69d3-49b4-b28e-5ff7a616bda9

### Steps to Reproduce the Bug or Issue

1. add classNames on calendarProps of DatePicker

### Expected behavior

Apply the classNames

### Operating System Version

macOs

### Browser

Chrome

**Comment by wingkwong** [comment]
`calendarProps` is not propagated correctly to the calendar and has been resolved in this [PR](https://github.com/nextui-org/nextui/pull/3773). You may use canary version or wait for the next release.
