### ISSUE TITLE
[BUG] - Error with Extra attributes

### ISSUE THREAD

**Issue by dimylkas** [nextui-org/nextui#3875]
### NextUI Version

2.2

### Describe the bug

I'm using NextUI with Next.js, and I want to remove the error from the log. ()

Follow your guide - https://nextui.org/docs/frameworks/nextjs

### Steps to Reproduce the Bug or Issue

Pre. follow the installation guide - https://nextui.org/docs/frameworks/nextjs

1. Or`npx create-next-app -e https://github.com/nextui-org/next-app-template`
2. cd into the folder and `npm run dev`

### Expected behavior

As a developer, I expecting 0 issues, meanwhile after initial setup i see error.

![image](https://github.com/user-attachments/assets/467f9a68-be85-4467-94ee-9cb86cf2e6d6)

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
couldn't reproduce. please provide a sandbox that shows that error.

![image](https://github.com/user-attachments/assets/72f13c9b-26c7-4a1e-a815-0afa60a102bd)

<img width="1494" alt="image" src="https://github.com/user-attachments/assets/a40c384d-e353-48ba-b3f3-33c0c5a96dfa">

**Comment by dimylkas** [comment]
<img width="1905" alt="image" src="https://github.com/user-attachments/assets/09e22ea6-6e75-4330-b362-1682af8ed4d6">

**Comment by wingkwong** [comment]
@dimylkas based on the error message, it seems that it's from the browser extension passing it. Do you have Grammarly extension in your browser?

**Comment by dimylkas** [comment]
@wingkwong thanks for a quick finding. You are right it's due to that extension
