### ISSUE TITLE
[BUG] - CLICK_PASSES_BEHIND_AUTOCOMPLETE

### ISSUE THREAD

**Issue by Likeakir** [nextui-org/nextui#3877]
### NextUI Version

2.4.8

### Describe the bug

Clicking an autocomplete element has errors when there's some other element behind it. Currently I'm working with next-ui 2.4.8, and what I'm experiencing is that when an autocomplete deploys the list of elements, if i click one, and behind it there's for example an other autocomplete, the item is selected, but the autocomplete from behind pops too, all in one click.

It's important to notice that this only happens when the screen size is not full.

### Your Example Website or App

https://carhub-nextjs-kohl.vercel.app/es/coches

### Steps to Reproduce the Bug or Issue

1. Click one of the autocomplete components.
2. Select an item which placement is right above the next autocomplete.
3. You'll see that the second autocomplete pops

### Expected behavior

As a user, I expected the item to get selected and thats it, but i see the items from behind getting selected too with the same click.

### Screenshots or Videos

Uploading Screen-Recording-2024-10-12-at-2.mp4…

### Operating System Version

macOs

### Browser

Chrome

**Comment by macci001** [comment]
Hi @Likeakir,
This issue is tracked here in: https://github.com/nextui-org/nextui/issues/3449. 
Just for the quick summary the issue occurs due to the chromium bug.

**Comment by wingkwong** [comment]
closing as duplicate
