### ISSUE TITLE
[BUG] - Select with numeric keys are not supported

### ISSUE THREAD

**Issue by mngu** [nextui-org/nextui#3880]
### NextUI Version

2.4.8

### Describe the bug

Hi,

I got a little issue with the Select (which is working great btw).
The `selectedKeys` prop does not work when keys are numeric.

### Steps to Reproduce the Bug or Issue

Here's how to reproduce it:
```js
<Select selectedKeys={[1]}>
  <SelectItem key={1} value={1}>
    Num 1
  </SelectItem>
</Select>
```

I got the following warning:
`Select: Keys "1" passed to "selectedKeys" are not present in the collection.`

### Expected behavior

The SelectItem with a numeric key should be selected

### Operating System Version

macOS

### Browser

Chrome

**Comment by ryo-manba** [comment]
Thanks for the issue!

To handle numeric keys correctly in SelectItem, you can structure the items like this:

```tsx
const items = [
  { id: 1, value: "Num 1" },
  { id: 2, value: "Num 2" },
  { id: 3, value: "Num 3" },
];

<Select items={items}>
  {(item) => <SelectItem>{item.value}</SelectItem>}
</Select>
```

However, a `key` is currently required, so this will be addressed in the following PR.
https://github.com/nextui-org/nextui/pull/3883

**Comment by mngu** [comment]
Thanks for the quick fix !
