### ISSUE TITLE
[BUG] - Select: missing key attribute in the code example

### ISSUE THREAD

**Issue by lucasromerodb** [nextui-org/nextui#3888]
### NextUI Version

2.4.2

### Missing key attribute in the code example ([NextUI doc reference](https://nextui.org/docs/components/select#dynamic-items))

[file to fix](https://github.com/nextui-org/nextui/blob/canary/apps/docs/content/components/select/dynamic.ts)

```
key={animal.key}
```

### Current
```
<Select
  items={animals}
  label="Favorite Animal"
  placeholder="Select an animal"
  className="max-w-xs"
>
  {(animal) => <SelectItem>{animal.label}</SelectItem>} 👈💥
</Select>
```

### Should be
```
<Select
  items={animals}
  label="Favorite Animal"
  placeholder="Select an animal"
  className="max-w-xs"
>
  {(animal) => <SelectItem key={animal.key}>{animal.label}</SelectItem>} 👈✅
</Select>
```

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/979554d9-0f32-48d9-87e9-5357fae6cfbd)

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3883. Please wait for next release.
