### ISSUE TITLE
[Feature Request] Add a Scroll to top button matched to websites design theme

### ISSUE THREAD

**Issue by MastanSayyad** [nextui-org/nextui#3892]
### Is your feature request related to a problem? Please describe.

Hi @wingkwong 

I would like to add a scroll to top button for the website so that users can scroll back to the top of the page with only one clickscroll-to-top

### Describe the solution you'd like

none

### Describe alternatives you've considered

None

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/48d32660-758d-4018-a3f0-562a585d2fa2)

**Comment by wingkwong** [comment]
1. you can just click navbar item with one click also. 
2. bottom right area is reserved by kapa.
