### ISSUE TITLE
[BUG] - NextUI modal is zooming in when the keyboard is active in the mobile safari browser.

### ISSUE THREAD

**Issue by melodyxpot** [nextui-org/nextui#3896]
### NextUI Version

2.4.8

### Describe the bug

The modal width is full now and it is fine with another browsers.
But in only mobile safari browser, the modal is zoom in when the keyboard is active through textarea or input field.

### Your Example Website or App

https://momoreis.vercel.app

### Steps to Reproduce the Bug or Issue

1. Open the web app
2. Click "Giriş Yap" button in the navbar
3. Focus on the username or password input field.

### Expected behavior

As a user, I want to just enter the text in the input field but the modal is zoom in so seems like it's a bug for the users.

### Screenshots or Videos

https://github.com/user-attachments/assets/ca216293-f03f-4a93-8cc3-b7a2c0d26ec2

### Operating System Version

iOS

### Browser

Safari

**Comment by wingkwong** [comment]
This behaviour is actually expected and not caused from our side. If the input font size is less than 16px, your page will automatically be zoomed in when the user on mobile iOS device click into the input. 

Therefore, here's two general solutions.

1. just increase your font size or
2. set the max viewport scale like `maximum-scale=1`. (not recommended)

**Comment by melodyxpot** [comment]
Thanks

**Comment by SweydManaf** [comment]
@melodyxpot did u find the better solution?

**Comment by melodyxpot** [comment]
> [@melodyxpot](https://github.com/melodyxpot) did u find the better solution?

I couldn't find the better solution. For now, I fixed the problem with @wingkwong 's solution but I am not sure if that is good. I am looking for another solution but need to take a look at it more.
