### ISSUE TITLE
[BUG] - [input] endContent and clearButton cannot appear at the same time

### ISSUE THREAD

**Issue by IsDyh01** [nextui-org/nextui#3901]
### NextUI Version

2.4.8

### Describe the bug

In the input component, if you pass endContent and isClearable props at the same time, endContent has a high priority, only endContent is displayed, and when endContent is clicked, the input box content is also cleared. endContent will also disappear

### Your Example Website or App

https://codesandbox.io/p/devbox/priceless-meitner-qys5k6?file=%2FApp.jsx%3A11%2C21-11%2C38

### Steps to Reproduce the Bug or Issue

1.pass the endContent prop
2.pass the isClearable prop
3.only appear the endContent
4.click the endContent

### Expected behavior

endContent and clearButton can appear at the same time, and endContent cannot be clicked

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/4ecc3559-3daa-4ff1-ba32-ffa7a1e71e5d)

### Operating System Version

window

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/2254. There's already a PR handling it.
