### ISSUE TITLE
[BUG] - Two(instead of one) clear icons pop up from `<Input />`

### ISSUE THREAD

**Issue by jjangga0214** [nextui-org/nextui#3907]
### NextUI Version

2.4.8

### Describe the bug

Two clear icons pop up.

<img width="293" alt="스크린샷 2024-10-17 오전 9 53 38" src="https://github.com/user-attachments/assets/851e2b73-458e-439b-97f8-f66355c2103f">

### Steps to Reproduce the Bug or Issue

```tsx
import { Input } from '@nextui-org/react'

<Input isClearable type="search" variant="underlined" />
```

### Expected behavior

I expected only a single clear icon appear.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Thanks for reporting. Indeed we need to handle that pseudo-element button in this case.

**Comment by sairiteshdomakuntla** [comment]
Hello @jjangga0214 ,I'd like to contribute to this, can you assign this to me?

**Comment by jjangga0214** [comment]
@sairiteshdomakuntla Since I am not a maintainer, you may ask others like @wingkwong.

**Comment by wingkwong** [comment]
@sairiteshdomakuntla go ahead.

**Comment by sanuj21** [comment]
can i look into this ? @wingkwong
