### ISSUE TITLE
The table has some bugs

### ISSUE THREAD

**Issue by just-ads** [nextui-org/nextui#3908]
### NextUI Version

2.4.8

### Describe the bug

1.When a switch component exists in the table and `showSelectionCheckboxes` is `true`, the single-machine multiple selection box will change the switch state to enabled at the same time.
![Apex_1729131438508](https://github.com/user-attachments/assets/4ad3d1e1-ac4a-4167-8d5e-3c978837373d)
2.In addition to using nextui's own buttons, using other tags will trigger multiple selections

### Steps to Reproduce the Bug or Issue

1.Set `showSelectionCheckboxes=true`
2.Add `Switch` Component
3.Click checkbox

### Expected behavior

1.Clicking the checkbox should not cause the switch state to change.
2.Clicking other custom buttons will not trigger the selection.

### Operating System Version

windown

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/2959
