### ISSUE TITLE
[BUG] - Links with a text-gradient broken on hover with CHROME ONLY

### ISSUE THREAD

**Issue by TheAlphaReturns** [nextui-org/nextui#391]
### Describe the bug

I think it is a CSS thing where if you use opacity with a text-gradient link on Chrome, it will just become black. For now, can I just disable the opacity for hovering?

### Your Example Website or App

https://inertia-unblocker.vercel.app

### Steps to Reproduce the Bug or Issue

1. hover on the main site link on GOOGLE CHROME ONLY

### Expected behavior

Works like it does on firefox

### Operating System Version

Windows, ChromeOS

### Browser

Chrome

**Comment by TheAlphaReturns** [comment]
OBTW its a <nextUI.Link> INSIDE OF a <nextUI.Text> with linear gradient property

**Comment by TheAlphaReturns** [comment]
full disclaimer, this is my second issue on this repo, but thanks.

**Comment by TheAlphaReturns** [comment]
any follow up?

**Comment by imentu** [comment]
![5ea315ca2840981a58d8f7faf4a849e](https://user-images.githubusercontent.com/62298214/166683129-6dd148aa-d4e5-4360-8cbd-dca6b549a1a5.png)
@TheAlphaReturns add these css attribute to the <nextUI.Link> could solve your problem

**Comment by TheAlphaReturns** [comment]
I'll try it.

**Comment by imentu** [comment]
@TheAlphaReturns is the problem solved?

**Comment by TheAlphaReturns** [comment]
oh sorry, no its not
