### ISSUE TITLE
DateRangePicker locale not working

### ISSUE THREAD

**Issue by pjatupon** [nextui-org/nextui#3910]
### NextUI Version

2.4.8

### Describe the bug

my code 
```
<I18nProvider locale="th-TH-u-ca-buddhist">
                            <DateRangePicker
                                //key={placement}
                                aria-label="Date (International DateRangePicker)"
                                label="เลือกช่วงวันที่"
                                labelPlacement="outside"
                                visibleMonths={2}
                                value={date}
                                onChange={setDate}
                            />
                        </I18nProvider>
```

### Steps to Reproduce the Bug or Issue

please help me.
how to set locale for calendar

### Expected behavior

![image](https://github.com/user-attachments/assets/ef0a26bf-682d-4827-9138-d87a18b066d7)

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/9a8af6f8-5e93-4a2d-8f74-642020d33c4f)

### Operating System Version

windows 11

### Browser

Chrome

**Comment by pjatupon** [comment]
I want to display like this
![image](https://github.com/user-attachments/assets/aa2edda3-1890-4a36-90b8-2eaa097bdde3)

**Comment by gamersover** [comment]
Same issue here in chinese. nextui version: 2.4.8

![image](https://github.com/user-attachments/assets/1b41fe10-bf5b-40f3-b860-df0e209d1631)

**Comment by omidbaharifar** [comment]
I had a similar problem, downgrading @react-aria/i18n to version 3.11.1 solved the problem.

**Comment by pjatupon** [comment]
> I had a similar problem, downgrading @react-aria/i18n to version 3.11.1 solved the problem.

It's work. Thank you.

**Comment by mamadohack** [comment]
> I had a similar problem, downgrading @react-aria/i18n to version 3.11.1 solved the problem.

thank you man , u saved my life !
