### ISSUE TITLE
[BUG] - Accordion get Hydration Error in Next.js

### ISSUE THREAD

**Issue by mengxi-ream** [nextui-org/nextui#3914]
### NextUI Version

2.4.8

### Describe the bug

I use this
```
import {Accordion, AccordionItem} from "@nextui-org/react";

export default function App() {
  const defaultContent =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";

  return (
    <Accordion>
      <AccordionItem key="1" aria-label="Accordion 1" title="Accordion 1">
        {defaultContent}
      </AccordionItem>
      <AccordionItem key="2" aria-label="Accordion 2" title="Accordion 2">
        {defaultContent}
      </AccordionItem>
      <AccordionItem key="3" aria-label="Accordion 3" title="Accordion 3">
        {defaultContent}
      </AccordionItem>
    </Accordion>
  );
}
```

### Steps to Reproduce the Bug or Issue

1. use the previous accordion code
2. put it in nextjs
3. Clear cache of your page and open a new tab
4. I use Arc browser by the way

### Expected behavior

no hydration error

### Screenshots or Videos

![CleanShot 2024-10-17 at 19 14 33@2x](https://github.com/user-attachments/assets/3907a560-5a91-48f0-a036-cc243ea20a7f)

### Operating System Version

macOS, Arc Browser

### Browser

Other (add additional context)

**Comment by macci001** [comment]
Hi, this should be client component.
Can u please add `"use client"` to the top of the file and try once?

Making it the client component makes the code something like below:
```
"use client"

import {Accordion, AccordionItem} from "@nextui-org/react";

export default function App() {
  const defaultContent =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";

  return (
    <Accordion>
      <AccordionItem key="1" aria-label="Accordion 1" title="Accordion 1">
        {defaultContent}
      </AccordionItem>
      <AccordionItem key="2" aria-label="Accordion 2" title="Accordion 2">
        {defaultContent}
      </AccordionItem>
      <AccordionItem key="3" aria-label="Accordion 3" title="Accordion 3">
        {defaultContent}
      </AccordionItem>
    </Accordion>
  );
}
```

**Comment by mengxi-ream** [comment]
> Hi, this should be client component. Can u please add `"use client"` to the top of the file and try once?
> 
> Making it the client component makes the code something like below:
> 
> ```
> "use client"
> 
> import {Accordion, AccordionItem} from "@nextui-org/react";
> 
> export default function App() {
>   const defaultContent =
>     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";
> 
>   return (
>     <Accordion>
>       <AccordionItem key="1" aria-label="Accordion 1" title="Accordion 1">
>         {defaultContent}
>       </AccordionItem>
>       <AccordionItem key="2" aria-label="Accordion 2" title="Accordion 2">
>         {defaultContent}
>       </AccordionItem>
>       <AccordionItem key="3" aria-label="Accordion 3" title="Accordion 3">
>         {defaultContent}
>       </AccordionItem>
>     </Accordion>
>   );
> }
> ```

Thanks for the reply. I've checked my code, Accordion is in the client component. But I also found in Chrome, I don't have this hydration error issue after clearing the cache. This only happened in Arc browser after clearing the cache.

**Comment by mengxi-ream** [comment]
This is caused by the browser extension 豆包
