### ISSUE TITLE
[BUG] - Slider is not compaitable with RTL direction

### ISSUE THREAD

**Issue by Steveb599** [nextui-org/nextui#3918]
### NextUI Version

2.2.15 - slider

### Describe the bug

When using slider in a webapp that has direction "rtl" the slider behavior is not correct.

![image](https://github.com/user-attachments/assets/ba3fbd01-3a44-4a7b-afff-dc888071c137)

the thumb should be at the right and sliding left and not sliding right.

### Steps to Reproduce the Bug or Issue

Use slider with dir="rtl"

### Expected behavior

I expected slider will slide left and the starting point will be right. this is the opposite.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/898d0448-dd5b-4e41-b884-957626bf6720)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
This is how it looks like in canary branch. Can you share a minimal reproducible environment for us to investigate?

![image](https://github.com/user-attachments/assets/bc9bf4ae-e3dd-47dc-9494-c374cbda2864)

**Comment by wingkwong** [comment]
Closing - inactivity
