### ISSUE TITLE
[BUG] - fa-IR locale in datepicker not working

### ISSUE THREAD

**Issue by esmailshahbazi** [nextui-org/nextui#3920]
### NextUI Version

2.4.8

### Describe the bug

 months name and years do not changing when i set locale "fa-IR" for NextUIProvider and I18nProvider

### Steps to Reproduce the Bug or Issue

 months name and years do not changing when i set locale "fa-IR" for NextUIProvider and I18nProvider

### Expected behavior

 months name and years do not changing when i set locale "fa-IR" for NextUIProvider and I18nProvider

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
please provide a minimal reproducible environment

**Comment by esmailshahbazi** [comment]
> please provide a minimal reproducible environment

for example in this screenshot you see i set locale hi-IN-u-ca-indian but months name and years are gregory
![bug](https://github.com/user-attachments/assets/bb56a349-b146-485b-9726-4fa998fb3c12)
![bug2](https://github.com/user-attachments/assets/02133ceb-6363-4fcc-8f44-38477f9c4513)

and this is my provider.jsx
`<NextUIProvider>
        {children}
 </NextUIProvider>`

**Comment by esmailshahbazi** [comment]
**Library version**

@react-aria/i18n : 3.12.3
@internationalized/date: 3.5.6

NextUI Version
2.4.8

**Comment by wingkwong** [comment]
1. please paste the code here
2. can you also share your NextUIProvider?

**Comment by esmailshahbazi** [comment]
> 1. please paste the code here
> 2. can you also share your NextUIProvider?


**NextUIProvider**

`<NextUIProvider> {children} </NextUIProvider>`


**Codes**

`
"use client";
import React from "react";
import { DatePicker } from "@nextui-org/react";
import { now, parseAbsoluteToLocal } from "@internationalized/date";
import { I18nProvider } from "@react-aria/i18n";

export default function Test() {
  let [date, setDate] = React.useState(
    parseAbsoluteToLocal("2021-04-07T18:45:22Z")
  );

  return (
    <div className="flex flex-col gap-4">
      <I18nProvider locale="hi-IN-u-ca-indian">
        <DatePicker
          showMonthAndYearPickers
          variant="bordered"
          className="max-w-md"
          label="Appointment date"
          value={date}
          onChange={setDate}
        />
      </I18nProvider>
    </div>
  );
}
`

**Library version**

`
    "@nextui-org/react": "^2.4.8",
    "@internationalized/date": "^3.5.6",
    "@react-aria/i18n": "^3.12.3",
`

**Comment by esmailshahbazi** [comment]
and im using next ui in next.js 14 app router

**Comment by esmailshahbazi** [comment]
> please provide a minimal reproducible environment

i think datepicker doesn't work correctly in next.js framework
please check this out

https://codesandbox.io/p/devbox/nextui-datepicker-locale-fa-ir-2kd2h9

**Comment by esmailshahbazi** [comment]
Can anyone solve this problem?
Is there any hope?

**Comment by omidbaharifar** [comment]
I had a similar problem, downgrading @react-aria/i18n to version 3.11.1 solved the problem.
