### ISSUE TITLE
[Feature Request]Fix collection-based components

### ISSUE THREAD

**Issue by Scholar01** [nextui-org/nextui#3921]
### Is your feature request related to a problem? Please describe.

 Listbox/Menu/Table/Dropdown, they cannot be imported on Next.js without adding the use client; directive, even when we import them from individual packages.

### Describe the solution you'd like

I hope this can be fixed soon, You can use collection items directly in server components. Otherwise it is really painful and will make server-side rendering less secure.

### Describe alternatives you've considered

No, Please fix it as soon as possible, thank you very much!

**Comment by wingkwong** [comment]
tracked here. #1403
