### ISSUE TITLE
[BUG] DateRangePicker - (zoned) placeholder value breaks onChange events and state

### ISSUE THREAD

**Issue by sroidl-airup** [nextui-org/nextui#3926]
### NextUI Version

2.4.8

### Describe the bug

Context: I was trying to make the DateRangePicker timezone aware **without** providing pre-selected values.
Hence I used the placeholder attribute and provided a ZonedDateTime object.
This then seems to break the component: No placeholder value is shown and selecting start & end does not trigger the onChange eventhandler anymore.

### Steps to Reproduce the Bug or Issue

1. Create a DateRangePicker component (like the examples)
2. Provide **no** value prop
3. Provide placeholder prop `now(getLocalTimezone())` (methods imported from `@internationalized/date`)
4. Provide an onChange callback, e.g. `console.log`
5. Open DateRangePicker component 
6. Try to select start & end range

### Expected behavior

1. I expected to see the selected dates in the component and the component to close, BUT no date is show and the component stays open.

2. I expected the onChange-callback to console.log the selection, BUT no console.log is emitted.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
please provide a minimal reproducible environment.

**Comment by wingkwong** [comment]
Closing - inactivity
