### ISSUE TITLE
[BUG] - Date-picker International Calendar not working correctly in next.js framework

### ISSUE THREAD

**Issue by esmailshahbazi** [nextui-org/nextui#3929]
### NextUI Version

2.4.8

### Describe the bug

nextui datepicker doesn't work correctly in next.js framework with app router
for example in my codes you see i set locale hi-IN-u-ca-indian but months name and years are gregorian

### Steps to Reproduce the Bug or Issue

see more information here:

https://codesandbox.io/p/devbox/nextui-datepicker-locale-fa-ir-2kd2h9

### Expected behavior

nextui datepicker doesn't work correctly in next.js framework

### Screenshots or Videos

![bug](https://github.com/user-attachments/assets/d5dda202-2b4b-48e2-a1be-8aff33339c5a)
![bug2](https://github.com/user-attachments/assets/3256bf66-e25c-4eac-966e-788424cdbcf9)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
tracked here: #3920
