### ISSUE TITLE
[BUG] - Invalid prop `ref` supplied to `React.Fragment` when using next.js 15

### ISSUE THREAD

**Issue by kevinrss01** [nextui-org/nextui#3930]
### NextUI Version

2.4.8

### Describe the bug

When using the **Calendar** Components in my next.js app (15.0.0). I have an error 
`Invalid prop `ref` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.`

### Your Example Website or App

https://stackblitz.com/~/github.com/kevinrss01/bug-nextjs

### Steps to Reproduce the Bug or Issue

Just start the app and the error will show up

### Expected behavior

No error displayed on the screen

### Screenshots or Videos

<img width="1050" alt="Screenshot 2024-10-22 at 13 21 56" src="https://github.com/user-attachments/assets/d32c66fe-15ac-4aef-ab17-d2f0e859fd16">

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
The current version hasn't supported React 19 yet. Will be tracked in react 19 upgrade issue instead.

**Comment by SuperMitic** [comment]
I have the same issue with NextJS 15 and React 18.3.1 when using DatePicker

**Comment by wingkwong** [comment]
@SuperMitic please ensure it is really using 18.3.1. you may do the following.

```json
"pnpm": {
  "overrides": {
    "react-dom": "18.3.1",
    "react": "18.3.1"
  }
}
```

**Comment by SuperMitic** [comment]
> @SuperMitic please ensure it is really using 18.3.1. you may do the following.
> 
> ```json
> "pnpm": {
>   "overrides": {
>     "react-dom": "18.3.1",
>     "react": "18.3.1"
>   }
> }
> ```

Added the overrides, but I still have the issue

**Comment by wingkwong** [comment]
have you removed node_moduels and reinstall?

**Comment by SuperMitic** [comment]
> have you removed node_modules and reinstall?

Yes I tried that, but I discovered that NextJS has a built-in React and NextJS 15 App Router work only with React 19

**Comment by SuperMitic** [comment]
I have tried with the latest 2.5 beta that should support React 19 but I am getting the same issue

**Comment by DaniCastel** [comment]
Same issue with
```
    "@nextui-org/date-picker": "^2.1.8",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
 ```
