### ISSUE TITLE
[BUG] - NextJS 15 Support

### ISSUE THREAD

**Issue by therealsras** [nextui-org/nextui#3939]
### NextUI Version

2.4.8

### Describe the bug

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @nextui-org/react@2.4.8
npm error Found: react@19.0.0-rc-1631855f-20241023
npm error node_modules/react
npm error   react@"19.0.0-rc-1631855f-20241023" from the root project
npm error   peer react@"^18.2.0 || 19.0.0-rc-1631855f-20241023" from next@15.0.2-canary.6
npm error   node_modules/next
npm error     next@"15.0.2-canary.6" from the root project
npm error   3 more (react-dom, react-icons, styled-jsx)
npm error
npm error Could not resolve dependency:
npm error peer react@">=18" from @nextui-org/react@2.4.8
npm error node_modules/@nextui-org/react
npm error   @nextui-org/react@"^2.4.8" from the root project
npm error
npm error Conflicting peer dependency: react@18.3.1
npm error node_modules/react
npm error   peer react@">=18" from @nextui-org/react@2.4.8
npm error   node_modules/@nextui-org/react
npm error     @nextui-org/react@"^2.4.8" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
```

### Steps to Reproduce the Bug or Issue

upgrade to NextJS15

### Expected behavior

support NextJS15

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
Can you provide a minimal reproducible environment? Nextjs 15 should be compatible with react ^18.2.0. And did you get the error during dev or build?

**Comment by DylanPW** [comment]
I've noted that the accordion component does not seem to work with the basic NextUI template app and the first example from the docs, it appears the nested content isn't rendered but I haven't been able to pinpoint exactly what is occurring as there's no error thrown

**Comment by steebchen** [comment]
@wingkwong This issue is related to React 19 which Next.js 15 prefers (it upgrades users to react 19 rc release, but NextUI has a peer dependency of react ^18.

**Comment by wingkwong** [comment]
If it's using react 19, then it won't work. We're working on this part. It's still possible to use react 18 tho, at least one of our applications does that.

**Comment by therealsras** [comment]
Yes, the issue is due to the react dependencies on react 19-rc-xxx.

**Comment by ahmedhussein-code** [comment]
I am having the same error when I attempt to install nextui on a nextjs 15 project using the following command
npm install @nextui-org/react framer-motion

Any idea please how to fix this error? we are starting a new project with nextjs 15, and we would like to use nextui for our UI components

**Comment by wingkwong** [comment]
Nextjs 15 is using react 19 while it's compatible with react 18. Currently nextui doesn't support 19 yet. There is another PR working on it and will be tracked there.

If you wish to use nextjs 15 with react 18, you need to override the react version to 18 at this moment. 

```json
"pnpm": {
  "overrides": {
    "react-dom": "18.3.1",
    "react": "18.3.1"
  }
}
```

**Comment by yupitomets** [comment]
`18.3.1` works for me.

**Comment by callmeahab** [comment]
> Nextjs 15 is using react 19 while it's compatible with react 18. Currently nextui doesn't support 19 yet. There is another PR working on it and will be tracked there.
> 
> If you wish to use nextjs 15 with react 18, you need to override the react version to 18 at this moment.
> 
> ```json
> "pnpm": {
>   "overrides": {
>     "react-dom": "18.3.1",
>     "react": "18.3.1"
>   }
> }
> ```
> 
> UPD: if you wish to use nextjs 15 with react 19 rc. you may use our beta version.

Is there a specific beta version that works with react 19, I've tried nextui `2.5.0-beta.19` and it's not working with react 19?

**Comment by kimutai-alex** [comment]
I did that and glad it worked, tnx

**Comment by wingkwong** [comment]
@callmeahab can you share a sandbox for us to investigate? 
> Is there a specific beta version that works with react 19, I've tried nextui `2.5.0-beta.19` and it's not working with react 19?

**Comment by callmeahab** [comment]
@wingkwong Actually I used bun to install packages and it seems to have fixed those issues.

**Comment by AmazingTurtle** [comment]
> UPD: if you wish to use nextjs 15 with react 19 rc. you may use our beta version.
@wingkwong 

```
Build Error
Next.js (15.0.4)
Failed to compile

../../node_modules/@nextui-org/react/dist/index.mjs
Error:   x The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.
    ,-[C:\my-project\node_modules\@nextui-org\react\dist\index.mjs:52:1]
 49 | export * from "@nextui-org/input-otp";
 50 | import { VisuallyHidden } from "@react-aria/visually-hidden";
 51 | import { ResizablePanel } from "@nextui-org/framer-utils";
 52 | "use client";
    : ^^^^^^^^^^^^^
 53 | export {
 54 |   ResizablePanel,
 55 |   VisuallyHidden
    `----
```

Looks like a bundling issue with beta. I was using 2.5.0-beta.26. It may be React 19 compatible (not confirmed) but definitely not nextjs 15 compatible.

**Comment by wingkwong** [comment]
@AmazingTurtle you may use our latest version `2.6.5`. if it doesn't work, please ping me at discord (same id).

**Comment by AmazingTurtle** [comment]
I am using `2.6.5` and I was able to provide this minimum reproduction:

This works
```tsx
'use client';

import { Tooltip } from '@nextui-org/react';

export function TestBug() {
  return (
    <Tooltip>
      <button />
    </Tooltip>
  );
}
```

This does not work
```tsx
'use client';

import { useRef } from 'react';
import { Tooltip } from '@nextui-org/react';

export function TestBug() {
  const copyButtonRef = useRef<HTMLButtonElement>(null);

  return (
    <Tooltip>
      <button ref={copyButtonRef} />
    </Tooltip>
  );
}
```
