### ISSUE TITLE
[BUG] - calendarProps - classNames doesn't work

### ISSUE THREAD

**Issue by hoapng** [nextui-org/nextui#3941]
### NextUI Version

2.4.8

### Describe the bug

```
<DatePicker
        ...
        calendarProps={{
          classNames: {
            gridBody: "bg-white",
          },
        }}
/>
```

```
<DateRangePicker
        ...
        calendarProps={{
          classNames: {
            gridBody: "bg-white",
          },
        }}
/>
```

### Steps to Reproduce the Bug or Issue

I have copied calendarProps-classNames from DateRangePicker to DatePicker, why it works only with DateRangePicker. When I inspected to check, I realized calendarProps in DatePicker doesn't work with any classNames. How can I fix this. Please tell me, thanks.

### Expected behavior

I expected how to fix this quickly. Please help me, thanks

### Operating System Version

Win 11

### Browser

Chrome

**Comment by hoapng** [comment]
```
table tbody[data-slot="grid-body"] {
  background-color: #ffffff;
}
```
i fixed by import 'style.css'

**Comment by wingkwong** [comment]
fixed in https://github.com/nextui-org/nextui/pull/3773. please wait for next release or use canary branch if necessary.
