### ISSUE TITLE
[BUG] - Popover opens and closes on 1st click, resumes normal behaviour from 2nd click (Macbook air touchpad)

### ISSUE THREAD

**Issue by chinmayAnnadate** [nextui-org/nextui#3942]
### NextUI Version

2.4.8

### Describe the bug

When a popover is first rendered, doesn't matter if it is controlled or uncontrolled, the first click on it results on a quick open and close. You can see it on console if you log the open state of a controlled popover. It resumes normal behaviour on the second click. Happens on macbook air touchpad, works fine with a mouse

### Steps to Reproduce the Bug or Issue

1. Create a simple simple popover using v.2.4.8
2. Click on it, it wont open
3. Click on it a second time, resumes normal behavior. Really bad for UX

### Expected behavior

It should stay open on first click

### Operating System Version

macOS sonoma v14.6.1

### Browser

Chrome

**Comment by Kris0011** [comment]
Have you tried in different browsers and is it happening in mac only ?

**Comment by shashwat558** [comment]
doesn't happen with me
