### ISSUE TITLE
[BUG] - Accordion chevron arrow not rotating 

### ISSUE THREAD

**Issue by Ejdyz** [nextui-org/nextui#3947]
### NextUI Version

@nextui-org/accordion@2.0.40

### Describe the bug

I copied the accordion example code from [here](https://nextui.org/docs/components/accordion#usage) and in the example the chevron arrows on the right side are working (rotating), but when I add it to my next.js project the arrows dont rotate. 

The page and component where i tried it were client side marked with ` "use client" `on the top of the file

I also tried importing it from `@nextui-org/react` version 2.4.8 and it didnt work either

### Steps to Reproduce the Bug or Issue

1. Copy the code from [nextui documentation](https://nextui.org/docs/components/accordion#usage)
2. Start the next app
3. Open the Accordion

### Expected behavior

I except the chevron arrow to rotate by 90° degrees when i open the accordion.

### Screenshots or Videos

![opened accordion](https://github.com/user-attachments/assets/0247f32e-c5a5-4438-a935-70c13e3eadbd)

![closed accordion](https://github.com/user-attachments/assets/5cd2685f-8e70-4726-9d16-5b2801ac204d)

### Operating System Version

Ubuntu 24.04.1 LTS

### Browser

Chrome

**Comment by wingkwong** [comment]
couldn't reproduce. please provide a sandbox.

**Comment by karthik-nair-20** [comment]
could not reproduce

**Comment by Ejdyz** [comment]
The problem was in tailwind config. 
My colleage changed the dynamic import that is in nextui documentation,
` "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}"`
and set it to staticly import installed packages without me knowing, so when i installed new one it didnt work beacose it wasnt in the tailwind config. 

sorry for the false alarm 😅

Thanks for getting involved.
