### ISSUE TITLE
[BUG] - Textarea use in page throws document not defined error on server using next 15

### ISSUE THREAD

**Issue by mephmanx** [nextui-org/nextui#3952]
### NextUI Version

2.4.8

### Describe the bug

Using the texture component in a nextjs 15 app throws a document not defined error.  It looks like texture is calling document. something and nextjs ssr has a problem with it

### Steps to Reproduce the Bug or Issue

create simple nextjs 15 app, add textarea to a page, start nextjs server and browse to page

### Expected behavior

textarea component to render properly and not throw 500 error

### Screenshots or Videos

https://github.com/user-attachments/assets/2913329a-40e5-4013-8467-b30302cdacdd

### Operating System Version

macOS

### Browser

Safari

**Comment by wingkwong** [comment]
are you using react 19? if not, please provide a sandbox.

**Comment by mephmanx** [comment]
hmm....no, using react 18....should 19 fix it?

**Comment by wingkwong** [comment]
Nextjs 15 supports both react 19 and compatible with 18 also. currently our version doesn't support react 19 yet. if you are using 18, please provide a sandbox for us to investigate.

**Comment by wingkwong** [comment]
Nextjs 15 is using react 19 while it's compatible with react 18. Currently nextui doesn't support 19 yet. If you are using react 18, then you can override the react version to 18 at this moment. 

```json
"pnpm": {
  "overrides": {
    "react-dom": "18.3.1",
    "react": "18.3.1"
  }
}
```
