### ISSUE TITLE
[BUG] - Many warnings while building

### ISSUE THREAD

**Issue by aiphton** [nextui-org/nextui#3954]
### NextUI Version

@nextui-org/navbar@2.0.37

### Describe the bug

When I try to build my application for production I get a bunch of errors like these:

▲ [WARNING] Unexpected "(" [css-syntax-error]

    <stdin>:1:45881:
      1 │ ...iable})/${opacityValue})`; } if (opacityVariable) { return `hsl(...
        ╵                                    ^

▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:1:45907:
      1 │ ... } if (opacityVariable) { return `hsl(var(${nextuiColorVariable}...
        │                                    ^
        ╵                                    :

▲ [WARNING] Expected ":" [css-syntax-error]

    <stdin>:1:46006:
      1 │ ...${opacityVariable})))`; } return `hsl(var(${nextuiColorVariable}...
        │                                    ^

### Steps to Reproduce the Bug or Issue

1. Install the navbar package
2. Run ``` npm run build ```

### Expected behavior

Building without error messages

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/225f5128-605e-4e80-8453-925f02a281a0)

### Operating System Version

Ubuntu (WSL)

### Browser

Chrome

**Comment by wingkwong** [comment]
please provide a sandbox.

**Comment by aiphton** [comment]
After further investigation I discovered this issue is not from nextui but from aceternity. I will close this issue.
