### ISSUE TITLE
Progress Size not working

### ISSUE THREAD

**Issue by shanewmurphy** [nextui-org/nextui#3970]
### NextUI Version

2.4.8

### Describe the bug

Using import `import {Progress} from "@nextui-org/react";` in Next Js project 
Setting the progress size size="sm" or "md" will not render the progress bar in browser. Setting the size to "lg" will work but not the for the other two sizes "sm" and "md"

### Steps to Reproduce the Bug or Issue

`<Progress size="sm" aria-label="Loading..." value={30} />` Doesn't render progress bar in browser 
`<Progress size="md" aria-label="Loading..." value={40} />`Doesn't render progress bar in browser 
` <Progress size="lg" aria-label="Loading..." value={50} />` Will render progress bar in browser 

### Expected behavior

When using  size="sm" and size"md" will not render progress bar in browser. 

### Screenshots or Videos

<img width="668" alt="Screenshot 2024-11-01 at 08 50 18" src="https://github.com/user-attachments/assets/7535f2d9-2a54-469c-b915-524c8d3f36b9">

### Operating System Version

MacOS

### Browser

Chrome

**Comment by ShrinidhiUpadhyaya** [comment]
Can you please provide a sandbox.

**Comment by shanewmurphy** [comment]
I don't have the time to create a sandbox!! if your employed by Next UI when test yourself by create Next JS with Tailwind import the Progress Bar and see yourself.

**Comment by wingkwong** [comment]
which nextjs & react version are you using?

**Comment by shanewmurphy** [comment]
> which nextjs & react version are you using?
Next JS Ver - "14.2.14"
React Ver - "18"

**Comment by IsDyh01** [comment]
https://codesandbox.io/p/devbox/x5vslz?file=%2Fapp%2Fpage.tsx%3A8%2C35 
![image](https://github.com/user-attachments/assets/a51b8ab5-f72e-4038-89e5-0db1b7c6b53d)

**Comment by wingkwong** [comment]
couldn't reproduce as well.

**Comment by shanewmurphy** [comment]
![Uploading NextUI_progress.jpg…]()

**Comment by wingkwong** [comment]
@shanewmurphy please share a sandbox instead so that others can investigate the issue.

**Comment by wingkwong** [comment]
Closing - inactivity
