### ISSUE TITLE
[BUG] - support next 15 and react 19

### ISSUE THREAD

**Issue by ussfranck** [nextui-org/nextui#3979]
### NextUI Version

2.4.8

### Describe the bug

![Screenshot 2024-11-03 200603](https://github.com/user-attachments/assets/b22715d0-3b4b-4a7c-a848-09d441e91796)
### **NextUI rendering problem: only compose components, such as dropdown, tooltip, select etc...** 
any **“compose”** component stops working, doesn't render, blocking in some cases the global interface.
This problem occurs after a project migration from **NextJS v14 to v15** and therefore from **React 18 to 19.**
However, this means that NextUI requires a recent version of **React 18.**

### Steps to Reproduce the Bug or Issue

1- If the version of your NextJS project <= 14 and your version of react !== 19 and the version of NextUI is <= 2.4.8; Then migrate from NextJS 14 to 15 and React 18 to 19. 

 After that, you'll probably notice warnings about the incompatibility of some of your packages as a result of this change, especially against React 19.

2- Run the app anyway and you'll get the same effect as the problem described here.

### Expected behavior

I expected that, following the upgrade of NextJS to version 15 and React to version 19, the application would run without package compatibility errors or **major warnings related to NextU**I or other dependencies. My goal is to launch the application **without** any compatibility issues between the different versions of React, NextJS and NextUI.

### Screenshots or Videos

https://github.com/user-attachments/assets/c191a759-29a7-47d1-8007-fc44ca5edd85

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
in short, currently react 19 is not supported. however you can use nextjs 15 with overriding react 18.

**Comment by ussfranck** [comment]
Thanks, it's already been noticed, the use of react 18 in spite of Next 15 had already been taken while waiting for a version of NextUI that supports React 19.

**Comment by wingkwong** [comment]
handled in #3732. please wait for next version.
