### ISSUE TITLE
[BUG] - Narbar with dropdown chevronDown not working in Astro

### ISSUE THREAD

**Issue by ozgurbaturalp** [nextui-org/nextui#3980]
### NextUI Version

2.4.8

### Describe the bug

ChevronDown is not working when I click on icon because of aria-hidden.

### Steps to Reproduce the Bug or Issue

1-copy the code on astro build project.
2-Navbar with dropdown is monitoring on screen
3-ChevronDown is not working

### Expected behavior

working on localhost

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
please share a minimal reproducible environment.

**Comment by wingkwong** [comment]
closing - inactivity
