### ISSUE TITLE
[BUG] - Ghost button with danger color - weird behaviour

### ISSUE THREAD

**Issue by Micueb** [nextui-org/nextui#3985]
### NextUI Version

@nextui-org/button": "^2.0.38

### Describe the bug

`ghost` button in combination with `danger` color does not show the correct font color

### Steps to Reproduce the Bug or Issue

1. Spun up new React 18 project, installed all necessary requirements for NextUI
2. Added `ghost` button with color `danger`
3. Added `ghost` button with color `primary` for comparison
4. Danger button text not visible, whereas it's visible for the primary one
5. Different props compared to primary button, danger button missing `data-[hover=true]:` before `!text-danger-foreground`
6. Adding the missing prop makes default font visible, but on hover it's missing then

### Expected behavior

`Danger` color button should behave the same as the `primary` one, showing the correct font color on default and hover state.

### Screenshots or Videos

https://github.com/user-attachments/assets/c82151c3-93e6-4d2c-82ec-456e81bb5886

### Operating System Version

macOS

### Browser

Chrome

**Comment by AnYiEE** [comment]
https://github.com/nextui-org/nextui/pull/3764

**Comment by wingkwong** [comment]
It's been fixed in above-mentioned PR. Please wait for the next release or use canary branch as a workaround.
