### ISSUE TITLE
[BUG] - Input bug

### ISSUE THREAD

**Issue by CodeVisionEvgen** [nextui-org/nextui#3992]
### NextUI Version

@nextui-org/input@2.2.5

### Describe the bug

Property maxLength don't work for <Input/> component

### Steps to Reproduce the Bug or Issue

1. Use maxLength propery in Input component 

### Expected behavior

none

### Operating System Version

Ubuntu

### Browser

Chrome

**Comment by ritikpal1122** [comment]
Assign To me

**Comment by CodeVisionEvgen** [comment]
MaxLength not work only for input type number
