### ISSUE TITLE
Button  - Danger color ghost variant issue 

### ISSUE THREAD

**Issue by VivekSambath** [nextui-org/nextui#4001]
### NextUI Version

2.4.8

### Describe the bug

'use client';

import {
  extendVariants,
  Button as NextButton,
  colorVariants
} from '@nextui-org/react';

const Button = extendVariants(NextButton, {
  variants: {
    size: {
      sm: 'rounded-full font-medium',
      md: 'rounded-full font-medium',
      lg: 'rounded-full font-medium'
    },
    isDisabled: {
      true: 'opacity-100 bg-gray-200 border-none text-gray-400'
    }
  },
});

export default Button;

Button classes : 

"z-0 group relative inline-flex items-center justify-center box-border appearance-none select-none whitespace-nowrap subpixel-antialiased overflow-hidden tap-highlight-transparent data-[pressed=true]:scale-[0.97] outline-none data-[focus-visible=true]:z-10 data-[focus-visible=true]:outline-2 data-[focus-visible=true]:outline-focus data-[focus-visible=true]:outline-offset-2 border-medium bg-transparent px-6 min-w-24 h-12 text-medium gap-3 [&>svg]:max-w-[theme(spacing.8)] transition-transform-colors-opacity motion-reduce:transition-none border-danger text-danger data-[hover=true]:!bg-danger !text-danger-foreground rounded-full font-medium"

issue class : !text-danger-foreground 

no effect of text-danger, this class only applied "!text-danger-foreground"

I'm using this  : 
variant: 'ghost',
color: 'danger',

### Steps to Reproduce the Bug or Issue

variant: 'ghost',
color: 'danger',

### Expected behavior

![Screenshot 2024-11-06 120344](https://github.com/user-attachments/assets/c57d3be7-84d1-447a-8956-eefe78a65627)

### Operating System Version

Windows

### Browser

Chrome

**Comment by AnYiEE** [comment]
- Merged PR
https://github.com/nextui-org/nextui/pull/3764

- Same issues
https://github.com/nextui-org/nextui/issues/3792
https://github.com/nextui-org/nextui/issues/3799
https://github.com/nextui-org/nextui/issues/3985

**Comment by wingkwong** [comment]
As mentioned above, please wait for the next release or use the canary version if necessary.
