### ISSUE TITLE
[BUG] - A div with a button inside can't trigger a click event?

### ISSUE THREAD

**Issue by wood3n** [nextui-org/nextui#4059]
### NextUI Version

latest

### Describe the bug

A div with a button inside can't trigger a click event

### Your Example Website or App

[codesandbox.io/p/devbox/brave-butterfly-l5wfp3](https://codesandbox.io/p/devbox/brave-butterfly-l5wfp3)

### Steps to Reproduce the Bug or Issue

Open codesandbox link and click the `Button`, then can't see log string on click `div`.

### Expected behavior

A div with a button inside should trigger a click event.

### Screenshots or Videos

![20241115-143404](https://github.com/user-attachments/assets/8d745602-0d6e-482c-a167-14405b8d6569)

### Operating System Version

linux,macos,windows

### Browser

Chrome

**Comment by wingkwong** [comment]
your sandbox is not accessible.

<img width="650" alt="image" src="https://github.com/user-attachments/assets/03a0398f-2463-4064-9be4-1c05e0ced41f">

**Comment by wood3n** [comment]
@wingkwong please try again: https://codesandbox.io/p/devbox/brave-butterfly-l5wfp3

**Comment by AnYiEE** [comment]
https://react-spectrum.adobe.com/react-aria/usePress.html

> By default, press events stop propagation to parent elements. In cases where a handler decides not to handle a specific event, it can call continuePropagation() to allow a parent to handle it.

**Comment by wood3n** [comment]
@AnYiEE I have tried to pass onPress with `continuePropagation` to `Button`, but it's not working.

**Comment by wingkwong** [comment]
You need to do it in this way.

```tsx
<div
  onPointerDown={() => console.log("pointer down propagated")}
  onKeyDown={() => console.log("keydown propagated")}>
  <Button
    color="primary"
    onPressStart={(e) => {
      e.continuePropagation();
      console.log("button click");
    }}
  >
    Button
  </Button>
  <button>native</button>
</div>
```

**Comment by wood3n** [comment]
@wingkwong so `onClick` is invalid on parents?

**Comment by wingkwong** [comment]
@wood3n you may refer to this blog post: https://react-spectrum.adobe.com/blog/building-a-button-part-1.html

**Comment by wood3n** [comment]
@wingkwong thanks. So `Pointer events` is better.
