### ISSUE TITLE
[BUG] - Datepicker raises Invalid prop `ref` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.

### ISSUE THREAD

**Issue by rhufsky** [nextui-org/nextui#4068]
### NextUI Version

2.4.8 and 2.5-beta.11, Next15, React 19RC

### Describe the bug

When hitting the calendar icon on datepicker, the datepicker popover opens and raises two errors:

`Invalid prop `ref` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.`

### Your Example Website or App

https://github.com/rhufsky/nextui-demo.git

### Steps to Reproduce the Bug or Issue

Click on datepicker icon.

### Expected behavior

Datepicker should open without errors.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by mikeyamato** [comment]
Also happening with React `18.3.1`.

**Comment by slothgeek** [comment]
same bug to me. Im using individual instalation of calendar

**Comment by JadonLee8** [comment]
Also happened to me with 18.3.1 and individual installation

**Comment by Scoteezy** [comment]
Has anyone fixed this?

**Comment by irvanhanif** [comment]
from https://github.com/tailwindlabs/headlessui/issues/3351#issuecomment-2246655751 , say it only occurs in development mode. idk why, it happen in dev mode

> Has anyone fixed this?

**Comment by yuriiIykyknow** [comment]
The same issue 
"next": "^15.0.3",
 "@nextui-org/date-picker": "^2.1.8",

**Comment by abbasEbadian** [comment]
This error is because of framer motion animation.
Passing `disableAnimation` to `DatePicker` will resolve the error.

**Comment by Cierra-Runis** [comment]
Issue still exists with:

```json
{
  "@nextui-org/calendar": "2.2.3"
}
```

**Comment by XBEAST1** [comment]
> When I reinstall the beta, this issue still exists. Any idea?

Try Passing disableAnimation to DatePicker resolve's the error for me

**Comment by Archivec** [comment]
Same error when `destroyInactiveTabPanel` prop set to true on `Tabs` component
