### ISSUE TITLE
[BUG] Error: Command failed: npm install @nextui-org/react framer-motion

### ISSUE THREAD

**Issue by LarryTheFatCat** [nextui-org/nextui#4075]
### NextUI Version

2.4.8 (latest)

### Describe the bug

When trying to run the command `nextui add --all`I run into the errortarkanzarrouk@Mac classroom_application % nextui add --all

NextUI CLI v0.3.5

Adding required dependencies: @nextui-org/react, framer-motion

npm install @nextui-org/react framer-motion
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: classroom_application@0.1.0
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   react@"19.0.0-rc-66855b96-20241106" from the root project
npm error   peer react@"19.0.0-rc-66855b96-20241106" from react-dom@19.0.0-rc-66855b96-20241106
npm error   node_modules/react-dom
npm error     react-dom@"19.0.0-rc-66855b96-20241106" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@">=18" from @nextui-org/react@2.4.8
npm error node_modules/@nextui-org/react
npm error   @nextui-org/react@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/tarkanzarrouk/.npm/_logs/2024-11-16T01_36_45_854Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/tarkanzarrouk/.npm/_logs/2024-11-16T01_36_45_854Z-debug-0.log

Unexpected error. Please report it as a bug:
Error: Command failed: npm install @nextui-org/react framer-motion
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at file:///opt/homebrew/lib/node_modules/nextui-cli/dist/index.js:36:259
    at new Promise (<anonymous>)
    at fe (file:///opt/homebrew/lib/node_modules/nextui-cli/dist/index.js:36:137)
    at st (file:///opt/homebrew/lib/node_modules/nextui-cli/dist/index.js:36:470)
    at Command.hn (file:///opt/homebrew/lib/node_modules/nextui-cli/dist/index.js:75:1670)
    at async Command.parseAsync (/opt/homebrew/lib/node_modules/nextui-cli/node_modules/commander/lib/command.js:935:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 8670,
  stdout: null,
  stderr: null
}

### Steps to Reproduce the Bug or Issue

open terminal
run `nextui add --all`

### Expected behavior

Run nextui add --all in your terminal and you'll encounter errors when using nextJS

### Screenshots or Videos

<img width="914" alt="Screenshot 2024-11-15 at 8 39 39 PM" src="https://github.com/user-attachments/assets/82e4d8ac-a6cd-4316-8e65-61adbddcee25">
<img width="858" alt="Screenshot 2024-11-15 at 8 39 46 PM" src="https://github.com/user-attachments/assets/6e1a0a7a-b28a-42a9-8fc2-b8fab37a7d58">

### Operating System Version

macOS 

### Browser

Chrome

**Comment by wingkwong** [comment]
The latest production version of nextui and framer-motion don't support react 19 rc. However, you can use our beta version and their alpha version if you need nextjs 15 & react 19 rc.

For framer-motion, you need to override the version as well. 

```json
"dependencies": {
    "framer-motion": "^12.0.0-alpha.1",
    "react": "19.0.0-rc-66855b96-20241106",
    "react-dom": "19.0.0-rc-66855b96-20241106"
},
"overrides": {
    "framer-motion": {
        "react": "19.0.0-rc-66855b96-20241106",
        "react-dom": "19.0.0-rc-66855b96-20241106"
    }
}
```

**Comment by wingkwong** [comment]
@xavierchow can you help create a new issue?

**Comment by xavierchow** [comment]
sure, created https://github.com/nextui-org/nextui/issues/4139.
