### ISSUE TITLE
[BUG] - toggle.js should be included instead of switch.js when using Switch component

### ISSUE THREAD

**Issue by HenryYangs** [nextui-org/nextui#4085]
### NextUI Version

@nextui-org/theme@2.2.11

### Describe the bug

When I want to import Switch in my project, I add switch.js in tailwind.config.ts:

```javascript
content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@nextui-org/theme/dist/components/(button|input|modal|radio|switch).{js,ts,jsx,tsx}'
  ],
```

Then, I found no UI change when I click Switch component on my page, and all states are correct. I checked node_modules directory, no switch.js there. But toggle.js was found.

I replace `switch` to `toggle`, problem was solved. I'm not sure why this happened, someone may check the compile procedure?

### Steps to Reproduce the Bug or Issue

1. add following content in `tailwind.config.ts`:

```javascript
content: [
    './node_modules/@nextui-org/theme/dist/components/switch.{js,ts,jsx,tsx}'
  ],
```

2. add basic Switch example on official docs
3. no UI change when click Switch on page
4. replace `switch` to `toggle`:

```javascript
content: [
    './node_modules/@nextui-org/theme/dist/components/toggle.{js,ts,jsx,tsx}'
  ],
```

### Expected behavior

I expected add `switch` in tailwind.config.ts, but I have to add `toggle`, without any tips on official docs

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
We cannot use `switch` because it is a reserved word in Javascript.
