### ISSUE TITLE
[BUG] - Components/Link

### ISSUE THREAD

**Issue by NitinNair89** [nextui-org/nextui#409]
### Describe the bug

An error "NextLink is not defined" is displayed when following the documentation for NextUI Link component. Documentation link - https://nextui.org/docs/components/link#next.js-link

### Your Example Website or App

https://codesandbox.io/s/kmd6yi?file=/App.js&from-sandpack=true

### Steps to Reproduce the Bug or Issue

1. Go to - https://nextui.org/docs/components/link#next.js-link
2. The example shows to use <NextLink> component
3. Open the sandbox for the example code - https://codesandbox.io/s/kmd6yi?file=/App.js&from-sandpack=true

### Expected behavior

As a user I expected <NextLink> component to work, but I am seeing an error "NextLink is not defined"

### Screenshots or Videos

![Error](https://user-images.githubusercontent.com/16149618/163541242-eee5f8b1-319e-4926-b0cf-9ba5b1405d9a.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @NitinNair89 thanks for reporting it

**Comment by lorenzejay** [comment]
You didn't import `NextLink` hence why its not defined.

**Comment by jrgarciadev** [comment]
Hey @NitinNair89 the fix is on the way https://github.com/nextui-org/nextui/commit/69eb84f94a4d3bb36df9413bbdf029e6432c19ad
