### ISSUE TITLE
[BUG] - isRequired prop isn't working in Input and Autocomplete

### ISSUE THREAD

**Issue by c0d3rm0n** [nextui-org/nextui#4116]
### NextUI Version

2.4.8

### Describe the bug

I'm using NextUI for quite some time and my forms were working just fine.
Only today I noticed that my forms weren't validated by my browser (but that was OK sometime ago). 
My required inputs didn't had any value but somehow it was passing the default validation.

I added an HTML input, set it as required, just to test and the form wasn't submitted, as expected.
So something was not OK in my form or its content...

I created a new project to test my inputs and it happened the same there. I didn't see anything wrong in my inputs, so I created another project to test NextUI Input component.

In this last project I used [NextUI example](https://nextui.org/docs/components/input#required) as base for my test and used the prop isRequired. I wrapped the Input in a form and tested it. Same... The Input is visually defined as required but in fact, the form validation was not stopping there...

To make it work, I used two props: isRequired and required.
If I set both to true, it works...

I also tested Autocomplete and there I could not make it work.
Even if I set both props to true, the form is valid even if the input is empty...

I didn't test the other input components, but maybe it is better to confirm if this functionality is working correctly.

### Your Example Website or App

https://codesandbox.io/p/devbox/loving-cdn-mxjzlp

### Steps to Reproduce the Bug or Issue

Use only isRequired={true} and it will not work correctly

### Expected behavior

Use isRequired={true} and required={true}, and it will work as it should
However, sometime ago, it was working only with isRequired

### Operating System Version

Linux

### Browser

Firefox

**Comment by wingkwong** [comment]
Currently by default `validationBehavior` is `aria` which will only mark the field as required and invalid for assistive technologies, and will not prevent form submission. In your case, you need to use `native` one. It was a breaking change we introduced in 2.4.0 (ref: https://nextui.org/blog/v2.4.0#validationbehavior).

Therefore, you can do the following change.

```diff
- <NextUIProvider>
+ <NextUIProvider validationBehavior="native">
```

![image](https://github.com/user-attachments/assets/8f2dac66-8a60-4b4d-99a6-9e0616c8b078)

**Comment by c0d3rm0n** [comment]
Thank you very much [wingkwong](https://github.com/wingkwong)!
