### ISSUE TITLE
[BUG] - DropdownItem ignore variants

### ISSUE THREAD

**Issue by marvin-42** [nextui-org/nextui#4119]
### NextUI Version

~~2.4.2~~ 2.4.8

### Describe the bug

I created custom component <DropdownItem /> which extends variants ( extendVariants used ). When I use this component inside <DropdownSection /> everything is rendered correctly but when this component is a direct child of <DropdownMenu />   then <DropdownItem /> get variants but styles are ignored.

### Steps to Reproduce the Bug or Issue

1. Create custom Dropdown items for example
```
const DropdownItem = extendVariants(NextDropdownItem, {
  variants: {
    variant: {
      solid: {
        base: ['rounded-none'],
      },
    },
    size: {
      md: {
        base: 'py-4',
      }
    },
  },
  defaultVariants: {
    variant: 'solid',
    size: 'md',
  },
});
```
2. Put this component inside <DropdownMenu />

### Expected behavior

styles from custom component should be applied 

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
have you tried on latest version?

**Comment by marvin-42** [comment]
> have you tried on latest version?

yes i use 2.4.8
