### ISSUE TITLE
[BUG] - Dropdown and Select not Displaying Open State!

### ISSUE THREAD

**Issue by KL2808** [nextui-org/nextui#4134]
### NextUI Version

tried with "@nextui-org/react": "^2.4.8", as well as the individual isntallation

### Describe the bug

I created a new app via `nextui init my-nextui-app` and added `next-intl`. 

When clicking on the dropdown nothing happens only the button goes into pressed state. I can see in the devtools that the dropdown is opening and for the select i can even see it for a split second. Its also clickable just not displaying. I tried it in Safari and in Chrome.

Thank you for helping me <3

### Steps to Reproduce the Bug or Issue

1. created a new app via `nextui init my-nextui-app`
2. added `next-intl` (but should no interfere)
3. try creating a dropdown:
```
'use client';

import { Button } from '@nextui-org/button';
import {
  Dropdown,
  DropdownItem,
  DropdownMenu,
  DropdownTrigger,
} from '@nextui-org/react';

export default function DocsPage() {
  'use client';

  return (
    <Dropdown>
      <DropdownTrigger>
        <Button variant="bordered">Open Menu</Button>
      </DropdownTrigger>
      <DropdownMenu aria-label="Static Actions">
        <DropdownItem key="new">New file</DropdownItem>
        <DropdownItem key="copy">Copy link</DropdownItem>
        <DropdownItem key="edit">Edit file</DropdownItem>
        <DropdownItem key="delete" className="text-danger" color="danger">
          Delete file
        </DropdownItem>
      </DropdownMenu>
    </Dropdown>
  );
}
```

### Expected behavior

Dropdown should open

### Operating System Version

macOS

### Browser

Safari

**Comment by KL2808** [comment]
okay, so in production its working somehow. I just saw that the navigation is also not working when simulating a mobile device. but when deployed on vercel its working... why?

**Comment by wingkwong** [comment]
couldn't reproduce. please share a reproducible sandbox environment.

<img width="349" alt="image" src="https://github.com/user-attachments/assets/283cea32-a479-4cae-bc3d-1ba7abceb2c8">

**Comment by KL2808** [comment]
Okay, so i traced it back to the upgrade to react 15 which was one of the first thing i've done.  I did not knew this library was incompatible with react 15... so its on me sorry <3

https://github.com/nextui-org/next-app-template/issues/24#issuecomment-2171449924

**Comment by wingkwong** [comment]
@KL2808 no problem. just fyi, you may try our beta branch which support next 15. see https://github.com/nextui-org/next-app-template/pull/32 for more.
