### ISSUE TITLE
[BUG] - Datepicker locale not working

### ISSUE THREAD

**Issue by meisamtj81** [nextui-org/nextui#4137]
### NextUI Version

2.4.8

### Describe the bug

Local not working!
`local="fa-IR-u-ca-persian"`
I saw many have this issue and there was no solution for this, this is when in docs seems it works correctly. Even copying and pasting the code as exactly it is also not working in local fresh installed app.

### Steps to Reproduce the Bug or Issue

1. install app
2. import datepicker
3. add local provider

### Expected behavior

it should change the calendar and date but it persistly show gerogory calendar

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
please share your package.json. It could be caused by higher version of `@internationalized/date`

**Comment by meisamtj81** [comment]
> please share your package.json. It could be caused by higher version of `@internationalized/date`

Good point, those are
`
"@internationalized/date": "^3.6.0",
"@nextui-org/react": "^2.4.8",
"@react-aria/i18n": "^3.12.4",
`

**Comment by wingkwong** [comment]
please use the following and lemme know the result.

```
"@internationalized/date": "3.5.4"
"@react-aria/i18n": "3.11.1"
```

**Comment by meisamtj81** [comment]
> please use the following and lemme know the result.
> 
> ```
> "@internationalized/date": "3.5.4"
> "@react-aria/i18n": "3.11.1"
> ```

Thank you, yes it solved the issue. 
By the way I have installed Vite-React version and it vite automatically choose the right version on install. 

It used bellow versions
` @internationalized/date -> 3.6.0 ` and `@react-aria/i18n -> 3.11.1`
