### ISSUE TITLE
[BUG] - `<Switch />` and/or `<Checkbox />` is not compatible within `<Table />` Row

### ISSUE THREAD

**Issue by mayeenulislam** [nextui-org/nextui#4145]
### NextUI Version

2.4.6

### Describe the bug

We implemented `<Switch />` inside `<Table />` row to update status from `0` to `1` to `0`. But we eventually found that, when the status is `0` the row is behaving ill for all the checkboxes within the row.

I can assure that, clicking on the checkboxes is working fine. The API is only getting called by the Switches when they are clicked on them.

And the anomaly of visually checking the `<Switch />`s are only on the UI, and no API is getting hit.

(I attached a video for understanding the issue)

The bug is OS and Browser-agnostic.

### Steps to Reproduce the Bug or Issue

1. Add a NextUI table
2. Within a cell, add NextUI Switch or any other Checkbox
3. Mark the checkbox unchecked (status = `0`)
4. Click on the row or the row selection checkbox

### Expected behavior

The row selection and switch or any other checkboxes within a row should work independently

### Screenshots or Videos

https://github.com/user-attachments/assets/1fc5b888-48cd-46d2-9caa-e76708b68171

### Operating System Version

Windows

### Browser

Edge

**Comment by wingkwong** [comment]
fixed in https://github.com/nextui-org/nextui/pull/3909. please wait for next release or you can use beta branch if necessary.
