### ISSUE TITLE
[BUG] - Image 

### ISSUE THREAD

**Issue by sathishdaniel9268** [nextui-org/nextui#4146]
### NextUI Version

ex.2.4.8

### Describe the bug

Image not visible in brow
![Screenshot 2024-11-25 183056](https://github.com/user-attachments/assets/d72bd006-3dde-420a-80d9-164f24459709)
ser display

### Steps to Reproduce the Bug or Issue

Image not visible in browser display

### Expected behavior

Image not visible in browser display
![Screenshot 2024-11-25 183056](https://github.com/user-attachments/assets/3c281533-fa64-4b0d-9339-f505abb278a0)

### Operating System Version

window

### Browser

Chrome

**Comment by wingkwong** [comment]
please provide a minimal reproducible environment.
