### ISSUE TITLE
i am using dark and light mode from NextThemesProvider and want to make a page explicitly dark mode always

### ISSUE THREAD

**Issue by RanitManik** [nextui-org/nextui#4150]
i am using dark and light mode from NextThemesProvider and want to make a page explicitly dark mode always

_Originally posted by @RanitManik in https://github.com/nextui-org/nextui/discussions/4144_

**Comment by wingkwong** [comment]
By default the default theme is light. You can change to dark in `defaultTheme` in your tailwind config file.

**Comment by RanitManik** [comment]
> By default the default theme is light. You can change to dark in `defaultTheme` in your tailwind config file.

i wanted to know if there is a way that i can make a page always dark or always light irrelevent of the the defaultTheme and currentTheme
