### ISSUE TITLE
[BUG] - DatePicker incompatible with @internationalized/date v3.6.0

### ISSUE THREAD

**Issue by kennyqiyenkan** [nextui-org/nextui#4154]
### NextUI Version

2.4.8

### Describe the bug

In v3.6.0 of @internationalized/date, `parseDate` return CalendarDate which is incompatible with the DatePicker's `value` and `onChange` props.

### Steps to Reproduce the Bug or Issue

1. Use v2.4.8 of NextUI
2. Use v3.6.0 of @internationalized/date
3. Use Typescript
4. Using the instructions in the [docs](https://nextui.org/docs/components/date-picker#controlled), create a controlled `DatePicker`
5. You should be receiving a TS error

### Expected behavior

Using `parseDate` from the latest `@internationalized/date` should be compatible with `DatePicker`.

### Screenshots or Videos

<img width="754" alt="Screenshot 2024-11-27 at 12 53 45 PM" src="https://github.com/user-attachments/assets/80aa04ee-96c7-4fd4-b130-90bb35eabb77">

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
For v2.4.8, please use `3.5.5` for `@internationalized/date`. Any higher version may cause unexpected issues. We've specified the exact version in docs (in next release) so users will install the same version as the one defined in our package

Will leave this issue open for `@internationalized/date` version upgrade and corresponding changes.

**Comment by wingkwong** [comment]
Closing - `@internationalized/date` has been upgraded to `3.6.0` in latest version.

**Comment by Hunkoys** [comment]
With HeroUI 2.6.14(using `@heroui/date-picker` 2.3.10), I just had to force it to use the `@internationalized/date` 3.6.0 specifically. I just wished this was on the example docs.

```diff
{
  "name": "nextjs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "prisma generate && next build",
    "start": "next start",
    "lint": "next lint",
    "migrate": "dotenv -e .env.development.local -- npx prisma migrate dev"
  },
  "dependencies": {
    "@clerk/nextjs": "^6.11.2",
    "@clerk/themes": "^2.2.17",
    "@heroui/react": "^2.6.14",
-  "@internationalized/date": "^3.7.0",
+  "@internationalized/date": "3.6.0",
    "@prisma/client": "^6.3.1",
    "@react-aria/i18n": "^3.12.5",
    "clsx": "^2.1.1",
    "framer-motion": "^12.3.1",
    "next": "15.1.6",
    "prisma": "^6.3.1",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@eslint/eslintrc": "^3",
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "dotenv-cli": "^8.0.0",
    "eslint": "^9",
    "eslint-config-next": "15.1.6",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}
```

**Comment by wingkwong** [comment]
@Hunkoys The doc has mentioned the exact version. We plan to port it as an internal package in 2.8.0 so that users don't need to worry about the version.

**Comment by e2corporation** [comment]
This ticket should be reopened, the bug is still present even in `v3.6.0` of `@internationalized/date`

**Comment by wingkwong** [comment]
@e2corporation due to upstream upgrade, you need to upgrade to `@heroui/react@2.7.2` with `@internationalized/date@3.7.0`.

**Comment by e2corporation** [comment]
Thank you @wingkwong will give those updated versions a try.

**Comment by mrcbjcmanagement** [comment]
Hi @wingkwong , the error is gone for the `value` attribute using the right versions but it is throwing the same error for the minValue and maxValue attributes.

![Image](https://github.com/user-attachments/assets/2f73e858-8c29-49bc-8476-d153567bb76d)
![Image](https://github.com/user-attachments/assets/ec874e8a-f910-40c0-bfc9-85fbaaae57ce)

**Comment by wingkwong** [comment]
@mrcbjcmanagement can you share a sandbox? I wanna check the lock file to see if you are using the latest version of RA.

**Comment by mrcbjcmanagement** [comment]
Hi @wingkwong , https://codesandbox.io/p/sandbox/heroui-tabs-issue-gp7q3n. Sorry for the late update, I was testing it yesterday  (both in the sandbox and actual application) and it looks like the functionality is working. But there is an issue with the detection of the typings. 

These are actual screenshots of my actual application.

![Image](https://github.com/user-attachments/assets/a54eb3d5-8c0b-4dea-b73c-fabe5241a866)
![Image](https://github.com/user-attachments/assets/6a373d3b-14e8-44a4-9ce8-a0ca94eebb41)
