### ISSUE TITLE
[BUG] - Select component hidration Error

### ISSUE THREAD

**Issue by shant99** [nextui-org/nextui#4165]
### NextUI Version

^2.4.8

### Describe the bug

My testing project on Next.js App-routing "next": "15.0.3" and I use "@nextui-org/react": "^2.4.8"

**Layout.tsx**

            export default async function RootLayout({ children }: IRootLayout) {
            
              return (
                <html lang={locale}>
                  <body className={bodyClass}>
                    <NextUIProvider>
                      <main>{children}</main>
                      <footer className="bg-white-900 text-black p-4 text-center">
                        <LanguageSwitcher />
                      </footer>
                    </NextUIProvider>
                  </body>
                </html>
              );
            }

**LanguageSwitcher.tsx**

      "use client";
      import { Select, SelectItem } from "@nextui-org/react";
      import { useState } from "react";
      
      const locales = [
        { key: "en", label: "English" },
        { key: "ru", label: "Русский" },
      ];
      
      export default function LanguageSwitcher() {
        const [value, setValue] = useState<string>("en");
      
        const handleLocaleChange = (selectedValue: React.ChangeEvent<HTMLSelectElement>) => {
          setValue(selectedValue.target.value);
        };
      
        return (
          <Select
            name="language"
            label="Select language"
            labelPlacement="inside"
            onChange={handleLocaleChange}
            value={value}
            className="max-w-36"
          >
            {locales.map((item) => (
              <SelectItem key={item.key} value={item.key}>
                {item.label}
              </SelectItem>
            ))}
          </Select>
        );
      }

And Select component throws Error

![Screenshot 2024-11-29 023929](https://github.com/user-attachments/assets/1cacb8a3-d8a5-453a-b024-afa521e43a65)

          hook.js:608 A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:
          
          - A server/client branch `if (typeof window !== 'undefined')`.
          - Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
          - Date formatting in a user's locale which doesn't match the server.
          - External changing data without sending a snapshot of it along with the HTML.
          - Invalid HTML tag nesting.
          
          It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.
          
          https://react.dev/link/hydration-mismatch
          
            ...
              <body className="__variable...">
                <NextUIProvider>
                  <$18f2051aff69b9bf$export$a54013f0d02a8f82 locale="en-US">
                    <$f57aed4a881a3485$export$bf688221f59024e5>
                      <$f57aed4a881a3485$export$178405afcd8c5eb>
                        <$f57aed4a881a3485$var$OverlayContainerDOM>
                          <div data-overlay-container={true} aria-hidden={null}>
                            <TopNav>
                            <main>
                            <footer className="bg-white-9...">
                              <LanguageSwitcher>
                                <NextUI.Select name="language" label="Select lan..." labelPlacement="inside" ...>
                                  <div data-slot="base" data-filled={undefined} data-has-value={undefined} data-has-label="true" ...>
                                    <HiddenSelect>
                                    <div data-slot="mainWrapper" className="w-full fle...">
                                      <button
                                        ref={{current:null}}
                                        data-slot="trigger"
                                        data-open={undefined}
                                        data-disabled={undefined}
                                        data-focus={undefined}
                                        data-pressed={undefined}
                                        data-focus-visible={undefined}
                                        data-hover={undefined}
                                        className="relative px-3 w-full inline-flex shadow-sm tap-highlight-transparent group-da..."
                                        type="button"
                                        disabled={undefined}
                                        onFocus={function}
                                        onBlur={function}
                                        onKeyDown={function}
                                        onKeyUp={undefined}
                                        tabIndex={undefined}
                                        onClick={function}
                                        onPointerDown={function}
                                        onMouseDown={function}
                                        onPointerUp={function}
                                        onDragStart={function}
                                        id="react-aria-:Rt7H2:"
                                        aria-label={undefined}
                                        aria-labelledby="react-aria-:Rt7H7: react-aria-:Rt7H3:"
                                        aria-describedby="react-aria-:Rt7H5: react-aria-:Rt7H6:"
                                        aria-haspopup="listbox"
                                        aria-expanded={false}
                                        aria-controls={null}
                                        aria-pressed={undefined}
                                        onPointerEnter={function}
                                        onPointerLeave={function}
                                        value="en"
          -                             fdprocessedid="1h001r"
                                      >
                                    ...

It doesnt throw error in case when I put this in Component

           const [isMounted, setIsMounted] = useState(false);
          
            useEffect(() => {
              setIsMounted(true);
            }, []);
          
            if (!isMounted) {
              return null; // Render nothing until the component is mounted on the client
            }

### Steps to Reproduce the Bug or Issue

1. Create Next.js app with App Routing "next": "15.0.3"
2. Install and configure  "@nextui-org/react": "^2.4.8"
3. In /src/app/Layout.tsx change RootLayout on this 
  

            interface IRootLayout {
              children: React.ReactNode;
            }
            
            export default async function RootLayout({ children }: IRootLayout) {
            
              return (
                <html>
                  <body>
                    <NextUIProvider>
                      <main>{children}</main>
                      <footer className="bg-white-900 text-black p-4 text-center">
                        <LanguageSwitcher />
                      </footer>
                    </NextUIProvider>
                  </body>
                </html>
              );
            }

4. Create LanguageSwitcher.tsx in any place. For example in /src/components  and put this code.

           
            "use client";
            import { Select, SelectItem } from "@nextui-org/react";
            import { useState } from "react";
            
            const locales = [
              { key: "en", label: "English" },
              { key: "ru", label: "Русский" },
            ];
            
            export default function LanguageSwitcher() {
              const [value, setValue] = useState<string>("en");
            
              const handleLocaleChange = (
                selectedValue: React.ChangeEvent<HTMLSelectElement>
              ) => {
                setValue(selectedValue.target.value);
              };
            
              return (
                <Select
                  name="language"
                  label="Select language"
                  labelPlacement="inside"
                  onChange={handleLocaleChange}
                  value={value}
                  className="max-w-36"
                >
                  {locales.map((item) => (
                    <SelectItem key={item.key} value={item.key}>
                      {item.label}
                    </SelectItem>
                  ))}
                </Select>
              );
            }

5.  Run app with - npm run dev
6. !! Disable or Remove some extensions in browser that may modify the HTML before React gets a chance to hydrate !!

### Expected behavior

**Console should be without any Error with Select component !**

![Screenshot 2024-11-29 023722](https://github.com/user-attachments/assets/06a50fab-b1eb-4ba1-aed4-351361c5633f)

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
Please share your package.json for reference. A minimal reproducible environment is preferred.

**Comment by shant99** [comment]
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@hookform/resolvers": "^3.9.1",
    "@nextui-org/react": "^2.4.8",
    "clsx": "^2.1.1",
    "i18next": "^24.0.2",
    "i18next-http-backend": "^3.0.1",
    "motion": "^11.11.17",
    "next": "15.0.3",
    "next-i18next": "^15.4.0",
    "next-intl": "^3.25.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-i18next": "^15.1.3",
    "react-icons": "^5.3.0",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "15.0.3",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}

**Comment by wingkwong** [comment]
Couldn't reproduce. Please bump `@nextui-org/react` to `2.6.10` and try again.

**Comment by shant99** [comment]
Thank you! I updated @nextui-org/react from ^2.4.8 to ^2.6.10, and the problem has been solved successfully. I appreciate your help! Wishing you a great day ahead!
