### ISSUE TITLE
[BUG] - use NextUI in obsidian plugin

### ISSUE THREAD

**Issue by Emt-lin** [nextui-org/nextui#4166]
### NextUI Version

2.4.8

### Describe the bug

The actual effect of the input box in Obsidian app differs from the official website style.

**code:**

```tsx
        <Input
          isRequired
          type={type}
          label={title}
          placeholder={placeholder || ""}
          labelPlacement={"outside"}
          variant={'bordered'}
          color={'secondary'}
          className="max-w-xs border-0"
        />
```

### Steps to Reproduce the Bug or Issue

nothing

### Expected behavior

Style consistency

### Screenshots or Videos

**The Actual style**

![CleanShot 2024-11-29 at 17 03 16](https://github.com/user-attachments/assets/6ebb9bf9-0c87-4d63-87f9-5ca2655aa5c7)

### Operating System Version

macos

### Browser

Other (add additional context)

**Comment by wingkwong** [comment]
1. please try the latest version
2. please check if Obsidian overrides some styles
3. please provide a minimal reproducible environment

**Comment by Emt-lin** [comment]
> 1. please try the latest version
> 2. please check if Obsidian overrides some styles
> 3. please provide a minimal reproducible environment

1. use v2.4.8 version
2. I check it, but I couldn't find the reason why this issue occurred.
3. follow these steps
      1. Install the BRAT plugin if you haven't already. Click here to install BRAT in Obsidian.
      2. Open the command palette and run the command "BRAT: Add a beta plugin for testing".
      3. Copy and paste this link into the modal: https://github.com/Emt-lin/obsidian-sample-plugin-test and click "Add Plugin" and wait for the installation.
      4. Go to Settings > Community plugins and refresh the list of plugins. Enable "Sample Plugin".
      5. Last as shown in the figure.
            ![CleanShot 2024-11-29 at 18 58 49](https://github.com/user-attachments/assets/e5be2fbf-1e8d-4ab3-a89f-ad26c6effd9f)

**Comment by wingkwong** [comment]
Unfortunately after checking the code, I don't think we could do much for this issue. As it works fine in simple usage as shown in the documentation, the root cause may cause from other dependencies over which we don't have control. 

However, I notice that `styles.css` seems not used in any files in the repo. You may import it to see if this causes the issue. Thanks.

**Comment by Emt-lin** [comment]
@wingkwong Thanke you. `style.css` will be auto import by plugin.
