### ISSUE TITLE
Circular Progress Bar: Unnecessary space between value and percentage symbol

### ISSUE THREAD

**Issue by GreatSamJ** [nextui-org/nextui#4199]
### NextUI Version

2.4.6

### Describe the bug

Hello Team,

I don't understand why there is a blank space between the value and the %. Is it a wanted behavior of NextUI?

<img width="153" alt="image" src="https://github.com/user-attachments/assets/c70467e2-d8fe-49ac-8e03-dff5c9291760">

### Steps to Reproduce the Bug or Issue

      <CircularProgress
        aria-label="circular progress bar"
        classNames={{
          svg: "w-36 h-36 drop-shadow-md",
          indicator: "stroke-primary_1",
          track: "stroke-primary_1/10",
          value: "text-3xl font-semibold text-primary_1",
        }}
        value={70}
        strokeWidth={4}
        showValueLabel={true}
      />

### Expected behavior

<img width="153" alt="image" src="https://github.com/user-attachments/assets/54b6bee0-9715-4378-a853-eae7c56b9036">

### Operating System Version

macOS

### Browser

Chrome

**Comment by Sanjoy-droid** [comment]
@GreatSamJ I am not able to reproduce this issue, it's working properly for me
you can refer to the docs on circularprogress component here

https://nextui.org/docs/components/circular-progress

and i am using it easily

![Screenshot from 2024-12-02 08-47-32](https://github.com/user-attachments/assets/c2b98c47-2ab1-4263-b0e9-bbb251a3849a)


this is the code from official docs

<Card className="w-[240px] h-[240px] border-none bg-gradient-to-br from-violet-500 to-fuchsia-500">
      <CardBody className="justify-center items-center pb-0">
        <CircularProgress
          classNames={{
            svg: "w-36 h-36 drop-shadow-md",
            indicator: "stroke-white",
            track: "stroke-white/10",
            value: "text-3xl font-semibold text-white",
          }}
          value={70}
          strokeWidth={4}
          showValueLabel={true}
        />
      </CardBody>
      <CardFooter className="justify-center items-center pt-0">
        <Chip
          classNames={{
            base: "border-1 border-white/30",
            content: "text-white/90 text-small font-semibold",
          }}
          variant="bordered"
        >
          2800 Data points
        </Chip>
      </CardFooter>
    </Card>

**Comment by wingkwong** [comment]
Not able to reproduce - please use the latest version.

**Comment by GreatSamJ** [comment]
Thanks for your replies. In fact, I'm using the version 2.4.6 and the I used same code picked up from the official doc and only the color get changed. Maybe the issue come from somewhere else.
