### ISSUE TITLE
[BUG] - week day incorrect when using I18nProvider

### ISSUE THREAD

**Issue by jeanp117** [nextui-org/nextui#4216]
### NextUI Version

2.4.8

### Describe the bug

When using the Envelope DatePicker component wrapped with:

`<I18nProvider locale="es-CO">
<DatePicker label="Test" />
</I18nProvider>`

I noticed a discrepancy in the first day of the week:

For es-CO (Colombia), November 24, 2014 is displayed as Monday (Lunes), but it should be Sunday (Domingo).
![image](https://github.com/user-attachments/assets/a25c1f1e-48c9-417b-a280-711d665f1509)

For es-ES (Spain), the component correctly displays Monday (Lunes) as the first day of the week.
![image](https://github.com/user-attachments/assets/1eaf0358-c2d6-4a5e-b443-747b7d796040)

This suggests that the locale settings for es-CO may not correctly align with the expected Colombian calendar conventions.

Using es-CO (Colombia) shows 24-nov-2014 as monday ( L ) but it should be sunday ( D )

 

 
 

### Your Example Website or App

https://codesandbox.io/p/devbox/datepicker-bug-z9hxjr

### Steps to Reproduce the Bug or Issue

Use i18n provider as follows
`<I18nProvider locale="es-CO">
<DatePicker label="Test" />
</I18nProvider>`

open the date picker and check the day of week

### Expected behavior

The day of the week is globally synchronized, so November 24, 2024, is Sunday everywhere.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
please try with "@react-aria/i18n": "3.11.1". Using a higher version (`3.12.2` in your sandbox) may introduce unexpected issue.

**Comment by wingkwong** [comment]
Closing - please use `3.12.4` for latest version.
