### ISSUE TITLE
[BUG] - Buttons wrapped with Link not working on mobile canary

### ISSUE THREAD

**Issue by christophmeise** [nextui-org/nextui#4223]
### NextUI Version

2.5.0

### Describe the bug

<Button> that are wrapped with a <Link> are not clickable on mobile devices on latest canary 2.5.0

On click, nothing happens.

### Steps to Reproduce the Bug or Issue

Example:

<Link href="/">
<Button color="default" variant="light">
click
</Button>
</Link>

### Expected behavior

Click should work mobile

### Operating System Version

Mobile

### Browser

Chrome

**Comment by christophmeise** [comment]
Probably related to: https://github.com/nextui-org/nextui/issues/4210

@macci001

**Comment by miljkovicjovan** [comment]
Experiencing the same right now

**Comment by christophmeise** [comment]
> Experiencing the same right now (tested on Safari and Brave)

My workaround is to only use <Button as={Link}> for now.

This is definitely a bug though.

**Comment by wingkwong** [comment]
Please upgrade to the latest version.
