### ISSUE TITLE
[BUG] - Next.js error with NextUI.Breadcrumbs: Each child in a list should have a unique 'key' prop

### ISSUE THREAD

**Issue by KUN1007** [nextui-org/nextui#4230]
### NextUI Version

2.4.8

### Describe the bug

Next.js reports an error with NextUI.Breadcrumbs: hook.js:608 Each child in a list should have a unique 'key' prop.
I have written a minimal reproducible example:

### Your Example Website or App

https://github.com/KUN1007/next-nextui-breadcrumb-key-error

### Steps to Reproduce the Bug or Issue

1. Clone [the project](https://github.com/KUN1007/next-nextui-breadcrumb-key-error) and install the dependencies.
2. Run `pnpm dev`, then visit http://localhost:3000/.
3. At this point, you will see the following error in the browser console: 'Each child in a list should have a unique "key" prop.'

### Expected behavior

If it runs as expected, there will be no error.
For the minimal reproduction, I directly copied the code from the NextUI website (https://nextui.org/docs/components/breadcrumbs#customizing-the-ellipsis-item) into the page.tsx file of my code without making any modifications.

### Screenshots or Videos

Chrome Browser
<img width="492" alt="KUN_2024-12-06_02-47-35" src="https://github.com/user-attachments/assets/a7e8d9cc-3706-4e07-be28-73dad8bf7a67">

VS Code
<img width="697" alt="KUN_2024-12-06_02-47-44" src="https://github.com/user-attachments/assets/d2064418-aa9d-4681-b737-1a2dba5035ef">

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
as a workaround, you may add a `key` prop to `<div className="flex items-center">`

**Comment by KUN1007** [comment]
> as a workaround, you may add a `key` prop to `<div className="flex items-center">`

Thank you very much for your reply, it's works fine!
However, I still have a question regarding the `Breadcrumb` component. For the BreadcrumbItem element, if it’s written as 
``` tsx
<BreadcrumbItem href="/example">example</BreadcrumbItem>
```
like on the [NextUI official website](https://nextui.org/docs/components/breadcrumbs#customizing-the-ellipsis-item), in a Next.js environment, clicking the 'example' element to navigate to the `/example` page causes a full page refresh.
However, I have already correctly configured the layout routing as per the official documentation.

``` tsx
'use client'

import { NextUIProvider } from '@nextui-org/react'
import { ThemeProvider } from 'next-themes'
import { useRouter } from 'next/navigation'

export const Providers = ({ children }: { children: React.ReactNode }) => {
  const router = useRouter()

  return (
    <NextUIProvider navigate={router.push}>
      <ThemeProvider attribute="class">{children}</ThemeProvider>
    </NextUIProvider>
  )
}

```
Now, if we create a new element like this:

``` tsx
      <BreadcrumbItem
        href="/test"
        onClick={(event) => event.preventDefault()}
        onPress={() => router.push('/test')}
      >
        Test
      </BreadcrumbItem>
```

Clicking the 'Test' element navigates to the `/test` page without causing a full page refresh, which is the expected behavior.
All the code above has been updated in my reproduction repository.
https://github.com/KUN1007/next-nextui-breadcrumb-key-error

**Comment by wingkwong** [comment]
Regarding the full reload issue, I've fixed it yesterday. Supposedly you don't need to add `onClick` & `onPress`. You can either use the canary version or wait for the next release.
