### ISSUE TITLE
[BUG] - `Link` component from NextUI hasn't `Soft Navigation` behavior

### ISSUE THREAD

**Issue by Cierra-Runis** [nextui-org/nextui#4232]
### NextUI Version

2.4.8

### Describe the bug

I am using `Link` component from NextUI now, but I notice that it hasn't the behavior as [this section](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#5-soft-navigation) said.

### Steps to Reproduce the Bug or Issue

Useful Info: [i18n-routing](https://next-intl-docs.vercel.app/docs/getting-started/app-router/with-i18n-routing#i18n-routing)

```tsx
// src/components/providers.tsx
'use client'

import {NextUIProvider} from '@nextui-org/react';

// It was `next/navigation` in [NextUI Router Guidebook](https://nextui.org/docs/guide/routing#add-the-userouter)
// I tryed both of them and having same result
import {useRouter} from '@/i18n/routing';

export function Providers({children}: { children: React.ReactNode }) {
  const router = useRouter();

  return (
    <NextUIProvider navigate={router.push}>
      {children}
    </NextUIProvider>
  )
}
```

```tsx
// ...
import { Link as I18nLink } from '@/i18n/routing';
import NextLink from 'next/link';
import { Link } from '@nextui-org/react';

import { Providers } from '@/components/providers';

export default function Test() {
  return (
    <Providers>
      <I18nLink href='/'>Home</I18nLink>
      <NextLink href='/'>Home</NextLink>
      <Link href='/'>Home</Link>
    </Providers>
  )
}
```

Result:
- `I18nLink` & `NextLink`: Soft Navigation. DevTools shows there's a request to `http://localhost:3000/zh-CN?_rsc=z25ei`
- `Link`: Hard Navigation. DevTools refreshed.

### Expected behavior

`Link` has some behavior like `I18nLink` and `NextLink`.

### Screenshots or Videos

https://github.com/user-attachments/assets/381e5d07-4063-44e9-9ea1-2bd6a199c881

### Operating System Version

Windows

### Browser

Edge

**Comment by wingkwong** [comment]
fixed [here](https://github.com/nextui-org/nextui/pull/4226). please use canary version or wait for the next release.
