### ISSUE TITLE
[BUG] - Unsupported export in client boundary

### ISSUE THREAD

**Issue by Santana1053** [nextui-org/nextui#4239]
### NextUI Version

2.6.2

### Describe the bug

Failed to compile.

./node_modules/@nextui-org/react/dist/index.mjs
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.
    at Object.transformSource (node_modules\next\dist\build\webpack\loaders\next-flight-loader\index.js:94:31)

### Steps to Reproduce the Bug or Issue

Build Next 15 with React 19.

### Expected behavior

Create an optimized production build.

### Operating System Version

Windows

### Browser

Chrome

**Comment by tansuasici** [comment]
Same

**Comment by Cierra-Runis** [comment]
Same here, and I solved it by adding all components by using NextUI CLI.

[Related Issue](https://github.com/nextui-org/nextui/issues/2735#issuecomment-2059385978)

**Comment by szbphoto** [comment]
Same here

**Comment by Abdellatif-E** [comment]
Same problem, had to downgrade the package version to be able to use it again

**Comment by wingkwong** [comment]
anyone can provide a minimal reproducible environment here?

**Comment by Santana1053** [comment]
Working for me in the latest release.
