### ISSUE TITLE
[BUG] - Type 'DateValue' is not assignable to type 'DateValue | null | undefined'

### ISSUE THREAD

**Issue by PikabobAlex** [nextui-org/nextui#4243]
### NextUI Version

2.6.2

### Describe the bug

This is a controlled DatePicker

```tsx
  const [date_of_birth, setDateOfBirth] = useState<DateValue>(
    parseDate(dayjs().subtract(18, "years").format("YYYY-MM-DD"))
  );
 ```
 
 ```tsx
<DatePicker
  label="Date of Birth"
  name="date_of_birth"
  className="col-span-12 group-data-[slot=input-wrapper]:border-1"
  minValue={parseDate(dayjs().subtract(100, "years").format("YYYY-MM-DD"))}
  maxValue={parseDate(dayjs().subtract(18, "years").format("YYYY-MM-DD"))}
  onChange={setDateOfBirth}
  value={date_of_birth}
  aria-label="Date of Birth"
  isInvalid={!!errors.date_of_birth}
  errorMessage={errors.date_of_birth}
/>
```

But there is an error on the line ```value={date_of_birth}```

Error:
```
Type 'DateValue' is not assignable to type 'DateValue | null | undefined'.
  Type 'ZonedDateTime' is not assignable to type 'DateValue | null | undefined'.
    Type 'import("E:/Github/b2-ming-tak-web/node_modules/.pnpm/@internationalized+date@3.6.0/node_modules/@internationalized/date/dist/types").ZonedDateTime' is not assignable to type 'import("E:/Github/b2-ming-tak-web/node_modules/.pnpm/@internationalized+date@3.5.6/node_modules/@internationalized/date/dist/types").ZonedDateTime'.
      Property '#private' in type 'ZonedDateTime' refers to a different member that cannot be accessed from within type 'ZonedDateTime'.ts(2322)
inputs.d.ts(67, 3): The expected type comes from property 'value' which is declared here on type 'IntrinsicAttributes & DatePickerProps'
```

The error was also causing an error with the same message during the build of my project. 

So my temporary fix was to put a ```@ts-ignore``` above it. 

### Steps to Reproduce the Bug or Issue

```DateValue``` should be able to match with ```DateValue | null | undefined``` ? Or did I missed something?

### Expected behavior

It shouldn't be causing an error, right? I followed the example from the documentation. If I was wrong, please let me know what can I do. 

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by AnYiEE** [comment]
Because NextUI and the upstream packages use different versions of dependencies and specify unique versions. The dependency `@react-types/shared` also exists in different versions, which can lead to similar issues. A temporary solution is to add the following content to `package.json` (assuming pnpm is used as the package manager):

```json
"pnpm": {
	"overrides": {
		"@internationalized/date@^3.5.6": "^3.6.0",
		"@react-types/shared@^3.23.0": "^3.26.0"
	}
}
```

**Comment by CarlosELSouza** [comment]
very useful, thanks
