### ISSUE TITLE
[BUG] - Clicking checkboxes in a multiple selection mode <Table> component no longer causes that row to be selected

### ISSUE THREAD

**Issue by Kismet333** [nextui-org/nextui#4252]
### NextUI Version

2.6.3

### Describe the bug

I just upgraded my NextUI to version 2.6.3 and I found that clicking checkboxes in a multiple selection mode `<Table>` component no longer causes that row to be selected. The row still can be selected if its clicked anywhere else except the checkbox. This includes the main "select all" checkbox in the header of the table, it is no longer selectable.

### Steps to Reproduce the Bug or Issue

1. Create a `<Table>` component with its selectionMode='multiple'. 
2. Add at least 1 row.
3. Attempt to click a row's checkbox.

### Expected behavior

The row becomes selected.

### Operating System Version

Windows

### Browser

Chrome

**Comment by gregmsanderson** [comment]
Noticed this too.

It can be seen on all the demos on the site e.g https://nextui.org/docs/components/table#multiple-row-selection

**Comment by Peterl561** [comment]
Seems to be related to #4220.

**Comment by mayeenulislam** [comment]
Also need to check with #4145

**Comment by chintan-traitfit** [comment]
This is a high-priority bug that needs to be fixed, as it is preventing multiple table row selection.

**Comment by macci001** [comment]
Sorry for the inconvenience caused. RCA for this issue is done and fix will be released soon.
PR to track the fix: https://github.com/nextui-org/nextui/pull/4274
