### ISSUE TITLE
[BUG] - Failed to resolve entry for package "@nextui-org/system"

### ISSUE THREAD

**Issue by wingkwong** [nextui-org/nextui#4254]
### NextUI Version

2.6.3

### Describe the bug

    src/provider.tsx:1:31:
      1 │ import { NextUIProvider } from "@nextui-org/system";

### Steps to Reproduce the Bug or Issue

1. Upgrade using nextui cli
2. start the vite app
3. see the error

### Expected behavior

no such error and vite app can be started

### Operating System Version

macOS

### Browser

Chrome

**Comment by gooooooooney** [comment]
same error
