### ISSUE TITLE
[BUG] - <Button> onClick handler is not triggered by keyboard

### ISSUE THREAD

**Issue by alyrik** [nextui-org/nextui#426]
### Describe the bug

`onClick` handler is not triggered when activating `<Button>` with keyboard.

### Steps to Reproduce the Bug or Issue

1. Go to [any page](https://nextui.org/docs/components/modal) with `<Button>` component.
2. Set focus on `<Button>` (for example, by tabbing).
3. Press Spacebar or Enter key.
4. `onClick` handler is not triggered, however button shows ":active" state.

### Expected behavior

`onClick` handler is triggered as it normally happens for `<button>` element in React.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by nanthony007** [comment]
Having this issue today as well.

**Comment by plepisnew** [comment]
still having this issue

Browser: Firefox
@nextui-org/react ^2.1.13

**Comment by Ninjaneer87** [comment]
Same here

Browser: Brave and Chrome
MacOS
@nextui-org/react ^2.1.8

**Comment by Minisaints** [comment]
What's the latest on this? Ran into this today.

**Comment by BasitAli** [comment]
Given that the issue has popped up again in the version 2, should we reopen the issue?

**Comment by wingkwong** [comment]
Closing - no longer reproducible

**Comment by Inbestigator** [comment]
Occurring again

**Comment by wingkwong** [comment]
@Inbestigator please create a new issue with a reproducible example. Make sure you're already using the latest version.

**Comment by kevinxmyr** [comment]
Issue is still not fixed im using the latest version. and im finding a way to trigger it onClick and onKeyDown separately so far no success for me. this should be fixed. thank you.
