### ISSUE TITLE
[BUG] - Switch inside of CardBody shows blue outline on toggle

### ISSUE THREAD

**Issue by daveycodez** [nextui-org/nextui#4260]
### NextUI Version

2.6.3

### Describe the bug

New bug in 2.6.3, if you toggle a switch it will show the blue focus outline but only inside of a CardBody, must be a focus issue. It's a little jarring to have the outline appear when tapping a switch. I'm using global install of @nextui-org/react@2.6.3

<img width="186" alt="Screenshot 2024-12-07 at 2 48 05 AM" src="https://github.com/user-attachments/assets/11293de9-10a4-4d40-b7d8-eff8c5825838">

### Steps to Reproduce the Bug or Issue

```jsx
import { Card, CardBody, Switch } from "@nextui-org/react"

export default function App() {
    return (
        <Card>
            <CardBody>
                <Switch>
                    Airplane mode
                </Switch>
            </CardBody>
        </Card>
    )
}
```

### Expected behavior

see above

### Operating System Version

macOS

### Browser

Chrome

**Comment by AnYiEE** [comment]
I can reproduce this issue without using the `Card` component; after switching the `Switch`, it automatically gains focus, so a blue outline is displayed.

**Comment by wingkwong** [comment]
@AnYiEE From my side, I could reproduce with Card component only.

**Comment by AnYiEE** [comment]
> @AnYiEE From my side, I could reproduce with Card component only.

I'm sure I didn't use the Card component there. The nesting structure is ModalContent → ModalBody → div (several) → Switch.

**Comment by wingkwong** [comment]
@AnYiEE Thanks for the info. I was testing with Switch component only.

**Comment by daveycodez** [comment]
> > @AnYiEE From my side, I could reproduce with Card component only.
> 
> 
> 
> I'm sure I didn't use the Card component there. The nesting structure is ModalContent → ModalBody → div (several) → Switch.

This likely means it is any kind of container? Probably occurring in Drawer as well
