### ISSUE TITLE
[BUG] - NextJS 15 + NextUI 2.6.4 Error

### ISSUE THREAD

**Issue by therealsras** [nextui-org/nextui#4266]
### NextUI Version

2.6.4

### Describe the bug

Installing, get this message error 

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: framer-motion@11.13.1
npm error Found: react@19.0.0
npm error node_modules/react
npm error   react@"19.0.0" from the root project
npm error   peer react@">=18 || >=19.0.0-rc.0" from @nextui-org/accordion@2.2.3
npm error   node_modules/@nextui-org/accordion
npm error     @nextui-org/accordion@"2.2.3" from @nextui-org/react@2.6.4
npm error     node_modules/@nextui-org/react
npm error       @nextui-org/react@"^2.6.4" from the root project
npm error   225 more (@nextui-org/alert, @nextui-org/aria-utils, ...)
npm error
npm error Could not resolve dependency:
npm error peerOptional react@"^18.0.0" from framer-motion@11.13.1
npm error node_modules/framer-motion
npm error   framer-motion@"^11.13.1" from the root project
npm error   peer framer-motion@">=11.5.6 || >=12.0.0-alpha.1" from @nextui-org/accordion@2.2.3
npm error   node_modules/@nextui-org/accordion
npm error     @nextui-org/accordion@"2.2.3" from @nextui-org/react@2.6.4
npm error     node_modules/@nextui-org/react
npm error       @nextui-org/react@"^2.6.4" from the root project
npm error   18 more (@nextui-org/autocomplete, @nextui-org/button, ...)
npm error
npm error Conflicting peer dependency: react@18.3.1
npm error node_modules/react
npm error   peerOptional react@"^18.0.0" from framer-motion@11.13.1
npm error   node_modules/framer-motion
npm error     framer-motion@"^11.13.1" from the root project
npm error     peer framer-motion@">=11.5.6 || >=12.0.0-alpha.1" from @nextui-org/accordion@2.2.3
npm error     node_modules/@nextui-org/accordion
npm error       @nextui-org/accordion@"2.2.3" from @nextui-org/react@2.6.4
npm error       node_modules/@nextui-org/react
npm error         @nextui-org/react@"^2.6.4" from the root project
npm error     18 more (@nextui-org/autocomplete, @nextui-org/button, ...)
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

```

### Steps to Reproduce the Bug or Issue

Just installing "npm install"

### Expected behavior

No issue

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
can you please share your package.json?

**Comment by therealsras** [comment]
@wingkwong 
```
{
  "name": "web-app",
  "version": "0.5.0-dev",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
},
  "dependencies": {
    "@hookform/resolvers": "^3.3.1",
    "@nextui-org/react": "^2.6.4",
    "apexcharts": "^3.45.1",
    "autoprefixer": "^10.4.15",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "date-fns": "^2.30.0",
    "flatted": "^3.3.1",
    "framer-motion": "^11.13.1",
    "loglevel": "^1.9.1",
    "lucide-react": "^0.268.0",
    "next": "15.0.4",
    "next-intl": "^3.15.2",
    "next-themes": "^0.3.0",
    "node-appwrite": "^14.1.0",
    "pino": "^9.3.1",
    "pino-pretty": "^11.2.1",
    "query-string": "^9.0.0",
    "react": "19.0.0",
    "react-countup": "^6.5.3",
    "react-day-picker": "^8.8.1",
    "react-dom": "19.0.0",
    "react-hook-form": "^7.46.1",
    "react-icons": "^5.2.1",
    "react-toastify": "^10.0.5",
    "recharts": "^2.13.3",
    "sharp": "^0.32.6",
    "tailwind-merge": "^1.14.0",
    "tailwindcss": "^3.4.0",
    "tailwindcss-animate": "^1.0.6",
    "usehooks-ts": "^3.1.0",
    "zod": "^3.22.2",
    "zustand": "^4.4.1"
  },
  "devDependencies": {
    "@iconify/react": "^5.1.0",
    "@types/node": "^20",
    "@types/react": "19.0.1",
    "@types/react-dom": "19.0.1",
    "eslint": "^8",
    "eslint-config-next": "15.0.4",
    "postcss": "^8",
    "ts-node": "^10.9.2",
    "typescript": "^5.5.4"
  },
  "overrides": {
    "@types/react": "19.0.1",
    "@types/react-dom": "19.0.1"
  }
}

```

**Comment by therealsras** [comment]
![image](https://github.com/user-attachments/assets/18d2f47d-af90-43ad-b891-9ee13bbd6a3e)

**Comment by daveycodez** [comment]
I don't think React 19 is a viable option atm, at least not until we have a set in stone guide for supporting it. I know I was having issues with framer-motion and other libraries.

For now I would suggest installing react 18 on your project

```
npm i react@18 react-dom@18
```

**Comment by therealsras** [comment]
@wingkwong how can I create sandbox for you. I am reproducing in the internal project. what say to create sandbox

**Comment by wingkwong** [comment]
@therealsras you can use stackblitz or codesandbox. We don't need the exact clone of your project, but just a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=In%20computing%2C%20a%20minimal%20reproducible,to%20be%20demonstrated%20and%20reproduced.) so that we could start investigating on the same page.

**Comment by therealsras** [comment]
@

> @therealsras you can use stackblitz or codesandbox. We don't need the exact clone of your project, but just a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=In%20computing%2C%20a%20minimal%20reproducible,to%20be%20demonstrated%20and%20reproduced.) so that we could start investigating on the same page.

https://github.com/therealsras/nextui-nextjs15 
please have a look

**Comment by therealsras** [comment]
@wingkwong what do you think

**Comment by arudenkoofficial** [comment]
> I don't think React 19 is a viable option atm, at least not until we have a set in stone guide for supporting it. I know I was having issues with framer-motion and other libraries.
> 
> For now I would suggest installing react 18 on your project (this will fix create-next-app@latest compatibility issues)
> 
> ```
> npm i react@18 react-dom@18
> ```
> 
> Shadcn suggests using --force or --legacy-peer-deps but I don't love it. I think for framer motion you can move it to the overrides somehow.
> 
> Maybe this will work? idk
> 
> ```
>   "overrides": {
>         "framer-motion": {
>             "react": "19.0.0",
>             "react-dom": "19.0.0"
>         }
>     }
> ```
> 
> I think when it's fully ready it would be helpful to have a React 19 guide on the NextUI docs

Worked for me!
I have following dependecies:
```

**Comment by daveycodez** [comment]
I've been using overrides for pretty much any package that doesn't support React 19, which seems to work.

```
"overrides": {
    "@piotr-cz/swr-idb-cache": {
      "react": ">=18.0.0",
      "react-dom": ">=18.0.0"
    },
    "framer-motion": {
      "react": ">=18.0.0",
      "react-dom": ">=18.0.0"
    },
    "react-avatar-editor": {
      "react": ">=18.0.0",
      "react-dom": ">=18.0.0"
    },
    "react-flagpack": {
      "react": ">=18.0.0",
      "react-dom": ">=18.0.0"
    },
    "react-swipe-to-delete-ios": {
      "react": ">=18.0.0",
      "react-dom": ">=18.0.0"
    },
    "swr": {
      "react": ">=18.0.0",
      "react-dom": ">=18.0.0"
    }
  },
```

**Comment by wingkwong** [comment]
Currently it only supports to react 19 rc. We need to wait for `react-aria` to support stable react 19.
