### ISSUE TITLE
[BUG] - Dropdown Error

### ISSUE THREAD

**Issue by cuunoong** [nextui-org/nextui#4267]
### NextUI Version

2.6.4

### Describe the bug

**I got this error after upgrading to latest version, and it work in previous version**

chunk-GZD7INZN.js?v=6411179e:521 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `NextUI.DropdownTrigger`.
    at PopoverTrigger (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=cb94c851:53307:43)
    at DropdownTrigger (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=cb94c851:57690:35)
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=cb94c851:53335:11
    at Dropdown (

### Steps to Reproduce the Bug or Issue

1. Create component with dropdown 

`<Dropdown>
          <DropdownTrigger>
              <div>
                  <Button variant="bordered">Open Menu</Button>
              </div>
          </DropdownTrigger>
          <DropdownMenu aria-label="Static Actions">
              <DropdownItem key="new">New file</DropdownItem>
              <DropdownItem key="copy">Copy link</DropdownItem>
              <DropdownItem key="edit">Edit file</DropdownItem>
              <DropdownItem
                  key="delete"
                  className="text-danger"
                  color="danger"
              >
                  Delete file
              </DropdownItem>
          </DropdownMenu>
      </Dropdown>`

### Expected behavior

Fix 

### Screenshots or Videos

chunk-GZD7INZN.js?v=6411179e:521 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `NextUI.DropdownTrigger`.
    at PopoverTrigger (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=cb94c851:53307:43)
    at DropdownTrigger (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=cb94c851:57690:35)
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=cb94c851:53335:11
    at Dropdown (

### Operating System Version

Mac OS

### Browser

Chrome

**Comment by AnYiEE** [comment]
https://github.com/nextui-org/nextui/issues/4245

**Comment by wingkwong** [comment]
Duplicate - lets' track in above one.
