### ISSUE TITLE
[BUG] - Component created from `extendVariants` cannot be used as a JSX component

### ISSUE THREAD

**Issue by shlyamster** [nextui-org/nextui#4269]
### NextUI Version

2.6.4

### Describe the bug

As I understand it, due to the change in the `ReactElement` interface in React 19, an error occurs in determining the type of component when creating your own styles through the `extendVariants` function.

When using `@types/react` version `18.3.12`
```typescript
interface ReactElement<P = any, T extends ...> 
```

When using `@types/react` version `19.0.1`
```typescript
interface ReactElement<P = unknown, T extends ...> 
```

### Steps to Reproduce the Bug or Issue

Using these library versions, try to create any component with custom styles through the `extendVariants` function. An error occurs - `'Component' cannot be used as a JSX component`.

```json
{
  "name": "project",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start --hostname 0.0.0.0",
    "lint": "next lint"
  },
  "browserslist": [
    "defaults"
  ],
  "dependencies": {
    "@nextui-org/react": "^2.6.4",
    "@nextui-org/use-infinite-scroll": "^2.2.1",
    "clsx": "^2.1.1",
    "framer-motion": "^11.13.1",
    "next": "^15.0.4",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@types/node": "^22.10.1",
    "@types/react": "^19.0.1",
    "@types/react-dom": "^19.0.1",
    "autoprefixer": "^10.4.20",
    "cssnano": "^7.0.6",
    "cssnano-preset-advanced": "^7.0.6",
    "eslint": "^9.16.0",
    "eslint-config-next": "^15.0.4",
    "postcss": "^8.4.49",
    "tailwindcss": "^3.4.16",
    "typescript": "^5.7.2"
  }
}
```

### Expected behavior

I think this is an error in the `extendVariants` function type declaration and need to specify `ReactElement<any>` there.

### Operating System Version

Any

### Browser

Chrome

**Comment by shlyamster** [comment]
I studied the source code of the `extendVariants` function in a little more detail. It looks strange to me that in the type declaration, the function returns `ForwardRefRenderFunction` type, although in fact in `extend-variants.js` the `ForwardedComponent` is returned, which is obtained as a result of the `forwardRef` call, and the returned type must be `ForwardRefExoticComponent`.

If I understand everything correctly, the actual declaration of the `ExtendVariants` type should be as follows.

```typescript
type ExtendVariants = {
  <
    C extends JSXElementConstructor<any>,
    CP extends ComponentProps<C>,
    S extends ComponentSlots<CP>,
    V extends ComposeVariants<CP, S>,
    SV extends SuggestedVariants<CP, S>,
    DV extends DefaultVariants<V, SV>,
    CV extends CompoundVariants<V, SV>,
  >(
    BaseComponent: C,
    styles: {
      variants?: V;
      defaultVariants?: DV;
      compoundVariants?: CV;
      slots?: S;
    },
    opts?: Options,
  ): ForwardRefExoticComponent<
    PropsWithoutRef<{
      [key in keyof CP | keyof V]?:
        | (key extends keyof CP ? CP[key] : never)
        | (key extends keyof V ? StringToBoolean<keyof V[key]> : never);
    }> &
      RefAttributes<ReactElement>
  >;
};
```

**Comment by wingkwong** [comment]
can you provide a simple sandbox for reproducing the issue and a PR for us to review?

**Comment by shlyamster** [comment]
@wingkwong I will try to do it soon

**Comment by shlyamster** [comment]
@wingkwong Check the reproduction of the error in my [codesandbox](https://codesandbox.io/p/devbox/next-ui-extendvariants-react-19-hwgm8y). In the `app/page.tsx` file you can see the ts error I'm talking about. And in `utils/extendVariants.ts`, a correction of the data type is presented. 

I also made a pull request #4291 with data type corrections.

**Comment by Andro172** [comment]
+1, also does anyone know when will this be released?

**Comment by blackmouse572** [comment]
+1, wait for further notification

**Comment by carlosriveroib** [comment]
also waiting for this release

**Comment by mehdivaezi** [comment]
+1, having the same issue
