### ISSUE TITLE
[BUG] - Components/Popover

### ISSUE THREAD

**Issue by czanas28** [nextui-org/nextui#427]
### Describe the bug

Not reporting a bug with the actual popover. Just the code sandbox project.

The Text component is not added in the import, on the Placements codesandbox, so testing returns and error until it's added manually.

### Steps to Reproduce the Bug or Issue

Go to https://nextui.org/docs/components/popover

Under the 'Placements' section

Click 'Open in CodeSandbox'

### Expected behavior

import { Popover, Button, Grid, **Text** } from "@nextui-org/react";

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @czanas28 thanks for reporting it,  fixed it is on its way https://github.com/nextui-org/nextui/actions/runs/2216736226
