### ISSUE TITLE
[BUG] - DropdownItem with href (link) is breaking with startContent or endContent

### ISSUE THREAD

**Issue by mayeenulislam** [nextui-org/nextui#4289]
### NextUI Version

2.6.5

### Describe the bug

![Dropdown item as a link with icon is breaking UI](https://github.com/user-attachments/assets/9e067274-86df-4a12-9386-67939945d532)

I can see you corrected the markup:

**🟥 invalid**

```jsx
<ul>
<a></a>
<li></li>
</ul>
```

**✅ corrected**

```jsx
<ul>
<li><a></a></li>
<li></li>
</ul>
```

But with this new JSX (`<a>`) inside the previous `<li>` it's breaking the list items, as the newly added JSX doesn't have any `flex` class. I tried using `classNames`, but that isn't working:

```jsx
<DropdownItem
  key="frontend"
  classNames={{
    base: "jingalujungla",
    wrapper: "abracadabra",
    title: "titlu",
    selectedIcon: "selectu",
  }}
  href="/"
  startContent={<IoMdLaptop className={dropdownIconClasses} />}
>
  {t("Front End")}
</DropdownItem>
```

> ⚠️ The issue is browser independent

### Steps to Reproduce the Bug or Issue

0. Add a Dropdown along with `DropdownItem` with `startContent` and `href`
1. Upgrade NextUI to 2.6.5

### Expected behavior

Shouldn't break the dropdown item

### Operating System Version

Windows 11 Pro (OS Build: 22631.4460)

### Browser

Edge

**Comment by AnYiEE** [comment]
https://github.com/nextui-org/nextui/issues/4244

**Comment by J4v4Scr1pt** [comment]
Same issue here, can't upgrade because of it.

**Comment by dann-dann** [comment]
same issue

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/4244. there is a PR fixing that already.

**Comment by J4v4Scr1pt** [comment]
Any ETA on fix release? :)

**Comment by wingkwong** [comment]
@J4v4Scr1pt There're a few PRs we need to review. We'll release a new bug fix version afterwards. If it's urgent, you may consider to use the canary version (`0.0.0-canary-20241209145441`).

**Comment by J4v4Scr1pt** [comment]
> @J4v4Scr1pt There're a few PRs we need to review. We'll release a new bug fix version afterwards. If it's urgent, you may consider to use the canary version (`0.0.0-canary-20241209145441`).

Thank you! 🙏
