### ISSUE TITLE
[BUG] - Interactive Elements Not Responding on iOS After Updating to NextUI 2.6.0

### ISSUE THREAD

**Issue by scarrascoalvarez** [nextui-org/nextui#4292]
### NextUI Version

2.6.0

### Describe the bug

After updating to NextUI 2.6.0, interactive elements such as cards, buttons, and clickable components stopped working on iOS devices when navigating through the web application. Tapping these elements does not trigger any action or event, making the interface non-functional on affected devices.

### Steps to Reproduce the Bug or Issue

	1.	Update the project to NextUI 2.6.0.
	2.	Deploy the application or run it locally.
	3.	Access the web app on an iOS device (Safari/Chrome).
	4.	Attempt to interact with buttons, cards, or clickable elements.

### Expected behavior

Interactive elements such as buttons and cards should respond to taps or clicks as expected, triggering the correct actions/events.

### Screenshots or Videos

https://github.com/user-attachments/assets/85630dd1-f479-4568-9f92-f8ec819ca738

### Operating System Version

iOS

### Browser

Safari

**Comment by jrgarciadev** [comment]
We're investigating this issue, fix should be out soon

**Comment by jimmailcamp** [comment]
It occurs when using buttons in Portals on ios

**Comment by bckd00r** [comment]
Small clarifacition about issue, if you change from onclick to onpress and remove preventdefault issue is disappears @jimmailcamp @scarrascoalvarez @sudongyuer

**Comment by sudongyuer** [comment]
Guys, have you tried use **onPress** instead of **onClick** ?

**Comment by jimmailcamp** [comment]
Why is this necessary tho?

**Comment by bckd00r** [comment]
> Guys, @scarrascoalvarez @jimmailcamp @bckd00r have you tried use **onPress** instead of **onClick** ?

yes, i have tried onpress and it's working now but why onClick not working on mobile devices tho?

**Comment by sudongyuer** [comment]
> Why is this necessary tho?

This is just a temporary solution, will fix it soon

**Comment by bckd00r** [comment]
> > Why is this necessary tho?
> 
> This is just a temporary solution, will fix it soon

thank you for quick answer i'm very glad to hear that gonna be fixed soon <3

**Comment by jrgarciadev** [comment]
Hey guys please test this in the v2.6.7

**Comment by sudongyuer** [comment]
> Hey guys please test this in the v2.6.7

Not woking, v2.6.7 just solve the ripple issue. I'v already found the reason, will make PR soon.

**Comment by jrgarciadev** [comment]
We've deprecated `onClick` in favor of `onPress` to align with React Aria's accessibility and compatibility standards. You can read more about why this change was made here: [Building a Button, Part 1](https://react-spectrum.adobe.com/blog/building-a-button-part-1.html).

Note that React Aria team already removed the `onClick` event but we managed to keep it in our implementations at least until the next minor version, you'll need to update your code to use `onPress` for all interactive elements instead of the `onClick` event. 

This will fix the issue on iOS devices and ensure proper functionality

**Comment by JRetza** [comment]
this is one of the more ridiculous things i think i've seen in 30 years of programming. if this isn't a breaking change - what is??

**Comment by JRetza** [comment]
specifically which nextui components require onPress and which still use onClick? it seems Inputs and other items still use onClick so not only is this a big pain in the ass but now there's no consistency between components. get it together guys and do a better job.

**Comment by itorz7** [comment]
Why do some use onPress and some use onClick?
adding more chaos

**Comment by wingkwong** [comment]
@JRetza

> specifically which nextui components require onPress and which still use onClick?

For the following interactive elements, you should use `onPress` to align with React Aria's accessibility and compatibility standards. `onClick` event is still there for these components at this moment until next minor version. However, please note that using `onClick` will cause some issues on iOS & Android devices. 

- AccordionItem
- Button
- Card
- Link
- ListboxItem
- MenuItem

For other components, they accept `onClick`. 

@itorz7

> Why do some use onPress and some use onClick?
> adding more chaos

We understand this may cause the inconvenience. Please note that this is the decision made by the `react-aria` team. We need to follow the same approach to avoid incompatibility. You may check out why [here](https://react-spectrum.adobe.com/blog/building-a-button-part-1.html) if you're interested.

**Comment by Jsox** [comment]
Using Button as="Link" adds warning to console too. With no onPress or onClick attribute given.

**Comment by wingkwong** [comment]
@Jsox that was introduced internally. we're aware and working of it. you may simply ignore that.

**Comment by bsodmike** [comment]
Is everyone suppressing this warning for now? Tested with the latest release in Chrome.

**Comment by wingkwong** [comment]
@bsodmike let's track in https://github.com/nextui-org/nextui/issues/4493
