### ISSUE TITLE
`Input` element when used returns `undefined`

### ISSUE THREAD

**Issue by JosiasAurel** [nextui-org/nextui#43]
**Describe the bug**
I recently (~30mins ago) updated NextUI version on one of my projects to use the new Input component and get an issue with it
Next.JS throws
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
**Steps to reproduce**
1. Create new Next.JS project and install NextUI
2. Create a page and add new Input element
3. See error

**Expected behaviour**
Display new Input element on the page

**Screenshots**
<img width="771" alt="codes" src="https://user-images.githubusercontent.com/47951376/134796863-76976d9e-2179-446b-9f99-140abce00b2a.PNG">
<img width="852" alt="errorPage" src="https://user-images.githubusercontent.com/47951376/134796865-f4ea1f0d-1de5-408e-a13c-46e9217fbccd.PNG">

**Environment / Context**
- Desktop
- Operating System: Windows 10
- Chrome 93
- Device: HP Laptop 14s

**Comment by jrgarciadev** [comment]
Hi @JosiasAurel, I just tried this and unfortunately, I couldn't replicate it, It works fine for me even though I downgraded the webpack version to 4 if you remove the "Input" import the problem disappears?

**Comment by JosiasAurel** [comment]
> Hi @JosiasAurel, I just tried this and unfortunately, I couldn't replicate it, It works fine for me even though I downgraded the webpack version to 4 if you remove the "Input" import the problem disappears?

The issue indeed disappears when I remove the `Input`

**Comment by jrgarciadev** [comment]
Is your project open source? If so, could you pass me the repo?

**Comment by JosiasAurel** [comment]
The project is not open source unfortunately. But maybe I could pass some parts of the code.
Let me try that

**Comment by jrgarciadev** [comment]
No problem, I just updated the next.js example -> https://github.com/nextui-org/nextui/tree/main/examples/create-next-app, you can use it to compare what it's different, let me know if you find out something maybe the next.js version it's different

**Comment by JosiasAurel** [comment]
here is a sample that causes the same error I had earlier except this time it says it got `object` instead of `undefined` 🤔

Here you go -> https://github.com/JosiasAurel/breaking-ui-nextui

Sorry for replying late btw

**Comment by jrgarciadev** [comment]
Great thank you for creating it, I'll take a look as soon as I can 🙌🏼

**Comment by jrgarciadev** [comment]
Hey @JosiasAurel could you try again with the last published version (alpha.47)? 🙋🏻‍♂️

**Comment by JosiasAurel** [comment]
Hey @jrgarciadev, I upgraded to the latest version (alpha.48) and also tried (alpha.47) but still getting the same error
https://github.com/JosiasAurel/breaking-ui-nextui

**Comment by jrgarciadev** [comment]
Hi! @JosiasAurel I was checking this out and I found the problem in the `_app.js` file you aren't destructuring the params,

You have this:

```js
function MyApp(Component, pageProps) 
```

You should be destructuring the params as follows:

```js
function MyApp({Component, pageProps}) 
```

After doing that works fine for me, hope this helps you, I'm going to close this issue 👍🏻
