### ISSUE TITLE
[BUG] Form errors not displaying properly in Modal

### ISSUE THREAD

**Issue by tazissam** [nextui-org/nextui#4300]
### NextUI Version

2.6.0

## [BUG] Form errors not displaying properly in Modal

**Describe the bug**
When using a form within a NextUI Modal component, form errors are not displaying correctly. The errors only appear when the modal is closed and reopened, rather than in real-time as expected.

**Additional context**
- This issue occurs when using libraries for form management (e.g., React Hook Form)
- The behavior differs between real-time usage and when using libraries
- There may be compatibility issues with React 19 and `useActionState`

**Code Example**
```jsx
import { Modal, Button, Input, useDisclosure } from "@nextui-org/react";
import { useActionState } from "react"; // Note: This is hypothetical, not part of NextUI
// Import server
export default function App() {
  const { isOpen, onOpen, onClose } = useDisclosure();

  const [{errors}, formAction] = useActionState(createTodo, {
    errors: {},
  });

  return (
    <div>
      <Button auto onPress={onOpen}>
        Open modal
      </Button>
      <Modal 
        isOpen={isOpen} 
        onClose={onClose}
        closeButton
        aria-labelledby="modal-title"
      >
        <Modal.Header>
          <h2 id="modal-title">Test Form</h2>
        </Modal.Header>
        <Modal.Body>
          <Form action={formAction} validationErrors={errors}>
      <Input name="todo" label="Task" />
      <Button type="submit">Add</Button>
    </Form>
        </Modal.Body>
      </Modal>
    </div>
  );

// app/actions.ts
"use server";

export async function createTodo(prevState: any, formData: FormData) {
  try {
    // Create the todo.
  } catch (err) {
    return {
      errors: {
        todo: "Invalid todo.",
      },
    };
  }
}

``` 

**Additional Information**
Any additional information, configuration, or context that might be helpful in understanding and reproducing the issue.
 I apologize if there are any mistakes because I wrote it on the phone.

### Steps to Reproduce the Bug or Issue

**Steps to Reproduce**
1. Create a NextUI Modal component
2. Add a form with input fields inside the Modal content
3. Implement form validation (e.g., using React Hook Form)
4. Submit the form with invalid data
5. Observe that no errors are displayed
6. Close and reopen the Modal
7. Observe that errors are now visible

### Expected behavior

**Expected behavior**
Form errors should display in real-time within the Modal, without requiring the Modal to be closed and reopened.

### Operating System Version

Windows 

### Browser

Chrome

**Comment by kofeinstyle** [comment]
Maybe need to change [example](https://www.heroui.com/docs/guide/forms#react-server-actions)? Because it does not work. And It works only like this https://github.com/heroui-inc/heroui/issues/4300#issuecomment-2537018475
