### ISSUE TITLE
[BUG] - Table selection not working

### ISSUE THREAD

**Issue by szbphoto** [nextui-org/nextui#4302]
### NextUI Version

2.6.5

### Describe the bug

The table with selection is not working when trying to select the row with the checkbox, if i press on the row then it will work fine. But the checkbox will not work as expected. I will drop a video also.

### Steps to Reproduce the Bug or Issue

Just try a table with selection or just check out on the nextui website https://nextui.org/docs/components/table#multiple-row-selection 

### Expected behavior

When i press on the checkbox then select the row 

### Screenshots or Videos

https://github.com/user-attachments/assets/1b69f085-87da-4696-84bd-997fae295663

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Duplicated: https://github.com/nextui-org/nextui/issues/4252
