### ISSUE TITLE
[BUG] - NextUi CLI

### ISSUE THREAD

**Issue by zMohammadz84** [nextui-org/nextui#4307]
### NextUI Version

next ui cli v0.5.0

### Describe the bug

nextui add button

NextUI CLI v0.5.0

Adding required dependencies: @nextui-org/button

npm install @nextui-org/button
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: framer-motion@11.13.3
npm error Found: react@19.0.0
npm error node_modules/react
npm error   peer react@">=18 || >=19.0.0-rc.0" from @nextui-org/react-rsc-utils@2.1.1
npm error   node_modules/@nextui-org/react-rsc-utils
npm error     @nextui-org/react-rsc-utils@"2.1.1" from @nextui-org/react-utils@2.1.1
npm error     node_modules/@nextui-org/react-utils
npm error       @nextui-org/react-utils@"2.1.1" from @nextui-org/system@2.4.4
npm error       node_modules/@nextui-org/system
npm error         @nextui-org/system@"^2.4.4" from the root project
npm error         2 more (@nextui-org/button, @nextui-org/ripple)
npm error       3 more (@nextui-org/button, @nextui-org/ripple, @nextui-org/spinner)
npm error   peer react@">=18 || >=19.0.0-rc.0" from @nextui-org/react-utils@2.1.1
npm error   node_modules/@nextui-org/react-utils
npm error     @nextui-org/react-utils@"2.1.1" from @nextui-org/system@2.4.4
npm error     node_modules/@nextui-org/system
npm error       @nextui-org/system@"^2.4.4" from the root project
npm error       2 more (@nextui-org/button, @nextui-org/ripple)
npm error     @nextui-org/react-utils@"2.1.1" from @nextui-org/button@2.2.4
npm error     node_modules/@nextui-org/button
npm error       @nextui-org/button@"*" from the root project
npm error     2 more (@nextui-org/ripple, @nextui-org/spinner)
npm error   29 more (@nextui-org/system, @nextui-org/system-rsc, ...)
npm error
npm error Could not resolve dependency:
npm error peerOptional react@"^18.0.0" from framer-motion@11.13.3
npm error node_modules/framer-motion
npm error   peer framer-motion@">=11.5.6 || >=12.0.0-alpha.1" from @nextui-org/system@2.4.4
npm error   node_modules/@nextui-org/system
npm error     @nextui-org/system@"^2.4.4" from the root project
npm error     2 more (@nextui-org/button, @nextui-org/ripple)
npm error   framer-motion@"^11.13.3" from the root project
npm error   3 more (@nextui-org/button, @nextui-org/ripple, @nextui-org/dom-animation)
npm error
npm error Conflicting peer dependency: react@18.3.1
npm error node_modules/react
npm error   peerOptional react@"^18.0.0" from framer-motion@11.13.3
npm error   node_modules/framer-motion
npm error     peer framer-motion@">=11.5.6 || >=12.0.0-alpha.1" from @nextui-org/system@2.4.4
npm error     node_modules/@nextui-org/system
npm error       @nextui-org/system@"^2.4.4" from the root project
npm error       2 more (@nextui-org/button, @nextui-org/ripple)
npm error     framer-motion@"^11.13.3" from the root project
npm error     3 more (@nextui-org/button, @nextui-org/ripple, @nextui-org/dom-animation)
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\USER\AppData\Local\npm-cache\_logs\2024-12-10T08_51_28_941Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\USER\AppData\Local\npm-cache\_logs\2024-12-10T08_51_28_941Z-debug-0.log

Unexpected error. Please report it as a bug:
Error: Command failed: npm install @nextui-org/button
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:882:11)
    at execSync (node:child_process:954:15)
    at file:///C:/Users/USER/AppData/Roaming/npm/node_modules/nextui-cli/dist/index.js:37:259
    at new Promise (<anonymous>)
    at xe (file:///C:/Users/USER/AppData/Roaming/npm/node_modules/nextui-cli/dist/index.js:37:137)
    at mt (file:///C:/Users/USER/AppData/Roaming/npm/node_modules/nextui-cli/dist/index.js:37:470)
    at Command.vn (file:///C:/Users/USER/AppData/Roaming/npm/node_modules/nextui-cli/dist/index.js:76:1501)
    at async Command.parseAsync (C:\Users\USER\AppData\Roaming\npm\node_modules\nextui-cli\node_modules\commander\lib\command.js:935:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7136,
  stdout: null,
  stderr: null
}

### Steps to Reproduce the Bug or Issue

1 => nextui add button
2 => error

### Expected behavior

add Button component

### Operating System Version

windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @zMohammadz84, React 19 is currently only supported as a release candidate (RC). Please install 19.0.0-rc.1 instead
