### ISSUE TITLE
[BUG] - MODAL GLITCH ON IOS (SAFARI BROWSER)

### ISSUE THREAD

**Issue by tjfaith** [nextui-org/nextui#4308]
### NextUI Version

^2.6.5

### Describe the bug

I am currently using nextui Modal version ^2.0.41, i noticed on Android devices the modal works smoothly but on IOS devices it tends to lag also the modal scales when a user tries to fill in the form on the modal 

### Your Example Website or App

https://usecotton-website.vercel.app/

### Steps to Reproduce the Bug or Issue

1. Go to https://usecotton-website.vercel.app/
2. Click on 'Order Service' button in the home page 
3. Try to fill in the form

### Expected behavior

![WhatsApp Image 2024-12-10 at 09 57 34_cdb0b561](https://github.com/user-attachments/assets/ee892b84-150e-4423-88d9-b680b6aed586)

### Screenshots or Videos

https://github.com/user-attachments/assets/817c629e-3e3e-4a70-92e6-0c0d035cc96b

![WhatsApp Image 2024-12-10 at 09 28 44_3c761d8b](https://github.com/user-attachments/assets/f6dc54cc-661c-41e7-977b-e91829b85044)

### Operating System Version

IOS

### Browser

Safari

**Comment by szbphoto** [comment]
Hello, the zoom in is because you haven't setted up the viewport option correctly.

**My own viewport settings with NextJS 14+:** 

```
export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};
```

Since you haven't provided any source code it's hard to tell anything else related to this issue, I use modal in our projects too but i dont have any lags. If you can provide a code snippet or anything that would be cool. Thanks!

**Comment by tjfaith** [comment]
> Hello, the zoom in is because you haven't setted up the viewport option correctly.
> 
> **My own viewport settings with NextJS 14+:**
> 
> ```
> export const viewport = {
>   width: "device-width",
>   initialScale: 1,
>   maximumScale: 1,
>   userScalable: 1,
>   themeColor: [
>     { media: "(prefers-color-scheme: light)", color: "white" },
>     { media: "(prefers-color-scheme: dark)", color: "black" },
>   ],
> };
> ```
> 
> Since you haven't provided any source code it's hard to tell anything else related to this issue, I use modal in our projects too but i dont have any lags. If you can provide a code snippet or anything that would be cool. Thanks!

oh thanks, i will try this, but i later found out that on IOS device the input fields font-size must be at least 16px

**Comment by KlutchKyle** [comment]
> Hello, the zoom in is because you haven't setted up the viewport option correctly.
> 
> **My own viewport settings with NextJS 14+:**
> 
> ```
> export const viewport = {
>   width: "device-width",
>   initialScale: 1,
>   maximumScale: 1,
>   userScalable: 1,
>   themeColor: [
>     { media: "(prefers-color-scheme: light)", color: "white" },
>     { media: "(prefers-color-scheme: dark)", color: "black" },
>   ],
> };
> ```
> 
> Since you haven't provided any source code it's hard to tell anything else related to this issue, I use modal in our projects too but i dont have any lags. If you can provide a code snippet or anything that would be cool. Thanks!

Worked for me! Thanks!
