### ISSUE TITLE
CHECKBOX BUG `initialChecked`

### ISSUE THREAD

**Issue by IraiDev** [nextui-org/nextui#431]
### Describe the bug

Warning: React does not recognize the `initialChecked` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialchecked` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### Steps to Reproduce the Bug or Issue

1. just call the checkbox component

### Expected behavior

I dont have logic in the component, it only throws this error when calling it, highlight that it is inside a table

### Screenshots or Videos

![screenshot checkbox](https://user-images.githubusercontent.com/85415332/165147637-f2653d01-d2a8-49f5-9db3-19cc29a8e78c.jpg)

### Operating System Version

windows

### Browser

Firefox

**Comment by Kaasfonthijn** [comment]
I also encountered this bug and later found this post. This warning even occurs with a fresh Next.js project with only Nextui as a dependency.
