### ISSUE TITLE
[BUG] - Cannot find module '@nextui-org/react' or its corresponding type declarations.

### ISSUE THREAD

**Issue by J4v4Scr1pt** [nextui-org/nextui#4315]
### NextUI Version

2.6.6

### Describe the bug

I just updated to 2.6.6 and got `Cannot find module '@nextui-org/react' or its corresponding type declarations.` for any component I import.
I have tried removing node_modules and re-install still same issue.
Downgrade to 2.6.5 resolve the issue.

**Tested in two completely different applications.**

### Steps to Reproduce the Bug or Issue

Install the latest NextUI version and import a component.

### Expected behavior

To be able to import components :) 

### Operating System Version

Window 11

### Browser

Chrome

**Comment by a-chacon** [comment]
Something similar here: `Cannot find module '@nextui-org/react' or its corresponding type declarations. ` Importing `Alert` component.
