### ISSUE TITLE
[BUG] - dist folder missing from installed Select component in node_modules

### ISSUE THREAD

**Issue by jah-1206** [nextui-org/nextui#4317]
### NextUI Version

@nextui-org/select@2.4.5

### Describe the bug

Hi,
I install different components with npm.
When I run `npm install @nextui-org/select`, the component gets correctly added in the package.json et the node_modules folder is created, but I can't import it in my project, I get this error :

> Cannot find module '@nextui-org/select' or its corresponding type declarations.

When i go in /node_modules/@nextui-org/select, I find a node_modules folder and not a dist folder as for the other components :

![image](https://github.com/user-attachments/assets/ebdb050c-05cd-4e52-9c63-662c484338b1)
 

### Steps to Reproduce the Bug or Issue

- In NextJs 15.0.2 project, `run npm install @nextui-org/select`

- Try to import the component in a NextJs component

### Expected behavior

I expect to be able to import the component as any other NextUI component.

### Operating System Version

Windows

### Browser

Firefox

**Comment by J4v4Scr1pt** [comment]
Dublicate: https://github.com/nextui-org/nextui/issues/4315

**Comment by jah-1206** [comment]
> Dublicate: #4315

Not really, I can use many other components like the buttons, forms and all... I just have this issue on the Select component.
I just tried  to install the Chip component and it works.

**Comment by J4v4Scr1pt** [comment]
Ok!
The Version 2.6.7 fixes the issue. for me.

**Comment by jah-1206** [comment]
Yes it's all good ! Thank you :)
