### ISSUE TITLE
[BUG] - SCSS Module styles for slots are overridden by TailwindCSS classes in production

### ISSUE THREAD

**Issue by ArtKira31** [nextui-org/nextui#4331]
### NextUI Version

2.6.8

### Describe the bug

I am using Next UI and trying to override styles for a component using the slots API as documented. My project uses SCSS Modules alongside TailwindCSS. Locally, everything works as expected, and my SCSS class takes precedence. However, in the production build, the TailwindCSS classes have higher priority and override my SCSS styles because they appear later in the final CSS output.

Actual Behavior
In the production build, TailwindCSS classes are applied after the SCSS module styles, causing the SCSS styles to be overridden.

Environment
Next UI version: 2.6.8
Next.js version: 15.0.4
TailwindCSS version: 3.4.16
Node.js version: 18.18.2

### Steps to Reproduce the Bug or Issue

Create a Next.js project with Next UI, TailwindCSS or use `npx create-next-app -e https://github.com/nextui-org/next-app-template` [as recomended](https://nextui.org/docs/frameworks/nextjs).

Override a Next UI component's slot with a class from an SCSS module.

```
// Input.tsx

import styles from './Input.module.scss';
<Input
      aria-label="Search"
      classNames={{
        inputWrapper: styles.inputWrapper,
      }}
      labelPlacement="outside"
      placeholder="Search..."
      type="search"
    />

// Input.module.scss
.inputWrapper {
  background: red;
  padding: 40px;
}
```

In development mode the styles work as expected, and the SCSS class has higher specificity.

In production mode the TailwindCSS styles appear lower in the compiled CSS output and override the SCSS class.

### Expected behavior

The SCSS module styles applied via slots should take precedence over TailwindCSS classes in both development and production modes.

### Operating System Version

macOS, windows

### Browser

Chrome

**Comment by sudongyuer** [comment]
Hi @ArtKira31, I reproduced this problem locally and found that it is not a bug in NextUI. You can try importing the SCSS module globally to make it work.
<img width="580" alt="image" src="https://github.com/user-attachments/assets/6a26d22f-c58f-4fde-9280-0bf78932bce3" />
<img width="588" alt="image" src="https://github.com/user-attachments/assets/d0a140cc-3e96-453d-b0ab-6536395bd487" />
