### ISSUE TITLE
[BUG] - Pressing Button with href attribute has no effect (next.js App Router)

### ISSUE THREAD

**Issue by partridgeworks** [nextui-org/nextui#4337]
### NextUI Version

2.6.8

### Describe the bug

The `<Button>` component does not perform router navigation when an `href` attribute is passed to it

### Steps to Reproduce the Bug or Issue

1. Set up next.js and nextUI as described in the documentation
2. Add `NextUIProvider` as wrapper around the app as described in [routing guide](https://nextui.org/docs/guide/routing)
3. Add a button like this:

```
// page.tsx

import { Button } from "@nextui-org/react";

export default function Page() {
  return (
    <div>
        <Button href="/">Go Home</Button>
    </div>
  );
}

```

Clicking the button does not navigate the browser to the new URL

### Expected behavior

Clicking the button should call the next.js `router.push(...)` function and the browser should navigate to `/`

### Operating System Version

MacOS Sequoia, latest

### Browser

Safari

**Comment by kennyqiyenkan** [comment]
+1 but for DropdownItem

**Comment by szbphoto** [comment]
Hello, please try adding as={Link} to it and it should work fine, then you can use the isExternal showAnchorIcon props too
You can see more here: [https://nextui.org/docs/components/link#polymorphic-component](url)


`import { Button, Link } from "@nextui-org/react";

export default function Page() {
  return (
    <div>
        <Button href="/" as={Link}>Go Home</Button>
    </div>
  );
}`

**Comment by wingkwong** [comment]
@partridgeworks @kennyqiyenkan can you guys share your package.json? a sandbox would be better.

**Comment by wingkwong** [comment]
@partridgeworks To supplement a bit on top of @szbphoto's answer. The Button component always represents a button semantically. To create a link that visually looks like a button, use the [Link](https://nextui.org/docs/components/link#polymorphic-component) component instead.

@kennyqiyenkan I tested it with the latest version and didn't reproduce. Please double check if you're using the latest version. If it's still reproducible, please create a new issue with a minimal reproducible environment. Thanks.
