### ISSUE TITLE
[BUG] - Docs sidebar elements should persist scroll position while navigating to another component

### ISSUE THREAD

**Issue by pushkarydv** [nextui-org/nextui#4347]
### NextUI Version

2.6.8

### Describe the bug

While reading the [docs](https://nextui.org/docs/components/input) if i scroll the sidebar to specific component and press it, on navigating to docs of another component it automatically scrolls sidebar to top.

Issue which arises due to this:
If i am reading / finding component needed i again and again scroll the sidebar to look the components preview.

### Your Example Website or App

https://nextui.org/docs/components/input

### Steps to Reproduce the Bug or Issue

1. Visit [https://nextui.org/docs/components/input](https://nextui.org/docs/components/input)
2. Scroll to Listbox in sidebar, and click
3. Now sidebar is at top, if you want to go to Modal or something else you are finding (hit and trial kind of search) you need to again scroll the sidebar to LIstbox first and then go on to others.

### Expected behavior

It shall persist position of sidebar while navigating, or scroll to that position after navigation completes

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
I couldn't reproduce the issue (also using Chrome). It did't scroll to the top after step 2. Can you provide a video?

**Comment by pushkarydv** [comment]
Just checked, someone fixed it today ✅
