### ISSUE TITLE
[BUG] - Switch [selected=true] doesnt work 

### ISSUE THREAD

**Issue by nickaris1** [nextui-org/nextui#4352]
### NextUI Version

2.2.5

### Describe the bug

when using custom class names, [selected=true] doesn't work for thumb slots, while if I remove the `=true` and leave it as [selected] it works

eg `group-data-[selected=true]:ml-8` doesn't works
`group-data-[selected]:ml-[33px]` works

### Steps to Reproduce the Bug or Issue

custom Switch
```
{
        base: twMerge(
          'ml-1 max-w-md bg-content1 hover:bg-content2 items-center',
          'rounded-lg gap-2 border-2 border-transparent',
          'data-[selected=true]:border-primary',
          base,
        ),
        wrapper: twMerge(
          'p-1 bg-white group-data-[selected=true]:bg-cxc-orange w-16 flex shadow-lg',
          wrapper,
          wrapperColor,
        ),
        thumb: twMerge(
          '!size-6 border-2 shadow-lg',
          'group-data-[hover=true]:border-primary',
          //selected
          'bg-cxc-gray group-data-[selected=true]:bg-white group-data-[selected=true]:ml-8',
          // pressed
          'group-data-[pressed=true]:w-7',
          'group-data-[selected=true]:group-data-[pressed=true]:ml-8',
          thumb,
        ),
      }
```
the code provided is based on [switch#custom-styles](https://nextui.org/docs/components/switch#custom-styles)

this happened after changing from `"@nextui-org/react": "^2.2.9"` to `"@nextui-org/switch": "^2.2.5"`

### Expected behavior

The thumb goes only to about ml-6 while I have a bigger wrapper

### Operating System Version

any

### Browser

Other (add additional context)

**Comment by stefnto** [comment]
Had the same error, use `group-data-[selected=true]:ms-8` instead. This probably happens because the tailwind class that comes with the component on the thumb slot 'group-data-[selected=true]:ms-5' has more specificity than yours. 
`group-data-[selected]:ml-[33px]` works because it has more specifity than the default rule used, so it overrides it. 
I would suggest structuring your tailwind rule the same way the default one is structured, since that way, because of tailwind variants, the default rule will not exist because you have provided one with the same structure.

**Comment by Peterl561** [comment]
Is it just being overwritten by `thumb`? Does it work if you move the args around? If not please provide a minimal, reproducible sandbox @nickaris1

**Comment by nickaris1** [comment]
> Had the same error, use `group-data-[selected=true]:ms-8` instead. This probably happens because the tailwind class that comes with the component on the thumb slot 'group-data-[selected=true]:ms-5' has more specificity than yours. `group-data-[selected]:ml-[33px]` works because it has more specifity than the default rule used, so it overrides it. I would suggest structuring your tailwind rule the same way the default one is structured, since that way, because of tailwind variants, the default rule will not exist because you have provided one with the same structure.

I should make that more specific. On the reproducible step is all you need to make it so it doesn't work. 
when I was in `dev`  which is refreshing the state on save, the margin did work on the thumb.

- thanks `group-data-[selected=true]:ms-8` works 
- the thing that worked for me is to change in the thumb slot the `[selected=true]:ml-8` to `[selected]:ml-8`

**Comment by nickaris1** [comment]
> Is it just being overwritten by `thumb`? Does it work if you move the args around? If not please provide a minimal, reproducible sandbox @nickaris1

[codesandbox](https://codesandbox.io/p/devbox/custom-switch-tmdwcd)

**Comment by Peterl561** [comment]
The custom styles example for `Switch` in the docs is using the wrong class. As @stefnto suggested, `ms` is the correct one to use. `ms`/`margin-inline-start` is used by default and should not be mixed with `ml`/`margin-left`.
