### ISSUE TITLE
[BUG] - [DateRangePicker] - Invalid prop `ref` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props. 

### ISSUE THREAD

**Issue by J4v4Scr1pt** [nextui-org/nextui#4358]
### NextUI Version

2.6.8

### Describe the bug

I'm upgrading my project to NextJs 15 and React 19, all works well so far but found an issue when using the DateRangePicker.

### Your Example Website or App

https://codesandbox.io/p/devbox/nk4vk2?file=%2Fapp%2Fpage.tsx%3A2%2C10-2%2C25

### Steps to Reproduce the Bug or Issue

Open the CodeSandbox and open  the DateRangePicker. There will be an error showing up.

### Expected behavior

To not have the error :)

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/bdc883fb-221a-4132-a46e-e67cd5a6500c)

### Operating System Version

Window 11

### Browser

Chrome

**Comment by shlyamster** [comment]
I have the same error

**Comment by wingkwong** [comment]
Currently it is only [compatible with react 19 rc](https://nextui.org/blog/v2.6.0#react-19-support--library-upgrades), since react-aria still hasn't supported react 19 yet.

**Comment by J4v4Scr1pt** [comment]
> Currently it is only [compatible with react 19 rc](https://nextui.org/blog/v2.6.0#react-19-support--library-upgrades), since react-aria still hasn't supported react 19 yet.

Ok, understand. Then we can keep track of it until they support LTS React. :)

**Comment by wingkwong** [comment]
seems not related to react 19. this sandbox https://codesandbox.io/p/devbox/friendly-diffie-55mxp5 can reproduce the error with react 18.
