### ISSUE TITLE
[BUG] - Label of Input of type File, never goes inside

### ISSUE THREAD

**Issue by templar-ajay** [nextui-org/nextui#4364]
### NextUI Version

14.2.15

### Describe the bug

The Input component property `labelPlacement="inside"` is not working as expected for with  property`type="file"`

Below is the code to reproduce the issue
```
<Input
                  startContent={
                    <>
                      <BookImage className="text-muted-foreground" size={18} />
                    </>
                  }
                  //   classNames={{
                  //     base: "!mt-0",
                  //     mainWrapper: "h-full pt-0",
                  //     inputWrapper: "pt-8 pb-2 h-full",
                  //     label: "mt-5 ml-3 text-xs",
                  //   }}
                  type="file"
                  accept="image/png, image/jpeg, image/jpg"
                  variant="flat"
                  label="Cover Image"
                  placeholder="Cover Image"
                  labelPlacement="inside"
                />
```

I have created a temporary fix for it. 
In the code above if we uncomment the classNames attribute the label appears inside the component as it should be when the `labelPlacement="inside"` is set on the Input Component

### Steps to Reproduce the Bug or Issue

```
<Input
                  startContent={
                    <>
                      <BookImage className="text-muted-foreground" size={18} />
                    </>
                  }
                  //   classNames={{
                  //     base: "!mt-0",
                  //     mainWrapper: "h-full pt-0",
                  //     inputWrapper: "pt-8 pb-2 h-full",
                  //     label: "mt-5 ml-3 text-xs",
                  //   }}
                  type="file"
                  accept="image/png, image/jpeg, image/jpg"
                  variant="flat"
                  label="Cover Image"
                  placeholder="Cover Image"
                  labelPlacement="inside"
                />
```

### Expected behavior

The Label should appear inside the Component when the Input component property `labelPlacement="inside"` is set with another property `type="file"`
It may work fine once when we change the input type from text to file but after reloading the web page, the label is placed outside the component.

### Screenshots or Videos

<img width="546" alt="Screenshot 2024-12-15 at 11 01 59 AM" src="https://github.com/user-attachments/assets/fd311da8-bdd5-4887-b430-8eb79df19223" />

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
From the source code, if the label placement is inside, it will throw `Input with file type doesn't support inside label. Converting to outside ...`. Not sure the reason tho. Need to check.

**Comment by templar-ajay** [comment]
> From the source code, if the label placement is inside, it will throw `Input with file type doesn't support inside label. Converting to outside ...`. Not sure the reason tho. Need to check.

Thank You for addressing the issue. I'm sure you can fix it 💪🏻
