### ISSUE TITLE
[BUG] - Unknown element <[object Object]> in collection. in v2.6.8

### ISSUE THREAD

**Issue by MeetBhingradiya** [nextui-org/nextui#4370]
### NextUI Version

2.6.8

### Describe the bug

I Wrtten Just a Example & Gets ERROR on Select Component

```tsx
  <Select
      className="max-w-xs"
      label="Favorite Animal"
      placeholder="Select an animal"
      selectionMode="multiple"
  >
      {animals.map((animal) => (
          <SelectItem key={animal.key}>{animal.label}</SelectItem>
      ))}
  </Select>
```

### Steps to Reproduce the Bug or Issue

Just Write this Example on A Component with Given Version !

### Expected behavior

Run As Expected Like in Docs but getting Errored

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/c6df72f7-cdbf-4d7c-9cea-09f477d6488a)

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment]
Have you used `use client` if you are using `Select` from `@nextui-org/react`?

**Comment by MeetBhingradiya** [comment]
yes i used `use client`

**Comment by wingkwong** [comment]
I couldn't reproduce the issue. Please provide a minimal reproducible environment.

**Comment by MeetBhingradiya** [comment]
Next js 15.0.1 App Router

**Comment by wingkwong** [comment]
That's not enough for us to debug. We don't know your configurations, dependencies and etc. That's why we asked for a minimal reproducible environment. It can be either a repo or a stackblitz project. Thanks.

**Comment by MeetBhingradiya** [comment]
Its Fixed when i Tryed to Delete All the Cache of Nextjs & install Dependencys again ✅
