### ISSUE TITLE
[BUG] - NavbarMenuToggle is not functioning correctly

### ISSUE THREAD

**Issue by amigoimmigration** [nextui-org/nextui#4393]
### NextUI Version

2.6.0

### Describe the bug

Issue: The NavbarMenuToggle component in the Next.js project is not functioning as expected. Clicking the toggle does not trigger the expected change in the visibility or state of the navigation menu.

Steps to Reproduce:

Navigate to the page with the Navbar component.
Click on the NavbarMenuToggle button.
The navigation menu does not open/close as expected.
Expected Behavior: When the NavbarMenuToggle button is clicked, the navigation menu should toggle its visibility (open or close).

Actual Behavior: Clicking the NavbarMenuToggle button does not alter the state of the navigation menu. The menu remains in its default state (either open or closed) despite clicking.

Possible Causes:

Issue with state management or event handling in the NavbarMenuToggle component.
CSS classes or styles not being updated properly.
Missing or incorrect integration with state management libraries or React hooks.

### Your Example Website or App

https://nextui.org/docs/components/navbar#navbarmenutoggle-props

### Steps to Reproduce the Bug or Issue

Not

### Expected behavior

not 

### Screenshots or Videos

Not 

### Operating System Version

all

### Browser

Chrome

**Comment by newguy123-creator** [comment]
Yes its the same issue as here:
https://github.com/nextui-org/nextui/issues/4345

Weridly, the Pro version of this works just fine. So not sure why would the Pro version work and the regualr one not...

**Comment by Develekko** [comment]
same here

**Comment by amigoimmigration** [comment]
how to fix any one

**Comment by wingkwong** [comment]
duplicate - will be tracked in https://github.com/nextui-org/nextui/issues/4345 instead.

**Comment by jt6677** [comment]
lol. NavbarMenuToggle does not appear properly, not even with  sm:hidden removed.  They are too busy making pro version they could not even make a basic nav bar properly.

**Comment by codekappal** [comment]
For me the issue was NavbarMenuToggle imported from "@heroui/react", importing using "@heroui/navbar" fixed the issue.
