### ISSUE TITLE
[BUG] - DropdownTrigger and PopoverTrigger pass onClick to Button causing console warning

### ISSUE THREAD

**Issue by notthatnathan** [nextui-org/nextui#4399]
### NextUI Version

2.6.8

### Describe the bug

`Button`'s `onClick` is deprecated but `DropdownTrigger` and maybe `PopoverTrigger` are passing an `onClick` prop to their one child, usually a `Button`. This causes the deprecation warning to be logged even though no direct `Button` instances are using `onClick`.

### Steps to Reproduce the Bug or Issue

1. Set up a dropdown with `Button` as trigger
2. Observe console

### Expected behavior

I expect no warnings.

### Screenshots or Videos

![CleanShot 2024-12-18 at 14 21 39@2x](https://github.com/user-attachments/assets/649e10ef-76f8-4a73-aee0-a398a9b0b6ef)

<img width="451" alt="image" src="https://github.com/user-attachments/assets/d9b29d37-3d2a-42d7-87a2-5e5087cc841e" />

Ignore the exact error, that's because the `warn` assumes `process` and Vite doesn't surface that. https://github.com/nextui-org/nextui/blob/afe0b527ce2dcd1f511b601fcba700fd2d12fcd6/packages/utilities/shared-utils/src/console.ts#L11

Stack shows error comes from deprecation check here: https://github.com/nextui-org/nextui/blob/afe0b527ce2dcd1f511b601fcba700fd2d12fcd6/packages/hooks/use-aria-button/src/index.ts#L108

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
For "process is not defined" issue, it has been fixed in canary and will be available in the next bug fix release.

To the original issue, another example would be using a polymorphic button. The `onClick` is passed from the Button component internally. We need to handle this case to avoid confusion (since users don't actually use onClick in their code).
