### ISSUE TITLE
[BUG] - Progress

### ISSUE THREAD

**Issue by lfraggioli-vulcan** [nextui-org/nextui#4400]
### NextUI Version

2.2.1

### Describe the bug

`$ npm i @nextui-org/progress
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: apollo@0.1.0
npm error Found: @nextui-org/system@2.2.1
npm error node_modules/@nextui-org/system
npm error   @nextui-org/system@"2.2.1" from @nextui-org/aria-utils@2.0.20
npm error   node_modules/@nextui-org/aria-utils
npm error     @nextui-org/aria-utils@"2.0.20" from @nextui-org/autocomplete@2.1.1
npm error     node_modules/@nextui-org/autocomplete
npm error       @nextui-org/autocomplete@"^2.1.1" from the root project
npm error     @nextui-org/aria-utils@"2.0.20" from @nextui-org/date-picker@2.1.1
npm error     node_modules/@nextui-org/date-picker
npm error       @nextui-org/date-picker@"^2.0.7" from the root project
npm error     4 more (@nextui-org/dropdown, @nextui-org/listbox, ...)
npm error   peer @nextui-org/system@">=2.0.0" from @nextui-org/autocomplete@2.1.1
npm error   node_modules/@nextui-org/autocomplete
npm error     @nextui-org/autocomplete@"^2.1.1" from the root project
npm error   40 more (@nextui-org/button, @nextui-org/avatar, ...)
npm error
npm error Could not resolve dependency:
npm error @nextui-org/progress@"*" from the root project
npm error
npm error Conflicting peer dependency: @nextui-org/system@2.4.4
npm error node_modules/@nextui-org/system
npm error   peer @nextui-org/system@">=2.4.0" from @nextui-org/progress@2.2.4
npm error   node_modules/@nextui-org/progress
npm error     @nextui-org/progress@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\lfraggioli\AppData\Local\npm-cache\_logs\2024-12-18T20_29_15_012Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\lfraggioli\AppData\Local\npm-cache\_logs\2024-12-18T20_29_15_012Z-debug-0.log

lfraggioli@NB0163 MINGW64 ~/OneDrive - Centaurus/Escritorio/Code/apollo (feature/SVT1249-LegajoDigitalLayout)
$ ^C

lfraggioli@NB0163 MINGW64 ~/OneDrive - Centaurus/Escritorio/Code/apollo (feature/SVT1249-LegajoDigitalLayout)
$ npx nextui-cli@latest add progress
Need to install the following packages:
nextui-cli@0.5.0
Ok to proceed? (y) y

NextUI CLI v0.5.0

✔ Components data updated successfully!

Adding required dependencies: @nextui-org/progress

npm install @nextui-org/progress
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: apollo@0.1.0
npm error Found: @nextui-org/system@2.2.1
npm error node_modules/@nextui-org/system
npm error   @nextui-org/system@"2.2.1" from @nextui-org/aria-utils@2.0.20
npm error   node_modules/@nextui-org/aria-utils
npm error     @nextui-org/aria-utils@"2.0.20" from @nextui-org/autocomplete@2.1.1
npm error     node_modules/@nextui-org/autocomplete
npm error       @nextui-org/autocomplete@"^2.1.1" from the root project
npm error     @nextui-org/aria-utils@"2.0.20" from @nextui-org/date-picker@2.1.1
npm error     node_modules/@nextui-org/date-picker
npm error       @nextui-org/date-picker@"^2.0.7" from the root project
npm error     4 more (@nextui-org/dropdown, @nextui-org/listbox, ...)
npm error   peer @nextui-org/system@">=2.0.0" from @nextui-org/autocomplete@2.1.1
npm error   node_modules/@nextui-org/autocomplete
npm error     @nextui-org/autocomplete@"^2.1.1" from the root project
npm error   40 more (@nextui-org/button, @nextui-org/avatar, ...)
npm error
npm error Could not resolve dependency:
npm error @nextui-org/progress@"*" from the root project
npm error
npm error Conflicting peer dependency: @nextui-org/system@2.4.4
npm error node_modules/@nextui-org/system
npm error   peer @nextui-org/system@">=2.4.0" from @nextui-org/progress@2.2.4
npm error   node_modules/@nextui-org/progress
npm error     @nextui-org/progress@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.`

### Steps to Reproduce the Bug or Issue

1. Go to terminal
2. npm i @nextui-org/progress

### Expected behavior

Unexpected error with this component, I often use NextUI components and it's the first time that happened to me.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by wingkwong** [comment]
I couldn't reproduce the issue (tried npm i and also nextui cli). Can you try removing your node_modules and do it again? also can you provide your package.json?

**Comment by lfraggioli-vulcan** [comment]
> I couldn't reproduce the issue (tried npm i and also nextui cli). Can you try removing your node_modules and do it again? also can you provide your package.json?

I already tried removing node_modules but the issue persists. Here is the package.json:

```
{
  "name": "apollo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3000 --turbo",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "prepare": "husky",
    "test": "jest",
    "test:watch": "jest --watchAll"
  },
  "dependencies": {
    "@aws-sdk/client-secrets-manager": "^3.632.0",
    "@emotion/is-prop-valid": "^1.3.0",
    "@emotion/react": "^11.13.0",
    "@emotion/styled": "^11.13.0",
    "@hookform/devtools": "^4.3.1",
    "@hookform/resolvers": "^3.9.0",
    "@internationalized/date": "^3.5.4",
    "@mui/icons-material": "^5.16.5",
    "@mui/material": "^5.16.5",
    "@nextui-org/autocomplete": "^2.1.1",
    "@nextui-org/avatar": "^2.0.27",
    "@nextui-org/breadcrumbs": "^2.0.7",
    "@nextui-org/button": "^2.0.37",
    "@nextui-org/card": "^2.0.30",
    "@nextui-org/checkbox": "^2.0.29",
    "@nextui-org/chip": "^2.0.29",
    "@nextui-org/date-picker": "^2.0.7",
    "@nextui-org/divider": "^2.0.28",
    "@nextui-org/dropdown": "^2.1.23",
    "@nextui-org/input": "^2.1.21",
    "@nextui-org/kbd": "^2.0.28",
    "@nextui-org/link": "^2.0.29",
    "@nextui-org/listbox": "^2.1.21",
    "@nextui-org/modal": "^2.0.33",
    "@nextui-org/navbar": "^2.0.30",
    "@nextui-org/pagination": "^2.0.30",
    "@nextui-org/radio": "^2.0.28",
    "@nextui-org/select": "^2.2.5",
    "@nextui-org/skeleton": "^2.0.31",
    "@nextui-org/spinner": "^2.0.33",
    "@nextui-org/switch": "^2.0.33",
    "@nextui-org/system": "^2.1.2",
    "@nextui-org/table": "^2.0.33",
    "@nextui-org/tabs": "^2.0.37",
    "@nextui-org/theme": "^2.2.3",
    "@nextui-org/tooltip": "^2.0.39",
    "@nextui-org/use-infinite-scroll": "^2.1.5",
    "@nextui-org/user": "^2.0.28",
    "@react-stately/data": "^3.11.4",
    "date-fns": "^3.6.0",
    "dayjs": "^1.11.13",
    "dayjs-plugin-utc": "^0.1.2",
    "deep-equal": "^2.2.3",
    "echarts": "^5.5.1",
    "echarts-for-react": "^3.0.2",
    "eslint-plugin-jest-dom": "^5.4.0",
    "eslint-plugin-testing-library": "^6.2.2",
    "framer-motion": "^11.1.8",
    "http-proxy-middleware": "^3.0.0",
    "jwt-decode": "^4.0.0",
    "ms": "^2.1.3",
    "negotiator": "^0.6.3",
    "next": "14.2.3",
    "next-intl": "^3.17.2",
    "next-themes": "^0.3.0",
    "pretty-quick": "^4.0.0",
    "qs": "^6.13.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.53.0",
    "react-hotkeys-hook": "^4.5.0",
    "react-toastify": "^10.0.5",
    "react-use-measure": "^2.1.1",
    "redis": "^4.7.0",
    "swr": "^2.2.5",
    "ts-jest": "^29.1.2",
    "zod": "^3.23.7",
    "zod-form-data": "^2.0.2"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^6.4.5",
    "@testing-library/react": "^15.0.7",
    "@types/deep-equal": "^1.0.4",
    "@types/jest": "^29.5.12",
    "@types/ms": "^0.7.34",
    "@types/negotiator": "^0.6.3",
    "@types/node": "^20",
    "@types/node-cron": "^3.0.11",
    "@types/qs": "^6.9.15",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.3",
    "eslint-plugin-unused-imports": "^4.1.3",
    "husky": "^9.0.11",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "postcss": "^8",
    "prettier": "^3.3.3",
    "tailwindcss": "^3.4.1",
    "ts-node": "^10.9.2",
    "typescript": "^5"
  }
}
```

**Comment by wingkwong** [comment]
I think the reason is you are trying to add the latest progress component while this requires `@nextui-org/system@>=2.4.0`. and from your package.json you are still using an outdated version of `@nextui-org/system`. Therefore, can you try bump all `@nextui-org/*` to latest version and try again?

**Comment by lfraggioli-vulcan** [comment]
it worked! thank you.
