### ISSUE TITLE
Error in Documentation for _document.tsx

### ISSUE THREAD

**Issue by anoushk1234** [nextui-org/nextui#441]
### Describe the bug

heres the code from the docs
```tsx
import Document, {
  Html,
  Head,
  Main,
  NextScript,
  DocumentContext,
  DocumentInitialProps,
} from "next/document";
import { CssBaseline } from "@nextui-org/react";
import { ReactElement } from "react";

class MyDocument extends Document {
  static async getInitialProps(
    ctx: DocumentContext
  ): Promise<DocumentInitialProps> {
    const initialProps = await Document.getInitialProps(ctx);
    return {
      ...initialProps,
      styles: <>{initialProps.styles}</>,
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>{CssBaseline.flush()}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```
i get a type error at this line `styles: <>{initialProps.styles}</>,` saying `Type 'Element' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>[] | ReactFragment | undefined'`

if i remove the <> </> it doesnt show a type error and it works

### Steps to Reproduce the Bug or Issue

Follow the nextjs guide in the docs https://nextui.org/docs/guide/getting-started#nextjs

### Expected behavior

the documentation should have the correct code

### Operating System Version

macOS

### Browser

Firefox

**Comment by anoushk1234** [comment]
> Hey @anoushk1234 I don't think it's a issue with NextUI.
> 
> My solution is to use [`React.Children.toArray`](https://reactjs.org/docs/react-api.html#reactchildrentoarray) I'm not sure if there's a better way.
> 
> Reference: [vercel/next.js#36008 (comment)](https://github.com/vercel/next.js/issues/36008#issuecomment-1096423122)
> 
> Example: [https://codesandbox.io/s/next-ui-ts-bf0t1z](https://codesandbox.io/s/next-ui-ts-bf0t1z?file=/pages/_document.tsx)
> 
> ```tsx
> import { Children } from "react";
> import { CssBaseline } from "@nextui-org/react";
> import Document, { Html, Main, Head, NextScript } from "next/document";
> 
> const MyDocument = () => {
>   return (
>     <Html>
>       <Head>{CssBaseline.flush()}</Head>
>       <body>
>         <Main />
>         <NextScript />
>       </body>
>     </Html>
>   );
> };
> 
> 
> MyDocument.getInitialProps = async (context) => {
>   const initialProps = await Document.getInitialProps(context);
> 
>   return {
>     ...initialProps,
>     styles: [ ...Children.toArray(initialProps.styles) ]
>   };
> };
> ```

hey, if it's not an issue with the defined types then the documentation needs to be update because `styles: <>{initialProps.styles}</>,` doesn't work

**Comment by jrgarciadev** [comment]
Hey @anoushk1234 could you please share with us your `tsconfig.json`?

**Comment by anoushk1234** [comment]
> Hey @anoushk1234 could you please share with us your `tsconfig.json`?

Yes sure, here you go https://github.com/anoushk1234/anoushk.xyz/blob/main/tsconfig.json

**Comment by NayamAmarshe** [comment]
Here's how I fixed it:
```
import Document, { Html, Head, Main, NextScript } from "next/document";
import { CssBaseline } from "@nextui-org/react";

class MyDocument extends Document {
  static async getInitialProps(ctx: any) {
    const initialProps = await Document.getInitialProps(ctx);
    return {
      ...initialProps,
      styles: [<>{initialProps.styles}</>],
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>{CssBaseline.flush()}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;

```

**Comment by anoushk1234** [comment]
> Here's how I fixed it:
> 
> ```ts
> import Document, { Html, Head, Main, NextScript } from "next/document";
> import { CssBaseline } from "@nextui-org/react";
> 
> class MyDocument extends Document {
>   static async getInitialProps(ctx: any) {
>     const initialProps = await Document.getInitialProps(ctx);
>     return {
>       ...initialProps,
>       styles: [<>{initialProps.styles}</>],
>     };
>   }
> 
>   render() {
>     return (
>       <Html lang="en">
>         <Head>{CssBaseline.flush()}</Head>
>         <body>
>           <Main />
>           <NextScript />
>         </body>
>       </Html>
>     );
>   }
> }
> 
> export default MyDocument;
> ```

ohk got it, I'll update the docs with this code

**Comment by marcoripa96** [comment]
This doesn't work for me. React throws a warning for duplicate keys when using an array. I'm ignore ts typechecking at the moment.
