### ISSUE TITLE
[BUG] - Table

### ISSUE THREAD

**Issue by ShahinAlomShuvo** [nextui-org/nextui#4418]
### NextUI Version

v2.6.8

### Describe the bug

when table  selectionMode="multiple" then face error

### Steps to Reproduce the Bug or Issue

just create a simple table component from the next UI & send props selection mode multiple, then the error is occurs

### Expected behavior

expected see checkbox for se;ect multiple items

### Operating System Version

Linux voyeger

### Browser

Chrome

**Comment by wingkwong** [comment]
Couldn't reproduce. Please provide more details. A minimal reproducible sandbox is preferred.

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/4385
