### ISSUE TITLE
Upgrading to the Latest Version Causes Missing Modal Styles

### ISSUE THREAD

**Issue by Pzx1997** [nextui-org/nextui#4419]
### NextUI Version

2.6.8

### Describe the bug

 My project was originally on version 2.4.0. After attempting to upgrade to the latest version, I noticed that the modal's close icon has moved to the left side. Upon inspecting the styles, I found that the "end-1" style is missing. Further investigation revealed that many new CSS styles are absent in the updated version. Please help me resolve this.

### Steps to Reproduce the Bug or Issue

@nextui-org/react@2.4.0 update to @nextui-org/react@2.6.8

### Expected behavior

The CSS styles should display correctly.

### Screenshots or Videos

<img width="963" alt="image" src="https://github.com/user-attachments/assets/9073a381-b8de-4458-a080-9c4fb0fe4ae2" />

<img width="693" alt="image" src="https://github.com/user-attachments/assets/ce64abc4-dd8f-4255-acb6-474624bff559" />

<img width="473" alt="image" src="https://github.com/user-attachments/assets/9c600425-8214-4006-abb7-b8d7970c9a0f" />

### Operating System Version

macOs

### Browser

Chrome

**Comment by uigywnkiub** [comment]
+1, also many many errors with Select and etc...

**Comment by wingkwong** [comment]
not able to reproduce. please provide a minimal reproducible environment.

![image](https://github.com/user-attachments/assets/a58c4484-e95e-4ca8-bff0-0eeeda76498b)

**Comment by jrgarciadev** [comment]
> +1, also many many errors with Select and etc... my prod is destroyed. Every version get many breaking changes and issues. Something you do not right. @Pzx1997 @jrgarciadev

We test every minor version as thoroughly as possible (including almost 700 unit tests), first releasing `beta` and then `canary` versions that many users try on their projects to help ensure a smooth production release. 

We even use these versions ourselves, as well as the production release, on https://frontio.ai/, and we haven’t experienced any breaking changes. It would be helpful if you could provide specific examples of the issues you’re encountering, so we can better understand and address them

**Comment by Pzx1997** [comment]
> not able to reproduce. please provide a minimal reproducible environment.
> 
> ![image](https://private-user-images.githubusercontent.com/35857179/397922805-a58c4484-e95e-4ca8-bff0-0eeeda76498b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MjcyMzgsIm5iZiI6MTczNDkyNjkzOCwicGF0aCI6Ii8zNTg1NzE3OS8zOTc5MjI4MDUtYTU4YzQ0ODQtZTk1ZS00Y2E4LWJmZjAtMGVlZWRhNzY0OThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA0MDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYWI5MTQ5YTgyYWY1NGEwMDU4NDI1MzIzMTBiZTdlZWU1NmU1ZDk0OWU4YTIzNmFhNWNiYjRjMGE0MmYxMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BopOTxjTs3AgxNSehs94I5wulGKGiRw3LInPpSP85H0)

Thank you for your reply. After further investigation, I found the issue was that the package @nextui-org/theme was installed separately in the project, while I had only updated @nextui-org/react. After I tried updating the @nextui-org/theme package to be in sync, I found that it worked normally.
