### ISSUE TITLE
[BUG] - Responsive Sidebar Vertical Scroll Bar Issues

### ISSUE THREAD

**Issue by SeeRich** [nextui-org/nextui#4422]
### NextUI Version

2.6.8

### Describe the bug

The vertical scroll bar inside the side bar component (NextUi Pro version) never shows up even though the width of the sidebar separator seems to be the width when a scroll bar is present?

I renamed some of the files from the sidebar component `Sidebar.tsx` -> `NextUiSidebar.tsx`, `SidebarDrawer.tsx` -> `NextUiSidebarDrawer.tsx` -> `App.tsx` -> `Sidebar.tsx`

I noticed that I can get the wide scroll bar to go away if I remove the `overflow-y-scroll` on line 100 in `NextUiSidebarDrawer.tsx` but this still doesn't actually scroll when the content overflows like desired.

### Your Example Website or App

https://github.com/SeeRich/web-template

### Steps to Reproduce the Bug or Issue

```
npm install --legacy-peer-deps
npm run dev
```

### Expected behavior

I would expect the width of the sidebar component separator to be much smaller when not actually scrolling. Also, when the content overflows, there should actually be a scroll bar.

### Screenshots or Videos

Appologize for the terrible quality, still can't figure out screen recording...

https://github.com/user-attachments/assets/a506f9ad-30d4-44c0-8ae2-9cde8daaadb0

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
For nextui-pro issue, please discuss in NextUI Pro channel (ping me in discord if you don't have the access) and don't create a public repo. You can set it private and invite our team member to investigate.
