### ISSUE TITLE
[BUG] - GETTİNG ERROR WHEN ADDİNG InputOTP

### ISSUE THREAD

**Issue by Abdullah05-js** [nextui-org/nextui#4424]
### NextUI Version

"@nextui-org/react": "^2.6.8"

### Describe the bug

am getting this error 

my version:"@nextui-org/react": "^2.6.8",

PS C:\Users\abdal\Desktop\Website\Frontend> npx nextui-cli@latest add input-otp

NextUI CLI v0.5.0

Adding required dependencies: @nextui-org/input-otp

npm install @nextui-org/input-otp
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: website@0.1.0
npm error Found: @nextui-org/system@2.2.2
npm error node_modules/@nextui-org/system
npm error   @nextui-org/system@"2.2.2" from @nextui-org/aria-utils@2.0.21
npm error   node_modules/@nextui-org/aria-utils
npm error     @nextui-org/aria-utils@"2.0.21" from @nextui-org/popover@2.1.24
npm error     node_modules/@nextui-org/popover
npm error       @nextui-org/popover@"^2.1.24" from the root project
npm error   peer @nextui-org/system@">=2.0.0" from @nextui-org/avatar@2.0.30
npm error   node_modules/@nextui-org/avatar
npm error     @nextui-org/avatar@"2.0.30" from @nextui-org/user@2.0.31
npm error     node_modules/@nextui-org/user
npm error       @nextui-org/user@"^2.0.31" from the root project
npm error     @nextui-org/avatar@"^2.0.30" from the root project
npm error   17 more (@nextui-org/badge, @nextui-org/button, ...)
npm error
npm error Could not resolve dependency:
npm error @nextui-org/input-otp@"*" from the root project
npm error
npm error Conflicting peer dependency: @nextui-org/system@2.4.4
npm error node_modules/@nextui-org/system
npm error   peer @nextui-org/system@">=2.4.0" from @nextui-org/input-otp@2.1.6
npm error   node_modules/@nextui-org/input-otp
npm error     @nextui-org/input-otp@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\abdal\AppData\Local\npm-cache\_logs\2024-12-21T18_40_42_159Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\abdal\AppData\Local\npm-cache\_logs\2024-12-21T18_40_42_159Z-debug-0.log

Unexpected error. Please report it as a bug:
Error: Command failed: npm install @nextui-org/input-otp
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at file:///C:/Users/abdal/AppData/Local/npm-cache/_npx/8a2bbc96f792a803/node_modules/nextui-cli/dist/index.js:37:259
    at new Promise (<anonymous>)
    at xe (file:///C:/Users/abdal/AppData/Local/npm-cache/_npx/8a2bbc96f792a803/node_modules/nextui-cli/dist/index.js:37:137)
    at mt (file:///C:/Users/abdal/AppData/Local/npm-cache/_npx/8a2bbc96f792a803/node_modules/nextui-cli/dist/index.js:37:470)
    at Command.vn (file:///C:/Users/abdal/AppData/Local/npm-cache/_npx/8a2bbc96f792a803/node_modules/nextui-cli/dist/index.js:76:1501)
    at async Command.parseAsync (C:\Users\abdal\AppData\Local\npm-cache\_npx\8a2bbc96f792a803\node_modules\commander\lib\command.js:935:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18884,
  stdout: null,
  stderr: null
}

### Your Example Website or App

https://github.com/Abdullah05-js/KOU.COM.TR

### Steps to Reproduce the Bug or Issue

null

### Expected behavior

null

### Screenshots or Videos

null

### Operating System Version

Windows

### Browser

Chrome

**Comment by Abdullah05-js** [comment]
to fix this bug use npm i @nextui-org/system

**Comment by winchesHe** [comment]
The latest nextui-cli version will handle this case
