### ISSUE TITLE
[BUG] - Input don't add defaultValue in uncontrolled Input after form submit

### ISSUE THREAD

**Issue by J4v4Scr1pt** [nextui-org/nextui#4431]
### NextUI Version

2.6.8

### Describe the bug

After submitting an form and there are validation errors the response will put back input value using defaultValue prop.
Following this [video](https://youtu.be/KhO4VjaYSXU?t=434).
When using NextUI Input component it clears no matter what. 
Using native input it works (or shadcn/ui as in video).

### Your Example Website or App

https://codesandbox.io/p/devbox/nk4vk2

### Steps to Reproduce the Bug or Issue

Start the project and test both the inputs

### Expected behavior

That the default value to be set as with the native input

### Operating System Version

Window 11

### Browser

Chrome

**Comment by Peterl561** [comment]
A form reset happens when the form `action` property is used in this way. If you want to keep this form reset behavior, then this is an issue with RAC (see adobe/react-spectrum#6830). For potential ways to opt-out of the reset and still use React 19 hooks, see the discussion of the [root issue](https://www.github.com/facebook/react/issues/29034).

**Comment by J4v4Scr1pt** [comment]
> A form reset happens when the form `action` property is used in this way. If you want to keep this form reset behavior, then this is an issue with RAC (see [adobe/react-spectrum#6830](https://github.com/adobe/react-spectrum/issues/6830)). For potential ways to opt-out of the reset and still use React 19 hooks, see the discussion of the [root issue](https://www.github.com/facebook/react/issues/29034).

Thanks for pointing me in the right direction ✌️. Not a big fan of the workarround tough, using onSubmit over action. 

Thanks again!

Happy holidays 🎅🎆!

**Comment by obouchari** [comment]
> A form reset happens when the form `action` property is used in this way. If you want to keep this form reset behavior, then this is an issue with RAC (see [adobe/react-spectrum#6830](https://github.com/adobe/react-spectrum/issues/6830)). For potential ways to opt-out of the reset and still use React 19 hooks, see the discussion of the [root issue](https://www.github.com/facebook/react/issues/29034).

Can't we use input's defaultValue to set value from state when validation fails on server?

```action.ts
return {
    success: false,
    inputs: values
}
```

```form.tsx
<Input defaultValue={state.inputs?.email ?? ""} />
```
