### ISSUE TITLE
[BUG] - onPress not working for button inside Popover

### ISSUE THREAD

**Issue by slatqh** [nextui-org/nextui#4446]
### NextUI Version

2.6.8

### Describe the bug

```
<Popover placement='top'>
        <PopoverTrigger>
          <Button onPress={() => console.log('THIS IS NOT EXECUTED')}>Open Popover</Button>
        </PopoverTrigger>
        <PopoverContent>
          <div className='px-1 py-2'>
            <div className='text-small font-bold'>Popover Content</div>
            <div className='text-tiny'>This is the popover content</div>
          </div>
        </PopoverContent>
      </Popover>
```

      
      Button onPress not working.
      Was working in prev version.
      Next.js 14.2.18

### Steps to Reproduce the Bug or Issue

described in my example.

### Expected behavior

onPress should trigger function 

### Operating System Version

macbook

### Browser

Chrome

**Comment by wingkwong** [comment]
https://react-spectrum.adobe.com/react-aria/usePress.html

> By default, press events stop propagation to parent elements. In cases where a handler decides not to handle a specific event, it can call continuePropagation() to allow a parent to handle it.

You can see what you can do [here](https://github.com/nextui-org/nextui/issues/4059#issuecomment-2499693544).
