### ISSUE TITLE
[BUG] - Typo in forms example

### ISSUE THREAD

**Issue by koolauri** [nextui-org/nextui#4464]
### NextUI Version

2.6.10

### Describe the bug

In your first example code block in Guide and Forms there is w-full written two times in form classname.

![image](https://github.com/user-attachments/assets/0323924e-00a5-4139-ab15-ca6c3d1fe801)

### Steps to Reproduce the Bug or Issue

1. Go to Guide on Docs
2. Go to Forms
3. On first example go to code

### Expected behavior

Just typo

### Operating System Version

Windows

### Browser

Chrome

**Comment by MarufSharifi** [comment]
Hi @wingkwong, i am interested in this issue, could you please assign it to me?

**Comment by wingkwong** [comment]
already fixed.
