### ISSUE TITLE
[BUG] - Alert description not optional

### ISSUE THREAD

**Issue by coratgerl** [nextui-org/nextui#4467]
### NextUI Version

2.6.10

### Describe the bug

In 2.6.8, the description field for Alert was optional, this not the case now, but every alert should not necessary have a description. Moreover the documentation propose some examples without description:

https://nextui.org/docs/components/alert#colors

### Steps to Reproduce the Bug or Issue

```ts
<Alert
          title="Title"
          color="danger"
          variant="bordered"
        />
```
=> Typescript error

### Expected behavior

The description should not be required

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
fixed in https://github.com/nextui-org/nextui/pull/4447. please wait for the next release.
