### ISSUE TITLE
[BUG] - Event Click on screens (sm or md) does not work 

### ISSUE THREAD

**Issue by fabjiro** [nextui-org/nextui#4469]
### NextUI Version

2.6.X

### Describe the bug

Hi NextUi team,i found a bug. It is in the onClick event of any html element, that is to say when you click on any html element you don't hear the onClick event.

This only happens in sm, md screens (only in these sizes I have tested them).

Note: I read the documentation thinking that the installation method had been changed, but it seems to be ok.

- In this video we can see in the case of version 2.4.6 that the onClick event works on screens (sm or md).

https://github.com/user-attachments/assets/74055105-36dd-44f8-90de-88b8f7ea2893

- And in this video we can see that version 2.6.10 the onClick event on screens (sm or md) no longer works

https://github.com/user-attachments/assets/8534f6bf-0ac5-4f30-a010-f42d35532815

### Steps to Reproduce the Bug or Issue

-Open the developer tools
-Adapt dimensions to a device (sm or md)
-Click on any Onclick event and it is not fired

### Expected behavior

onClick events should work on sm or md screens. 

### Operating System Version

- OS [Linux, Windows, Android]

### Browser

Chrome

**Comment by wingkwong** [comment]
you need to use `onPress`. See https://github.com/nextui-org/nextui/issues/4292#issuecomment-2532881764
