### ISSUE TITLE
[BUG] - property length required when creating a component with styled

### ISSUE THREAD

**Issue by marcoripa96** [nextui-org/nextui#453]
### Describe the bug

I setup a clean nextjs typescript project, installed nextUI and imported styled to create a styled component following Stitches documentation.
For some reason the object which contains the styles requires a length property and typescript isn't happy.

### Your Example Website or App

https://github.com/marcoripa96/next-nextui-trpc-starter

### Steps to Reproduce the Bug or Issue

1. Create a nextjs typescript from their documentation starter
2. install nextUI
3. import styled and create a component

### Expected behavior

Styled object should not require any object specific properties like length.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/48448387/166807119-053b725d-0f10-4759-8f79-f23be4cfc8af.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @marcoripa96 this issue has been reported before #291 , here's a workaround https://github.com/nextui-org/nextui/issues/291#issuecomment-1064031921, we already fixed this but it's pending to be released

Hope it helps!
