### ISSUE TITLE
[BUG] - Unblured Help menu bar on Firefox (mobile and desktop)

### ISSUE THREAD

**Issue by behrouze** [nextui-org/nextui#456]
### Describe the bug

On mobile devices, when browsing with Firefox Mobile, the blur effect applied to the menu `backdrop-filter: saturate(180%)blur(10px);` does not work.

Maybe could you apply a [CSS filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) instead `filter: blur(10px);` that [work on all browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/filter#browser_compatibility).

Thanks 🙏

### Steps to Reproduce the Bug or Issue

1. open https://nextui.org/docs/guide/getting-started on Firefox Andoid
2. open the lateral menu

### Expected behavior

The menu background should be blured

### Screenshots or Videos

![NextUI unblured menu on Firefox](https://user-images.githubusercontent.com/9475977/166945520-855ddb75-0e31-47b2-b55f-afaff59f0d11.png)

### Operating System Version

Android

### Browser

Firefox

**Comment by MR-AliHaashemi** [comment]
As *Next Ui* is created with `stitches`, It would be great to use the `@supports` rule ( like [this](https://stitches.dev/docs/styling#supports-rule) ).

It could be just a transparent (like `a:0.8`?) background, and if the browser supports the `backdrop-filter: blur`, then enabling the blur effect and changing the background transparency.

Sadly, I can't do it myself as I'm a newbie, but I just wanted to give some reference 😅
