### ISSUE TITLE
Popover component

### ISSUE THREAD

**Issue by abhay44** [nextui-org/nextui#46]
I think it will be a good addition to the current set of components
Reference: https://react-bootstrap.github.io/components/overlays/#popovers

**Comment by ibrahimtelman** [comment]
I think the Tooltip component can be used for this purpose. Tooltip components support custom triggers and custom content. 

- https://nextui.org/docs/components/tooltip#custom-content
- https://nextui.org/docs/components/tooltip#trigger

**Comment by jrgarciadev** [comment]
Hi, @abhay44 as @ibrahimtelman said you can use the `Tooltip` component for this purpose
