### ISSUE TITLE
More Loading Types

### ISSUE THREAD

**Issue by I-am-abdulazeez** [nextui-org/nextui#47]
Hi sir, Nice work.

Since Inspiration was drawn from [Vuesax](https://vuesax.com/docs/components/Loading.html#type), i would love to add more loading types [i.e more loading designs]

**Comment by jrgarciadev** [comment]
Hi, @I-am-abdulazeez thanks for your recommendation but for now we are only focused on coming out components and fix issues then we will consider adding new loading types 👍🏻
