### ISSUE TITLE
[BUG] - Components/Popover

### ISSUE THREAD

**Issue by mattmanik** [nextui-org/nextui#481]
### Describe the bug

Hello !
 I'm getting an undefined error for Popover.Trigger and Popover.Content , a new release from NextUI I think. 

### Steps to Reproduce the Bug or Issue

1. Use the popover component below 

    <Popover>
      <Popover.Trigger>
        <Button auto flat>Open Popover</Button>
      </Popover.Trigger>
      <Popover.Content>
        <Text css={{ p: "$10" }}>This is the content of the popover.</Text>
      </Popover.Content>
    </Popover>

### Expected behavior

Expected the popover button to trigger

### Operating System Version

Windows 10

### Browser

Edge

**Comment by jrgarciadev** [comment]
Hey @mattmanik could you please provide a Codesanbox?

**Comment by cdjbm** [comment]
I have the same issue, i cant import the component, display this message **Module '"@nextui-org/react"' has no exported member 'Popover'** I have the last version of NextUI

**Comment by jrgarciadev** [comment]
Hey @cdjbm here's a fully working Codesandbox https://codesandbox.io/s/nextui-popover-bjozgx?file=/App.js (using the NextUI lastest version)

**Comment by mattmanik** [comment]
Apologies for not informing this. I got my issue resolved after uninstalling Next UI and reinstalling it.
