### ISSUE TITLE
[BUG] - Components/Table

### ISSUE THREAD

**Issue by Yan-Zhelanov** [nextui-org/nextui#488]
### Describe the bug

The table is re-rendered every time the mouse and keyboard are clicked. If you click sequentially first on the left mouse button, then on any button on the keyboard, the table will be rendered as a result 2 extra times. This is the sequence in which it works.

### Your Example Website or App

https://codesandbox.io/s/zbgfe2?file=/App.js:0-1209&from-sandpack=true

### Steps to Reproduce the Bug or Issue

1. Open sandbox
2. Activate flag in Profiler "Highlight updates when components render."
3. Click the left mouse button anywhere.
4. Table rerendered.
5. Press any key on the keyboard.
6. Table rerendered again!
7. Repeat this as many times as you want and the table will be rerendered all the time.

### Expected behavior

The table should not be re-rendered by pressing the keyboard and mouse.

### Screenshots or Videos

![Screenshot_20220525_152510](https://user-images.githubusercontent.com/78805363/170261391-3a8334b5-1c40-4a47-ab41-dbf0fc94d645.png)
![Screenshot_20220525_152605](https://user-images.githubusercontent.com/78805363/170261526-f26e21c7-7b05-40d8-8e86-440351a180a9.png)

### Operating System Version

Linux

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Yan-Zhelanov I couldn't see any `re-render` on  mouse hover, right/left click or pressing any keyboard key

https://user-images.githubusercontent.com/30373425/187081211-c899024b-dd62-47e2-8b34-3c195481c9f7.mov

**Comment by whalemare** [comment]
@jrgarciadev how did you solve this issue?

**Comment by jimmailcamp** [comment]
Using the exact example in the nextui website. I can not get Topcontent to not rerender everytime I click anywhere in the table.
Im trying to implement the searchInput in topContent. Impossible! Even with correct memoization and callbacks
