### ISSUE TITLE
[BUG] - Button Not Working With Next.js Link Component on Andorid(brave browser)

### ISSUE THREAD

**Issue by jstbyte** [nextui-org/nextui#490]
### Describe the bug

TypeError: Cannot read property 'nodeName' of undefined.

### Steps to Reproduce the Bug or Issue

    <Link href='/test'>
          <Button
            as='a'
            auto
            size='sm'
            shadow
            css={{ marginTop: '$12' }}
            onClick={() => ''}
          >
            Test Page
          </Button>
        </Link>

### Expected behavior

Expected behavior is navigate to spacified page but i'm getting error:
TypeError: Cannot read property 'nodeName' of undefined.

### Operating System Version

windows 10

### Browser

Chrome

**Comment by smartercow** [comment]
@jrgarciadev I also have the same problem with. If I wrap Button with Link from Next I get the same error. Link and Button works on their own.

**Comment by jrgarciadev** [comment]
Hey @smartercow, @jstbyte could you try this way?: 

```tsx
      <Button
        auto
        shadow
        as={Link}
        size='sm'
        href="/test"
        css={{ marginTop: '$12' }}
        onPress={() => console.log('pressed')}
      >
       <a>
           Test Page
        </a>
      </Button>
    </Link>
```

**Comment by creazy231** [comment]
The above example results in `Error: Multiple children were passed to <Link> with `href` of `/register` but only one child is supported`. Facing the same issue for all links I want to display as buttons.

**Comment by BenSwitzerHavas** [comment]
Hi @jrgarciadev,

I too am getting the same issues as @jstbyte and @creazy231.

I've tried the following: 

```
import Link from 'next/link';
import { Button } from '@nextui-org/react';

<Link href='/test'>
<Button as='a'>
    Test Page
</Button>
</Link>
```
See the following error: _TypeError: Cannot read properties of undefined (reading 'nodeName')_

**and** 

```
import Link from 'next/link';
import { Button } from '@nextui-org/react';

<Button
  as={Link}
  href="/test"
>
 <a>
     Test Page
  </a>
</Button>
```

See the following error: Error: _Multiple children were passed to <Link> with `href` of `some-url` but only one child is supported_ 

My package.json contains the following:
    "@nextui-org/react": "*",
    "next": "12.3.1",
    "react": "18.2.0",
    "react-dom": "18.2.0"

**Comment by leogilmour** [comment]
```
import { Button, Link } from "@nextui-org/react";
import { default as NextLink } from "next/link";

<NextLink href={href} passHref>
      <Button
        as={Link}
      >
        Sign in
      </Button>
    </NextLink>
   ```
results in: _TypeError: Cannot read properties of undefined (reading 'nodeName')_ briefly flashing before navigating. I think the flash only occurs on first navigation from a new page.

```"@nextui-org/react": "*", ("1.0.0-beta.10",)
"next": "12.2.5",
"react": "18.2.0",
"react-dom": "18.2.0",```

**Comment by rolznz** [comment]
The above isn't just on Android, it's on Windows Chrome too.

This is a common usecase (button that opens a link).

**Comment by rolznz** [comment]
It looks like as a temporary fix you can do: (note e?. required for clicking the button again after navigating back, it seems like the event is not always available)

```
import { Button, Link } from "@nextui-org/react";
import { default as NextLink } from "next/link";
<NextLink href={Routes.withdraw} passHref>
  <Button as="a"onClick={(e) => { e?.preventDefault();}}>
    Test
  </Button>
</NextLink>
```

**Comment by gBoole01** [comment]
Issue is stale but for anyone that couldn't apply the workaround of @rolznz, here is mine.

If the Link is internal we can just attach a callback function on the onPress event with the router from next/router like this

```
import { useRouter } from 'next/router'

const router = useRouter()

<Button onPress={() => router.push('/some-route')}>
          Dummy button
</Button>
```

Hope this helps !

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).

**Comment by menesyurtlu** [comment]
Why don't you use just like this?
```
<Button as="a" href="/to/link">
Click me!
</Button>
```
