### ISSUE TITLE
[Feature Request] Add Tooltip prop to disable focus

### ISSUE THREAD

**Issue by TechnologicNick** [nextui-org/nextui#494]
### Is your feature request related to a problem? Please describe.

I made a table that has buttons wrapped in tooltips, just like in the [custom cells example](https://nextui.org/docs/components/table#custom-cells). When navigating to the buttons using the keyboard, the tooltip `<div>` is focussed instead. To navigate to the button, an additional keypress is required.

### Describe the solution you'd like

As a user, I expected the button to be selected, but the tooltip element is selected instead.

Ideal steps I would like to see:
1. Navigate to the desired row.
2. Navigate to the desired button, without the Tooltip's `<button>` element receiving focus first.

### Describe alternatives you've considered

Currently, I'm passing the `disabled` prop to the Tooltip. This changes the behaviour exactly to what I want. The Tooltip's button is taken out of the Accessibility Tree and the child buttons are still focusable.

Using the `disabled` prop is not ideal, because this suggests the Tooltip will not show when hovered, even though it does. The `disabled` prop is also not in the Tooltip's Props type, causing Typescript to mark it as an error, even though it's actually passed to the Tooltip's `<button>` element.

### Screenshots or Videos

Current tooltip focus behaviour:
![Current tooltip focus behaviour](https://user-images.githubusercontent.com/20935774/170592741-51ca11c7-da70-49a1-be12-f2a5d425a97d.gif)

Desired tooltip focus behaviour:
![Desired tooltip focus behaviour](https://user-images.githubusercontent.com/20935774/170593046-d8abd3d8-e61c-42ea-9aef-5cdfedacc249.gif)

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
