### ISSUE TITLE
[BUG] - Components/Button

### ISSUE THREAD

**Issue by emadel1990** [nextui-org/nextui#495]
### Describe the bug

When you have a "hoverable" effect on a component, all the Buttons changes in every hover.

### Your Example Website or App

https://pokemons-nextjs.netlify.app/name/ivysaur

### Steps to Reproduce the Bug or Issue

1. Hover the card on the left.
2. You will see the button on the right corner changes in every hover.

### Expected behavior

I expected to not have this behavior on buttons when have a hoverable component.

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @emadel1990 , it cannot replicate the bug that you mention

https://user-images.githubusercontent.com/30373425/172164670-b67498f4-45af-441b-b083-d1145e3bc7be.mov
