### ISSUE TITLE
[BUG] - Opening and closing a modal breaks page scrolling

### ISSUE THREAD

**Issue by joheiska** [nextui-org/nextui#500]
### Describe the bug

Opening a modal breaks the page scrolling as the page scrolling is disabled even after closing the modal. Overflow issue within the modal component. If you inspect the page while opening/closing modal, body gets assigned `overflow: hidden` but it is never removed.

### Steps to Reproduce the Bug or Issue

- Create modal withing a page that is > 100% vh. 
- Open modal
- watch the scrollbar disappear (expected)
- close modal
- watch the scrollbar being still missing (unexpected)

### Expected behavior

- Create modal withing a page that is > 100% vh. 
- Open modal
- page is not scrollable
- close modal
- scrollbar and scrolling is enabled again

### Operating System Version

windows 10

### Browser

Edge

**Comment by aje** [comment]
I still have this problem.

**Comment by SolcAndMe** [comment]
+1

**Comment by SolcAndMe** [comment]
This issue occurs if the Modal component is conditionally rendered (wrapped inside an if statement) vs. if the `open` prop is used.

**Comment by wong2** [comment]
Still occurs to me.

**Comment by razvanilin** [comment]
I encountered this issue quite a few times as well. The solution was to set `overflow: auto` on the `<body>` tag whenever the Modal is closed. In my use-cases, I sometimes use Modals with a URL change, and this way I set `overflow: auto` when the component unmounts.

`document.body.style.overflow = "auto";`

or with `useEffect`:

```
useEffect(() => {
  return () => {
    document.body.style.overflow = "auto";
  }
}, []);

return (
  <Modal open>
...
  </Modal>
)
```
