### ISSUE TITLE
[BUG] - Components/Tooltip offset due to margin at document start

### ISSUE THREAD

**Issue by TechnologicNick** [nextui-org/nextui#521]
### Describe the bug

When the document starts with a vertical margin, all tooltips are offset by this margin.

This bug might be the same as #230, which was unable to be reproduced and later closed as a non-NextUI issue.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-3h6lsu?file=/index.tsx

### Steps to Reproduce the Bug or Issue

1. Hover over any of the two buttons to see that the tooltips are not in the correct positions.
2. Click either of the "Toggle bug" buttons.
3. Notice the tooltips are now in the correct positions.

### Expected behavior

As a user, I expected the tooltips to be just under and just right of the buttons, but I am seeing that the tooltip that's supposed to be just under the button has a gap.

### Screenshots or Videos

https://user-images.githubusercontent.com/20935774/172715377-fcc17cfe-ef6b-41e9-b8df-06996bd9f2f2.mp4

### Operating System Version

Windows

### Browser

Chrome

**Comment by TarsiSurdi** [comment]
Interesting... when using paddings instead of margins for the parent component the position of the tooltips is not affected:
https://user-images.githubusercontent.com/19439765/174789473-8381bd9b-1589-4a64-b2f1-cae382bc328e.mp4

**Comment by danielsimao** [comment]
So, if you inspect the container that is applying the margin, it looks like this:
![image](https://user-images.githubusercontent.com/43269067/175552796-3c3c8698-862b-441e-b5a6-e98b79171b99.png)

If you inspect the parent container, you will see that it doesn't not take into account the `Container`'s margin. Look a this:
![image](https://user-images.githubusercontent.com/43269067/175552648-9a3108d3-a061-4284-9dfd-9ae7497df568.png)

I cannot find any explanation for this and could be that I'm missing something obvious.

**Comment by danielsimao** [comment]
Found this: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing#see_also

**Comment by imchell** [comment]
> Found this: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing#see_also So if you put any other child as the first child of the container, you wont have that issue. I wonder if the `getRect` should have this into consideration.

I'm not sure whether I get it right so please point out if I'm wrong. So the key problem here is how we place the tooltip, which was implemented [here](https://github.com/nextui-org/nextui/blob/2eb31e5fe3c29f89c658101072ce44a29e366632/packages/react/src/tooltip/tooltip-content.tsx#L122) but didn't take root element offset into consideration.

**Comment by danielsimao** [comment]
> https://codesandbox.io/s/sandpack-project-forked-3h6lsu?file=/index.tsx

Exactly, but the offset is odd it self. If you place a `h1` for example as the first child, there won't be an offset.

This is how reachUI calculates the tooltip position: [https://github.com/reach/reach-ui/blob/develop/packages/tooltip/src/index.tsx#L610](url)

**Comment by jrgarciadev** [comment]
Hey guys we are working migrate the current `Tooltip` implementation to [react aria tooltip](https://react-spectrum.adobe.com/react-aria/useTooltipTrigger.html), it should solve the offset calculations issues
