### ISSUE TITLE
[BUG] - Switch Animation In Safari

### ISSUE THREAD

**Issue by imchell** [nextui-org/nextui#525]
### Describe the bug

When trying to uncheck an animated & checked switch component, the animation looks weird.

My guess is that the `left` and `width` of `StyledSwitchCircle` do not update simultaneously in Safari. Similar bug also appears in some of other libs like [Vuesax](https://vuesax.com/docs/components/Switch.html). If there is a animation sequence to perform `width` transformation first and then `left` transformation, like [the switch in antd](https://ant.design/components/switch/), maybe it can be avoided. Not sure if it's a good solution.

### Steps to Reproduce the Bug or Issue

Click any animated & checked switch in Safari.

### Expected behavior

The animation should be fluent.

### Screenshots or Videos

![switch](https://us1.myximage.com/2022/06/09/35137ee15b1feb530ddca6e709e11036.gif)

### Operating System Version

macOS

### Browser

Safari

**Comment by imchell** [comment]
A bug when `shadow = {true}`

![shadow](https://us1.myximage.com/2022/06/09/77b58b1ea2e8d69355b77e76edd70dd6.gif)

**Comment by jrgarciadev** [comment]
Hey @imchell 👋🏼, thanks for reporting it!
