### ISSUE TITLE
[BUG] - Components/Tooltip

### ISSUE THREAD

**Issue by AivarGabd** [nextui-org/nextui#527]
### Describe the bug

Tooltip with trigger="click" onClick evenbt 'onClick is deprecated, please use onPress '

"react-dom": "18.1.0"

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-kc3sl1?file=/App.js:218-225

### Steps to Reproduce the Bug or Issue

When clicking Tooltip with trigger=click, react-dom send message 'onClick is deprecated, please use onPress ' into console and tooltip doesn't appear 

### Expected behavior

On pressing button apprearing tooltip

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/78880503/172819472-69130b29-313f-41ac-bb87-3822ac487e4a.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by AivarGabd** [comment]
❤️ ❤️ ❤️  
Love You work btw, keep moving

**Comment by imchell** [comment]
This was not caused by `onClick()` but a conflict between `<Button />` click action and `<Tooltip />` click action. If you replace `<Button />` with something unclickable, say `<Card />`, the function works well. Hope this helps.

**Comment by AivarGabd** [comment]
Oki
