### ISSUE TITLE
[BUG] - Tooltip trigger="click" not working.

### ISSUE THREAD

**Issue by Guilledorfman** [nextui-org/nextui#538]
### Describe the bug

The trigger="click" property on the tooltip component is not working, not even the example listed on the NextUI documentation. Tested on multiple browsers.

### Your Example Website or App

https://nextui.org/docs/components/tooltip

### Steps to Reproduce the Bug or Issue

     <Tooltip
          content={"Developers love Next.js"}
          trigger="click"
          color="primary"
        >
          <Button auto flat>
            Click me
          </Button>
        </Tooltip>

### Expected behavior

Expected it to work, it doesn't :P

### Screenshots or Videos

https://user-images.githubusercontent.com/14132591/173079696-b80990a5-cd98-432e-be2b-873927e70370.mov

### Operating System Version

macOS

### Browser

Chrome

**Comment by imchell** [comment]
Please kindly refer to #527.

**Comment by Guilledorfman** [comment]
> This is due to a conflict between tooltip and button. Please kindly refer to #527.

Thank you!
