### ISSUE TITLE
[BUG] - Card props does not work

### ISSUE THREAD

**Issue by TaoN23** [nextui-org/nextui#539]
### Browser Console:
`Warning: Received `true` for a non-boolean attribute `hoverable`.

If you want to write it to the DOM, pass a string instead: hoverable="true" or hoverable={value.toString()}.
div
Styled.div
./node_modules/@nextui-org/react/esm/card/card.js/d<@http://localhost:3001/static/js/bundle.js:50711:7
SignIn@http://localhost:3001/static/js/bundle.js:1368:60
Routes@http://localhost:3001/static/js/bundle.js:104552:7
Router@http://localhost:3001/static/js/bundle.js:104489:7
BrowserRouter@http://localhost:3001/static/js/bundle.js:103295:7
div
App@http://localhost:3001/static/js/bundle.js:55:60
div
$f57aed4a881a3485$var$OverlayContainerDOM@http://localhost:3001/static/js/bundle.js:62204:7
$f57aed4a881a3485$export$178405afcd8c5eb@http://localhost:3001/static/js/bundle.js:62165:7
$f57aed4a881a3485$export$bf688221f59024e5
$704cf1d3b684cc5c$export$9f8ac96af4b1b2ae@http://localhost:3001/static/js/bundle.js:62505:62
./node_modules/@nextui-org/react/esm/theme/theme-provider.js/__WEBPACK_DEFAULT_EXPORT__<@http://localhost:3001/static/js/bundle.js:56606:7
$@http://localhost:3001/static/js/bundle.js:72721:7
y@http://localhost:3001/static/js/bundle.js:72707:65`

### Steps to Reproduce the Bug or Issue

packages installed:
nextui
next themes
react router
firebase

### Expected behavior

The Cards should show a hover effect, but they are fixed

### Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/88403373/173171955-09c0e39d-395a-4a9e-9607-b1eb1e0ec8a5.png)

### Operating System Version

-Windows

### Browser

Firefox

**Comment by imchell** [comment]
Thanks for feedback. If you are passing props to `<Card />`, the correct attribute is [`isHoverable`](https://nextui.org/docs/components/card#hoverable) instead of `hoverable`.

**Comment by TaoN23** [comment]
ok, thank you. I overlooked, that the card component was updated.
