### ISSUE TITLE
[BUG] - Module not found: Can't resolve '@react-stately/collections'

### ISSUE THREAD

**Issue by pprathameshmore** [nextui-org/nextui#541]
### Describe the bug

I was working on the Next.js app. I installed the react-use package in my Next.js project! Suddenly Next.js started throwing errors!

![image](https://user-images.githubusercontent.com/17108186/173217596-0194c390-ebce-4c3e-90e6-d33b40a56dca.png)

Then, I searched for similar errors on Stackoverflow. Some of them suggested removing node_modules and package-lock.json and trying to reinstall npm packages. I did so, but nothing seems working! Then restarted VSCode and computer, but the error was still there!

Even I tried to install that package, which is shown in error, but again it throwing an error for another package.

I am not sure why suddenly started throwing errors!

This is my package.json

![image](https://user-images.githubusercontent.com/17108186/173217622-e9768b40-fc8e-4935-9c69-396215509913.png)

### Your Example Website or App

https://stackoverflow.com/questions/72589638/module-not-found-cant-resolve-react-stately-collections-in-next-js-app

### Steps to Reproduce the Bug or Issue

1. Install the latest version of NextUI
2. Run the app in development mode.

### Expected behavior

As a developer, I should I able to use NextUI without any errors!

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/17108186/173217690-9d992c0e-f1c6-4b11-a1fa-5705f156b7c5.png)

### Operating System Version

Windows 10

### Browser

Other (add additonal context)

**Comment by tianenpang** [comment]
Please share a full repro case of this issue, I can not reproduce it.

**Comment by pprathameshmore** [comment]
https://github.com/takeKode/takeKode-frontend
Please checkout develop branch

**Comment by tianenpang** [comment]
Hey @pprathameshmore Looks like it's working great.

```bash
# try to clean the cache and delete node_modules then install it again
npm cache verify

npm cache clean --force

# delete node_modules before install
npm install
```

Here is my environment.

```text
npm  8.11.0
yarn 1.22.19
Node 16.15.1
OS   Windows 10
```

Screenshot of home and code pages.

![ss](https://user-images.githubusercontent.com/32772271/173233880-56bdac7f-fa2c-4515-8c30-f7bfd1c611d2.png)

**Comment by pprathameshmore** [comment]
Thank you! It is working now!
