### ISSUE TITLE
[Feature Request] Table pagination 'Load More' trigger

### ISSUE THREAD

**Issue by Guilledorfman** [nextui-org/nextui#548]
### Is your feature request related to a problem? Please describe.

Currently we have two ways to paginate the table, using the Table.Pagination and infinity pagination.
I find myself needing a third way, an infinity pagination type of thing but instead of automatically fetching the data when reaching the bottom, displaying a 'Load More' button inside the table, this way I can read the last row of the table without making another unwanted request to the DB. 

I already made this myself but I can't put the load more button inside of the table so that is not always visible and you can only see it when you reach the bottom of the table.

### Describe the solution you'd like

Same behaviour as the infinity pagination but the trigger would be a 'Load More' button at the bottom of the table (like an extra row) instead of scrolling to the bottom.

### Describe alternatives you've considered

Adding some kind of Table.Footer so that you can add a 'row' at the end of the table would solve this.

### Screenshots or Videos

![Screen Shot 2022-06-16 at 15 48 22](https://user-images.githubusercontent.com/14132591/174144503-f8dc5118-22e7-4cde-998e-659aa650b797.jpg)

**Comment by jrgarciadev** [comment]
This feature was implemented on V2 please upgrade.
