### ISSUE TITLE
[BUG] - Components/Table

### ISSUE THREAD

**Issue by koten551** [nextui-org/nextui#551]
### Describe the bug

using input tag on Table.cell making this is read only, cant change value of

### Steps to Reproduce the Bug or Issue

using input tag on Table.cell making this is read only, cant change value of

### Expected behavior

using input tag on Table.cell making this is read only, cant change value of

### Screenshots or Videos

using input tag on Table.cell making this is read only, cant change value of

### Operating System Version

macos

### Browser

Chrome

**Comment by afzaalb** [comment]
+1

**Comment by opiepj** [comment]
Still facing this
