### ISSUE TITLE
[BUG] - Components/Table Get an error when using onSelectionChange

### ISSUE THREAD

**Issue by yuyake0084** [nextui-org/nextui#557]
### Describe the bug

Thank you for providing a great library.
I tried using onSelectionChange to detect a change in a checkbox in a Table.
However, when I use it, I get the following error:

```
Warning: Unknown event handler property `onSelectionChange`. It will be ignored.
```

```tsx
    <Table
      ref={ref}
      aria-label="hoge"
      selectionMode="multiple"
      color="success"
      compact
      css={{
        width: '100%',
        fontSize: FONT_SIZES.S,
      }}
      defaultSelectedKeys={new Set(completed)}
      onSelectionChange={(key) => {
        ...
      }}
    >
      ...
    </Table>
```

### Steps to Reproduce the Bug or Issue

1. Pass onSelectionChange to props

### Expected behavior

The behavior works as expected, but I'm worried about the cause of the error.

### Operating System Version

macOS 12.3

### Browser

Chrome

**Comment by yuyake0084** [comment]
Note: Reproduce in local environment, but not reproduce when deployed

**Comment by TarsiSurdi** [comment]
Could you provide your implementation of the component so that I can look into the problem? I don't believe there's an issue with the library itself, but I'l also not discard this option when analysing what you did!

**Comment by TarsiSurdi** [comment]
I have made a [code sandbox](https://codesandbox.io/s/nextui-issue-557-rfj7yx) for your issue and indeed, that warning is displayed when using that property on the `<Table>` component 🤔. I'll take a look into it, but as far as functionality goes it seems to work just fine.

**Comment by danielsimao** [comment]
Thanks for reporting the issue @yuyake0084

**Comment by yuyake0084** [comment]
@danielsimao 
Thank you for your support!
Then this will be closed.
