### ISSUE TITLE
[BUG] - Beta 8 and newer cause lag in animations for components in `Card`

### ISSUE THREAD

**Issue by DannyNemer** [nextui-org/nextui#561]
### Describe the bug

When using the `Card` component in Beta 8 or later, animations of components inside the card (e.g., hover with `Button`) experience a significant lag. Merely downgrading to Beta 7 removes the lag instantly.

### Beta 8 & 9 - slow animations
https://user-images.githubusercontent.com/170023/174913771-0da76ce3-05bc-4407-b8f7-03fb85598222.mov

### Beta 7 - fast animations
https://user-images.githubusercontent.com/170023/174913796-ed17fa13-b3e3-4f88-bb1a-8c263b49b98f.mov

### Steps to Reproduce the Bug or Issue

1. Create a new Next.js project with the [default NextUI setup](https://nextui.org/docs/guide/getting-started).
2. Use this example `_app.tsx` page:
    ```tsx
    import { Button, Card } from "@nextui-org/react";
    import type { NextPage } from "next";
    
    const Home: NextPage = () => {
      return (
        <Card>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
          <Button flat>Test</Button>
        </Card>
      );
    };
    
    export default Home;
    ```
3. Run `next dev` and experience the **_slow_** hover and click animations in the browser (as shown in the first screen recording above).
4. Downgrade to NextUI beta 7:
    ```sh
    yarn add @nextui-org/react@1.0.0-beta.7
    ```
5. Run `next dev` and experience the **_fast_** hover and click animations in the browser (as shown in the second screen recording above).

### Expected behavior

Expected smooth animations.

### Operating System Version

**OS:** macOS 11.6.7
**Processor:** 2.8 GHz Quad-Core Intel Core i7
**Memory:** 16 GB 1600 MHz DDR3

### Browser

Tested in Chrome and Safari, but slowness is more pronounced in Safari

**Comment by imchell** [comment]
Hi @DannyNemer have you tried beta9? I think the performance has been improved since then. Here's a working sample: https://codesandbox.io/s/multiple-buttons-3wevf4

**Comment by DannyNemer** [comment]
> Hi @DannyNemer have you tried beta9? I think the performance has been improved since then. Here's a working sample: https://codesandbox.io/s/multiple-buttons-3wevf4

@imchell Yep, performance issues are identical in beta9 as beta8

**Comment by imchell** [comment]
Ah I can reproduce it in Safari.

**Comment by TroyTae** [comment]
It seems this issue is coming from this style `filter: var(--nextui-dropShadows-lg);`

Current:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/20078201/175783545-abf3ca5c-6fa7-40c8-be50-2bc9ddc9a03b.png">

Set `filter: none`:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/20078201/175783675-cd8ee8dc-a6ee-4629-a2f0-07f91e05680f.png">

@DannyNemer 
If you don't need shadow, you can avoid this issue with `variant="flat"`
```
  <Card variant="flat">
    <Button flat>Test</Button>
  </Card>
```

To fundamentally fix it, we can choose between several options, but let's wait for the maintainer's opinion first 😅

**Comment by jrgarciadev** [comment]
Hey @DannyNemer could you please share the specs of your machine? 

I've tested it, on safari and chrome and it works without lag
https://user-images.githubusercontent.com/30373425/177015738-934ddabe-3b3c-49cc-b1fd-0ffe065499ad.mov

@TroyTae could you share the name of the tool you used for measuring the CPU?

**Comment by TroyTae** [comment]
@jrgarciadev
It's built-in tool of Safari (https://webkit.org/blog/8993/cpu-timeline-in-web-inspector/)
You can find timelines tab in Safari Web Inspector!

**Comment by jrgarciadev** [comment]
Thanks @TroyTae 🙏🏻

**Comment by DannyNemer** [comment]
> Hey @DannyNemer could you please share the specs of your machine?
> 
> I've tested it, on safari and chrome and it works without lag https://user-images.githubusercontent.com/30373425/177015738-934ddabe-3b3c-49cc-b1fd-0ffe065499ad.mov
> 
> @TroyTae could you share the name of the tool you used for measuring the CPU?

@jrgarciadev Thank you for investigating!

### Specs:
**OS:** macOS 11.6.7
**Processor:** 2.8 GHz Quad-Core Intel Core i7
**Memory:** 16 GB 1600 MHz DDR3

**Comment by biscuit-deluxe** [comment]
I was able to replicate this issue by disabling hardware acceleration on Chrome/Brave. Safari also exhibits this issue. As suggested by @TroyTae, the lag can be mitigated by disabling shadows.

**Comment by jrgarciadev** [comment]
Hey guys, could you try again using the latest version `v10`? I've added box shadows for safari instead of a `drop-shadow` filter

**Comment by SimonShiki** [comment]
> Hey guys, could you try again using the latest version `v10`? I've added box shadows for safari instead of a `drop-shadow` filter

It's still laggy in Chrome but solved in Safari

**Comment by SimonShiki** [comment]
Is this issue still active?

**Comment by SimonShiki** [comment]
Is this issue still active?

**Comment by SimonShiki** [comment]
Is this issue still active?

**Comment by depyronick** [comment]
Persists on v10; changing the variant to flat helps.

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates. New version is way more perfomant
