### ISSUE TITLE
[BUG] - Container: doesn't accept ref prop

### ISSUE THREAD

**Issue by mtsmfm** [nextui-org/nextui#566]
### Describe the bug

```tsx
import { useRef } from "react";
import { Container } from "@nextui-org/react";

export default function App() {
  const containerRef = useRef(null);

  return (
    <Container ref={containerRef} gap={2} justify="center">
      Hi
    </Container>
  );
}
```

```
Type '{ children: string; ref: MutableRefObject<any>; gap: number; justify: "center"; }' is not assignable to type 'IntrinsicAttributes & Omit<Props, "gap" | "xs" | "sm" | "md" | "lg" | "xl" | "responsive" | "fluid" | "wrap" | "as" | "display"> & Partial<{ gap: number; ... 9 more ...; display: "flex" | ... 5 more ... | "inline-grid"; }> & NativeAttrs'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & Omit<Props, "gap" | "xs" | "sm" | "md" | "lg" | "xl" | "responsive" | "fluid" | "wrap" | "as" | "display"> & Partial<{ gap: number; ... 9 more ...; display: "flex" | ... 5 more ... | "inline-grid"; }> & NativeAttrs'.ts(2322)
```

### Your Example Website or App

https://codesandbox.io/s/nextui-grid-ref-forked-tigu7s?file=/App.tsx:0-254

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/s/nextui-grid-ref-forked-tigu7s?file=/App.tsx:0-254

### Expected behavior

Type check successfully passed

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1796864/175499512-527b9952-4e56-47ed-8f79-bf14930a57b8.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by notmedia** [comment]
@jrgarciadev Hey, I looked to main branch and there is no forward ref there :(
