### ISSUE TITLE
[BUG] - Modal scroll is not blocked in mobile Safari

### ISSUE THREAD

**Issue by TroyTae** [nextui-org/nextui#572]
### Describe the bug

Modal scroll is not blocked in mobile Safari.
`overflow: auto;` is a frequently used way, but I think it is better to block it with js.

### Steps to Reproduce the Bug or Issue

1. Open modal in safari
2. Try scroll outside
3. Scroll is not blocked

### Expected behavior

Scroll need to be blocked

### Screenshots or Videos

https://user-images.githubusercontent.com/20078201/175798823-9dc8452c-889f-4acc-97c7-6effb012e6cd.mp4

### Operating System Version

iPadOS

### Browser

Safari

**Comment by danielsimao** [comment]
I was only able to find a library that handled this edge case: [React Spectrum](https://react-spectrum.adobe.com/react-aria/useDialog.html).

I don't know if @jrgarciadev would allow a refactor of the component to use `useDialog` from `react-aria` instead.

**Comment by jrgarciadev** [comment]
Hey guys, the migration of this component to `react-aria` is in progress, it should be available in the next release `v10`, it should fix this issue

**Comment by TroyTae** [comment]
@jrgarciadev 
It's built-in tool of Safari (https://webkit.org/blog/8993/cpu-timeline-in-web-inspector/)
You can find `timelines` tab in Safari Web Inspector!
