### ISSUE TITLE
[BUG] - Card Shadow Cropped in Documentation

### ISSUE THREAD

**Issue by imchell** [nextui-org/nextui#578]
### Describe the bug

Card component shadows are cropped in doc live previews. **Only in Safari**.

A possible solution would be adding `css = {{ overflow: "visible" }}` to `Card` but it's not enough for transitions (in hoverable `Card` for example).

### Your Example Website or App

https://nextui.org/docs/components/card

### Steps to Reproduce the Bug or Issue

Visit https://nextui.org/docs/components/card via Safari

### Expected behavior

`drop-shadow` of `Card` is visible and not cropped.

### Screenshots or Videos

![Cards](https://us1.myximage.com/2022/06/27/8b4bebfc4a6921475630af43fc89de25.png)

### Operating System Version

macOS

### Browser

Safari

**Comment by kamami** [comment]
It is still cropped in Safari.

**Comment by horvathandris** [comment]
I can still reproduce this bug on Safari on iOS.
