### ISSUE TITLE
Table - Conditionnal rendering -> typescript error

### ISSUE THREAD

**Issue by Guarn** [nextui-org/nextui#583]
### Describe the bug

If I add a conditionnal rendering in a Table :

      <Table>
        <Table.Header>
          <Table.Column>Client</Table.Column>
        </Table.Header>
        <Table.Body>
          {1 === 1 && (                                                  <-- Here
            <Table.Row>
              <Table.Cell>a</Table.Cell>
            </Table.Row>
          )}
        </Table.Body>
      </Table>

Typescript complains with :

Impossible d'assigner le type 'false | Element' au type 'CollectionChildren<unknown>'.
Impossible d'assigner le type 'boolean' au type 'CollectionChildren<unknown>'.ts(2322)
index.d.ts(102, 3): Le type attendu provient de la propriété 'children', qui est déclarée ici sur le type 'IntrinsicAttributes & TableBodyProps<unknown> & { css?: CSS | undefined; }'

![image](https://user-images.githubusercontent.com/24851412/176393277-a89866a4-2d4b-40af-b7bc-6e36a6da9e3c.png)

### Steps to Reproduce the Bug or Issue

Just copy this code :

      <Table>
        <Table.Header>
          <Table.Column>Client</Table.Column>
        </Table.Header>
        <Table.Body>
          {1 === 1 && (
            <Table.Row>
              <Table.Cell>a</Table.Cell>
            </Table.Row>
          )}
        </Table.Body>
      </Table>

### Expected behavior

No typescript error with conditionnal rendering

### Operating System Version

W11

### Browser

Chrome

**Comment by danielsimao** [comment]
This problems comes from the types inherited from `@react-type/table`.

https://github.com/nextui-org/nextui/blob/main/packages/react/src/table/base/table-body.tsx#L5

**Comment by jrgarciadev** [comment]
Hey @Guarn that's because, in static tables, the `Table.Body` always expects at least one  `Table.Row`, if you want to have dynamic row you should use the dynamic implementation, here's an example:
https://codesandbox.io/s/dynamic-table-conditional-row-0vp5v1?file=/App.js

Here's the documentation: https://nextui.org/docs/components/table#dynamic

Hope it helps you 🙌🏻
