### ISSUE TITLE
[BUG] - Components/Dropdown

### ISSUE THREAD

**Issue by fathonialimukti** [nextui-org/nextui#585]
### Describe the bug

I want to make user login button with custom-trigger, and there seems to be some bug there. so i tried onAction but it wouldn't  work on Dropdown.Item so we can't interact with Dropdown.Item if we place onAction on Dropdown.Menu, it will execute when we click any of the Dropdown.Item , and looks like the key at (key:Key)=>{} didn't refer to Dropdown.Item's key. I have tried with adding some Next/Link and Button but none of it works.

### Your Example Website or App

https://nextui.org/docs/components/dropdown#custom-trigger

### Steps to Reproduce the Bug or Issue

1. Just copy one of those code
2. Try add onAction on Dropdown.Item
3. Try add Link or Button or something clickable inside of Dropdown.Item

### Expected behavior

expecting Dropdown.Item interaction such as go to dashboard and logout 

### Operating System Version

Pop!_OS 22.04 LTS x86_64

### Browser

Chrome

**Comment by danielsimao** [comment]
@fathonialimukti Could you please provide a codesandbox?

**Comment by fathonialimukti** [comment]
`<Dropdown disableAnimation>
    <Dropdown.Trigger>
        <User
        bordered
        as="button"
        size="lg"
        color="primary"
        name={session.user?.name}
        description={session.user?.email}
        src="https://i.pravatar.cc/150?u=a042581f4e29026024d"
        />
    </Dropdown.Trigger>
    <Dropdown.Menu color="primary" aria-label="User Actions">
        <Dropdown.Item key="profile" css={{ height: "$18" }}>
        <Text b color="inherit" css={{ d: "flex" }}>
            {session.user?.name}
        </Text>
        <Text b color="inherit" css={{ d: "flex" }}>
            {session.user?.email}
        </Text>
        </Dropdown.Item>
        <Dropdown.Item key="dashboard" withDivider>
            <Link href='/dashboard'>Dashboard</Link>
        </Dropdown.Item>
        <Dropdown.Item  key="logout" color="error" withDivider> {/* onAction={()=>signOut()} */}
            <Button light color="error" auto onClick={()=>signOut()}>Log Out</Button>
        </Dropdown.Item>
    </Dropdown.Menu>
</Dropdown>`

i cant access the Link and Button even if i set the z-index to max

**Comment by fathonialimukti** [comment]
> @fathonialimukti Could you please provide a codesandbox?

![image](https://user-images.githubusercontent.com/50938757/176886580-0c42e333-8540-4a9b-b75f-88942744935e.png)
