### ISSUE TITLE
[BUG] - Container / Row / Col gap

### ISSUE THREAD

**Issue by wayf** [nextui-org/nextui#590]
### Describe the bug

```
<Container gap={0}>
    <Row gap={1}>
        <Col>qwe</Col>
    </Row>
</Container>
<Container>
    qwe
</Container>
```

The left padding of the first text block does not match the second

### Your Example Website or App

https://codesandbox.io/s/nextui-bug-x1p3ry

### Steps to Reproduce the Bug or Issue

None

### Expected behavior

Paddings must be the same

### Operating System Version

macOS

### Browser

Chrome

**Comment by wayf** [comment]
In this case $space$lg must be 1.5rem
```JS
space: {
    lg: "1.5rem",
}
```

**Comment by danielsimao** [comment]
Hey 👋. The padding is applied by the container. What happens is that in the first use case you have a `Row` and a `Col`.

-`Row`: Applied Margin left.
-`Col`: applies padding in the axis.

The second use case is just a container. So they wont match unless you customise on your end.

The only thing I see as odd here is the margin applied on the `Row`, but not the padding that you mention.

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.

Use Tailwind CSS layout classes
