### ISSUE TITLE
[BUG] - Invisible font color on nextui.org when switching to light theme

### ISSUE THREAD

**Issue by mnik01** [nextui-org/nextui#598]
### Describe the bug

I've got invisible white on white colored text in page

![image](https://user-images.githubusercontent.com/39025497/177287741-887702da-c5e8-41d5-8d19-4d4815865812.png)

### Steps to Reproduce the Bug or Issue

1. Go to https://nextui.org/docs/components/avatar
2. Press CTRL + K
![image](https://user-images.githubusercontent.com/39025497/177288031-c113f6f3-ad94-46a9-bc39-e5ae359399b4.png)
3. Choose light theme 
4. Get te bug

### Expected behavior

To change font color when theme changed

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/39025497/177288288-1054c594-1d15-4c6b-842b-c80fd5ababf0.png)

### Operating System Version

- OS: windows 10 x64

### Browser

Chrome

**Comment by danielsimao** [comment]
Hey 👋 Thank you for opening this issue @mnik01. I will take a look into it. Cheers
