### ISSUE TITLE
[Feature Request] Add a link or click event to dropdown item

### ISSUE THREAD

**Issue by adilet-web-dev** [nextui-org/nextui#606]
### Is your feature request related to a problem? Please describe.

I placed a link inside the dropdown item and when a user clicks this link it should redirect to some page.
The problem is user should click exact link text, otherwise it won't redirect

### Describe the solution you'd like

Can you make whole dropdown item a link or add click event to it?

### Describe alternatives you've considered

Make dropdown item as short as text, so user can click only link text

### Screenshots or Videos

https://user-images.githubusercontent.com/72970300/177724789-4a62be5a-7dde-4a1f-82a9-a4b6be86279a.mp4

**Comment by danielsimao** [comment]
Hey @adilet-web-dev 👋.

In my opinion, a dropdown contais a list of options, where each option is connected to an action. Placing an anchor inside a Dropdown Item does not provide the item with a specific action, which goes against the purpose of a Dropdown.

In your case, I would mimic a navigation programmatically by using `onAction` event handler provided by the Dropdown. If you are using NextJS, you would use `useRouter` to handle your navigation here.

**Comment by KieSun** [comment]
Hey @danielsimao .

In dropdown component, I use `icon` props and want to customize the click event when the user clicks on the icon. But i saw the event not trigger. What can i do?

**Comment by danielsimao** [comment]
If you check this example, it seems to work with the alert

https://codesandbox.io/s/sandpack-project-forked-9zy7h2?file=/App.js:488-789

**Comment by rumfiske** [comment]
I still cant use onClick

```
 <Dropdown.Item
                            textValue="Log ud"
                            key="logout"
                            color="error"
                            onClick={() => console.log("hey")}
                            withDivider
                            command="L"
                          >
                            Log ud{" "}
                          </Dropdown.Item>
```

**Comment by ianeinser** [comment]
> I still cant use onClick
> 
> ```
>                             <Dropdown.Item
>                             textValue="Log ud"
>                             key="logout"
>                             color="error"
>                             onClick={() => console.log("hey")}
>                             withDivider
>                             command="L"
>                           >
>                             Log ud{" "}
>                           </Dropdown.Item>
> ```

use onAction because onClick is not available

**Comment by ImLunaHey** [comment]
Thanks to this stackoverflow I worked out a way around this. https://stackoverflow.com/a/1121754

Basically set the `<li>` to have no padding and fit the inner `<a>` to be the same size. 

```tsx
<Dropdown.Menu aria-label="User menu actions" color="secondary">
  <Dropdown.Item
    textValue={`@${sessionData.user?.page?.handle}`}
    key="profile"
    className="p-0"
  >
    <Link
      className="m-0 block h-full w-full p-2"
      href={`/${sessionData.user?.page?.handle}`}
    >
      <Text b color="inherit" css={{ d: 'flex' }}>
        @{sessionData.user?.page?.handle}
      </Text>
    </Link>
  </Dropdown.Item>
</Dropdown.Menu>
```

**Comment by starhound** [comment]
The solution is to use minWidth of 100% on the Link component.

**Comment by mflash123** [comment]
> Thanks to this stackoverflow I worked out a way around this. https://stackoverflow.com/a/1121754
> 
> Basically set the `<li>` to have no padding and fit the inner `<a>` to be the same size.
> 
> ```tsx
> <Dropdown.Menu aria-label="User menu actions" color="secondary">
>   <Dropdown.Item
>     textValue={`@${sessionData.user?.page?.handle}`}
>     key="profile"
>     className="p-0"
>   >
>     <Link
>       className="m-0 block h-full w-full p-2"
>       href={`/${sessionData.user?.page?.handle}`}
>     >
>       <Text b color="inherit" css={{ d: 'flex' }}>
>         @{sessionData.user?.page?.handle}
>       </Text>
>     </Link>
>   </Dropdown.Item>
> </Dropdown.Menu>
> ```

Well, thats bad solution. I wish to have native Dropdown.Item click event. I am surprised that next ui doesnt have a general event on this component.

**Comment by fabiodevn1** [comment]
pra quem tiver esse problema, adicionei isso no inicio e funcionou

  <Dropdown.Menu
                    color="primary"
                    aria-label="User Actions"
                    selectionMode="single"
                    onSelectionChange={(e) => {
                        const { currentKey } = e
                        if (currentKey === "logout") {
                            console.log("logout")
                        }
                    }}
                >

**Comment by hunguet231** [comment]
> pra quem tiver esse problema, adicionei isso no inicio e funcionou
> 
> <Dropdown.Menu color="primary" aria-label="User Actions" selectionMode="single" onSelectionChange={(e) => { const { currentKey } = e if (currentKey === "logout") { console.log("logout") } }} >

Thanks @fabiodevn1, that works. We can separate the function to handle when selection changes by switch case the dropdown item key and putting the corresponding action on it.

**Comment by jeffexavier** [comment]
What was worked for me was insert a button element inside the Dropdown.Item with "width: 100%" css.

` <Dropdown.Item key={index} textValue={item.name}>
<button className="w-full" onClick={() => console.log(item.name)}>{item.name}</button>
</Dropdown.Item>`

**Comment by t3db0t** [comment]
I must be missing something somewhere, because it's bizarre that the Dropdown docs do not list `onAction` in the events. Why???

**Comment by akilesh-io** [comment]
Here is a example using `onAction` method

```ts
<Dropdown.Menu
  onAction={(item) => {
    console.log(item);
  }}
>
  <Dropdown.Item key="trainers">Trainers</Dropdown.Item>
  <Dropdown.Item key="shedules">Shedules</Dropdown.Item>
  <Dropdown.Item key="courses">Courses</Dropdown.Item>
</Dropdown.Menu>

```

**Comment by t3db0t** [comment]
@akilesh-io I know how to do it now, I'm saying `onAction` needs to be in the `Dropdown` docs under `Events.`

**Comment by Dteeech** [comment]
> pra quem tiver esse problema, adicionei isso no inicio e funcionou
> 
> <Dropdown.Menu color="primary" aria-label="User Actions" selectionMode="single" onSelectionChange={(e) => { const { currentKey } = e if (currentKey === "logout") { console.log("logout") } }} >

Thank you su much it worked for me. 💪🏽

**Comment by codekappal** [comment]
Fixed by adding <Link> for all components. 
```
 {navItem.items.map((item) => (
              <DropdownItem
                key={item.key}
                className={"p-3 hover:bg-slate-900 rounded-xl w-[300px] "}
                description={
                  <Link
                    className="px-3 text-sm text-secondary"
                    href={item.href}
                  >
                    {item.description}
                  </Link>
                }
                href={item.href}
                startContent={
                  <Link href={item.href}>
                    <Image
                      alt="image"
                      className="border border-gray-700 hover:text-primary"
                      height={50}
                      src={item.image}
                      width={50}
                    />
                  </Link>
                }``
```
