### ISSUE TITLE
[BUG] - Link does not trigger Router 'routeChangeStart' event

### ISSUE THREAD

**Issue by HarveyB02** [nextui-org/nextui#622]
### Describe the bug

When clicking the link element to redirect to another page, 

### Steps to Reproduce the Bug or Issue

Listen for the routeChangeStart event
```tsx
Router.events.on('routeChangeStart', () => {
	console.log('routeChangeStart emitted')
})
```
Create a nextui Link element
```tsx
<Link href="/">Example</Link>
```

- Open the browser console & click the Link element

### Expected behavior

routeChangeStart should be triggered by the Link element

### Operating System Version

- OS: Arch Linux

### Browser

Firefox

**Comment by jrgarciadev** [comment]
Hey @HarveyB02 you have to wrap the NextUI `Link` in a Next.js `Link`,  here's the docs https://nextui.org/docs/components/link#next.js-link
