### ISSUE TITLE
[BUG] - `Dropdown` is rendered twice in `React 18`

### ISSUE THREAD

**Issue by xlboy** [nextui-org/nextui#627]
### Describe the bug

In `React 18`, `Dropdown` component will be rendered twice after clicking.

### Your Example Website or App

https://codesandbox.io/s/jovial-rumple-zj2pm8?file=/src/index.tsx

### Steps to Reproduce the Bug or Issue

Preview the given link, Simple debugging `Dropdown` components

### Expected behavior

After clicking on the `Dropdown` component, it should be rendered once, not twice (resulting in flickering effect)

### Screenshots or Videos

https://user-images.githubusercontent.com/63690944/179940163-196fdd2a-49cc-4762-a9a8-ca0700a5fe59.mov

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @xlboy thanks for the feedback, however, as we mention in the last release (https://github.com/nextui-org/nextui/releases/tag/v1.0.0-beta.9) React 18 is only partially supported,  the strict mode support will be done separately
