### ISSUE TITLE
[BUG] - Link component reloads page when already on page.

### ISSUE THREAD

**Issue by malewis5** [nextui-org/nextui#636]
### Describe the bug

When using the Link component from Next UI if you click a link that is your current route it will reload the page. I would expect this component to work similar to the NextJS Link component where this doesn't happen.

### Your Example Website or App

https://codesandbox.io/s/great-dawn-3reh63

### Steps to Reproduce the Bug or Issue

1. Visit provided code sandbox.
2. Click Next Home Link and notice no reload.
3. Click Next UI Home Link and notice full reload.

### Expected behavior

As a user I expected the link to not cause a full reload if I am on the page. Instead the full page reloaded.

### Operating System Version

macOS Monterey v12.4

### Browser

Chrome

**Comment by ZeKap** [comment]
Still not fixed?
