### ISSUE TITLE
[Feature Request] Selection Mode in Button Group

### ISSUE THREAD

**Issue by TroyTae** [nextui-org/nextui#639]
### Is your feature request related to a problem? Please describe.

I got a requirement that displays selected button in button group. (Like radio button!)
But there is no selected prop or selection mode in Button Group.

### Describe the solution you'd like

So I overwrite selected button's css like this:
```
<Button.Group flat>
  <Button css={someBoolean ? { color: "$primarySolidContrast", bgColor: "$primary" } : undefined}>
    Selected Button
  </Button>
</Button.Group>
```
![image](https://user-images.githubusercontent.com/20078201/181191428-cc67c49c-62af-48e1-a9b6-6a1e0c968e44.png)

### Describe alternatives you've considered

Do you have a roadmap about this already?
I would be very happy if this feature is built in :)

**Comment by MForMarlon** [comment]
Here's a workaround where I am using the ButtonGroup like tabs:

```
const [activeTab, setActiveTab] = useState('a');
...
<Button.Group size="xl">
  <Button
    onClick={() => setActiveTab('a')}
    light={activeTab !== 'a'}
    bordered={activeTab === 'a'}>a</Button>
  <Button
    onClick={() => setActiveTab('b')}
    light={activeTab !== 'b'}
    bordered={activeTab === 'b'}>b</Button>
  <Button
    onClick={() => setActiveTab('c')}
    light={activeTab !== 'c'}
    bordered={activeTab === 'c'}>c</Button>
</Button.Group>
```

**Comment by aed0nis** [comment]
Would be good to have this in the documentation.
