### ISSUE TITLE
[BUG] - Wrong Import in table document (.ts mode)

### ISSUE THREAD

**Issue by SPY-STAR0003** [nextui-org/nextui#653]
### Describe the bug

Hi Mr Junior Garcia!

Your package is very awesome & I really enjoy it !
But I found a problem in importing in table document in your website ([Custom Cells](https://nextui.org/docs/components/table#custom-cells))

see eyeIcon, deleteIcon, editIcon in ts mode !

import { React } from '@nextui-org/react'; ?????

True is ==> import React from 'react'; 

Thanks a lot !

### Your Example Website or App

https://nextui.org/docs/components/table#custom-cells

### Steps to Reproduce the Bug or Issue

...

### Expected behavior

import React from "react";

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Thanks for reporting it @SPY-STAR0003 🙌🏻 , and thank you @tianenpang for fixing it 🚀
