### ISSUE TITLE
[Feature Request] Modal Prop: focusRef prop to focus on specified element after modal opens

### ISSUE THREAD

**Issue by anuraglol** [nextui-org/nextui#659]
### Is your feature request related to a problem? Please describe.

Like chakra ui (https://chakra-ui.com/docs/components/modal/usage#focus-on-specific-element), a prop that accepts a ref and focuses on it after modal opens.

### Describe the solution you'd like

The ideal approach for this would be to accept a new prop and bind `.current.focus()` method to it when the modal is open

### Describe alternatives you've considered

Any solutions which produces similar effects...

**Comment by jrgarciadev** [comment]
Hey @kr-anurag thank you for your suggestion, we have in our roadmap the migration to https://react-spectrum.adobe.com/react-aria/useDialog.html we hope to add this feature once we migrate the Modal

**Comment by jrgarciadev** [comment]
Modal has been migrated https://nextui.org/docs/components/modal, you can focus any element inside of it by using its ref.
