### ISSUE TITLE
[Next.js] NextUIProvider breaks Suspense in Next.js projects, even without suspended components

### ISSUE THREAD

**Issue by nghiepit** [nextui-org/nextui#660]
### Describe the bug

When you add NextUIProvider to `_app.tsx`, any usage of `Suspense` breaks the app.

### Your Example Website or App

https://codesandbox.io/s/wonderful-yonath-v9ko1f?file=/pages/index.js

### Steps to Reproduce the Bug or Issue

1/ Create a vanilla `Next.js` app
2/ Add a `Suspense` component with <p>Hello world</p> as children into pages/index.tsx
3/ Verify it works fine (should)
3/ Add <NextUIProvider> into _app.tsx
4/ Reload the page - emits the following error:
> Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.

### Expected behavior

No error

### Screenshots or Videos

https://user-images.githubusercontent.com/4768095/183388390-0e338087-e4d6-4780-9bcf-c83bddabf45a.mov

### Operating System Version

macOS

### Browser

Chrome

**Comment by gariasf** [comment]
Hi @nghiepit, I think this library doesn't fully support React 18 yet.

**Comment by jrgarciadev** [comment]
Hey @nghiepit as @gariasf said, React 18 is not fully supported yet, we hope to add support once the `react-aria` team adds fully support to `react` 18
