### ISSUE TITLE
[BUG] - Components/Tooltip content behind Components/Modal

### ISSUE THREAD

**Issue by TechnologicNick** [nextui-org/nextui#664]
### Describe the bug

When using a Tooltip in an open Model, the tooltip content shows up behind the Modal. Setting the `z-index` of the Tooltip to `10000` resolves this, because the Modal uses a `z-index` of `9999`.

### Your Example Website or App

https://codesandbox.io/s/next-ui-tooltip-behind-modal-sxh06v

### Steps to Reproduce the Bug or Issue

1. Hover over the "Do hover here" button.
2. See that the Tooltip content is behind the Modal.

### Expected behavior

As a user, I expected the Tooltip content to be on top of the Modal, but I am seeing the Tooltip content is behind the Modal.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/20935774/183738185-bc22d0b9-e23b-405a-a43f-11f361f4e34d.png)
![image](https://user-images.githubusercontent.com/20935774/183738191-31c2b3b6-1a73-42cd-98a8-c7a6fe08e40d.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by SellersEvan** [comment]
I had this issue as well. And this fix worked.

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

Tooltip and Modal components were created from scratch using react-aria hooks, Tailwind CSS and framer-motion
