### ISSUE TITLE
[BUG] - Components/Dropdown

### ISSUE THREAD

**Issue by pl-90** [nextui-org/nextui#666]
### Describe the bug

when I try to use the dropdown, the open event is not kept (opens and closes quickly) unless I keep clicked.

### Steps to Reproduce the Bug or Issue

1. Set the dropdown in react page
2. click on the dropdown
3. it will close automatically

### Expected behavior

I wait for the normal functioning of the component

### Screenshots or Videos

https://user-images.githubusercontent.com/34556034/184004499-af31a6bc-c165-4ea4-8117-7170c760a9c2.mp4

### Operating System Version

Windows

### Browser

Firefox

**Comment by tianenpang** [comment]
Hi @pl-90 are you using `yarn add`? Please try using `npm` or [`pnpm`](https://pnpm.io/) for package management.

Duplicate with https://github.com/nextui-org/nextui/issues/649.

**Comment by Keroro2139** [comment]
Same here :(

**Comment by pl-90** [comment]
The issue was resolved using react version 17 and installing with npm.
