### ISSUE TITLE
[BUG] - Breakpoints don't work with styled/css

### ISSUE THREAD

**Issue by EthanStandel** [nextui-org/nextui#674]
### Describe the bug

It appears that if I try to make a styled component (using the `import { styled, css } from "@nextui-org/react"`), the breakpoints just don't seem to work. I apologize if I am severely misunderstanding the Stitches syntax, but I do believe the breakpoints just aren't working.

### Your Example Website or App

https://stackblitz.com/edit/react-ts-yigy98?file=App.tsx

### Steps to Reproduce the Bug or Issue

1. Create a custom styled component or use `className={css({...})}` on an arbitrary element with breakpoints
2. Observe the breakpoints not working

### Expected behavior

The breakpoints should work for the `styled` and `css` exports.

### Operating System Version

macOS

### Browser

Chrome

**Comment by AmirRivar** [comment]
Hi @EthanStandel Thanks for contributing.
The problem you are facing is not a bug.
As shown in [Stitches documents](https://stitches.dev/docs/responsive-styles) you should prefix breakpoints with `@`.
For example your code should be:
```js
const MyButton = styled('button', {
  background: 'red',
  '@sm': {
    background: 'blue',
  },
  '@smMax': {
    background: 'blue',
  },
});

```

**Comment by EthanStandel** [comment]
@AmirRivar Thaaaaaank you! I thought the default breakpoints in Stitches were litterally called `"@bp1"` and that's why they were referenced like that 🤦
