### ISSUE TITLE
[BUG] - Table.Header left corner is not rounded

### ISSUE THREAD

**Issue by notmedia** [nextui-org/nextui#677]
### Describe the bug

When Table has only one column left corner of Table.Header is not rounded

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/s/sandpack-project-forked-5zcov7?file=/App.js

### Expected behavior

Left corner is rounded

### Operating System Version

macos

### Browser

Chrome

**Comment by wangly19** [comment]
The example you provided looks normal

<img width="2616" alt="image" src="https://user-images.githubusercontent.com/45115006/185953874-e42a4e7a-7cb3-46dd-8487-0bb245701b2f.png">

**Comment by notmedia** [comment]
I talked about Table.Header component, look at the screenshot:

<img width="887" alt="Screenshot 2022-08-22 at 18 53 01" src="https://user-images.githubusercontent.com/12993018/185964997-fb34e263-22f2-470f-b0f1-cda21bc4081d.png">

But if I define 2+ columns then it looks like this:
<img width="884" alt="Screenshot 2022-08-22 at 18 57 16" src="https://user-images.githubusercontent.com/12993018/185965753-f4742df7-b677-4d55-8970-ca5635b36bb9.png">

**Comment by wangly19** [comment]
Reason: In a single-column representation, first-child and last-child setting border-radius at the same time will be overridden according to priority.

I solved this problem at #684.

I offer a temporary solution.  @notmedia  

codesandbox link:  https://codesandbox.io/s/sandpack-project-forked-bmqk4i?file=/styles.css
