### ISSUE TITLE
[BUG] - Using block property on Link component throws error on browser console

### ISSUE THREAD

**Issue by buhowo** [nextui-org/nextui#680]
### Describe the bug

Using the block prop in the Link component it's throwing error on console, it seems to be a mismatch between client an server content

### Steps to Reproduce the Bug or Issue

1. Create a NextJs App 
2. Use NextJs Link component to wrap NextUI Link component as a children
3. use block prop on NextUI component

### Expected behavior

I expect none errors on console 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/19356282/185705947-c38dc9f5-db2f-4aa5-a166-5563260be6b8.png)

### Operating System Version

Linux

### Browser

Chrome

**Comment by Yukiniro** [comment]
If your nextjs's version is 13.x, you can add `legacyBehavior ` to `Link` or add `as="div"` to `NextUILink` for this problem.
```javascript
<Link href="/" legacyBehavior>
      <NextUILink color="secondary">Go to Button</NextUILink>
</Link>
```
or
```javascript
<Link href="/">
      <NextUILink as="div" color="secondary">Go to Button</NextUILink>
</Link>
```
Hope it is useful for you.

**Comment by jrgarciadev** [comment]
Hey @buhowo  sorry the delay, please upgrade to  [V2](https://nextui.org/blog/nextui-v2)
