### ISSUE TITLE
[BUG] - Module not found: Can't resolve '@react-stately/collections' using yarn PnP 

### ISSUE THREAD

**Issue by Rezaabdi78** [nextui-org/nextui#681]
### Describe the bug

I'm trying to use `@nextui-org/react 1.0.0-beta.9` with Yarn PnP but it gives me the following error:

```
Module not found: Can't resolve '@react-stately/collections' in '/app/.yarn/__virtual__/@nextui-org-react-virtual-3e83de94fb/0/cache/@nextui-org-react-npm-1.0.0-beta.9-dbg2-7352ab2338-557fcd4d23.zip/node_modules/@nextui-org/react/esm/dropdown'
```
I checked NextUI's `package.json` file and saw that the package "@react-stately/collections" is not listed in the project's dependencies:

![image](https://user-images.githubusercontent.com/52544177/185741680-492f03dc-75f4-4bfa-87de-e733a2ba0ac4.png)

Yarn PnP creates a linker file when running `yarn install` and if there is a dependency that has mistakenly not been mentioned in a package, yarn will not link it and thus causing the `import` to fail:

![image](https://user-images.githubusercontent.com/52544177/185741888-167c5d20-4c97-4583-a371-95a88e879bb2.png)

The solution is as easy as adding every direct dependency to the `package.json` file.

### Steps to Reproduce the Bug or Issue

1. Create a project with Yarn PnP enabled
2. Install `@nextui-org/react`
3. Run `yarn build`

### Expected behavior

The project is expected to be built successfully using Yarn PnP but it doesn't.

### Operating System Version

- OS: Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Rezaabdi78 this was fixed in the `v10`, https://github.com/nextui-org/nextui/pull/616

Upgrade to the `v10` and try again 🙌🏻
