### ISSUE TITLE
[Feature Request] Add 'isDisabled' prop for Tooltip component

### ISSUE THREAD

**Issue by Rezaabdi78** [nextui-org/nextui#683]
### Is your feature request related to a problem? Please describe.

I've been working with the Text component and I was thinking to show a tooltip on those texts that are truncated.

I think it would be great to enable conditional rendering for the Tooltip component. this feature will prevent code duplication and makes using the Tooltip component more friendly

for example, there is this feature in the Tooltip component Developed by `Chakra-ui` team.
check this link:
[disabling tooltip](https://chakra-ui.com/docs/components/tooltip#disabling-tooltip)

### Describe the solution you'd like

1. add a boolean `isDisabled` prop to the `Tooltip` component
2. when `isDisabled` is true when hovering over children component `Tooltip` will not pop 

### Describe alternatives you've considered

This will be solved by using conditional rendering but causes code duplications and maybe some performance issues

**Comment by wangly19** [comment]
Trying to use visible to make Tooltip controllable? 

![image](https://user-images.githubusercontent.com/45115006/185825667-da990a4a-5084-4aef-aa2f-dfa83703d03e.png)

**Comment by Rezaabdi78** [comment]
@wangly19 not gonna work. If `visible` prop is set to `true`, then the `tooltip` will be open by default. and that's not the behavior I am looking for. 

By the way thanks for your suggestion.

**Comment by wangly19** [comment]
I tried using the css display property to solve your problem.
Did I provide an example that met your expectations?

https://react-ts-uyiz8e.stackblitz.io/

**Comment by Rezaabdi78** [comment]
Thanks for the example, it is precisely what I meant by creating this issue; But the thing is if you are disabling the `Tooltip` by overriding CSS, there will still be some code executions backstage. I mean the code already running will just have a CSS ` display: none ` property added to it. 

I hope I've explained this well.

**Comment by Rezaabdi78** [comment]
@wangly19 yes that's the feature I'm talking about. Thanks for your comment
