### ISSUE TITLE
[BUG] - Icon Button width not working well with the "auto" prop

### ISSUE THREAD

**Issue by razvanilin** [nextui-org/nextui#687]
### Describe the bug

The width of buttons that only have icons without text is unpredictable when using the `auto` prop. In the example below, the width is too small and cuts the icon a bit. In my app, the `auto` prop doesn't even work (I can't reproduce it in the example).

![image](https://user-images.githubusercontent.com/5342321/186343486-7be53ab5-6e89-41dc-9827-345786da523c.png)

### Your Example Website or App

https://codesandbox.io/s/pensive-river-ee2pw3?file=/src/App.js

### Steps to Reproduce the Bug or Issue

Add a button with an icon only and the `auto` prop and see the observe the width.

```
<Button
  icon={<TickSquare />}
  color="secondary"
  onClick={() => {}}
  auto
/>
```

### Expected behavior

As a user, I'm expecting the icon button with the `auto` prop to encompass the icon with equal padding on the left and right sides of the button. Like in the documentation:

![image](https://user-images.githubusercontent.com/5342321/186343236-5419527c-df1f-47bb-9fb4-a368f0e2465c.png)

### Operating System Version

MacOS

### Browser

Chrome

**Comment by razvanilin** [comment]
As a workaround, I found that removing `auto` and adding `css={{ minWidth: "fit-content" }}` works better.

```
<Button
  icon={<TickSquare />}
  color="secondary"
  onClick={() => {}}
  css={{ minWidth: "fit-content" }}
/>
```

**Comment by Thaekeh** [comment]
Do you happen to know if an IconButton or change to this button is already being worked on?
I'd be happy to give it a go otherwise

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).

https://nextui.org/docs/components/button#icon-only
