### ISSUE TITLE
[BUG] - NextUIProvider color-scheme incorrect

### ISSUE THREAD

**Issue by jackyleefu** [nextui-org/nextui#692]
### Describe the bug

NextUIProvider: incorrect color-scheme value for style attribute of html element

### Steps to Reproduce the Bug or Issue

the problem is [nextui/packages/react/src/theme/utils.ts  getThemeName](https://github.com/nextui-org/nextui/blob/8ef205663b61f2b2c0eff6495ceac656ce5bb58e/packages/react/src/theme/utils.ts#L108) last line:
el?.setAttribute("style", clsx(prevStyles, `color-scheme: ${theme};`));
==>
el?.setAttribute("style", clsx(prevStyles, `color-scheme: ${getThemeName(theme)};`));

### Expected behavior

color-scheme: dark; OR color-scheme: light; without -theme

### Screenshots or Videos

![屏幕截图 2022-08-26 153023](https://user-images.githubusercontent.com/14267445/186847777-95f715ad-6518-4f03-9b2c-403e51810b8b.png)
![屏幕截图 2022-08-26 153237](https://user-images.githubusercontent.com/14267445/186848001-f091e472-b074-4764-9804-49468292dfb5.png)

![屏幕截图 2022-08-26 153641](https://user-images.githubusercontent.com/14267445/186848803-a89e7f12-721a-4f37-a16d-97bc1f58be56.png)

### Operating System Version

OS: Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @jackyleefu could you please create a repository/codesandbox? The `ThemeType` value its always `dark` / `light` so in theory, it should only put `color-scheme: dark/light` unless you call manually the `changeTheme` function with other theme value

**Comment by jackyleefu** [comment]
https://codesandbox.io/s/little-morning-6ub1i4?file=/src/index.js
![屏幕截图 2022-08-29 084721](https://user-images.githubusercontent.com/14267445/187102849-2e64419e-02d6-4443-b0cf-9b08fd7112f3.png)

**Comment by jackyleefu** [comment]
Hey [@jrgarciadev](https://github.com/jrgarciadev), createThemeBase() used default className(`${type}-theme`) in `stitches.config.ts`, so [useEffect in ThemeProvider](https://github.com/nextui-org/nextui/blob/10c4c25bfd39b02987631a4a888ef820710a8c8d/packages/react/src/theme/theme-provider.tsx#L84) will  changeTheme(userTheme.className);

**Comment by sun0day** [comment]
I can offer a PR @jrgarciadev
