### ISSUE TITLE
[BUG] - Navbar ShowIn & HideIn Props Swapped

### ISSUE THREAD

**Issue by kentond18** [nextui-org/nextui#695]
### Describe the bug

Currently, the props for the Navbar.Toggle at the least are switched. The hideIn acts as the showIn prop should and viceversa.

The current work around I have is using the showIn prop where I need the Navbar to Hide at, which works great, however this is not what is documented per the documentation.

I could be plainly misunderstanding the logic of the documentation, but if so, I would recommend that it be amended for clearer documentation.

### Your Example Website or App

https://github.com/kentond18/nextui-bug

### Steps to Reproduce the Bug or Issue

1. Run ```npm run dev```
2. Open in browser
3. Resize the browser
4. View ```MainNav.tsx``` and navigate to ```<Navbar.Toggle>``` component
5. See how ```showIn``` prop is set to ```sm``` and upon resizing the toggle is missing from ```md``` and up

### Expected behavior

As a user, I am expecting the toggle to be visible from the defined breakpoint and up within the ```showIn``` prop rather than hidden from 0 to defined breakpoint. Same happens if I alter this and use ```hideIn="md"```, it hides it from ```xs``` and ```sm``` and displays from ```md``` and up, rather than the opposite.

### Operating System Version

macOS 12.5.1

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
