### ISSUE TITLE
[BUG] - Mobile navbar doesn't disappear when resizing 

### ISSUE THREAD

**Issue by OGKingFox** [nextui-org/nextui#697]
### Describe the bug

If you open the mobile menu and resize the browser, the mobile menu doesn't close itself and there's no way to close it until you resize it back down and hit close button. 

### Steps to Reproduce the Bug or Issue

1. resize window so the mobile navbar is active
2. open the mobile navbar
3. resize window so it's no longer in mobile view and back to desktop

### Expected behavior

when resized while the mobile menu is open, it should hide itself

### Screenshots or Videos

https://user-images.githubusercontent.com/13415222/187007240-5c84ef28-2ea2-4325-ac2e-9035efafa791.mp4

### Operating System Version

Windows 11 22000.856

### Browser

Chrome

**Comment by sun0day** [comment]
It can be reproduced in https://nextui.org/docs/components/navbar#with-avatar-user

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2

https://nextui.org/docs/components/navbar#controlled-menu
