### ISSUE TITLE
[BUG] - Navbar doesn't render at exact breakpoints

### ISSUE THREAD

**Issue by OGKingFox** [nextui-org/nextui#698]
### Describe the bug

When at an exact breakpoint (such as 960px) nothing on the navbar renders. Not sure if this extends to other responsive elements.

### Steps to Reproduce the Bug or Issue

just resize window to an exact breakpoint, such as 960px. (Used mobile view in Chrome on Desktop via the Console, and set the size to exactly 960px)

### Expected behavior

navbar should be visible even at exact breakpoints

### Screenshots or Videos

https://user-images.githubusercontent.com/13415222/187007364-438ceeb0-a612-418b-860a-1472f1d39aa1.mp4

### Operating System Version

Windows 22000.856

### Browser

Chrome

**Comment by lhthang96** [comment]
I think this is the breakpoint problem which is reported here: https://github.com/nextui-org/nextui/issues/644#issue-1321479659.

Would be great if the team can fix this as soon as possible. Currently there is no way using grid for handling the breakpoint from 650px to 960px.

**Comment by sun0day** [comment]
Can you provide a mini-reproduction on sandbox or stackblitz? @OGKingFox

**Comment by Xariwey** [comment]
> Can you provide a mini-reproduction on sandbox or stackblitz? @OGKingFox

https://nextui.org/docs/components/navbar#with-avatar-user

There play with the size of the demo box to reproduce the bug

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2

Use `maxWidth` property: https://nextui.org/docs/components/navbar#navbar-props

**Comment by OGKingFox** [comment]
> Hey please update to v2.0 https://nextui.org/blog/nextui-v2
> 
> Use `maxWidth` property: https://nextui.org/docs/components/navbar#navbar-props

lul that response, waits until v2 is out to comment some bs lmao
