### ISSUE TITLE
[BUG] - Navbar.Link and Dropdown.Trigger abnormal

### ISSUE THREAD

**Issue by xCrazylei** [nextui-org/nextui#703]
### Describe the bug

current version 1.0.0-beta.10, An unresolvable problem occurred after the project was created, Need help...

### Steps to Reproduce the Bug or Issue

1. `Navbar.Link` There is an error: "Warning: Prop `className` did not match. Server: ...";
2. `Dropdown.Trigger` There is an error: "Unknown event handler property `onPressStart`. It will be ignored.";

### Expected behavior

I want it to work, clear the errors

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/25242674/187029870-929241b9-4973-4973-90c2-961fe19b80a2.png)

![image](https://user-images.githubusercontent.com/25242674/187030007-e4708aab-983e-4fda-8931-29dd080895e3.png)

### Operating System Version

macOS

### Browser

Chrome

**Comment by doksara** [comment]
Did anyone manage to fix this?
