### ISSUE TITLE
Report a bug button is not working

### ISSUE THREAD

**Issue by jrgarciadev** [nextui-org/nextui#71]
**Describe the bug**
The "Report a bug" button is not working on the documentation site

**Steps to reproduce**
1. Go to 'https://nextui.org/docs/components/button'
2. Click on any of the Live editors
3. Try to click on 'Report a bug'

**Expected behaviour**
It should send the user to the "Issues" project section

**Screenshots**

![Screenshot 2021-10-08 at 15 32 18](https://user-images.githubusercontent.com/30373425/136609230-92f2797c-0646-4724-8ed8-3e1657c617e3.png)

**Environment / Context**
- Desktop or Mobile?: Desktop
- Operating System: macOS
- Browser and version: Chrome last version
- Device: MacBook Pro

**Additional info**
This problem could be generated by the 'display: none' in the `editor.tsx`

**Comment by TechManos** [comment]
Hello, this seems like something I'd like to work on. Could you please assign it to me, if possible?

**Comment by jrgarciadev** [comment]
Hi @TechManos yeah for sure, thank you!

**Comment by ibrahimtelman** [comment]
Hi, If it's still open could you assign me this issue? When I look down at the project I think I found the fix.

**Comment by jrgarciadev** [comment]
Hi, @ibrahimtelman I going to assign this to you, thanks! 

@TechManos I appreciate your interest in solving this bug but since @ibrahimtelman already know the solution and the users currently can't report a bug from the website I'm reassigning it to him
