### ISSUE TITLE
[BUG] - Button text can be seen through the Navbar.Collapse menu

### ISSUE THREAD

**Issue by Some-Guyy** [nextui-org/nextui#724]
### Describe the bug

`Button` text can be seen through the `Navbar.Collapse` menu.
`Button` is also clickable even while behind the `Navbar.Collapse` menu
This bug becomes more obvious when using dark theme due to contrasting `Button` text color.
The example code I will be using comes from an example code from the [NextUI docs](https://nextui.org/docs/components/navbar) for `Navbar`, in which I only changed to dark theme and added a `Button`.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-4wkqxr?file=/Content.js

### Steps to Reproduce the Bug or Issue

1. Create a `Navbar` with the `Navbar.Toggle` to toggle the `Navbar.Collapse`.
2. Create a `Button` below the `Navbar`
3. Click the `Navbar.Toggle` to open the `Navbar.Collapse` menu
4. The `Button` text will be seen clearly under the `Navbar.Collapse` menu and is clickable, while the rest of the content will be blurred and inaccessible.

### Expected behavior

I expected the `Button` to be blurred and unclickable like the rest of the content behind the `Navbar.Collapse` menu.

### Screenshots or Videos

![Screenshot from 2022-09-01 02-16-55](https://user-images.githubusercontent.com/48655377/187753764-d3fa57a5-3a6a-4178-88d6-94a566c8958a.png)

### Operating System Version

Ubuntu 22.04 LTS

### Browser

Chrome

**Comment by sun0day** [comment]
The reason why this happens is that `nav` and `button-text` has the same `z-index:200`, and `button-text` is behind `nav` in the HTML tree. You can override `button-text` `z-index: 0` to bypass this problem. @Some-Guyy 

Isn't it weird to set `button-text` `z-index:200` as below? @jrgarciadev 

```
.nextui-button-text {
  z-index: var(--nextui-zIndices-2); // 200
}
```

**Comment by Some-Guyy** [comment]
> You can override button-text z-index: 0 to bypass this problem. @Some-Guyy

Thank you!

**Comment by FredBros** [comment]
> You can override `button-text` `z-index: 0` to bypass this problem. @Some-Guyy

Hello, could you explain me how to do that , please ?

**Comment by shekspir55** [comment]
![image](https://github.com/nextui-org/nextui/assets/8617379/0ffccb88-eb14-4919-921e-7af1f7c79bb7)

Button text and badge visible in the "sticky" navbar.

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).  

https://nextui.org/docs/components/navbar
