### ISSUE TITLE
[BUG] - Position dropdown in NavBar

### ISSUE THREAD

**Issue by FPT-NMTung** [nextui-org/nextui#730]
### Describe the bug

The drop-down menu in the Navbar is now being moved according to the site content instead of not moving.

### Your Example Website or App

https://nextui.org/docs/components/navbar#with-dropdown-menu

### Using preview in page

![image](https://user-images.githubusercontent.com/63092029/188212095-c03e3d83-7f3c-4170-9673-1a619f5f0011.png)

1. Go to [website](https://nextui.org/docs/components/navbar#with-dropdown-menu)
2. Scroll down
3. Click Dropdown
4. Scroll up

### Expected behavior

As a user, I expected `Dropdown` is kept position according to `Navbar` behavior but i am seeing `Dropdown` is kept position by content

### Screenshots or Videos

https://user-images.githubusercontent.com/63092029/188208459-487da371-5cf7-4867-8959-80c01eb6358a.mp4

### Operating System Version

Windows 11

### Browser

Edge

**Comment by sun0day** [comment]
I dont think this is a valid bug. Since the `dropdown` list container is appended in the tail of `body` and its `position` is `absolute`, it is normal for the `dropdown` to scroll with `body`.

**Comment by Clovel** [comment]
Perhaps using `position: sticky;` can be a solution.

**Comment by jrgarciadev** [comment]
Hey guys, I already sent a PR to fix this, in the meantime, you can check this [codesandbox](https://codesandbox.io/s/navbar-fixed-dropdown-4o7osb?file=/App.js) to fix it while the new version (v11) is released, thanks! 🙌🏼

**Comment by FPT-NMTung** [comment]
Hi @jrgarciadev, I check in your [preview](https://nextui-docs-git-fix730-dropdown-position-and-4276ec-nextui-org.vercel.app/) and it work but i still see the same problem when use with `Avatar` component.

![image](https://user-images.githubusercontent.com/63092029/188537802-ef4ba1f5-d884-4df8-9d42-920e4edac8a3.png)

**Comment by Xariwey** [comment]
@jrgarciadev  you solution only works for fixed navbar position it still breaks in static and in float it overlaps, at least in the codesandbox u provided
