### ISSUE TITLE
[BUG] - NextUI giving Rules of Hooks error after adding _document.js code as mentioned in NextUI documentation

### ISSUE THREAD

**Issue by badma025** [nextui-org/nextui#731]
### Describe the bug

I am following the steps to add NextUI to a project, but instead I getting the error: 

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:  
1. You might have mismatching versions of React and the renderer (such as 
React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy 
of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

after adding this code (mentioned in [NextUI](https://nextui.org/docs/guide/getting-started)) in my _document.js: 

```jsx
// pages/_document.js
import React from 'react';
import Document, { Html, Head, Main, NextScript } from 'next/document';
import { CssBaseline } from '@nextui-org/react';

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return {
      ...initialProps,
      styles: React.Children.toArray([initialProps.styles])
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>{CssBaseline.flush()}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```
I did a bit of research into this error and found out that hooks cannot be used in class components, therefore I tried to convert it from a class component to a function component (I removed the `getInitalProps()` function as it seemed to serve no relevance):

```jsx
// pages/_document.js

import React from "react";
import { Html, Head, Main, NextScript } from "next/document";
import { CssBaseline } from "@nextui-org/react";

const Document = () => {
  return (
    <Html lang="en">
      <Head>{CssBaseline.flush()}</Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
};

export default Document;
```
Despite this, I am still getting the same Rules of Hooks error as mentioned at the beginning of the issue.

### Steps to Reproduce the Bug or Issue

1. Put this in your `_app.js` file: 
```jsx
import '../styles/globals.css'
// 1. import `NextUIProvider` component
import { NextUIProvider } from '@nextui-org/react';

function MyApp({ Component, pageProps }) {
  return (
    // 2. Use at the root of your app
    <NextUIProvider>
      <Component {...pageProps} />
    </NextUIProvider>
  );
}

export default MyApp;
```
2. Put this code in your `_document.js` file
```jsx
import React from 'react';
import Document, { Html, Head, Main, NextScript } from 'next/document';
import { CssBaseline } from '@nextui-org/react';

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return {
      ...initialProps,
      styles: React.Children.toArray([initialProps.styles])
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>{CssBaseline.flush()}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

3. Put this code in your `index.js` file (a NextUI button component):
```jsx
import { Button } from "@nextui-org/react";

export default function App() {
  return <Button>Default</Button>;
}
```

You will get the same error as I mentioned at the beginning of this issue.

### Expected behavior

As a user, I expected a NextUI button component to render, but instead I am getting an error about the Rules of Hooks, 

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by turbofuture1** [comment]
### UPDATE:

I removed the code from `document.js` and NextUI worked just fine.
So now my question is:

What is the point of the code in `document.js`?

**Comment by tianenpang** [comment]
Hi @turbofuture1 the `CssBaseline.flush()` will generate all the CSS you need in order to render it server-side.

Here's an example of `pages/_document.js`

```tsx
import { Children } from 'react';
import Document, { Html, Main, Head, NextScript } from 'next/document';
import { CssBaseline } from '@nextui-org/react';

const Doc = () => {
  return (
    <Html>
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
};

Doc.getInitialProps = async (context) => {
  const initialProps = await Document.getInitialProps(context);

  return {
    ...initialProps,
    // flush here
    styles: Children.toArray([initialProps.styles, CssBaseline.flush()])
  };
};

export default Doc;
```

**Comment by jrgarciadev** [comment]
Hey please update to v2 https://nextui.org/blog/nextui-v2, this configuration is no longer needed since we moved from Stitches to TailwindCSS
