### ISSUE TITLE
[Feature Request] Max character length in Input component

### ISSUE THREAD

**Issue by New-dev0** [nextui-org/nextui#733]
### Is your feature request related to a problem? Please describe.

I want to set a character limit in Input. I can't  find the required prop in docs.
Vs code intellisense shows "maxLength", but setting it doesn't make any difference

### Describe the solution you'd like

_

### Describe alternatives you've considered

I don't know

**Comment by Hdanzo** [comment]
I can't reproduce the issue, it seems to be working for me, for both controlled and uncontrolled inputs
