### ISSUE TITLE
[BUG] - `Avatar` throwing various console errors regarding its `button` `onPress`

### ISSUE THREAD

**Issue by ndom91** [nextui-org/nextui#735]
### Describe the bug

I'm using an `Avatar` as the `Dropdown.Trigger` inside the Navbar, i.e.

```jsx
<Navbar
  isBordered={false}
  maxWidth="fluid"
  variant={'floating'}
  className="bg-none"
>
  <Navbar.Brand>
    <Avatar squared size="lg" src="/favicon.png" alt="ndo logo" />
  </Navbar.Brand>
  <Navbar.Content>
    <Dropdown placement="bottom-right">
      <Dropdown.Trigger>
        <Avatar
          bordered
          size="lg"
          squared
          zoomed
          as="button"
          color="gradient"
          src={session?.user.image ?? '/favicon.png'}
        />
      </Dropdown.Trigger>
    </Dropdown>
  </Navbar.Content>
</Navbar>
```

Upon render, I get a few error messages in the console with stack traces pointing at the `Avatar` within the `Dropdown.Trigger`. For example, using an unknown event handler like `onPressStart`. As well as a `react-aria-id` mismatch. 

I'm using the latest version of `@nextui-org/react` (`1.0.0-beta.10`), and wasn't able to find any reference to any `*press*` related code (on `main`) in the `avatar.tsx` component source code. So I'm a bit confused as to where these errors come from exactly.

Related Console Errors:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/7415984/188318379-0f226ef3-202b-43b8-a965-e3a154e1abb7.png">

<img width="802" alt="image" src="https://user-images.githubusercontent.com/7415984/188318386-85ba2e76-f7c5-491c-9a72-ef7e10494ce9.png">

<img width="802" alt="image" src="https://user-images.githubusercontent.com/7415984/188318395-f547309a-ff05-4f1d-9e81-c1cd3dbcee69.png">

### Your Example Website or App

https://ndo-so.vercel.app

Affected Code: https://github.com/ndom91/ndo.so/blob/main/src/components/nav.jsx#L46

### Steps to Reproduce the Bug or Issue

The console errors do not appear to be thrown in Prod (Vercel URL), so cloning [the project](https://github.com/ndom91/ndo.so) and running the dev server (`pnpm dev`) should reproduce it right away when visiting the `index.jsx` page.

### Expected behavior

Render without `console.error()`.

### Screenshots or Videos

See Description Above for `console.error` screenshots.

### Operating System Version

Happening in both MacOS 12.5 + Arch Linux (5.19 Kernel)

### Browser

Chrome 101, 102, 104 + Brave 1.38

**Comment by sun0day** [comment]
Seems like `react-aria` `useButton` params is conflict with `stitches` `styled.button`.

**Comment by ndom91** [comment]
Yeah I saw a 703 got fixed in `beta-10`. You're saying the same fix needs to be applied to the `Avatar` Element (or `Dropdown.Trigger`) as well?

**Comment by sun0day** [comment]
- It hasn't get fixed yet in `beta-10`
- Yes, two issues need the same fix

**Comment by ndom91** [comment]
Ah okay, apparently I misread something - thought it had gotten fixed there already.

Is there a PR or branch or anything open fixing the original `NavBar.Link` + `Dropdown.Trigger`? I'm happy to open a PR re-applying those fixes to `Avatar1l

**Comment by sun0day** [comment]
> Ah okay, apparently I misread something - thought it had gotten fixed there already.
> 
> Is there a PR or branch or anything open fixing the original `NavBar.Link` + `Dropdown.Trigger`? I'm happy to open a PR re-applying those fixes to `Avatar`

Currently there are no PRs or branches to fix these problems as I can see.
