### ISSUE TITLE
[BUG] - Components/Link

### ISSUE THREAD

**Issue by benmneb** [nextui-org/nextui#742]
### Describe the bug

The [External Link](https://nextui.org/docs/components/link#external-link) docs say 

```
Show an icon in the Link with the isExternal prop.
```

but the example doesnt actually have the `isExternal` prop in it.

![Screen Shot 2022-09-06 at 10 04 32 pm](https://user-images.githubusercontent.com/62878664/188655906-b0a9df0d-f69e-4688-8476-625beae4ea2f.png)

The prop works... it's just missing from the example. 

### Your Example Website or App

https://nextui.org/docs/components/link#external-link

### Steps to Reproduce the Bug or Issue

1. go to the docs
2. see it

### Expected behavior

show the prop!

### Operating System Version

macOS

### Browser

Firefox

**Comment by jrgarciadev** [comment]
Hey @benmneb this has been fixed, thanks for reporting it 🙏🏻

![Screenshot 2022-11-05 at 18 09 08](https://user-images.githubusercontent.com/30373425/200141402-105155e1-9e67-4d20-8fc5-5b480778ba17.png)
