### ISSUE TITLE
[BUG] - Unknown element <button> in collection.

### ISSUE THREAD

**Issue by Clovel** [nextui-org/nextui#753]
### Describe the bug

When using a simple `NextUI.Table` component, I get the following error :

![image](https://user-images.githubusercontent.com/5107774/189339925-35abf287-5fc4-44af-b36f-da488a2d2cef.png)

My page then falls back to the ErrorBoundary.

### Steps to Reproduce the Bug or Issue

Here is a CodeSandbox reproducing the error : https://codesandbox.io/s/nextui-react-18-error-tes3wg

### Expected behavior

Render the table. 

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by Clovel** [comment]
Ok, so apparently I had a rogue `<button />` component in my table. I removed it and went on to get another (perhaps unrelated) error (descibed here : #729). 

Nonetheless, the error should be more explicit. Is anything possible to make this error easier to understand ?

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2

**Comment by tchisama** [comment]
to fix it , just use "use client" in the top of the file

**Comment by halitiince** [comment]
hey @tchisama thank you for you comment, it solved my issue 👍Do you have any idea about why is this erro happening?
