### ISSUE TITLE
[BUG] Container fluid prop doesn't work

### ISSUE THREAD

**Issue by aKus-dev** [nextui-org/nextui#754]
# Description 
There is a problem with the `fluid` property of the `Container` component, the problem is that when placing this property, it does not fulfill its function of occupying 100% of the width in all the breakpoints. From 650px it stops occupying 100% of the width.

I tried the solutions said on the discord server like putting `gap={0}` but that still doesn't solve the problem.

The only solution I found is to place `css={{ mw: '100%' }}`, but of course, this should be the default behavior when placing the prop `fluid`

Finally, and this is more of a personal opinion, I think that fluid should be the default property, since in html we are used to containers occupying 100% of the width by default

## Codesandbox example

https://codesandbox.io/s/nextui-container-fluid-bug-4v9x7p

## Steps to Reproduce the Bug or Issue

1. Use the `Container` component
2. Put the `fluid` property and add some background color to see the container size
3. Resize the viewport size above 650px and see how the `fluid` property is not working

## Expected behavior

The container should have 100% width

## Screenshots or Videos

Here is a screenshot of the result when we use `fluid` prop

![Image](https://cdn.discordapp.com/attachments/886605174162989068/1017872886339469482/unknown.png)

Does not occupy 100% of the width

### Operating System Version
Windows

### Browser
Chrome

**Comment by Xariwey** [comment]
@aKus-dev

I dont know if its intended or not, maybe in the documentation example it is missing, but that is because the responsive tag is default to true a quick fix using the provided props would be to set it to false

`Container fluid responsive={false}`

but its most likely to be a bug

maybe this is a fix
main/packages/react/src/container/container.styles.ts
line-7
`variants: {
    fluid: {
      true: {
        maxWidth: "100%",
        responsive: false,
      },
`

**Comment by Farzane2630** [comment]
I`m trying to use Grid.Contaimer and it`s need to be fluid but this property doesn`t seem to exist. any solution? since Grid is a responsive-true element, above solution wo`nt work for my case.

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.

Use TailwindCSS container
