### ISSUE TITLE
[BUG] - Components/Modal

### ISSUE THREAD

**Issue by Daliens01** [nextui-org/nextui#758]
### Describe the bug

It shows a dark background instead of a translucent background 

### Steps to Reproduce the Bug or Issue

just clicking on the button to show a modal

### Expected behavior

i just wan't to know if this is a general bug or just my bad 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/102380312/189503628-6e3b5396-e180-46d2-9b1f-91f75772ff7b.png)

### Operating System Version

windows 10

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @Daliens01 could you share a codesandbox? I couldn't replicate it

**Comment by Daliens01** [comment]
i already solved. i was putting the modal code on another html render instead of the main one

**Comment by mozart25** [comment]
ya same with me
