### ISSUE TITLE
[BUG] - Clearable with rightLabel

### ISSUE THREAD

**Issue by mdragossh** [nextui-org/nextui#762]
### Describe the bug

Input with clearable and rightIcons, the clearable button is not displayed correctly.

### Steps to Reproduce the Bug or Issue

Clearable button is not display correctly with labelRight
```jsx
<Input bordered required clearable color="primary" labelPlaceholder="Email" labelRight={<User />} />
<Input.Password bordered required color="primary" labelPlaceholder="Password" />
```
<img width="295" alt="Screenshot 2022-09-13 at 13 19 23" src="https://user-images.githubusercontent.com/46487312/189877161-5a623263-053e-459d-9891-956d47fd8007.png">

### Expected behavior

Clearable button should appear left than right label.

### Screenshots or Videos

<img width="295" alt="Screenshot 2022-09-13 at 13 19 23" src="https://user-images.githubusercontent.com/46487312/189877161-5a623263-053e-459d-9891-956d47fd8007.png">

### Operating System Version

macOS

### Browser

Firefox

**Comment by yuriwithowsky** [comment]
According to the documentation, you need to use `contentRight` to display an icon. Use `labelRight` when you want to display text.

[https://nextui.org/docs/components/input#content](https://nextui.org/docs/components/input#content)

Replace to:
`<Input bordered required clearable color="primary" labelPlaceholder="Email" contentRight={<User />} />`

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

https://nextui.org/docs/components/input
