### ISSUE TITLE
[BUG] - hidden prop of Table.Pagination doesn't work

### ISSUE THREAD

**Issue by buskerone** [nextui-org/nextui#766]
### Describe the bug

`Table.Pagination` component has a prop called `hidden`. This prop should hide `Table.Pagination`, but for some reason it doesn't work and it's still visible.

e.g

```typescript
      <Table.Pagination
        noMargin
        align="center"
        rowsPerPage={rows}
        hidden
      />
```

### Steps to Reproduce the Bug or Issue

1. Create a basic table with `Table.Pagination`
2. Add the prop `hidden`
3. Check if the `Table.Pagination` is visible

### Expected behavior

`hidden` prop of `Table.Pagination` should work correctly.

### Operating System Version

macOS

### Browser

Chrome

**Comment by Sylvenas** [comment]
This is perfectly legal behavior (as per specs), maybe not expected but not a bug per se I think:

Changing the display CSS value of an element with the hidden attribute overrides the behavior. For instance, an element styled display: flex will be displayed on screen regardless of the hidden attribute being present.

NextUI:
https://github.com/nextui-org/nextui/blob/main/packages/react/src/pagination/pagination.styles.ts#L229

Relation:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute
https://lists.w3.org/Archives/Public/public-whatwg-archive/2014Apr/0094.html

**Comment by buskerone** [comment]
@Sylvenas thanks for the explanation, that makes sense. But I think what doesn't make sense is to have a prop that doesn't do the work.

There is a prop called `hideHeader` for `Table.Column`, maybe we can think of something similar for the pagination component?

**Comment by jrgarciadev** [comment]
Hey @buskerone as @Sylvenas explained the `hidden` prop comes from the `native` web API for any HTML element, Pagination doesn't include it as a prop, here's the available `Pagination` API https://nextui.org/docs/components/pagination#pagination-props

![Screen Shot 2022-09-22 at 14 47 15](https://user-images.githubusercontent.com/30373425/191816536-cfff647e-cffa-498b-a143-11022daf748e.png)
