### ISSUE TITLE
[Feature Request] Add option without custom server for NextJS

### ISSUE THREAD

**Issue by peteole** [nextui-org/nextui#767]
### Is your feature request related to a problem? Please describe.

When developing a NextJS project with nextui it is a bit annoying to use a custom server. Is this really necessary?
https://nextui.org/docs/guide/nextui-plus-nextjs

### Describe the solution you'd like

Just add the NextUI provider like in React and everything works.
Alternatively better document the custom server.

### Describe alternatives you've considered

Just don't use a custom server, from the docs I am not sure if you really need it, expecially since the nextjs example does not have a custom server.

**Comment by jrgarciadev** [comment]
Hey @peteole the custom server config is not mandatory, it is only in case you have a custom server implementation, , if you don't have a custom server implementation you should be able to use NextUI in NextJS only with this config https://nextui.org/docs/guide/nextui-plus-nextjs#next.js
