### ISSUE TITLE
[BUG] - Warning: Prop `className` did not match. Server: "nextui-c-dIWzTP

### ISSUE THREAD

**Issue by jeponkz** [nextui-org/nextui#769]
### Describe the bug

I am experiencing an error on my console log. Here's the error log

Warning: Prop `className` did not match. Server: "nextui-c-dIWzTP nextui-c-PJLV nextui-c-dIWzTP-hfnKRU-color-default nextui-c-dIWzTP-isWIbj-animated-true nextui-c-PJLV-gulvcB-isFocusVisible-false nextui-c-dIWzTP-icTVmtU-css nextui-link" Client: "nextui-c-dIWzTP nextui-c-PJLV nextui-c-dIWzTP-hfnKRU-color-default nextui-c-dIWzTP-isWIbj-animated-true nextui-c-PJLV-gulvcB-isFocusVisible-false nextui-c-dIWzTP-ifziWOk-css nextui-link"

### Steps to Reproduce the Bug or Issue

Installed Next-UI

### Expected behavior

No error should be found

### Operating System Version

macOS

### Browser

Chrome

**Comment by indiemakersid** [comment]
Hey i have the same issue, how i can fix this ?

**Comment by jeponkz** [comment]
> Hey i have the same issue, how i can fix this ?

Hi there,

I didn't manage to fix the issue. I still have it. What I did was, I used `Link` from next/link rather than '<Navbar.Link>' from nextui. 

My code goes like this

`<Navbar.Content>
<Link href="/"> Home </Link>
<Link href="/about"> About </Link>
</Navbar.Content>
`

I just added custom CSS and effect to the menu. I'm way too tired to find solution for that error, someone says that the error goes away during production build. Hope it helps. Thanks!

**Comment by affanshahid** [comment]
This is still a bug that exists.

**Comment by doksara** [comment]
Also can confirm that this bug still exists.

**Comment by TedDDDao** [comment]
Still exists.  Several nextui components are unusable due to either Hydration, or console errors in react 18.

**Comment by gauravkrp** [comment]
> Still exists. Several nextui components are unusable due to either Hydration, or console errors in react 18.

Exactly !!!

**Comment by gauravkrp** [comment]
I wonder why and how this issue was closed, the issue is still there for many of the components.
