### ISSUE TITLE
[BUG] - Navbar Width Issues

### ISSUE THREAD

**Issue by ahmad1702** [nextui-org/nextui#770]
### Describe the bug

In both Next.js and Create-react-app applications, a bug for the navbar occurs where there is a max width set by the breakpoints where it is contained. Normally, this would be fine if it's a stylistic choice, but the bottom border will only cover the width of the actual content, so a gap would be apparent to a user. I was able to fix this with a minor CSS adjustment.

`nav .nextui-navbar-container {
  width: 100% !important;
  max-width: none;
} `

### Before:

<img width="1439" alt="Screen Shot 2022-09-16 at 11 11 14 PM" src="https://user-images.githubusercontent.com/72112379/190840170-554b460f-6997-4408-8d98-d83d49758ef7.png">
<img width="1440" alt="Screen Shot 2022-09-16 at 10 10 07 PM" src="https://user-images.githubusercontent.com/72112379/190840171-4c51dd65-0bcb-4487-b42e-fc0457e9fe18.png">

### After:
<img width="1440" alt="Screen Shot 2022-09-16 at 11 12 02 PM" src="https://user-images.githubusercontent.com/72112379/190840188-8318df6f-c020-4838-a272-17342b0eb49e.png">
<img width="1440" alt="Screen Shot 2022-09-16 at 11 11 53 PM" src="https://user-images.githubusercontent.com/72112379/190840189-d564c7bf-9b12-420b-a859-294c9537eb24.png">

### Steps to Reproduce the Bug or Issue

Use Navbar component with isBordered and test with a screen width of 1440px

### Expected behavior

One would expect a bottom border of a navbar to be the full width of the screen. But instead, the max-width set on the navbar container component is constraining it

### Screenshots or Videos

<img width="1439" alt="Screen Shot 2022-09-16 at 11 11 14 PM" src="https://user-images.githubusercontent.com/72112379/190840328-5f247512-357c-4c64-a7f5-4edb47a3bbbb.png">
<img width="1440" alt="Screen Shot 2022-09-16 at 10 10 07 PM" src="https://user-images.githubusercontent.com/72112379/190840329-e0013f37-fffb-4105-8a04-d3762b105c39.png">

### Operating System Version

macOs, Windows

### Browser

Chrome

**Comment by Xariwey** [comment]
@ahmad1702 

Thats not a bug i belive, in the documentation u will find that in the navbar props theres maxWidth and it defaults to "lg", so just set it to fluid and it should fix ur issue without the need to mees with extra styles

<Navbar maxWidth="fluid" isBordered >

**Comment by ahmad1702** [comment]
That worked, guess I didn't see that option at first. Thanks for the clarification. Really like what you guys are doing with the project, works great
