### ISSUE TITLE
[BUG] - The `css` attribute produces broken styles for any entry that requires processing

### ISSUE THREAD

**Issue by zvictor** [nextui-org/nextui#774]
### Describe the bug

Applying styles according to the [media queries guide](https://nextui.org/docs/theme/media#usage) leads to broken CSS.

### Steps to Reproduce the Bug or Issue

This is the snippet I want to have applied:

```ts
<Input
  css={{
    '@xs': {
      minWidth: 430,
    },
    '@sm': {
      minWidth: 590,
    },
    '@md': {
      minWidth: 740,
    },
    '@lg': {
      minWidth: 890,
    },
  }}
/>
```

Here are the styles it generates:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/181076/190997347-e8805637-5277-4d69-868b-aa922b9c3751.png">

Needless to say, these are not valid css statements.

### Operating System Version & Browser

macOS 12.5 / Chrome

**Comment by zvictor** [comment]
I just noticed it's not only for media queries.

![image](https://user-images.githubusercontent.com/181076/191082903-b4583982-c747-4c8b-ac2a-f09f8625df35.png)

All I am doing is copying/pasting examples from the NextUI docs 🤷‍♀️

**Comment by zvictor** [comment]
This might be a problem with Nextjs.
I have faced [issues with the emotion plugin](https://github.com/vercel/next.js/issues/40091#issuecomment-1236852467) and, even though it's early for me to be sure, it looks like this issue has the same root cause.

I have commented out `nextConfig.compiler.emotion` completely and I will keep an eye to see if the problem comes back.

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.
