### ISSUE TITLE
Constant problems with node-modules to install in React Project

### ISSUE THREAD

**Issue by Cainuriel** [nextui-org/nextui#776]
### Discussed in https://github.com/nextui-org/nextui/discussions/775

<div type='discussions-op-text'>

<sup>Originally posted by **Cainuriel** September 19, 2022</sup>
There has been no way to test their attractive service.  At first I get the error ```module not found: can't resolve '@react-stately/collections ``` and I have followed your solution without success listed here:
https://github.com/nextui-org/nextui/issues/541
If I install what I am asked for I get a failure in another module:
``` node_modules/@nextui-org/react/esm/dropdown/use-dropdown.js ```

I am trying to use it in a React project, with npm version 7.24.0, node version 16.10.0 and windows 10.</div>

**Comment by TIMMLOPK** [comment]
Which version of nextui?

**Comment by jrgarciadev** [comment]
Hey @Cainuriel this issue was fixed here https://github.com/nextui-org/nextui/pull/616, please be sure you are using the latest version of NextUI `1.0.0-beta.10`, 

1. delete your `node_modules`
2. delete your `yarn.lock` / `package-lock.json`
3. upgrade the NextUI version to `v10`
4. try again 👍🏻

**Comment by Cainuriel** [comment]
> Which version of nextui?

the last.

**Comment by Cainuriel** [comment]
> Hey @Cainuriel this issue was fixed here #616, please be sure you are using the latest version of NextUI `1.0.0-beta.10`,
> 
> 1. delete your `node_modules`
> 2. delete your `yarn.lock` / `package-lock.json`
> 3. upgrade the NextUI version to `v10`
> 4. try again 👍🏻

sorry I didn't see your messages before looking for the solution I shared.

On the other hand, I take this opportunity to ask a question. 
How can I make a popover work with hover? I do not have to click to get the text. Thank you very much, I love your service.
