### ISSUE TITLE
[BUG] - You must wrap your application in an <SSRProvider> & Prop 'data-key' did not match

### ISSUE THREAD

**Issue by Kaamyab** [nextui-org/nextui#779]
### Describe the bug

The `NextUI.Table` Dynamic Table Throws an Error on Terminal (NextJS) :

`When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.`

And also a warning on Chrome DevTools :

`Warning: Prop 'data-key' did not match. Server: "row-header-column-ilm253m8gg" Client: "row-header-column-57c34tinu8f"`

### Your Example Website or App

https://codesandbox.io/s/frosty-christian-nwei79

### Steps to Reproduce the Bug or Issue

1. Go to https://nextui.org/docs/components/table#custom-cells
2. Try to use it with NextJS

### Expected behavior

I Expect No Warnings

### Screenshots or Videos

![Screenshot 2022-09-21 141003](https://user-images.githubusercontent.com/21309437/191471723-39e00533-d8c7-48a9-b873-6aa154a3fa33.png)
![Screenshot 2022-09-21 141041](https://user-images.githubusercontent.com/21309437/191471760-a90e6fa8-fa04-4a91-bacc-204c1fdf29e7.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by vizFlux** [comment]
I got the same issue too.

**Comment by jaaymes** [comment]
import { useSSR } from '@nextui-org/react'

 const { isBrowser } = useSSR()

isBrowser && (
<Component />
)

**Comment by jrgarciadev** [comment]
Hey guys, that's because you didn't wrap your application in the "NextUIProvider", please follow the installation steps:
https://nextui.org/docs/guide/getting-started#next.js

**Comment by spencerchang** [comment]
I have no idea about this even though i followed [jrgarciadev](https://github.com/jrgarciadev) said that wrap my application in the "NextUIProvider" and follow the installation steps.

But i still having 
Warning: Prop `data-key` did not match. Server: "row-header-column-eaat0e6j285" Client: "row-header-column-vk0zw265nm"

And i didn't have warning on Terminal (NextJS)

**Comment by tianenpang** [comment]
In some cases, there may be an `id` or `data-key` mismatch error, even if wrapped the app in the `NextUIProvider`, since `react-aria` does not yet support [React Strict Mode](https://reactjs.org/docs/strict-mode.html), but that doesn't mean you don't need NextUIProvider.

Under the hood, the `row-header-column` keys are [generated by `Math.random`](https://github.com/adobe/react-spectrum/blob/a009f1d27b7c9b95938b68333edc942e8f9370e7/packages/%40react-stately/table/src/TableCollection.ts#L19-L21), the reason why it causes a mismatch between server and client.

In my opinion, ignore the mismatch errors **temporarily** and wait for future updates to support it, or just render the component on the client-side, disabling the Strict Mode can be a way, but I don't recommend it. [How to disable the strict mode in Next.js?](https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode)

Refer to https://github.com/adobe/react-spectrum/issues/2231#issuecomment-1087805956.

**Comment by ekendra-nz** [comment]
I'm getting this error too even though I've wrapped my app properly:

```
      <NextUIProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </NextUIProvider>
```

**Comment by alexH56** [comment]
@jrgarciadev, I'm seeing the same issue as @ekendra-nz: my app is correctly wrapped in the NextUIProvider, yet I'm still seeing the error.

**Comment by MeloHenrique** [comment]
Same issue here. Any updates?

**Comment by CookieHax** [comment]
[Next.js 13](https://nextui.org/docs/guide/nextui-plus-nextjs#next.js-13)
Next.js 13 introduces a new app/ directory folder structure. By default it uses React Server Components. To use NextUI in those components, you need to convert them into client-side component by adding a
'use client'; at the top of your file. NextUI only works in client-side components.

**Comment by MeloHenrique** [comment]
I am using Next.js 13 however I am not using the new app/ directory folder structure.

**Comment by ekendra-nz** [comment]
same. i don't use server-side rendering or the new 'app' dir architecture.
still getting this error message in the console

**Comment by CookieHax** [comment]
Are you using client components?

**Comment by ekendra-nz** [comment]
i may need to break down endpoints and separate out everything to more
clearly define client side / server side

**Comment by MeloHenrique** [comment]
I only have a blank page with the Navbar component from NextUI. 
Running without the component there's no error, but running with the component there's an error.
I made the test without anything inside the Navbar.

**Comment by ImLunaHey** [comment]
> import { useSSR } from '@nextui-org/react'
> 
> const { isBrowser } = useSSR()
> 
> isBrowser && ( )

To the people above, this worked perfectly.

**Comment by CookieHax** [comment]
Where do I put this code?

**Comment by MeloHenrique** [comment]
> > import { useSSR } from '@nextui-org/react'
> > const { isBrowser } = useSSR()
> > isBrowser && ( )
> 
> To the people above, this worked perfectly.

That worked, thanks!

**Comment by delaencina** [comment]
Add in _app.tsx
´´´
import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import { NextUIProvider } from '@nextui-org/react';
import { darkTheme } from '@/themes';
import { useSSR } from '@nextui-org/react'

export default function App({ Component, pageProps }: AppProps) {
  const { isBrowser } = useSSR()
  return(
    isBrowser && (
      <NextUIProvider theme={darkTheme}>
        <Component {...pageProps} />
      </NextUIProvider>
    )
  )
}

´´´

**Comment by CookieHax** [comment]
Worked!

**Comment by bj0rn1** [comment]
I am using Next.js 13 and the new app/directory folder structure and i have this same issue, even after "use client". In my case, there is no __app.tsx_ to wrap the provider to.

**Comment by mrjomp** [comment]
I think this issue should be reopened as no real fix was created for handling it

**Comment by MeloHenrique** [comment]
I am not sure but NextUI only works with client side rendering. Is it possible that one or more components of the page is rendering server-side? (Not sure if it’s possible)

**Comment by Ishan-sa** [comment]
> > import { useSSR } from '@nextui-org/react'
> > const { isBrowser } = useSSR()
> > isBrowser && ( )
> 
> To the people above, this worked perfectly.

perfect, thank you so much!

**Comment by depyronick** [comment]
> 

this disables server-side rendering

**Comment by st4ng** [comment]
Seems to be a dependency issue. NextUI has `@react-aria/ssr` locked to  `3.3.0`, but some of the other @react-aria packages depend on `^3.4.1`. Therefore multiple versions are installed.

![image](https://user-images.githubusercontent.com/76733377/224503952-d912e6d3-696b-41fc-b23f-bbff3eccb445.png)

**I fixed it by adding the following to my package.json:**

```
"resolutions": {
    "@react-aria/ssr": "^3.4.1"
  }
```

**Comment by ashbuilds** [comment]
How to use `NextUIProvider` in `layout.tsx` with SSR?

**Comment by peterhijma** [comment]
> > Add in _app.tsx
> > ```
> > import '@/styles/globals.css'
> > import type { AppProps } from 'next/app'
> > import { NextUIProvider } from '@nextui-org/react';
> > import { darkTheme } from '@/themes';
> > import { useSSR } from '@nextui-org/react'
> > 
> > export default function App({ Component, pageProps }: AppProps) {
> >   const { isBrowser } = useSSR()
> >   return(
> >     isBrowser && (
> >       <NextUIProvider theme={darkTheme}>
> >         <Component {...pageProps} />
> >       </NextUIProvider>
> >     )
> >   )
> > }
> > ```
> 
> This will disable SSR.
> 
> You should use this conditional `isBrowser` only on the offending component. Comment out segments and drill down to where it is.
> 
> This is a workaround until we get v2 🪩

I use v2, but still got this error using https://nextui.org/docs/components/table#custom-styles. (using Remix)

**Comment by stasnocap** [comment]
> I use v2, but still got this error using https://nextui.org/docs/components/table#custom-styles. (using Remix)
> 
> Problem disappears if I remove `selectionMode="multiple"` from the table.

Same! But with nextjs

**Comment by ftsmasaki** [comment]
I have same issue, but I can't use the way that wrap with `useSSR()` on v2.
How can I solve this problem?

**Comment by seb350** [comment]
This happens because there's a mismatch between the server-rendered content and the client-side rendered content, specifically the data-key.

Since NextUI needs "use client" anyway, both your custom Table compoenent and the NextThemesProvider component can be imported using next/dynamic and disable SSR completely.

**This:**
`import TableX from './components/Table';`
`import { ThemeProvider as NextThemesProvider } from "next-themes";`

**To this:**
`const TableX = dynamic(
  () => import('./components/Table'),
  { ssr: false }
);`
`const NextThemesProvider = dynamic(
  () => import('next-themes').then((mod) => mod.ThemeProvider),
  { ssr: false }
);`

Then use as imported normally.

**Comment by ebokoo** [comment]
> This happens because there's a mismatch between the server-rendered content and the client-side rendered content, specifically the data-key.
> 
> Since NextUI needs "use client" anyway, both your custom Table compoenent and the NextThemesProvider component can be imported using next/dynamic and disable SSR completely.
> 
> **This:** `import TableX from './components/Table';` `import { ThemeProvider as NextThemesProvider } from "next-themes";`
> 
> **To this:** `const TableX = dynamic( () => import('./components/Table'), { ssr: false } );` `const NextThemesProvider = dynamic( () => import('next-themes').then((mod) => mod.ThemeProvider), { ssr: false } );`
> 
> Then use as imported normally.

worked thanks

**Comment by Cainier** [comment]
### solution

https://github.com/nextui-org/nextui/issues/1729#issuecomment-2115392407
