### ISSUE TITLE
[BUG] - Components/Table

### ISSUE THREAD

**Issue by AVER343** [nextui-org/nextui#784]
### Describe the bug

 ```
const renderCell = (user: UserType, columnKey: React.Key) => {
    const cellValue = user[columnKey];
```
React.Key cannot be used , we need to replace it with  ```keyof UserType```
eventual result being
```
const renderCell = (user: UserType, columnKey: keyof UserType | 'actions') => {
    const cellValue = user[columnKey];
```
also adding type to columns
```
const columns: { name: string; uid: keyof UserType|"actions" }[] 
```

### Steps to Reproduce the Bug or Issue

Copy paste code to tsx

### Expected behavior

No error but getting error

### Operating System Version

VS code 

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

https://nextui.org/docs/components/table#custom-cells

**Comment by lyolkinn** [comment]
Here in 2024, implementing this example https://nextui.org/docs/components/table#custom-cells I experience the same problem. columnKey can't be definetely typed.

I type this:
` const renderCell = useCallback(
    (user: UserType, columnKey: keyof UserType) => {
      const cellValue = user[columnKey];`
and the conflict with types here:
`return (
    <Table aria-label="">
       ...
      <TableBody items={users}>
        {(item) => (
          <TableRow key={item.id}>
            {(columnKey:**Key**) => (
              <TableCell>{renderCell(item, columnKey)}</TableCell>
            )}
          </TableRow>
        )}
      </TableBody>
    </Table>
  );
}`

> Argument of type 'Key' is not assignable to parameter of type 'keyof tAggregator'.
>   Type 'string' is not assignable to type 'keyof tAggregator'.ts(2345)
> (parameter) columnKey: Key

>
