### ISSUE TITLE
[BUG] - Table pagination (Total Pages Amount) doesn't update on filtering

### ISSUE THREAD

**Issue by rumfiske** [nextui-org/nextui#789]
### Describe the bug

If you filter data inside of a table with pagination the amount of pages is not updated. Please see video for refference. The table with pagination is from the examples,

### Steps to Reproduce the Bug or Issue

Please see video

### Expected behavior

When you filter the table, the amount of pages would change, and navigate the user to the first page.

### Screenshots or Videos

[screen-capture.webm](https://user-images.githubusercontent.com/59709554/192271168-2dbacbd0-6555-41a7-9d9d-0817875df866.webm)

### Operating System Version

Windows - Chrome (Newest update 26-09-2022)

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

https://nextui.org/docs/components/table#custom-styles
