### ISSUE TITLE
[BUG] - Dropdown disableAnimation is broken

### ISSUE THREAD

**Issue by RealistKilla** [nextui-org/nextui#797]
### Describe the bug

When disableAnimation is true, the dropdown menu just doesn't show, I've tested on the site as well as within my app across Chrome and Firefox just to make sure.

### Steps to Reproduce the Bug or Issue

Add the disableAnimation attribute.

### Expected behavior

As a user I expect the dropdown menu to open up without the animation.

### Operating System Version

Windows

### Browser

Firefox

**Comment by ibrahimtelman** [comment]
Hi, The issue is not only for the Dropdown. It affects all Popover-based components when you disable animations.
