### ISSUE TITLE
[BUG] - Pagination Data Not Updated

### ISSUE THREAD

**Issue by rnkdsh** [nextui-org/nextui#798]
### Describe the bug

When I change the page using state the new data is loaded using API but it's not updated in the table. It shows blank table.

### Steps to Reproduce the Bug or Issue

1. Implemented Pagination using Table

### Expected behavior

It should show the data of the different pages. It only shows data of the first page.

### Screenshots or Videos

<img width="1397" alt="Screenshot 2022-10-04 at 8 57 44 PM" src="https://user-images.githubusercontent.com/16722278/193861221-2fa1aad0-fd5c-4f48-ada0-7b247f89f11a.png">

### Operating System Version

macOS

### Browser

Chrome

**Comment by Knorrke** [comment]
Hello,
I'd like to work on this, but it seems to be working in the docs https://nextui.org/docs/components/table#pagination
Can you share a code example where the pagination fails?

**Comment by rnkdsh** [comment]
It's working in the docs because it has static list of items.
What I want to do is on click of page 3, I want to request new data from server and show that list.
List is being fetched from server successfully, But, the data disappears like this in the table.

**Comment by affanshahid** [comment]
I have the same issue, the Table component internally does client side filtration. i.e if you render 20 items and select page 2 with 10 items per page it will show the last 10 items. There should be a way to disable this internal pagination mechanism.

**Comment by ibrahimtelman** [comment]
Hi, 

I think you should use **items** attribute of **Table.Body** component when you try to get data dynamically. In this way, I am able to show the data dynamically.

```jsx
<Table.Body
  items="{items}"
>
  {(item) => (
  <Table.Row key="{item.name}">
    {(key) =>
    <Table.Cell>{item[key]}</Table.Cell>}
  </Table.Row>
  )}
</Table.Body>
```

**Comment by rnkdsh** [comment]
Here is my implementation

```
<Table.Body items={countries}>
      {(item: Country) => (
        <Table.Row>
          {(columnKey) => (
            <Table.Cell>
              {renderCell(item, columnKey, (countryId) => {
                setSelectedCountry(countryId);
                setVisible(true);
              })}
            </Table.Cell>
          )}
        </Table.Row>
      )}
</Table.Body>
```

**Comment by Xariwey** [comment]
did u try using this method

https://nextui.org/docs/components/table#infinity-pagination

**Comment by Knorrke** [comment]
I think I found the issue, the `TableContext` doesn't update when `collection` prop updates. Will create a pull request.

**Comment by affanshahid** [comment]
Currently the only workaround I see is to put a key on the table itself so it re-renders when the data is changed. This is far from ideal.

**Comment by CarolSum** [comment]
您好，邮件已收到。

**Comment by carlosriveroib** [comment]
this still happens to me in beta.12

could you upload one example using react-query

thank you very much

**Comment by CarolSum** [comment]
您好，邮件已收到。

**Comment by Knorrke** [comment]
Hello @carlosriveroib
the storybook contains an example with `Table.Pagination`, does that work for you? https://github.com/nextui-org/nextui/blob/93a92340f367d0bf66ccda70c32ab2f4a071e680/packages/react/src/table/table.stories.tsx#L347-L416

**Comment by TrishBhakatPG** [comment]
Still this issue persists.

**Comment by CarolSum** [comment]
您好，邮件已收到。

**Comment by JanKrb** [comment]
> Hi again, sorry for request a example with react-query, I don't need the example.
> 
> I update my last comment
> 
> It's not working if I use `<Table.Pagination />` but if I use `<Pagination />` component outside table it is working

Issue with Table.Pagination still persists. Regular pagination component is working as expected.

**Comment by CarolSum** [comment]
您好，邮件已收到。
