### ISSUE TITLE
[Feature Request] YOUR_FEATURE_TITLE_HERE_REPLACE_ME

### ISSUE THREAD

**Issue by modyabhi** [nextui-org/nextui#802]
### Is your feature request related to a problem? Please describe.

The problem is sometimes drop downs can have a lot of items, react-select provides a searchable experience which totally enhances user experience. 

### Describe the solution you'd like

On drop down open a searchable text area with the selection filtering with each key stroke.

### Describe alternatives you've considered

react-select

**Comment by khashayarghajar** [comment]
@modyabhi pls add title to your feature request
