### ISSUE TITLE
[BUG] - Navbar styling issue on Firefox

### ISSUE THREAD

**Issue by Rainnny7** [nextui-org/nextui#803]
### Describe the bug

Styling on the navbar is a bit broken on the Firefox browser - It seems to be only Firefox, however you may be able to replicate this issue on other browsers.

Active variants cause navbar items to merge into one (The only variants that work are: default, underline, and underline-rounded).
Buttons on the navbar also seem to fall off of the navbar (E.g: the "Sign Up" button on the example page).

You can see this issue by simply going to the navbar component page on the official website using Firefox (https://nextui.org/docs/components/navbar)

### Your Example Website or App

https://nextui.org/docs/components/navbar

### Steps to Reproduce the Bug or Issue

1. Go to the official navbar component page on the website
2. See the issue

### Expected behavior

The expected outcome would be for the navbar to act the same on all browsers

### Screenshots or Videos

https://user-images.githubusercontent.com/32585528/194543877-61f1f378-f953-4286-a6ea-e4a633b5a836.mp4
![OKQLsXYUFk](https://user-images.githubusercontent.com/32585528/194544066-89b4c823-b05d-49f6-9947-a72dfce07ce1.png)

### Operating System Version

Linux (Manjaro)

### Browser

Firefox

**Comment by okNick36** [comment]
I’ve had this same issue using a Firefox browser on both Windows 10 and 11.

**Comment by AloeDev** [comment]
I have the same problem on firefox.

**Comment by Rainnny7** [comment]
Resolved this issue using _content-box,_ however it's still an issue in NextUI nonetheless
