### ISSUE TITLE
[BUG] - Remix + NextUI navigating back after a 404 removes all styles

### ISSUE THREAD

**Issue by affanshahid** [nextui-org/nextui#806]
### Describe the bug

I am using Remix with NextUI and have customized the root file as shown in the example. If I click on a link to page that doesn't exist I get a 404 from the Remix server as expected, however if I click on the browser's back button to go to the previous page, when that page loads all NextUI components are completely unstyled.

### Steps to Reproduce the Bug or Issue

1. Create a Remix app
2. Add NextUI
3. Create a route that uses NextUI
4. Add a Link to a route that doesn't exist
5. Click the above link
6. Press the browser back button

### Expected behavior

I expected to see the page I navigated from rendered normally, however I am seeing a page without any styles

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.
