### ISSUE TITLE
[BUG] - INPUT NOT UPDATING VALUES

### ISSUE THREAD

**Issue by Sharpmind015** [nextui-org/nextui#814]
### Describe the bug

I created an input component, and I'm trying to update the value with react's useState once the onChange event fires, the state is being updated but it's not reflecting on the input component. 

### Steps to Reproduce the Bug or Issue

1. Create a state `const [amountOne, setAmountOne] = useState<string>("0.0");`
2. Create a next-ui input component and update `amountOne` state in `onChange` event ```<Input id="amountOne" placeholder="0.0" onChange={(e) => { if(isNaN(Number(e.target.value))) return; setAmountOne(e.target.value); }} value={amountOne} initialValue={amountOne} aria-label="First token input"/>```

### Expected behavior

I expect the input to be binded to my state, so whatever is it in my state should reflect as the value in the input

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/36773145/195212014-36f23c2d-8e70-4143-9729-1e98f8e061d0.png)
![image](https://user-images.githubusercontent.com/36773145/195212074-ecb0af8e-0ab4-4225-8840-236ada90ca0f.png)

### Operating System Version

Windows

### Browser

Chrome

**Comment by nooikko** [comment]
Reviewed, created codesandbox for testing based on instructions provided.
Link:
https://codesandbox.io/s/cool-raman-1brx3z?file=/pages/index.jsx

Result:
Unable to replicate.

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).
