### ISSUE TITLE
[Feature Request] Box component for HTML Div tag!

### ISSUE THREAD

**Issue by siamahnaf198** [nextui-org/nextui#818]
### Is your feature request related to a problem? Please describe.

For perfect web design we need html div tag. But in Next Ui there haven't any Box Componet for HTML div tag. If we use html div tag we can't add css props in this tag. That's why we need Box component for css-in-js styles (css props).

### Describe the solution you'd like

Just add Box component without giving heavy styling. Just keep it simple for any customization.

### Describe alternatives you've considered

No alternative

**Comment by siamahnaf198** [comment]
Any update.

**Comment by tianenpang** [comment]
Hi @siamahnaf198 you can use `styled` to make a `Box` component at the moment.

```tsx
import { styled } from '@nextui-org/react';

export const Box = styled('div', {
  // base styles...
  // variants...
});

// usage
() => {
  return <Box css={{ ... }} />
};
```

If you are using typescript, you can import the css type from nextui.

```tsx
import type { CSS } from '@nextui-org/react';

const overrideCss: CSS = {
  bg: "$gradient"
};

// usage
() => {
  return <Box css={overrideCss} />
};
```

More about the `styled` and `css`:
- https://stitches.dev/docs/styling
- https://nextui.org/docs/theme/override-styles

**Comment by jrgarciadev** [comment]
Thanks @tianenpang 🙌🏻
