### ISSUE TITLE
[Feature Request] Clickable Badge on Popover.Trigger

### ISSUE THREAD

**Issue by parkjbdev** [nextui-org/nextui#824]
### Is your feature request related to a problem? Please describe.

Expected to work with Popover Trigger button combined with badge, but only badge was trigger-able for popover.

### Describe the solution you'd like

```tsx
<Popover>
  <Popover.Trigger>
    <Badge css={{ p: 0 }} content={4} color="error">
      <Button auto flat size="sm">
        Trigger Button
      </Button>
    </Badge>
  </Popover.Trigger>
  <Popover.Content>
  {/* Content Here */}
  </Popover.Content>
</Popover>
```

### Describe alternatives you've considered

or is there a way to trigger popover manually?

### Screenshots or Videos

<img width="81" alt="image" src="https://user-images.githubusercontent.com/65279823/195969461-630d4a1c-9e6d-419a-8b9f-17d7543babdd.png">

**Comment by Xariwey** [comment]
```js
    <Popover>
      <Popover.Trigger>
        <Button auto flat size="sm">
          <Badge content={4} color="error">
            Trigger Button
          </Badge>
        </Button>
      </Popover.Trigger>
      <Popover.Content>
        <Text css={{ p: "$10" }}>This is the content of the popover.</Text>
      </Popover.Content>
    </Popover>
```

**Comment by parkjbdev** [comment]
<img width="75" alt="image" src="https://user-images.githubusercontent.com/65279823/196018339-d20ee6c1-7855-41d9-b99c-9797414d50f8.png">
Wrapping `Badge` with `Button` cuts the badge as shown

**Comment by PatrickRNG** [comment]
Would love that feature too. In my case, I needed the normal badge text to be clickable. Or maybe a new Tag component or something.

Wrapping in a Button results in the following:
https://user-images.githubusercontent.com/25394736/196020859-f9abbd3a-26d7-4a12-bfe6-9a501fdbafaf.mov

**Comment by Xariwey** [comment]
the issue  is that the trigger is applied to the child element,  if u put bagde first u can actually trigger the popup if u click on the badge but its too small,

try to see fi using the badge offsets props its a viable solution for u to align the badge where u want it...
https://nextui.org/docs/components/badge#badge-props
horizontalOffset
verticalOffset

if not just add css={{ overflow: 'visible' }} to the button, keep in mind that u will need to set animated to false or the ripple effect will look like if ur playing the Osu!

**Comment by parkjbdev** [comment]
or Is there a way to import `usePopoverContext()` from `@nextui-org/react/popover-context`

such as

```jsx
import { Badge, Button } from "@nextui-org/react";
import { usePopoverContext} from "@nextui-org/react/popover/popover-context";

const PopoverTriggerButton = () => {
  const { state } = usePopoverContext();
  const onPress = () => state.open();

  return (
    <Badge css={{ p: 0 }} content={4} color="error">
      <Button auto flat size="sm" css={{ overflow: "visible" }} onPress={onPress}>
        Filter
      </Button>
    </Badge>
  );
};

export default PopoverTriggerButton;
```

which would allow every component to trigger popover manually

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.
