### ISSUE TITLE
[BUG] - Can't focus/type on Input when using it inside a Card with isPressable prop

### ISSUE THREAD

**Issue by PatrickRNG** [nextui-org/nextui#826]
### Describe the bug

When using the Input component inside a Card component with the `isPressable` prop, I can't focus or click on the input to type. It works without the `isPressable`. Even if I disable the animations or ripple effect it still has the problem.

```
<Card isPressable isHoverable>
  <Card.Body>
    <Input placeholder="Add Tag" size="xs" />
  </Card.Body>
</Card>
```

### Steps to Reproduce the Bug or Issue

1. Create a Card component with the `isPressable` prop
2.  Add an Input component inside it
3. Try to click/type in the Input

### Expected behavior

Expected to be able to focus/type on the input

### Screenshots or Videos

https://user-images.githubusercontent.com/25394736/196060014-384d66b8-3c2d-4cfb-939b-e331173e4325.mov

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

https://nextui.org/docs/components/card

check the `isPressable` and `allowTextSelectionOnPress` props.
