### ISSUE TITLE
[BUG] - Navbar UI/animation display error in dev environment

### ISSUE THREAD

**Issue by recallwei** [nextui-org/nextui#827]
### Describe the bug

I found a navbar UI/animation error in the dev environment but the production environment will not reproduce it. Is it my bad usage of the navbar component or some other reasons caused by Next.js SSR?
And on the screenshot, the console throws out a Next.js hydration error.

### Your Example Website or App

https://github.com/recallwei/recallwei/blob/main/web/components/Layout/Navbar/index.tsx

### Steps to Reproduce the Bug or Issue

Hover on the nav link.

### Expected behavior

The rounded background block does not move with the hovered link changed.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/62941121/196073486-f8cf00d5-eb4a-4263-b69b-7a5b49915157.png)

### Operating System Version

macOS and Windows 11

### Browser

Chrome

**Comment by recallwei** [comment]
And my production site: https://bruceworld.top

**Comment by tianenpang** [comment]
Duplicate hydration error https://github.com/nextui-org/nextui/issues/763

**Comment by recallwei** [comment]
And the bad dev experience caused by the UI bug.
The rounded background block does not move with the hovered link changed.
It always stopped at that position.

**Comment by jeponkz** [comment]
does it only happen on dev and not on production server?

**Comment by recallwei** [comment]
> does it only happen on dev and not on production server?

@jeponkz Yes, only on dev.

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
