### ISSUE TITLE
[Feature Request] Tooltip automatic position

### ISSUE THREAD

**Issue by krystxf** [nextui-org/nextui#828]
### Is your feature request related to a problem? Please describe.

Add an option (maybe when placement is not specified) that the tooltip can automatically decide to show above or under the content like the popover element does

![image](https://user-images.githubusercontent.com/48121710/196296704-89038018-3d75-484a-9980-b518e8a82fc5.png)
(tooltip on the image overflows above the screen and the content is not visible)

### Describe the solution you'd like

I expected that when the button with a tooltip is on top of the page, the tooltip will appear under the button without specifying the placement argument. And the same tooltip would appear above the button when located at the end of the page.

### Describe alternatives you've considered

Add behavior from the popover element

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.
