### ISSUE TITLE
[BUG] - e.currentTarget undefined when button is used with next/link

### ISSUE THREAD

**Issue by jndao** [nextui-org/nextui#833]
### Describe the bug

When a button is wrapped with Next/Link component for internal routing, it causes an `e.currentTarget` error.

Using the Link component as the `Button` does not suppress the error. 

Issue arose as I would like to keep the button styling without the use of the NextUi `Link` component and would want to use the Button as an `a` component for internal routing.

### Your Example Website or App

https://johndao.com

### Steps to Reproduce the Bug or Issue

Create a Next/Link component that wraps around a NextUi `Button` and set `href` to an internal route. 

### Expected behavior

No `e.currentTarget` is undefined error should be thrown by NextJS

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/51881944/196668479-37cfeadb-5f3a-4ad8-8cf1-ff8f665e1890.png)
![image](https://user-images.githubusercontent.com/51881944/196668575-95f14af3-2793-4cf3-a191-7c7711100b75.png)

### Operating System Version

Windows

### Browser

Firefox

**Comment by jndao** [comment]
Current workaround is to wrap the the `Button` with a `Link` component and adding css to disable `pointerEvents`

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.
