### ISSUE TITLE
[Feature Request] Tooltip overflows body

### ISSUE THREAD

**Issue by dpmango** [nextui-org/nextui#837]
### Is your feature request related to a problem? Please describe.

Tooltip position is not agnostic about it's position within a page, it might overflow body and become invisible / partly visible

### Describe the solution you'd like

Expecting automatic shrinks or placement change

### Describe alternatives you've considered

Would be available for workaround if `TooltipOnVisibleChange` also pass dom ref or `getBoundingClientRect` params, so it would be possible to change `placement` prop of `<Tooltip>`

### Screenshots or Videos

<img width="612" alt="tooltip" src="https://user-images.githubusercontent.com/18535792/197241129-73d028dd-bd70-43dd-892e-9ed891ad4731.png">

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates. Tooltip component was created by scratch on top of react-aria hooks
