### ISSUE TITLE
[BUG] - $$checkboxColor does not work in css property

### ISSUE THREAD

**Issue by sierra7659** [nextui-org/nextui#845]
### Describe the bug

I am trying to change the color of the checkboxes with the css property and accessing the $$checkboxColor variable, the $$checkboxBorderColor variable does work for me, but $$checkboxColor has no effect.

```jsx
<Checkbox
    value={category}
    aria-label={category.name}
    onChange={(checked) => {
    manageSelectCategory(
	    category,
	    checked
    )
    }}
    css={{
    $$checkboxBorderColor:
	    category.color,
    $$checkboxColor: category.color
    }}
    className="mr-2">
      <Text
        span
        size="$sm"
        color={category.color}>
          {category.name}
      </Text>
    </Checkbox>
```
$$checkboxBorderColor does works ✔︎
<img width="174" alt="image" src="https://user-images.githubusercontent.com/50959412/198251141-996be90d-7b25-43cd-98d2-b5ee2c496518.png">
$$checkboxColor does not works ❌
<img width="173" alt="image" src="https://user-images.githubusercontent.com/50959412/198251260-fb0050b3-1fbf-4a24-a305-cd0728e9d0a1.png">

Thank you!

### Steps to Reproduce the Bug or Issue

Use a Checkbox component and try to change $$checkboxColor variable.

### Expected behavior

Checkbox should change color

### Operating System Version

macOs Monterey

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

https://nextui.org/docs/components/checkbox
