### ISSUE TITLE
[BUG] - MD breakpoint for showIn and hideIn does not cover 1280

### ISSUE THREAD

**Issue by misterkuka** [nextui-org/nextui#847]
### Describe the bug

When using the hideIn and showIn prop for an element and setting it to "md", no element will render for 1280, seems like one of the conditions should also include "equal"

In the example below, no element will render for screen width 1280, but all works for 1279 and 1281

`       <Navbar.Brand hideIn="md">
                <Text b css={{ letterSpacing: 5, fontFamily: 'VT323, monospace', fontWeight: 900 }} >
                  DARK<FontAwesomeIcon style={{ color: 'black', background: '#fff', borderRadius: 3, padding: 3, fontSize: 22, verticalAlign: 'bottom' }} icon={faA} />
                </Text>
              </Navbar.Brand>
              <Navbar.Brand css={{ width: '100%' }} showIn={"md"}>
                <Navbar.Toggle aria-label="toggle navigation" />
                <Text b css={{
                  letterSpacing: 5, marginLeft: "auto",
                  fontFamily: 'VT323, monospace',
                  fontWeight: 900,
                  marginRight: "auto",
                  paddingRight: 40
                }} >`

### Steps to Reproduce the Bug or Issue

Use showIn and hideIn on two elements set to "md" and check the behaviour for 1280px screen

### Expected behavior

one of the elements should render

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.
