### ISSUE TITLE
Warning: Prop `className` did not match.

### ISSUE THREAD

**Issue by LeoMartinDev** [nextui-org/nextui#851]
### Describe the bug

I'm trying to use the Navbar example but following issue occurs : `Warning: Prop `className` did not match.`
Someone had the same issue but it has been closed https://github.com/nextui-org/nextui/issues/769

### Steps to Reproduce the Bug or Issue

Install NextJS with React 18, Next UI and pick one Navbar example

### Expected behavior

Expect no error

### Operating System Version

Ubuntu 20.04 WSL 2

### Browser

Chrome

**Comment by DominicWrege** [comment]
I have the same issue

**Comment by taychris** [comment]
Same issue

**Comment by arjunindia** [comment]
Same here

**Comment by gauravkrp** [comment]
I'm also facing this.

**Comment by Octillerysnacker** [comment]
It's been almost 3 weeks, will we ever receive an update?

**Comment by sFritsch09** [comment]
Same here with following versions:
react: 18.2.0
next: 13.0.4
@nextui-org/react: 1.0.0-beta.10

**Comment by jhess3** [comment]
Am also facing this issue.

**Comment by lei900** [comment]
also facing this..Any solution..?

**Comment by legshampoo** [comment]
+1
