### ISSUE TITLE
[BUG] - NextJs 13 Production Build is not progressing if we are using some NextUI components like Text.

### ISSUE THREAD

**Issue by ryadav96** [nextui-org/nextui#852]
### Describe the bug

NextJs 13 Production Build is not progressing if we are using some NextUI components like Text.

### Steps to Reproduce the Bug or Issue

Create a next 13 app
Use Text component in pages
Run production build

### Expected behavior

Production build should success.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/30411972/199596863-fc74c561-597e-4725-b241-271447bbd8af.png)

_No response_

### Operating System Version

macOs

### Browser

Chrome

**Comment by ryadav96** [comment]
for nextJs 12. Its working

**Comment by tianenpang** [comment]
Duplicate with https://github.com/nextui-org/nextui/issues/848 and refer to https://github.com/vercel/next.js/issues/42171.

**Comment by dmythro** [comment]
> Duplicate with #848 and refer to [vercel/next.js#42171](https://github.com/vercel/next.js/issues/42171).

Well, SWC bug fix did resolve this one so far, just checked and build still stuck there.

**Comment by tianenpang** [comment]
The [`v13.0.2`](https://github.com/vercel/next.js/releases/tag/v13.0.2) release seems not include this fix, please wait for the next (canary) version, currently it can be solved by disabling the `swcMinify` in [`next.config.js`](https://nextjs.org/docs/advanced-features/compiler#minification).

Link to https://github.com/vercel/next.js/issues/42483

**Comment by tianenpang** [comment]
Hey guys, it's been fixed in [next@13.0.3-canary.0](https://github.com/vercel/next.js/releases/tag/v13.0.3-canary.0), install `next@canary` and give it a try.

*The issue can be closed*
