### ISSUE TITLE
Media query can't be defined and useable to nextui componet?

### ISSUE THREAD

**Issue by siamahnaf** [nextui-org/nextui#855]
### Describe the bug

Hello, I read full documentation of nextui. Here I am not finding any media query documentation except one- https://nextui.org/docs/theme/media. Here we can see- export a media object. But how can I use it with nextui, I actually not finding documentation here. In this media can we create custom breakpoints? Where, I have to call this media object or how can I use it with next ui.

Here I am trying to use it
```
<Container xlMax>
      <Button>Hello World</Button>
</Container>
```
but `xlMax` not working.

I can see this in documentation-

```
export const media = {
  xs: `(min-width: ${defaultTokens.breakpoints.xs})`,
  sm: `(min-width: ${defaultTokens.breakpoints.sm})`,
  md: `(min-width: ${defaultTokens.breakpoints.md})`,
  lg: `(min-width: ${defaultTokens.breakpoints.lg})`,
  xl: `(min-width: ${defaultTokens.breakpoints.xl})`,
  xsMin: `(min-width: ${defaultTokens.breakpoints.xs})`,
  smMin: `(min-width: ${defaultTokens.breakpoints.sm})`,
  mdMin: `(min-width: ${defaultTokens.breakpoints.md})`,
  lgMin: `(min-width: ${defaultTokens.breakpoints.lg})`,
  xlMin: `(min-width: ${defaultTokens.breakpoints.xl})`,
  xsMax: `(max-width: ${defaultTokens.breakpoints.xs})`,
  smMax: `(max-width: ${defaultTokens.breakpoints.sm})`,
  mdMax: `(max-width: ${defaultTokens.breakpoints.md})`,
  lgMax: `(max-width: ${defaultTokens.breakpoints.lg})`,
  xlMax: `(max-width: ${defaultTokens.breakpoints.xl})`,
  motion: '(prefers-reduced-motion)',
  safari: 'not all and (min-resolution:.001dpcm)',
  hover: '(any-hover: hover)',
  dark: '(prefers-color-scheme: dark)',
  light: '(prefers-color-scheme: light)'
};
```
My question is-
1. But actually, where we should use this?
2.  Where We should call this media object?
3. Is there has many options to use custom media like as I need to define `xxxl: 2560px` 
4. Can we get better documentation about media query.
5. If there are no options to use custom breakpoints with nextui component, then how can we use custom media query for nextui component like as Grid, Container.

### Steps to Reproduce the Bug or Issue

https://github.com/siamahnaf198/nextui

### Expected behavior

Actually, I want to use some custom breakpoints as media query. Such as I need to define some style for minimum 2560 device, I need to define some style for 1980px device. But I am not finding any solution to use custom breakpoints as media query with next ui. If there are already have this feature then please document this well, otherwise you should give this feature.

### Operating System Version

Windows

### Browser

Edge

**Comment by g17628381307** [comment]
i also have this bug, i change breakpoints from createTheme fn, but, my the changed, not work , my nextUI version is `1.0.0-beta.10`

**Comment by siamahnaf198** [comment]
Any update?

**Comment by audifaxdev** [comment]
@siamahnaf198 I was able to easily make my own custom breakpoints by forking nextui project, then editing the default breakpoints https://github.com/nextui-org/nextui/blob/f85a569b4782e99124c752269867272dc91f6313/packages/react/src/theme/common.ts line 154

```
yarn install && yarn build:nextui
cd packages/react && yarn pack
//then in your project
npm i ~/path/to/package.tgz
```

I know it's not ideal, but it's an easy and quick workaround for now.

If you look at https://github.com/nextui-org/nextui/blob/f85a569b4782e99124c752269867272dc91f6313/packages/react/src/theme/stitches.config.ts

The nextui project seems to need to hold a ref to the stitches theme object which is created at lib initialization.

The feature we need would probably require quite a bit of work, I'm just getting into nextui and stitches so I can't tell.

**Comment by siamahnaf198** [comment]
It is not perfect solution. Your wat to define custom breakpoint give a lot of typescript error. It need to create this library with capable of custom breakpoint.

**Comment by jrgarciadev** [comment]
Hey please update to v2 https://nextui.org/blog/nextui-v2

https://tailwindcss.com/docs/hover-focus-and-other-states#responsive-breakpoints
