### ISSUE TITLE
[BUG] - disable tooltip hover trigger on touchscreen devices

### ISSUE THREAD

**Issue by khashayarghajar** [nextui-org/nextui#859]
### Describe the bug

disable tooltip hover trigger on touchscreen devices

### Steps to Reproduce the Bug or Issue

1. Go to browser dev-tools ( F12 or CMD + ALT + i  or CTRL + SHIFT + i )
2. Make sure activate Emulate touch events is checked 
3. Click on Toggle Device Mode icon ( CTRL / CMD + SHIFT + M )

### Expected behavior

tooltip with trigger="hover" should be disabled on touchscreen devices

### Screenshots or Videos

https://user-images.githubusercontent.com/78317297/200132268-0b7679a0-5650-40e6-b83e-8d5fe1614edd.mp4

### Operating System Version

Linux

### Browser

Chrome

**Comment by khashayarghajar** [comment]
@hamza4600 
i think you should use matchmedia "pointer" instead of breakpoints "width"
`matchMedia('(pointer:fine)').matches`

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

Tooltip component was created from scratch on top of TailwindCSS and react-aria hooks

https://nextui.org/docs/components/tooltip
