### ISSUE TITLE
[BUG] -<Text> endless production build

### ISSUE THREAD

**Issue by AivarGabd** [nextui-org/nextui#867]
### Describe the bug

next js ^13.0.2
reactStrictMode: false

run build endless 'Creating an optimized production build'

### Steps to Reproduce the Bug or Issue

add <Text> element in ur app, run build 

### Expected behavior

successful build

### Operating System Version

Windows

### Browser

Chrome

**Comment by tianenpang** [comment]
Hi @AivarGabd it has been fixed in [next@13.0.3-canary.0](https://github.com/vercel/next.js/releases/tag/v13.0.3-canary.0), install `next@canary` and build again.

*Duplicate with https://github.com/nextui-org/nextui/issues/848*
