### ISSUE TITLE
[Feature Request] Input helperText should also accept a component or react node

### ISSUE THREAD

**Issue by gauravkrp** [nextui-org/nextui#883]
### Is your feature request related to a problem? Please describe.

Recently, while using the NextUI Input component for the password field, I used `helperText` props to dynamically show error messages. But in some of my use cases, the verbose error message was longer than for a single line and helperText component in this looks very ugly. (See the screenshot attached).

I would want to be able to either use a component of my choice to pass into helperText props or have a new props `helperTextStyle` where I can pass custom stylings such as the line-height of the text. I would prefer former as it will allow me to pass customized text as well like in 2 colors or gradients. (I know, this particular example is not much of a great use-case but see the flexibility).

### Describe the solution you'd like

I expect the `helperText` to adjust accordingly with longer text. The `helperText` currently accepts only string but I want to be able to pass a `p` or `span` or even an `anchor` tag to it.

### Describe alternatives you've considered

I had to write custom CSS to force style the helperText container and string.
<img width="368" alt="Screenshot 2022-11-15 at 8 28 29 PM" src="https://user-images.githubusercontent.com/12250556/201951702-87143368-bf17-4e30-bbd8-487d6e338bbd.png">

I can also choose not to use `helperText` props and instead implement a custom solution where I can control `stylings`

### Screenshots or Videos

<img width="498" alt="Screenshot 2022-11-15 at 7 55 02 PM" src="https://user-images.githubusercontent.com/12250556/201943795-c15f13fb-dc04-4e20-9511-64c1a990e99b.png">

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

https://nextui.org/docs/components/input#with-error-message (It now receives a ReactNode) element.
