### ISSUE TITLE
[Feature Request] Button should accept a block property

### ISSUE THREAD

**Issue by gauravkrp** [nextui-org/nextui#884]
### Is your feature request related to a problem? Please describe.

I want the button component to accept a `block` property so that it spans over the entire width. This is useful in a UI where the layout is fixed and a block button would look best.

### Describe the solution you'd like

Button component should accept a `boolean` block property 

### Describe alternatives you've considered

Using `css={{ w: '100%' }}`

### Screenshots or Videos

<img width="394" alt="Screenshot 2022-11-15 at 8 12 34 PM" src="https://user-images.githubusercontent.com/12250556/201947708-6b98537f-c6e9-460a-8bb8-5a473823479e.png">

**Comment by brunostyle** [comment]
+1

**Comment by khashayarghajar** [comment]
+ 2

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.
