### ISSUE TITLE
[BUG] - Unknown element <[object Object]> in collection  in Components/Dropdown 

### ISSUE THREAD

**Issue by khashayarghajar** [nextui-org/nextui#889]
### Describe the bug

When I'm using the Dropdown component with dynamically import multiple named exports from a module in next.js 13.0.0, I'm getting this error `Unknown element <[object Object]> in collection` .

### Your Example Website or App

https://github.com/vercel/next.js/discussions/13139

### Steps to Reproduce the Bug or Issue

1 :  `import dynamic from "next/dynamic";`

![Screenshot from 2022-11-16 10-51-40](https://user-images.githubusercontent.com/78317297/202268520-167938e8-46ca-4289-9339-a717e8911e82.png)

2 :  `const { name }  = { name: dynamic(() => import("@nextui-org/react").then(module => module.name))};`

![Screenshot from 2022-11-16 10-52-10](https://user-images.githubusercontent.com/78317297/202268534-bc249359-cca8-4f27-bac9-e2f968dde33c.png)

3 : `<Dropdown> { code } </Dropdown>`

![Screenshot from 2022-11-16 10-52-32](https://user-images.githubusercontent.com/78317297/202268543-5a368c5a-584e-4c3b-9cee-4059f571063e.png)

4 : Click on trigger button

 
![Screenshot from 2022-11-16 10-53-45](https://user-images.githubusercontent.com/78317297/202268568-14bbc7e4-154d-4c1c-aecc-250f48c723fa.png)

### Expected behavior

reference to Describe the bug section

### Screenshots or Videos

reference to Steps to Reproduce the Bug or Issue section

### Operating System Version

Linux

### Browser

Firefox

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

**Comment by nurullah** [comment]
> Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

I got same error with [next-app-template](https://github.com/nextui-org/next-app-template). Should I use `use client` for the dropdown component?

**Comment by jrgarciadev** [comment]
Hey @nurullah we're checking this with react-aria team, please use `use client` on top of the file in the meantime
