### ISSUE TITLE
[BUG] - Table: lined property not working

### ISSUE THREAD

**Issue by Guilledorfman** [nextui-org/nextui#890]
### Describe the bug

The lined property of the table is not working anymore since I upgraded to the new version, even on the examples of the documentation

### Steps to Reproduce the Bug or Issue

Make a table with lined property

### Expected behavior

This was working well on previous versions

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

Lined tables were removed though
