### ISSUE TITLE
[Feature Request] Col should accept props for breakpoints to make it responsive

### ISSUE THREAD

**Issue by gauravkrp** [nextui-org/nextui#891]
### Is your feature request related to a problem? Please describe.

I want Columns (`Col`) to spread fully on smaller width and customizable via props on larger width, just like how `bootstrap` and other libraries/frameworks such as `antd` works.

### Describe the solution you'd like

As a user, I would want to be able to use Col components as `<Col span={{ md: 4, sm: 6, lg: 3 }} />`

### Describe alternatives you've considered

Not using `Col` for now in my app, instead using `tailwindcs` to control the width on breakpoints.

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

https://tailwindcss.com/docs/columns
https://tailwindcss.com/docs/flex
https://tailwindcss.com/docs/grid-template-columns
