### ISSUE TITLE
[BUG] - Particular Cell value not updating when react state updates

### ISSUE THREAD

**Issue by sudeepjhs** [nextui-org/nextui#892]
### Describe the bug

Consider a state having array of object. When I update single object key value of that state and passing into table body it's not updating. 

### Steps to Reproduce the Bug or Issue

 const [rowdata, setRowData] = useState([ {
    "id": 1,
    "name": "xyz",
    "count": 500,
    "status": true
},{
    "id": 2,
    "name": "abc",
    "count": 12,
    "status": true
}, ]);

<Table.Body items={rowdata}>
        {(item) =>
          console.log(item) && (
            <Table.Row>
              {(columnKey) => (
                <Table.Cell>{renderCell(item, columnKey)}</Table.Cell>
              )}
            </Table.Row>
          )
        }
      </Table.Body>

**Note -> consider renderCell as a props function** 

Now try to update the the count from 500 to 502, As a result state got update but table body does'nt.

### Expected behavior

As a user, if we update the state connected to table body items, then it should be re-render 

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please update to v2.0 https://nextui.org/blog/nextui-v2 due to v1 will not receive more updates.

https://nextui.org/docs/components/table#use-case-example

**Comment by rosortoa** [comment]
I'm on v2 and is still happening
