### ISSUE TITLE
[Feature Request] Add possibility to change texts colors in User component

### ISSUE THREAD

**Issue by nonam4** [nextui-org/nextui#893]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

When adding an User component to screen I want to be able to pass 'textColor' or 'descColor' as props and this will change the default color

### Describe alternatives you've considered

-

**Comment by Danjavia** [comment]
+1

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).

Now you can use the `classNames` property to change any slot styles of the component. https://nextui.org/docs/components/user#slots
