### ISSUE TITLE
[Feature Request] Navbar Collapse Icon change

### ISSUE THREAD

**Issue by dialformonkey** [nextui-org/nextui#894]
### Is your feature request related to a problem? Please describe.

Hi. Looking for a solution to use custom icons for the navbar.collapse icon. I notice that it is currently using two spans to create it. However it would be helpful if there was a way to override this default.

### Describe the solution you'd like

Ideally if we could pass an svg icon or a lottiefiles animation as a prop it would be great.

### Describe alternatives you've considered

No alternatives have been considered other than recreating a navbar.

**Comment by jrgarciadev** [comment]
Hey @dialformonkey this feature is already implemented, you can use the `Navbar.Toggle` component and change its children: https://nextui.org/docs/components/navbar#navbar.toggle-props
