### ISSUE TITLE
[BUG] - Components/Input

### ISSUE THREAD

**Issue by Xariwey** [nextui-org/nextui#897]
### Describe the bug

when passing reset  from useInput, to  onClearClick it sould reset the input value to its initialvalue

using reset from other means works fine

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-in2181?file=/App.js

### Steps to Reproduce the Bug or Issue

```js
const { value, reset, bindings } = useInput('initial value') // Initial value here works with reset

<Input
	{...bindings}
	type="text"
	label={`-> ${value}`}
	initialValue="Initial Value" // initial value here dsnt work with reset
	clearable
	onClearClick={reset} // reset here dosnt work
/>
```

### Expected behavior

i would expect that onClearClick={reset}  will restore the value to its initial state and not setting it as empty string ""

### Operating System Version

Windows

### Browser

Chrome

**Comment by Yukiniro** [comment]
```javascript
const clearHandler = (event: React.MouseEvent<HTMLButtonElement>) => {
      event.preventDefault();
      event.stopPropagation();
      event.nativeEvent.stopImmediatePropagation();

      isControlledComponent || setSelfValue("");
      onClearClick && onClearClick(event);
      /* istanbul ignore next */
      if (!inputRef.current) return;

      const changeEvent = simulateChangeEvent(inputRef.current, event);

      changeEvent.target.value = "";
      onChange && onChange(changeEvent);
      inputRef.current.focus();
    };
```
`changeEvent.target.value = ""` will invoke after the `onClearClick`. I am not sure if this is intentional.

It can be done asynchronously without changing the source code. Here is a demo.
https://codesandbox.io/s/sandpack-project-forked-dtlh6v?file=/App.js

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay, please update to [V2](https://nextui.org/blog/nextui-v2)

https://nextui.org/docs/components/input
