### ISSUE TITLE
[Feature Request] Expose ref for use along with react hook form library

### ISSUE THREAD

**Issue by xegulon** [nextui-org/nextui#909]
### Is your feature request related to a problem? Please describe.

I'm using the the checkbox like this :

```jsx
({ label, name }) => (
    <Controller
        key={label}
        control={control}
        {...register(name)}
        render={({ field }) => (
            <Checkbox
                {...field}
                label={label}
                isDisabled={isCheckboxDisabled(
                    name
                )}
            />
        )}
    />
)                                      
```

But I get this error: https://github.com/react-hook-form/react-hook-form/issues/85

I think the problem comes from the fact the ref of the component is not accessible.

### Describe the solution you'd like

Make the components' refs accessible for use with other libraries.

### Describe alternatives you've considered

None.

**Comment by Hdanzo** [comment]
The Checkbox component does expose a ref, though, you can see it here:
https://github.com/nextui-org/nextui/blob/f85a569b4782e99124c752269867272dc91f6313/packages/react/src/checkbox/checkbox.tsx#L48

Maybe you can share your whole code to get a better picture of what your problem is.

**Comment by jrgarciadev** [comment]
Hey @xegulon as @Hdanzo the checkbox ref is available and work without problem, here's and example: 
https://codesandbox.io/s/nextui-react-hook-form-ekesj8?file=/src/index.js

**Comment by LucaDiba** [comment]
Hi @jrgarciadev, it looks like the `TableBody` component does not have a `ref` prop.

```
Property 'ref' does not exist on type 'IntrinsicAttributes & TableBodyProps<unknown>'
```

Should I open a new issue for this?
I think this could fall under this issue given the generic title and description (it refers to components in general, not to the checkbox specifically).

Thanks.
