### ISSUE TITLE
[BUG] - remix.run input rendering

### ISSUE THREAD

**Issue by PR0F1L3R1** [nextui-org/nextui#910]
### Describe the bug

when using `<Input />` in remix.run getting this errors 
![image](https://user-images.githubusercontent.com/40261445/203582230-abcd526f-f56d-4f63-9c9f-2ca933e057bb.png)

### Steps to Reproduce the Bug or Issue

1. Download 'https://github.com/nextui-org/nextui/tree/main/examples/create-remix-app' example
2. `yarn`
3. Add `<Input />` to /app/routes/index.tsx

### Expected behavior

not receive errors

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey please update to v2 https://nextui.org/blog/nextui-v2, here's the remix guide https://nextui.org/docs/frameworks/remix
