### ISSUE TITLE
[BUG] - Cannot set height for table

### ISSUE THREAD

**Issue by rs-trilx** [nextui-org/nextui#926]
### Describe the bug

Hi team,
I want to set the height to limit the table height so I can scroll the table body when the data number is greater than height. But when I set height, nothing happens

### Steps to Reproduce the Bug or Issue

1. Set height
2. Nothing happens

### Expected behavior

I can set height in css attribute of Table

### Operating System Version

Linux

### Browser

Chrome

**Comment by robertn702** [comment]
It looks like the table only allows that behavior if you're using the infinity scroll functionality.

`isInfinityScroll` styles are applied when the `Table.Body` `loadingState` prop is anything other than `undefined` and `onLoadMore` is a function.

**Scroll styles**
https://github.com/nextui-org/nextui/blob/eb09f77da4de372ae7e276da663156a4e3cd324b/packages/react/src/table/table.styles.ts#L193

**Infinity scroll conditional check**
https://github.com/nextui-org/nextui/blob/5221e73207a05592227217f8e6dd5226a28eaf02/packages/react/src/table/utils.ts#L25

---
In the meantime, my workaround is this:

```jsx
const noop = () => {};

// ...

<Table.Body
  loadingState='idle'
  onLoadMore={noop}
>
{...}
</Table.Body>
```

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.
