### ISSUE TITLE
[BUG] - Components/Navbar

### ISSUE THREAD

**Issue by gregordimi** [nextui-org/nextui#928]
### Describe the bug

The navbar disappears on a small screen

### Steps to Reproduce the Bug or Issue

if you reduce the screen to mobile, there is no navbar anymore

### Expected behavior

A responsive navbar menu with submenus

### Screenshots or Videos

normal screen:

![image](https://user-images.githubusercontent.com/22796693/205077330-26a6a0b7-551d-455c-894d-da239176908f.png)

small screen:
![image](https://user-images.githubusercontent.com/22796693/205077543-43a8d368-063c-4800-a2d1-f9e7c1dc80d6.png)

### Operating System Version

macOS

### Browser

Chrome

**Comment by romainmarchand** [comment]
Hi, maybe it's a silly question but did you try removing hideIn prop?
