### ISSUE TITLE
Modal Page in docs

### ISSUE THREAD

**Issue by I-am-abdulazeez** [nextui-org/nextui#93]
**Describe the bug**
Full Screen Modal misbehaves... it open but does not come in view, until you scroll down a little

**Steps to reproduce**
1. Go to 'https://nextui.org/docs/components/modal#full-screen'
2. Click on 'Open Modal'

**Expected behaviour**
Show open Modal by default to the screen

**Comment by jrgarciadev** [comment]
Hey guys @I-am-abdulazeez @LeoBlouin @Alejandroid17, could you please try again with the latest published version (Alpha 57)?

**Comment by LeoBlouin** [comment]
> Hey guys @I-am-abdulazeez @LeoBlouin @Alejandroid17, could you please try again with the latest published version (Alpha 57)?

Hi, for me the problem is solved. Thank you !

**Comment by Alejandroid17** [comment]
> Hey guys @I-am-abdulazeez @LeoBlouin @Alejandroid17, could you please try again with the latest published version (Alpha 57)?

now works perfectly :rocket:

**Comment by I-am-abdulazeez** [comment]
Works perfectly 🚀🚀🚀
