### ISSUE TITLE
[BUG] - Customized theme is applied with a delay

### ISSUE THREAD

**Issue by romainmarchand** [nextui-org/nextui#935]
### Describe the bug

When customizing the theme with createTheme() and NextUIProvider, the type, colors (and likely other values?) are applied to components with a delay. E.g. when setting type to "dark" the page will appear with default theme and "light" type, and then "dark".

### Packages versions
  "dependencies": {
    "@nextui-org/react": "^1.0.0-beta.10",
    "eslint": "^8.29.0",
    "eslint-config-next": "^13.0.6",
    "next": "^13.0.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }

I also tried for the same result with "next": "^12.3.4", "react": "^17.0.2", "react-dom": "^17.0.2".

### Your Example Website or App

https://github.com/nextui-org/nextui/tree/main/examples/create-next-app

### Steps to Reproduce the Bug or Issue

1. Clone https://github.com/nextui-org/nextui/tree/main/examples/create-next-app
2. Update packages
3. Customize theme colors and/or switch to "dark" type following documentation's instructions (https://nextui.org/docs/theme/customize-theme)
4. Start the app
5. Refresh the page a few times to see the issue

### Expected behavior

The custom theme values are instantly applied.

### Screenshots or Videos

https://user-images.githubusercontent.com/40261761/205473196-9ced7c1c-5502-465c-bcab-ad84f482620d.mp4

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by tianenpang** [comment]
Hey @romainmarchand please try with [`next-themes`](https://nextui.org/docs/theme/dark-mode#using-next-themes).

**Comment by romainmarchand** [comment]
Hi, as stated in the original message I also tried with next 12 and had the same issue, so I don't think it is specific to next 13. However, using next-themes like suggested by @tianenpang did solve the issue, for both 12 and 13. Thanks a lot for your answers!
