### ISSUE TITLE
[Feature Request] Pagination pages as Link (<a>)

### ISSUE THREAD

**Issue by depyronick** [nextui-org/nextui#936]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

To make it SEO friendly, it would be a good idea to be able to use pagination buttons as links so that crawler can follow them.

### Describe alternatives you've considered

None.

**Comment by jrgarciadev** [comment]
Hey please update to v2 https://nextui.org/blog/nextui-v2

https://nextui.org/docs/components/pagination#custom-items
