### ISSUE TITLE
[BUG] - Components/NEXT JS NEW UPDATE 13!

### ISSUE THREAD

**Issue by dag-bag** [nextui-org/nextui#937]
### Describe the bug

after new next 13 version update,  all the components are server components they don't allow any kind context.

### Steps to Reproduce the Bug or Issue

1.Create a new Next 13 app 
2.create a new directory name app
3.create a file page.tsx and try any next ui component.

### Expected behavior

I don't expect this kind error shown me,like this kind of things not happened in tailwind ui components libraries
cause they don't need any kind of context or state providers i think this is a good library for ui.But you should also go for the tailwind css ui libraries.

### Screenshots or Videos

[https://res.cloudinary.com/hellooworkd/image/upload/v1670281177/Screenshot_2022-12-06_042754_qejdhf.png](url)

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by SerekKiri** [comment]
Error already reported in https://github.com/nextui-org/nextui/issues/849

**Comment by jrgarciadev** [comment]
Hey please update to v2 https://nextui.org/blog/nextui-v2, RSC is now supported by default.
