### ISSUE TITLE
[Feature Request] Formik Wrapper

### ISSUE THREAD

**Issue by flobaader** [nextui-org/nextui#955]
### Is your feature request related to a problem? Please describe.

Creating forms in react is still a massive pain, formik tries to fix that. For every major UI library like MUI and Chakra there already exists a custom wrapper for formik (see https://formik.org/docs/3rd-party-bindings)

Sadly no such wrapper exists for Next UI.

### Describe the solution you'd like

A formik wrapper for Next UI like https://github.com/stackworx/formik-mui

### Describe alternatives you've considered

You can write the bindings yourself

**Comment by code-withAshish** [comment]
@flobaader or it can be handled the way [Chakra UI](https://chakra-ui.com/getting-started/with-formik) handles it, i mean it's quite simple to implement and can get your work done with formik

**Comment by jrgarciadev** [comment]
Hey @flobaader thanks for the suggestion, but you could implement the `formik` hooks, they should work correctly with NextUI 👍🏻
