### ISSUE TITLE
[BUG] - Components/Tooltip. trigger="click" doesn't work

### ISSUE THREAD

**Issue by Shakthi08** [nextui-org/nextui#968]
### Describe the bug

`<Tooltip
          content={"Developers love Next.js"}
          trigger="click" 
          color="primary"
        >
          <Link>
            <Text b color="primary">
              Click me
            </Text>
          </Link>
        </Tooltip>`

when setting the `trigger` to `click`, the tooltip isn't displayed even if clicked. `trigger="hover"` only works
the given code is copied from [https://nextui.org/docs/components/tooltip#trigger](url)
please note that the preview in that section of `trigger="click"` (in the docs) also doesn't function.

### Steps to Reproduce the Bug or Issue

1. import `@nextui-org/react` package
2. add code - `<Tooltip
                          content={"Developers love Next.js"}
                          trigger="click"
                          color="invert"
                        >
                          <Link>
                            <Text>Click</Text>
                          </Link>
                        </Tooltip>`
3. click button for tooltip to display
4. ERROR - the tooltip isnt displayed. 

### Expected behavior

expected to see tooltip when clicking button/text/image but tooltip isnt shown.

### Operating System Version

Windows

### Browser

Chrome

**Comment by joaoGabriel55** [comment]
I can take a look on that
