### ISSUE TITLE
[BUG] - Input re-renders when using useInput to  control it

### ISSUE THREAD

**Issue by ArihantBapna** [nextui-org/nextui#975]
### Describe the bug

When using the bindings property of the useInput hook to control an input, moving the cursor and attempting to type in the input causes re-renders in the input that move the cursor to the end of the line.

### Your Example Website or App

https://codesandbox.io/embed/ecstatic-nash-vezw5b?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce the Bug or Issue

Create a NextUI Input
Attach the useInput bindings to the input
Attempt to move the cursor position and type 

### Expected behavior

As a user I expect to be able to type in the input field at any cursor position and the cursor position not moving to the end of the input field

### Screenshots or Videos

https://user-images.githubusercontent.com/17776553/210118862-19747026-5432-40ca-a048-c0978186049e.mov

### Operating System Version

macOS

### Browser

Safari

**Comment by gaizkaurd** [comment]
Hello.

I am having the same bug, but using directly the **Input** component. I have faced this problem also in chrome and macOS.

**Versions**

NEXTUI BETA 11.
PREACT ^10.11.3

Thanks!

**Comment by ArihantBapna** [comment]
@gaizkaurd , a quick fix to the issue I found was to change the binding from value to defaultValue. Let me know how that works out for you

**Comment by gaizkaurd** [comment]
@ArihantBapna thank you for the early reply. Yes, it works for me. Thank you very much.

**Comment by kamami** [comment]
> @gaizkaurd , a quick fix to the issue I found was to change the binding from value to defaultValue. Let me know how that works out for you

How did you do that, any example?

**Comment by ArihantBapna** [comment]
@kamami 
Here is a quick fix example
https://codesandbox.io/s/nextui-input-rerender-quick-fix-67psrk

**Comment by kamami** [comment]
@ArihantBapna Thanks!
So we should avoid the useInput hook for now?
You example is using onChange with useState.

**Comment by ArihantBapna** [comment]
You can build your own useInput hook! But yes until #1001 is merged, avoid it.

**Comment by kamami** [comment]
I tried you solution @ArihantBapna but this does not allow me to manipulate the input value from another function. Btw. the param `defaultValue` does not exist.

**Comment by Strapontin** [comment]
> @kamami Here is a quick fix example https://codesandbox.io/s/nextui-input-rerender-quick-fix-67psrk

There is no control over the value. If I want to clear the input when I click on a button, the "defaultValue" prop won't change it.

**Comment by himrocks33** [comment]
I wrote my own hook to fix the issue.  Would be nice if they would just merge in the fix to the repo though?  Is next UI still supported?  I see a lot of open issues with no one working on them?

```
import { Input } from '@nextui-org/react'
import { useState } from 'react'

const useInput = (s: string) => {
    const [value, setValue] = useState<string>(s)
    

    return {
        value,
        setValue,
        reset: () => setValue(''),
        bindings: {
            defaultValue: value,
            onChange: (e: any) => setValue(e.target.value)
        }
    }
}

export { Input, useInput }
```
