### ISSUE TITLE
[BUG] - Dark Mode not working

### ISSUE THREAD

**Issue by SaadBazaz** [nextui-org/nextui#988]
### Describe the bug

Hi!
I'm using the latest version of nextui (`"@nextui-org/react": "^1.0.0-beta.11",`), on Google Chrome.
I want to use Dark mode only for my app, but it seems stuck at light theme.

### Steps to Reproduce the Bug or Issue

- Deleting everything in `globals.css` and `Home.module.css`
- The following variations of code:
```
import { NextUIProvider } from '@nextui-org/react';
import '../styles/globals.css';
import '../components/IsometricTrain/isometric-train.css';
import { createTheme } from '@nextui-org/react';
import { Layout } from '/components/Layout';

const darkTheme = createTheme({
  type: 'dark'
});

export default function App({ Component, pageProps }) {
  return (
    <NextUIProvider
      defaultTheme="dark"
      attribute="class"
      theme={{ type: 'dark' }}
      value={{
        light: darkTheme.className,
        dark: darkTheme.className
      }}
    >
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </NextUIProvider>
  );
}

```

### Expected behavior

Should either automatically switch to dark mode with system, or should be permanently stuck at Dark mode. Nothing happens. It just stays at light mode.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/51885228/210382487-aad6cb97-1d75-405d-a7a2-b552cd7bce13.png)

### Operating System Version

Linux

### Browser

Chrome

**Comment by tianenpang** [comment]
Hey @SaadBazaz you need to use [`next-themes`](https://github.com/pacocoursey/next-themes) together with NextUI, docs here: [Using next-themes](https://nextui.org/docs/theme/dark-mode#using-next-themes).

Example: [codesandbox.io/p/sandbox/nextui-example-d4is80](https://codesandbox.io/p/sandbox/nextui-example-d4is80).

**Comment by SaadBazaz** [comment]
@tianenpang I've tried that, doesn't work.
