### ISSUE TITLE
[BUG] - Components/Dropdown does not open for touch devices

### ISSUE THREAD

**Issue by TechnologicNick** [nextui-org/nextui#989]
### Describe the bug

Dropdowns do not open when pressed on touch devices. This happens both in Chrome 108 devtools with the device toolbar turned on, as well as Safari on iPadOS 15.7.

### Your Example Website or App

https://nextui.org/docs/components/dropdown

### Steps to Reproduce the Bug or Issue

1. Press any `Dropdown.Button` or `Dropdown.Trigger`
2. Observe the button press animation plays, but the dropdown menu does not open

### Expected behavior

As a user, I expect the dropdown menu to open, but I am seeing it not open.

### Screenshots or Videos

![chrome_agtzGQFuWJ](https://user-images.githubusercontent.com/20935774/210411271-875b8ab4-f98f-4245-afab-9b933cb25b91.gif)

### Operating System Version

Windows, iPadOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @TechnologicNick thank you for taking the time to report this issue, however, it was already reported, I encourage you check the previous issues before open a new one 🙏🏻 

https://github.com/nextui-org/nextui/issues/969

**Comment by TechnologicNick** [comment]
Ah, sorry, I must've missed it then.
