### ISSUE TITLE
[BUG] - divide style from tailwind css isn't working

### ISSUE THREAD

**Issue by ta1bbty** [nextui-org/nextui#992]
### Describe the bug

As mentioned in Issue #991 , similar to that, the `divide-y` divide style isn't getting applied properly to the elements 🤔 

I am using this example from here to make the card layout - https://flowbite.com/docs/components/card/#card-with-list
<img width="937" alt="image" src="https://user-images.githubusercontent.com/45117337/210779131-b386cc12-e307-45ea-add4-9cf433b5578c.png">

However the rendering on my device is like this : 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/45117337/210779734-134b8df0-6c79-4f9e-917b-03c123e09bee.png">

LMK if you need more inputs here 😃

I've used this in the code : 
```js
<ul role="list" className="divide-y divide-gray-700 dark:divide-gray-700">

```

### Steps to Reproduce the Bug or Issue

Setup a new project with tailwind css and add the code in the example. Sorry for brevity, please check the previous issue for full sample project #991 

### Expected behavior

There should be a visible divider between the elements.

### Operating System Version

Mac OS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay, please upgrade to [V2](https://nextui.org/blog/nextui-v2), TailwindCSS is now the default style engine
