### ISSUE TITLE
[BUG] - Input placeholder disappearing 

### ISSUE THREAD

**Issue by Jacob-Sussman** [nextui-org/nextui#993]
### Describe the bug

If you select an input that has a placeholder then <Link> the placeholder will disappear

### Steps to Reproduce the Bug or Issue

1. Select an Input with a "placeholder" field
2. Click a Link with a href that goes to another page
3. The placeholder will disappear if the page uses a shared Input component

### Expected behavior

I expected the placeholder to reappear after un-selecting the Input

### Screenshots or Videos

https://user-images.githubusercontent.com/116610914/210851140-e9df96a0-4c6f-4995-8e88-107febfe43e3.mov

### Operating System Version

macOS

### Browser

Chrome

**Comment by nooikko** [comment]
Created Code Sandbox based on replication steps, unable to reproduce.
Link:
https://codesandbox.io/s/modest-galileo-8isd79?file=/components/TestInput.jsx

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).

https://nextui.org/docs/components/input
